### ISSUE TITLE
bitmonerod: --offline flag not working 

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#1013]
It seems the --offline flag doesnt work anymore in bitmonerod. Simplewallet is unable to connect to daemon.

**how to reproduce:** 
-make sure your computer has no Internet connection (detach cable)
-launch bitmonerod --offline 
-launch simplewallet
-refresh simplewallet 

-> simplewallet will throw an Error here.

**bitmonerod has to be able to work with --offline flag when:**
-No IP has been distributed
-No Interface is installed at all

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/1031

**Comment by NanoAkron** [comment]
Who closes these issues once they've been solved?

**Comment by medusadigital** [comment]
quickly tested without cable --> worked fine.
didnt test without Network Interface

**Comment by moneromooo-monero** [comment]
NanoAkron, typically fluffypony whenever he gets to it.

**Comment by medusadigital** [comment]
long time no see, works now for some time. ---> closed
