### ISSUE TITLE
bitmonerod example for start_miner is incorrect

### ISSUE THREAD

**Issue by quanah** [monero-project/monero#1020]
Output of help is:

  start_mining         Start mining for specified address, start_mining <addr> [threads=1]

However, the format is actually
  start_mining         Start mining for specified address, start_mining <addr> [<threads>]

**Comment by JamesCullum** [comment]
Fixed in https://github.com/monero-project/bitmonero/commit/1d5ba65f3dfc498fbbfac7e00b6e434022816eaf, isnt it?

**Comment by quanah** [comment]
Yep!
