### ISSUE TITLE
Assumes name of "gcc-ar" and "gcc-ranlib" for gcc>=4.9 with lto enabled

### ISSUE THREAD

**Issue by alown** [monero-project/monero#1026]
My distribution names the compiler based upon the architecture the compiler (and related tools) are built for, so the correct version of ar to use is named $CHOST-gcc-ar (which is itself a symlink to the selected alternative) and lives under /usr/$CHOST/bin/.

Normally, I would pass this information through -DCMAKE_AR/-DCMAKE_RANLIB when running cmake, but the root CMakeLists.txt has a check which nullifies doing so around line 419 (if USE_LTO && GNU && >= 4.9.0 && NOT OPENBSD).

Removing this if section allows build.  Perhaps the best option would be to only do this if CMAKE_AR and CMAKE_RANLIB are not already passed in by the user?

**Comment by radfish** [comment]
Thanks. Would this patch work? https://github.com/radfish/bitmonero/tree/PR--cmake-chost

**Comment by alown** [comment]
resolved with #1065
