### ISSUE TITLE
[Feature Request] Simplewallet rescan_bc_from_height

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#1036]
The load command to restore from a given height is awesome.

A within wallet command to rescan from a given height would be even awesomer and would allow for epic awesomeness to rain upon the fields of glory that is Moneroland.

**Comment by iamsmooth** [comment]
This should be done as an "advanced mode" feature disabled by default or something. If you specify the wrong (too high) rescan height you will lose coins that will never be picked up by the wallet unless you rescan again.

**Comment by Gingeropolous** [comment]
The load command is all thats needed.
