### ISSUE TITLE
[Feature Request] Simplewallet upgrade_wallet

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1037]
Please consider adding a function ```upgrade_wallet``` to the next version of simple wallet to convert transactions to RingCT until the hard fork making RingCT compulsory for all transactions.

I'm happy to close this once one of the devs acknowledges they've read it.

**Comment by moneromooo-monero** [comment]
Can you describe what you mean by "convert transactions to RingCT" ?

**Comment by NanoAkron** [comment]
I guess moving my transactions to a new account through the blockchain. Now that could mean thousands of people trying to make transactions at the same time for a couple of days, but that pain would be worth it in the long run.

**Comment by moneromooo-monero** [comment]
You could use sweep_all, which... /me checks... yes, it will use rct txes. So that would use up all your (rct or not) outputs and make a rct output for you. I guess there could be a variant that only takes pre-rct outputs, that'd be easy to add.

**Comment by NanoAkron** [comment]
Thank you. Would be nice to make it as user-friendly as possible in the wallet itself, or provide a step-by-step writeup on stackexchange in time for release.

I'll close this tomorrow.
