### ISSUE TITLE
Monero still makes ~/log directory even if specific .log file specified in .conf

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1043]
Unless I'm missing something, I've got my `bitmonero.conf` (which should maybe be renamed to `monero.conf`)  looking like so:

```
log-file=./monero.log
log-level=0
p2p-bind-ip=192.168.xxx.xxx
p2p-bind-port=18080
max-concurrency=3
out-peers=64
```

Even specifying a .log file, I keep getting a /log directory containing `dr-monero` and `net` subdirectories each time. Is there a way to stop the system from creating these or trying to log to these?

**Comment by radfish** [comment]
I noticed that too. If you really don't want those files created, a workaround is to run the daemon from a working directory where it has no write access:
```
sudo mkdir /var/lib/monero
cd /var/lib/monero
./monerod
```

**Comment by NanoAkron** [comment]
:(

**Comment by Gingeropolous** [comment]
try using the ```data-dir``` command line flag instead of the logfile flag. This will put both the logfile and the block data in the same, new directory.

**Comment by NanoAkron** [comment]
I may have traced the reason to the order in which the Daemon processes args at startup. Testing this weekend.

**Comment by NanoAkron** [comment]
This should now be fixed following the inclusion of easylogger++

Will open a new issue if not
