### ISSUE TITLE
monero-wallet-cli : wrong numbers with pending transfers

### ISSUE THREAD

**Issue by schnerchi** [monero-project/monero#1054]
After sending a tx, show_transfers will show wrong numbers for the pending transaction. sometimes the shown numbers (sent amount and fee) add up to (sent amount)+fee, though not always...

tested with master commit afe3cce

**Comment by moneromooo-monero** [comment]
If you have that wallet still, please try with https://github.com/monero-project/monero/pull/1085 which I think should fix it (it does here, but just in case the patch doesn't catch all cases).

**Comment by schnerchi** [comment]
Hmm... tested it and seams to work.
