### ISSUE TITLE
Cannot no longer build using brew on OS X

### ISSUE THREAD

**Issue by peanutsformonkeys** [monero-project/monero#1059]
The instructions in README.md to build Monero using brew for OS X no longer seem to work:

```
brew tap sammy007/cryptonight
…
brew install bitmonero --build-from-source
Error: No available formula with the name "bitmonero" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

```

Is this due to the recent GitHub repository name change? I am very new to all this, it's the only thing I can think of. This worked fine on another Mac about 1 or 2 weeks ago, same OS X version, same setup.

**Comment by NanoAkron** [comment]
Hi @peanutsformonkeys is this still an issue for you or can it be closed?

**Comment by peanutsformonkeys** [comment]
I just did some tests here. I confirm I can do `brew install monero --build-from-source`. But with `brew install monero --HEAD -v` it fails at the end now:

> [ 98%] Built target simplewallet
> [100%] Linking CXX executable ../../bin/monerod
> [100%] Built target daemon
> Error: No such file or directory - ./build/release/bin/bitmonerod

No idea if that has another cause or not …

**Comment by NanoAkron** [comment]
Ah...yes, someone will have to change that.

**Comment by peanutsformonkeys** [comment]
Thanks for clarifying about `--HEAD`. Going to close the issue because `--build-from-source` works.
