### ISSUE TITLE
[Feature Request] Option to split transaction fees between miners and developers

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1060]
How about a flag in the wallet that allows us to send 50% of our transaction fee to the miners and 50% to a fixed address to fund development. It could be explicitly introduced in hard fork X, and deactivated again in hard fork Y a year later.

**Comment by perl5577** [comment]
is beautifull idea. 
Is it motivating for the dev to reduce costs transaction ?

**Comment by NanoAkron** [comment]
Well I think the next step is to make transaction fees float rather than fixed, so it shouldn't change that incentive. They don't get a split at the moment so the financial incentive to keep the fees static doesn't exist.

**Comment by moneromooo-monero** [comment]
It'd increase the tx size by a fair bit (50% more outputs on average).

**Comment by NanoAkron** [comment]
That's a shame. Is there any way that this would be possible in a post-RingCT world?

**Comment by NanoAkron** [comment]
Closing to increase the signal to noise ratio
