### ISSUE TITLE
Where to find a computation example of the monero traceable ring signature mechanism in a small finite field

### ISSUE THREAD

**Issue by eriksank** [monero-project/monero#1061]
In the following article, ["The math behind bitcoin"](http://www.coindesk.com/math-behind-bitcoin), you can find a beautiful example of the ECDSA keypair generation, signature and signature verification algorithms in use in bitcoin. They illustrate it in a finite field of order n=79, which keeps the computations manageable; even with just a calculator.

I suspect that a basic monero/cryptonote calculation example would be quite a bit longer. Still, even such longer article would be interesting to a lot of people, in order to gain a better understanding of what monero/cryptonote actually do.

Does such article exist already? (I could not find one)

If there is no elaborated exercise available, I would certainly be interested in jointly composing one, together with someone who is intimately familiar with the practical monero/cryptonote implementation.

I think that quite a few math-inclined people would be interested in pulling a calculator and repeat the computations in such article, in order to gain better insight in how it all works. It would certainly beef up confidence, and attract more early adopters to monero.

Do you know of anybody on the team who would be interested in helping out with this, by answering questions, and assisting with the composition of the exercise?

**Comment by expez** [comment]
Questions like these are better asked on the [monero stack exchange](http://monero.stackexchange.com/), or on IRC, as its only tangentially relevant to the code in this repository.

**Comment by eriksank** [comment]
Thanks for the link. I will ask the question on the monero stack exchange!
