### ISSUE TITLE
ARM hash rate greatly reduced following latest pulls

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1069]
Aloha!

Prior to the latest set of pulls, my little ARMv8 box was managing 8H/sec (dizzying, I know). However, now it can only do 2H/s.

@radfish Maybe something related to #1049?

**Comment by iamsmooth** [comment]
Is yours running in 64 bit? It is possible that the arm asm mul code (reenabled by #1049) is worse than what the compiler generates on 64 bit. If so the asm code should only be enabled on 32-bit arm, not all arm.

**Comment by radfish** [comment]
@NanoAkron.. could you please run an experiment for comaprison by invoking cmake with `-DNO_OPTIMIZED_MULTIPLY_ON_ARM=ON` and holding all else constant?

**Comment by NanoAkron** [comment]
Hi @radfish, so I did
```cmake -DNO_OPTIMIZED_MULTIPLY_ON_ARM=ON``` followed by ```make``` but the binary it produced crashed. Was this the right way to do what you were asking, or should I have done ```make release```?

**Comment by radfish** [comment]
Yes, just to make sure (assuming your slow-hash-rate build was from `make release`):

    cd monero
    mkdir build-no-asmmul && cd build-noasmmul
    cmake -DNO_OPTIMIZED_MULTIPLY_ON_ARM=ON ..
    make
    ./bin/monerod

Without the optimized asm code, the build should be the same as before #1049. If you successfully built and ran before #1049, then this crash you are getting now is probably unrelated. In any case, might be worth running with gdb to get a stack trace, to document this crash.

**Comment by NanoAkron** [comment]
Just an interim report - have pulled in #1077 which has doubled the hash rate from 2 to 4H/s...but this is still less than half the hash rate I was getting before #1049 :(

Will test properly later tonight.

**Comment by NanoAkron** [comment]
Have just tried with ```cmake -DNO_OPTIMIZED_MULTIPLY_ON_ARM=ON ..``` but sadly no change - hash rate still 4H/s

I wonder whether we need to change the compile flags in CMakeLists.txt now that @hyc has added the custom AES code. Will investigate later.

**Comment by hyc** [comment]
Before my patch in master, ARMv8 was using the generic C code. After #1077 , ARMv8 uses the ARM-specific code. Also, the NO_OPTIMIZED_MULTIPLY_ON_ARM flag only affects ARMv7/ARMv6.

**Comment by NanoAkron** [comment]
:(

**Comment by hyc** [comment]
eh? With #1077 The ARMv8 code always uses fast multiply.

**Comment by NanoAkron** [comment]
So why am I only seeing 4H/sec when I used to get 8H/sec with the vanilla version?

Do you know how I can roll back to about #1041 and then just pull in #1077 to test it out?

**Comment by NanoAkron** [comment]
Increasing the thread count does push the mining rate up above where it was before. I may have done something silly here, but I'm going to try adjusting gcc -mtune because I was running a fully customised version before.

**Comment by NanoAkron** [comment]
I'm going to close this. My has rate is now at 14/sec with the new ASM code and compiling with +crypto, was at 11-12 without +crypto. Have submitted #1088.
