### ISSUE TITLE
When running simplewallet with --wallet-file flag, the check whether the file exists is done after asking user for the password

### ISSUE THREAD

**Issue by JollyMort** [monero-project/monero#1071]
C&p of command prompt below. System: Windows 7 x64. Version: monero.win.x64.v0-9-4-0

I believe it would make sense to check for the file first, before asking the user for the password.

```
C:\monero.win.x64.v0-9-4-0>simplewallet --wallet-file test
Creating the logger system
Monero 'Hydrogen Helix' (v0.9.4.0-release)
Logging at log level 0 to C:\monero.win.x64.v0-9-4-0\simplewallet.log
password: ****
Error: failed to load wallet: file not found "test.keys"
```

**Comment by moneromooo-monero** [comment]
Is the problem just wasted work (inputting a password), or something else ?

**Comment by JollyMort** [comment]
Yeah only that, just an user experience thing.

**Comment by JollyMort** [comment]
i think this is about to fix it :)

https://github.com/monero-project/monero/pull/2238

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by selsta** [comment]
This is fixed in recent versions.

**Comment by dEBRUYNE-1** [comment]
+resolved
