### ISSUE TITLE
Testnet Error: Failed to connect to any of seed peers, continuing without seeds

### ISSUE THREAD

**Issue by phloatingman** [monero-project/monero#1078]
I'm running Monero 'Hydrogen Helix' (v0.9.4.0-7c899ec) in a fresh Ubuntu 16.04.1 64-bit install via VirtualBox.

When I run this command...

`monero@monero:~$ '/home/monero/monero/build/release/bin/monerod' --testnet --testnet-rpc-bind-port 38081`

I get this repeating error...

`2016-Sep-15 21:55:55.582913 [P2P0]Failed to connect to any of seed peers, continuing without seeds`

I'm trying to connect monero-core gui wallet to the testnet.  Any help would be appreciated.  Thanks!

**Comment by NanoAkron** [comment]
Silly question - do you have that port open on your router?

**Comment by phloatingman** [comment]
I have port 28080 open.  When I go to http://www.canyouseeme.org/ it says it can successfully see the service.  

I tried running testnet on a different laptop running Windows and v0.9.4.0-release and get the same error as well.

**Comment by phloatingman** [comment]
I'm able to run other services fine on my network like http, ssh, vnc..

**Comment by NanoAkron** [comment]
Why does having port 28080 open matter when you're trying to bind port 38081?

**Comment by mbg033** [comment]
I would like to run a node connected to public testnet, but having the same issue.  Tried both on Ubuntu VPS and local windows PC, same error, it looks like remote peers just rejecting connection (tried to connect manually with "telnet remote_ip remote_port"). At the same time,  I can successfully run mainnet node on the same VPS.

**Comment by phloatingman** [comment]
I got the default ports from [here](http://monero.stackexchange.com/questions/604/what-ports-does-monero-use-rpc-p2p-etc/605)...

P2P: 18080 for the mainnet, 28080 for the testnet
RPC: 18081 for the mainnet, 28081 for the testnet

I forwarded 28080 because that's the testnet port for p2p.  

I manually set RPC to 38081 because that's the rpc port that lets my local monero-core (gui wallet) connect to testnet.  38081 doesn't need to be forwarded.

**Comment by NanoAkron** [comment]
I don't understand. How do you think the daemon connects to testnet if you're not forwarding the port you're binding to?

**Comment by moneromooo-monero** [comment]
The RPC port is different from the P2P port. You don't need the RPC port open to have incoming P2P connections (and should be able to connect to a seed node even if your P2P port is not open).
That said, I don't even know if there are seed nodes for testnet.

**Comment by phloatingman** [comment]
How does one become a public seed node for testnet?

**Comment by fluffypony** [comment]
@phloatingman we've just revised the list and removed all the dead ones. Becoming a seed node is non-trivial, because of the responsibility involved (even for testnet), so you basically need to be part of the dev community for a few months and then offer.

**Comment by phloatingman** [comment]
@fluffypony thanks for the quick reply!

Monero 'Wolfram Warptangent' (v0.10.0.0-release) seems to be working with testnet just fine now...

`Height: 7201/802057 (0.9%) on testnet, syncing, net hash 324 H/s, v1, up to date, 4+0 connections`
