### ISSUE TITLE
monero-wallet-cli: failed to load wallet: basic_string::_M_replace_aux

### ISSUE THREAD

**Issue by nthterm** [monero-project/monero#1106]
Wallet created in 0.9.4, ubuntu 16.04 pre-built binaries using simplewallet. Upon deleting db and resyncing db for 0.10.0, I tried to load old simplewallet wallet into monero-wallet-cli and got the following error:

monoero-wallet-cli error:
failed to load wallet: basic_string::_M_replace_aux

Output of monero-wallet-cli.log:
2016-Sep-19 17:42:50.714003 Loaded wallet keys file, with public address: 47YFBeAeygoec1hXHEChthVht2S8wvsFRXB1FHSsnWLi3cwQetsk1JsUq8SJCW4dzqDmVgenonRMxcw4wxm3oHrX3oVSmMM

2016-Sep-19 17:42:52.158224 Error: failed to load wallet: basic_string::_M_replace_aux

2016-Sep-19 17:42:52.183977 Error: You may want to remove the file "walletissue" and try again

2016-Sep-19 17:42:52.184036 ERROR /DISTRIBUTION-BUILD/src/simplewallet/simplewallet.cpp:1432 failed to open account

2016-Sep-19 17:42:52.184053 ERROR /DISTRIBUTION-BUILD/src/simplewallet/simplewallet.cpp:3928 Failed to initialize wallet

The issue is reproducible on my end, so I've created a test wallet that reproduces the error and can be inspected. Wallet password is the same as the wallet name: "walletissue"

wallet files: https://github.com/nthterm/monero_test_wallet

**Comment by moneroexamples** [comment]
I guess format changed. You can remove the cache file as suggested by the message, and new one should be generated after refresh.

**Comment by nthterm** [comment]
Removing the cache file as suggested and refreshing fixes the issue.

**Comment by moneromooo-monero** [comment]
With boost versions are 0.9.4 and 0.10.0 using ? ldd bitmonerod will tell you.

**Comment by nthterm** [comment]
Will confirm boost versions across 0.9.4 and 0.10.0 in approx 8 hours and update this post.

**Comment by moneromooo-monero** [comment]
Could you also please post the output of: ldd simplewallet (the 0.9.4 version)

**Comment by nthterm** [comment]
ldd simplewallet
                                   
linux-vdso.so.1 =>  (0x00007fff9b19e000)                                    
       
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f294b4c8000)         

libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f294b1bf000)           

libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f294afa1000)

libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f294abd8000)

/lib64/ld-linux-x86-64.so.2 (0x0000564f0aa16000)

**Comment by nthterm** [comment]
Boost version installed on my system:
Version: 1.58.0.1ubuntu1

**Comment by moneromooo-monero** [comment]
What I found yesterday debugging this:

- I can't load the wallet cache you supplied with current code and boost 1.59
- the loading fails trying to read a string from boost serialization near startup
- if I built current code with boost 1.55, it gets past that, but finds an unexpected version
- the version is 14, which boost 1.60 and 1.61 write, while boost 1.55 writes 10

That kinda hints that the wallet was created with a mix of boost 1.55 and 1.60, which seems very strange. Unless the data read isn't really a version, but is read as one. I'll continue looking at this bug this evening.

**Comment by moneromooo-monero** [comment]
I can open the wallet cache if (1) I build with boost 1.55, and (2) I take out the version check in boost.

When I then resave the wallet, it's saved with version 10 (which corresponds to boost 1.55, as expected).

So AFAICT, the wallet cache was saved with some kind of bastard mix of boost 1.51 and boost 1.60/1.61.

**Comment by nthterm** [comment]
If i created the wallet using one version of Boost, and later refreshed and updated the cache after upgrading to a different Boost version, could that explain the bastardization?

**Comment by moneromooo-monero** [comment]
No, since you used 0.9.4 binaries from getmonero.org, which are statically linked against boost, so updating boost will not have an effect on this. The wallet will be written with whatever boost version is linked with 0.9.4. Whatever it was originally created with does not matter.

**Comment by chaica** [comment]
I've got almost the same message here.
I'm under GNU/Linux Debian. I'm upgrading from monero_0.9.4.0, just copied my wallet file and wallet.keys and wallet.address.txt from my previous monero version.

The log tells me:
```
2016-Sep-24 00:15:12.568117 Monero 'Wolfram Warptangent' (v0.10.0.0-release)
2016-Sep-24 00:15:12.568146 Setting log level = 0
2016-Sep-24 00:15:12.568157 default_log: ./monero-wallet-cli.log
2016-Sep-24 00:15:12.568175 Logging at log level 0 to /home/user/monero_10.0.0/./monero-wallet-cli.log
2016-Sep-24 00:15:12.568206 Loading wallet...
2016-Sep-24 00:15:12.583152 Loaded wallet keys file, with public address: 51P9SG4URLDFfzSxvUYUxTLftcR398DT5Mv0B4JLMRih3icqrjVJiY8Jr9YF1PAXN7UFBDx4vKq4s3ozUpH5rEAuEioytyKJ
2016-Sep-24 00:15:12.740045 ERROR /DISTRIBUTION-BUILD/src/simplewallet/simplewallet.cpp:3901 Wallet initialization failed: basic_string::_M_replace_aux
```

Let me know if you need more information.

**Comment by moneromooo-monero** [comment]
Did you compile your own 0.9.4, or were you using the prebuilt one from getmonero.org ?

**Comment by nthterm** [comment]
Prebuilt

**Comment by chaica** [comment]
Prebuilt too

**Comment by chaica** [comment]
Let me know if you need more information. I'm just stuck using monero because of this bug :(

**Comment by netmonk** [comment]
Chaica, what are you doing here ? :+1: 
Sorry for the noise, but happy to see him in the Monero adventure.

**Comment by moneromooo-monero** [comment]
For now, I'm pretty sure that if you build with boost 1.55, and disable the version check in boost/archive/impl/basic_binary_iarchive.ipp like below, your wallet cache will load.

--- ./boost/archive/impl/basic_binary_iarchive.ipp      2016-09-27 21:07:19.088000000 +0100
+++ /tmp/basic_binary_iarchive.ipp      2016-09-27 21:07:09.972000000 +0100
@@ -137,5 +137,5 @@

-    if(BOOST_ARCHIVE_VERSION() < input_library_version)
+    if(0 && BOOST_ARCHIVE_VERSION() < input_library_version)
         boost::serialization::throw_exception(
             archive_exception(archive_exception::unsupported_version)
         );

**Comment by chaica** [comment]
@moneromooo-monero ok it worked. I also had to change Boost version line 570 of CMakeLists.txt but after that it built successfully with boost 1.55, thanks for the lead.

**Comment by vatcave** [comment]
@nthterm @moneromooo-monero 
Guys i am getting the exact same error "failed to load wallet: basic_string::_M_replace_aux" when importing keys generated in a Windows 10 0.10 wallet to an Ubuntu 16.04 0.10 prebuilt wallet. Can you please specify where this cache file is located so i can delete it?

**Comment by moneromooo-monero** [comment]
Same place as the keys file.

**Comment by tsirolnik** [comment]
Getting this error too, on Ubuntu x64 while logging into my wallet

**Comment by moneromooo-monero** [comment]
The "not found" is OK in some cases, so it doesn't mean something is wrong, per se.
The "Killed" is likely the OOM killer shooting monerod, and is almost certainly unrelated.

**Comment by moneromooo-monero** [comment]
Fixed with the switch to portable boost format.

+resolved
