### ISSUE TITLE
Sync status reporting 100% incorrectly

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero#1108]
The status command currently reports:

Height: 1139870/1140106 (100.0%) on mainnet, not mining, net hash 31.18 MH/s, v2 (next fork in 2.0 days), up to date, 8+0 connections

This is monero compiled statically, on Gentoo, amd64, commit hash 53e18cafdfb2bf..

**Comment by NanoAkron** [comment]
1139870/1140106 is 99.98%

What degree of precision would you like?

**Comment by voidzero** [comment]
Floor it - 99.9%. Because 100% will be understood as "fully synchronised."

**Comment by NanoAkron** [comment]
I don't see any problem with 2 significant digits actually.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1124

**Comment by luigi1111** [comment]
Fixed as above.
