### ISSUE TITLE
monerod reporting "Output does not exist"

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero#1109]
During sync, I got the following message but don't understand what it means and if it is something problematic on my end:

<pre>[P2P1]Output does not exist! amount = 500000000000</pre>

This is monero compiled statically, on Gentoo, amd64, commit hash 53e18ca.

**Comment by moneromooo-monero** [comment]
Possibly an alt chain. It's unclear without more context.

**Comment by voidzero** [comment]
Agreed. But is it possible to get more context a posteriori? I know that more verbose messages become visible when set_log is higher than 0, but in that case things like these will also be easier to pass by unnoticed, due to the amount of other output.

As an idea; maybe cases like these could be logged to a file when a user would specify something like, say, 'buglog' pointing to a filename? Another idea is to allow to set something like logfile_level=i, so that the console output level can be set separately from output that'd be written to a file. Hope this makes sense.

**Comment by moneromooo-monero** [comment]
A change in logging will be done, and I expect it'll make it easier to find things.
However, such messages are expected if you're seeing an alt chain.

**Comment by radfish** [comment]
@voidzero sorry for offtopic, do you happen to have a portage script for Gentoo to share?

**Comment by voidzero** [comment]
@radfish no, I don't, because I usually run a stable system.

To get this done, I temporarily install some keyworded (~amd64) packages, which get the 'static-libs' use-flag (these packages are ldns, expat, gtest, unbound, boost). I also install doxygen and boost-build.

After this, I build static monero binaries (command make -j4 release-static).

And when all this this is done and my binaries are built, I reinstall the original versions of the packages I mentioned above.

**Comment by moneromooo-monero** [comment]
No claim of anything not working beyond the message, and I believe some of them were expected back then. Closing.

+invalid
