### ISSUE TITLE
monerod: out_peers is reporting "unsuccesful"

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero#1110]
Nothing else. For example:

<pre>
out_peers 7
2016-Sep-20 17:48:02.215668 Error: Unsuccessful
Error: Unsuccessful
out_peers 9
2016-Sep-20 17:48:04.415551 Error: Unsuccessful
Error: Unsuccessful
out_peers 8
2016-Sep-20 17:48:06.559639 Error: Unsuccessful
Error: Unsuccessful
</pre>

This is monero compiled statically, on Gentoo, amd64, commit hash 53e18ca.

**Comment by moneromooo-monero** [comment]
This is a noop at the moment, and already reported.

**Comment by voidzero** [comment]
Apologies for filing the duplicate report, feel free to close it.

**Comment by NanoAkron** [comment]
I think it's easier if you close it - not sure what permissions various people need to close other peoples' issues.

**Comment by luigi1111** [comment]
Dupe of...something.
