### ISSUE TITLE
Remove ability to select database type from 10.0 upwards?

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1111]
I still note that the system allows us to select Berkeley DB

```
# default database:
# should be lmdb for testing, memory for production still
# set(DATABASE memory)
```

Is it pretty straight forward to remove this option and leave us with just LMDB? 

I don't mind tinkering if so.

**Comment by radfish** [comment]
If approved, please remember to drop libdb from README deps section, too.

**Comment by NanoAkron** [comment]
So...can blockchain_export be deprecated for v.10 because we're not going to be format shifting?

**Comment by radfish** [comment]
On Wed, Sep 21, 2016 at 03:13:57PM -0700, NanoAkron wrote:
> So...can blockchain_export be deprecated for v.10 because we're not going to be format shifting? 

Isn't export useful regardless of internal format? For example, to
distribute .raw on the website?

**Comment by moneromooo-monero** [comment]
Keep blockchain_export as radfish said, and we want to support other db backends, even though we have just lmdb now.

**Comment by NanoAkron** [comment]
@moneromooo-monero OK, that means basically leaving everything intact except reporting the database selection in CMakeLists.txt

Should be pretty straightforward really.

**Comment by radfish** [comment]
On Thu, Sep 22, 2016 at 12:19:31PM -0700, NanoAkron wrote:
> @moneromooo-monero OK, that means basically leaving everything intact except reporting the database selection in CMakeLists.txt

Agreed if it's not already reporting the DB being used.

Btw, also consider tweaking those couple messages in cmake to not say
"could not find... X using Y". Instead, rephase to just "using Y"
because the current messages look like an error but are not an error.
I think there are ~3 messages like these now.

**Comment by moneromooo-monero** [comment]
If not too late, I think it's be better to leave the db selection stuff, but have only LMDB as an option. This will avoid having to redo it once another backend gets added. If it's too late, then fair enough, it can be revived later.

**Comment by NanoAkron** [comment]
I'm not going to tackle this just yet so will close the issue to improve the signal-to-noise a bit.
