### ISSUE TITLE
[Feature Request] Add payment ID as option to sweep_all feature 

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero#1115]
Currently sweep_all only works with an address. That is, `sweep_all <address>`. However, people might want to sweep their wallet to an exchange, which requires a payment ID. Therefore, it would be convenient if people were also able to specify a payment ID with this feature. Thus:

`sweep_all <address> <payment ID>`

**Comment by mzdici** [comment]
ditto

**Comment by moneromooo-monero** [comment]
It was in fact allowing this. I added it in the help text.

**Comment by dEBRUYNE-1** [comment]
@moneromooo-monero Thanks, will close this issue then.
