### ISSUE TITLE
docker/CoreOS crash

### ISSUE THREAD

**Issue by FelixWeis** [monero-project/monero#1118]
During the initial block download the monerod daemon uses an insane amount of CPU resources and is able to make the whole system non-responsive. (load of 14.00 seen on a CPU with 8 cores). 
At some point the whole docker system crashes.

The option `--max-concurrency` seems to be ignored.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1129 might help some.

**Comment by moneromooo-monero** [comment]
As well as https://github.com/monero-project/monero/pull/2446 for max-concurrency.

**Comment by moneromooo-monero** [comment]
I'll call that fixed with the patches above.

**Comment by moneromooo-monero** [comment]
+resolved
