### ISSUE TITLE
low priority : daemon log lvl 0 shows x days ahead when connecting to old peers

### ISSUE THREAD

**Issue by darentuzi** [monero-project/monero#1119]
Node, version 0.10 running on Ubuntu 14.04
The daemon synchronizes to the latest block fine and works correctly with the wallet but it continuously prints "Sync data returned unknown top block [latest] -> [oldblock] x days ahead SYNCHRONIZATION STARTED
I am assuming its connecting to some peer who is behind in history but its kinda annoying to see this at log level 0.
A possible solution proposed by moneromooo could be to move it to log level 1 if (peer's height is less then latest chain height  && its top hash is part of the main chain).

**Comment by NanoAkron** [comment]
Hi @darentuzi it seems like we need to change the log levels for quite a few things and formalise just exactly what should appear at each level - see #1187.

@moneromooo-monero also recommends we change the underlying logging system entirely.

I'll try to ask about these at an upcoming dev meeting.

**Comment by luigi1111** [comment]
Part of #1187. Further discussion can be there.
