### ISSUE TITLE
SimpleWallet isn't included in the download tar for the latest release 

### ISSUE THREAD

**Issue by stealthcopter** [monero-project/monero#1122]
SimpleWallet isn't included in the tar files for v0.10.0 Wolfram Warptangent.

Not sure if this was to save bandwidth or if it's been discontinued, but as it isn't mentioned in the release notes or in the wiki it will/has caused confusion.

**Comment by moneromooo-monero** [comment]
It was renamed to monero-wallet-cli. Same for bitmonerod -> monerod.

**Comment by fluffypony** [comment]
Covered by the third point in the release notes:

"renamed binaries to follow a more logical, consistent convention"
