### ISSUE TITLE
Exception: cryptonote::TX_DNE with every refresh

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero#1130]
Log excerpt [attached](https://github.com/monero-project/monero/files/491453/monero_TX_DNE.txt).

Built against release `0.10.0` using [release AUR package](https://aur.archlinux.org/packages/monero/).

Doesn't appear to effect functionality (at least not immediately).

**Comment by moneromooo-monero** [comment]
The stack trace is not very useful. For instance, there is no call to get_tx in expand_transaction_2, etc. I suspect optimizations confused the source lookup. A debug version might help in that regard.

**Comment by anonimal** [comment]
I'll have to build a debug version on another machine and also see if its reproducible, then I'll attach any new results.

**Comment by anonimal** [comment]
When I `-DCMAKE_BUILD_TYPE=Debug` against a cloned tagged release, I cannot reproduce this issue.  When using the same `.bitmonero` data directory but `-DCMAKE_BUILD_TYPE=Release` in the AUR package, I **can** reproduce this issue.

Note: I can *only* build `Release` with the AUR package because, when building with `Debug`, `monerod` will fail to start:

`/usr/bin/monerod: error while loading shared libraries: librpc.so: cannot open shared object file: No such file or directory`

Fortunately, cloning and building `Release` *or* `Debug` **cannot** reproduce any of these issues.

 @radfish any ideas why the AUR package is problematic? Could `monerod` somehow not like split packages for `libmonero-wallet` and `monero`? Could GUI deps have any impact? Note: removing linkage with `ld.gold` has *no* effect on the issue (at least on x86_64).

**Comment by moneromooo-monero** [comment]
Maybe any custom CFLAGS either get the compiler to emit bad code, or expose some undefined behavior.

**Comment by radfish** [comment]
On Wed, Sep 28, 2016 at 08:50:04AM -0700, 0x914409F1 wrote:
> Note: I can *only* build `Release` with the AUR package because, when building with `Debug`, `monerod` will fail to start:
> 
> `/usr/bin/monerod: error while loading shared libraries: librpc.so: cannot open shared object file: No such file or directory`

What's librpc.so? is that a new internal lib?

Could you please try with `-DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF`? (make sure to rm build dir completely before retrying).

**Comment by moneromooo-monero** [comment]
I think that can be closed. Can you check whether this still happens with 0.10.3.1 ? There were some expected TX_DNE (verifying an invalid tx) which were "hidden" (logged as normal errors, not exceptions) while back.

**Comment by anonimal** [comment]
I can't reproduce.
