### ISSUE TITLE
Testnet daemon says I'm synchronized with the network, but status stuck on 99.2%.  Never shows 100%.

### ISSUE THREAD

**Issue by phloatingman** [monero-project/monero#1134]
![](https://ipfs.pics/ipfs/QmVqZq8GdLim4UbKnayaYMYP57BAdxh5VU6ZM4cNky3PRJ)

I'm still able to transfer testnet coins between wallets.  The unlocked balance reports everything fine even though the daemon says 99.2%.

**Comment by moneroexamples** [comment]
It happens sometimes. Dont know exactly why, but my guess is that its due to lack of up-to-date  peers to synchronise with.

**Comment by moneromooo-monero** [comment]
Does https://github.com/monero-project/monero/pull/1133 help ?

**Comment by moneromooo-monero** [comment]
On testnet, it might be because we rolled back testnet to allow a change in the rct signature encoding. This would have meant that for a while, the "real" chain would have been shorter than the longest (since the longest would have had invalid blocks due to the change).

**Comment by ElLamparto** [comment]
monerod reached 100% and then fall to 99%,, 98% though being connected all the time.
Currently is shows "3 days behind" (first entry from the top), while the client shows "synced".

![moneroblocks](https://cloud.githubusercontent.com/assets/9163437/19233377/71365ede-8ee5-11e6-98b5-89be56a98af6.png)

Debian Jessie 32bit, monero Wolfram Warptangent.

**Comment by ElLamparto** [comment]
UPDATE: It looks like my database is no longer updated, I am many days behing (though online).

Debian Jessie 32bit, monero Wolfram Warptangent.

**Comment by ElLamparto** [comment]
Should I open a new ticket for this? Since my db is not updated, **I can no longer use Monero**.
Is there anything that I can do to change it?

**Comment by NanoAkron** [comment]
@ElLamparto What do you mean by not updated? I would recommend closing this issue if solved and opening a new one to address the new specific issue you've discovered.

**Comment by ElLamparto** [comment]
@NanoAkron, This issue is not solved. Please see my previous entries in this ticket (especially the one of 10 Oct. with screenshots). It should be clear.

**Comment by ElLamparto** [comment]
Shortly again. At certain moment, monerod stops syncing, all I get are entries like:
2017-Jan-01 09:37:26.798813 [P2P1][193.70.8.151:18080 OUT]Sync data returned a new top block candidate: 1017006 -> 1214096 [Your node is 197090 blocks (273 days) behind]

I NO LONGER get:
2016-Dec-31 02:42:34.072885 [P2P9][195.154.207.151:18090 OUT]Synced 1009806/1213156

I've possibly found a workaround: setting the throttle correctly. If too high or too low, at certain height monerod stops syncing.

The below settings seem to work:
./monerod --limit-rate-up 10 --limit-rate-down 500

Attached is a level 1 log covering about 30 minutes, with throttle by default (too high vs my Internet connection speed). Please have a look at it.
[bitmonero.log.zip](https://github.com/monero-project/monero/files/680100/bitmonero.log.zip)

I keep testing. If OK, I will close this ticket one week from now.

Monero 'Wolfram Warptangent' (v0.10.1.0-release)
Debian Jessie 32bit

**Comment by moneromooo-monero** [comment]
That log shows blocks being added. Maybe it just got a lot slower ?

**Comment by ElLamparto** [comment]
@moneromooo-monero, maybe. There is no doubts about one thing: adding blocks slows down dramatically when approching 100%. Shutting down monerod for 24 hours (fully synchronized) will require 2-3 days to get to 100% again.

On the other hand, once 100% synchronized, it remains synchronized without problems.

Bitcoin and Litecoin (Core) synchronize at a steady rate until synchronized. It would be great if monerod were able to do the same.

**Comment by moneromooo-monero** [comment]
It can sync at a steady rate if you use --fast-block-sync 0. That'll slow it down though.
Current master should be a good bit faster for HDDs (the tester reported about 4 times as fast). That might help.

**Comment by moneromooo-monero** [comment]
That all seems to be fixed. The original problem (stuck 99.2%) should be fixed by the recent target height updating.

+resolved
