### ISSUE TITLE
sweep_all shows 0 as amount but works.

### ISSUE THREAD

**Issue by Onefox** [monero-project/monero#1135]
I just used a VM with monero.linux.x86.v0-10-0-0.tar.bz2 on testnet [(iso)](https://www.reddit.com/r/Monero/comments/53ucza/monero_testnet_live/).

And the sweep_all command doesn't show the correct amount that is transferred but its working as it should except of the displayed amount.

See:
![sweep_all](https://cloud.githubusercontent.com/assets/1709259/18818318/70a16c04-8376-11e6-807b-ba11ab349441.PNG)

**Comment by moneromooo-monero** [comment]
Can you try with set_log 2, and look for "Transaction X/Y:" lines. Do these show non-zero amounts after "sending" ? I think you can post the lines from "Made an attempt at a final", that should not dislcose much private info.
If it does show 0, do you have several lines with "amount=0.002000000000, real_output=2, real_output_in_tx_index=7, indexes:" immediately before those lines, with non zero amounts ?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1224
