### ISSUE TITLE
monerod v0-10-0-0 segfaults frequently

### ISSUE THREAD

**Issue by ElLamparto** [monero-project/monero#1142]
1. Always at exit
   ![monerodsegfault](https://cloud.githubusercontent.com/assets/9163437/18866787/c315e452-84a1-11e6-859b-eb1097fc88a9.png)
2. After synchro at 99.5%, it segfaults every a few minutes
   ![monerodsegfault2](https://cloud.githubusercontent.com/assets/9163437/18866839/e640802c-84a1-11e6-93ca-4eb37fc0ed35.png)

OS: Debian Jessie 32bit

**Comment by moneromooo-monero** [comment]
You can ignore the first one.

For second one, can you share a stack trace ?

ulimit -c unlimited
Run monerod with whatever options you use
gdb monerod core*
bt

**Comment by ElLamparto** [comment]
Last time I started monerod, it quickly took 100% CPU and I had to kill it... I'll play with it in the coming weekend.

**Comment by moneromooo-monero** [comment]
If you have a fast connection, and you're not synced, it's expected: it will quickly download blocks, and verify them. The verification part is somewhat CPU intensive.

**Comment by ElLamparto** [comment]
Here is the gdb output:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x986fdb40 (LWP 757)]
0x0850f203 in mdb_cursor_unref ()


backtrace:
==========
(gdb) backtrace
#0  0x0850f203 in mdb_cursor_unref ()
#1  0x085199b3 in mdb_cursor_close ()
#2  0x0848b2fe in boost::thread_specific_ptr<cryptonote::mdb_threadinfo>::delete_data::operator()(void*) ()
#3  0x085302ad in tls_destructor.part ()
#4  0x0853177b in thread_proxy ()
#5  0xb7f4fefb in start_thread (arg=0x986fdb40) at pthread_create.c:309
#6  0xb7e87d0e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

**Comment by moneromooo-monero** [comment]
Thanks.

**Comment by rboe** [comment]
Same here with version (v0.10.1.0-release) on Ubuntu 16.04 LTS 32 Bit.

- crashes nearly always at exit
- crashes after snychronizing most of the blocks (7 days behind) randomly after snychronizing some more blocks.

Before this lots of threads are crated and exit. I'm not sure if this is normal behavior.

```
...
[New Thread 0x938fcb40 (LWP 26085)]
[New Thread 0x940fdb40 (LWP 26086)]
[New Thread 0x948feb40 (LWP 26087)]
[New Thread 0x950ffb40 (LWP 26088)]
[Thread 0x950ffb40 (LWP 26088) exited]
[Thread 0x948feb40 (LWP 26087) exited]
[Thread 0x940fdb40 (LWP 26086) exited]
[Thread 0x938fcb40 (LWP 26085) exited]
2017-Jan-09 19:10:28.518271 [P2P3][37.59.53.25:18080 OUT]Synced 1214804/1220160
[New Thread 0x950ffb40 (LWP 26089)]
[New Thread 0x948feb40 (LWP 26090)]
[New Thread 0x940fdb40 (LWP 26091)]
[New Thread 0x938fcb40 (LWP 26092)]
[Thread 0x950ffb40 (LWP 26089) exited]
[Thread 0x940fdb40 (LWP 26091) exited]
[Thread 0x948feb40 (LWP 26090) exited]
[Thread 0x938fcb40 (LWP 26092) exited]
[New Thread 0x938fcb40 (LWP 26093)]
[New Thread 0x940fdb40 (LWP 26094)]
[New Thread 0x948feb40 (LWP 26095)]
[New Thread 0x950ffb40 (LWP 26096)]
[Thread 0x948feb40 (LWP 26095) exited]

Thread 10836 "monerod" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x940fdb40 (LWP 26094)]
0x08528c33 in mdb_cursor_unref ()
(gdb) bt
#0  0x08528c33 in mdb_cursor_unref ()
#1  0x085333e3 in mdb_cursor_close ()
#2  0x08407efe in boost::thread_specific_ptr<cryptonote::mdb_threadinfo>::delete_data::operator()(void*) ()
#3  0x08549cdd in tls_destructor.part ()
#4  0x0854b1ab in thread_proxy ()
#5  0xb7f4c295 in start_thread (arg=0x940fdb40) at pthread_create.c:333
#6  0xb7e76eee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:114

```

**Comment by ElLamparto** [comment]
No, it isn't.
