### ISSUE TITLE
monerod upgrade v0-9-4-0 -> v0-10-0-0 fails

### ISSUE THREAD

**Issue by ElLamparto** [monero-project/monero#1143]
After about 20 minutes of torturing disk, v0-10-0-0 fails fails with:

2016-Sep-24 12:00:06.700432 Failed to delete tx_outputs: MDB_TXN_FULL: Transaction has too many dirty pages - transaction too big

2016-Sep-24 12:00:06.723907 Error opening database: Failed to delete tx_outputs: MDB_TXN_FULL: Transaction has too many dirty pages - transaction too big

Then monerod starts but does nothing.

OS: Debian Jessie 32bit

**Comment by moneromooo-monero** [comment]
Sync from scratch, it's usually faster than conversion anyway.

**Comment by ElLamparto** [comment]
Maybe then syncing from scratch should be the default option?

**Comment by fluffypony** [comment]
@ElLamparto the problem is unattended nodes - we're trying not to break them, and the auto-conversion seemed the least harmful way. We do mention in the release notes that sync-from-scratch is preferred.

**Comment by ElLamparto** [comment]
@fluffypony, It seems that in my case the auto-conversion killed the database (quite harmful!). It is then up to you to close this ticket.

Where can I find the release notes? Thanks.

**Comment by iamsmooth** [comment]
Release notes are here: https://github.com/monero-project/monero/releases/tag/v0.10.0

The other disadvantage of sync-from-scratch is much higher bandwidth use, which can be expensive for people with bandwidth metering or limits. Conversion-in-place should ideally work, but is just broken in some cases.

**Comment by NanoAkron** [comment]
Hi @ElLamparto is this still an issue for you or can it be closed?

**Comment by ElLamparto** [comment]
I have synced from the scratch, so it is no longer an issue for me. But the bug exists - so it is up to you to close this ticket (with or without fixing the bug).

**Comment by luigi1111** [comment]
Will likely be without "fixing". :)
