### ISSUE TITLE
Can't stop monerod 

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1146]
Stopped syncing at 60k blocks, tried to use ```monerod exit```, logs showing stop signal sent, not stopping

Will try running with ```gdb``` tomorrow

**Comment by moneromooo-monero** [comment]
How much did you wait ? If it's syncing, it'll stop after it's done processing the current 200 blocks.

**Comment by NanoAkron** [comment]
8 minutes. This is the 3rd attempt at resyncing and previous ones flew past these early blocks.

**Comment by moneromooo-monero** [comment]
Then a "thread apply all bt" will be helpful.

**Comment by NanoAkron** [comment]
Would you mind explaining that a little more?

**Comment by moneromooo-monero** [comment]
When you end up in such a situation again, run gdb like this:
gdb /path/to/monerod `pidof monerod`
Then, in gdb:
thread apply all bt
You will have to press enter to cycle through all pages of the data. When you've gone through all, paste that info here.
It shows what each thread it bitmonerod was doing at the time. There might be a deadlock in some of them.

**Comment by NanoAkron** [comment]
OK thanks, will do

**Comment by NanoAkron** [comment]
Closing. It now stops....eventually.
