### ISSUE TITLE
Unclear error message when trying to send more than my balance.

### ISSUE THREAD

**Issue by oyvkva** [monero-project/monero#1147]
`transfer somewhere 5000`

> Failed to find a way to create transactions. This is usually due to dust which is so small it cannot pay for itself in fees.

I get this message in wallet if I try to send more than my balance.

Log:

> not enough money to transfer, available only 0.300000000000, transaction amount 5000.000000000000 = 5000.000000000000 + 0.000000000000 (fee)

Wouldn't it be good if it said "Not enough money to transfer" in wallet as well?

**Comment by NanoAkron** [comment]
The fault looks to be due to the wrong message being used at line 2558 in `simplewallet.cpp`

Will fix.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1220
