### ISSUE TITLE
[feature] --language option for monero-wallet-cli

### ISSUE THREAD

**Issue by athanclark** [monero-project/monero#1151]
There's a `--password=...` argument, but there isn't a `--language="0"` argument: generating a wallet forces a programmer to supply the language int via stdin, which isn't healthy.

**Comment by mbe24** [comment]
I will try to look into that.

**Comment by mbe24** [comment]
The problem lies within `std::string simple_wallet::get_mnemonic_language()`. There, a language out of a list provided by `crypto::ElectrumWords::get_language_list` has to be chosen be its index.

**Comment by athanclark** [comment]
I did a little digging too, but C++ is way out of my league. I think there's some kind of options parsing class or something that clearly declares the CLI options, and different subcomponents peek into its instance to see if the option was provided already or not. I might be wrong though - I'll fetch a line number here soon.

This is similar with the "restore block height" input needed when restoring a deterministic seed; there's a `--restore-height` argument that has no effect when using `--restore-deterministic-wallet`, and again the index of the list of options needs to be supplied via stdin similarly.

**Comment by mbe24** [comment]
The problem lies in `simplewallet.cpp`. I'll change it so that when `--language=<int>` is provided, the program continues. If the parameter is missing, the language-to-index mapping is printed and the user is prompted. 

Please create another issue for your second request. Maybe I'll look into it, after I finished this one.

**Comment by rserranon** [comment]
Very important for --restore-deterministic-wallet there is no way to specify the language of words, any update on this?

**Comment by Elycin** [comment]
Bump.
Writing an application and could use this feature right now since it is not possible to create a wallet via RPC.

**Comment by hyc** [comment]
Creating a wallet via RPC is supported in git master. 110b683152e4930247c88d426799d53943f19e72

**Comment by Elycin** [comment]
@hyc thank you for referencing me to this, however I'm afraid over the past two days of my research that it's not officially documented anywhere, or to at least what I have searched for.

**Comment by jonathancross** [comment]
@mbe24 Did you ever make any progress on this?

**Comment by hyc** [comment]
@ghost the docs are online now https://getmonero.org/resources/developer-guides/wallet-rpc.html#createwallet

**Comment by hyc** [comment]
monero-wallet-cli now has a --mnemonic-language option. It was added in #2293

**Comment by hyc** [comment]
+resolved
