### ISSUE TITLE
Can't delete past edge when typing seed in --restore-deterministic-wallet

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero#1170]
In v0.10 if I'm restoring a wallet from seed (Linux 64-bit), a typical seed may take up 3 or 4 lines of text when the software prompts me to enter it. 

Here's the issue: if I'm fifteen or so words in and realize I made an error earlier in the word list, and hit backspace/delete to get back, it will hit the edge of terminal and refuse to keep going. It will stay on that single line, hitting the edge of the page and staying there. Does that make sense? It's as if you can't delete more than the single line you're already on when restoring from seed.

**Comment by NanoAkron** [comment]
Are you able to perform multi-line deletion when trying this in other programs?

**Comment by xmr-eric** [comment]
It works in Terminal. Can you suggest another program for me to test?

**Comment by moneromooo-monero** [comment]
Are you using rlwrap ?

**Comment by xmr-eric** [comment]
@moneromooo-monero That solved it. Thanks. It would be interesting to make this a default setting, though I assume ya'll got bigger fish to fry.

**Comment by NanoAkron** [comment]
Do you want to open that as a [Feature Request] issue and close this one? Then it'll remain obvious into the future.

**Comment by xmr-eric** [comment]
Great
