### ISSUE TITLE
[feature request] Possibility to use an external I2P router

### ISSUE THREAD

**Issue by ElLamparto** [monero-project/monero#1178]
There is a lot of talks on i2p integration. If one day an i2p router is integrated into Monero, it should be possible to use an external i2p router.

I run i2p with an open port (for years because I need it). However my band width is limited and I prefer to avoid running two routers at the same time.

Monero should use its internal i2p router by default, but there should be a possibility to disable it and connect to an external one.

**Comment by anonimal** [comment]
https://github.com/monero-project/kovri
https://github.com/monero-project/monero-site/pull/170/commits/1bbe94680745e05fcfff78dc1aa124bf0c29b40a

**Comment by luigi1111** [comment]
Request should be on kovri repo (?)
