### ISSUE TITLE
[RFC] Formalise log levels

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1187]
Hi all, just wanted to seek some comments about formalising the logging system.

`Log Level 0` Turn off all logging. Leave log files in situ but do not log any events
`Log Level 1` Major system events including activation/deactivation of major components and block synchronisation. Fatal errors and major component errors through `LOG_ERROR`
`Log Level 2` Minor system events including activation/deactivation of sub-components with more details of peer connectivity. Now log warnings through `LOG_WARNING`
`Log Level 3` Log all details. Could including programmer's notes for later debugging through `LOG_NOTE`

**Comment by moneromooo-monero** [comment]
I'd do that as part of the change of logging system (eg, easylogging++).

**Comment by NanoAkron** [comment]
Agreed. Adding a new logging system is way beyond my skill level though so was just wanting to get something formally agreed and publicly available for all developers.
