### ISSUE TITLE
[RFC] Option to view live logs in daemon mode

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1188]
`monerod --live` could give scrolling logs at the current log level for those geeks (such as myself) who like to watch things happily tick by on the terminal...

**Comment by moneroexamples** [comment]
set_log (or similar, dont remember) command in the deamon allows to specify how much log info is displayed in the terminal window.

**Comment by NanoAkron** [comment]
Yes but if I log out and then want to log back in again and check up on my little node...

I currently use a terminal alias to call `tail -f ./.bitmonero/monero.log` but for people who don't know or care to do this, it might be a nice little feature to add.

Not sure how you'd terminate it again from the command line though :(
