### ISSUE TITLE
problem with alt chains

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#119]
The recent attack resulted in the following message on some nodes, but the message indicates an inconsistency in the alt chain data structure, so there is likely some earlier consistency check missing

2014-Sep-06 11:02:18.859952 [P2P4]ERROR /home/user/bitmonero/src/cryptonote_core/blockchain_storage.cpp:771 alternative chain have wrong connection to main chain

**Comment by fluffypony** [comment]
I think we've fixed this with blockchain_db?

**Comment by iamsmooth** [comment]
I'm not sure we ever identified the root cause so it is difficult to say whether it is fixed. Much of the alt chain code works similarly with blockchain_db since alt chains are not stored in the db

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by Cactii1** [comment]
Looks like this was fixed, should probably close this issue.

**Comment by selsta** [comment]
This issue is almost 8 years old and it's unclear if it's still relevant. It can be reopened if we get other reports about this.
