### ISSUE TITLE
Command to to calculate the total of all coinbase transactions so far

### ISSUE THREAD

**Issue by shmacoshmuesday** [monero-project/monero#1196]
Per this discussion in the monero stackexchange, please add this functionality to calculate total coin supply.
https://monero.stackexchange.com/questions/692/how-can-i-verify-the-monero-coin-supply-without-using-a-block-explorer

**Comment by moneroexamples** [comment]
You can do it using `blkinfo` tool: https://github.com/moneroexamples/block-access-time

Example output: http://i.imgur.com/BU0RBYs.png

If you want, I can later generate full output for you?

**Comment by moneromooo-monero** [comment]
This is now done.

+resolved

**Comment by shmacoshmuesday** [comment]
Awesome work thank you!!!
