### ISSUE TITLE
impossible with RPC call determine if chain fork or not fork

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#1202]
/getheight 
Return only last height if new block is find with same height.

T0 network find block 85145 hash 000xxxx44
T0+1  /getheight  return 85145 
T0+2  Get blocktemplate  85145 hash 000xxxx44

T1 network find block 85144 
T1 network find block 85145  hash 000xxxx7e
T1+1  /getheight  return 85145   ( I mine allway bad block )

If get blocktemplate directly , I can estimate good fork with difficulty of block

**Comment by moneromooo-monero** [comment]
There is a getinfo which returns both height and top block hash.

**Comment by perl5577** [comment]
getinfo not return information for détermine best chain  .

With same daemon , is always top !
I think need cumulary diff is necessary 

If , I want monitoring fork and change 
if , I wan compare many daemon ?

**Comment by perl5577** [comment]
I open other issue for get_info write error data

**Comment by moneromooo-monero** [comment]
Add another bug for adding cumulative diff to get_info, please, and we'll do that.

**Comment by moneromooo-monero** [comment]
You now have top hash and cumulative difficulty in PRs.
target_height is only used when batch syncing, not in "normal" keeping up with the network.

**Comment by luigi1111** [comment]
Desired functionality added in response to #1210 and #1211
