### ISSUE TITLE
macOS - make release link error

### ISSUE THREAD

**Issue by RaskaRuby** [monero-project/monero#1207]
[100%] Linking CXX executable ../../bin/monerod
Undefined symbols for architecture x86_64:
  "bool cryptonote::Blockchain::get_blocks<unsigned long long, unsigned long long const, std::__1::list<cryptonote::block, std::__1::allocator<cryptonote::block> > >(unsigned long long const&, unsigned long long const&, std::__1::list<cryptonote::block, std::__1::allocator<cryptonote::block> >&) const", referenced from:
      cryptonote::core::get_coinbase_tx_sum(unsigned long long, unsigned long long) in libcryptonote_core.a(cryptonote_core.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by schnerchi** [comment]
PR #1204 causes this...

**Comment by monerobby** [comment]
Broken in Mac OS X El Capitan as well.

**Comment by RaskaRuby** [comment]
Thanks for fixing!
