### ISSUE TITLE
Streamlining compilation of dependencies for multi-core systems

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1209]
I'm getting failed compiles with all values for `make -jx release` with x from 1 - 6 on my 4-core ARMv8 Cortex A53 system. It always seems to start around the 40% mark when it compiles `obj_rpc` or `obj_wallet`.

It only compiles reliably if I run it as a single-threaded process...which leaves me with compile times around 90 minutes and 3 cores just sat there twiddling their thumbs.

Is there any way we could tweak the compilation sequence in the makefiles to improve this? I freely admit this is beyond my abilities.

**Comment by moneromooo-monero** [comment]
There is a .NOTPARALLEL directive in GNU make. If you find how to shoehorn htat in cmake.

**Comment by NanoAkron** [comment]
Is it possibly due to the ordering of the dependencies within the various makefiles? What if all the code was compiled into object files first and linking was postponed to the end?

**Comment by NanoAkron** [comment]
A reasonable ordering of compilation through analysing the dependency graphs appears to be the following:

Cryptonote_protocol
Mnemonics
Otshell_utils
+/- blocks
Crypto
Common
RingCT
Blockchain_db
Cryptonote_core
P2P
RPC
Wallet
Simplewallet
Daemonizer
Daemon

**Comment by moneromooo-monero** [comment]
I was assuming the failed compiles were OOM, since you did not say. cmake should (but maybe does not) respect the dependencies. Maybe some of the cmake makefiles don't have the correct dependencies (ie, missing one).

**Comment by NanoAkron** [comment]
I thought it might be OOM as well, but it's even failing with -j2 when I've got a quad-core with 2GB of memory.

Am currently adding dependency lists and seeing what happens. Sadly not much by the look of things so far...

**Comment by NanoAkron** [comment]
OK I just can't get this thing to compile with any value of -j, even -j2

Have increased my swapfile to 2GB, have also removed the dependencies and placed them explicitly in `/src/CMakeLists.txt`. Will push a PR so others can test.

Is there anyone we could call on to take a look at the build sequence?

**Comment by moneromooo-monero** [comment]
If it's OOM, you'll usually get a "Killed" on the console. Otherwise you get normal GCC output.
If someone knows cmake and sees that, they can try to get it fixed if it's actually broken (ie, if your failures aren't just OOM)

**Comment by NanoAkron** [comment]
Thanks @moneromooo-monero I'll close this now after @iDunk5400's testing.

**Comment by radfish** [comment]
Yes, 2GB is enough only for one thread (from my experience on Odroid U3). If you add swap and run with -j2 or more, it won't be killed by OOM killer, but it will thrash and your compile will take many hours.

There are several source files that are outliers wallet2.cpp and others that take a very large amount of memory and time to compile. I thought breaking apart those files into multiple chunks (to effectively parallelize their compilation) would be worth a try, but @hyc said he investigated this already.

**Comment by hyc** [comment]
Yes, I tried breaking up the source files already. The source files themselves are already small, there's nothing to break up. The problem is all of the boost include files, which bloat up all the compiles. And that problem is the overuse of templates and other boost junk, which prevents us from just compiling small chunks into separate linkable object files - all of that gets recompiled by every reference to the include files. The fact that so many C++ header files in our source tree contain implementations instead of only API definitions makes each actual source file effectively orders of magnitude larger and much slower to compile. It's a pretty horrible layout and would take quite a bit of refactoring to prevent this problem from arising.
