### ISSUE TITLE
rpc daemon get_info   top_block_hash :  is allway empty

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#1210]
top_block_hash :  is allway empty

target_height : Why is different from many monerod in same version and same time is different.

For target_height is possible, I have not understand metrics

**Comment by moneroexamples** [comment]
A command to test this:

```
curl -X POST http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id:"0","method":"get_info"}' -H 'Content-Type: application/json'
```

**Comment by perl5577** [comment]
Why target_height as different value from different daemon in same time ?

**Comment by moneromooo-monero** [comment]
target_height is the max height of seen peers, so may be different for two daemons. I think it doesn't take into account whether that chain is invalid or not though.

**Comment by moneromooo-monero** [comment]
And I have no idea why there are two getinfo calls. The other one sets top hash. I'm guessing any change gets made to one function and the ohter one gets forgot...

**Comment by perl5577** [comment]
Exemple 8 Daemon started same time (  full sync and found block ).

target_height is always > current_height  

For moment is only updated when "Sync data returned unknown top block"

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1221
