### ISSUE TITLE
Silly compiler error: ‘payment_id_seen’ set but not used

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1226]
`monero/src/simplewallet/simplewallet.cpp: In member function ‘bool cryptonote::simple_wallet::locked_transfer(const std::vector<std::__cxx11::basic_string<char> >&)’:`

`monero/src/simplewallet/simplewallet.cpp:2660:8: warning: variable ‘payment_id_seen’ set but not used [-Wunused-but-set-variable]  bool payment_id_seen = false;`

But it is used! Stupid compiler...

**Comment by moneromooo-monero** [comment]
It's not an error, and the compiler means "not used beyond setting". The reason is in my 1179 comments, but this got merged before I could comment. Hopefully the author might fix, or I'll do it at some point.

**Comment by NanoAkron** [comment]
Hope so too after reviewing your comments.
