### ISSUE TITLE
Testnet doesn't work for 0.9.4 beyond 800500

### ISSUE THREAD

**Issue by arnuschky** [monero-project/monero#1231]
Trying to use testnet with 0.9.4. It somehow doesn't work beyond block 800500:

```
2016-Oct-17 00:05:04.099748 [P2P7][x.x.x.x:28080 OUT]Sync data returned unknown top block: 800500 -> 821989 [21489 blocks (14 days) behind] 
```

This continues until all nodes block mine. What so special about block 800500? So no testnet for older versions?

**Comment by moneroexamples** [comment]
Only RingCT txs are accepted. Maybe that's why. Upgrade your monero to 0.10 version.

**Comment by NanoAkron** [comment]
That's not true. The last hardfork (v3) made coinbase more standardised. Next (v4) makes ringct voluntary and finally September 2017 is when normal tx will be fully replaced by ringct tx.

**Comment by NanoAkron** [comment]
That said, a hard fork generally means that old issues will no longer be supported, so if this issue disappears when you upgrade to v0.10 then I'm afraid...meh.

**Comment by moneromooo-monero** [comment]
800500 is the coinbase thing indeed, but only rct are being accepted now (except with unmixable stuff, where pre-rct is still allowed). But yes, update needed.

**Comment by luigi1111** [comment]
Testnet is on v5 currently. Need 0.10 or newer.
