### ISSUE TITLE
monero.win.x64.v0-10-0-0 monero-wallet-cli clouses after password input

### ISSUE THREAD

**Issue by Pilotvt** [monero-project/monero#1234]
Hi I'm new here so sory for my dullness in advance.
monero.win.x64.v0-10-0-0 monero-wallet-cli clouses after password input
I enter wallet name, then pass, and it show some error, but it clouses before i can read it.

**Comment by dEBRUYNE-1** [comment]
It might be that you are entering the wrong password. Could you check the `monero-wallet-cli` log file for errors? It's called `monero-wallet-cli.txt` if I recall correctly.

**Comment by Pilotvt** [comment]
2016-Oct-18 15:51:36.930709 Monero 'Wolfram Warptangent' (v0.10.0.0-release)
2016-Oct-18 15:51:36.930709 Setting log level = 0
2016-Oct-18 15:51:36.930709 default_log: C:\Users\Vitaly\Downloads\monero.win.x64.v0-10-0-0\monero-wallet-cli.log
2016-Oct-18 15:51:36.930709 Logging at log level 0 to C:\Users\Vitaly\Downloads\monero.win.x64.v0-10-0-0\monero-wallet-cli.log
2016-Oct-18 15:51:46.725226 Loaded wallet keys file, with public address: 44VsJWdhEzUNZc5jtG8yds8aZjVFHT61heQGV57iLq1R1u6HdRyWsb8gprgRWrW4h2YvWk9hisfAvAv1LSau9DXQR52iQSo
2016-Oct-18 15:51:47.257411 Error: failed to load wallet: std::bad_alloc
2016-Oct-18 15:51:47.319912 Error: You may want to remove the file "monerovt2" and try again
2016-Oct-18 15:51:47.319912 ERROR C:/msys64/DISTRIBUTION-BUILD/src/simplewallet/simplewallet.cpp:1432 failed to open account
2016-Oct-18 15:51:47.319912 ERROR C:/msys64/DISTRIBUTION-BUILD/src/simplewallet/simplewallet.cpp:3928 Failed to initialize wallet

**Comment by moneromooo-monero** [comment]
Known bug with the prebuilt binaries. See https://github.com/monero-project/monero/issues/1106

**Comment by Pilotvt** [comment]
It does help, but I encountered another problem: the wallet started to synchronise and windows freezed (probably because I flash GPUs) I restarted the system, and tryed to start monerod - it shuts down by itself.

**Comment by moneromooo-monero** [comment]
Paste the error message(s) monerod outputs.

**Comment by Pilotvt** [comment]
it just clousing, no log file for it.

**Comment by moneromooo-monero** [comment]
Now fixed thanks to the switch to portable boost format.

+resolved
