### ISSUE TITLE
get_hashes() causes broken wallet cache in error case.

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#1235]
If get_hashes() cant run properly and has to return an error (like here https://github.com/monero-project/monero-core/issues/75), the situation is not handled proberly and can cause a corrupt wallet cache, which results in :
![genesis_missmatch](https://cloud.githubusercontent.com/assets/17108301/19485129/65c3b738-955a-11e6-9099-5834c3e1e0c3.png)

**Comment by moneromooo-monero** [comment]
I could reproduce the "GUI hangs", but whatever I did, I did not get that problem after reloading the wallet.

**Comment by medusadigital** [comment]
can not reproduce.

--> closed
