### ISSUE TITLE
[RFC] Expected behaviour of set-default-mixin

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1243]
My thoughts:

In HF 3 (currently) - default is 4 but minimum allowed is 2. In HF 4 these will both be 4

Someone typing `set` in the console will see the value that has actually been set as their default, and not `0` defining `default`

If a wallet has a mixin value below the minimum allowed, their wallet will be forced to upgrade to the minimum allowed value of 2, rising to 4 after HF 4.

**Comment by luigi1111** [comment]
Related to #1206. Will leave both open for now.

**Comment by moneromooo-monero** [comment]
+resolved
