### ISSUE TITLE
Segmentation fault compiling on ARM

### ISSUE THREAD

**Issue by abelboldu** [monero-project/monero#1256]
I tried to compile on a RPi 2, because of that issue:

https://github.com/monero-project/monero/issues/1148

but also fails to compile:

```
[ 25%] Built target obj_ringct
make[3]: Entering directory '/home/vdo/src/monero/build/release'
Scanning dependencies of target ringct
make[3]: Leaving directory '/home/vdo/src/monero/build/release'
make[3]: Entering directory '/home/vdo/src/monero/build/release'
[ 25%] Linking CXX static library libringct.a
make[3]: Leaving directory '/home/vdo/src/monero/build/release'
[ 25%] Built target ringct
make[3]: Entering directory '/home/vdo/src/monero/build/release'
[ 26%] Generating testnet_blocks.o
Segmentation fault (core dumped)
make[3]: *** [src/blocks/CMakeFiles/blocks.dir/build.make:66: src/blocks/testnet_blocks.o] Error 139
make[3]: *** Deleting file 'src/blocks/testnet_blocks.o'
make[3]: Leaving directory '/home/vdo/src/monero/build/release'
make[2]: *** [CMakeFiles/Makefile2:1664: src/blocks/CMakeFiles/blocks.dir/all] Error 2
make[2]: Leaving directory '/home/vdo/src/monero/build/release'
make[1]: *** [Makefile:139: all] Error 2
make[1]: Leaving directory '/home/vdo/src/monero/build/release'
make: *** [Makefile:59: release-all] Error 2
```

**Comment by NanoAkron** [comment]
Would you be able to include the entire compilation sequence to include the setting up of the flags at the beginning?

**Comment by abelboldu** [comment]
http://pastebin.ca/3732366

**Comment by moneromooo-monero** [comment]
Looks the same as https://github.com/monero-project/monero/issues/1131

**Comment by NanoAkron** [comment]
May be related to #355 - there's no C standard for converting between `int` (as used in the functions in `blockexports.c` and `bool` used to define `m_testnet` which is how values are passed in.

Is there a way we can either drop `bool` entirely, or define it somewhere so it's internally consistent, as per http://stackoverflow.com/questions/1921539/using-boolean-values-in-c

**Comment by NanoAkron** [comment]
#1269 

I've brushed the dust off my RPi 2 and successfully built from scratch. I think your issues are with your installation of boost. 

Please delete all previous boost installs with `apt-get remove --purge libboost*` and then `sudo rm -rf /usr/local/lib/libboost*` and `sudo rm -rf /usr/local/include/boost`

Then install boost from scratch. Building and installing will take at least 12 hours, then building monero itself will take another 8. You will hit an out-of-memory issue linking the daemon so increase the swap size as per: https://www.bitpi.co/2015/02/11/how-to-change-raspberry-pis-swapfile-size-on-rasbian/

**Comment by radfish** [comment]
See #974. Try Invoking cmake with: `-DCMAKE_LINKER=/usr/bin/ld.gold`

**Comment by moneromooo-monero** [comment]
Is gold something that'd be installed with fairly high probability ? If so, it might be a good thing if someone wanted to autodetect it in cmake.

**Comment by radfish** [comment]
@moneromooo-monero On Arch and on Ubuntu ld.gold is owned by binutils package, so high probability. But, iiurc, the build failure with ld has been fixed already after I reported it at the time: http://lists.gnu.org/archive/html/bug-binutils/2016-08/msg00165.html

**Comment by moneromooo-monero** [comment]
Nice, thanks.
I'll just call it fixed then.

+resolved
