### ISSUE TITLE
Standardize ARM architecture naming convention

### ISSUE THREAD

**Issue by peronero** [monero-project/monero#1257]
Successor to  #1227:

Currently, README build instructions for ARMv8 static build are 'make release-static-arm8' but there is no make rule for 'arm8' - the rule is for 'armv8'.

This is inconsistent with the other ARM build rules and corresponding references in the README ('arm6' and 'arm7'), but these are incorrectly named since ARM6, ARM7, and ARM8 are distinctly different architectures from the Cortex product line comprised of architectures named ARMv6, ARMv7 and ARMv8 for which Monero is intended.

References to ARM architectures should follow their actual naming convention as designated by ARM, in this case 'armv6', 'armv7', and 'armv8'.

**Comment by NanoAkron** [comment]
Hi @peronero, why did you abandon your previous PR? Please make sure that you change the names in the readme, makefile and CmakeLists.txt

**Comment by peronero** [comment]
@NanoAkron The PR was intended to be a quick fix to align the README with the code so that the text on the frontpage of the repo contains working instructions. 

It wasn't merged because 2 lines in the text displayed 'arm#' and 1 line displayed 'armv#', despite that being the state of code. Standardizing the nomenclature project-wide was outside the scope of the PR.

Since you seem to already know what needs to be changed where, feel free to make the changes yourself.

**Comment by NanoAkron** [comment]
But I don't want to because I'm not having any problems with the existing naming convention. Sorry, but meh. I won't resist someone else doing it though.

**Comment by NanoAkron** [comment]
#1268 ;)

**Comment by peronero** [comment]
Fixed.
