### ISSUE TITLE
Can we make the compilation of the import/export programmes optional?

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1274]
I'm not sure how I'd go about doing the change but am willing to try it if anyone wants to offer some pointers.

**Comment by moneromooo-monero** [comment]
Tests are optional. You can see what the differences are between tests and tools.

**Comment by NanoAkron** [comment]
Thanks :)

**Comment by NanoAkron** [comment]
Don't think this is going to be done any time soon as I'm the only one it's annoying :)

Closing to improve signal/noise ratio.
