### ISSUE TITLE
Payment Id's show as 0000000000000000 after recent commits

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#1279]
Payment Id's show up as 0000000000000000 when using show_transfers after recent commits.

probably related to https://github.com/monero-project/monero-core/issues/87

**Comment by moneromooo-monero** [comment]
Testing here, with recent code:
Sending with integrated address (short payment id): payment id is wrong (though not 0)
Sending with full size payment id: payment id is correct

**Comment by moneromooo-monero** [comment]
The integrated one is now fixed with https://github.com/monero-project/monero/pull/1282
