### ISSUE TITLE
Fees show up as Max Amount

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#1280]
Fees can show up as Max Amount. Affects GUI as well as CLI wallet.

![maxfeemoo](https://cloud.githubusercontent.com/assets/17108301/19839316/d9743c1e-9edf-11e6-9ef7-30ebf1360c2c.png)

**Comment by moneromooo-monero** [comment]
For CLI only:

Are you running with commit 1dd5b0b7dff60d45aa3d5d33f8be304f3e222c7a in monero ?

If yes, does the bug appear for transactions *sent* with this commit, or only for transactions sent before it ?

Is the bug showing up for in, out, pending, failed, pool, txes ?

**Comment by medusadigital** [comment]
bug only seems to affect outgoing transactions which get restored. probably rebuildig cache is the issue

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1288

That's a GUI fix though, so that doesn't fix the bug on restore, that'd be a second bug.

**Comment by medusadigital** [comment]
fixed --> closed
