### ISSUE TITLE
CLI wallet bug: Multiple integrated_addresses allowed in a single transfer

### ISSUE THREAD

**Issue by kenshi84** [monero-project/monero#1293]
2 integrated_addresses generated by the receiver:
```
[wallet 44AFFq]: integrated_address
Random payment ID: <77c89b9508415bb1>
Matching integrated address: 4DrvGduF3ynBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVPpukyNHDiAEM16ya4J
[wallet 44AFFq]: integrated_address
Random payment ID: <08a86c7fc8c82605>
Matching integrated address: 4DrvGduF3ynBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVPkhWcDNZB411fPUMZH
```
The sender transfers fund to these 2 integrated_addresses:
```
[wallet 4AkvYS]: transfer 4DrvGduF3ynBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVPpukyNHDiAEM16ya4J 0.1 4DrvGduF3ynBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVPkhWcDNZB411fPUMZH 0.1
The transaction fee is 0.010000000000, of which 0.008000000000 is dust from change.
Is this okay?  (Y/Yes/N/No)y
Money successfully sent, transaction <c40a8639a0aa17ed8fb12b9ed7dc81cd9f5d2333de43ca67070059d9525e85b2>
```
The receiver sees the fund:
```
Height 1171319, transaction <c40a8639a0aa17ed8fb12b9ed7dc81cd9f5d2333de43ca67070059d9525e85b2>, received 0.200000000000
[wallet 44AFFq]: payments 77c89b9508415bb1 08a86c7fc8c82605
                                                             payment                                                         transaction      height               amount     unlock time
  <77c89b9508415bb1000000000000000000000000000000000000000000000000>  <c40a8639a0aa17ed8fb12b9ed7dc81cd9f5d2333de43ca67070059d9525e85b2>     1171319       0.200000000000               0
No payments with id <08a86c7fc8c82605000000000000000000000000000000000000000000000000>
```
Looks like the payment ID of the first integrated address is put into the transaction.
Maybe this is not such a huge issue, but still I guess this is a sort of bug.

**Comment by moneromooo-monero** [comment]
Works for me (the transfer part). The transfer doesn't get done. Are you running an old version for some reason ?

The payments command being broken is unrelated.

**Comment by kenshi84** [comment]
Do you mean, you see an error message when you tried to transfer? I didn't see any error message. I believe I'm using the latest version, 'Wolfram Warptangent' (v0.10.0.0-release).

**Comment by moneromooo-monero** [comment]
Yes.

transfer 4 [integrated address 1]  0.2  [integrated address 2] 0.2

Error: a single transaction cannot use more than one payment id: [integrated address 2]

**Comment by moneromooo-monero** [comment]
If I gave you a patch, would you be able to build and run this ?
It'd have extra logs to see what;s going on.

**Comment by kenshi84** [comment]
Yes I'll be able to build and run the patch.

**Comment by moneromooo-monero** [comment]
https://github.com/moneromooo-monero/bitmonero/tree/mia

**Comment by moneromooo-monero** [comment]
Run with log level 1, please

**Comment by kenshi84** [comment]
Oh, I realized it's just that the release binary (v0.10.0.0-release) was outdated, and the latest build just emits the error message:
```
Error: a single transaction cannot use more than one payment id
``` 
Sorry for bothering you :P

**Comment by NanoAkron** [comment]
Still worth finding. Would you mind closing issues that have been solved please?

**Comment by kenshi84** [comment]
Wasn't sure who's supposed to close an issue, I'm pretty new to GitHub:)

**Comment by NanoAkron** [comment]
No worries - thank you very much for doing so :)
