### ISSUE TITLE
Also showing total outgoing amount when confirming transaction

### ISSUE THREAD

**Issue by kenshi84** [monero-project/monero#1299]
This came out of another issue #1292 which was due to MacOS Terminal's bug. If the CLI wallet asks for a confirmation not only about the fee but also the total outgoing amount, potentially disastrous accidents due to such terminals' bug can be avoided.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1336

**Comment by kenshi84** [comment]
Thank you for your great work!
