### ISSUE TITLE
What is this about? 

### ISSUE THREAD

**Issue by Comodore125** [monero-project/monero#1332]
I am talking about the red color Error message. Why is it happening? 

![bug_monero](https://cloud.githubusercontent.com/assets/6156234/20240791/8560580a-a921-11e6-9134-e78591415e51.JPG)

**Comment by moneromooo-monero** [comment]
Setting "crystal ball" as dependency.

**Comment by Comodore125** [comment]
Closing as monero.stackexchange had helped.
