### ISSUE TITLE
Win_10_64bit synchronization messing with sound 

### ISSUE THREAD

**Issue by Comodore125** [monero-project/monero#1333]
Having monerod.exe started and working, this program is messing with sound on my system without going over 60% on CPU neither doing some problems with HDD. 

This issue is pretty strange. 

The problems it does with sounds is when I am listening to some podcast on Soundcloud it is interfering with the process like every 30 seconds sound output feels like shaking (or like it freezes) and then it moves on for another tens of seconds.

**Comment by moneromooo-monero** [comment]
Seems like the OS is a bit bad at I/O scheduling. The heavy load is there only while syncing, it should be gone once you're up to date and getting only new blocks. A workaround might be to set a download rate limit, which will, if small enough for your system, also keep CPU and disj I/O usage lower.

**Comment by Comodore125** [comment]
It might be bad at I/o scheduling, but it makes little sense when this issue is hapening only with monerod.exe. Bitcoin Core is causing no problems as well as other cryptos I tried. And nothing else is causing me problems.

**Comment by anonimal** [comment]
>it makes little sense when this issue is hapening only with monerod.exe

Unless you've produced a reliable [scientific control](https://en.wikipedia.org/wiki/Scientific_control), [deductive reasoning](https://en.wikipedia.org/wiki/Deductive_reasoning) without proper [scientific method](https://en.wikipedia.org/wiki/Scientific_method) can be misleading (e.g., are all conditions the same?).

Can you produce video/audio recording snapshots of all instances or provide another form of verifiable measurement? These types of symptoms with heavy I/O are usually indicative of low-resources, old hardware, and/or a bad operating systems (windows is inherently bad). 

I've noticed that syncing requires much I/O regardless of OS - and it is noticeable, so I think more info is needed.

**Comment by Comodore125** [comment]
Ok, guys, I will be testing this further

**Comment by Comodore125** [comment]
https://uloz.to/!V3XVCvx7Wxdx/monero-m4a

0:48 I started monerod.exe

When it start running on full speed the issue is happening more often. You can hear the problem after 2:00. 

![pc_detailsjpg](https://cloud.githubusercontent.com/assets/6156234/20245166/c7c315f0-a99b-11e6-95fc-3aa45010d7da.JPG)

**Comment by iDunk5400** [comment]
https://www.google.com/#q=deferred+procedure+call

**Comment by Comodore125** [comment]
yes, it is likely related. on other PC with win_10 I did not have this issue. It is likely related to sound drivers.

**Comment by moneromooo-monero** [comment]
It might be better now with current master, with 510d0d47.

**Comment by selsta** [comment]
Closing as the issue appears to be unrelated to monero.
