### ISSUE TITLE
Limit P2P system to just 2-3 connections to the same IPv4 address

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1338]
Is this possible to at least make it a little more difficult to drown out the network by spawning endless spoof nodes requiring sync data?

**Comment by moneromooo-monero** [comment]
No. Feel free to add it. Also a lesser anti-preference for hosts on the same subnet would be useful.

**Comment by NanoAkron** [comment]
That would require a dynamic peer risk stratification/scoring system, which would be nice but sadly beyond my experience.

**Comment by moneromooo-monero** [comment]
Doesn't need to be super complex to start with.

New peers we connect to: see make_new_connection_from_peerlist
This picks a random peer: get_random_index_with_fixed_probability
Then a few tests for suitability: is_peer_used, is_remote_ip_allowed, is_addr_recently_failed
Then connects: try_to_connect_and_handshake_with_new_peer

A simple way would be to add another suitability test: check the randomly selected IP is not in the same subnet has another one. Or the randonm selection could first partition known IPs in "same subnet as an current connection" and "others", and always pick from others unless it's empty.

**Comment by anonimal** [comment]
As noted in #1572, will this effect Tor users (more than 3 connections from 1 exit node)?
