### ISSUE TITLE
JSON-RPC protection

### ISSUE THREAD

**Issue by 3junit** [monero-project/monero#1340]
Hello. I have multy wallet system that work with monero too via JSON-RPC. Monero work on separated server. There is any way to set up allow ip for rpc or not? Like in bitcoin.

**Comment by NanoAkron** [comment]
If you type monero --help in the console you'll see the command to bind to an RPC address:port

**Comment by 3junit** [comment]
Well, thats is the problem. If i know this address:port i can do what i want! With simple curl! In bitcoin you have rpc user\password protection + allowip function for rpc. So you cant simply send curl and do commands.

**Comment by moneromooo-monero** [comment]
There is no authentication nor encryption for RPC. If you want to do that, for now you need to tunnel through ssh.

**Comment by 3junit** [comment]
Thank you, Will do tunnel via autossh
