### ISSUE TITLE
Debugging monerod crash issue

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1374]
So this crash after 1.5 days has been seen by asok. 

I propose we all choose a point to rewind to and then we can each post which PR we're going to test and post that info here. Once one of us gets to the point where the crash happens it'll make debugging easier.

Interlacing the testing this way will also help speed things up.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/issues/1377

**Comment by moneromooo-monero** [comment]
Fluffypony reports a crash with boost 1.62 on Mac with current master.

**Comment by NanoAkron** [comment]
@moneromooo-monero I'm going to roll back to the commit just before fluffy blocks, #1312 thread_group: fix build with asserts enabled

**Comment by NanoAkron** [comment]
Seems nobody is coordinating the debugging through this issue so am closing.
