### ISSUE TITLE
show_transfers via JSON-RPC

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#1410]
Hello.

There is already show_transfers command in cli to show all possible transfers.

But for JSON-RPC there is only incoming_transfers functionality which show incoming transfers only.

Is it possible to add show_transfers or outgoing_transfers for JSON-RPC as well (show_transfers would be better as it displays payment_id as well as txid).

Thank you.

**Comment by moneromooo-monero** [comment]
Use get_transfers. Set misc booleans to true for what you're interested in (in, out, pending, etc)

**Comment by moneromooo-monero** [comment]
And the payment id is incldued.

**Comment by gituser** [comment]
thanks, closing this.
