### ISSUE TITLE
Usage of quantum-proof Diffie Hellman method

### ISSUE THREAD

**Issue by Silur** [monero-project/monero#1416]
Quantum-computers are an emerging threat to the logarithm and prime-factorization problems that holds 99% of our common crypto standards, including ECDH. Call me paranoid but I write every software of mine with quantum-proof cryptography included and AFAIK monero is for... paranoid people :)

There's a wonderful, stable, reviewed [library](https://www.microsoft.com/en-us/research/project/sidh-library/) from microsoft that provides 128bit security against shor's algorithm.

I'd really like to implement it myself and make a pull request but I cannot and actually don't want to touch C++ code but let me know if I can help with that using pure C.

**Comment by moneromooo-monero** [comment]
Looks unexpectedly good (MIT, actually compiles on Linux). I wouldn't trust MS though with their history, especially if we can find other code. I believe some people in MRL are going to look at QC resistant algorithms, and I'll get the link passed on.

**Comment by moneromooo-monero** [comment]
Turns out the MRL people already knew about it, and it isn't useful in this case.

Thanks

**Comment by Silur** [comment]
Sorry but what is MRL? and why exactly isn't it useful, you use ECDH in a way that breaking it doesn't expose users to the public?

**Comment by anonimal** [comment]
@Silur https://lab.getmonero.org/ https://github.com/monero-project/research-lab

**Comment by moneromooo-monero** [comment]
I don't know the details of why it wasn't useful, but you can talk to luigi1111 on IRC.

**Comment by luigi1111** [comment]
This is an area to research, rather than just up and replace. :) Further discussion and findings can/should be added to the lab repo.
