### ISSUE TITLE
[FEATURE REQ] add txid filter for get_transfers

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#1420]
From RPC calculating issue (https://github.com/monero-project/monero/issues/1317#issuecomment-263902565): 

Please add filtering by transaction (txid) for get_transfers method.

Thanks,

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1537 adds a get_transfer_by_txid RPC

**Comment by moneromooo-monero** [comment]
(and you get an extra "type" field, which can be in, out, pending, failed, pool.

**Comment by gituser** [comment]
I guess this is already in the latest `0.10.3.1` ? 

If so this issue can be closed.

Thank you.

**Comment by moneromooo-monero** [comment]
Yes, it should be. You are the one who opened it, so you are the one who can close it (beyond fluffy, who gets time for this about twice in a year, so don't count on it :))

**Comment by moneromooo-monero** [comment]
+resolved
