### ISSUE TITLE
No hash or PGP signiture available for the source tar ball on Release section

### ISSUE THREAD

**Issue by good-guy-greg** [monero-project/monero#1429]
On the [release section](https://github.com/monero-project/monero/releases), there aren't any checksum hashes available for v0.10.0.zip and v0.10.0.tar.gz source files. Please add them, and even better, add a PGP signed file.

**Comment by NanoAkron** [comment]
@fluffypony is this still an issue with 0.10.1.0?

**Comment by moneromooo-monero** [comment]
Looks like it.
If you want the source though, it's best to get it from github, then you can check all signatures.
For other files, there's a GPG signed file at https://getmonero.org/downloads/hashes.txt

**Comment by moneromooo-monero** [comment]
Still the case for 0.10.3.1, for the record.

**Comment by moneromooo-monero** [comment]
The source tarball is apparently an automatic github thing, and so having a signature on it would not be too useful, since it'd be signing a tarball made by a third party. So I guess I'll close this. Use git if you want the source, checkout the release tag, and check signatures there.

+invalid
