### ISSUE TITLE
Replacing boost serialization with something else (eg cereal) offering compatibility 

### ISSUE THREAD

**Issue by kenshi84** [monero-project/monero#1430]
PR #1435 

As mentioned in previous issues #1106 #1341, it seems useful to be able to read wallet cache file from different platforms independent of the boost version used for building the wallet software.

@hyc mentioned on IRC that in the future, boost serialization may be replaced by LMDB which eliminates the boost serialization compatibility issue. Is anyone working on actually implementing this?

Have people considered another library called [cereal](https://github.com/USCiLab/cereal)? It's a header-only library and I found it quite easy to use in my past projects. If no one is working on it, I'd be up for contributing a patch.

**Comment by NanoAkron** [comment]
Is cereal being maintained? There are PRs hanging around from 2-3 years ago.

**Comment by kenshi84** [comment]
As I skimmed through some of those 2-3 year old PRs, they're mostly a bit controversial requiring discussion which seems to be continuing (albeit not too actively), so the project seems overall reasonably actively maintained.

**Comment by moneromooo-monero** [comment]
hyc has been thinking about this for a while.
There are other constraints behind "must be compatible between architectures", though:
- data must be encrypted
- would be nice to not have it all in memory (for large wallets, it can be significant)

**Comment by kenshi84** [comment]
@moneromooo-monero: I suppose the first constraint is satisfied currently by doing encryption  before serialization / decryption after de-serialization?
Is the second constraint satisfied currently?

**Comment by moneromooo-monero** [comment]
Yes, and no.

**Comment by kenshi84** [comment]
@moneromooo-monero thanks! Looks like I need to study a bit more how serialization is implemented currently, it's more complicated than I initially thought :)
