### ISSUE TITLE
connection timeouts dont work properly

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#144]
The recent change that increased the maximum send queue size has exposed that connection timeouts don't really work. What happens is an error message is produced, repeatedly, but the connection is never closed until eventually the underlying socket times out, which then in turns causes more errors until finally the connection is eventually recognized as closed. The entire process takes 

2014-Sep-16 11:41:50.035516 [P2P3][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:42:51.046131 [P2P4][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:43:52.057143 [P2P9][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:44:53.068512 [P2P4][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:45:54.079023 [P2P4][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:46:55.089978 [P2P3][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:47:56.101071 [P2P9][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:48:57.112118 [P2P6][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:49:58.123004 [P2P8][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:50:59.133490 [P2P3][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:52:00.144132 [P2P7][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:53:01.154523 [P2P9][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:54:02.164672 [P2P5][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 11:55:00.531227 [P2P0][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)
2014-Sep-16 11:55:00.531437 [P2P0][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)
2014-Sep-16 11:55:00.530861 [P2P0][sock 22] Some problems at write: Connection timed out:110
2014-Sep-16 11:55:00.531108 [P2P0]Failed to invoke command 1002 return code -3
2014-Sep-16 11:55:00.531227 [P2P0][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)
2014-Sep-16 11:55:00.531337 [P2P0]Failed to invoke command 1002 return code -3
2014-Sep-16 11:55:00.531437 [P2P0][120.237.2.216:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)

Under conditions that are unclear, under some cases this state persists for an hour or more (in fact as of the time of writing this connection still has not been close on my node):

2014-Sep-16 13:29:40.357908 [P2P1][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:30:41.382070 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:31:42.392198 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:32:43.402550 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:33:44.412598 [P2P8][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:34:45.422626 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:35:46.432818 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:36:47.442919 [P2P8][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:37:48.452901 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:38:49.462956 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:39:50.473054 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:40:51.483142 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:41:52.493340 [P2P1][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:42:53.503501 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:43:54.513471 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:44:55.524014 [P2P7][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:45:56.534166 [P2P9][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:46:57.544262 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:47:58.554417 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:48:59.564502 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:50:00.574416 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:51:01.584787 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:52:02.592057 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:53:03.600980 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:54:04.609064 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:55:05.617018 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:56:06.625088 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:57:07.632822 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:58:08.640849 [P2P9][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 13:59:09.648584 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:00:10.657095 [P2P3][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:01:11.678406 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:02:12.686113 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:03:13.693832 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:04:14.701464 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:05:15.708926 [P2P3][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:06:16.717168 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:07:17.724670 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:08:18.732146 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:09:19.740808 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:10:20.748628 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:11:21.756016 [P2P3][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:12:22.764635 [P2P3][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:13:23.772998 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:14:24.780629 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:15:25.787992 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:16:26.795464 [P2P7][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:17:27.802920 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:18:28.810453 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:19:29.817996 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:20:30.825620 [P2P1][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:21:31.833252 [P2P8][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:22:32.840965 [P2P8][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:23:33.849332 [P2P4][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:24:34.858354 [P2P7][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:25:35.868202 [P2P9][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:26:36.877861 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:27:37.887714 [P2P6][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:28:38.897479 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:29:39.907174 [P2P0][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:30:40.931465 [P2P3][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:31:41.941277 [P2P1][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:32:42.951257 [P2P9][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:33:43.961217 [P2P1][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:34:44.971523 [P2P5][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:35:45.981408 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2014-Sep-16 14:36:46.991356 [P2P2][50.68.44.191:18080 OUT]COMMAND_TIMED_SYNC invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)

**Comment by xpbcreator** [comment]
Was this ever resolved?  I might be experiencing issues related to this bug.

**Comment by moneromooo-monero** [comment]
I think https://github.com/moneromooo-monero/bitmonero/tree/leaking-sockets fixes most of this. If you can still repro with this branch, let me know.

**Comment by jonathancross** [comment]
Can this be closed?

**Comment by iamsmooth** [comment]
I guess we can close it and reopen or make a new one if the problem is still observed
