### ISSUE TITLE
[Feature] wallet: add  'donate <amount>' command

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero#1447]
```
@anonimal | Silly question, but how silly would it be to implement a 'donate <amount>' command which donates to a hardcoded monero fund address?
@anonimal | *the monero donation address
```

I'm curious to see how popular this idea is. An optional `sweep_all` like argument would be nice too.

**Comment by NanoAkron** [comment]
I like it. If we could have a sunshine clause so it's only around for a year or two that might be better.

**Comment by fluffypony** [comment]
Or just pay it to donate.getmonero.org, and warn if it doesn't match the hardcoded one, no need to sunshine it:)

**Comment by luigi1111** [comment]
Added by #1451

**Comment by anonimal** [comment]
@luigi1111 can we reopen this since the command doesn't donate with cli wallet. Can anyone else confirm?

**Comment by luigi1111** [comment]
It does work.

**Comment by anonimal** [comment]
Nope, not for everyone. Please see https://github.com/monero-project/monero/pull/1451#issuecomment-267496171.

**Comment by luigi1111** [comment]
OpenAlias not working over tor is a different issue, but fine. Please bring further discussion from PR #1451 back here.

**Comment by luigi1111** [comment]
https://github.com/luigi1111/bitmonero/commit/bfa23e4c4e6d9fbae3bef998dd98739d760a3008

That kinda lies to the user, but makes it look good.

**Comment by anonimal** [comment]
Commented in https://github.com/luigi1111/bitmonero/commit/bfa23e4c4e6d9fbae3bef998dd98739d760a3008

**Comment by luigi1111** [comment]
I care very little about this functionality in general. I have significant doubts it'll actually facilitate meaningful donations over not having it (a button in a GUI, maybe that's different).

**Comment by anonimal** [comment]
Is not every bit of XMR meaningful though? I think pushing all users to donate with cli or gui should be encouraged (gui button is a great idea too, btw). It comes at no cost to us. The easier the better too: is that not the basis (partly) of good sales strategy (don't make people wait or jump through hoops and don't give them time to change their mind)?

What if I simply PR'd the original hardcoded address and then we can close this issue?

**Comment by luigi1111** [comment]
> What if I simply PR'd the original hardcoded address and then we can close this issue?

Fine with me. :) Dunno what the others think.
