### ISSUE TITLE
import_outputs: Error: Failed to import outputs: unsupported version

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#1456]
This error is boost serialisation error. If normal wallet is made on a pc that uses different boost version than a pc with viewonly wallet, exporting and importing outputs may result in this error.

I used ubuntu 16.10 to export outputs, and my second wallet is on 16.04. The import fails because boost versions are different on those systems. 

Its worth mantioning, that it only happens when importing and exporting output files, as only this functionality uses boost serialization to produce and read the files. Importing key images, unsigned and singed txs files works because they dont use boost for this.

**Comment by NanoAkron** [comment]
I think this is a known issue with binary compatibility between wallets. @hyc is trying to solve by converting the wallet to LMDB, @kenshi84 is proposing a change to the serialisation library.

**Comment by moneroexamples** [comment]
Thanks, but not sure what lmdb has to do with it.The problem is with output file format, which you export from one wallet to the other. Key image files dont have this problem, for example. It only affects output files.

**Comment by kenshi84** [comment]
I think PR #1435 fixes this issue.

**Comment by moneroexamples** [comment]
PR https://github.com/monero-project/monero/pull/1483c solved the issue with output files.

Thank you. Closing this issue.
