### ISSUE TITLE
Error when compiling on Ubuntu 16.04 (vultr 2gb ram)

### ISSUE THREAD

**Issue by pmitchev** [monero-project/monero#1457]
I got the following error when I compile the latest version from master:
http://pastebin.com/PR8epe8M

**Comment by NanoAkron** [comment]
@pmitchev Can you try `sudo apt-get install -y liblzma-dev` and report back if that works?

**Comment by pmitchev** [comment]
no success

**Comment by NanoAkron** [comment]
So even with liblzma the build still fails?

If so, uninstall libunwind and liblzma and try again - you just won't be able to get stack traces but it should build. We'll chalk this one up to yet another libunwind issue.

**Comment by moneromooo-monero** [comment]
It's probably the same again and again :)

**Comment by NanoAkron** [comment]
@moneromooo-monero Is there any alternative stack trace tool/library available?

**Comment by NanoAkron** [comment]
Just found this header-only library:

https://github.com/bombela/backward-cpp/blob/master/README.md

**Comment by NanoAkron** [comment]
@pmitchev @moneromooo-monero has submitted PR #1494 to address this issue. Would you mind testing and reporting back inside #1494? Thanks!

**Comment by pmitchev** [comment]
the problem does not exists anymore. thanks :)
