### ISSUE TITLE
Error when compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by Onefox** [monero-project/monero#1465]
I needed to build boost 1.58 from source first but after that i still get an error while building the source:

`Scanning dependencies of target epee
make[3]: Leaving directory `/home/bitmonerod/monero/build/release'
make[3]: Entering directory `/home/bitmonerod/monero/build/release'
[ 11%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/http_auth.cpp.o
/home/bitmonerod/monero/contrib/epee/src/http_auth.cpp: In constructor ‘epee::net_utils::http::http_auth::http_auth(epee::net_utils::http::http_auth::login)’:
/home/bitmonerod/monero/contrib/epee/src/http_auth.cpp:485:46: error: no matching function for call to ‘epee::net_utils::http::http_auth::session::session(<brace-enclosed initializer list>)’
         : user(session{std::move(credentials)}) {
`

Here is the full log:
http://pastebin.com/5iaHQnfm
Is there any dependence i missed?

**Comment by moneroexamples** [comment]
On Fedora 25 there are also compilation problems. From what I recall they are related to tests, assuming they are same problems. You can try building without the tests `make release`. It helps on F25.

**Comment by xmr-eric** [comment]
Also perhaps run a `make clean` beforehand

**Comment by Onefox** [comment]
make clean and than make release results in the same error.

**Comment by moneroexamples** [comment]
I chacked again on Fedora 25, and it compiles properly now. The ubuntu 16.4/10 and Fedora 25 dependencies that I use are listed here: 

https://github.com/moneroexamples/compile-monero-09-on-ubuntu-16-04

Maybe you are missing some dependencies?

**Comment by NanoAkron** [comment]
@moneroexamples this is great - would you consider submitting your README as a PR to the main repo?

**Comment by moneroexamples** [comment]
@NanoAkron 

I think its better to keep it separate. The reason is that I make this to match monero projects at https://github.com/moneroexamples?tab=repositories and this guide changes in response to them, and not only to monero itself.

**Comment by NanoAkron** [comment]
@moneroexamples Would you consider maybe submitting that link to the README?

**Comment by daveinli** [comment]
Hi,
tried to install as per your instructions and getting many errors.
clean install, ubuntu 16.04. Did updates, installed dependencies.
Tried make clean then make release, same errors

[ 93%] Linking CXX executable ../../bin/monero-blockchain-import
/root/monero/src/crypto/slow-hash.c: In function ‘cn_slow_hash’:
/root/monero/src/crypto/oaes_lib.c:948:2: warning: ‘aes_ctx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  free( *_ctx );
  ^
/root/monero/src/crypto/slow-hash.c:533:15: note: ‘aes_ctx’ was declared here
     oaes_ctx *aes_ctx;
               ^
/tmp/ccbwxXET.ltrans15.ltrans.o: In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool)':
<artificial>:(.text+0x1e1c): undefined reference to `boost::re_detail::put_mem_block(void*)'
/tmp/ccbwxXET.ltrans15.ltrans.o: In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
<artificial>:(.text+0x215c): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
/tmp/ccbwxXET.ltrans15.ltrans.o: In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
<artificial>:(.text+0x4d71): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
/tmp/ccbwxXET.ltrans15.ltrans.o: In function `tools::is_local_address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x6a9d): undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
<artificial>:(.text+0x74d5): undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
/tmp/ccbwxXET.ltrans20.ltrans.o: In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail::re_set_long<unsigned int> const*, boost::re_detail::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
<artificial>:(.text+0x59a2): undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
<artificial>:(.text+0x5bbd): undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
/tmp/ccbwxXET.ltrans20.ltrans.o: In function `void boost::re_detail::raise_error<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >(boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::error_type)':
<artificial>:(.text+0x5f1a): undefined reference to `boost::re_detail::raise_runtime_error(std::runtime_error const&)'
<artificial>:(.text+0x5f38): undefined reference to `boost::re_detail::get_default_error_string(boost::regex_constants::error_type)'
/tmp/ccbwxXET.ltrans20.ltrans.o: In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack()':
<artificial>:(.text+0x5fa8): undefined reference to `boost::re_detail::get_mem_block()'
/tmp/ccbwxXET.ltrans29.ltrans.o: In function `bool boost::regex_search<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) [clone .constprop.17]':
<artificial>:(.text+0x872): undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
<artificial>:(.text+0x877): undefined reference to `boost::re_detail::get_mem_block()'
<artificial>:(.text+0x9d8): undefined reference to `boost::re_detail::verify_options(unsigned int, boost::regex_constants::_match_flags)'
<artificial>:(.text+0xa25): undefined reference to `boost::re_detail::put_mem_block(void*)'
<artificial>:(.text+0xd80): undefined reference to `boost::re_detail::put_mem_block(void*)'
collect2: error: ld returned 1 exit status
src/blockchain_utilities/CMakeFiles/blockchain_import.dir/build.make:170: recipe for target 'bin/monero-blockchain-import' failed
make[3]: *** [bin/monero-blockchain-import] Error 1
make[3]: Leaving directory '/root/monero/build/release'
CMakeFiles/Makefile2:1730: recipe for target 'src/blockchain_utilities/CMakeFiles/blockchain_import.dir/all' failed
make[2]: *** [src/blockchain_utilities/CMakeFiles/blockchain_import.dir/all] Error 2
make[2]: Leaving directory '/root/monero/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/monero/build/release'
Makefile:51: recipe for target 'release' failed
make: *** [release] Error 2
root@xmrglobalpool:~/monero#

**Comment by moneromooo-monero** [comment]
+resolved
