### ISSUE TITLE
monero-wallet-rpc Wallet initialization failed: std::bad_alloc

### ISSUE THREAD

**Issue by got3nks** [monero-project/monero#1489]
After upgrading to v0.10.1 I can no longer load a wallet created with simplewallet (v0.9):
```

monero@server:~$ /home/monero/monero-wallet-rpc --rpc-bind-ip=0.0.0.0 --rpc-bind-port 8082 --password xxx --wallet-file /home/monero/wallet.bin --daemon-address=127.0.0.1:18081
Creating the logger system
Monero 'Wolfram Warptangent' (v0.10.1.0-release)
Logging at log level 0 to /home/monero/monero-wallet-rpc.log
2016-Dec-22 17:37:01.660812 Loading wallet...
2016-Dec-22 17:37:01.703471 Unknown refresh-type value (32767), using default
2016-Dec-22 17:37:01.703733 Loaded wallet keys file, with public address: xxxxxx
2016-Dec-22 17:37:03.603663 ERROR /DISTRIBUTION-BUILD/src/walle /wallet_rpc_server.cpp:1205 Wallet initialization failed: std::bad_alloc
```

**Comment by gituser** [comment]
Just restore your wallet using seed or private key into new wallet file via monero-wallet-cli.

**Comment by dEBRUYNE-1** [comment]
This is caused by an incompatible wallet cache. If you delete the cache (`<wallet>`) you should be able to open the wallet created with simplewallet.

**Comment by vtnerd** [comment]
So this is most likely caused by a crazy allocation request when trying to parse in the new invalid format. Does the existing cache format have a header that can be used to identity between types? So that the code doesn't try to blindly attempt to parse the wrong format?

**Comment by dEBRUYNE-1** [comment]
+resolved
