### ISSUE TITLE
Can't send transaction with multiple integrated addresses

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#1505]
Hi.

I've got a problem when sending out transaction to multiple destinations which include >1 integrated addresses (even if I use the same address twice):
``` 
array (
    'code' => -5,
    'message' => 'A single payment id is allowed per transaction',
  ),```

is there a workaround for this or this is not allowed at all?

**Comment by moneromooo-monero** [comment]
There are several ways to do this, and it's not clear what's best.
The core could automatically make multiple transactions.
The core could allow duplicate payment ids and merge, but then the recipient would be seeing just one single transfer of the whole amount.

**Comment by gituser** [comment]
I'm not sure what's the best way, but my main idea is to reduce locked balance by sending multiple transactions in 1 transaction.

I think it's ok if recipient sees single transaction instead of multiple ones. I think it's already like that for regular addresses.

**Comment by moneromooo-monero** [comment]
It is possible. The tool does not allow you. There is no option for this.

**Comment by gituser** [comment]
OK, so to sum things up:
* you can't send in one transaction to multiple different integrated addresses
* you can send in one transaction to 1 integrated address and multiple regular
* you can't send in one transaction to the same integrated address (at the moment) if you pass the same integrated address to destinations array more than 1 time

So, the best approach to send to integrated addresses is to send separate transaction to each address.

**Comment by gituser** [comment]
@moneromooo-monero can you confirm what I wrote in previous post?

thanks.

**Comment by moneromooo-monero** [comment]
I'm not sure whether the second one works if the multiple regular have one payment id. It's all down to wallet behvior, but there's no spec for this. Not sure about 3 either, as I think the wallet is supposed to merge destinations, but then there are people who think this is wrong in the first place, as it prevents splitting coins in more than two bits when sending to yourself, which is a valid and useful use case.

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by zeshanvirk** [comment]
I'm trying to send one transaction to one integrated Address but getting the error

 "code": -5,
        "message": "A single payment id is allowed per transaction"

whats is the solution?

**Comment by moneromooo-monero** [comment]
Give the entire command you're sending.

**Comment by moneromooo-monero** [comment]
ping, give the entire JSON query you're sending to get that error.

**Comment by moneromooo-monero** [comment]
Works for me at the moment with:

curl -k -X POST http://127.0.0.1:28081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"transfer_split","params":{"destinations":[{"address":"A3R9yd7we7uX9pj9WSAMLvA7z5CFDCX7Na2gr82eotVEa8dEWJKPduMcvBLs22tPpGDFLp2kqenBXeyH26TQoKtq7h7fMaCSfErNnEAFjj","amount":1000000000000}],"fee":50000000000,"mixin":10,"unlock_time":0, "trusted_daemon":true,"do_not_relay":false}}' -H 'Content-Type: application/json'

So I'll call that user error unless more information is given. Or maybe there was a bug which got fixed, but I think pool would have screamed as people typically use this to send to exchanges.

**Comment by moneromooo-monero** [comment]
Worked for me, no replies in a long time. Reopen with more info if it still does not work with current master.

+invalid
