### ISSUE TITLE
[Feature request] Starting block height for rescan_bc?

### ISSUE THREAD

**Issue by kenshi84** [monero-project/monero#1519]
Recently my wallet suddenly started to show an incorrect balance. I don't know why this was caused, but doing `rescan_bc` gave me the correct balance. (Btw, is this the primary use case for this command?)

I created the wallet a few months ago, so it seemed to me like a waste of time that the wallet rescans blocks from the genesis height. Wouldn't it make sense to allow the user to optionally specify the starting block height for rescanning?

**Comment by moneromooo-monero** [comment]
rescan_bc is not supposed to be used unless you really need it. People started using it every time there's something off, even if not needed. It's better to debug why something is off in the first place. Now, we've got no idea what went wrong.
Still, maybe worth doing.

**Comment by kenshi84** [comment]
I see. Since it's not supposed to be used frequently, maybe it's OK to force the user to start the rescanning from the genesis block. Closing.
