### ISSUE TITLE
FreeBSD Port

### ISSUE THREAD

**Issue by emc2** [monero-project/monero#1520]
I've created a FreeBSD port for installing Monero.  The repository is [here](https://github.com/emc2/freebsd-ports/tree/monero_port).  The port is found under net-p2p/monero.

I've tested this in an empty jail, built successfully, and am currently syncing up the blockchain.

The port would need someone to add a MAINTAINER entry before FreeBSD would take it.  Also, it currently defaults to LMDB, but it might be good to add an option for BerkeleyDB at some point.

**Comment by moneromooo-monero** [comment]
The bdb port is now obsolete, and won't work. Only LMDB is supported now.

**Comment by danrmiller** [comment]
I'll test this out too. Whether or not this is eventually included in FreeBSD's ports, maybe we need a directory in contrib or somewhere for packaging metadata, there's been some other discussion and interest in packaging for other platforms, like .deb/.aur/.rpm.

**Comment by anonimal** [comment]
JFTR: AUR release is [here](https://aur.archlinux.org/packages/monero/). There is also a git-version in the AUR but I'm packaging releases only.

**Comment by dEBRUYNE-1** [comment]
+proposal
