### ISSUE TITLE
Rpc 'Transfer' method with 16 character payment_id from an integrated address

### ISSUE THREAD

**Issue by Pwnmanship** [monero-project/monero#1528]
First I get the payment_id and address from an intregrated address which gives:
Address: 46w8MJYhrSca5gZug7PrwZNKjvHFmKeV11L6pNJPgj5QNEHsN6eeX3DaAQFwZ1ufD4LYCZKArktt113W7QjWvQ7CLjUXpwk
Payment_id: 635e56cc6fbe2b3e

Then I use that to call a transfer:
`{"jsonrpc":"2.0","id":1,"method":"transfer","params":{"destinations":[{"address":"46w8MJYhrSca5gZug7PrwZNKjvHFmKeV11L6pNJPgj5QNEHsN6eeX3DaAQFwZ1ufD4LYCZKArktt113W7QjWvQ7CLjUXpwk","amount":386174160000}],"payment_id":"635e56cc6fbe2b3e","get_tx_key":true,"mixin":3,"unlock_time":0}}`

And the error I get:
`{
  "error": {
    "code": -5,
    "message": "Payment id has invalid format: \"635e56cc6fbe2b3e\", expected 16 or 64 character string"
  },
  "id": 1,
  "jsonrpc": "2.0"
}`

This is with the newest monerod and monero-wallet-rpc.

**Comment by NanoAkron** [comment]
If this has been addressed, please close the issue.

**Comment by luigi1111** [comment]
The payment ID is in the integrated address; you shouldn't be supplying it in addition to that.

**Comment by moneromooo-monero** [comment]
+resolved
