### ISSUE TITLE
Which method accepts the 'winner' miner's block in the implementation?

### ISSUE THREAD

**Issue by DanielTipo** [monero-project/monero#1529]
I was browsing the source code but is a little bit more complicated. I have found the part where the miner's reward transacted. But how the 'winner' miner block is accepted amongst others? Which method implements this feature?

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a Q&A forum. Ask on IRC, on Freenode (irc.freenode.met), in #monero-dev.

**Comment by danrmiller** [comment]
Also try https://monero.stackexchange.com/ or https://forum.getmonero.org/
