### ISSUE TITLE
monero db-type option

### ISSUE THREAD

**Issue by sHAsHiLx** [monero-project/monero#1533]
typed monerod --help and see option "--db-type". tried to use it. tried to give something like "bin" as option. why? because there is no documentation about it so used anything i want. get error about it and at least get what i can provide - berkeley or lmdb. provided "berkeley" as option. received error about berkeley is disabled. then why this option is still here if only lmdb is enabled??? why no documentation about what option this arg accept?? why no any other documentation about other options (i mean about other options what I can get from --help command and see "args" as command option)? why I must provide something like "kdsbndewk" to receive error and see what other args want as options???
sorry for my english

**Comment by moneromooo-monero** [comment]
It is an obsolete option. Berkeley DB is not usable anymore, as LMDB now works fine on 32 bits, which was the bdb niche.

**Comment by sHAsHiLx** [comment]
remove it then?
also what about other args not documented and can be only understun to provide some fake args and only after it receive whar args can be?

**Comment by moneromooo-monero** [comment]
+resolved
