### ISSUE TITLE
 error: ‘get_address_from_str’ was not declared in this scope

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#1546]
Following today's merges of PRs, monero does not compile anymore:

```
/home/mwo/monero/src/simplewallet/simplewallet.cpp:3544:76: error: ‘get_address_from_str’ was not declared in this scope
     if (!get_address_from_str(args[1], address, has_payment_id, payment_id8))
```

function `get_address_from_str` does not exist in monero source code.

**Comment by kenshi84** [comment]
Fixed by PR #1544

**Comment by moneroexamples** [comment]
LoL. Just prepared the same fix: https://github.com/moneroexamples/monero/commit/48be39977906d01dc040161e72ac03d286813317

Anyway, thanks for fast response :-)

**Comment by luigi1111** [comment]
:)
