### ISSUE TITLE
Linux version at downloads page at monero.org

### ISSUE THREAD

**Issue by pcd70** [monero-project/monero#1553]
I am not sure I am at the right place but
At http://monero.org/downloads/  the linux file is for mac and the version displayed is not good

**Comment by anonimal** [comment]
Try the official download page https://getmonero.org/downloads/ or on github https://github.com/monero-project/monero/releases

**Comment by fluffypony** [comment]
@pcd70 monero.org is not listed in the README or in any of the community resources, I'm quite surprised that it would be treated as canonical in any way. It is most likely serving malware, and if you've run software downloaded from there you should consider sanitising your computer or formatting and reinstalling.
