### ISSUE TITLE
Extremely high bandwidth usage

### ISSUE THREAD

**Issue by Snipa22** [monero-project/monero#1556]
Hello,

I was doing an audit of my server/pool nodes, which run just Monerod, and noticed that several of them were performing extremely high levels of network transit, in excess of 200Mbit/second.  Based on this, I pulled a full stats logs for my servers, and noted almost 37Tb of traffic being transferred in the last week:
http://i.imgur.com/9joIAbL.png

This would equate out to over 12k blockchain syncs at this point, which seems quite excessive offhand, as this is only a week's worth of traffic.  I've gone ahead and reduced the speed of syncs on my boxes, but hope this can be resolved.

**Comment by Snipa22** [comment]
Looks like a good chunk of this may be bad nodes trying to sync as well:
http://i.imgur.com/rU03eaU.png

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2149 will help a fair amount (once your peers have updated).

**Comment by moneromooo-monero** [comment]
What does it look like now ? :)

**Comment by moneromooo-monero** [comment]
monerod should now use about a third less bandwidth, and another third less once most other nodes have updated.

**Comment by selsta** [comment]
06:07 <Snipa> Haven't checked in forever.  My ISP's stoped complaining, so I'll assume they're fine.
