### ISSUE TITLE
Maximum duration of network split

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1580]
Let's say a transatlantic cable goes down and the mining network splits for x length of time, leading to two independent chains. The cable is then repaired.

What is the maximum age of a chain root that we'll accept as taking precedence over ours even if it does have more work? Should we set this at an upper limit like 1-2 weeks of age?

**Comment by moneromooo-monero** [comment]
If the other is valid, and has more work, then the other will be accepted. Setting an upper limit means a hard fork that is unresolvable, essentially making the two networks entirely separate. Either both keep going (with a lot of noise) and no commerce is possible (via monero) between the two patrs, or one dies, and the users have to manually delete and resync.

**Comment by moneromooo-monero** [comment]
I'm not sure there's a point to this. If this was asking for a "please don't resolve forks after an arbitrary time has passed without resolution", then no, unless new research shows it to be a good idea.

For now,

+invalid
