### ISSUE TITLE
walletnotify with bitmonero?

### ISSUE THREAD

**Issue by domi771** [monero-project/monero#161]
I am looking to integrate Monero into our exchange. We normally communicate with the wallets over walletnotify. However I can not find this function in bitmonerod.

How can I communicate with bitmonerod from outside?

I would need to do this command:

Code:

```
    walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=deposit.coin payload='{"txid":"%s", "channel_key":"monero"}
```

any help welcome!

**Comment by muhammednagy** [comment]
Peatio?

**Comment by muhammednagy** [comment]
did you solve it?

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4333

**Comment by moneromooo-monero** [comment]
Better late than never.

+resolved
