### ISSUE TITLE
What's _mh_execute_header?

### ISSUE THREAD

**Issue by kenshi84** [monero-project/monero#1623]
I'm trying debug build Monero on Mac and failing with the following error:

```
Undefined symbols for architecture x86_64:
  "__mh_execute_header", referenced from:
      _get_blocks_dat_start in libblocks.a(blockexports.c.o)
      _get_blocks_dat_size in libblocks.a(blockexports.c.o)
ld: symbol(s) not found for architecture x86_64
```

`_mh_execute_header` is only used in src/blocks/blockexports.c and only for the Mac build. The linker can somehow find the symbol in the release mode but not in the debug mode. This library looks a little unusual in that it appears to create object files directly from *.dat files. Can anyone please give me a hint?

**Comment by moneromooo-monero** [comment]
Is that fixed now ? :)

**Comment by kenshi84** [comment]
Yes, sorry for my late reply :)

**Comment by ggsoul** [comment]
@kenshi84 I have the same error. How fixed?

**Comment by KouMeanSun** [comment]
how to do /
