### ISSUE TITLE
monero-wallet-cli get_tx_key not working when sending from monero-wallet-rpc

### ISSUE THREAD

**Issue by ocminer** [monero-project/monero#1625]
i'm sending payments through monero-wallet-rpc with get_tx_key set..

When looking through show_transfers out ... I see the corresponding txids in show_transfers but I cannot get the tx key for that txid .. get_tx_key reports "no tx keys found for this txid".

In my rpc.log the txid is sucessfully saved, no crashes whatsoever

show_transfers also doesn't return any receiving addresses for me 

i'm on 0.10.1.0 release

**Comment by moneromooo-monero** [comment]
I've tested this, and it works: run monero-wallet-rpc, call transfer_split with get_tx_keys=true, and I get back the txid and tx key, and get_tx_key works with that tx id when I load monero-wallet-cli after that.

**Comment by moneromooo-monero** [comment]
Is this still happening ?

**Comment by moneromooo-monero** [comment]
ping ?

**Comment by moneromooo-monero** [comment]
I'll close this as invalid if no reply soon since it works for me.

**Comment by moneromooo-monero** [comment]
+invalid
