### ISSUE TITLE
.daemon_lock not deleted after monerod exit

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1633]
As per title. Each time I exit, I still find `.daemon_lock` in my `.bitmonero` directory.

**Comment by IPGlider** [comment]
There is no _need_ to remove the file on exit, it is created each time the daemon starts if it does not exists and a lock acquired over it if there is none already, otherwise the daemon does not start.

Should it be deleted?

**Comment by NanoAkron** [comment]
So if the file already exists when the daemon starts, is there any risk it will not acquire the lock?

**Comment by IPGlider** [comment]
Doesn't seem so.

`boost::interprocess::file_lock`[0] is being used. I have tested it and works.

[0] http://www.boost.org/doc/libs/1_44_0/doc/html/boost/interprocess/file_lock.html

**Comment by moneromooo-monero** [comment]
It's not the file that serves as a lock, it's a file lock on the file. When the process does, the file lock is automatically released by the kernel, so it's safe against crashes.

**Comment by NanoAkron** [comment]
What function would I call to delete a file?

**Comment by moneromooo-monero** [comment]
r = boost::filesystem::remove(old_file);
    if (!r) {
      LOG_ERROR("error removing file: " << old_file);
    }

**Comment by vtnerd** [comment]
The interface to this function is confusing BTW. The boolean return code indicates whether the file existed. `remove(std::string)` throws on filesystem errors (permissions, etc.), and `remove(std::string, boost::system::error_code)` returns errors via the code object.

**Comment by NanoAkron** [comment]
Urgh...I'm guessing since we had permission to create and write to the file, that removing it would also be ok?

**Comment by moneromooo-monero** [comment]
Usually, yes :)

**Comment by NanoAkron** [comment]
I've tried my best but I can't figure out how to refer to the filename in the code. I've tried `db_lock` and `lock_path.string()` but I keep getting compilation errors :(

**Comment by hyc** [comment]
This problem is going to disappear soon. As of PR#1506 it's now possible for multiple daemons to run concurrently from the same DB. Currently the daemons would still overwrite each other's poolstate and p2pstate files, so that still needs to be adjusted. (I believe PR#1641 solves that now.) With everything out of the way we won't need the daemon_lock any more.

This way we can have separate daemons on multiple ports using the same DB. (E.g., one for public access with restricted rpc, and one for private access. Or one on clearnet and one on TOR. Or all of the above.)

Also, we'll probably move the poolstate into its own LMDB database so it can also be safely shared between multiple daemons.

**Comment by NanoAkron** [comment]
@hyc Oooh...nice. Do you know who is doing the work?

**Comment by hyc** [comment]
I'll be looking into the mempool in LMDB. As of now things should already work if you comment out the daemon_lock. Each daemon will be using its own pool, so it's not optimal. Also, @IPGlider reported a DB conflict after some hours of running so it needs some more testing and investigation.

**Comment by hyc** [comment]
I take that back - it will not work smoothly in its current state. The daemons screw each other up if one does a map resize, the other should notice it but doesn't.

**Comment by hyc** [comment]
Turns out that my previous map resize problem was that I was running a 32bit daemon and a 64bit daemon on the same DB. This doesn't work on Linux because mutexes aren't structured the same way btw 32bit and 64bit glibc. (It would work fine on just about every other platform LMDB supports though.)

**Comment by NanoAkron** [comment]
Fixed by PR #1748
