### ISSUE TITLE
Update readme copyright

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#1638]
> Copyright (c) 2014-2016, The Monero Project

Should be 2014-2017

**Comment by anonimal** [comment]
I think this should apply to all source files too. If anyone gets to this, could they also do https://github.com/monero-project/kovri/issues/517?

**Comment by moneromooo-monero** [comment]
I update the source files when (1) I edit them and (2) I remember to. One should not do a search/replace of copyright on otherwise unchanged source files.

**Comment by anonimal** [comment]
I think this is a legally fuzzy area, and also resolves point (2).

**Comment by anonimal** [comment]
```
2017-01-27 anonimal        For Kovri, yes because the act of updating the copyright date in turn effects the most recent contribution to file -> in term justifies new copyright date -> in term requires new copyright date to be added :)
```

**Comment by moneromooo-monero** [comment]
Circular reasoning,

**Comment by iamsmooth** [comment]
seems done. closing
