### ISSUE TITLE
Change default log level to avoid exposing public address and txids

### ISSUE THREAD

**Issue by monerohow** [monero-project/monero#1644]
Request: change default log level for CLI wallet so that no logs are written unless otherwise specified.

Some users don't have encrypted file storage (either because they have unencrypted hard drives, or use unencrypted online backup, or keep their files on company/university storage which other people can inspect, or keep their wallet on an unencrypted flash drive).

For these people, it'd be useful if the CLI wallet did not log to disk by default, so that they can rely completely on the encryption provided by the wallet password. Otherwise, their public address and txids are exposed in the log file if anyone gets access to the location of their wallet.

**Comment by moneromooo-monero** [comment]
It's a bit of an annoying one, as it requires cleanup of how user output is made. Monero inherits code which makes user output from the internal libraries, and which needs to stay visible on the console. There is no fine grained selection of what goes to the console or log currently, except using console writer classes, but these do not belong to the libs, only to the user level programs.

So this needs doing, but isn't just a trivial change.

**Comment by NanoAkron** [comment]
In the interim you can set --log-level=OFF

**Comment by monerohow** [comment]
Perfect, that's a good solution, thanks.

**Comment by moneromooo-monero** [comment]
You will lose the "transaction sent: txid XXXXXX" messages on the console too, though.

**Comment by moneromooo-monero** [comment]
+resolved
