### ISSUE TITLE
make debug-test failed to build: easylogging++

### ISSUE THREAD

**Issue by tdprime** [monero-project/monero#1660]
I sync'd with master this morning.  On Ubuntu 16.04, make debug-test

[ 60%] Linking CXX executable hash-target-tests
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::utils::s_currentHost[abi:cxx11]'
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::elStorage'
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::utils::s_currentUser[abi:cxx11]'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/hash-target-tests.dir/build.make:109: recipe for target 'tests/hash-target-tests' failed
make[3]: *** [tests/hash-target-tests] Error 1

**Comment by tdprime** [comment]
I have a pull request that addresses this issue, 
[fix depency on libepee.a for debug-test build #1676](https://github.com/monero-project/monero/pull/1676)

**Comment by moneromooo-monero** [comment]
The patch seems not to have been merged. Was this fixed another way, or still happening ?

**Comment by tdprime** [comment]
Looks like the real cause of this issue was fixed with #1688.
