### ISSUE TITLE
Failed to connect to any of seed peers, continuing without seeds

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero#1661]
TL;DR: monero node no longer syncs over Tor (tested over multiple circuits and exits)
```
anonimal        "Failed to connect to any of seed peers, continuing without seeds"
anonimal        Multiple Tor circuits, same message. If this is because of #1572, I will shake my fist in the air rapidly.
 *      anonimal using same commit that worked fine several days ago 2806842200d848b02c2c9c1816dbbc6e4803c923
anonimal        If it looks like #1572, smells like #1572, I'm assuming for now it's #1572.
anonimal        If so, this is a blow to privacy and to Tor users everywhere. If so, then using Tor to sync now requires a 3rd party to host an onionsite to their public node.
anonimal        Syncing over I2P, that could take weeks to months to finish. Not very appealing
```
Built against 2806842200d848b02c2c9c1816dbbc6e4803c923, I don't want to jump to conclusions but possibly #1572 related?

**Comment by NanoAkron** [comment]
Try manually bumping the limit and feed back here.

**Comment by anonimal** [comment]
Since this is a P2P issue, if nodes are running #1572, I can set the limit to infinity and it wouldn't matter because *they* would need to set the limit too, correct?

**Comment by NanoAkron** [comment]
I doubt every node out there has updated to include that patch. I'd argue the majority will be running vanilla 0.10.1

**Comment by IPGlider** [comment]
@anonimal your limit does not affect remote nodes, they would still have the limit, but as @NanoAkron said I doubt many nodes are running master.

Anything I can do to help?

**Comment by anonimal** [comment]
Two notes:

1. The commit I mentioned above was the same commit I used when there wasn't an issue
2. In `#monero-dev`, @Jaqueeee noted that recently received the same message but Jaquee's solution was to change DNS resolver

`anonimal | Since I can't change which resolver a Tor exit uses, I can't test your solution. I *can* test at the application level though if monero/unbound can somehow do that.`

**Comment by anonimal** [comment]
I can't reproduce this issue now. Was this DNSSEC related? Who runs moneroseeds?
