### ISSUE TITLE
Daemon not writing exit message on quit

### ISSUE THREAD

**Issue by NanoAkron** [monero-project/monero#1681]
So I recently had #1628 merged which should give a clear 'Daemon stopped successfully' message on the command line upon exit. 

However, this never seems to appear :(

Can anyone explain why? `scoped_message_writer.h` has been included appropriately.

**Comment by moneromooo-monero** [comment]
You mean, you didn't actually try it before PR ?

**Comment by moneromooo-monero** [comment]
Anyway, adding lots of redundant messages which appear regardless of log level is not really wanted in the first place.

**Comment by NanoAkron** [comment]
Well it just seemed obvious that it would work - the correct header was included, the same exact code worked elsewhere in the codebase, and it was a very small change without potential to break anything.

The idea wasn't to write to the log but to provide positive feedback to a user on the command line that the process had terminated so that they wouldn't then have to run `top` or `less ~/.bitmonero/monero.log` to check it had terminated correctly.

**Comment by moneromooo-monero** [comment]
Ooooh, this is supposed to be the daemonized process printing this ?
If so, it explains why it doesn't print anything. stdin/out/err are closed.

**Comment by NanoAkron** [comment]
Aaaah.

Well bugger. Can you think of any simple way to let the user know when the daemon has terminated successfully without checking the logs?

**Comment by moneromooo-monero** [comment]
Yes, check the PID does not run anymore.

**Comment by moneromooo-monero** [comment]
But really, the best way is to ensure the RPC waits till the end (or close enough).

**Comment by moneromooo-monero** [comment]
I think best way to do this would be to get the calling daemon to wait. Posibly by adding a "wait" boolean to the RPC call, which would cause the receiving daemon to wait till most of the CN layers are down (not sure how much it can wait before blocking though). Otherwise, by having the calling daemon check for when the other process dies. Not sure the effort/gain is good though.

**Comment by moneromooo-monero** [comment]
It's a daemon. Daemons are discreet creatures. They keep their logs to... logs. We'll keep it typical.

+invalid
