### ISSUE TITLE
make debug-test, behaves differently after, make clean

### ISSUE THREAD

**Issue by tdprime** [monero-project/monero#1688]
Doing the following experiment,
```
make clean; make debug-test 2>&1 | tee make1.log
make debug-test 2>&1 | tee make2.log
diff make[12].log | head -22
```
yields this result,
```
< -- Building internal libraries with position independent code
---
> -- Building internal libraries as static
```

Having the build behave differently creates many problems.  Requiring all builds to be done after `make clean`.

**Comment by NanoAkron** [comment]
What platform/processor?

**Comment by tdprime** [comment]
Linux, Ubuntu 16.04

**Comment by tdprime** [comment]
`BUILD_SHARED_LIBS` is being changed inside `tests/gtest/CMakeLists.txt`

**Comment by NanoAkron** [comment]
Your issue arises from different build flags each time you run `make debug-test` is the result of lines `189-199` in `CmakeLists.txt`. 

For some reason your system is not caching the `set(BUILD_SHARED_LIBS ON)` value between runs.

**Comment by tdprime** [comment]
Me?  I am new to this project.  I was just trying to get a working build.  Encountered issue #1660 and have been trying to fix things.  Since the build isn't repeatable, that has been made 10x more difficult.

**Comment by NanoAkron** [comment]
Just build without debug for now - `make release`

@moneromooo-monero should this be static or -fPIC? What if we remove `option(BUILD_SHARED_LIBS "Build shared libraries (DLLs)." OFF)` from `/tests/gtest/CMakeLists.txt`?

**Comment by moneromooo-monero** [comment]
I'm not the right guy to ask about cmake to be honest. I know close to nothing about it. But it does indeed seem wrong. However, I've been making incrementally for ages without apparent trouble (though with a custom target, but based on the existing ones).

**Comment by NanoAkron** [comment]
@moneromooo-monero @tdprime I think we should remove `option(BUILD_SHARED_LIBS "Build shared libraries (DLLs)." OFF) from /tests/gtest/CMakeLists.txt` and let the master shared vs. static option override here. 

Unless you can see a reason why this might not be desirable (e.g. always wanting shared libraries ON) then let me know.

**Comment by hyc** [comment]
(1) Why are we building shared libraries, ever? Security-sensitive binaries like these should only use static libraries.
(2) Shared libraries suck for test environments. They require you to use LD_LIBRARY_PATH or equivalent to find the correct shared libs.

**Comment by tdprime** [comment]
> On Feb 7, 2017, at 1:26 PM, hyc <notifications@github.com> wrote:
> 
> (1) Why are we building shared libraries, ever? Security-sensitive binaries like these should only use static libraries.
> 
Please clarify your concern.  All of the security code I know of is in a shared library: libcryto.so libssl.so, ...
> (2) Shared libraries suck for test environments. They require you to use LD_LIBRARY_PATH or equivalent to find the correct shared libs.
> 
I mostly work on Linux and FreeBSD.  On Linux, it’s not so bad.  One can differentiate between the build location and the install location easily enough with -rpath.

I don’t know what motivated this particular build choice.  I speculate this could have more to do with the build cycle at the time one is actively debugging a problem.  Under such conditions, there will be rapid code churn in a localized portion of the code.  If most is unchanged and it those are in shared libraries, the linking phase will be quicker.  Perhaps the time saving is 10-60s per iteration.  As I said, this is just a guess.

**Comment by tdprime** [comment]
I was able to learn one more thing, installing libgtest*.a into /usr/lib/ works around this issue.

**Comment by NanoAkron** [comment]
Where were they before?

@hyc @moneromooo-monero @fluffypony So two ways through this really - default should always be static unless there's a good reason otherwise. Can you think which of the `Makefile` builds should be built with shared libs? Otherwise I'll go through and make this stuff explicit where necessary.

**Comment by tdprime** [comment]
I did some research today.  Came across this, https://crascit.com/2015/07/25/cmake-gtest/ <https://crascit.com/2015/07/25/cmake-gtest/>

I was going to look into adapting this method for the monero project.  This will keep tests/gtest/CMakeLists.txt from polluting the build environment for others.

As for the history of things, here is when things changed: https://github.com/monero-project/monero/commit/06bb6923c3068637af729dd7e7500ce1a6c888b9 <https://github.com/monero-project/monero/commit/06bb6923c3068637af729dd7e7500ce1a6c888b9>

**Comment by hyc** [comment]
tdprime wrote:
>> On Feb 7, 2017, at 1:26 PM, hyc <notifications@github.com> wrote:
>>
>> (1) Why are we building shared libraries, ever? Security-sensitive binaries
> like these should only use static libraries.
>>
> Please clarify your concern. All of the security code I know of is in a shared
> library: libcryto.so libssl.so, ...

We statically link libssl.a and libcrypto.a on the official binaries. 
Different Linux distros ship wildly varying versions of these things, you 
can't depend on the right version of the shared library to be present.

-- 
   -- Howard Chu
   CTO, Symas Corp.           http://www.symas.com
   Director, Highland Sun     http://highlandsun.com/hyc/
   Chief Architect, OpenLDAP  http://www.openldap.org/project/

**Comment by NanoAkron** [comment]
@hyc Do those two libraries get included when one clones the repo from GitHub?

**Comment by hyc** [comment]
@NanoAkron no. they still come from the build machine.

**Comment by NanoAkron** [comment]
@tdprime The steps described in that link would seem to ensure that we always build against the latest google test libraries.

But this issue does raise an important point as noticed by @hyc - do we always build static _except_ for a few cases (as yet undefined) where we want shared libs. If so, we need to define the times when it is acceptable or necessary to build against shared libs.

Otherwise we just go in to `Makefile` and add `-D STATIC=ON` to every option, and amend those corresponding lines we've identified in `CmakeLists.txt`.

@vtnerd, @moneromooo-monero, @fluffypony Opinions on static vs shared libs?

**Comment by moneromooo-monero** [comment]
I don't like stuff that pulls from the internet when I build and will veto something that does this (though some script does it in the GUI, but it's easy to avoid it). This is a good way to get pwned.

As for the gtest stuff overriding shared libs setting, is this something that can be done locally (ie, save CFLAGS, let it do its thing, reset CFLAGS) ? I don't really care for shared libs either to be honest, though it's nice for not having to relink the world when debugging.

**Comment by tdprime** [comment]
Only a moron would suggest we suck in stuff automatically over the internet.

What was suggested and being worked on is a means of protecting the monero build from the gtest build.

Do you have anything constructive to contribute here?

**Comment by moneromooo-monero** [comment]
That's how I interpreted "ensure that we always build against the latest google test libraries, which is nice (so long as we have an internet connection at build time)", maybe this was incorrect. I have not looked at the code in particular.

As for constructive contribution, the two paragraphs in my previous post were. I have nothing to add right now.

**Comment by NanoAkron** [comment]
@tdprime Wow that's a pretty insulting response to both myself and one of our most experienced developers, in place of a simple factual correction. 

Could you please explain why you chose the words and tone that you did?

**Comment by tdprime** [comment]
I will agree that there was an insulting tone taken.  Threatening “veto” is nothing short of a personal attack.  It is childish and it is bullying.

We have people volunteering there time here.  I bring 30 years of experience with me.  I am sure there are others here who bring more.

When I started looking at this project, the stuff did not build.  It took days of analysis and fiddling to learn how the project is organized.  The point is, I put in the effort and have been making real contributions.  I try some changes, and submit them for public review.  Each iteration, things get better and better.

All I heard was knee-jerk shouting.  Fear without understanding.  Anger without compassion.

No advice.  No questions.  Just a whiny child.

When you see a bully, call him out.

**Comment by NanoAkron** [comment]
You sound like you have some ego issues.

General statement about what warrants a veto != a personal attack

Gross generalisation about 'knee jerk shouting' (when and where?)

Calling someone a 'whiny child'

Parading your 'years of experience' as a medal in a community of peers who just contribute where they can, no matter how much or how little experience they have.

I strongly advise you to wind your neck in.

**Comment by kenshi84** [comment]
Just FYI, my motivation to make PR #1626 was to accomplish debug build on Mac. The reason for the debug build failing turned out to be the fact that the debug build somehow activates the shared lib building and the mutual dependency between libblockchain_db/libringct and libcryptonote_core prevents them from being successfully built due to link errors with missing symbols.

If the shared libs building is to be discouraged in general, that PR may not be able to justify itself very well (although I tend to like the resulting straightened dependency relationship after splitting libcryptonote_core).

**Comment by moneromooo-monero** [comment]
I think you'll find most projects have reviewers. I know a lot of stuff gets merged to Monero which isn't totally ready or could be done nicer, etc, but there's still stuff I won't accept. I'm not sure why you're trying to be insulting over this, but if this starts to go over a sane grief/benefit ratio, it is not going to be helpful.

In short: if you want to help, help without the attitude. Otherwise, plenty of other projects around.
