### ISSUE TITLE
Wallet slowly rolling up all outputs into one

### ISSUE THREAD

**Issue by Snipa22** [monero-project/monero#1707]
I assume this is expected and/or wanted functionality, but it's starting to get problematic as a pool-op.  At this point in time, I tend to have a single large output, which, as soon as it's spent, causes the wallet to not have enough available funds to multiple transactions.

I would assume that this is expected/wanted functionality, but it does cause issues for pool-ops, whom may be making 10-15-20 transactions at a time depending on the state of the pool.  Is there a good solution for this, or a good way to handle this going forwards?

**Comment by moneromooo-monero** [comment]
I see two ways to fix this:
- have a value threshold, where a second unnecessary input is added only if one is available under that threshold
- have a min outputs threshold, where a second unnecessary input is added only if the wallet has more outputs than this threshold

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1919 should help with this.

**Comment by moneromooo-monero** [comment]
Wondering whether to keep this open or not. The settings above help, but they're not default, and I guess they're crude. Opinions ?

**Comment by Snipa22** [comment]
Sorry for not responding, looks like it helps deal with it without an issue.  We're good on our side.
