### ISSUE TITLE
request: set_log default; show_log (display current log levels)

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero#1734]
Upon startup, monerod shows the current loglevel:

`New log categories: *:WARNING,net*:FATAL,global:INFO,verify:FATAL,stacktrace:INFO`

If possible, it would be nice if we could restore this setting by use of `set_log default`.

Additionally, I'd like to request a `show_log` command that prints the current loglevel to the screen. Example:

<pre>show_log
Current log level: *:WARNING,net*:FATAL,global:INFO,verify:FATAL,stacktrace:INFO</pre>

This allows to see what the current log level is without changing it.

**Comment by moneromooo-monero** [comment]
Default is 0, which maps to what you are seeing.
I might add some more helpers though.

**Comment by voidzero** [comment]
Ah yes. I missed the obvious. Glad to hear about maybe adding helpers.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2512

**Comment by moneromooo-monero** [comment]
+resolved
