### ISSUE TITLE
Would like choice of Esperanto language for mnemonic seed

### ISSUE THREAD

**Issue by Engelberg** [monero-project/monero#1738]
Given the name of the project, when I installed the official Monero wallet and ran it for the first time, I was rather surprised me when it prompted me for a language and Esperanto wasn't on the list.

**Comment by moneromooo-monero** [comment]
Feel free to contribute a word list for Esperanto, with unique 4 letter or 3 letter prefixes.

**Comment by Engelberg** [comment]
I can do that.  How many words?

**Comment by moneromooo-monero** [comment]
1626 words. The intent is that they have a unique prefix, typically 3 letter (ie, you can't have duplicate and duped, for example). Also no proper names, words that hopefully are not too esoteric (to the target population). See for example src/mnemonics/italian.h in the monero tree. Supplying a list of words is enough, and I can turn it into a header and plug it wherever it needs to be plugged.

**Comment by Engelberg** [comment]
What's more important: unique 3-letter prefixes (as opposed to 4) or avoiding accented characters?  If I remove all the words that have accented characters, I'm not sure I can make a long enough list with unique 3-letter prefixes.

**Comment by moneromooo-monero** [comment]
Probably avoiding accents I'd say, given this is an international language so we'd want to be able to input it with a wide selection of keyboards. But that's my subjective opinion only.

**Comment by ProkhorZ** [comment]
This should be possible. As a test, I created a list of Esperanto words starting with M, unique for the first 3 letters, avoiding diacritics, names and uncommon words. The result was 70 words. This is slightly below the target of 1626/22=74 words, but there will be more combinations starting with a vowel. 
Source: http://www.reta-vortaro.de/revo/ 
My list: http://pastebin.com/WPvTuFVN

**Comment by dnaleor** [comment]
@ProkhorZ we could add Zamenhof just as an exception to the "name rule" ;)

**Comment by ProkhorZ** [comment]
@dnaleor Great! In that case, I'll work backwards from M to L, K, etc. But I'll be busy this week.

@moneromooo-monero I could also create the header file, I'm looking for easy coding tasks. It would be helpful if you'd add the references to esperanto.h elsewhere.

**Comment by Engelberg** [comment]
@ProkhorZ @dnaleor I don't want to dissuade you from trying, but I did a quick sanity check by counting _all_ the unique three-letter prefixes among all the unaccented words from the Baza Radikaro, which is one popular wordlist of "common words" by some definition of common.  I even included the rarer groups 6-9, and the "group X".  There are only 948, and that's before removing the proper nouns like continent names (which aren't usually capitalized in Esperanto, but I'm assuming are not desirable in this wordlist), the grammar words (like "adjektivo"), the negative or bodily function words like "vomi" (to vomit), a couple stray abbreviations and punctuated exclamations ("t.e." and "ve!"), etc.
https://gist.github.com/Engelberg/9f117e931d1589fb381c8666a7ee33d5

Going to 4-letter prefixes, I got to 1838, which gave me some room to trim the worst options and still get 1626.

**Comment by moneromooo-monero** [comment]
OK about the header file, I can plug wherever is needed afterwards, thanks.

**Comment by ProkhorZ** [comment]
@Engelberg The Baza Radikaro is a list of about 2500 words, useful for language learners, but of course that wont be enough for our purposes. There are more sources, for instance this page links to a list of 10,000 words: https://eo.wikipedia.org/wiki/Esperantaj_vortaroj_en_la_reto

**Comment by dnaleor** [comment]
so what do we do, stick to 3 or go to 4 letter uniqueness ? 
Was planning to do some letters this week...

**Comment by ProkhorZ** [comment]
I still prefer 3-letter unique prefixes. We could always go from 3 to 4 if necessary. 

And I actually prefer a mix of word types, just like the lists for the other languages. Every word ending in -o would be boring!

**Comment by dnaleor** [comment]
ok, I'll continue with 3-letter uniqueness. We'll see what the total will be and if needed we redo a few letters and expand the list. Dan, Esperanto, why is the language so simple? We need more words ;)

**Comment by ProkhorZ** [comment]
Progress update: I've done A to M by now, resulting in a running total of 1241 words, not counting 3-letter words. Thanks for your list, @Engelberg, I'm using it as a base, adding words from 2 online dictonaries.
@dnaleor Did you do some more letters after Z?

BTW, I've been thinking about a list of Dutch words for mnemonics. That will be much easier, because linguists have created lists of frequent words and huge corpora of words labeled and sorted by frequency.

**Comment by dnaleor** [comment]
I've done S-T-U-V-Z Don't know total. Was planning to finish this week with N-O-P-R, but you can do N-O if you want ;)

**Comment by ProkhorZ** [comment]
OK, I did the letters N and O. Did you finish the rest, @dnaleor? 
Then I could create the full list and the header file this Sunday. I'm afraid it'll have to be a 4 letter prefix after all. But this way, it'll be as distinctive as possible.

FYI, here's what I came up with so far.
[running list.txt](https://github.com/monero-project/monero/files/848403/running.list.txt)

**Comment by dnaleor** [comment]
I was busy, only did R-S-T-U-V-Z at this point. Will compile full list tomorrow, after I double checked.

**Comment by moneromooo-monero** [comment]
Seems it's almost finished. Is the list ready ? If it is, it can be included in the coming release.

**Comment by ProkhorZ** [comment]
It seems we were waiting on each other and got distracted. What I have is the running list of 1302 words posted above. I have some free time, I can finish the list this week.

In the meantime, I have been thinking about mnemonics in general, after the [How I stole your Siacoins](https://mtlynch.io/stole-siacoins/) blog, where a user wrote down *tonic* instead of *ionic*. I think we should prioritize distinctive words rather than recognizable words. E.g. *tubo, tufo, tuko* are easily confused, so I'd rather use *tubisto, tufgrebo, tuja, tukano*. What do you think?

**Comment by moneromooo-monero** [comment]
That seems like a good thing to aim for, assuming those words aren't obscure. I don't think there's any current rule which prevents disctinctive words at all. Indeed, I remember a guideline saying similar words should be avoided.

**Comment by ProkhorZ** [comment]
*Jes, ĝi estas finita!* I did reach 1626 words with a 3 letter prefix after all. I ran it through an online spelling checker and I checked that no prefixes are repeated. For the last update, I used a [bigger online dictionary](http://www.denisowski.org/Esperanto/ESPDIC/espdic.txt), and I added some words for languages/peoples that are written in lower case, like *azteca* and *maorio*, as well as some animal and plant names that not everybody might know (*egreto, ibekso*). But most Esperanto speakers will probably have a limited vocabulary anyway.
[fina listo.txt](https://github.com/monero-project/monero/files/1220012/fina.listo.txt)

@moneromooo-monero Could you create the pull request to add this, please?

Credits for compling the list: dnaleor, Engelberg, ProkhorZ.
Sources:
- Baza Radikaro Oficiala
- [Reta Vortaro](http://www.reta-vortaro.de/revo/)
- [Esperanto Panorama](http://www.esperanto-panorama.net/vortaro/eoen.htm) - Esperanto-English Dictionary
- [ESPDIC](http://www.denisowski.org/Esperanto/ESPDIC/espdic.txt) - Paul Denisowski

**Comment by moneromooo-monero** [comment]
Great! Can you put that file on fpaste.org or pastebin.mozilla.org please ? For some reason I always get signature errors when loading from an amazon server via github.

**Comment by ProkhorZ** [comment]
OK, that's weird, but I uploaded the list here: https://pastebin.mozilla.org/9029590

The name of the language in Esperanto is simply Esperanto. (Originally, it didn't have a name; it was described as *internacia lingvo* by Doktero Esperanto, but *esperantistoj* have been calling the language Esperanto for over a century.)

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2292

If any of the word list authors want a change in attribution, let me know and I'll update.

**Comment by dnaleor** [comment]
Hey @ProkhorZ  ... I indeed forgot to finish my part of the task, meanwhile I switched computers and it would have been hard to get the part of the work I did from the old drive. So thank you very much for doing the task on your own and sorry for my lack of communication. I kinda forgot :/

**Comment by dnaleor** [comment]
yeah @moneromooo-monero , don't put me as an author

**Comment by ProkhorZ** [comment]
OK, no problem, I love collecting words! @dnaleor 
Buy some Siacoin for backups :)

**Comment by moneromooo-monero** [comment]
OK, done

**Comment by moneromooo-monero** [comment]
anonimal's asking whether we could have monero in the list (instead of monda, where the 3-prefix matches). Does that sound OK ?

**Comment by ProkhorZ** [comment]
Yeah, monero is a word, of course. I didn't think of that. I did use bitmonero.

**Comment by moneromooo-monero** [comment]
er, is that actually a word ?

**Comment by ProkhorZ** [comment]
Yeah, it was in the ESPDIC dictionary. Bit- is a prefix independently of bitcoin, e.g. in *bitlibro* for 'e-book'.

**Comment by moneromooo-monero** [comment]
OK, so that's a good reason not to use monero, as those words are similar (unless another one replaces bit),

**Comment by ProkhorZ** [comment]
Well, if you want to be extra cautious, i'd use *bitlibro* and *monero*.

**Comment by moneromooo-monero** [comment]
Sounds good, thanks :)

**Comment by moneromooo-monero** [comment]
+resolved
