### ISSUE TITLE
Would like wallet to allow optional passphrase in addition to mnemonic seed

### ISSUE THREAD

**Issue by Engelberg** [monero-project/monero#1741]
I prefer wallet software that, upon creating the wallet, allows for the entry of an optional passphrase and then the wallet recovery becomes dependent on both the mnemonic seed and the optional passphrase.

I like this because then I can write down the mnemonic seed and not worry quite as much about someone seeing it, because it doesn't do them any good without knowing the passphrase (which is something memorable to me, but not written down).

When the recovery is based only upon information which must be written down, it feels less secure.

**Comment by fluffypony** [comment]
It's doable, but we'd have to have a longer checksum at the end to validate your password, else the seed by itself is somewhat pointless (every password would generate a different wallet).

**Comment by Engelberg** [comment]
From a security standpoint, isn't it ideal if every wrong password generates a valid wallet that simply doesn't happen to contain anything?

**Comment by fluffypony** [comment]
@engelberg sure, as long as you're volunteering to deal with every person that gets their password wrong when restoring:-P We have to assume that many people won't remember their password or address, and so they'll have to wait for an ENTIRE restore just to check that they put the right password in.

**Comment by NanoAkron** [comment]
The eternal trade-off between perfect and practical

**Comment by JollyMort** [comment]
@Engelberg fyi, there's a quite neat external tool for this: https://xmr.llcoins.net/

Actually I rolled 1 random seed and then used a couple of passwords to generate multiple wallets. It comes with some conveniences:

- they all look the same, so there's no way to tell they can be linked with some password
- you don't have to worry about someone stealing just the seed, and you could also plant some funds to the wallet derived from the "encrypted" seed to make someone think there's nothing beyond it
- if you use the common seed to derive it all, you can keep the seed safe for backup but you can also use any of the derived wallets (with the password) to recreate the seed!

> In the "CN Add" method, the key is hashed with CryptoNight, then interpreted as a private key/scalar and added to the hex seed. The resulting mnemonic looks exactly the same as an unencrypted one.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2257 - using the same method as luigi1111's CN_Add encryption in https://xmr.llcoins.net

Every password generates a different seed, as fluffypony mentioned above. Fair point about people forgetting the password, but, you know...

**Comment by moneromooo-monero** [comment]
+resolved
