### ISSUE TITLE
Typo "rcp-bind-ip" in monerod's Usage

### ISSUE THREAD

**Issue by peanutsformonkeys** [monero-project/monero#1778]
There's a typo in the description for the `--confirm-external-bind` setting: should be `rpc-bind-ip` instead of `rcp-bind-ip` (version 0.10.2).

**Comment by NanoAkron** [comment]
@peanutsformonkeys care to submit a PR? I'm sure it would be accepted.

**Comment by moneromooo-monero** [comment]
Thanks, https://github.com/monero-project/monero/pull/1781

**Comment by peanutsformonkeys** [comment]
Fixed in 0.10.2.1
