### ISSUE TITLE
getblocktemplate rpc call always returns "Core is busy" despite daemon being synced.

### ISSUE THREAD

**Issue by osensei** [monero-project/monero#1788]
Happens on v0.10.2, on both testnet and mainnet:

    {
      "error": {
        "code": -9,
        "message": "Core is busy"
      },
      "id": "0",
      "jsonrpc": "2.0"
    }

**Comment by hyc** [comment]
Known issue, fixed by PR #1786

**Comment by osensei** [comment]
Great! I can confirm it works.

**Comment by osensei** [comment]
Hmmm, it keeps happening. It worked yesterday and it was working today, but I restarted the daemon and now it happens again.

**Comment by osensei** [comment]
Sorry, my bad. 
It is working now, but it wasn't working in the testnet I was synced using one exclusive node that seemed to be out of sync of the real testnet.
