### ISSUE TITLE
How to display pending transactions in get_transfers?

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#1791]
Hi.

I've been using get_transfers rpc call to get all transfers from our wallet in and out.

Is there any way to show there as well pending transactions which are not included in the block yet?
I'm on 0.10.1-release.

Thanks.

**Comment by moneromooo-monero** [comment]
Set whichever of these you want to true: 

      bool in;
      bool out;
      bool pending;
      bool failed;
      bool pool;

pool is those to you, pending is those from you.

**Comment by gituser** [comment]
Yes, it works, thank you.

What about 'failed' ?

**Comment by moneromooo-monero** [comment]
What is the question ?

**Comment by gituser** [comment]
thank you.
