### ISSUE TITLE
--log-file is now ignored in monero-wallet-cli

### ISSUE THREAD

**Issue by potyt** [monero-project/monero#1808]
No matter what you specify in this option, the log file is always created in the current directory and named monero-wallet-cli.log, basically the command line option is ignored. This wasn't the situation previously (~6 months)

**Comment by moneromooo-monero** [comment]
I can see it too. Somehow, the command line code is claiming --log-file isn't given, when it is. Looking...

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1813

Surprisingly annoying to fix :)

**Comment by moneromooo-monero** [comment]
+resolved
