### ISSUE TITLE
Mining with the daemon not working on Linux 64-bit VPS with 0.10.2.1

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero#1810]
I tried both regular mining (start_mining [address] [threads] and background mining (adding [true/false] [true/false]) and the status will say "smart mining" or "mining" but it never changes from 0 hashes/sec and the VPS CPU utilization doesn't change either.

**Comment by hyc** [comment]
Works for me.
`start_mining 47xxx... 4
2017-02-26 14:01:51.961     7fac45413700        WARN    miner   src/cryptonote_basic/miner.cpp:293      Mining has started with 4 threads, good luck!
2017-02-26 14:01:51.961     7fa79cff9700        INFO    global  src/cryptonote_basic/miner.cpp:399      Miner thread was started [0]
2017-02-26 14:01:51.962     7fa763fff700        INFO    global  src/cryptonote_basic/miner.cpp:399      Miner thread was started [1]
2017-02-26 14:01:51.962     7fa79d7fa700        INFO    global  src/cryptonote_basic/miner.cpp:399      Miner thread was started [2]
2017-02-26 14:01:51.962     7fa7637fe700        INFO    global  src/cryptonote_basic/miner.cpp:399      Miner thread was started [3]
show_hr
Hash rate logging is on
hashrate: 50.0000
hashrate: 52.0000
hashrate: 53.2500
hashrate: 53.8000
hashrate: 54.3333
`

**Comment by NanoAkron** [comment]
@xmr-eric have you tried telling it to ignore the battery status?

**Comment by xmr-eric** [comment]
@NanoAkron That isn't working either. And when I try to stop the smart miner it errors like this:

2017-02-26 22:36:37.562	[miner 0]	INFO 	global	src/cryptonote_basic/miner.cpp:469	Miner thread stopped [0]
2017-02-26 22:36:37.563	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:119	Exception: boost::thread_interrupted
2017-02-26 22:36:37.563	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:120	Unwound call stack:
2017-02-26 22:36:37.574	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [1] ./home/xmr_eric/monero-release/monero-v0.10.2.1/monerod:boost::this_thread::hiden::sleep_for(timespec const&)+0x5bc [0x8648bc]
2017-02-26 22:36:37.574	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [2] ./home/xmr_eric/monero-release/monero-v0.10.2.1/monerod:cryptonote::miner::background_worker_thread()+0xd1 [0x6ebd41]
2017-02-26 22:36:37.574	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [3] ./home/xmr_eric/monero-release/monero-v0.10.2.1/monerod() [0x8635b5]
2017-02-26 22:36:37.574	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [4] /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7f681a06a6ba]
2017-02-26 22:36:37.574	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [5] /lib/x86_64-linux-gnu/libc.so.6:clone+0x6d [0x7f6819da082d]
2017-02-26 22:36:37.574	[miner 0]	INFO 	stacktrace	src/common/stack_trace.cpp:158	
2017-02-26 22:37:01.973	    7f3511ed4740	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,global:INFO,verify:FATAL,stacktrace:INFO

**Comment by vtnerd** [comment]
I see the offending spot in the code. It is triggered in `mining::stop` to "wake-up" the thread from sleeping. This is easy to fix, and I will issue a pull request for it.

And can you try this with debug logging? I am wondering about the target CPU rate calculation, which might telling the mining threads to sleep for an extended period of time resulting in effectively zero hash rate.

**Comment by vtnerd** [comment]
Also tagging @revler1082 who might want to follow this.

**Comment by revler1082** [comment]
Apologies for the poopie code gents. I'd venture to guess that the more likely reason for the 0 H/s is that the background mining is never actually "starting" because some threshold isn't being met. I should update the status to be a little more verbose (about whether mining is currently paused, etc).

Does your system have the following path: "/sys/class/power_supply/AC/online"?
Assuming it's not the battery, in order for background mining to trigger, the cpu idle percentage has to be >= 90% (BACKGROUND_MINING_DEFAULT_IDLE_THRESHOLD_PERCENTAGE). Are you maybe running something else on the VPS?

**Comment by xmr-eric** [comment]
Here's log level 2. If you want level 3 or 4 let me know

https://paste.fedoraproject.org/paste/BhPvRwkj8T48WLy~ysuUkV5M1UNdIGYhyRLivL9gydE=

**Comment by xmr-eric** [comment]
@revler1082 It won't mine with normal mining or smart mining, so I'm not sure if the problem is just for background mining alone.

**Comment by xmr-eric** [comment]
@revler1082 The CPU utilization is hovering around 5% 24 hours a day with a few spikes to 10%. The only software running is the node and the pool software. And my Linux VPS doesn't have power_supply/AC/online. It has power_supply/ACAD/online. But I'm pretty sure I checked the option for ignore battery.

**Comment by revler1082** [comment]
@xmr-eric thanks for the info. That path works as well, so I don't think it's a battery issue. Just a side note, the ignore battery only kicks in if the code fails to find out about battery power, so because you have that path, it WILL find out whether you're plugged in or not, and it will have to be plugged in for mining to start.

There's definitely something more going on since mining normally should be exactly the same as before, I didn't mess with anything in there, but let me check it out.

**Comment by vtnerd** [comment]
Is the VPS a container? How are you getting the CPU idle statistics (top, etc.)? Can you run `head - n 1 /proc/stat` - which just prints out the first line containing CPU statistics.

**Comment by The13thDoc** [comment]
So, this looks like it's certainly a defect in the code that is affecting the normal mining as well. I initially thought this was specific to @xmr-eric's setup.

I'm also, now, unable to establish any hashrate with mining, smart or regular, on **wallet-cli**. My issue for this is #1821, due to the previous uncertainty of this issue, and the fact that @hyc appears to not have problems.

**Comment by xmr-eric** [comment]
@vtnerd I don't know how to tell if it's a container. I assume you're asking if it's a dedicated machine, and I don't think it is. I get statistics of stuff like CPU load from the VPS software, which shows an image like this: https://i.imgur.com/VjFLqVS.png

If I run that `head` command it simply says "==> standard input <==" with nothing below that text. Instead if I run `top` it spits out this: https://paste.fedoraproject.org/paste/MmEgjKjeEJLC5vwX2SBNIl5M1UNdIGYhyRLivL9gydE=

**Comment by vtnerd** [comment]
Crap, earlier `head -n 1 /proc/stat` - no space after the dash. Could you run that instead? Top should be reading the same information, so this is unlikely to be the problem anyway.

**Comment by xmr-eric** [comment]
xmr_eric@localhost:~$ head -n 1 /proc/stat
cpu  4036686 0 212138 81823600 319375 0 43104 0 0 0
xmr_eric@localhost:~$

**Comment by xmr-eric** [comment]
I wonder if this is a Linux specific bug, and that it's because I start the daemon inside Linux /etc/rc.local file. I am having trouble sending commands to a daemon started within /etc/rc.local (for example starting a testnet daemon process) when those commands are sent from within a logged in user and not the main OS itself.

**Comment by xmr-eric** [comment]
Basically, the daemon is started by the OS/root, but the commands are issued from a logged in user, so that may be the reason for the disconnect.

**Comment by The13thDoc** [comment]
I just found out that logging in remotely triggers the idle percentage to stay in the 80s. It never seems to reach 90, despite nothing running differently.The CPU was remaining the same.

The moment I logged in directly, not remotely, it went above 90% and began mining again.

I'm not sure why remote access is having this effect. Other than that, I can't duplicate the zero hash rate problem.

**Comment by revler1082** [comment]
Maybe the extra work required by whatever process is doing the remote work
is higher?

**Comment by The13thDoc** [comment]
It didn't look that way. I mean sure, there is probably a little extra something running. I can't argue that. I was running it with low CPU usage to begin with, and it wouldn't kick in. Even now, My CPU usage is higher than that, but it is still producing a hashrate.

I just logged in remotely, with my CPU running higher, and the mining kept going, dropping only slightly. So now that remote bug is not consistent either. I'm not sure what's happening.

Perhaps we should keep the "remote" idea in the back of our heads, though.

**Comment by moneromooo-monero** [comment]
Is this working now for those people for whom it wasn't ?
