### ISSUE TITLE
Smart Mining not properly differentiating between idle and non idle.

### ISSUE THREAD

**Issue by The13thDoc** [monero-project/monero#1821]
Running this command: `start_mining <threads> true true`

The battery check doesn't appear functional (not the point of this issue), which was already mentioned; so I'm keeping that parameter **true**.

I'm running this command from **wallet-cli**, so as to not worry about the wallet address.

**Problem:**
It appears to start normally, detecting that the computer is somewhat/mostly idle (is *idle* just a matter of how much CPU is being used?). It adjusted based on how much CPU I used.

Locking the computer and letting it sit (idle) appears to have not tiggered a mostly idle status. So, returning to the computer resulted in me seeing no mining.

**Update:**
Now, starting it initially, it recognizes a 96% (fluctuating  in the 90s) idle CPU, but remains at 1% mining, hashrate of  0. 

**My specs:**
- Ubuntu 16.04 LTS (64-bit)
- AMD
- monero-v0.10.2.1
- (anything else?)

----------------------
@revler1082

**Comment by vtnerd** [comment]
This is going to be a duplicate of https://github.com/monero-project/monero/issues/1810 .

Is this running in a VM or container?

**Comment by The13thDoc** [comment]
I considered that. I have been mining successfully on each previous version
of monerod and wallet-cli.

It's not a VM. Enlighten me as to what a container is.

**Comment by moneromooo-monero** [comment]
A container is a kind of souped up jail, where you can run up to an entirely different userspace with the same kernel. Docker, for example.

**Comment by vtnerd** [comment]
Yes in particular I am concerned that the information in the container under `/proc/stat` is different than the information provided by the VPS console. Although it sounds like you might be running this locally.

**Comment by The13thDoc** [comment]
Correct. This is local.

It sounds like #1810 is discovering that the bug is "larger", since it is
affecting normal mining as well.

**Comment by vtnerd** [comment]
But are you have an issuing with "normal" mining, or just "smart" mining?

**Comment by The13thDoc** [comment]
Both, since 10.2.1. I haven't done extensive troubleshooting yet.

**Comment by The13thDoc** [comment]
A little ashamed to admit, I finally got around to building and running monerod from source. 

I'm slowly working my way through the workflow. Has there been progress on the smart mining bug that I can zone in on?

**Comment by moneromooo-monero** [comment]
Apply the patch in https://github.com/monero-project/monero/pull/1946, and run with --log-level 0,miner:DEBUG and paste the log to fpaste.org after you have run into the bug again.

**Comment by The13thDoc** [comment]
Question:

I'm _not_ running into the idle (hashrate 0) problem, smart mining on monerod 10.3.1 via source.

I went back to run monerod 10.2.1, hoping to recreate the bug (`./monerod --log-level 0,miner:DEBUG`) via the downloaded tar (where I found the problem), but now I'm not seeing **monerod.log** in **~/.bitmonero/**. I deleted the file to clear it for the new 10.2.1 logging. It's not being written again by monerod. **bitmonero.log** is updated by monerod.

Would the log be in a different place? I'm not finding it in the directory where I'm running monerod either. Was **monerod.log** a new file created in 10.3.1?

**Comment by moneromooo-monero** [comment]
The filename was changed when the daemon was renamed from bitmonerod to monerod. This was fairly recently, can't recall exactly when, maybe a few months ago.

**Comment by moneromooo-monero** [comment]
Can I assume it's been working with the patch mentioned above, and thus this bug can be closed ?

**Comment by The13thDoc** [comment]
With or without the patch, I couldn't duplicate the issue in 0.10.3.1. There are other problems occurring with 0.11.0.0 that I don't have the time to debug.
