### ISSUE TITLE
RPC call to get current Monero version?

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#1830]
I cant find how to get a version of monero daemon, e.g., `0.10.1.0-15eb2bc`. Is there some obscure rpc call for this or some other method allowing external application to get monero version of a daemon? 

This is related to this issue: 
https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/40

**Comment by moneromooo-monero** [comment]
No such RPC (and that'd allow fingerprinting so it'd have to be restricted, in which case you alrady known what you're on anyway).

**Comment by moneroexamples** [comment]
Ok thanks, for anwser.
