### ISSUE TITLE
Feature request: allow viewwallets to show if keyimage has been added

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero#1833]
If I have a view-only wallet and I add a key image to it (eg: to keep an eye on some balance that's in cold storage) there's no functionality that displays if the key image has been added.

Would it be possible to add a message like "Key image added to inputs up to blockheight 1200000" within the status of a view-wallet?

**Comment by moneromooo-monero** [comment]
It does. If you didn't see it, then maybe an error message was displayed instead ?

**Comment by xmr-eric** [comment]
Thanks
