### ISSUE TITLE
Fee using 12 decimal places

### ISSUE THREAD

**Issue by luigi1111** [monero-project/monero#1835]
Calculating fee to 12 decimal places is needlessly specific, and will likely get in the way in the future if we move to different size range proof that doesn't cover the entire field. This is because the specificity of the fee is leaving change outputs for the difference. I recommend rounding up to nearest digit at either the 6th or 8th (a la Bitcoin) decimal place.

Conversely, outputs that presently have digits smaller than 10^-6 (or 8), likely due to the above, might want to drop those digits to the fee instead, but that can be left as a future change.

**Comment by iamsmooth** [comment]
This can be closed now? Not sure the PR or commit but I believe this is implemented in the new release?

**Comment by luigi1111** [comment]
Yes.
