### ISSUE TITLE
Easy to paste only the first words of a seed when restoring

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#1849]
Since the wallet displays the seed as three lines, people tend to paste the three lines when restoring, causing the wallet to parse only a third of the seed.
Either mention it needs to be on one line, or (since poeple won't read) continue parsing till we have 24 or 25 words.

**Comment by xmr-eric** [comment]
Related to #1170 ?

**Comment by moneromooo-monero** [comment]
No. That is a terminal bug editing a line.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1984

**Comment by binaryFate** [comment]
Why is it still open if fix is merged?

**Comment by moneromooo-monero** [comment]
True. I'm not used to being the one filing a bug :)
