### ISSUE TITLE
Terminology Clarification: Stealth Address

### ISSUE THREAD

**Issue by alvinjoelsantos** [monero-project/monero#1858]
There are 4 views of what a "stealth address" means:

1. wallet address = stealth address (_because wallet addresses do not appear in the blockchain_)

2. output = one-time public key = one-time output key = output public key = stealth address (_because addresses that appears in the blockchain are not “real” addresses, but are destinations where the funds go to_)

3. “stealth address” describes the overall process of unlinkability

4. Abandon the term 

Support for view 1: http://monero.stackexchange.com/questions/2926/terminology-clarification-stealth-address

Support for view 2: https://steemit.com/monero/@luigi1111/understanding-monero-cryptography-privacy-part-2-stealth-addresses

Support for view 3: https://getmonero.org/knowledge-base/moneropedia/stealthaddress

Contributors, what is your view on this?

EDIT:
added "output public key" meaning output as well in 2 and added 4th option

**Comment by kenshi84** [comment]
3

**Comment by moneroexamples** [comment]
Stleath address is tx public key, anwser no 2.

Please have a look at fluffyponyza clarification of this issue, with examples of stealth addresses:

- https://www.reddit.com/r/Monero/comments/4wupab/why_doesnt_my_monero_address_change_after_every/d6a99dl/?context=3
