### ISSUE TITLE
Issue with GUI resizing/snapping on Windows

### ISSUE THREAD

**Issue by philkode** [monero-project/monero#1891]
The way the Windows QT borderless display works is a bit broken, in that it doesn't play nice with Windows compositor (can't be scaled to 1/2 screen by dragging to the edge of the screen or using Windows+arrow keys as per most Windows apps). It's a shame because the flat GUI looks very much at home on Windows 10 and could easily be mistaken for a Metro app if it behaved like all other Windows apps.

I found a post on StackOverflow referring to a similar issue with QT & Windows Vista's Aero compositor. An example solution was recently posted here: https://github.com/dfct/TrueFramelessWindow , not sure if this will be an applicable route for the XMR GUI but seemed to work in that instance.

**Comment by iDunk5400** [comment]
Wrong repo. You probably wanted to post here: [https://github.com/monero-project/monero-core/issues](url)

**Comment by philkode** [comment]
Yes, yes I did. Thanks.
