### ISSUE TITLE
Starting wallet rpc server

### ISSUE THREAD

**Issue by Joter85** [monero-project/monero#1906]
Our monero-wallet-rpc.exe is stucked at "Starting wallet rpc server". It doesn't move over this step. We have increased verbosity level but can't get any useful log data. Version 10.1 works without any issues with same startup parameters. 

System: Windows Server 2012 R2
Version: Monero 10.2.1 64bit

![image](https://cloud.githubusercontent.com/assets/8576660/24148872/e94aa062-0e40-11e7-98c3-1cf6f7e0b43d.png)

**Comment by amiuhle** [comment]
Is the wallet synchronized?

If you open the wallet with `monero-wallet-cli`, you should see some more progress on synchronization, I think. I would open it with cli, let it sync completely, then exit and open the wallet with `monero-wallet-rpc` again.

**Comment by Joter85** [comment]
Thanks. Because of DNS issue monerod lost all its peers. Now we have manually added IP addresses of few peers and it works ok. 

http://monero.stackexchange.com/questions/3861/why-is-monerod-not-connecting-to-any-peers
https://github.com/monero-project/monero/pull/1879

**Comment by Joter85** [comment]
Now we have manually added some peers like someone suggested here. It is now synced with network, but doesn't seem to start wallet rpc server...

**Comment by amiuhle** [comment]
Did you try with `--log-level 2` or `--log-level 4`? There's no log level 5, I don't know if that will just fall back to level 4 though.

Also you can try opening the wallet with `monero-wallet-cli`, wait for synchronization, then `exit` and try again with `monero-wallet-rpc`.

**Comment by Joter85** [comment]
Have tried with log level 4. Have restarted rpc.exe few times...

**Comment by moneromooo-monero** [comment]
Update to latest master, it's likely it's refreshing from the daemon, then pulling the (currently hefty) tx pool. The wallet now has a cache, so first load will still be slow, but subsequent ones will not be.

**Comment by Joter85** [comment]
How do I do that?

**Comment by Joter85** [comment]
Ok thanks. I have managed to start RPC server, but now we have authentication issues. Previous RPC server didn't have any authentication, is there a way to disable it? We are connecting to RPC via secure VPN tunnel, so we can have it disabled...

**Comment by vtnerd** [comment]
Yes, just remembered that @fluffypony told me to add logging to the server when it rejects requests. Its now on my whiteboard.

**Comment by moneromooo-monero** [comment]
+resolved

**Comment by FinleySmile** [comment]
It needs to sync block

![image](https://user-images.githubusercontent.com/12446331/37321588-f41715b6-26b3-11e8-80cd-26353bd63638.png)

**Comment by zeshanvirk** [comment]
i'm having the same issue, how can i fix it?
