### ISSUE TITLE
reddit submitted typo

### ISSUE THREAD

**Issue by grummerd** [monero-project/monero#1922]
Minor typo in `monero-wallet-cli` command, sweep_all
-------------------------------------------------------------------------

[`/u/moneronoob12345` writes:](https://np.reddit.com/r/Monero/comments/61cs9c/typo_in_cli_wallet/)

sweep_all sweep_all [mixin] address [payment_id] - Send all unlocked balance an address

It should be:

sweep_all sweep_all [mixin] address [payment_id] - Send all unlocked balance **to** an address

**Comment by grummerd** [comment]
`monero-wallet-cli --wallet-file=[your wallet] --password=[your password] --command help`

Then look for the sweep_all command description

**Comment by darentuzi** [comment]
pull request #1921 fixes this
