### ISSUE TITLE
Block cumulative size is too big

### ISSUE THREAD

**Issue by ddyzhang** [monero-project/monero#1926]
Following error message found in the logs after upgrading to v0.10.3.0 on one of my win64 machines:
`Block cumulative size is too big: 227915964163754343, expected less than 131522`

Daemon will not sync past block 1274262 and appears to be rejecting and then banning any node attempting to relay the next block.

All of my other machines appear to be fine. Upgraded straight from 0.10.2.1, no resync performed.

See the level 4 log file here (warning, large text file): https://derekzhang.org/uploads/monero.log

**Comment by moneromooo-monero** [comment]
Probably fixed  by https://github.com/monero-project/monero/pull/1927

**Comment by schnerchi** [comment]
are there any reports for this from other OS than win64?

**Comment by fluffypony** [comment]
@schnerchi someone on IRC reported having it on macOS, but considering we've only had 2 reports of it it's either environmental or isolated. If you're not seeing it then it doesn't matter:)

**Comment by schnerchi** [comment]
I am asking if I can test against it. mac os and ubuntu avail..

**Comment by fluffypony** [comment]
@schnerchi yes, please do :)

**Comment by schnerchi** [comment]
okay.. trying your release builds then....

**Comment by moneromooo-monero** [comment]
If you can build your own, and get the same problem, can you please do this:
- edit src/cryptonote_basic/cryptonote_format_utils.cpp
- line 46, uncomment the line: // #define ENABLE_HASH_CASH_INTEGRITY_CHECK

Then try again and see if you get integrity check fails in the log, and post the log if so.

**Comment by jakefb** [comment]
I'm having this issue too on Debian 8.7 64 bit. When I upgrade to v0.10.3.0 it worked at first and I was able to send a transaction, but when sending a second transaction I accidentally killed the daemon so it didn't successfully send and since then had this issue persistently

`2017-03-26 09:25:43.447	[P2P7]	ERROR	cn	src/cryptonote_basic/cryptonote_basic_impl.cpp:114	Block cumulative size is too big: 6691072190604965985, expected less than 131274`

**Comment by adot23** [comment]
I experienced this with a docker build of v0.10.3.0. It appears to be fixed for v0.10.3.1.

**Comment by ddyzhang** [comment]
No new reports of this issue in v0.10.3.1, appears to be fixed by #1927.
