### ISSUE TITLE
daemon output color problem

### ISSUE THREAD

**Issue by SnaiLiuS** [monero-project/monero#1934]
Screenshot shows the problem:

![default](https://cloud.githubusercontent.com/assets/22018711/24377602/94159504-1348-11e7-902e-15629f328bbf.png)

**Comment by anonimal** [comment]
Color capable terminal? OS? Distro?

**Comment by iDunk5400** [comment]
That does not look like a recent Windows 10, probably Windows 7 or 8/8.1. So even if I PRed a possible solution, it would not work for you.

![image](https://cloud.githubusercontent.com/assets/20195079/24379718/94747c68-1348-11e7-9f75-698faaf8a1f0.png)

**Comment by SnaiLiuS** [comment]
Bad dreams guys: windows vista here.

btw, wallet-cli colorization is ok, only daemon color is broken.

**Comment by anonimal** [comment]
>windows vista 6.0.6002
>0.10.1.0+

I don't see Vista in easylogging++'s [compatability list](https://github.com/muflihun/easyloggingpp#compatibility).

**Comment by hyc** [comment]
http://monero.stackexchange.com/questions/3705/monero-win-x64-v0-10-2-1-cli-questions

**Comment by tikwanleap** [comment]
I have the same problem in Windows 10 64 bit since 0.10.1.0 release. Still happening in latest 0.10.3.1 release.

In hyc's stackexchange answer (https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1050078) there is a mention needing to call the SetConsoleMode function to get this working in Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms686033(v=vs.85).aspx

**Comment by tikwanleap** [comment]
Could it be related to this issue?
https://github.com/muflihun/easyloggingpp/issues/363

**Comment by tikwanleap** [comment]
This looks like the solution.

https://github.com/bin-build/bin/commit/e4a038bb7f89b51f3eb794b83da6fa054d48900b

Apparently Windows 10 had ansi color support enabled by default at one point but more recent versions have it disabled by default.

The application needs to programmatically enable ansi color support.

**Comment by moneromooo-monero** [comment]
Any coder with Windows want to make a patch based on the above ? :)

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by dEBRUYNE-1** [comment]
+help wanted

**Comment by moneromooo-monero** [comment]
Fixed for some versions of Windows.

**Comment by lazaridiscom** [comment]
Vista is "dead" since 2 years:

https://support.microsoft.com/en-za/help/22882/windows-vista-end-of-support

So possibly its not worth to spend resources to make cosmetic things work for it.

Issue should be closable.

**Comment by moneromooo-monero** [comment]
Ah, I fixed it anwyay, since it was small stuff on top of other work I needed to do.
See https://github.com/monero-project/monero/pull/5688
I'll close this when it gets merged.
