### ISSUE TITLE
Lmdb error after disconnecting HDD

### ISSUE THREAD

**Issue by mrosseel** [monero-project/monero#1939]
Hi,

I was doing my initial sync on a raspberry pi 3 with USB HDD (1Tb). Monero 0.10.3.0 was installed on this drive (/mnt) and started with '--data-dir /mnt/monero_chain'. Everything worked fine, but after 20k blocks the HDD disconnected (not sure why). 

The next run I get this:
https://gist.github.com/mrosseel/541647833bd3983ea61c4b3155e06845

Let me know if more info is needed. Is there any way to recover this? Restarting is painful on the pi!

**Comment by hyc** [comment]
Unfortunately we don't really have a mechanism for recovering from hardware failures. It's possible that we can salvage this DB still. Find me on IRC and we can try to walk through it. You will need mdb_stat built from the monero source tree, and a binary file editor.

**Comment by iamsmooth** [comment]
This is not an issue with the code. Please close.

**Comment by moneromooo-monero** [comment]
There is a new --db-salvage option now, which might help in case of bad sector or something in the last tx writes. Otherwise, a resync from scratch on good media seems necessary.

+invalid
