### ISSUE TITLE
Issue Getting The Daemon Started

### ISSUE THREAD

**Issue by Jayhorns** [monero-project/monero#1953]
I am having a near identical issue as a user on another forum. I am trying to use the Windows 64bit version of the GUI. The application appears to have synchronized successfully after about 8 hours, but I cannot get the daemon to start. I receive this message: "Daemon failed to start. Please check your wallet and daemon log for errors. You can also try to start monerod.exe manually." However, the log does not show any message or text at all. And despite the message, the network status still says Connected and monerod is running as a background process in the task manager.

The solution that seemed to work for another user did not work for me (rename the folder that contains the monero-wallet-gui Application to "MoneroGui2").

If I run the monerod application manually, eventually I get a message that says: "You are now synchronized with the network. You may now start monero-wallet-cli."

With all that said, am I synced with the network and able to send Monero to this wallet despite the error message with the daemon?

[http://i.imgur.com/dPVB7l6.png](url)

**Comment by dEBRUYNE-1** [comment]
Could you post your issue at [this](https://github.com/monero-project/monero-core/) repository?

**Comment by Jayhorns** [comment]
I will do so now. Thanks.

**Comment by voidzero** [comment]
Feel free to close this one.

**Comment by pspitalieri** [comment]
Thanks guys, changing the path to MoneroGui2 helped. Thumbs up

**Comment by passabilities** [comment]
I was getting the same error on Ubuntu 17.04. I needed to start the daemon manually using `sudo monerod`

**Comment by passabilities** [comment]
I was getting the same error on Ubuntu 17.04. I needed to start the daemon manually using `sudo ./monerod`
