### ISSUE TITLE
Different addresses while using command <address> and <viewkey>

### ISSUE THREAD

**Issue by Lihaes** [monero-project/monero#1958]
Hey, 
while I try to get familliared with the monero-wallet, I was wondering why `viewkey` returns as I considered my Kpriv + Kpup, but `address` gets me a key different and longer than the Kpup from `viewkeys.`

What is the differnence between this two?

**Comment by moneromooo-monero** [comment]
At the risk of missing the obvious, the address is an encoded version of both public keys. Are you just comparing the string representations of both ? If so, there's your problem. If you know what you're doing and they're really different, then please give more information (ie, how you compared).

**Comment by Lihaes** [comment]
I just compared the string rep. of them. Is there a tutorial for the different keys and their representation(s)?
I found additional `spendkey` which is a further different key...

**Comment by moneromooo-monero** [comment]
Keys are hexadecimal. The address is base58. Monero uses two keys, not one as Bitcoin.
You can ask such questions on monero.stackexchange.com (search first, it might already asked and answered). Please keep github for bug reports.

**Comment by moneromooo-monero** [comment]
And please close that issue now, I can't :)

**Comment by Lihaes** [comment]
Thanks!
