### ISSUE TITLE
Error: Reason: double spend

### ISSUE THREAD

**Issue by patjnolan** [monero-project/monero#1960]
I'm trying to send money, but I get Error: Reason: double spend. I issued a rescan_bc twice and I still get the error. Any ideas on what I can do to fix this?

**Comment by moneromooo-monero** [comment]
That's probably because you ran rescan_bc. Don't run this unless you really need it.
Anyway, if you ran rescan_bc and you had an outgoing tx waiting to be mined, then you need to run rescan_spent after it as well to sync to the txpool.

**Comment by moneromooo-monero** [comment]
Known reasons for the wallet to get out of sync with real spent state are now gone, except the case where a wallet crsahes or is killed after sending, but before saving. I'm calling it fixed, the remaining case will be fixed with the lmdb wallet file.

+resolved
