### ISSUE TITLE
[Proposal for protocol change] Allowing view-only wallets to recognize outgoing transfers

### ISSUE THREAD

**Issue by kenshi84** [monero-project/monero#1963]
In a comment to a recent Reddit [post](https://www.reddit.com/r/Monero/comments/64bui4/modifying_the_viewkey_to_to_see_outgoing/dg0z26h/) by u/mirapos, @moneroexamples cited an [archived post](https://www.reddit.com/r/Monero/comments/51i0n7/solved_it_hopefully_heres_how_we_can_make_the/) by u/TheKing01 proposing an interesting protocol change that allows view-only wallets to recognize outgoing transfers.

As I understand the proposal, its essence is to pair the original output pubkey

    P = Hs(r*A)*G + B

with another kind of output pubkey

    Q = Hs(Hs(r*A))*G + A

whose secret key is

    y = Hs(Hs(a*R)) + a.

Furthermore, we redefine the key image as

    I = y*Hp(Q)

(instead of `I=x*Hp(P)`). Key images still function as before for preventing double spends, while they can be generated by view-only wallets.

# Opt-out mode

@knaccc came up with an [interesting extension](https://www.reddit.com/r/Monero/comments/64bui4/modifying_the_viewkey_to_to_see_outgoing/dg2mhia/) to this proposal where the user can opt out of this feature (i.e. allow view-only wallets to recognize incoming transfers only). A new wallet address format is introduced, consisting of a triplet of public keys `(A,B,C)` where `C=c*G` is called tentatively a "key-image view" key. With this address format, the second output pubkey is computed differently:

    Q = Hs(Hs(r*A))*G + C

whose secret key is

    y = Hs(Hs(a*R)) + c.

Passing only `(a,B,C)` to third parties (e.g. MyMonero) allows them to recognize incoming transfers only, while passing `(a,B,c)` allows them to also recognize outgoing transfers.

# Drawback

The most significant drawback is that it will double the number of pubkeys that need to be stored in the blockchain. Although the blockchain size is currently dominated by range proofs, they can be pruned. The maximally pruned bare-minimum blockchain would only store output keys and key images, so this proposal will increase the size of this bare-minimum blockchain by 50%.

----

What do you think about this proposal? Is it worth the trouble and cost?

[Poll on reddit](https://www.reddit.com/r/Monero/comments/64mvc9/poll_how_much_do_you_care_if_moneros_view_wallet/)

**Comment by moneroexamples** [comment]
Cannot comment on crypto stuff, but I always considered the viewkey showing only incoming txs as a limitation of Monero. There has been plenty of posts of users asking how to check balance of cold-storage wallet or paper-wallets. Unfortunately, often answers provided about using viewonly wallet with viewkey is incorrect.  The correct answer requires follow troublesome and probably complicated procedure for new users with setting up wallets, key images exports, importing key images, to get correct balance in a view only wallet.

**Comment by knaccc** [comment]
I think you meant for your first link to point here: https://www.reddit.com/r/Monero/comments/64bui4/modifying_the_viewkey_to_to_see_outgoing/dg0z26h/

**Comment by kenshi84** [comment]
After a brief conversation with @moneromooo-monero on IRC, now I realized that changing the definition of the key image is quite infeasible since it's not clear how we can prevent double spends with the two different definitions coexisting. Closing.
