### ISSUE TITLE
WARN ge_frombytes_vartime failed at 266 ???

### ISSUE THREAD

**Issue by bart886** [monero-project/monero#1971]
What is that warn in monerod? All blockchain is synchronized.
[P2P5]  WARN    ringct  src/ringct/rctOps.cpp:266       ge_frombytes_vartime failed at 266

**Comment by moneromooo-monero** [comment]
It tells you some part of the transaction's ringct signatures is invalid.

**Comment by bart886** [comment]
Ist`s not a bug or problem on my site?

**Comment by moneromooo-monero** [comment]
No, this is normal if you're getting a bad tx. Some older monero version code can send those (though this was before rct was enabled), so I'm assuming someone is using that. But given it still happens nowadays, something may be off. Still, there's nothing wrong with your setup based on this.

**Comment by bart886** [comment]
ok thanks
