### ISSUE TITLE
get_transfers in 0.10.3.1 is not showing out address anymore

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#1988]
Hi.

After upgrading from 0.10.1 it seems that get_transfers call has been changed and it's no longer showing for outgoing transactions destination address.

Is it an intended change or is it just a bug?

I find it very annoying not to be able to track down where particular payment has been sent to.
Thanks.

**Comment by gituser** [comment]
e.g. (in old version was):

```
"out": [{
      "amount": 6996000000000,
      "fee": 33738023280,
      "height": 835329,
      "note": "",
      "payment_id": "0000000000000000",
      "timestamp": 1485364270,
      "txid": "xxx2"
    },{
      "amount": 1008683510000,
      "fee": 35359956047,
      "height": 810690,
      "note": "",
      "payment_id": "0000000000000000",
      "timestamp": 1482345760,
      "txid": "xxx1"
    },{
      "amount": 100000000000,
      "destinations": [{
        "address": "monero_address",
        "amount": 100000000000
      }],

```

**Comment by gituser** [comment]
any update on this?

**Comment by moneromooo-monero** [comment]
I have just checked that it works. The wallet cache was probably destroyed and recreated from the blockchain, from which this data cannot be recovered (because it's not there).
Please make a new tx, and check whether addresses/amounts appear for that one.

**Comment by moneromooo-monero** [comment]
ping

**Comment by moneromooo-monero** [comment]
Since it works for me, I'll close this. Please reopen if it does not work, and is not due to the cache being missing or corrupt in some way (or the wallet being rescanned).

+invalid

**Comment by gituser** [comment]
Hi. there is another issue I've encountered lately with the latest `0.10.3.1` under load (if there is a lot of disk i/o operations) and if there was transaction sent like a minute ago or so wallet isn't saved momentally and if you restart the monero-rpc-daemon transaction isn't in the wallet anymore.

It's reproduceable - you need to load your system with a lot of disk i/o activitity and try to send some monero transaction and then after it gets mined restart the daemon.
