### ISSUE TITLE
0.10.3.1 ARMv7 binaries computing incorrect hashes and failing to accept valid blocks

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero#1991]
I am posting this here after this [discussion with hyc on stackexchange](https://monero.stackexchange.com/questions/4061/syncronisation-problem-on-geekbox-running-node-from-sd-card). Please see this discussion as all the information I have is there.

I may not be able to be much more help (not least because I'm a noob) as I followed hyc's instructions and now have a Debian OS and successfully syncing node. I can't really run any more tests I'm afraid.

**Comment by hyc** [comment]
Should also close #847 now
