### ISSUE TITLE
Know total amount  in waiting on pending TX ( change address)

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#1993]
Exemple simple for understand, I have only one TXNO for 100XMR.
Balance 100 Unlocked 100

I payout 70XMR to another addresse ( not already include on block).
Balance 0 Unlocked 0

Is impossible know amount 30XMR is waiting spend 

Is very difficults follow amount in wallet when make many payout.

**Comment by moneromooo-monero** [comment]
This is probably caused by the bug fixed by https://github.com/monero-project/monero/pull/1989

**Comment by perl5577** [comment]
No,
I want juste method for know amount in my wallet after payout.

Other exemple :
sweep_all  MYADDRESS 
balance
Balance:  0.000000000000, unlocked balance: 0.000000000000

**Comment by jonathancross** [comment]
@perl5577 Can you test the latest version now that #1989 is merged?

**Comment by moneromooo-monero** [comment]
+resolved
