### ISSUE TITLE
Watch-only wallet misreporting transactions.

### ISSUE THREAD

**Issue by 564765975** [monero-project/monero#1994]
My watch-only wallet is reporting an outgoing transaction as incoming.

This is an edited printout of the transaction from both full wallet and watch-only:

Full:

1292949 out 09:48:00 PM 0.900000000000 <tx-id removed> 0000000000000000 0.016342040000

Watch-only:

1292949 in 09:48:00 PM 0.083657960000 <tx-id removed> 0000000000000000 -

**Comment by moneromooo-monero** [comment]
Did you ever get your hot and cold wallets out of sync ?
Monero distinguishes in and out txes by checking whether a tx spends an output it owns. It can only know that if an outgoing ring has a key image matching one of its own outputs, and only the cold wallet can calculate the key images. So if you rescan the hot wallet without reimporting key images, this will happen.

**Comment by 564765975** [comment]
Yes I exported/imported the key images and it's working fine now. Thank you.
