### ISSUE TITLE
Option to save signed transaction to file from full wallet

### ISSUE THREAD

**Issue by mochaccinuh** [monero-project/monero#1999]
When doing "transfer" in a view only wallet an unsigned transaction is stored to a file. It would be nice if full wallet (with spend key) also could save transaction to file and in addition sign the transaction. This enables a full cold wallet to easily create transactions that are ready to be broadcast to the network via a hot wallet with submit_transfer.

**Comment by moneromooo-monero** [comment]
The cold wallet already saves the signed transaction to a file. Can you elaborate on what you are asking exactly ?

**Comment by hyc** [comment]
+invalid
