### ISSUE TITLE
Wrong SKEIN function selection for cryptonight implementation

### ISSUE THREAD

**Issue by Kais-DkM** [monero-project/monero#2001]
According to [this document](https://cryptonote.org/cns/cns008.txt), hash function should select SKEIN-256 at certain situation.
However, according to [crypto/skein.c](https://github.com/monero-project/monero/blob/master/src/crypto/skein.c#L20), SKEIN-256 is turned off.
Instead, [SKEIN-512 with block size 256](https://github.com/monero-project/monero/blob/master/src/crypto/skein.c#L1942) is turned on.
Is there any specific reason for this?

**Comment by fluffypony** [comment]
@Kais-DkM I wouldn't trust documents on the CryptoNote website, as they were created after-the-fact. With inherited code like this we veer more towards "the documentation is the code", and tend not to change things unless they have been found dodgy in practice or there is some suspicion of brokenness.

**Comment by Kais-DkM** [comment]
@fluffypony
Then is it document's fault for this case?
Code is reference for actively maintained project like here, but in my thought, document should be valid at same time.

**Comment by fluffypony** [comment]
@Kais-DkM we aren't connected to CryptoNote, and are far divorced from our CryptoNote origins. The inherited bits of code that still remain in the source tree are slowly being phased out (e.g. wire protocol is being replaced with ZMTP). I wouldn't rely on CryptoNote documentation to be a reflection of anything in Monero, because it isn't:)

**Comment by Kais-DkM** [comment]
@fluffypony 
Oh, then maybe I should reopen issue in CryptoNote's repository.
Closing this issue, and thank you for your response.

**Comment by fluffypony** [comment]
@Kais-DkM no problem, any time:)
