### ISSUE TITLE
Please show payment ID when signing and broadcasting transactions

### ISSUE THREAD

**Issue by moneronoob** [monero-project/monero#2007]
I use this process when using a cold wallet to sign transactions:

https://monero.stackexchange.com/questions/2160/how-do-i-use-cold-transaction-signing

Before signing or broadcasting a transaction, it tells you the amount being spent, the fee, the recipient address, the change amount, and  the change address, and then it asks you to verify it. It would be extremely nice if it also showed the payment ID as well, so that you can verify that too and make sure you haven't made any silly mistakes.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2196 does this, though encrypted payment ids are just shown to be present, as they can't be decrypted. This is something which could be improved later.

**Comment by moneromooo-monero** [comment]
Encrypted payment ids are now shown also.

+resolved
