### ISSUE TITLE
set min-output-count 10 & set min-output-value 30 unrecognized command

### ISSUE THREAD

**Issue by ocminer** [monero-project/monero#2019]
while using wallet-cli and trying to set those options I get:

[wallet XXXXXX]: set min-output-value 30
Error: set: unrecognized argument(s)

And it doesn't seem to be possible to set those values to the wallet-rpc as well

**Comment by iDunk5400** [comment]
Try `set min-outputs-value 30`.

**Comment by stoffu** [comment]
Typo fixed in #2021

**Comment by ocminer** [comment]
Thanks, output**s** works fine !

**Comment by moneromooo-monero** [comment]
+resolved
