### ISSUE TITLE
i'm import raw

### ISSUE THREAD

**Issue by PQFitz** [monero-project/monero#2027]
Hi bro,
import raw
print:
what=Aborting: chunk size exceeds buffer size

help me!!
Thank you very much!

**Comment by moneromooo-monero** [comment]
Re-run with --log-level 1, and paste the relevant new messages.

**Comment by moneromooo-monero** [comment]
I've tried recently, and it all works fine. I reckon the file was corrupted. Please reopen if it happens again and the file is NOT corrupted.

+invalid
+resolved
