### ISSUE TITLE
failed to get random outs

### ISSUE THREAD

**Issue by AJIekceu4** [monero-project/monero#2028]
Hello ALL.
Wallet: Monero 'Wolfram Warptangent' (v0.10.3.1-9ed496b)
Remote node: Monero 'Wolfram Warptangent' (v0.10.3.1-9a9fb04)

Trying to send some monero from **mining** wallet to another:

> No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
> Error: failed to get random outputs to mix: failed to get random outs

> sweep_unmixable
> Wallet password: ********
> Error: No unmixable outputs found

> sweep_all 48xxx
> Wallet password: ********
> No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
> Error: failed to get random outputs to mix: failed to get random outs

But i can successfully transfer not big amount, like 1/25 of total wallet balance.

**Comment by moneromooo-monero** [comment]
Is your daemon slow ? The wallet might be hitting a timeout. If the daemon isn't on 127.0.0.1 (but is on the local network), you may want to add --trusted-daemon, which makes that call a lot faster (at the cost of leaking some private info from the wallet to the daemon).

**Comment by AJIekceu4** [comment]
> Is your daemon slow ?

Maybe, it running on 2 cores cpu. 

> The wallet might be hitting a timeout. If the daemon isn't on 127.0.0.1 (but is on the local network), you may want to add --trusted-daemon, which makes that call a lot faster (at the cost of leaking some private info from the wallet to the daemon).

But "Error: failed to get random outputs to mix: failed to get random outs" appears after 2-3 second after transfer command. I think timeout time is much bigger than few seconds.

Anyway, i add --trusted-daemon, but nothing change. Command "sweep_unmixable" has same output, but much faster, about 2 second. But i still can not use transfer or sweep_all  because get "Error: failed to get random outputs to mix: failed to get random outs" after few seconds.

**Comment by moneromooo-monero** [comment]
Then level 2 log in both daemon and wallet, please.

**Comment by AJIekceu4** [comment]
Daemon log (my ip is 91.211.144.242):
https://paste.fedoraproject.org/paste/MeBrh4VSznks-cOvq12oal5M1UNdIGYhyRLivL9gydE=/raw

Wallet don't print any log with log_level 2 and 3, and 4

**Comment by AJIekceu4** [comment]
Thanks to moneromooo ;)
My problem was related with "--restricted-rpc" option in daemon start parameters. Without this parameter - all OK.
