### ISSUE TITLE
[Question] How to specify in url payment_id

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#2041]
Hi.

Is there any mechanism for official GUI client or is it specified in monero white paper how to specify payment_id in the url like monero:wallet_address&payment_id=XXX, so when user clicks on the url monero client picks up wallet address and payment_id as well automatically?

thank you.

**Comment by MoroccanMalinois** [comment]
http://monero.wikia.com/wiki/URI_formatting

**Comment by gituser** [comment]
thanks a lot, @MoroccanMalinois !

searched hard, but couldn't find this page :(
