### ISSUE TITLE
[BUG] integrated_address no longer allows 64 symbol hex payment_id

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#2043]
Hi.

Testing with `v0.10.3.1-release`.

```
[wallet XXX]: integrated_address 2b71cc0ffabb1d2b16112c0eaa11f5fec465abe862789219a943bc1bee391de9
Error: failed to parse payment ID or address
[wallet XXX]: integrated_address bff59eda1e4fc2f3
XXXX_address
[wallet XXX]: integrated_address 0000000000000000
XXXX_address
```

It appears to me that only 16 symbol payment_id is supported for generating integrated addresses?

Lots of exchangers are still requiring 64 symbol payment_ids. Can this be fixed for backward compatibility?

Thank you.

**Comment by moneromooo-monero** [comment]
It never did. If you need a 256 bit payment id, you use it. Integrated address use 64 bit payment ids.

**Comment by gituser** [comment]
@moneromooo-monero ok, thanks for clarifying.
