### ISSUE TITLE
Error: failed to generate new wallet: failed to save file "home/portfolio.keys"

### ISSUE THREAD

**Issue by masonsam** [monero-project/monero#2045]
Hi,
I tried to create a walet with monero-wallet-cli but i get this error
 `Error: failed to generate new wallet: failed to save file "home/portfolio.keys"`
what can i do?
this is the command:
`./monero-wallet-cli --log-level 3 --generate-new-wallet   home/portfolio`
thank you!
Fixed

**Comment by moneroexamples** [comment]
You first need to create folder called "home". 
```
mkdir home
./monero-wallet-cli --log-level 3 --generate-new-wallet home/portfolio
```

**Comment by masonsam** [comment]
I had the folder yet, i'm in ubuntu 16.4 and i put the wallet in Home

**Comment by masonsam** [comment]
I fixed it with / before path:
`./monero-wallet-cli --log-level 3 --generate-new-wallet home/portfolio`
thank you

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by moneromooo-monero** [comment]
+resolved
