### ISSUE TITLE
GUI Wallet:  Missing DLL Message

### ISSUE THREAD

**Issue by CrackBackBlock** [monero-project/monero#2046]
Getting this error message when trying to open the .exe file.  Also can't open wallet using .bat file as prompt closes immediately.  Thanks in advance for any help.

![missingdllmessage](https://cloud.githubusercontent.com/assets/28939708/26431687/710e00ec-40c4-11e7-91d2-81f4e087c799.PNG)

**Comment by nfd9001** [comment]
Try extracting a fresh copy of the latest GUI wallet release (beta2) into a different directory, then run that executable. If that doesn't work, grab a fresh copy of the archive and try again. If that doesn't work, let me know.

**Comment by CrackBackBlock** [comment]
Apparently, just had to extract to different directory and it works.  Thanks a ton!

**Comment by moneromooo-monero** [comment]
+invalid
