### ISSUE TITLE
[request] Windows environment variable for blockchain data storage location

### ISSUE THREAD

**Issue by imakiro** [monero-project/monero#2077]
Hello,

It seems that the blockchain data location cannot be easily specified on a windows machine, forcing a windows user to first launch monerod.exe with the --data-dir parameter and then launch the GUI.

It would help ease things up to do like QT and have a possible environment variable to set once and for all for the user the blockchain location.
example https://github.com/monero-project/monero-core/issues/660#issuecomment-291591638

this would allow for wallet startup at boot with a different blockchain location.

Regards

**Comment by YellowOnion** [comment]
is daemon start-up flags in GUI setting page not what you're looking for?

**Comment by moneromooo-monero** [comment]
Since it seems to be already doable as per YellowOnion's comment, I'll close.

+invalid
