### ISSUE TITLE
Can you return alternative blocks from the deamon using RPC?

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#2080]
Currently you can get number of alternative blocks using get_info rpc command

https://github.com/monero-project/monero/blob/master/src/rpc/core_rpc_server.cpp#L127

But how do you get actual alternative blocks with txs in these blocks?

**Comment by moneromooo-monero** [comment]
getblock RPC (if you know the hash).

**Comment by moneroexamples** [comment]
So what rpc call returns the hashes of alternative blocks?

**Comment by moneromooo-monero** [comment]
I don't think there's one for that.

**Comment by moneroexamples** [comment]
Ok. Thanks. I will keep the issue open for a bit.

**Comment by moneroexamples** [comment]
I will be adding such call to my local copy of monero becasue I want to add listing of alt blocks to the onion explorer. For now there is only number of alt blocks given (http://139.162.32.245:8081/), but cant view them.

If main monero project would find such rpc call interesting, could you advice what would suit best for you. For now I'm just addint it as:

```
MAP_URI_AUTO_BIN2("/getaltblocks.bin", on_get_alt_blocks, COMMAND_RPC_GET_ALT_BLOCKS)
```

**Comment by moneromooo-monero** [comment]
I think it'd be better to get just the hashes, or it could become a pretty heavy call on long running daemons. Actual blocks can be fetched from the hashes in a second call, possibly with the caller fetching by chunk of N.

**Comment by moneroexamples** [comment]
Thanks for feedback. Makes sense. So I will do as suggested. Thanks.

**Comment by moneroexamples** [comment]
I tentatively added the call. It is here: https://github.com/moneroexamples/monero/commit/ff340c5056820875b202de3d5206bab549d0e226

Any feedback appreciated. 

Its use is already being implemented in the explorer, e.g.: http://139.162.32.245:8082/altblocks

**Comment by moneromooo-monero** [comment]
That looks good, just bump the minor RPC version though.

**Comment by moneromooo-monero** [comment]
Added by the reporter.

+resolved
