### ISSUE TITLE
Compile on Centos 6

### ISSUE THREAD

**Issue by knutov** [monero-project/monero#2085]
How to compile on Centos 6?

**Comment by moneromooo-monero** [comment]
make, or make release-static

Install all the things it needs and complains about.

If errors which aren't due to missing dependencies, post here.

**Comment by knutov** [comment]
After 

yum install expat-devel openssl-devel unbound-devel libunwind-devel xz-devel xz-libs ldns-devel gtest-devel doxygen graphviz graphviz-devel boost-devel boost-static pth-devel glibc-static glibc-devel

I still can not compile this. `make` ends with 

```
CMake Error at CMakeLists.txt:48 (message):
  Could not find Boost libraries, please make sure you have installed
  Boost or libboost-all-dev (1.58) or the equivalent
```

./monero-master/build/release/CMakeFiles/CMakeError.log
ends with 
```
Run Build Command:/usr/bin/gmake "cmTryCompileExec993420673/fast"
gmake[1]: Entering directory `/vz/monero/monero-master/build/release/CMakeFiles/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec993420673.dir/build.make CMakeFiles/cmTryCompileExec993420673.dir/build
gmake[2]: Entering directory `/vz/monero/monero-master/build/release/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /vz/monero/monero-master/build/release/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec993420673.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec993420673.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec993420673
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec993420673.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec993420673.dir/CheckFunctionExists.c.o  -o cmTryCompileExec993420673 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: ld returned 1 exit status
gmake[2]: *** [cmTryCompileExec993420673] Error 1
gmake[2]: Leaving directory `/vz/monero/monero-master/build/release/CMakeFiles/CMakeTmp'
gmake[1]: Leaving directory `/vz/monero/monero-master/build/release/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec993420673/fast] Error 2
```

What should I install else?

**Comment by hyc** [comment]
Seems like a makefile error somewhere. The correct library name is "-lpthread" not "-lpthreads". Also, we shouldn't even be referencing this library at all, we should be using the compiler switch "-pthread" which tells the compiler to build thread-aware code and link to the appropriate platform-specific thread library (which isn't always named libpthread anyway).

**Comment by moneromooo-monero** [comment]
As for boost, install ALL of boost.

**Comment by NanoAkron** [comment]
Instructions for building boost are contained in readme.md

**Comment by moneromooo-monero** [comment]
The bit using -lpthreads seems to be cmake probing to see what it should use, so doesn't seem like an error. Since it seems this bug is just about needing to install boost, it's invalid.

+invalid
