### ISSUE TITLE
A better `start-gui.sh` script

### ISSUE THREAD

**Issue by oerdnj** [monero-project/monero#2088]
The start-gui.sh script has to be run from the "installation" directory now as it runs `./monero-wallet-gui`. The improved version can be called from elsewhere including linking it to `~/bin/monero-gui` (as an example).

```
#!/bin/bash
MONERO_HOME=$(dirname $(realpath ${0}))
export LD_LIBRARY_PATH=${MONERO_HOME}/libs
export QT_PLUGIN_PATH=${MONERO_HOME}/plugins
export QML2_IMPORT_PATH=${MONERO_HOME}/qml
exec ${MONERO_HOME}/monero-wallet-gui
```

**Comment by Jaqueeee** [comment]
hi @oerdnj 
The GUI repo is here: https://github.com/monero-project/monero-core
Please submit the issue there instead, or even better a PR =)

**Comment by oerdnj** [comment]
Will do, I just couldn't find the repository with the script. Thanks for the pointer.

**Comment by oerdnj** [comment]
Filled as https://github.com/monero-project/monero-core/issues/765
