### ISSUE TITLE
2 nodes crash at the same time

### ISSUE THREAD

**Issue by golangdude** [monero-project/monero#2090]
https://pastebin.com/gMmNh717

**Comment by golangdude** [comment]
Both nodes run release 0.10.3.1.

**Comment by moneromooo-monero** [comment]
Do you have a stack trace of the crash ? The stack trace in there is a previous one it seems.

**Comment by golangdude** [comment]
Unfortunately I don't have a stack trace of this crash.

**Comment by moneromooo-monero** [comment]
Quite possibly https://github.com/monero-project/monero/pull/2438

**Comment by moneromooo-monero** [comment]
That was very likely to be https://github.com/monero-project/monero/pull/2437

+resolved
