### ISSUE TITLE
build of current master fails on mac osx 

### ISSUE THREAD

**Issue by schnerchi** [monero-project/monero#2093]
I think this is stopping it : 

/dev/bitmonero/contrib/epee/include/net/net_utils_base.h:131:19: error: use 'template' keyword to treat 'as' as a dependent template name
                                        KV_SERIALIZE(as<ipv4_network_address>());
                                                     ^
                                                     template

**Comment by kenshi84** [comment]
Addressed by #2094

**Comment by schnerchi** [comment]
works!
