### ISSUE TITLE
OSX build failing

### ISSUE THREAD

**Issue by jtgrassie** [monero-project/monero#2096]
Build on OSX now failing:
`/monero/contrib/epee/include/net/net_utils_base.h:118:54: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]
                const std::type_info &type() const { return typeid(**this); }
                                                                   ^
/monero/contrib/epee/include/net/net_utils_base.h:131:19: error: use 'template' keyword to treat 'as' as a dependent template name
                                        KV_SERIALIZE(as<ipv4_network_address>());
                                                     ^
                                                     template 
/monero/contrib/epee/include/serialization/keyvalue_serialization.h:85:74: note: expanded from macro 'KV_SERIALIZE'
#define KV_SERIALIZE(varialble)                           KV_SERIALIZE_N(varialble, #varialble)
                                                                         ^
/monero/contrib/epee/include/serialization/keyvalue_serialization.h:71:63: note: expanded from macro 'KV_SERIALIZE_N'
  epee::serialization::selector<is_store>::serialize(this_ref.varialble, stg, hparent_section, val_name);`

**Comment by danrmiller** [comment]
Fixed in #2094

**Comment by jtgrassie** [comment]
#2094 fixes the build error on Mac but does it have side effects for other platforms?

**Comment by danrmiller** [comment]
I'm not the best person to speak to the substance of the change, but #2094 builds on all our platforms including non mac osx (the tests don't build but those are fixed in #2095).

**Comment by jtgrassie** [comment]
Just did a Ubuntu build and works OK there too. 
Those pesky test errors - I'll be pleased when that PR gets merged.

**Comment by kenshi84** [comment]
It should compile on other platforms since the change makes the code more conforming to the C++ standard.
