### ISSUE TITLE
Lots of warnings on OSX build

### ISSUE THREAD

**Issue by jtgrassie** [monero-project/monero#2097]
`/monero/contrib/epee/include/net/net_utils_base.h:118:54: warning: expression with side effects will be evaluated despite being used as an
      operand to 'typeid' [-Wpotentially-evaluated-expression]`

Caused by commit 072102cfd23c47d36f4d51875026339a767f22ae

**Comment by jtgrassie** [comment]
Having researched this quite a bit now it seems the only resolution is to disable the warning. The problem with that is that it may hide other future issues.
I'm happy to add the exclusion specifically for Mac builds if there is consensus.

**Comment by moneromooo-monero** [comment]
Could you share a couple of the most pertinent links please, I want to see what's said about it ?

**Comment by jtgrassie** [comment]
@moneromooo-monero there are quite a few but I think these both sum up well why the warning is being emitted and how to disable.

http://trac.wxwidgets.org/ticket/16968
https://jira.mongodb.org/browse/SERVER-17728

**Comment by hyc** [comment]
Seems like this typeid stuff is gratuitous complexity. Just treat this the way unions in C are handled - define an explicit field that you store a type identifier in (like a sockaddr's address family field). You know that's what C++ is doing under the covers anyway, and all of this C++ glue isn't actually making the code any easier to write or to understand. You still have to eventually do a switch(address_type) somewhere, when you start adding support for other types of network addresses.

**Comment by jtgrassie** [comment]
@hyc I couldn't agree more. As I never wrote the commit that introduced the warning, this PR at least gets rid of the warning rather than needing an immediate rewrite.

**Comment by jtgrassie** [comment]
@hyc how about an abstract method `type()` which returns a `std::type_info` on the class `network_address_base`. Then subclasses like `ipv4_network_address` can implement by returning `typeid(ipv4_network_address)`. Lastly `network_address::type()` can be rewritten to `return *this->type()`. 
To be honest though, I'm not enamored by the overall design in which `network_address` is subclassing a `boost::shared_ptr`!

**Comment by moneromooo-monero** [comment]
It avoids having an extraneous enum and extra functions in each derived classes that just return their own enum value. Admittedly, the extraneous code might not be too much, though.

**Comment by moneromooo-monero** [comment]
In fact, I seem to have added a get_type_id anyway, as it was needed for serialization, so the typeid one can be removed since there's already something else. I'd forgot I had had to do that.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2128
