### ISSUE TITLE
monerod "stopped working" windows 10

### ISSUE THREAD

**Issue by owen358** [monero-project/monero#2102]
I am trying to mine monero. The first step is to open monerod.  it didnt work from the command line. so i double clicked on monerod in the wondows explorer.  it started to sync but my computer turned off overnight so i am not sure if it completed or not. when i try to sync again it just says "stopped working" every time with no explanation or error message. how can i proceed. i am lost here and there seems to be no source of instructions online in spite of searching for hours. there are tutorials but none work for me. there is always an error which no one addresses, help is much appreciated.

**Comment by moneromooo-monero** [comment]
It is likely the OS crash corrupted the database. In that case, you'd have to remove it (it's called data.mdb), and monerod will restart syncing. If your computer restarts often, you may want to set monerod in db safe sync mode, which is much slower, but more resistant to windows, for instance: --db-sync-mode safe:async:5000

**Comment by owen358** [comment]
i searched in windows explorer for data.mdb but nothing came up. where is this file located?

**Comment by moneromooo-monero** [comment]
I think it might be C:\ProgramData on windows ?

**Comment by owen358** [comment]
that worked. i am now syncing the blockchain. however i have another problem. i was supposed to type this command before starting th emonerod.

" C:\monero>monero-blockchain-import.exe --verify 0 --input-file ./blockchain.raw"

since it took a couple of hours to download i forgot and started monerod before doing this.  does this matter if i do it after and not before?
 when i type the above command i get the following error?

'monero-blockchain-import.exe' is not recognized as an internal or external command,
operable program or batch file.

do i need to start the whole process again from scratch? (at this point the blockchain has almost finished syncing)

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a support chat. Try #monero on freenode, reddit, etc.

**Comment by moneromooo-monero** [comment]
+invalid
