### ISSUE TITLE
readline history is reset at every run

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#2105]
When I run monero-wallet-cli without rlwrap, command history only being remembered in the current process. If I exit and run it again, the history will be blank.

**Comment by jtgrassie** [comment]
This is by design implementation. I decided to not store history to file for potential security issues.

**Comment by moneromooo-monero** [comment]
That's a fair point, but it also kinda defeats the purpose of readline.

**Comment by jtgrassie** [comment]
Well it depends on how the cli tools are used really. If a user just starts one up, runs a command, then exits, sure it's not much benefit. But if you run the daemon non-detached, it's really useful. Or if you have your wallet open for a longer session. If you think we should persist history I could add that in though.

**Comment by moneromooo-monero** [comment]
Not sure. Your point about security is very good and I had not thought of it :/

**Comment by jtgrassie** [comment]
Whilst somewhat unrelated, one thing I wanted to add was tab-completion. This is a nice feature of readline that makes it easier for the user. We then keep from writing history to disk but its quicker to type commands.

**Comment by moneromooo-monero** [comment]
Sounds good. Someone already added a command list for rlwrap (possibly a bit out of date now though).

**Comment by jtgrassie** [comment]
I'm thinking about using the command binder instead of a list. That way it's more generic and we don't need to maintain a separate list.

**Comment by moneromooo-monero** [comment]
About history, I think you're right that it's best removed, though an option to allow it would be nice, keeping the default to not saving it. Nothing pressing though.

**Comment by moneromooo-monero** [comment]
The privacy argument is good, closing.
