### ISSUE TITLE
hashes.txt doesnt work when doing sha256sum -c ??

### ISSUE THREAD

**Issue by 2SI3NX** [monero-project/monero#2115]
The file https://getmonero.org/downloads/hashes.txt has 3 comment lines:

> This GPG-signed message exists to confirm the SHA256 sums on Monero binaries.
> 
> Please verify the signature against the signature for fluffypony in the
> source code repository (/utils/gpg_keys).

which causes the below command to not work/verify, ive realized commenting out those lines makes the command work.  funny enough if i delete the word fluffypony in the line or edit it, it will verify ok.

sha256sum -c "hashes.txt" "monero-gui-linux-x64-v0.10.3.1.tar.bz2" 2>&1 | grep OK

It would be easier if you could comment them out so that the file can be downloaded for users who want to auto-check their hashes without needing to edit the hashes.txt file

**Comment by 2SI3NX** [comment]
Also, why does gpg give bad signature?

fluffypony's siganture of: v0.10.3.1
with command: gpg --verify hashes.txt

gpg: Signature made Wed 29 Mar 2017 20:58:17 SAST using RSA key ID 1CCD4FCD
gpg: BAD signature from "Riccardo Spagni <ric@spagni.net>"

**Comment by 2SI3NX** [comment]
Has anyone investigated this issue or seen same results? please respond.

**Comment by glv2** [comment]
To check the hashes automatically with sha256sum, you can strip the signature and the message from the file before processing it:

``` bash
grep -E '^[[:xdigit:]]{64} ' hashes.txt | sha256sum --ignore-missing -c
```

**Comment by 2SI3NX** [comment]
Thanks @glv2 !!!
