### ISSUE TITLE
Trouble with Windows 10 GUI Wallet and CLI monerod

### ISSUE THREAD

**Issue by DavidJNowak** [monero-project/monero#2136]
Help!
I would like to run a monero full node on the blockchain.

I downloaded both the "Windows, 64-bit (GUI Beta 2)" and the "Windows, 64-bit (Command-Line Tools Only)" from https://getmonero.org/downloads/.

When I started the GUI version, it askes for my wallet and password.  Then the program goes and looks for the server.  When I can not find the server, it puts up a dialog box wht the message: "Daemon failed to start.  Please check your wallet and daemon log for errors. You can also try to start monerod.exe manually.".

Then I opend a cmd window, changed directories to the directory I unzipped the CLI programs into.  I received a warning and failures message.

I have include screen dumps of each.

My next step would be to recompile the monerod from scratch, but I am not a programmer.  I did install msys2, but am unfamiliar with how to download and compile the code from github.

Please help me.
![monero daemon start message](https://user-images.githubusercontent.com/13257104/27756970-349b4ea8-5db1-11e7-8362-09d4323f7ce4.PNG)
![mymonerowallet not connect window](https://user-images.githubusercontent.com/13257104/27756972-38e71d8e-5db1-11e7-87f4-3669edf7a9af.PNG)
![monerd windows startup failure](https://user-images.githubusercontent.com/13257104/27756988-58b509b4-5db1-11e7-9930-6379e95cfdc6.PNG)
![monerd windows startup and import failures](https://user-images.githubusercontent.com/13257104/27756990-5d51d97a-5db1-11e7-99c8-1a198eba1fc7.PNG)

**Comment by Jaqueeee** [comment]
Looks like your database is corrupt. Did you have a crash prior to this?
Remove the lmdb folder` C:\ProgramData\Bitmonero\lmdb` and restart monerod and it should start syncing.

**Comment by moneromooo-monero** [comment]
Corrupt DB, so not a bug.

+invalid

**Comment by moneromooo-monero** [comment]
+resolved
