### ISSUE TITLE
Miner power supply

### ISSUE THREAD

**Issue by mehtaphysical** [monero-project/monero#2143]
I'm getting an error when attempting to mine on linux:
```
uname -a
Linux fichte 4.11.6-3-ARCH #1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux
```

Error:

```
2017-07-02 16:27:15.516	    7f45517fa700	ERROR	miner	src/cryptonote_basic/miner.cpp:829	Couldn't find battery/power status file, can't determine if plugged in!
```
Seems like the issue comes from here: https://github.com/monero-project/monero/blob/421a6d0340527fe23c1b10cfd20769555afffb1b/src/cryptonote_basic/miner.cpp#L849. The paths to check battery status are hard coded.

Also, others appear to be having this issue: https://forum.getmonero.org/5/support/87704/mining-issue-on-linux and https://www.reddit.com/r/Monero/comments/61yy9s/essential_update_monero_01031_wolfram_warptangent/dfkczl0/

I can submit a PR to fix this if it is welcome.

**Comment by moneromooo-monero** [comment]
A good patch for this would be welcome, yes. Thanks.

**Comment by mehtaphysical** [comment]
Cool. added #2144
