### ISSUE TITLE
readline: some commands are ignored

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#2150]
Sometimes, commands are ignored. Press enter after a command, and nothing happens. A subsequent command will be executed, so it's not like it's timing out waiting on a lock (this can happen, and is something unrelated entirely - when needing the blockchain lock while syncing, for instance). Might be related to #2117. This is rare-ish, but happens a few times daily.

**Comment by jtgrassie** [comment]
Was the command added to the history though? That might help isolate whats going on.

**Comment by moneromooo-monero** [comment]
I don't know. If it happens again, I'll check and report.

**Comment by moneromooo-monero** [comment]
It does. I just tried it, running commands a, b, c, d... q was not run (ie, I did not get an error for q), but it got added to the history.

**Comment by jtgrassie** [comment]
Right, so if it's adding to history, is readline verified as the problem? Reason I say is this... to get added to history, the condition var would notify and get_line would return the command to calling code.

**Comment by jtgrassie** [comment]
`q` for some odd reason appears to be translated to quit/exit for me.

**Comment by jtgrassie** [comment]
Unknown commands are certainly showing funky results though. Sometimes the cursor is midway inside the prompt. That maybe a red herring but I'll take a look at fixing that anyway.

**Comment by jtgrassie** [comment]
OK so q is a valid command for exit:
```
else if(0 == command.compare("exit") || 0 == command.compare("q"))
```

**Comment by jtgrassie** [comment]
Unknown commands should always print usage though so something amiss.
```
          else
          {
            std::cout << "unknown command: " << command << std::endl;
            std::cout << usage;
          }
```
I suspect our readline buffer is not in the correct state. I'll do more tests anyway.

**Comment by moneromooo-monero** [comment]
Ah, I'd forgot about that :) Still, it should have quit, and it didn't.

**Comment by moneromooo-monero** [comment]
q is actually a dud command, it never quits here. I guess something else compares with "exit" elsewhere. I'll try to repro again.

**Comment by moneromooo-monero** [comment]
I can get it to happen while I'm syncing, so while the blockchain lock has high contention (and the commands wait for that lock). if I send two commands in quick succession, like "status" and "print_cn" just after a "Synced" message. I'll only get the status output. I'd need to revert all the readline stuff again to double check it does work then though, since while I don't remember that being the case in the past, I don't think I particularly tried to do this.

There's also some weird extra characters sometimes popping up on messages. I'd never seen that before, and I'm in a mind to blame the readline patches, but I do not have clear evidence they're related:

T�Height: 4401/947885 (0.5%) on testnet, not mining, net hash 340 H/s, v1, up to date, 2(out)+0(in) connections, uptime 0d 0h 2m 16s�

Usually, I only see the one extra char at the end. I'd never seen them at start of line before. Maybe it's the readline prompt getting printed at the same time as the actual output ?

**Comment by moneromooo-monero** [comment]
Delays exiting are fine, as long as you see a "Stop signal sent" message.

**Comment by jtgrassie** [comment]
When exiting wallet or daemon? I only ever see that output when stopping the daemon. The wallet doesn't output the message when exiting.

**Comment by moneromooo-monero** [comment]
Actually, I was too cynical. After rebuilding without readline, the problem still happens, so it's inherited.
I don't get any extra characters though, so those two things are unrelated.
I can either change the bug subject, or close and reopen.

**Comment by moneromooo-monero** [comment]
I was exiting the daemon.

**Comment by jtgrassie** [comment]
> I can either change the bug subject, or close and reopen.

It would be helpful for me if the character issue can be it's own issue, so recommend closing this. I'm struggling to keep track of the specific issue!

Thanks

**Comment by moneromooo-monero** [comment]
Done, I've created two separate bugs for those, and added my testing without readline for the ignored command one.

**Comment by jtgrassie** [comment]
Many thanks
