### ISSUE TITLE
some commands are ignored if entered in quick succession

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#2155]
Sometimes, commands are ignored. Press enter after a command, and nothing happens. A subsequent command will be executed, so it's not like it's timing out waiting on a lock (this can happen, and is something unrelated entirely - when needing the blockchain lock while syncing, for instance).This is rare-ish, but happens a few times daily. This happens with or without readline. A good test is to sync from scratch, ensuring some good load, then quickly enter "status" and "exit". status will execute after a delay once it's got the blockchain lock, and exit will never run.

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by moneromooo-monero** [comment]
I'll say this is fine, it's serial, and the "apparent" problem is really readlin displaying the prompt too early, making you think you can enter a new command.
