### ISSUE TITLE
Extraneous characters on daemon output

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#2156]
There are some weird extra characters sometimes popping up on messages. I'd never seen that before, and I'm in a mind to blame the readline patches, but I do not have clear evidence they're related:

�T�Height: 4401/947885 (0.5%) on testnet, not mining, net hash 340 H/s, v1, up to date, 2(out)+0(in) connections, uptime 0d 0h 2m 16s�

Usually, I only see the one extra char at the end. I'd never seen them at start of line before. Maybe it's the readline prompt getting printed at the same time as the actual output ?

**Comment by jtgrassie** [comment]
Can you test with #2159 please?

**Comment by moneromooo-monero** [comment]
I still got it to happen (running "status" in monerod till it happens while it syncs).

**Comment by jtgrassie** [comment]
Hmm. If this is readline related, I'm sure it would be to do with the terminal color sequences.
The extra characters are hex EF BF BD.
https://codingrigour.wordpress.com/2011/02/17/the-case-of-the-mysterious-characters/

The only time our readline code adds readline color sequences is in the wallet cli which prints a color prompt. However you are in the daemon, which doesn't get a color prompt. Plus, the status message which is getting these extra chars is actually not touching libreadline, just our streambuf which simply gets synced to stdout.

All this said, a quick test on the theory:

> Maybe it's the readline prompt getting printed at the same time as the actual output ?

Would be to place a lock at the start of `readline_buffer::set_prompt`
  
```diff
void rdln::readline_buffer::set_prompt(const std::string& prompt)
{
+  std::lock_guard<std::mutex> lock(sync_mutex);
```
which I think it should have anyway.

**Comment by jtgrassie** [comment]
I have added the synchronization lock to #2159

**Comment by moneromooo-monero** [comment]
Annoyingly, I can't reproduce that without your patch in the first place right now, so it's hard to tell whether it'd fix it. I'll continue on and off trying to find a good way to repro.

**Comment by jtgrassie** [comment]
Annoyingly I have never managed to produce it but there are soo many variables with term setup mixed in.

That sync lock was needed anyway.

Hope you're enjoying the tab completion as much as I am btw ;)

**Comment by moneromooo-monero** [comment]
After a few minutes of trying to repro this with the lock, I've not seen it happen again yet.
And yes, tab works well here :)

**Comment by moneromooo-monero** [comment]
BTW, my TERM is xterm-256color, and wider than 80.

**Comment by moneromooo-monero** [comment]
I've not seen it happen in a while now. I'll reopen if I see it again.

+resolved
