### ISSUE TITLE
Loading blockchain on startup

### ISSUE THREAD

**Issue by jtgrassie** [monero-project/monero#2161]
`src/cryptonote_core/cryptonote_core.cpp:323	Loading blockchain from folder...`

This can take quite a few minutes and there is zero user feedback. Might be nice to have some kind of progress indicator.

**Comment by moneromooo-monero** [comment]
While it's "stuck", get a stack trace for all threads. Chances are it's timing out on some network call.

**Comment by moneromooo-monero** [comment]
I had that problem today, and it was indeed a DNS call, looking up dynamic checkpoints. Guess it's worth adding a message for that.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2230

**Comment by moneromooo-monero** [comment]
+resolved
