### ISSUE TITLE
Background mining options not accepted

### ISSUE THREAD

**Issue by alejandorr** [monero-project/monero#2163]
Two symptoms, not sure if the root problem is the same:

1) Issuing e.g. --bg-mining-idle-threshold 80 in the command line says that the value is not valid for the option.

2) Starting bg mining from the daemon console works (once the threshold is reached), but when requested from the command line, the idle threshold is never reported, and bg mining never actually starts.

Both tested in 0.10.3.1 and HEAD, ubuntu 16.04 x64

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2169 fixes the first. It might fix the second, but I'm not sure what you did exactly, so if it doesn't, detail your steps.

**Comment by alejandorr** [comment]
Confirming that options are now accepted, thanks. Still, bg mining is not working from command line, but I will open a separate issue that clarifies the problem.
