### ISSUE TITLE
Make it possible to generate multisig address via the Monero RPC JSON API

### ISSUE THREAD

**Issue by CameronRuggles** [monero-project/monero#2175]
So when multisig gets here, it would be good if we could use the JSON API to send/recieve the info needed to form an integrated multisig address. Is this possible? If not, how can we make it possible?
This seems like it'll be the easiest and quickest way to get monero multisig marketplaces to market. I believe that will dramatically increase the usability and adoption of Monero.

As multisig is already being developed it should be fairly easy to also get it to work with the API?

Sorry if this issue is poor etiquette or done improperly, not really sure the best way to create an issue/feature request, but this is incredibly important. Likely I'll be using it to implement monero multisig in annularis, which is free and open source marketplace software.

**Comment by moneromooo-monero** [comment]
There is no RPC for multisig, but I'll add it.

**Comment by CameronRuggles** [comment]
Awesome! I'm not a coder  but if there is anything I can do to help let me know. 
When do you think this will be implemented and where do I go to watch the code development?

**Comment by moneromooo-monero** [comment]
I don't know when, but the code will be PR'd in this repo (most likely in a new PR, rather than tacked on the current multisig one).

**Comment by CameronRuggles** [comment]
Great thanks. Will look into it :)

**Comment by CameronRuggles** [comment]
Also does it seem complicated to do? Just curious since you've started on it and have looked around it a bit. 

Thanks again. Extremely excited about Monero and all the implications it has once it gets multisig, and this is just a great step forward.

**Comment by moneromooo-monero** [comment]
No, that is not complicated.

**Comment by lessless** [comment]
@monero-project what's the progress with this one?

**Comment by moneromooo-monero** [comment]
There is multisig RPC in my multisig2 branch. If you have comments about it, feel free.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2134 now has full RPC for N-1/N as well.

**Comment by moneromooo-monero** [comment]
+resolved
