### ISSUE TITLE
monero-wallet-rpc now prompts for password if none is supplied

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#2179]
It would previously error out. I think that was better, since it allows starting unattended (if a --password or --password-file is supplied, obviously). Opinions ?

**Comment by moneromooo-monero** [comment]
Actually, it also asks if the wallet being loaded has no password, so this needs changing anyway.

**Comment by Timo614** [comment]
Just to write down my understanding of this and confirm the behavior we want:

- No `--wallet-file` and no password is passed in it asks for the wallet name
  - Wallet name exists? Asks for password and if valid logins in; failure invalid password message
  - Wallet name does not exist? Asks user if they'd like to make it and asks them for a password for the wallet
- `--wallet-file` specified with a password
  - If password is correct logins
  - If password is invalid fails with an invalid password message
- `--wallet-file` not specified with a password
  - Asks for password and if valid logins in; failure invalid password message

So the behavior here we're trying to fix is for the case of a `--wallet-file` that expects no password?
`--password ""` can handle that at the moment but it's less immediately obvious with a wallet with no password that you'd need to supply it in that way.

So the correct behavior here is to just treat the lack of the password as if the password was empty in the place of asking for one? If so sounds good.

**Comment by moneromooo-monero** [comment]
I think the best would be to have an --prompt-for-password flag, to allow monero-wallet-rpc to prompt. The problem I have with prompting is that tools like monero-wallet-rpc are supposed to be used in scripts (ie, a restart script), and/or without a human at the console, so you usually don't want them to prompt and wait till they get some input.

**Comment by moneromooo-monero** [comment]
+resolved
