### ISSUE TITLE
[BUG] monerod halts on x64 4.11.9-1-ARCH at seemingly random times

### ISSUE THREAD

**Issue by JollyMort** [monero-project/monero#2180]
Happened 2 times, first time on release build (moneromooo's sync-hit branch, but it happened before on tagged ver.), second time on debug build. Monerod just stops responding at seemingly random time and cpu drops to 0. 

```
$ top -H -p 12876

top - 23:34:23 up 3 days,  2:49,  1 user,  load average: 0.40, 0.50, 0.47
Threads:  25 total,   0 running,   0 sleeping,   0 stopped,   0 zombie
```

Log1: https://paste.fedoraproject.org/paste/Du9z1KQfcTTwIjjLNG4mgw/raw
Log2: https://paste.fedoraproject.org/paste/2ZopyB3vj9dwHYiITlo1fw/raw

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by knaccc** [comment]
I'm experiencing the same issue on a fresh install of Fedora 26. 

gdb output: http://termbin.com/eh7h

gcc version: 7.1.1 20170622 (Red Hat 7.1.1-3)

glibc version: 2.25-9.fc26

**Comment by JollyMort** [comment]
I'm running 335681896a8ea6142a4331aa203ce728d507265c, seems like it's more stable for me. Honestly, didn't pay attention but I don't recall it stopped like before and it's been running for days.

**Comment by hyc** [comment]
Based on #2323 and @knaccc confirming that glibc 2.25 is being used, this is clearly a bug in glibc. We should be able to close this or #2323 now, yes?
