### ISSUE TITLE
show_transfers missing entries during a transfer completion

### ISSUE THREAD

**Issue by evanrinehart** [monero-project/monero#2202]
Step 0. Open your local monero-wallet-cli with a sync-ed up monerod running.

Step 1. Send monero from kraken to your wallet.

Step 2. show_transfers will eventually show something like this:
```
[wallet ????????]: show_transfers
    pool     in      10:11:19 PM      1.000000000000 <transaction hash> 0000000000000000 -
[wallet ????????]:
```

Step 3. After a while, show_transfers forgets about this momentarily:
```
[wallet ????????]: show_transfers
[wallet ????????]:
```

Step 4. Luckily, this is only temporary. When the transfer is complete, it comes back.
```
Height 1361000, transaction <transaction hash>, received 1.000000000000
[wallet ????????]: balance
Balance: 1.000000000000, unlocked balance: 0.000000000000
[wallet ????????]: show_transfers
 1361000     in      10:11:19 PM      1.000000000000 <transaction hash> 0000000000000000 -
[wallet ????????]:
```

**Comment by moneromooo-monero** [comment]
Thanks for the detalied report, fixed in https://github.com/monero-project/monero/pull/2203

**Comment by moneromooo-monero** [comment]
+resolved
