### ISSUE TITLE
When sending to integrated address via cold signing, confirmation shows normal address + paymentID

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#2221]
When sending to integrated address via cold signing functionallity, the confirmation (after signing) is very confusing. It splits the integrated address into normal address + paymentId.

to verify the address is still correct, the User will need to decode the integrated address into normal address + paymentId himself, and compare with the confirmation message.

the desired way would be to show the original integrated address inside the confirmation.

This affects CLI and GUI wallet in the same way

**Comment by moneromooo-monero** [comment]
That'd a bit annoying since the payment id is encrypted already, so not known at that time. It'll need passing unencrypted address manually.

**Comment by moneromooo-monero** [comment]
+resolved
