### ISSUE TITLE
Name the 3rd quarter 2017 release

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero#2265]
The next element in the list is Helium (we stepped out the list for Wolfram Warptangent, which was an honorary release), and we have the following options:

Helium Hanny
Helium Hardcastle
Helium Hercules
Helium Hoag
Helium Holmberg
Helium Horologium
Helium Horseshoe
Helium Hucra
Helium Hydra

Input required, hopefully we'll get some clear consensus on the name in the next week or so:)

**Comment by bullno1** [comment]
No Hail Hydra?

**Comment by DaveyJonesXMR** [comment]
Helium Hydra - if you take away one output , few more shall rise :p

**Comment by rusticbison** [comment]
Helium Hydra has a nice ring to it.

**Comment by BitOfWisdon** [comment]
Helium Hydra

**Comment by pajasevi** [comment]
Helium Hydra

**Comment by MaxXor** [comment]
Helium Hydra 👍

**Comment by RawlzSec** [comment]
All hail Helium Hydra

**Comment by werdnalien** [comment]
Helium Holly

**Comment by DonChals** [comment]
Helium Horseshoe

**Comment by Hohhle** [comment]
Helium Hydra 
These words flow off the tongue.

**Comment by lethos3** [comment]
Helium Hydra.

**Comment by serhack** [comment]
Helium Hydra

**Comment by Makkari-A** [comment]
Helium Hydra!!!

**Comment by LordMajestros** [comment]
Helium Hydra

**Comment by Makkari-A** [comment]
:)

**Comment by madLyfe** [comment]
Helium Hootenanny

**Comment by mariodian** [comment]
How about Helium [Humongous](https://www.youtube.com/watch?v=RzA4dCT4X0I)? LOL

I like Helium Hydra too.

**Comment by janowitz** [comment]
How about Helium Hoax? :)

However if it doesn't find consensus, I'm also for Helium Hydra...

**Comment by antanst** [comment]
Oh, bikeshedding!

Helium Hydra of course.

**Comment by renecannao** [comment]
Helium Hydra

**Comment by medusadigital** [comment]
Helium Hydra

**Comment by afighttilldeath** [comment]
Helium Helix (not listed but like the name)

**Comment by anonimal** [comment]
Helium Hacker

**Comment by denk0815** [comment]
Helium Hydra.

**Comment by jtgrassie** [comment]
Helium Hydra

**Comment by 2Xest** [comment]
Helium Hydra

**Comment by brinstarnetworks** [comment]
all heil Helium Hydra~

**Comment by ViolentlyPeaceful** [comment]
Helium Hydra

**Comment by binaryFate** [comment]
Helium Hydra, because all others don't flow well

**Comment by KeeJef** [comment]
Helium Hardcastle. Because it Sounds very strong and proper

**Comment by M5M400** [comment]
Hail....erm... Helium Hydra

**Comment by vdo** [comment]
Helium Hydra

:dragon_face:

**Comment by sunday-afternoon** [comment]
Helium Horseshoe

**Comment by Gingeropolous** [comment]
"Helium Hydra". As others have mentioned, the hydra component does convey the anti-fragile / decentralized nature of the Monero cryptocurrency. As people become more aware of Monero, maintaining this decentralization will become more and more important as centralizing forces seem to coincide with increased adoption... at least that seems to be the way things happened in bitcoin. 

Basically, I feel this name will inspire continued development towards making the protocol, network and software even more robust. In this way, it points to the future of Monero.

It also points to the past - this effort has been attacked in multiple ways throughout its 3 year existence, yet it is still here. ( insert Morpheus speech in the temple clip ).

**Comment by ferretinjapan** [comment]
No Heilium Hitler? Damn savages!

**Comment by tufcos** [comment]
Helium Hydra.

**Comment by NanoAkron** [comment]
Helium Helix?

**Comment by BitOfWisdon** [comment]
Helium Hydrogen?

**Comment by johnalanwoods** [comment]
Helium Hydra

**Comment by peanutsformonkeys** [comment]
Side-stepping from the periodic table, how about the "Unknown Amount" release?

**Comment by luijoy** [comment]
Helium Hardcastle, but looks like Helium Hydra has it by this point.

**Comment by endorxmr** [comment]
Helium Hydra!

**Comment by cryptochangements34** [comment]
There seems to be a pretty clear consensus that Helium Hydra is the only way to go

**Comment by qral** [comment]
Helium Hydra

**Comment by panopolis** [comment]
Helium Hydra

Although I also suggest 
Helium Homunculus

**Comment by fluffypony** [comment]
Helium Hydra it is:)
