### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by gaud247** [monero-project/monero#2278]
All of a sudden my gui stopped working on my mac.. im up to date on all mac updates .. i run pia vpn.. and mcafee antivirus... specific prob is my monero gui does not connect to daemon anymore .. i try local and i try node.moneroworld.com.. i think ive tried everything a guy w very limited tech background can try .. if anybody can help i would very much appreciate ite it .. thank u

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help channel. Try https://reddit/r/monero or #monero on freenode IRC, or the Monero thread on bitcointalk.org. You'll have to give them more information though (ie, any errors you get, symptoms, anything else that seems relevant).

+invalid
