### ISSUE TITLE
How `payments <payment_id>` should work?

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#2304]
Based on this thread, https://www.reddit.com/r/Monero/comments/6ttr7r/developer_questions/

and I checked that `payments <payment_id>` only shows payments made into your wallet, not payments from you. So I wonder if this is intended behaviour or a bug?

**Comment by moneromooo-monero** [comment]
It is intended.

**Comment by moneroexamples** [comment]
Ok, thanks.
