### ISSUE TITLE
submit_transfer fails

### ISSUE THREAD

**Issue by PsychicCat** [monero-project/monero#2305]
I created a tx with transfer [hot] / sign_transfer [cold] / submit_transfer [hot]. I get this log in monero-wallet-cli when I try submit_transfer.

`Error: transaction <txid> was rejected by daemon with status: Failed`

In monerod, I set_log 1 and this is all I get:
`2017-08-17 21:58:05.151 [RPC0]  WARN    daemon.rpc      src/rpc/core_rpc_server.cpp:603 [on_send_raw_tx]: tx verification failed`

Any ideas?

Update: I just realized that my hot wallet was not fully up to date on key images when I created the unsigned transfer. Could that be it? Maybe it was trying to send something that had already been spent.

**Comment by moneromooo-monero** [comment]
in monerod: set_log 1
You'll see why it failed just before that line.

**Comment by PsychicCat** [comment]
Indeed, now I see it. "Key image already spent in blockchain".
