### ISSUE TITLE
unbound, osx, ranlib warning

### ISSUE THREAD

**Issue by jtgrassie** [monero-project/monero#2308]
```
[ 56%] Linking C static library libunbound.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libunbound.a(checklocks.c.o) has no symbols
```

**Comment by moneromooo-monero** [comment]
This file seems to be empty if USE_THREAD_DEBUG is not defined, so that's fine.

**Comment by moneromooo-monero** [comment]
Invalid seems a bit wrong for a report that's correct, but not actually a bug (or not something we want to fix), but looks like the closest we have.

+invalid
