### ISSUE TITLE
Set max log size for daemon

### ISSUE THREAD

**Issue by smccloud** [monero-project/monero#2321]
I would love the ability to set a max log size for the daemon on my machine.  I have it installed as a Windows service, but I do not want to have to stop it and restart it every so often just to clear out the log file.

**Comment by moneromooo-monero** [comment]
Log files are rotated every 100 MB. You can then auto remove the log files with the same name with an extra -* suffix (ie, instead ~/.bitmonero/bitmonero.log-* or wherever it is on windows).

**Comment by moneromooo-monero** [comment]
+easy

**Comment by moneromooo-monero** [comment]
+resolved
