### ISSUE TITLE
[Idea] Flush stale tx from the mempool if any of its key images have been flagged as spent

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero#2325]
A situation might occur where a user first sends a transaction with the lowest fee and then decides to re-send the same transaction with a higher fee (because the prior tx didn't get confirmed quickly). If the latter tx gets confirmed, the former tx will continue to exist in the mempool until it expires after 24hrs.

Perhaps it's a good idea to make the daemon automatically drop such txes to reduce the cost of relaying etc?

**Comment by moneromooo-monero** [comment]
It's not clear to me whether that would facilitate double spending attacks.

**Comment by NanoAkron** [comment]
@stoffu @moneromooo-monero it would prevent some mempool flooding attacks though

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2509

**Comment by stoffu** [comment]
Thank you, @moneromooo-monero!
