### ISSUE TITLE
Which exchange can buy monero? 

### ISSUE THREAD

**Issue by algorithmcode** [monero-project/monero#2341]
Bitfinex?
BitYep?

**Comment by mongakshay** [comment]
I use bittrex.com

**Comment by anonimal** [comment]
A list here: https://getmonero.org/community/merchants/

Also, probably better to ask on /r/Monero (this is a dev issue tracker).

**Comment by moneromooo-monero** [comment]
Also https://monero.stackexchange.com/questions/1201/what-options-are-available-for-directly-buying-monero-with-fiat-currency

+invalid
