### ISSUE TITLE
add-exclusive-node appears broken

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#2346]
The --add-exclusive-node option is supposed to only connect to the specified node or nodes (I think it can be specified multiple times). This may be done for security reasons, including to only connect to friendly nodes and prevent the deamon IP from appearing in foreign nodes' connection tables.

When using --add-exclusive-node I can see the daemon still attempting to connect to other nodes. My guess would be this was due to some of the other p2p enhancements (such as anchor nodes, etc.) not recognizing the exclusive node option.

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by moneromooo-monero** [comment]
This seems to be the "gray list housekeeping" code, which will try to connect to check whether a given node is up. This will not lead to an actual connection "full" connection, as it gets dropped if succesful (and the node moved to the white list). I'll disable this when an exclusive node is set.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2428

**Comment by radfish** [comment]
Is @osensei 's explanation on #848 no longer apply?

**Comment by iamsmooth** [comment]
@radfish #848 is a different issue. That refers to incoming connection this issue to outgoing.

It appears this issue is fixed by the above mentioned 2428 once that is merged.

**Comment by moneromooo-monero** [comment]
+resolved
