### ISSUE TITLE
Too big amounts are sent and received back for every transaction.

### ISSUE THREAD

**Issue by miningpoolhub** [monero-project/monero#2351]
Hi
I am running monero pool.
https://monero.miningpoolhub.com

When I send 1 XMR to some address, 1000 XMR is sent and 999 XMR gets back.
I know why it works like this but I need to payout many many miners and I have to wait several minutes to confirm the change amount.
So many payouts are delayed more than a day currently.

I already asked about this issue few months ago at forum and couldn't get clear solution.
What can I do to reduce this happening?

Maybe increase/decrease mixin parameter helps?
Divide wallet?
Is there sendmany like API that supports paymentId?

**Comment by moneromooo-monero** [comment]
You can send 50 monero 20 times in one tx to yourself (make sure you have set merge-destinations to 0 first). This will break up the 1000 output.
Also set min-outputs-count and min-outputs-value to, say, 20 and 10, see the commit message for 0ad87db01f19eff22ab9c3998826b7aa943975cf for an explantion of how they work. Last, you can pay several destinations in the same tx, which means no intervening change. Payment id is per tx, so if you have two payment ids, you have to make two txes at least. Just make the payout limit higher for people with a payment id.

**Comment by miningpoolhub** [comment]
@moneromooo-monero 
Thank you for detailed answer.
Is there any way to set min-outputs-count and min-outputs-value to simplewallet rpc?

I searched and read source code but still bit confused that there's no way to set those variables for rpc simplewallet. Those info seems like to be saved in wallet file itself but don't know how to set from outside.

**Comment by moneromooo-monero** [comment]
Yes, you did it right.

**Comment by miningpoolhub** [comment]
Thanks!
