### ISSUE TITLE
Moneroj has yet to appear in GUI wallet - 8 weeks

### ISSUE THREAD

**Issue by DoctorCarlo1955** [monero-project/monero#2359]
Operating in Windows 7 Professional 64-bit on an 8-core AMD FX 3.1 GHz processor and 16GB memory, running the operating system alone on a 128GB SSD.  Dual boot with Linux Manjaro on its own 64GB SSD.  Run the GUI wallet on both but can not get the "Blocks Remaining" to count-down.  Been working on this since July 6th.  Even reinstalled Windows.  I have changed the block-sync-size to 20.  Instead of localhost, have tried node.moneroworld.com.  Have tried logging in at log level 2.  Out of a hundred attempts, the "Blocks Remaining" have counted down at a visible rate about five times for about five minutes.  I just hope that I am in the right place to get help; I have tried several other forums, etc. but my problem remains a mystery.

**Comment by moneromooo-monero** [comment]
Nope, this is a bug tracker. Try #monero on Freenode, that's a good place to get help getting things to work. Just make sure you're using 0.10.3.1.

+invalid
