### ISSUE TITLE
Error: failed to generate new wallet: failed to save file "testWallet.keys"

### ISSUE THREAD

**Issue by Edoin** [monero-project/monero#2369]
I have deployed a copy of monero for linux in centos 7 with version `Monero 'Wolfram Warptangent' (v0.10.3.1-release)`. 

I have finished synching with the mainnet using `./monerod --detached` and finished in 2 days. 

Now I am trying to create a wallet and it gives me this error `Error: failed to generate new wallet: failed to save file "testWallet.keys"` and this is my code

```./monero-wallet-cli --log-level 3 -- generate-new-wallet testWallet```

I am now stuck in this error and trying to figure out what are the missing files since I just followed what is on the documentation <https://www.monero.how/tutorial-how-to-speed-up-initial-blockchain-sync> without using the `sync boost` module. Thanks in advance.

**Comment by moneromooo-monero** [comment]
Do you have write permissions in . ?

**Comment by moneromooo-monero** [comment]
Ping. If no reply, I'll assume you do not and close.

**Comment by moneromooo-monero** [comment]
Looks like typical filesystem permission error.

+invalid

**Comment by AMatiasC** [comment]
Hi, sorry! but i have the same error. I was changing permissions but I could not find the solution. The error is as follows:
"Enter the number corresponding to the language of your choice: 1
Error: failed to generate new wallet: failed to save file "test-etn.keys".

Please, help me! 
Thanks!
