### ISSUE TITLE
Able to send transaction with mixin of 2 on v0.11.0.0 release

### ISSUE THREAD

**Issue by campassi** [monero-project/monero#2415]
[wallet 44x44x]: `transfer unimportant 3 44x44xVLyWTcEqPFMBAWCd9vq5K2mt5C6EDpje5WKZVxL9wyEaAVVX5fXSrPu5Wih8JiqueYqEh6tWAfWQJkhU1v4JCmJ4K .05`
Wallet password: **
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
Failed to check for backlog: no connection to daemon
Is this okay anyway?  (Y/Yes/N/No): y
Sending 0.050000000000.  The transaction fee is 0.003365050000
Is this okay?  (Y/Yes/N/No): y
Transaction successfully submitted, transaction <1412ed7dd4d6df7f7d2be9ec16afb7c87c60b6733848979c3b44549983ce19e8>
You can check its status by using the `show_transfers` command.

http://moneroblocks.info/search/1412ed7dd4d6df7f7d2be9ec16afb7c87c60b6733848979c3b44549983ce19e8

**Comment by moneromooo-monero** [comment]
Nice, I didn't realize you could set priority as a one off.
Anyway, this is fine, till the fork in a few days.

+invalid

**Comment by campassi** [comment]
Thank you for your feedback moneromooo
