### ISSUE TITLE
UI Proposal

### ISSUE THREAD

**Issue by alphathree** [monero-project/monero#2419]
Guys, been testing the GUI and started to work on some layouts to help out if welcome.

![home 2x](https://user-images.githubusercontent.com/19602081/30236707-dec3102a-94f5-11e7-895f-70d45ae10ad8.png)

![send 2x](https://user-images.githubusercontent.com/19602081/30236708-e7d0173a-94f5-11e7-9758-331e765a761e.png)

**Comment by moneromooo-monero** [comment]
Please file on https://github.com/monero-project/monero-core/issues, that's where the GUI is.

+invalid
