### ISSUE TITLE
Please indicate required Monero version for upcoming hardfork

### ISSUE THREAD

**Issue by arnuschky** [monero-project/monero#2426]
The readme still reads this:

| Fork Date              | Consensus version | Minimum Monero Version | Recommended Monero Version | Details            |  
    | ----------------- | ----------------- | ---------------------- | -------------------------- | ------------------ |
| 2017-09-21        | v6                | Not determined as of 2017-03-27                | Not determined as of 2017-03-27                    | Allow only RingCT transactions      |

**Comment by arnuschky** [comment]
According to this https://getmonero.org/2017/09/07/monero-0.11.0.0-released.html version 0.11.0.0. Is that correct?

**Comment by bymaximus** [comment]
I got this message running monerod version 0.10, "Last scheduled hard fork time shows a daemon update is needed now.".

I need update to version 0.11? Daemon still syncing with 0.10, I currently having many problems when running version 0.11 at linux and windows thats why I still use version 0.10

**Comment by moneromooo-monero** [comment]
Latest version is 0.11.0.0.

This needs to be the version you run by the time block 1400000 comes, in about 2 days. 0.10.3.1 and earlier will be left stuck there.

If you're having trouble syncing, ask either on Freenode IRC (#monero) or Reddit, and describe the symptoms in detail.

**Comment by SamsungGalaxyPlayer** [comment]
Can this be closed?

**Comment by moneromooo-monero** [comment]
+resolved
