### ISSUE TITLE
404s for GUIs on getmonero.org

### ISSUE THREAD

**Issue by einsteinsfool** [monero-project/monero#2431]
Hello.

When you go to [Downloads](https://getmonero.org/downloads) page for Monero and you click any link for GUI you get to a site with "404 Not Found".

If GUIs are not yet ready there probably should be some information near the link or maybe indication by crossing the link out. Or hopefully GUI packages hasn't been uploaded to the server yet.

**Comment by lodotek** [comment]
Hmmm that is a bit concerning....

**Comment by moneromooo-monero** [comment]
This should really be filed on the website repo (https://github.com/monero-project/monero-site), but it's fixed now. The GUI binaries took a while to get right.

+resolved
