### ISSUE TITLE
monero-blockchain-import v0.11.0.0 ERROR "MDB_MAP_FULL: Environment mapsize limit reached"

### ISSUE THREAD

**Issue by RigacciOrg** [monero-project/monero#2450]
I tried to import the blockchain into v0.11.0.0, after exporting it from from v0.10.3.1. The host is a GNU/Linux amd64, 12 Gb RAM, over 120 Gb of free disk on SATA III HD.

During the process, the host becomes almost unresponsive, the 4 cores went overwhelmed by more of 10 pending processes. Some suggestion on how to help in debugging? You can see the error in the log attached.

[monero-blockchain-import.log.txt](https://github.com/monero-project/monero/files/1305848/monero-blockchain-import.log.txt)

**Comment by moneromooo-monero** [comment]
Try with --batch-size 100

**Comment by hyc** [comment]
Just to confirm, I tried to do an import from scratch and hit this error around block 1015000. All default parameters.

**Comment by RigacciOrg** [comment]
I repeated the same exact import using "--batchsize 100" as suggested (same raw file, same monero-blockchain-import executable). This time the process took 9.5 hours instead of 16, no errors were reported, the load average was less problematic. Thanks!
