### ISSUE TITLE
windows build creates extra libraries, crashes on execution

### ISSUE THREAD

**Issue by dcwatson84** [monero-project/monero#2453]
Im trying to build monero on windows. It compiles fine but creates 3 extra files in the release/bin directory:

libcrypto.a
libssl.a
libwinpthread-1.dll

When I run monerod it crashes with a generic "Application was unable to start correctly (0x000007b)" message. If I remove the .dlls the crash shows the message "libwinpthread-1 was missing from your computer".

What is going on locally that doesn't produce the exact build I got from https://getmonero.org/downloads/#windows

Edit: Looks like the latest download _does_ contain these extra libraries. My build is still crashing upon starting though.

**Comment by gazhayes** [comment]
Are you using msys2?

There are usually dll files in the msys2 bin directory that you also need to copy to binary directory.

**Comment by dcwatson84** [comment]
Yea, I followed the directions for the windows build in the readme. 
The getmonero.org download (for v 0.10.3.1) contains the following files:

monero-blockchain-export.exe
monero-blockchain-import.exe
monero-utils-deserialize.exe
monero-wallet-cli.exe
monero-wallet-rpc.exe
monerod.exe

Is there a reason my build, from the same tag, isn't producing that exact set?

**Comment by gazhayes** [comment]
I'm not sure why, but I get the same result as you. I'm not sure how the official binaries are being built.

To verify that its just missing dll libraries causing it to fail you can try copying monerod.exe into the bin directory at the root of your msys2 folder. Anything it could possibly need should be in there so that should at least get it to run.

Apart from that, hopefully someone watching can elaborate on the build process thats being used for official releases.

**Comment by hyc** [comment]
You should be using these instructions https://forum.getmonero.org/5/support/2510/building-monero-v0-9-2-on-win32 and you should be building v0.11 now, not v0.10.

**Comment by dcwatson84** [comment]
This appears to be specific to win _32_ . I'll try ti adjust it in the obvious places to use 64 bit tools and see how it goes. I cant seem to find a post on that support form that references build instructions like the above link. In fact I can't even seem to find that post when searching the support forum. Maybe it's been deleted/hidden?

**Comment by dcwatson84** [comment]
I followed those instructions and got the same result. It also still complains about the libwinpthread-1.dll library if I remove it.

My guess is that it's because those instructions are very old. Are there updated instructions somewhere that are specific to win64 and v11?

**Comment by dcwatson84** [comment]
Update: I went through the instructions again and followed them as-is with 0.10.3.1, using 32 bit everything, instead of trying to modify them for 64 bit. it compiled and runs fine. 

I'll keep working on getting the 64 bit build working. I probably just had some paths incorrect.

**Comment by moneromooo-monero** [comment]
Do you still get the crash with current master ? Known crashes are now fixed.

**Comment by moneromooo-monero** [comment]
Rereading, it looks like the crash was just due to a 32/64 bit configuration mixup, closing.

+invalid
