### ISSUE TITLE
New daemon slows down Ubuntu 16.04 to a halt

### ISSUE THREAD

**Issue by reppolice** [monero-project/monero#2455]
I have tried the new daemon on both a 2011 Macbook, as wells as a Quad Core laptop with Ubuntu and 32GB RAM, and while the Mac managed a complete sync in about a day without too much strain, my Ubuntu can hardly do anything while the daemon is syncing, even though "top" never shows more than 45% of CPU. It looks like the process might still complete in a day, but quite a mystery! Putting the disk under too much strain perhaps? Something more evil?

**Comment by moneromooo-monero** [comment]
Do these have spinning HDDs or SSDs ?

**Comment by reppolice** [comment]
HDD on the fast computer, a slow SSD on the Mac, it is impossible to justify a "hanging" computer for 24 hours just to sync the 2GB or whatever the size of Monero's blockchain

**Comment by celavek** [comment]
I have witnessed something similar, although my system does not go to a total halt but it gets really slow. I'm on Debian 9 and I'm using netdata to collect information about my system and the disk backlog(an indication of the duration of pending disk operations) is very high and often goes to critical levels during the whole sync operation with cpu iowait also through the roof.

**Comment by hyc** [comment]
Have you actually compared sync performance using v0.10.3.1 on the same machine?

For the record, I've noticed freezes on my linode running v0.11 too, that never occurred before running v0.10. During those times, top shows monerod eating a lot of CPU. If you can build from source, try compiling master plus #2446 and see how that behaves. It has definitely reduced the impact on my systems.

**Comment by reppolice** [comment]
Well, it is certainly the worst performance I've seen in a daemon, speaking from weak human fallible memory :) It has to be said the blockchain has grown to 28GB while I was not watching. The whole thing feels very suboptimal, "obviously" it is ignoring my available RAM, would it be too much to ask for more RAM caching?

**Comment by hyc** [comment]
Unfortunately, we tried that in earlier releases. Too many Windows users got corrupted blockchains from system crashing during a sync. So now we flush data to disk more frequently, to avoid that. You can always start monerod with an explicit --db-sync-mode setting if your system doesn't have such reliability issues.

**Comment by hyc** [comment]
If you pay close attention with a system monitoring tool you'll see that far more than 50MB is already being cached by default. And again - if you know your system is reliable, you can change the settings yourself. But yes, experience over the past year has shown us that using unsafe defaults results in broken files, and the majority of users are (1) using windows and (2) using default settings.

**Comment by moneromooo-monero** [comment]
hyc's threading code got merged, can you report whether it feels better now ?

**Comment by NanoAkron** [comment]
@reppolice

**Comment by moneromooo-monero** [comment]
No reply, and believed fixed. Reopen if it's still as bad. It is subjective, but don't reopen just becaus it'd be nice if even faster. As long as it doesn't wedge the machine too much, it should be fine.

+resolved

**Comment by Bomper** [comment]
I don't think this is fixed. I've just download the latest GUI (monero-gui-linux-x64-v0.11.1.0.tar.bz2) and the daemon that ships with it, and on Ubuntu 16.04, CPU usage goes through the roof: towards the end of syncing the blockchain, switching tasks takes seconds, the mouse cursor skips when moving etc. This makes the wallet unusable and I can't wait for the blockchain to sync, see my transaction, transfer the XMR elsewhere, uninstall, and recover the [gobs of disk space that the wallet uses](https://github.com/monero-project/monero-gui/issues/1164).

![image](https://user-images.githubusercontent.com/34669048/37006816-1266ca14-208f-11e8-8efc-248d7624863b.png)

**Comment by lh1008** [comment]
My pc freezes as well when GUI is running and synchronizing. I don't know how to slow the synchronization. I have been using the monerod manually but I can't do anything else while is running in the cpu(laptop) the same as @Bomper. :) Hope this gets fixed. Are there are any instructions on how to slow down the blockchain sync? Thank you for your support..
