### ISSUE TITLE
Wallet: let user set his own threshold before warning about tx backlog.

### ISSUE THREAD

**Issue by FelixWeis** [monero-project/monero#2465]
The new feature to warn users of transaction backlog is very nice. It would be nice to be able to set a wallet option so it does not warn before X blocks.

    There is currently a 1 block backlog at that fee level. Is this okay?  (Y/Yes/N/No)

**Comment by moneromooo-monero** [comment]
+easy

**Comment by moneromooo-monero** [comment]
+resolved

**Comment by moneromooo-monero** [comment]
I closed the wrong one, this one is still active, till the PR gets merged.
