### ISSUE TITLE
Transaction fails with error: “original_output_index too large”

### ISSUE THREAD

**Issue by frost-monkey** [monero-project/monero#2472]
I'm a pool operator, and for the first time tonight, I got this error while trying to send a payout to miners:

    Error with transfer RPC request to wallet daemon {"code":-4,"message":"original_output_index too large"}

For what I can see from the source code, the error happens in this file, at line 4364:

https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp

Problem is, I don't exactly get what the problem is. For what it's worth, I made sure all addresses were valid standard XMR wallet addresses, and that none of them appeared twice in the parameters. I'm trying to send payouts between 0.1 and 2.0 XMR.

I'm using [this pool software](https://github.com/clintar/cryptonote-xmr-pool) with a slight modification: I use transfer_split instead of transfer. This particular transaction had 31 different recipients.

I've done my best to find questions / threads / information about that specific error, and have found nothing. Any help would be greatly appreciated.

Thanks a lot!

**Comment by moneromooo-monero** [comment]
Any other interesting/unusual messages near that error ? I've tried sending 31 amounts, and did not get any trouble (same address though, guess I'll try making 31 different temporary addresses now).

**Comment by frost-monkey** [comment]
I'll get back to you with more details as soon as I can.

I finally decided to manually make two payout rounds, and realized there were in fact 37 addresses, but only 31 appeared in the failed transaction log. At some point 37 became 31 or the opposite, and I suppose that because the numbers didn't match, it caused the error I got.

**Comment by moneromooo-monero** [comment]
I've reproduced it now, so no need for further info.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2491

**Comment by frost-monkey** [comment]
Thanks a lot for your time and help. You guys make a tremendous job!

**Comment by moneromooo-monero** [comment]
+resolved
