### ISSUE TITLE
RPC call get_coinbase_tx_sum returns 0 fees and 0 emission for some (all?) blocks

### ISSUE THREAD

**Issue by whateverpal** [monero-project/monero#2476]
monerod (v0.11.0.0) RPC call get_coinbase_tx_sum returns

{u'status': u'OK', u'fee_amount': 0, u'emission_amount': 0}

for blocks 800000, 1200000, 1400000

monerod is run with --block-sync-size=20 and --detach flags

**Comment by moneromooo-monero** [comment]
Thanks, fixed in https://github.com/monero-project/monero/pull/2477

**Comment by moneromooo-monero** [comment]
+resolved
