### ISSUE TITLE
No AltiVec/VMX hash function provided

### ISSUE THREAD

**Issue by madscientist159** [monero-project/monero#2489]
ppc64el machines have an analogue to SSE known as AltiVec or more specifically VMX.  This includes AES instructions.

A ppc64el-optimized hash function should be provided, considering there is an optimized ARM hash function already in the tree alongside the x86 hash functions.

**Comment by hyc** [comment]
Nothing just gets "provided" out of thin air. You're welcome to submit a patch to add this code though.

**Comment by madscientist159** [comment]
I'm aware :smile:  Lodged the issue as a wishlist item that either I or someone else may get around to doing at some point.  Not expecting anything to magically appear out of thin air here.

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by selsta** [comment]
I will close this issue as it doesn't seem anyone is interested in implementing this. PRs are still welcome even after this is closed.
