### ISSUE TITLE
Ring size too small

### ISSUE THREAD

**Issue by khelle** [monero-project/monero#2531]
Hi, today my transactions started to failing wheh being sent from monero daemon with log "ring size too small". I have read that default ring size has been raised from 4 to 10 for transactions and I would like to change that in my setup, but I cannot find documentated option to configure it. Where can it be set?

**Comment by fluffypony** [comment]
Have you updated to the latest version? And are you running the GUI wallet, the CLI wallet, or an RPC wallet integration?

**Comment by khelle** [comment]
I am using newest `Helium Hydra` release, daemon + few RPC wallets.

**Comment by khelle** [comment]
I was able to make it work by changing the `mixin` parameter of transfer to 10. Is the mixin and ring size the same thing named differently?

**Comment by moneromooo-monero** [comment]
Ring size is mixin + 1. Min mixin is now 4, bar special cases (and certainly not 10).

**Comment by khelle** [comment]
What about https://github.com/monero-project/monero/issues/1673 ? If the min mixin is now 4 why I cant send any transaction with that (setting mixin to 4 or not providing it at all). With mixin=10 everything works fine. This happens with transaction to singleaddress without payment_id.

**Comment by moneromooo-monero** [comment]
What do you want to know about 1673 ? Apparently the person doing the study is AWOL.
About transaction failure: please post a log of the wallet with --log-level 2, and the JSON you are sending monero-wallet-rpc. If the log has private information, feel free to redact it (or post it to fpaste.org with a password and give me the password in a PM on Freenode IRC, moneromooo).

**Comment by moneromooo-monero** [comment]
If no more info is given soon, I'll close this, since it (RPC txes with mixin set to 4) works for me (testnet).

**Comment by khelle** [comment]
Thank you for warning me beforehand, but I told everything I could say. I am using Helium Hydra and a call to `transfer` RPC method with these params:

```
{ destinations: [{ address: someAddress, amount: someAmount }], payment_id: someID }
```

Gives me "ring size too small". On the other hand, the same clal, but with addeded mixin=10 works great.

```
{ destinations: [{ address: someAddress, amount: someAmount }], payment_id: someID, mixin: 10 }
```

**Comment by moneromooo-monero** [comment]
The first one does not give *any* mixin. Don't do that. Using 0 there will (should) automatically adjust.
Anyway, as my comment above:
please post a log of the wallet with --log-level 2, and the JSON you are sending monero-wallet-rpc. If the log has private information, feel free to redact it (or post it to fpaste.org with a password and give me the password in a PM on Freenode IRC, moneromooo).

**Comment by moneromooo-monero** [comment]
In particular, there should be:
2017-10-03 09:34:47.480	[RPC0]	WARN 	wallet.rpc	src/wallet/wallet_rpc_server.cpp:233	Requested ring size 1 too low for hard fork 6, using 5

**Comment by moneromooo-monero** [comment]
ping

**Comment by moneromooo-monero** [comment]
Alright, I get the hint.

+invalid

**Comment by cryptobuilder2018** [comment]
i have same issue 
WARN wallet.rpc	src/wallet/wallet_rpc_server.cpp:233	Requested ring size 1 too low for hard fork 6, using 5
any solutions regarding the same?
thanks
