### ISSUE TITLE
error: suggest braces around initialization of subobject

### ISSUE THREAD

**Issue by danrmiller** [monero-project/monero#2544]
I started getting this error on debian linux aarch64 "stretch" using boost 1.62:

https://build.getmonero.org/builders/monero-static-debian-armv8/builds/1977/steps/compile/logs/stdio

Building CXX object src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/block_queue.cpp.o
/mnt/buildbot/buildbot/slave/monero-static-debian-armv8/build/src/cryptonote_protocol/block_queue.cpp:208:44: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  static const boost::uuids::uuid uuid0 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

I think it started with #2434, but I'm not sure because I also had unrelated openssl errors building at that time.

**Comment by radfish** [comment]
From IRC:
2017-09-26 18:47:32     +moneromooo      = boost::uuids::nil_uuid
2017-09-26 18:47:41     +moneromooo     Possibly with () at the end, can't recall.

Perhaps PR that please?

**Comment by danrmiller** [comment]
thanks, OK will test that and then PR

**Comment by danrmiller** [comment]
error: no type named 'nil_uuid' in namespace 'boost::uuids'

**Comment by radfish** [comment]
boost::uuids::uuid u = boost::uuids::nil_uuid();

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2571 does this one work ? It works here, so if it doens't work for you it might be a boost version thing.

**Comment by danrmiller** [comment]
Thanks, #2571 works.
