### ISSUE TITLE
[RPC] Feature Request: Name / Status which wallet-file is currently in use

### ISSUE THREAD

**Issue by krtschmr** [monero-project/monero#2547]
`get_status`

should return the filename of the wallet that is currently open. if we closed the wallet it should return {}

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2605 allows getting the current wallet description, which seems more appropriate.

**Comment by krtschmr** [comment]
that's a nice commit and a useful feature!

**Comment by moneromooo-monero** [comment]
+resolved
