### ISSUE TITLE
linux(Command-Line Tools Only),run monero-wallet-rpc , use curl request , return 'Unauthorized Access'

### ISSUE THREAD

**Issue by jiushigan** [monero-project/monero#2553]
./monero-wallet-rpc --rpc-bind-port 18082 --wallet-file sun --password ****** &

curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'

<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>

------------------------------------
I don't know why,
help me.

**Comment by moneromooo-monero** [comment]
See --disable-rpc-login or the other login related options.
If you need help using monero, this is not the place. Try #monero on freenode, or Reddit.

+invalid

**Comment by fourseaLee** [comment]
curl  -u username:password --digest  -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'  maybe can use. @jiushigan
