### ISSUE TITLE
Add "print_tx_sh" command for a short version of "print_tx" in the daemon

### ISSUE THREAD

**Issue by binaryFate** [monero-project/monero#2559]
Currently `print_tx` spits the whole tx. 
Often one wants only to check the block height of the transaction, or simply to check whether it is known to the daemon at all. A one-liner version would be practical so as not to scroll up and search among a large blob.  
Anyone would find it useful? If so what info do we want to be returned? txid, payment id, fees amount, ring size, block height (or time received if not confirmed yet)?

**Comment by moneromooo-monero** [comment]
It'd be useful. Maybe everything except the JSON and hex. Or just add options to print_tx to select json and/or hex in addition to the "human text" data.

**Comment by binaryFate** [comment]
> Or just add options to print_tx to select json and/or hex in addition to the "human text" data.
I like it, better than creating more commands IMO.

Would it be worth being consistent with the print_pool command(s)? Currently print_pool and print_pool_sh.

**Comment by moneromooo-monero** [comment]
I wouldn't care much either way. They're different commands. New ones don't have to slavishly try to mimic if another way seems better. In that case, there's not a huge amount of difference, since they'll all go through the same RPC anyway.

**Comment by binaryFate** [comment]
I'll do this one soon
