### ISSUE TITLE
Block 1288623 bug - clients performing IBD get stuck on dead chain

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#2562]
There's no logs, its been reported multiple places and times. 

as @hyc mentioned elsewhere, indicated in

https://github.com/monero-project/monero/issues/2449

https://github.com/monero-project/monero/issues/2451

https://www.reddit.com/r/Monero/search?q=1288623&restrict_sr=on

and its 7 blocks after the 1288516 hardfork of RingCT introduction.

**Comment by moneromooo-monero** [comment]
Any evidence it's not fixed by 2492 ?

**Comment by hyc** [comment]
PR #2492 appears to be about fixing a crash. These reports don't seem to be about crashes, and most likely could be cleared up by deleting p2pstate.bin.

**Comment by moneromooo-monero** [comment]
They're both about crashes (the ones on github anyway).

**Comment by hyc** [comment]
Ah, right. Not sure how those people would have tested PR#2492, they're only using v0.11.0.0 official binaries.

**Comment by moneromooo-monero** [comment]
One of those on reddit is not a crash though, but could plausibly be this as the size of the tx hash array is dynamic. The other is unknown, not enough data to tell.

**Comment by moneromooo-monero** [comment]
Sure, I mean I won't investigate another thing unless I have some evidence there *is* another thing :)

**Comment by moneromooo-monero** [comment]
If there is a report for this which does not go away after using 2492 (which is merged now), then please ask to restart with: --log-level 1,net.cn:DEBUG,\*p2p\*:INFO

**Comment by dEBRUYNE-1** [comment]
@hyc. Deleting `p2pstate.bin` doesn't seem to help here. In addition, I've noticed that often even popping blocks doesn't help. 

@moneromooo-monero [Here's](https://paste.fedoraproject.org/paste/VDXcdXmFw7BBDT~9CRKItA
) a log from someone who used a `monerod` from #2492 (he used the buildbot binaries). Full thread can be read here:

https://www.reddit.com/r/Monero/comments/73fij0/wallet_keeps_disconnecting/

**Comment by Gingeropolous** [comment]
yet another

https://www.reddit.com/r/Monero/comments/7562kx/wallet_gui_daemon_is_crashing/

**Comment by moneromooo-monero** [comment]
All evidence is pointing to this being a duplicate. Can you find any pointing to it not being ?

**Comment by moneromooo-monero** [comment]
I've been pointing a few people having that problem to a build with those fixes above, and it always worked. So this is indeed a dupe.

+duplicate
