### ISSUE TITLE
A bug about monero-blockchain-import.

### ISSUE THREAD

**Issue by p1gd0g** [monero-project/monero#2566]
The option "--data-dir" in monero-blockchain-import had been removed, but you still see it in "--help".

https://github.com/monero-project/monero/blob/a2041c98742154df4360831c99cfd9200a5620c2/src/blockchain_utilities/blockchain_import.cpp#L588

Someone is confused at this.
https://monero.stackexchange.com/questions/6219/bootstrap-import-data-dir-command-not-working/6228#6228

**Comment by moneromooo-monero** [comment]
These lines are obsolete, I'll remove them. The data dir and a couple others are now set by the core. Anyway, it works for me:

$ ./build/debug/bin/monero-blockchain-import --data-dir /home/user/FOO-dd --input-file blockchain.raw

2017-10-03 08:12:01.140	    7ce5648bd880	INFO 	bcutil	src/blockchain_utilities/blockchain_import.cpp:719	database path:       /home/user/FOO-dd

$ ls ~/FOO-dd/lmdb/
data.mdb  lock.mdb
