### ISSUE TITLE
cryptonote::OUTPUT_DNE error flooding logs

### ISSUE THREAD

**Issue by emesik** [monero-project/monero#2580]
I have my monerod logs being flooded by stack traces of _cryptonote::OUTPUT_DNE_ error.

The log: [monero-bug.log](https://github.com/monero-project/monero/files/1357427/monero-bug.log)

By function names (_tx_memory_pool_, _check_tx_inputs_, _get_output_key_) I guess this is somebody trying to broadcast invalid transactions.

However, if this is something serious, a more user-friendly message would be nice and the log level could be perhaps higher (ERROR ?)

If this is not important, perhaps demoting it to loglevel DEBUG would be a good idea?

**Comment by moneromooo-monero** [comment]
Please restart with --log-level 1,\*pool\*:DEBUG,*msg:INFO
Then paste a new log with the extra info.

**Comment by emesik** [comment]
The messages stopped appearing. Perhaps it was someone trying to publish invalid transactions. If that happens again and I'm able to provide more details, I'll reopen.
