### ISSUE TITLE
While on testnet, randomly generated wallets do not receive transactions

### ISSUE THREAD

**Issue by emesik** [monero-project/monero#2584]
I've created own testnet. The setup/sandbox is present here: https://github.com/emesik/monero-testnet-sandbox

When I transfer coins between wallets that have been generated from 25-word seed, it works as expected (`walletA` and `walletB` are examples in the sandbox). 

However, if I generate a random wallet and send coins to the address it presents on startup, the new wallet never acknowledges incoming transactions. No matter if they are in mempool or already signed in a block, the new wallet always shows balances as 0/0. `refresh` command doesn't change anything. The wallet also doesn't receive freshly mined coins if I direct a daemon to mine to its' address. `walletC` in the sandbox is an example of it. 

The destination address is correct and coins aren't lost. The only way I found to recover them is:

1. Issue `seed` command in client running `walletC` and copy away the words.
2. Exit client.
3. Remove all wallet files.
4. Run client again with `monero-wallet-cli --testnet --restore-deterministic-wallet` and enter the 25 words.
5. The new wallet suddenly refreshes all transactions and displays correct balance.

The behavior is 100% reproducible. I tried it on several new wallets, rebooted the network from scratch. Always fails. I'm running `monero-0.11.0.0` and current testnet blockchain height is 425.

On real network I'm also using randomly generated wallet and it works perfectly.

**Comment by perl5577** [comment]
When you are create wallet, wallet is connected on daemon?

I have already problem wallet create without start daemon .

**Comment by emesik** [comment]
I don't know. The client doesn't say explicitly when it connects to the node, but I guess it happens after wallet creation.

**Comment by moneromooo-monero** [comment]
Try with https://github.com/monero-project/monero/pull/2542

**Comment by emesik** [comment]
I rebuilt monero from latest master including that merge. Nothing has changed, the bug is still there.

**Comment by gazhayes** [comment]
If you delete the random wallets and regenerate them from the mnenomic does it work?

If that's the case it's probably getting the start sync height from mainnet instead of testnet, so the wallet is not syncing transactions from before block x.

**Comment by moneromooo-monero** [comment]
Try https://github.com/monero-project/monero/pull/2596

**Comment by emesik** [comment]
It doesn't help either.

Here's an example output of a freshly created wallet. I sent there 2.00 XMR which are visible in `show_transfers` as being in the pool. However, two blocks later the pool gets empty but balance is still 0.

```
Monero 'Helium Hydra' (v0.11.0.0-86e9de58)                 
Logging to monero-wallet-cli.log                           
Generated new wallet: 9uW1Y6N1RvK131tptvyyQyhWhTGakDBktG2LttdfwECTZLDHYnHHS9e9DEg9DhT5s2Qq3FY8UNhJZdNdttVVTigf3sM54zo  
View key: 3a15b644b646bff66b834580330299576a84f5b31963b64c0063b3984b24af03                                             
**********************************************************************                                                 
Your wallet has been generated!                            
To start synchronizing with the daemon, use "refresh" command.                                                         
Use "help" command to see the list of available commands.  
Always use "exit" command when closing monero-wallet-cli to save your                                                  
current session's state. Otherwise, you might need to synchronize                                                      
your wallet again (your wallet keys are NOT at risk in any case).                                                      


PLEASE NOTE: the following 25 words can be used to recover access to your wallet. Please write them down and store them somewhere safe and secure. Please do not store them in your email or on file storage services outside of your immediate control.

lair festival bogeys token umpire welders inkling coffee   
lobster silk gifts certain nocturnal pistons almost exquisite                                                          
gambit nasty setup afraid bunch pool bowling cohesive gifts                                                            
**********************************************************************                                                 
Monero 'Helium Hydra' (v0.11.0.0-86e9de58)                 
Logging to monero-wallet-cli.log                           
Opened wallet: 9uW1Y6N1RvK131tptvyyQyhWhTGakDBktG2LttdfwECTZLDHYnHHS9e9DEg9DhT5s2Qq3FY8UNhJZdNdttVVTigf3sM54zo         
**********************************************************************                                                 
Use "help" command to see the list of available commands.  
**********************************************************************                                                 
Starting refresh...          
Refresh done, blocks received: 0                                                                                       
Balance: 0.000000000000, unlocked balance: 0.000000000000  
Background refresh thread started                          
[wallet 9uW1Y6]: refresh     
Starting refresh...          
Refresh done, blocks received: 0                                                                                       
Balance: 0.000000000000, unlocked balance: 0.000000000000  
[wallet 9uW1Y6]: show_transfers                            
    pool     in      05:17:43 PM       2.000000000000 7dcae948240f99ee7697b813694f76cf409d760e044816d61b43aeff820f5234 0000000000000000 - 
[wallet 9uW1Y6]: refresh                                                                                               
Starting refresh...          
Refresh done, blocks received: 2                                                                                       
Balance: 0.000000000000, unlocked balance: 0.000000000000  
[wallet 9uW1Y6]: show_transfers                            
[wallet 9uW1Y6]:
```

**Comment by moneromooo-monero** [comment]
Hmm, works for me. Can you log the value of m_refresh_from_block_height in wallet2.cpp,line 2207 (just before store_keys) ?

**Comment by emesik** [comment]
Yes, it works! I must have used wrong binary in the last test.

BTW, the value reported in line 2207 is 0

**Comment by BengtGoran** [comment]
I am having this issue live with version Helium Hydra. Pretty much, the background sync thread retrieves 0 blocks at sync. Unless i recreate the wallet, then it just works

**Comment by CoinLogik** [comment]
@gazhayes 
> If that's the case it's probably getting the start sync height from mainnet instead of testnet, so the wallet is not syncing transactions from before block x.

But shouldn't that be fixed by `refresh`?

**Comment by acardi** [comment]
Following commands solved the problem for me:

set refresh-from-block-height 1
rescan_bc

**Comment by nikitasius** [comment]
> Following commands solved the problem for me:
> 
> set refresh-from-block-height 1
> rescan_bc

the same even those days on latest xmr client.
