### ISSUE TITLE
/sys/class/power_supply errors when smart mining on Fedora 25

### ISSUE THREAD

**Issue by shmacoshmuesday** [monero-project/monero#2614]
On Fedora 25, x64, running version 11 GUI wallet and daemon, trying to smart mine. I do get hashes from it but apparently it's having trouble monitoring the power supply...? Here are the errors I'm getting. I believe I'm on the latest kernel or a very recent one. When I type status it shows that smart mining is working and giving me about 60 hashes/s.

2017-10-09 01:18:05.197	    7f2bff0fc700	ERROR	miner	src/cryptonote_basic/miner.cpp:940	couldn't query power status from /sys/class/power_supply
2017-10-09 01:18:05.197	    7f2bff0fc700	INFO 	global	src/cryptonote_basic/miner.cpp:650	idle percentage is 55%, miner percentage is 44%, ac power : 1
2017-10-09 01:18:15.199	    7f2bff0fc700	WARN 	miner	src/cryptonote_basic/miner.cpp:864	Unable to read from "/sys/class/power_supply/AC" to check if power supply present

**Comment by glv2** [comment]
If you can compile and test the master branch, there is a patch in it that should fix that (commit 20256b7c0499b07c4f2ad45901bcde7d68893345).

**Comment by shmacoshmuesday** [comment]
This will be my first time compiling if successful, will report back by end of week. Thank you!!

**Comment by shmacoshmuesday** [comment]
I haven't been successful compiling (checked all dependencies, have a thread open on stackexchange asking for help, need to check on it). Just wanted to give a headsup. Thanks again

**Comment by shmacoshmuesday** [comment]
Question for anyone that can answer: if I'm getting an error compiling from the master branch and I've verified my dependencies, should I open that as an issue here on github?

**Comment by moneromooo-monero** [comment]
If you think it's a monero bug, yes.

**Comment by shmacoshmuesday** [comment]
Thanks moneromoo. I found the answer to my latest issue and was able to compile from the master branch.

Happy to report I tested this issue and it appears to be resolved. 

I'm sure this isn't the best place but please point me to a better place to post such things if there is one. Is there a way that I/we can add a column for fedora on the dependency list? There are quite a few subtle (and not so subtle) differences in the dependencies required for fedora compared to what's listed on the project page. I'd be happy to do whatever needs done to accomplish that, I can provide the list of what I had to install to compile the latest on fedoray.

**Comment by moneromooo-monero** [comment]
They're in the README.md file, just add a column to the table starting on line 162, like there is for Ubuntu and Arch already.

+resolved

**Comment by shmacoshmuesday** [comment]
Thanks (many times over of course) moneromoo
I'm a noob so may have more noob questions but I get what you're saying and I'll make that another project to mark off the list :)

**Comment by jaidetura55** [comment]
is it still mining or block mining
