### ISSUE TITLE
tag v0.11.0.0 behind release-v0.11.0.0 branch

### ISSUE THREAD

**Issue by sroecker** [monero-project/monero#2623]
When I tried to build monero from source I noticed that the tag v0.11.0.0 doesn't contain all commits from the release-v0.11.0.0 branch. I assume one should use the latter to build Helium Hydra from source.

**Comment by moneromooo-monero** [comment]
This is as expected. The tag is what was released. The branch now has a few more commits, which will be part of 0.11.0.1 whenever this gets released.

+invalid
