### ISSUE TITLE
Release Static not content all commit 

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#2637]
After tag release and build binary .

merge request is pushed on release and binary not rebuild.

**Comment by perl5577** [comment]
On https://getmonero.org/downloads/  Linux, 64-bit

https://downloads.getmonero.org/cli/linux64
if not make error is build on 11/09/2017

For release tag:release-v0.11.0.0 after 11/09/2017 
4 merge  and 2 commit is accepted/merged on tag release-v0.11.0.0

**Comment by moneromooo-monero** [comment]
There will be a 0.11.0.1 at some point, with those new commits on the release-v0.11.0.0 branch. The current build is from the v0.11.0.0 tag.
