### ISSUE TITLE
GUI Wallet - Advanced filtering fails

### ISSUE THREAD

**Issue by 1337tester** [monero-project/monero#2647]
Advanced filtering in the 'History' tab fails to filter with any of the three parameters - 
'Type of transaction', 'Amount from', 'To'
as you see on the below picture, none of the three tx should pass through the filter setting
![advanced_filtering_fail](https://user-images.githubusercontent.com/6553766/31566662-f2678b4c-b06b-11e7-8cfb-d94bc6e15268.jpg)

**Comment by moneromooo-monero** [comment]
Please file this in the GUI repo: https://github.com/monero-project/monero-core/issues

**Comment by 1337tester** [comment]
present already - https://github.com/monero-project/monero-core/issues/173
sorry didnt realize that the GUI project is separate

**Comment by moneromooo-monero** [comment]
+invalid
