### ISSUE TITLE
CLI wallet - 'set ask-password' command reacts to invalid input

### ISSUE THREAD

**Issue by 1337tester** [monero-project/monero#2648]
'set ask-password' command should accept only 0 or 1, as per help - 'ask-password <1|0>'

However when there is an invalid (nor 0 or 1) parameter provided, the value is set to 0, see screenshot (works also with non numeric values)
![ask_password](https://user-images.githubusercontent.com/6553766/31566906-08d7be8c-b06d-11e7-91ca-097f7ac02d8d.jpg)

**Comment by selsta** [comment]
What be defaulting to 1 better?

**Comment by stoffu** [comment]
#2683

**Comment by moneromooo-monero** [comment]
+resolved
