### ISSUE TITLE
Update notification with link disappears before I can use it

### ISSUE THREAD

**Issue by snirp** [monero-project/monero#2665]
Upon opening the GUI, an orange notification box pops up in the bottom right. It contains an update notification with link.
 
I cannot access this link, because I first have to log in. During me logging in, the notification disappears to the bottom right and I cannot seem to make it appear again.

**Comment by moneromooo-monero** [comment]
The GUI repo is https://github.com/monero-project/monero-core, refile there.
There's no link btw, though you should be given the time to copy the link to paste elsewhere.

**Comment by moneromooo-monero** [comment]
Wrong repo, it'll be dealt with in the GUI repo, closing.

+invalid
