### ISSUE TITLE
Monerod, method not found

### ISSUE THREAD

**Issue by lukaisailovic** [monero-project/monero#2674]
I'm trying to call any method from my php script like this: 

```
      $client = new Client('http://127.0.0.1:28081/json_rpc');
      $result = $client->execute('getbalance');
      dd($result);
```
Now whatever method I chose from documentation it always result in error response `Method not found`. Is there any configuration to the node or anything that I'm not aware of ?

**Comment by glv2** [comment]
```getbalance``` is a valid RPC method for *monero-wallet-rpc*, not for *monerod*.

**Comment by lukaisailovic** [comment]
Never made anything with monero before, assumed it was same as Btc but looks like there are some major differences. So how can I run `monero-wallet-rpc` in testnet mode ?

**Comment by glv2** [comment]
Basically, you run ```monero-wallet-rpc --testnet --rpc-bind-port 28091 --wallet-file path_to_your_testnet_wallet_file```.

You can find some answers about RPC related questions on stackexchange: https://monero.stackexchange.com/questions/tagged/rpc.
