### ISSUE TITLE
Generate new Genesis TX and Nonce

### ISSUE THREAD

**Issue by romankosoj** [monero-project/monero#2676]
I want to create a Monero fork for a prvatnogo project, how to make a new genesis tx and nonce and also remove the restriction on 1000 blocks. Thanks in advance.

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help desk. You can try #monero on Freenode.

+invalid

**Comment by romankosoj** [comment]
Are you out of your mind? I was sent there from there.

**Comment by skynode** [comment]
Somebody please help @romankosoj. Outright dismissals like this are not what the community is about.

**Comment by stoffu** [comment]
The question definitely seems inappropriate for here. No one is interested in teaching you how to fork Monero; we're all interested in improving Monero. Maybe you can get some help from people which forked Monero recently, such as

- https://github.com/sumoprojects/sumokoin
- https://github.com/masari-project/masari

Also, such a basic question may be better directed to the CryptoNote repository:

- https://github.com/cryptonotefoundation/cryptonote

**Comment by romankosoj** [comment]
Thank you colleague.
