### ISSUE TITLE
transfers information disappeared from wallet

### ISSUE THREAD

**Issue by jonahar** [monero-project/monero#2706]
I pulled and compiled after the subaddresses merge so I can try it. Since then I can't see anything when typing the command `show_transfers`.
Machine: Ubuntu 16.04, 64-bit

**Comment by moneromooo-monero** [comment]
If you've not exited yet, kill the wallet process so it doesn't save the cache over the old one.

**Comment by jonahar** [comment]
Too late for that, I already closed the cli. Do you think there's anything else to do now?

**Comment by moneromooo-monero** [comment]
No, if it's saved the cache, the info is most likely gone, unless this is a display bug only (unlikely).

**Comment by moneromooo-monero** [comment]
It's not gone, but there is some corrupt info. I don't think it's recoverable cleanly, but should be recoverable in most cases.

https://github.com/monero-project/monero/pull/2715 fixes the bug, but does not fix a resaved cache. It should be possible to detect and fix the most egregious (ie, index > 250), but can't be sure if someone's used a lot of subadresses already.

**Comment by jonahar** [comment]
I have the `<wallet_name>.unportable` file. Can I use it to restore the information?

**Comment by moneromooo-monero** [comment]
Did you ever use subaddresses ? If not, I can make some changes which will recover the info.

**Comment by jonahar** [comment]
No, still haven't used a subaddress.

**Comment by moneromooo-monero** [comment]
https://github.com/moneromooo-monero/bitmonero/tree/zerosub

**Comment by jonahar** [comment]
I was able to recover only part of the transactions - just the outgoings.

**Comment by moneromooo-monero** [comment]
Try again with the new code, one of the fields was missing.

**Comment by jonahar** [comment]
This fixed it!
Would you mind sharing your personal tip address :) ?

**Comment by moneromooo-monero** [comment]
It's on moneroaddress.org, where you can optionally verify it with my GPG key :)

Fix merged.

+resolved
