### ISSUE TITLE
Please add key 686F07454D6CEFC3 to your GitHub account

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero#2709]
@moneromooo-monero Please consider adding your pgp pubkey `686F07454D6CEFC3` to your GitHub account. https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/#adding-a-gpg-key

This will allow GitHub users to easily verify your commit signatures.

Example:
![2017-10-23_monero-moo-upload-pubkey](https://user-images.githubusercontent.com/5115470/31867378-d34c2608-b78e-11e7-9fa1-338ecc317bb6.png)

**Comment by moneromooo-monero** [comment]
Doing this does not help people verify anything. It makes people dependent on github to claim it verified it for them. It is a lot better to verify the signature yourself locally. Verifying signatures should never be delegated to a third party.

**Comment by anonimal** [comment]
Come on moo, [drink the kool-aid](https://en.wikipedia.org/wiki/Drinking_the_Kool-Aid).

**Comment by moneromooo-monero** [comment]
Yeah, while I don't like that as it gives security conscious people an incentive to decrease their security, it also gives random people an incentive to increase theirs. There are certainly pros both ways.

**Comment by moneromooo-monero** [comment]
(though pony does sign merges, so people would check that signature anyway)

**Comment by jonathancross** [comment]
Okay valid points. Maybe it would lull people into complacency... can't be sure.
Feel free to close this issue now that you've considered the suggestion.  :-)

**Comment by moneromooo-monero** [comment]
+invalid
