### ISSUE TITLE
Consider using an individual database file per block

### ISSUE THREAD

**Issue by heptathlon** [monero-project/monero#2714]
Right now monero is using one big database blob file stored in `~/.bitmonero/lmdb/data.mdb`, currently sized at around 30GB. Please switch to using one file per (multiple) blocks like Bitcoin, Ethereum and a major part (if not all) other cryptocurrencies are currently doing. This has the advantage of being easier to backup and restore individual blocks (e.g. using a primitive backup program such as Apple Time Machine which backs up every different file as a whole and doesn't support incremental backups on a per file-delta level). Other tools are affected as well.

**Comment by iamsmooth** [comment]
As a workaround you might store the blockchain database in a [sparse bundle disk image](https://en.wikipedia.org/wiki/Sparse_image#Sparse_bundle_disk_images)

Or just exclude it from Time Machine altogether. You can always restore it from the net, or keep a copy of the .bin file locally.

**Comment by NanoAkron** [comment]
@heptathlon I once asked this same question, and our database guru and inventor of LMDB explained that this is actually a far better structure. I know it's a bit annoying, but for the sake of efficiency I'm willing to put up with it. 

Please just exclude it from your backup

**Comment by emesik** [comment]
Another important problem is that a 30GB file cannot be stored on a FAT filesystem, which is very popular on USB sticks and external drives.

That's a serious issue when someone wants to use an offline computer to serve as cold wallet.

**Comment by hyc** [comment]
This entire ticket is ridiculously stupid. Bitcoin and ethereum use multifile databases and they self-corrupt if you look at them funny. It is physically impossible to prevent a multifile database from self-corrupting.

At this point, SDcards and USBsticks with 64GB or more are using exFAT, and there's no problem. This ticket is utterly garbage.

**Comment by Gingeropolous** [comment]
> This entire ticket is ridiculously stupid.

I just want to celebrate this comment.

**Comment by dEBRUYNE-1** [comment]
+invalid
