### ISSUE TITLE
Expected memory usage of monerod

### ISSUE THREAD

**Issue by svenha** [monero-project/monero#2722]
Hi.
I freshly installed monero from the source file monero-0.11.1.0.tar.gz (worked nicely on Ubuntu 17.04). If I start monerod, it will synchronize up to 90 %, but than it requests an mmap size that exceeds my
32 GB RAM and stops. What RAM size is required by monerod?
Sven

**Comment by moneromooo-monero** [comment]
32 GB should be way more than enough. I run monerod with at most 2GB free. mmap size may reach terabytes, it doesn't really matter.

Run monerod with "--log-level 1" and see if you get more info on the stop.

**Comment by svenha** [comment]
Thanks for your help.
I had to increase the ulimit -v (virtual memory) from
ulimit -S -v 32000000
ulimit -S -v 64000000
Now, monerod continues the synchronization.

**Comment by hyc** [comment]
You'll be better off running monerod with unlimited virtual memory. The mapsize is always set larger than the space in use.
