### ISSUE TITLE
GUI 'start daemon' and 'Show status' ignore custom settings

### ISSUE THREAD

**Issue by ronohara** [monero-project/monero#2734]
If you set up a remote daemon, in the GUI, under Settings. The Show Status button only checks the localhost daemon (which obviously is not running).

With a remote daemon, you would expect to be able to Show Status, but not 'Start' or 'Stop' the daemon.

**Comment by moneromooo-monero** [comment]
Please file in the GUI repo: https://github.com/monero-project/monero-core/issues

**Comment by dEBRUYNE-1** [comment]
+resolved 

(used to close this issue).

**Comment by moneromooo-monero** [comment]
-resolved
+invalid
