### ISSUE TITLE
problem with display coin at new wallet

### ISSUE THREAD

**Issue by mraksoll4** [monero-project/monero#2746]
When i create new wallet and mine , or send to them money it's not display balance and tx.

Only if i restore it from seed/key's or use  set refresh-from-block-height 0

it's start display tx balance , i use latest release. 

I compile it from sources.

**Comment by moneromooo-monero** [comment]
Did you create the wallet with a previous release ?

**Comment by mraksoll4** [comment]
i create it at new release .

**Comment by moneromooo-monero** [comment]
What is the value of refresh-from-block-height before you set it to 0 ?

**Comment by mraksoll4** [comment]
how i can see it  , i dont see this info at log's?

**Comment by moneromooo-monero** [comment]
If you type "set", it will display it.

**Comment by Brigson** [comment]
refresh-from-block-height = 1413083

**Comment by moneromooo-monero** [comment]
That looks right. You'll have to supply a log (run the wallet with --log-level 2, and paste on fpaste.org or pastebin.mozilla.org) showing the bug happening.
