### ISSUE TITLE
Disguise password length in 'Wallet password:' prompt

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero#2748]
```sh
./monero-wallet-cli
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /path/to/monero-wallet-cli.log
Wallet password: **** # <-- Leaks password length
```

Better use a suitable readline prompt instead.

**Comment by iamsmooth** [comment]
It looks like you removed backspace handling altogether in the second commit. This is arguably okay (requiring the user to type the password without any errors) but should at least be noted in the commit title/comment.

**Comment by leonklingele** [comment]
> you removed backspace handling altogether in the second commit

Correct, but that change got reverted again a few minutes later because it didn't work out as expected.
The most current version can be found here: https://github.com/monero-project/monero/pull/2749/files
