### ISSUE TITLE
How to create checkpoint.dat self ?

### ISSUE THREAD

**Issue by Brigson** [monero-project/monero#2757]
How to create checkpoint.dat self ?

i meen this file https://github.com/monero-project/monero/blob/master/src/blocks/checkpoints.dat

I try to find at doc's how do this , but do not find any info.

**Comment by moneromooo-monero** [comment]
This is a bug tracker. Ask in #monero on Freenode, or reddit.

+invalid

**Comment by Brigson** [comment]
I understand :( I ask but no who not answer this , and i try answer at here , sorry for my qustion. But if you can hepl please answer :( I try to find this 5 day's and no info.

**Comment by Brigson** [comment]
and if it not hard for you , how to calculate this value 
static const char expected_block_hashes_hash[] = "d3ca80d50661684cde0e715d46d7c19704d2e216b21ed088af9fd4ef37ed4d65";

**Comment by fluffypony** [comment]
We don’t provide support for Monero forks.

**Comment by Brigson** [comment]
I ask about how do this , i not say anyting abou creating fork. Info how this templates value cannot find , and i ask about it , if it secret closed info ,say that and close sources. I whant undestand how it work for modify and add how to propose changes. But for do this i need first understand how it work. But info no exist

**Comment by fluffypony** [comment]
It’s not a secret, it’s been discussed many times on IRC, and frankly it’s rather self-explanatory to any serious contributor.

**Comment by Brigson** [comment]
Ok i understand sorry for qustion at issure

**Comment by Brigson** [comment]
no who not answer at freenode , sorry for my qustion again . Try to find it self.

**Comment by Brigson** [comment]
about  static const char expected_block_hashes_hash[] =  ir's sha256 off blockchain,dat ( siple can be findet with 7zip sha256 claculate
