### ISSUE TITLE
serialization

### ISSUE THREAD

**Issue by zhangdaoling** [monero-project/monero#2759]
I want to develop open source implementations of serialize and sign for golang.
my question is :should i use uint64 or uin32 for size_t when doing serialize?
do I miss something?

the c++ code use many "size_t" 
for example:  "monero/src/serialization/string.h"

template <template <bool> class Archive>
inline bool do_serialize(Archive<true>& ar, std::string& str)
{
  size_t size = str.size();
  ar.serialize_varint(size);
  ar.serialize_blob(const_cast<std::string::value_type*>(str.c_str()), size);
  return true;
}

**Comment by glv2** [comment]
Integers are not serialized as raw uint32 or uint64, but as variable size integers (see #2340).

**Comment by moneromooo-monero** [comment]
I'd use uint64_t. That way you can handle > 4 GB data :) In practice I think this will only happen if your implementation is attacked, so make sure you test the case :)

+invalid
