### ISSUE TITLE
Block found, coin missing?

### ISSUE THREAD

**Issue by Thawwed** [monero-project/monero#2762]
Block found, transaction shows payment sent to pool wallet, but pool wallet not received anything?

Is something wrong with my wallet-rpc?

**Comment by moneromooo-monero** [comment]
Please report the output of "status" in monerod.

**Comment by Thawwed** [comment]
`
Height: 12006/12006 (100.0%) on mainnet, not mining, net hash 135.61 MH/s, v1, up to date, 8(out)+23(in) connections, uptime 0d 1h 29m 32s
`

**Comment by moneromooo-monero** [comment]
Is this a monero alt ? Because that doesn't make sense otherwise.

**Comment by fluffypony** [comment]
Yes, it's Electroneum. STOP OPENING ISSUES ON THE MONERO REPOSITORY!!

**Comment by moneromooo-monero** [comment]
That explains why stuff that built for me did not for you. Thanks for wasting my time building stuff earlier :/ If you make changes, mention it first....

**Comment by Thawwed** [comment]
Electroneum is built off of this, and this issue stems from this. The same error occurs when I use it for straightup Monero. 

The issue is blocks are being found but something is not communicating right for it to actually credit to a wallet.

**Comment by moneromooo-monero** [comment]
And if you're using a low height chain, this is probably one bug that got a fix which got merged recently, update to recent code.

**Comment by Thawwed** [comment]
And I didn't make changes. If you click through the links Electroneum is just another commit of this.

**Comment by fluffypony** [comment]
@Thawwed no, Electroneum is a fork *with merged changes* to the codebase.

**Comment by Thawwed** [comment]
That's fine. I opened up a new issue. We can talk about the SAME EXACT issue because it happens with my Monero pool too.

**Comment by Thawwed** [comment]
Setup was the exact same.

**Comment by quangvu3** [comment]
Our blockchain is very stable and never missed a single coin. Please don't mention Sumokoin as we've never asked any silly question for help here
