### ISSUE TITLE
Block found, coin missing

### ISSUE THREAD

**Issue by Thawwed** [monero-project/monero#2763]
Block found, transaction shows payment sent to pool wallet, but pool wallet not received anything?  Is something wrong with my wallet-rpc?

My original problem was referenced to Electroneum; however, this is also the same issue with my Monero pool as well.

Blockchain is synced. Daemon is synced. Wallet is synced. Transaction links to wallet in blockexplorer. But still, there's no XMR. What's the deal?

**Comment by moneromooo-monero** [comment]
And does it happen with current code AND a wallet created with current code ?

**Comment by Thawwed** [comment]
Yes. Server was setup yesterday about 24 hours ago to be more precise, and it was setup using git clone. I'm new to linux, so if it sounds like it, it is. Everything functions perfectly until a block is found.

Like I said, transaction matches my pool wallet in the blockexplorer, but no matter how many times I sync the wallet or rebuild it from keys, there is no remnant of the transaction. The wallet works fine too, because I have sent XMR to it no problem from another wallet and received easily.

**Comment by moneromooo-monero** [comment]
Then:
- remove the cache file (FOO if the keys is FOO.keys)
- run the wallet with --log-level 2
- post the log to fpaste.org

**Comment by moneromooo-monero** [comment]
And include the txid of the coinbase you've found.

**Comment by Thawwed** [comment]
Problem solved. Had to rebuild wallet using mnemonic seed. Something was bugged with the original. After the rebuild everything processed perfectly.
