### ISSUE TITLE
Monero GUI Wallet toolbar is redundant

### ISSUE THREAD

**Issue by Enkrypto** [monero-project/monero#2769]
[Reference Image](https://imgur.com/a/KOKBo)
One can see that items on the toolbar, such as the minimize, maximize, exit, and application title are redundant with the linux release.

**Comment by moneromooo-monero** [comment]
You can turn it off in the settings (custom decorations). Anyway, please file GUI bugs in the GUI repository: 

https://github.com/monero-project/monero-core/issues

+invalid
