### ISSUE TITLE
GUI sets refresh-from-block-height to a distant future block

### ISSUE THREAD

**Issue by stevesbrain** [monero-project/monero#2802]
Hi all,

Just been playing around with testnet, and noticed that the GUI version 0.11.1 for Linux x64 (and Monerujo) both set the wallets `refresh-from-block-height` to a block far in the future (in my testing, approximately 27850 blocks further down the line). I am making the assumption this is not by design, as it has the effect that a transaction sent to the wallet will show as pending, but once assigned a block + confirmed it will disappear. 

Manually setting the refresh-from-block-height to a lower value and then rescanning the blockchain allows the balance to appear.

_In case this is a GUI-code-specific issue (as I suspect it may be) I've cross posted to https://github.com/monero-project/monero-core/issues/955_

**Comment by binaryFate** [comment]
Fixed in https://github.com/monero-project/monero/pull/2342

**Comment by Jaqueeee** [comment]
+resolved

**Comment by stevesbrain** [comment]
Thanks @binaryFate @Jaqueeee
