### ISSUE TITLE
Сan not send coins

### ISSUE THREAD

**Issue by AntoniMaton** [monero-project/monero#2804]
Hi,
In the wallet monero-gui-win-x64-v0.11.1.0 is not the active send button. There are coins, the wallet is synchronized. What could be the problem?

**Comment by moneromooo-monero** [comment]
Please file GUI bugs in the GUI repo: https://github.com/monero-project/monero-core/issues (unless it happens with the command line monero tools too).
In any case, you have to give some info if you want us to find out. For example, wallet logs (you can set log level to 1 or 2 in the settings page).

**Comment by moneromooo-monero** [comment]
Wrong repo, and no further info.

+invalid
