### ISSUE TITLE
Electroneum BUILD PROBLEM

### ISSUE THREAD

**Issue by minitzi** [monero-project/monero#2810]
Hello
Ubuntu 16.04.3 LTS \n \l

I go this error while trying to install Electroneum
[ 58%] Building CXX object tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o
/usr/src/gtest/electroneum-master/tests/core_tests/block_validation.cpp: In function 'bool {anonymous}::lift_up_difficulty(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&, std::vector<long unsigned int>&, std::vector<long unsigned int>&, test_generator&, size_t, cryptonote::block, const cryptonote::account_base&)':
/usr/src/gtest/electroneum-master/tests/core_tests/block_validation.cpp:48:85: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
       difficulty_type diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                     ^
/usr/src/gtest/electroneum-master/tests/core_tests/block_validation.cpp: In member function 'bool gen_block_invalid_nonce::generate(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) const':
/usr/src/gtest/electroneum-master/tests/core_tests/block_validation.cpp:178:81: error: 'DIFFICULTY_TARGET_V1' was not declared in this scope
   difficulty_type diffic = next_difficulty(timestamps, commulative_difficulties,DIFFICULTY_TARGET_V1);
                                                                                 ^
In file included from /usr/src/gtest/electroneum-master/src/cryptonote_basic/cryptonote_basic.h:47:0,
                 from /usr/src/gtest/electroneum-master/src/cryptonote_basic/account.h:33,
                 from /usr/src/gtest/electroneum-master/src/cryptonote_basic/account_boost_serialization.h:33,
                 from /usr/src/gtest/electroneum-master/tests/core_tests/chaingen.h:47,
                 from /usr/src/gtest/electroneum-master/tests/core_tests/block_validation.cpp:31:

Can anybody help me please ?
Thanks

**Comment by moneromooo-monero** [comment]
Wrong project, this is the monero repo.

+invalid

**Comment by minitzi** [comment]
where i can post ? 
do you have any idee when i press on electroleum they bring me here

**Comment by moneromooo-monero** [comment]
Where did you find the link to this repo exactly ?

**Comment by minitzi** [comment]
https://github.com/electroneum/

**Comment by moneromooo-monero** [comment]
Ah, well, that link seems to be where you should file bugs. When I click on electroneum, it doens't being me here, but on their own repo. What did you do exactly (ie, which links/button did you click) ?

**Comment by minitzi** [comment]
https://github.com/electroneum/electroneum  / Pull Requesst / New Pull REquest / https://github.com/monero-project/monero/compare/master...electroneum:master / ISSUE / New Issue

**Comment by moneromooo-monero** [comment]
OK, that's a github weirdness then. The electroneum people seem to have disabled their bug report page, probably because they don't care about bug reports.

**Comment by minitzi** [comment]
i understand. :) thanks

**Comment by moneromooo-monero** [comment]
Cool. Or you could use monero, which is pretty much the same, but actually builds ^_^

**Comment by minitzi** [comment]
im currenty mining electrneum on a public pool and its ok . i wanted to create my own pool :)
monero is not that profitable at the moment.

**Comment by moneromooo-monero** [comment]
Alright, fair enough. Can you close this please, looks like the bot failed to close it when asked.
