### ISSUE TITLE
Testnet donation command breaks

### ISSUE THREAD

**Issue by Cifrado** [monero-project/monero#2848]
Trying to `donate` in the wallet-cli over testnet leads to the error beneath because of testnet's address incompatibility:

    Error: failed to parse address

This error could be prevented either by stating this command is not callable over testnet or by defining a testnet donation address. The later one has two advantages:

- Allowing the command to be called which should be the case for any command whether being on testnet or not.
- Allowing, before erasing a testnet wallet, to sweep and centralize TXMRs to a wallet which can be used to redistribute its content to people willing to use the testnet later.

I'd be happy to fix this either way.
The second option will however require someone from getmonero to create the testnet wallet first.

**Comment by moneromooo-monero** [comment]
The second option does not require someone from getmonero to create the testnet wallet first. Just make one, and print its seed when running just "donate" on testnet.

**Comment by xmr-eric** [comment]
We could have the testnet donate function send money to the Testnet Faucet

**Comment by Cifrado** [comment]
@xmr-eric Is there any dev approved testnet faucet? I don't know if dis.gratis is one.

**Comment by Maxithi** [comment]
> The second option does not require someone from getmonero to create the testnet wallet first. Just make one, and print its seed when running just "donate" on testnet.

Do you mean `donate` without an argument or just print the seed once a donation has been made?

**Comment by moneromooo-monero** [comment]
Maybe both.

**Comment by dEBRUYNE-1** [comment]
+bug
