### ISSUE TITLE
monerod running with --restricted-rpc makes monero-wallet-rpc error "failed to get random outs"

### ISSUE THREAD

**Issue by vitorgatti** [monero-project/monero#2855]
Similar to the issue #2028, even if `monero-wallet-rpc` is running with the `--trusted-daemon` option, I can't make payments because the error `Issue making payments{"code":-4,"message":"failed to get random outs"}` shows up.

The only way I can make the payments correctly is if I remove the `--restricted-rpc` option from monerod

Is this intended or a bug?

Thank you

**Comment by moneromooo-monero** [comment]
You're probably asking for more fake outs than the restricted limit. Which probably should get increased anyway, so I'll do that.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2856

**Comment by moneromooo-monero** [comment]
+resolved

It'll still happen for even larger amounts of outs, but there's got to be a sane limit somewhere.
