### ISSUE TITLE
[Feature] Add option to export multisig data to ASCII (e.g. text file)

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero#2859]
Currently the following commands write to a file:

`export_multisig_info`
`sign_multisig` 

In addition, both `import_multisig_info` and `submit_multisig` will look for a file. Now imagine a 2/3 multisig case where buyer, seller, and arbitrator don't trust each other. It's highly unlikely that they would download files from each other. An elegant solution would be to export multisig data to ASCII (e.g. to a text file) such that the participants can simply paste their data and subsequently import it. More specifically, wallet A could post the output of `export_multisig_info` on https://paste.fedoraproject.org. Subsequently, wallet B could grab the data, save it to a text file, and lastly import it. 

For convenience, it might be easy to add intuitive multisig commands for this. For instance:

`export_multisig_info_txt`
`import_multisig_info_txt`
`sign_multisig_txt`
`submit_multisg_txt`

**Comment by moneromooo-monero** [comment]
I'm planning on adding a "set export-format raw hex" which will take care of this.
This will work also for other stuff like the cold signing info.

**Comment by stoffu** [comment]
Just a minor comment: the file-less data exchange is already what it is for the RPC mode, and I experienced using the standard terminal on OSX that pasting the long hex string for the (partially signed or fully signed) tx takes quite long, at least a few minutes.

Also, I don't see the difference trustedness-wise between passing the data directly as text vs file download/attachment. If a participant gave some fake data, the end effect is simply that the resulting signature doesn't check.

**Comment by moneromooo-monero** [comment]
It's just about ease of handling, not difference in trust. Sending raw data will end up with possible corruption as people copy/paste, if they don't use files. And we can't really tell people to use the RPC wallet for this.

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by tmoravec** [comment]
I'm going to try to implement this.

**Comment by saloppe73** [comment]
It would help if the output of wallet-cli export/import multisig-data are additional in hex like wallet-rpc. In case of 2/3 when alice and bob use wallet-cli and charly use wallet-rpc there is no way - or did I miss(understand) something?

**Comment by ajs-xmr** [comment]
@moneromooo-monero being able to review the contents of `multisig_monero_tx` in raw hex/json would be very helpful, especially when dealing with multiple transactions to know which file is what by opening a text editor.

**Comment by vtnerd** [comment]
I commented in the PR too, but using the `base64` program will achieve the same thing - ?

**Comment by tmoravec** [comment]
Implemented.

**Comment by dEBRUYNE-1** [comment]
Yes, thanks a lot. Will close this issue.
