### ISSUE TITLE
Docker build might fail due to low memory

### ISSUE THREAD

**Issue by emilianbold** [monero-project/monero#2865]
On macOS Docker is configured by default to use only 2GB of RAM.

Because the Dockerfile calls `make -j$(nproc)` it will fail because there won't be enough RAM for so many distributed jobs.

The error does not really make any reference to a low memory situation:

> c++: internal compiler error: Killed (program cc1plus)

One solution I prefer would be to remove the `-j$(nproc)` flag. This would make the build work, although it might be a bit slower.

The least, a warning message should be printed on low-memory docker containers.

**Comment by moneromooo-monero** [comment]
For the record, "Killed" is the OOM killer.

**Comment by moneromooo-monero** [comment]
+resolved
