### ISSUE TITLE
What is c if cols = 1 Error

### ISSUE THREAD

**Issue by vietanh79** [monero-project/monero#2868]
I cant send coins from my wallet to bittrex wallet

It looked like this:

[wallet 43MhVc]:
[wallet 43MhVc]: balance
Balance: 119.954321910000, unlocked balance: 119.954321910000
[wallet 43MhVc]: transfer 1 463tWEBn5XZJSxLU6uLQnQ2iY9xuNcDbjLSjkn3XAXHCbLrTTErJrBWYgHJQyrCwkNgYvyV3z8zctJLPCZy24jvb3NiTcTJ 19.954321910000 126e621c89b84deea94e248540045e7e528cd164f434455fb09734c2b78f84b0
Wallet password: ************
Error: unexpected error: Error! What is c if cols = 1!
[wallet 43MhVc]:

This synstax is required by bittrex  transfer 1 base address amount payment id
I am using version: 0.11.1.0 Helium Hydra for Windows, 32-bit (Command-line Tools Only)
Can anyone help? Thanks a lot

**Comment by vietanh79** [comment]
I then tried to send to another bittrex wallet. This time the error is different. It said not enough money, but I think the fee is certainly less than 0.9 xmr.

[wallet 43MhVc]: transfer 1 463tWEBn5XZJSxLU6uLQnQ2iY9xuNcDbjLSjkn3XAXHCbLrTTErJrBWYgHJQyrCwkNgYvyV3z8zctJLPCZy24jvb3NiTcTJ 199.95 efa1e884660f4cf4aad2b537593eb3c5fedbf1e09bc84e978422b22e5b0f6254
Wallet password: ************
Error: Not enough money in unlocked balance
[wallet 43MhVc]: transfer 1 463tWEBn5XZJSxLU6uLQnQ2iY9xuNcDbjLSjkn3XAXHCbLrTTErJrBWYgHJQyrCwkNgYvyV3z8zctJLPCZy24jvb3NiTcTJ 199.9 efa1e884660f4cf4aad2b537593eb3c5fedbf1e09bc84e978422b22e5b0f6254
Wallet password: ************
Error: Not enough money in unlocked balance
[wallet 43MhVc]: transfer 1 463tWEBn5XZJSxLU6uLQnQ2iY9xuNcDbjLSjkn3XAXHCbLrTTErJrBWYgHJQyrCwkNgYvyV3z8zctJLPCZy24jvb3NiTcTJ 199 efa1e884660f4cf4aad2b537593eb3c5fedbf1e09bc84e978422b22e5b0f6254
Wallet password: ************
Error: Not enough money in unlocked balance
[wallet 43MhVc]:
Any help is appreciated.

**Comment by iDunk5400** [comment]
You are trying to use an invalid mixin value. Minimum mixin is 5 (and also the default) since the September hardfork.

**Comment by moneromooo-monero** [comment]
That error currently displays a more helpful message about too low mixin.

+resolved
