### ISSUE TITLE
fee == 0 in get_transfer_by_txid rpc method

### ISSUE THREAD

**Issue by prudnitskiy** [monero-project/monero#2879]
As I can see, RPC method `get_transfer_by_txid` shows me zero fee (0). But [moneroblocks](https://moneroblocks.info/search/) shows me real fee and amount? Is it a bug, or deserved behavior? Is there a way to get transaction fee via RPC?

**Comment by moneromooo-monero** [comment]
You've got to give more information, other this is not very useful. Like in or out tx, the JSON you're sending and receiving.

**Comment by prudnitskiy** [comment]
TXID: be83fc780d7d53a1e7cab27b4f0a6f19b22db4a5952166c6ac370a0b59d18f23

request:
```curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_transfer_by_txid","params":{"txid":"be83fc780d7d53a1e7cab27b4f0a6f19b22db4a5952166c6ac370a0b59d18f23"}}' -H 'Content-Type: application/json' -u ********:******** --digest```

response:
```{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "transfer": {
      "amount": 10000000000,
      "fee": 0,
      "height": 1452909,
      "note": "",
      "payment_id": "d40d84a85101579c",
      "timestamp": 1511877503,
      "txid": "be83fc780d7d53a1e7cab27b4f0a6f19b22db4a5952166c6ac370a0b59d18f23",
      "type": "in",
      "unlock_time": 0
    }
  }
}```

**Comment by moneromooo-monero** [comment]
In this case, it looks like it's just "not implemented yet". Since this is an incoming tx, the fee is not tracked. Should be easy to add.

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by onodera-punpun** [comment]
The same happens (a fee of `0`) with get_transfers (on incoming transfers). If I understand correctly this will possibly be added in the future?

**Comment by stoffu** [comment]
#3113

**Comment by moneromooo-monero** [comment]
+resolved
