### ISSUE TITLE
Missing make release-static-linux-x86_64

### ISSUE THREAD

**Issue by StiiCeva** [monero-project/monero#2882]
Is there anyway to make a portable static build for POSIX?

**Comment by moneromooo-monero** [comment]
A portable build for POSIX ? Surely it will depend on arch.
Also, the title is unclear. What is missing ? That target exists.

**Comment by StiiCeva** [comment]
In the dev branch or the stable release? 

I' using the v0.11.0.0  and it does not have that target.

**Comment by danrmiller** [comment]
It is in both the master branch and in the release-v0.11.0.0 branch:

https://github.com/monero-project/monero/blob/c328163ffa28fee3236ddc7a958a50cede727ba6/Makefile#L91-L93

**Comment by StiiCeva** [comment]
my bad some other script replaced it. Sorry about that!
