### ISSUE TITLE
Synchronizing takes forever

### ISSUE THREAD

**Issue by HACKHERS** [monero-project/monero#2884]
Hello, I saw some issues about that I tried what people say about that issues but no luck.

First I've downloaded GUI v2 0.10.3.1 but It instantly stucked so I downloaded the lastest version 0.11.1.0 Helium Hydra. I deleted the C:\ProgramData\bitmonero folder completely. It first started with 1 3xx xxx blocks remaining I waited like 20~ hours after that when 1xx xxx blocks remaining It started from 1 3xx xxx  again. I have no idea what should I do. 

Note: Size of the data.mdb 26.1 GB

**Comment by moneromooo-monero** [comment]
GUI bugs go to https://github.com/monero-project/monero-core please. It looks like you're just seeing two different progress bars, which is confusing and will be changed.

**Comment by moneromooo-monero** [comment]
Known GUI bug, so doesn't belong here.

+invalid
