### ISSUE TITLE
really ignore battery-checking if --ignore-battery option is given

### ISSUE THREAD

**Issue by Piraty** [monero-project/monero#2886]
you should reverse the logic and call that function only if --ignore-battery flag is not used

https://github.com/monero-project/monero/blob/8512a83572094f96aff95e02db359914a37c3c71/src/cryptonote_basic/miner.cpp#L622-L638

sth like 
```
if( m_ignore_battery )
  on_ac_power = true;
else
{
  boost::tribool battery_powered(on_battery_power());
  ...
}
```

because my system, despite having the flag set, issues warnings that it can't find the powersupply status (because there is none).
`ERROR   miner   src/cryptonote_basic/miner.cpp:940      couldn't query power status from /sys/class/power_supply`

**Comment by dEBRUYNE-1** [comment]
+bug
