### ISSUE TITLE
Failure to parse Peerlist

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero#2892]
Peerlist is unable to get parsed, resulting in new users being unable to synchronize with the network.

https://paste.fedoraproject.org/paste/eCzLLhncXl9WT-dFjoF73w
https://paste.fedoraproject.org/paste/XBLw9W2HVaBHCrKpoIeu3A

Issue does not affect Release 0.11.1.0, but current Master

**Comment by brendanmmcmanus** [comment]
@medusadigital The paste is no longer there. Could you please provide the errors?

**Comment by moneromooo-monero** [comment]
I saw them, and I believe I fixed it in https://github.com/monero-project/monero/pull/2906

**Comment by moneromooo-monero** [comment]
Which is now merged. Please confirm it fixes your case.

**Comment by moneromooo-monero** [comment]
+resolved
