### ISSUE TITLE
[Feature] separate, shorter mnemonic for public address

### ISSUE THREAD

**Issue by nasaWelder** [monero-project/monero#2896]
Private seed mnemonic really helps me feel confident that I copied things down. And some people are dyslexic... However on cold storage computer I'm getting really paranoid that I'll send funds to nowhere if I mess up the public Address.

Prevailing wisdom says to copy addresses several times which just increases chance for human error, then there's error in typing it into exchange for use.

QR codes are ok but not helpful for architectures that don't have gui deployed like raspPi(arm7). I also don't like the idea of having to trust my QR code reader also since not human readable. 

I'm sure there's a way to design scheme that won't confuse people with private seed, such as different dictionary, word amount, perhaps more.

**Comment by dEBRUYNE-1** [comment]
>However on cold storage computer I'm getting really paranoid that I'll send funds to nowhere if I mess up the public Address.

Just as fyi, you can always verify your transaction by setting up a view only wallet or "decrypting" the transaction on a block explorer:

https://monero.stackexchange.com/questions/6137/how-do-i-as-a-recipient-verify-that-my-transaction-actually-arrived

**Comment by moneromooo-monero** [comment]
The public address has a checksum.

Changing the encoding format would not solve the problem anyway.

**Comment by nasaWelder** [comment]
@moneromooo-monero so should I delete this?

**Comment by moneromooo-monero** [comment]
If your problem was just a typo in a public address meaning lost monero, yes. Easy to try yourself by the way, and run "set always-confirm-transfers 1" set prior to the test.

**Comment by nasaWelder** [comment]
Not very useful idea, it turns out.
