### ISSUE TITLE
"Refresh-from-block-height" has value of 0 after entering restore height

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero#2898]
Steps to reproduce:

1. Create a new wallet w/ `--generate-from-view key <arg> `

2. Set a restore height (e.g. 1400000) .

3. Once it's fully refreshed, type `set`.

4. It'll show a `refresh-from-block-height` value of 0.

Haven't verified yet, but this probably happens with `--restore-deterministic-wallet` and `--generate-from-keys` too.

**Comment by snirp** [comment]
Can verify that this happens with `--generate-from-keys`. Tried to create a view-only wallet and initially gave a blockheight 0. When trying to correct this from the settings, it remained at 0.

**Comment by moneromooo-monero** [comment]
Works for me, did you use master ?

**Comment by dEBRUYNE-1** [comment]
I used release. I'll try to reproduce later with master.
