### ISSUE TITLE
adding priority node with authentication not allowed

### ISSUE THREAD

**Issue by razorman8669** [monero-project/monero#2927]
I'm trying to add a priority node upon launching the monero daemon like so:
```./monerod --add-priority-node un:pw@111.222.333.444:18089```  however, this results in the daemon quiting upon startup with the log message ```Failed to parse address from string: un:pw@111.222.333.444:18089```

is this just something unsupported?

**Comment by moneromooo-monero** [comment]
Indeed. Use a tunnel if you want to do anything like this.

**Comment by razorman8669** [comment]
I had it all wrong..  I was trying to add a priority node via the RPC port and not the P2P port.  Once I opened the P2P port I was able to connect just fine.  no need for authentication
