### ISSUE TITLE
Donate command needs sanity check

### ISSUE THREAD

**Issue by ghost** [monero-project/monero#2933]
I meant to type `help donate` to see it's description. Instead I typed `donate help`. The CLI then said `Donating help to donate.getmonero.org. Enter password:`

I know this isn't super important, but it might be a good idea to at least make sure it's a number.

**Comment by xmr-eric** [comment]
Also, it might be fun to add a testnet address for use with --testnet flag. Like, the faucet address from https://dis.gratis/

**Comment by moneromooo-monero** [comment]
Are you assuming it does not check, or did you check it does not check ?

**Comment by xmr-eric** [comment]
I'm assuming. I thought if I typed in a string of letters it would error something like "This is not a number". I can close this if there's already a check.

**Comment by moneromooo-monero** [comment]
Well, IIRC this calls the transfer command, so I'm pretty sure it does check.
Now, that message is unfortunate, since it happens before the check, so maybe an extra one might be warranted, or the extra message removed. Anyway, that bug can stay since the message is wonky.

**Comment by Cifrado** [comment]
> Also, it might be fun to add a testnet address for use with --testnet flag. Like, the faucet address from https://dis.gratis/

Same as #2848

**Comment by dEBRUYNE-1** [comment]
+enhancement
