### ISSUE TITLE
Error when trying to submit_transfer. Says "fee too low".

### ISSUE THREAD

**Issue by ghost** [monero-project/monero#2935]
I made sure to `set priority 0` on both ends just to be safe. Perhaps the issue is on my end, but on the new v7 testnet I'm unable submit signed transfers in a view wallet.

https://paste.fedoraproject.org/paste/e5J4WRBVEc2ZO8~xh5aucQ

**Comment by xmr-eric** [comment]
Here's the daemon output: `2017-12-15 18:25:43.537 [RPC1]  WARN    daemon.rpc      src/rpc/core_rpc_server.cpp:690 [on_send_raw_tx]: tx verification failed: fee too low`

**Comment by moneromooo-monero** [comment]
Run again with --log-level 2 in the wallet. In particular, check the tx sizes.

**Comment by xmr-eric** [comment]
Here you go (I think): https://paste.fedoraproject.org/paste/gwnpF8~~LvP7tu~Tt1qURQ

Above line 86 is me inside the CLI. Below line 86 is the monero-wallet-cli.log file

**Comment by moneromooo-monero** [comment]
That doesn't look like a level 2 log.

**Comment by xmr-eric** [comment]
Inside CLI: https://paste.fedoraproject.org/paste/4H1RYnL5GLrsrHZRJR5b0g
CLI log file: https://paste.fedoraproject.org/paste/OkbVYuIXOmBzLMsJEnrUOA
Daemon log file: https://paste.fedoraproject.org/paste/w4Apt6yuogN9FlAfUsMrBQ

**Comment by Maxithi** [comment]
Ping @moneromooo-monero - Response from OP.

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by dEBRUYNE-1** [comment]
Fwiw, I incurred the same error when testing Bulletproofs.

**Comment by xmr-eric** [comment]
Just checking in. Retested with recent master and it still errors out with "fee too low"

**Comment by arnuschky** [comment]
Same problem on stagenet:

```
[wallet 58cisX]: sweep_all 5AiV6wffn42AN3RTkKzE3sKzZHMbNWsCjFCJkdTwb1AZL1pcyK4gjfqZMXXeoumLtmSfELyu9t93d7LXGxMEzPqzVhUwZLn
Wallet password: 
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y

Transaction 1/6:
Spending from address index 0

Transaction 2/6:
Spending from address index 0

Transaction 3/6:
Spending from address index 0

Transaction 4/6:
Spending from address index 0

Transaction 5/6:
Spending from address index 0

Transaction 6/6:
Spending from address index 0
Sweeping 57961.974120396672 in 6 transactions for a total fee of 0.470207580000.  Is this okay?  (Y/Yes/N/No): y

Transaction successfully submitted, transaction <84cb4f6f73226cc22b3a224356357cfbd2d96e364439d9e23ec80305ba71a68e>
You can check its status by using the `show_transfers` command.
Error: transaction <dbf44ce6ea6d6c2ea5dabc73bc5169402ebcdf2fb540abe84c4f037a3c88b758> was rejected by daemon with status: Failed
Error: Reason: fee too low
Height 46332, txid <26263ff1032aace1de58358f46c84df8cde9143d15ebcd23af139d012253c59f>, 33.206587519886, idx 0/0
[wallet 58cisX]: set_log 2
New log categories: *:DEBUG
[wallet 58cisX]: sweep_all 5AiV6wffn42AN3RTkKzE3sKzZHMbNWsCjFCJkdTwb1AZL1pcyK4gjfqZMXXeoumLtmSfELyu9t93d7LXGxMEzPqzVhUwZLn
Wallet password: 
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y

Transaction 1/6:
Spending from address index 0

Transaction 2/6:
Spending from address index 0

Transaction 3/6:
Spending from address index 0

Transaction 4/6:
Spending from address index 0

Transaction 5/6:
Spending from address index 0

Transaction 6/6:
Spending from address index 0
Sweeping 55165.455358629378 in 6 transactions for a total fee of 0.103605060000.  Is this okay?  (Y/Yes/N/No): y
Transaction successfully submitted, transaction <4052893669f8deace0c4e7061b3ee5f549ff50b7c0aff8e5b42b2312cace7f15>
You can check its status by using the `show_transfers` command.
Error: transaction <865d73f4969c6a6ecd2f1823761f29ce46cf4c3dccc35a85e2ef10feacb2ab3a> was rejected by daemon with status: Failed
Error: Reason: fee too low
[wallet 58cisX]: 
```

Version:
```
From the log:monerod --version
Monero 'Lithium Luna' (v0.12.0.0-master-release)
```

I got the full debug log, but it's 30MB.

**Comment by liyanhrxy** [comment]
I have the same issue ??? please tell me why ???

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/monero/pull/3955

**Comment by moneromooo-monero** [comment]
Anybody still getting this with #3955 ? If so, send level 2 wallet logs.

**Comment by arnuschky** [comment]
I tried replicating this with 0.12.3.0 and couldn't. Either my unspents were structured in a way that didn't cause the problem, or it's indeed fixed. I'll try again later.

**Comment by moneromooo-monero** [comment]
Did you repro it ?

**Comment by moneromooo-monero** [comment]
ping :)

**Comment by arnuschky** [comment]
Ah, thanks for the ping @moneromooo-monero. Apologies, totally forgot about it.

No I didn't manage to reproduce it using 0.12.3.0. So from my side this can be closed.

**Comment by moneromooo-monero** [comment]
OK, thanks.

+resolved
