### ISSUE TITLE
wallet-cli cold storage balance

### ISSUE THREAD

**Issue by jakubtrnka** [monero-project/monero#2954]
cold storage generated from viewkey should tell the user that it's not possible to determine the final balance unless key_images are imported. monero-wallet-cli is telling potentially incorrect value.

**Comment by jakubtrnka** [comment]
wallet should tell something like
"verified balance: xxx"
"unverified balance:yyy"
for transaction whose key_images have been imported and whose not respectively.

**Comment by xmr-eric** [comment]
Interesting idea

**Comment by moneromooo-monero** [comment]
The multisig code does this already. Extending it for cold wallets should be a simple task for a newcomer to get their first patch in.

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by dEBRUYNE-1** [comment]
+easy

**Comment by al-maisan** [comment]
I would like to try my hand on this unless someone else is already working on it.

**Comment by moneromooo-monero** [comment]
Go for it, try #monero-dev if you want help finding things.

**Comment by al-maisan** [comment]
I was too optimistic -- 5 weeks passed already and I did not find any time to work on this.
If anyone else is interested: please ignore me and go for it.

**Comment by jakubtrnka** [comment]
Ok, I'll make a try

**Comment by jcktm** [comment]
I'm trying to do this.

Am I correct in understanding that we should modify the existing code so that `balance` shows something like "image keys are not imported" instead of the balances when the image keys are not present?

@moneromooo-monero Right now I am looking at the `simple_wallet::show_balance_unlocked` code. How is this implemented in the multisig code? Is there a file and line number I can check, to see what you mean by this?

**Comment by moneromooo-monero** [comment]
Yes to the first paragraph.
For the second:

  std::string extra;
  if (m_wallet->has_multisig_partial_key_images())
    extra = tr(" (Some owned outputs have partial key images - import_multisig_info needed)");

**Comment by jcktm** [comment]
After looking into this further I think it's not possible to detect if the image keys aren't present, so this is just a simple warning for all watch-only wallets. Is this right?

First attempt at https://github.com/monero-project/monero/compare/monero-project:master...jcktm:wallet-cli-cold-storage-balance?expand=1

**Comment by moneromooo-monero** [comment]
The code I pasted above does it.

**Comment by moneromooo-monero** [comment]
+resolved
