### ISSUE TITLE
Sorry If This is Spamish

### ISSUE THREAD

**Issue by m-henderson** [monero-project/monero#2966]
I couldn't find any other way to contact the person I need to. 

who do I need to contact about using a different platform for the monero forum? 

I am the forum product owner at freecodecamp.org and I control our forum. we use [discourse](https://www.discourse.org/).  I would love to contribute by setting up a more user friendly forum for monero and manage it. 

[here ](https://forum.freecodecamp.org/)is what our forum is like. 

I want to do this because it gives an outlet for people to get involved. I tried using the current forum but it is not mobile friendly or appealing. 

thanks!

**Comment by moneromooo-monero** [comment]
Try fluffypony in #monero on Freenode.

Or you could just do it, and post about it on BCT's monero thread, and reddit, and the above IRC channel. Since it'd be a website controlled by a third party, there's no need for the core team to get involved.

+invalid
