### ISSUE TITLE
Code Style - Line Width Limit

### ISSUE THREAD

**Issue by ilprincipe33** [monero-project/monero#2982]
Please consider formatting all sources by placing a strict column limit to (say) 80 columns to improve readability and maintainability. 

Some source files are extremely difficult to read to the point where I had to use [Clang Format](https://clang.llvm.org/docs/ClangFormat.html) before I could actually start reading the code...

Here is an example of a function that that is currently displayed as a single statement spanning 176 columns:

```C++
bool construct_tx_with_tx_key(const account_keys& sender_account_keys, const std::unordered_map<crypto::public_key, subaddress_index>& subaddresses, std::vector<tx_source_entry>& sources, const std::vector<tx_destination_entry>& destinations, const boost::optional<cryptonote::account_public_address>& change_addr, std::vector<uint8_t> extra, transaction& tx, uint64_t unlock_time, const crypto::secret_key &tx_key, const std::vector<crypto::secret_key> &additional_tx_keys, bool rct, bool bulletproof, rct::multisig_out *msout)
```

[Source](https://github.com/monero-project/monero/blob/master/src/cryptonote_core/cryptonote_tx_utils.cpp#L191)

Here is an example of aforementioned function styled with clang-format using [Mozilla code style](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style) conventions:

```C++
bool
construct_tx_with_tx_key(
  const account_keys& sender_account_keys,
  const std::unordered_map<crypto::public_key, subaddress_index>& subaddresses,
  std::vector<tx_source_entry>& sources,
  const std::vector<tx_destination_entry>& destinations,
  const boost::optional<cryptonote::account_public_address>& change_addr,
  std::vector<uint8_t> extra, transaction& tx, uint64_t unlock_time,
  const crypto::secret_key& tx_key,
  const std::vector<crypto::secret_key>& additional_tx_keys, bool rct,
  bool bulletproof, rct::multisig_out* msout)
```

Hope this helps. GLHF.

**Comment by ilprincipe33** [comment]
Another thing: in C++ source files function definitions are being preceded by a comment line composed of hyphens that look like this: 

```C++
//--------------------------------------------------------------------------------------
std::whatever_t core::my_method() const 
{
/* do whatever ... */
}
```
Presumably, these markers are being interpreted to facilitate code-folding specific to some editor(s). Whatever the case, this is just more cruft that makes code harder to read and should be removed.

**Comment by jasjuang** [comment]
+1 for clang-format, strict 80 column limit is needed

**Comment by moneromooo-monero** [comment]
NAK, no reformatting. If you're adding new code, you're free to keep to 80 columns, though.

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by jasjuang** [comment]
@moneromooo-monero That's unfortunate. I was thinking about contributing to monero on my free time (I am sure @ilprincipe33 is too, that's why we are here), but the current no-coding-style is making the friction to contribute unnecessarily high.

**Comment by fluffypony** [comment]
@jasjuang then create an issue about establishing a coding style, and submit a PR after discussion in that issue. @moneromooo-monero is *only* saying that refactor-as-you-go is acceptable, but necessary refactoring is not.

**Comment by stoffu** [comment]
As someone who's been working on Monero for a little over a year, I'd say the codebase may look a bit overwhelming and intimidating at first sight, but it'll become quite manageable as you get used to it. Monero developers should have at least this level of patience and perseverance, IMO.
