### ISSUE TITLE
Usage of `std::get_time`

### ISSUE THREAD

**Issue by arnuschky** [monero-project/monero#2984]
Current master uses `std::get_time` in `contrib/epee/include/storages/portable_storage_val_converters.h`. This isn't available in GCC 4.x, which should be sufficient as per the requirements. Do you want to update the requirements or shall we replace that method?

**Comment by moneromooo-monero** [comment]
If it's the only thing that's borked there, I'd rather we fix it. strptime should do the trick.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/2986

**Comment by arnuschky** [comment]
:+1:  Worked great, thanks. Managed to build it with gcc 4.8.4

**Comment by moneromooo-monero** [comment]
+resolved
