### ISSUE TITLE
Failure to detect readline on Fedora

### ISSUE THREAD

**Issue by eklitzke** [monero-project/monero#2992]
Monero fails to detect GNU Readline on my computer (Fedora 27). I spent some time looking at this, and the issue is that on my computer linking with -lreadline also requires linking with -ltinfo. I'm not that proficient with CMake, but I think the right thing to do in FindReadline.cmake is:

 * Try compiling the readline test program with just -lreadline
 * If that fails, try compiling with -lreadline and -lcurses
 * If that fails, try compiling with -lreadline and -ltinfo

This would also allow removing the OpenBSD-specific logic introduced in #2874

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/issues/2919 (WIP)

**Comment by moneromooo-monero** [comment]
+duplicate
