### ISSUE TITLE
monero-wallet-rpc --version doesn't output version

### ISSUE THREAD

**Issue by rwdim** [monero-project/monero#2998]
> monero.monero-wallet-rpc --version
> Failed to parse arguments: the option '--rpc-bind-port' is required but missing

wallet-cli works, but rpc does not.

> monero.monero-wallet-cli --version
> Monero Helium Hydra (v0.11.1.0-release)

**Comment by moneromooo-monero** [comment]
It works on master, got fixed a few months ago. Did you test master ?

**Comment by rwdim** [comment]
i built and installed v0.11.1.0 and hour before I posted and it occurs there.

**Comment by moneromooo-monero** [comment]
OK, so most likely fixed.

+invalid
