### ISSUE TITLE
No --detach option for monero-wallet-rpc

### ISSUE THREAD

**Issue by rwdim** [monero-project/monero#2999]
Hi guys,

Wallet RPC is designed to run as a process without UI, so it stands to reason that it should have a --detach option as well.

Yes, I know I can background it with &, but why not be consistent and make all backround-able processes support "--detach"?

Great work otherwise!! :)

**Comment by hyc** [comment]
Why add code for a feature that no one actually needs, since `&` works perfectly well?

**Comment by moneromooo-monero** [comment]
& would still kill the process on term exit IIRC. nohup *might* get around that but I'm not sure...

**Comment by rwdim** [comment]
Just a suggestion.

if consistency isn't a consideration, then it's a non-issue.

**Comment by hyc** [comment]
@moneromooo-monero yes, nohup addresses that for Bourne-style shells. For C-Shell derivatives, it's not needed.

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by lessless** [comment]
RPC service is an API service and only reason to keep it in the foreground is for logs monitoring. Not the most urgent feature, but would be a nice addition imo.

**Comment by moneromooo-monero** [comment]
There is a patch for this, but the author did not use the existing daemon code, and didn't reply. Someone who wants this can feel free to change it.

**Comment by moneromooo-monero** [comment]
+resolved
