### ISSUE TITLE
Monero Standards/Specification Documentation

### ISSUE THREAD

**Issue by ilprincipe33** [monero-project/monero#3001]
In the most recent MRL logs (2017/12/11) one of the devs mentioned (possible) forthcoming documentation for Monero:

> \<suraeNoether> [...] I want to write up the Monero Standards [...] 1) to describe what the monero codebase currently does, 2) why those choices seem to have been made (if monero) or kept (if cryptonote reference), and 3) an outline of possible future algorithms for use in place of each piece.

[Source](https://getmonero.org/2017/12/11/logs-for-the-Monero-Research-Lab-meeting-held-on-2017-12-11.html)

Is there any ETA on when aforementioned docs might be published? If not, do you maintain any internal notes that you would be willing to share? Even tentative, drafts...

**Comment by moneromooo-monero** [comment]
No, and https://github.com/monero-project/research-lab

**Comment by dEBRUYNE-1** [comment]
+resolved
