### ISSUE TITLE
Additional testnet for integration

### ISSUE THREAD

**Issue by amiuhle** [monero-project/monero#3017]
We currently have a v6 and a v7 version of testnet. v6 is still required because applications like Monerujo support testnet, but ship release binaries.

I suggest we create an additional testnet that will run release binaries (eg current v6 testnet fork), making it easier to set up demos which people can quickly test using a wallet like Monerujo.

We already have this situation at the moment, it's just about making it "official", give it a name and it's own ports and set up some rules how frequently it will be reset.

Hardforks could be deployed a couple of weeks before they go live on mainnet to potentially catch some additional bugs.

I initially called it `staging`, but maybe `integration` would be a better name.  
https://www.reddit.com/r/Monero/comments/7mcte3/can_we_have_a_staging_testnet/

Thoughts?

**Comment by moneromooo-monero** [comment]
"applications like Monerujo support testnet, but ship release binaries"

Isn't there a contradiction between "testing" and "release" ?

**Comment by fluffypony** [comment]
@moneromooo-monero the discussion I had with @binaryFate was around three nets:

- Devnet, which is the current testnet renamed. It lets us test future forks and features live.
- Testnet, which is a new net, new ports, and matches the live environment by forking at roughly the same time.
- Mainnet, stays as-is.

The big change is that testnet becomes a "staging" testnet, which lets integrators play and test without burning live funds.

**Comment by moneromooo-monero** [comment]
Then whoever does this, please also add the "fake chain" overrides used by core tests.

**Comment by hyc** [comment]
I'm kinda inclined to keep testnet with its current network and ports, and come up with a new name for the newly created staging network. But I guess it's not crucial and we could go with this existing proposal as-is.

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by moneromooo-monero** [comment]
stoffu has done this (see link above). For this network to be useful, it'll need people who asked for it to mine on it semi-reguarly, as well as some seeding data (ie, transactions). This patch will most likely go in for the coming release, and will be set to fork till v6 over some yet to be determined timeframe. This will allow pre-rct txes to be recorded on the blockchain so this new network gets a representative set of data. So be prepared to mine when this goes live.

**Comment by moneromooo-monero** [comment]
+resolved

It's not using rct though, people who want to use this will need to decide when they want to switch.
