### ISSUE TITLE
Latest master code doesn't connect to testnet

### ISSUE THREAD

**Issue by emesik** [monero-project/monero#3018]
I compiled the code from master (tip at 270236e) and it fails to connect to testnet. I launch it without any fancy command line settings, just `--testnet --log-level 2`. The log contains numerous *handshake failure* messages but nothing that could hint me what the exact reason is.

I submit an example log file.
[monerod.log.txt](https://github.com/monero-project/monero/files/1590037/monerod.log.txt)

**Comment by moneromooo-monero** [comment]
Is that still the case ? If so, try adding: --add-exclusive-node 5.9.100.248:28080

**Comment by emesik** [comment]
It didn't help, the daemon complained about a block having invalid version for its height.

I'm downloading the blockchain again. Will post an update then.

**Comment by moneromooo-monero** [comment]
Ah, you might have synced with a v6 daemon past the v7 height, as we did not have much notice for poeple to update.

**Comment by emesik** [comment]
It works now with the node address you provided. Thanks.
