### ISSUE TITLE
Cannot Restore Deterministic Wallet from Seed Using latest build

### ISSUE THREAD

**Issue by phloatingman** [monero-project/monero#3025]
I'm running Ubuntu Mate 16.04.3 64-bit

After I build, this is the version of the CLI wallet
Monero 'Helium Hydra' (v0.11.1.0-master-a0a8706)

After I run, this command.. I am able to input the seed, but it just hangs forever and I have to Ctrl+c to quit

./monero-wallet-cli --log-level 4 --restore-deterministic-wallet

Here is the log file...
https://gist.github.com/phloatingman/376a3edb2c3ad8e2499d00bce80f47cc

Here is a screenshot of my terminal session...
https://i.imgur.com/PdLDCXd.png

**Comment by stoffu** [comment]
I can't reproduce this on Mac. Restoring wallet from seed is such a frequently used tool that this bug is likely specific to Ubuntu Mate (or possibly also to a few other platforms).

**Comment by phloatingman** [comment]
Thanks for looking into it...

Hmmmm..  I just tried on Antergos an Arch based OS and it still would hang on restoring from seed and I needed to ctrl+c out of it.. screenshot..

https://i.imgur.com/U1Vjsmk.png

**Comment by moneromooo-monero** [comment]
Possibly it's prompting for a password and the prompt is getting buffered. Try pressing enter when it looks blocked.

**Comment by phloatingman** [comment]
You're right!  I just had to press enter a second time, then it asks for a password and continues as expected...

screenshot...
https://i.imgur.com/rSpIrXz.png

Thanks for checking it out!  A bit confusing for an end user having to press enter twice though...

**Comment by moneromooo-monero** [comment]
Does https://github.com/monero-project/monero/pull/2960/files help ?

**Comment by phloatingman** [comment]
Sorry, I'm a bit new to git.. do I build after running this command to see if 2960 works?

git clone -b ms-next https://github.com/moneromooo-monero/bitmonero

**Comment by moneromooo-monero** [comment]
Yes, you could do that.

**Comment by phloatingman** [comment]
Restoring from seed seems to work correctly using that branch. Thanks!
