### ISSUE TITLE
Segmentation fault (core dumped) with latest build after restoring a wallet from keys and trying to check balance

### ISSUE THREAD

**Issue by phloatingman** [monero-project/monero#3026]
I'm running Ubuntu Mate 16.04.3 64-bit in virtualbox

After I build from master, this is the cli version...
Monero 'Helium Hydra' (v0.11.1.0-master-a0a8706)

After I run this command..
./monero-wallet-cli --log-level 4 --generate-from-keys fromkeys

I am able to input the standard address, secret spend key, and secret view key.. however, when I run the balance command, it gives me segmentation fault (core dumped)

Here is the log file..
https://gist.github.com/phloatingman/440f695ea21fe0342454ace52c764402

Here is a screenshot of my terminal session...
https://i.imgur.com/sb3JBvp.png

After the Segmentation fault (core dumped) error, I can open the wallet normally and see balance without issue.. as seen here...
https://i.imgur.com/HdOnsIy.png

**Comment by stoffu** [comment]
This is a bug. #3028
Thank you for reporting!

**Comment by moneromooo-monero** [comment]
+resolved
