### ISSUE TITLE
Dockerfile returning 'make: *** No rule to make target 'release-static'.  Stop.'

### ISSUE THREAD

**Issue by allexlima** [monero-project/monero#3039]
Hi, 

When I try building the [dockerfile](https://github.com/monero-project/monero/blob/master/Dockerfile), I get the following error:

```bash
$ docker build -t monero-alone .
Sending build context to Docker daemon  3.072kB
Step 1/14 : FROM ubuntu:16.04 as builder
 ---> 00fd29ccc6f1
Step 2/14 : RUN apt-get update &&     apt-get --no-install-recommends --yes install         ca-certificates         cmake         g++         libboost1.58-all-dev         libssl-dev         libzmq3-dev         libreadline-dev         libsodium-dev         make         pkg-config         graphviz         doxygen         git
 ---> Using cache
 ---> 2972a74e2ff1
Step 3/14 : WORKDIR /src
 ---> Using cache
 ---> 8002585c60cf
Step 4/14 : COPY . .
 ---> Using cache
 ---> aaaefc2d8326
Step 5/14 : ARG NPROC
 ---> Using cache
 ---> 63b20d47afc3
Step 6/14 : RUN rm -rf build &&     if [ -z "$NPROC" ];then make -j$(nproc) release-static;else make -j$NPROC release-static;fi
 ---> Running in 96a3fdc888ea
make: *** No rule to make target 'release-static'.  Stop.

```

Is it any problem with the dockerfile?

**Comment by moneromooo-monero** [comment]
The Makefile has a release-static target, so it's not using the right makefile. Can you tell which one it's trying to use (ie, add a call to pwd before calling make) ?

**Comment by MoroccanMalinois** [comment]
fwiw, i just tried to rebuild the image and it works fine. 

@allexlima Did you clone the repo or just took the dockerfile ?

**Comment by allexlima** [comment]
@moneromooo-monero I tried to add `pwd`  before `rm -rf build && \` (line 26) in the Dockerfile, but it didn't return anything :/

@MoroccanMalinois I just took the dockerfile from the repo

**Comment by allexlima** [comment]
update: I tried cloning the repo and then build the dockerfile and now it worked =)

**Comment by ealexhaywood** [comment]
In my particular case, the Makefile was being ignored in the `.dockerignore` file.  Drove me nuts trying before I realized thats what it was

**Comment by hsyia** [comment]
So I ran into this same problem saying `make: *** No rule to make target 'release-static-android-armv8'. Stop`  on android64.Dockerfile and I changed the last part to be

```
ADD . /src
RUN cd /src \
    && pwd \
    && ls /src \
    && CMAKE_INCLUDE_PATH="${PREFIX}/include" \
       CMAKE_LIBRARY_PATH="${PREFIX}/lib" \
       ANDROID_STANDALONE_TOOLCHAIN_PATH=${TOOLCHAIN_DIR} \
       USE_SINGLE_BUILDDIR=1 \
       PATH=${HOST_PATH} make release-static-android-armv8 -j${NPROC}
```

and I found out that it was copying my files from utils/build-scripts/ into src/

so my src/ directory looked like 

android64.Dockerfile
android32.Dockerfile
windows.bat

when it was supposed to be copying my repository. 

I fixed this by running docker from the root directory monero/ instead of monero/utils/build-scripts/ so that ADD . / actually adds the src code to the docker blahhhhh
