### ISSUE TITLE
Provide SHA3 hashes on downloads page of getmonero.org

### ISSUE THREAD

**Issue by b-g-goodell** [monero-project/monero#3041]
Since SHA256 is vulnerable to length extension attacks, the downloads page of getmonero.org should include at least the SHA3 hash for each file.

**Comment by b-g-goodell** [comment]
I'm aware that a more complete "canonical" list is available, but I don't think the sha256 hash should be the one on getmonero.org

**Comment by MitchellBerry** [comment]
The hashing is to check file integrity, not for security. If getmonero/repo is compromised changing the hash is trivial. Verifying the signature determines authenticity and ensures security, the particular hash function used doesn't really matter. 

 Length extension is used against HMAC's where a secret part of the hash is not known.

**Comment by Maxithi** [comment]
Whichever the outcome is, this issue is more related to the [monero-site repository](https://github.com/monero-project/monero-site/issues).

**Comment by dEBRUYNE-1** [comment]
@b-g-goodell Please reopen this issue on the monero-site repository.

+invalid
