### ISSUE TITLE
monerod on MacOS should automatically write output to ~/Library/Application Support/Monero

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero#3044]
Monero 'Helium Hydra' (v0.11.1.0-release)

Reproducibility: always

Steps:
Run monerod directly from Terminal.

What happened:
monerod writes output to ~/.bitmonero

Expected result:
monerod writes output to ~/Library/Application Support/Monero

**Comment by moneromooo-monero** [comment]
Can you post the output of "monerod --os-version" please ?

**Comment by rex4539** [comment]
`OS: Darwin Darwin Kernel Version 17.4.0: Mon Dec 11 21:15:27 PST 2017; root:xnu-4570.40.9~4/RELEASE_X86_64 17.4.0`

**Comment by moneromooo-monero** [comment]
For whoever has a mac and looks at this, I think it might need replacing "#ifdef MAC_OSX" with "#ifdef __APPLE__" in src/common/util.cpp. Odd that it would not have been found before though.

**Comment by stoffu** [comment]
I've used Mac for a while and never observed the `~/Library/Application Support/Monero` folder being created (at least with the last couple of OS versions).

**Comment by Maxithi** [comment]
@rex4539  Per #3052 it has been chosen to have as UNIX output folder `~/.bitmonero` and remove the previously unused Mac specific code.

**Comment by jtgrassie** [comment]
This needs closing as it's misleading.

**Comment by Maxithi** [comment]
And the `invalid` tag.

**Comment by jtgrassie** [comment]
Personally, I prefer the OP to acknowledge and close.

**Comment by rex4539** [comment]
ack
