### ISSUE TITLE
Consider deprecating the wallet RPC methods getheight, getaddress and getbalance

### ISSUE THREAD

**Issue by onodera-punpun** [monero-project/monero#3045]
https://getmonero.org/resources/developer-guides/wallet-rpc.html

Consider deprecating the wallet RPC methods `getheight`, `getaddress` and `getbalance` in favor of more consistent names using snake case like all other methods, so:  `get_height`, `get_address` and `get_balance`.

**Comment by Sylvyrfysh** [comment]
#3047 implements suggested behavior

**Comment by moneromooo-monero** [comment]
+resolved
