### ISSUE TITLE
Bus 10 error - does someone want to look at DB

### ISSUE THREAD

**Issue by jwm1969** [monero-project/monero#3046]
My lmdb/data.mdb got corrupt around last block (is my assumption based on error), was wondering if someone wanted the DB before I deleted it.  I was able to recover by doing an export / import versus a slow re-sync

FYI:  export reported Bus 10 error around last block but export/import still worked for recovery.

commands performed:

blockchain-export 
renamed ~/.bitmonero/lmdb/ directory. 
monero-blockchain-import --verify 0 --database lmdb#nosync

**Comment by moneromooo-monero** [comment]
Did your computer/OS crash before you got this corruption ?

Good thinking about the export/import :)

**Comment by jwm1969** [comment]
I think my Macbook Pro either crashed or the battery ran out because when i plugged it in it required a cold start...leaning towards abrupt shutdown for sure.

**Comment by selsta** [comment]
Closing, issue doesn't seem relevant anymore.
