### ISSUE TITLE
INode Iwallet.

### ISSUE THREAD

**Issue by Andrewsopoku** [monero-project/monero#3050]
Please i would want to create a web wallet for cryptonote coin where users won't have to run a node or wallet daemon. They will be able create and initialize their wallet with their password, sync with my node, make transactions and others. The clue I have is I can do that with IWallet but my problem is how I will be able to interact with IWallet.

**Comment by dEBRUYNE-1** [comment]
You might want to look at the MyMonero & Openmonero repositories:

https://github.com/moneroexamples/openmonero

https://github.com/mymonero

Also, this issue doesn't belong on the monero repository.

+resolved
