### ISSUE TITLE
monerod testnet options

### ISSUE THREAD

**Issue by hyc** [monero-project/monero#3054]
Two topics:
1) we have a --testnet flag for running in that mode. We also have a plethora of --testnet-* flags corresponding to the same purpose as the regular flags. (e.g. --testnet-rpc-bind-port corresponding to --rpc-bind-port, etc.) Since monerod can't operate on both mainnet and testnet simultaneously, all of these --testnet-* flags are redundant. We should just use the plain flags and toggle their behavior according to the overriding --testnet flag, and delete all of the other --testnet-* flags.

Also, when we remove the --testnet-data-dir option: the --data-dir option will always refer to the mainnet directory. The "/testnet" will be hardcoded to be appended to whatever selected directory. The hardcoding is intended to avoid getting mainnet and testnet DBs confused with each other.

2) this also impacts #3017 but it should actually help, by avoiding even more proliferation of flags.

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by moneromooo-monero** [comment]
+resolved
