### ISSUE TITLE
monero-wallet-cli --generate-from-json asks to restore from height when scan_from_height is set.

### ISSUE THREAD

**Issue by mikemhenry** [monero-project/monero#3080]
When using

`monero-wallet-cli --generate-from-json test_wallet.json `

with` test_wallet.json` containing:
```

{
        "version": 1,
        "filename": "test_wallet_json",
        "scan_from_height": 0,
        "password": "",
        "seed": "REDACTED"
}
```

I get
```

Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to ./monero-wallet-cli.log
Restore from specific blockchain height (optional, default 0),
or alternatively from specific date (YYYY-MM-DD):
```
The behavior I expected was if `scan_from_height` is set, for that height to be used and not prompt the user to enter a height or date.

Thanks!

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by mikemhenry** [comment]
To further help triage/diagnose this, I've noticed the same behavior when using the command line argument `--restore-height=0` that is to say, it ignores what I put for the height and asks me for a date or height interactively.
