### ISSUE TITLE
"Height x, transaction <>, unsupported transaction format" messages appearing in terminal whilst restoring from seed or keys

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero#3086]
These messages will appear in the terminal when you restore a wallet from the 25 word mnemonic seed or the private keys. I incurred this one testnet, so only a few of those appeared in the terminal, but there are a lot more on mainnet. This can be somewhat confusing and therefore it would, in my opinion, be best to move these messages to the log.

**Comment by dEBRUYNE-1** [comment]
+easy

**Comment by stoffu** [comment]
#3257

**Comment by moneromooo-monero** [comment]
+resolved
