### ISSUE TITLE
fungshui=(fork monero + customize) info_request

### ISSUE THREAD

**Issue by 3ch0elite** [monero-project/monero#3089]
Not sure if this is right place to post: 
Project for learning = [Forking monero and making my own little brother version called "fungshui"]
(any monero docs similar to  cyrptonote inner instructions)

Thanks in advance, if in wrong place for discussing please direct me to appropriate place to learn.

**Comment by FndNur1Labs** [comment]
im confused they lib something missing lol~

**Comment by Maxithi** [comment]
I'm not sure what this ticket is about. Are you asking permission, help, ... ?

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help desk.

For information, try:
getmonero.org
monero.stackexchange.com
or the source code

+invalid
