### ISSUE TITLE
Can the tags "monero" and "cryptocurrency" be added to this repo?

### ISSUE THREAD

**Issue by c789** [monero-project/monero#3090]
[Someone](https://www.reddit.com/r/Monero/comments/7oymah/can_monero_project_on_github_add_the_tags_monero/) asked about this on the subreddit so I created an issue.

**Comment by anonimal** [comment]
Referencing https://github.com/monero-project/meta/issues/78 @fluffypony @luigi1111.

**Comment by fluffypony** [comment]
Done
