### ISSUE TITLE
--print-genesis-tx

### ISSUE THREAD

**Issue by 3ch0elite** [monero-project/monero#3100]
Ive been reading over monero source and comparing to cryptonote.
What do I need to do to get new genesis block to test with monero? I dont want to use testnet.
I want to recompile --print-genesis-tx code back into /monero/src/daemon
cryptonote only had 3 files compared to monero. It looks like monero has just organized arg better. But makes it alot more confusing for me.

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help desk.
Your question has an answer on monero.stackexchange.com.

+invalid
