### ISSUE TITLE
Deamon starts, network sync complete Wallet-CLI wont connect

### ISSUE THREAD

**Issue by digitalhuman** [monero-project/monero#3101]
Hi there,

The monerod started fine. It synct perfectly and when I don't use --detach i can see the status etc. No problem. When use --detach I can not see anything but thats fine.

status
Height: 1484738/1484738 (100.0%) on mainnet, not mining, net hash 585.31 MH/s, v6, up to date, 9(out)+0(in) connections, uptime 0d 0h 6m 13s
sync_info
Height: 1484738, target: 1484738 (100%)

When I look at netstat -ln I see the RPC deamon is binded to 127 and port 18081. 

tcp        0      0 0.0.0.0:18080           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:18081         0.0.0.0:*               LISTEN

You think, well, sounds good lets start the wallet-cli. Its starts, asks for the password etc. Then I get:

**********************************************************************
Use "help" command to see the list of available commands.
**********************************************************************
Error: wallet failed to connect to daemon: 127.0.0.1:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Error: wallet failed to connect to daemon: 127.0.0.1:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.

Background refresh thread started

[wallet 494XKV (no daemon)]: help

Any idea what is going on? I can't seem to figure it out.

**Comment by moneromooo-monero** [comment]
I assume you're doing this on the same VM/machine.

Can you connect using telnet ?  telnet 127.0.0.1 18081

**Comment by digitalhuman** [comment]
Yes same machine. Yeah I can connect with telnet. No problem.

monero]# telnet 127.0.0.1 18081
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^C
Connection closed by foreign host.

**Comment by moneromooo-monero** [comment]
Start both monerod and monero-wallet-cli with `--log-level 1,*rpc*:DEBUG,*wallet*:DEBUG` and see if you get any errors/warnings.

**Comment by digitalhuman** [comment]
**********************************************************************
Use "help" command to see the list of available commands.
**********************************************************************
Error: wallet failed to connect to daemon: http://127.0.0.1:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Error: wallet failed to connect to daemon: http://127.0.0.1:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Background refresh thread started

[wallet 494XKV (no daemon)]:

**Comment by digitalhuman** [comment]
No errors, debug messages, nothing

**Comment by moneromooo-monero** [comment]
The prompt means you've got that from the console, not the log file, right ? The wallet doesn't print logs to the console.
About the daemon, since there are already logs with default log level, there's bound to be some unless there's a typo in the parameter.

**Comment by digitalhuman** [comment]
Exactly, from the console. 
Started with: 
monerod --data-dir=/mnt/blockchain/monero --log-file /var/log/monero.log --log-level 1 --no-igd --rpc-bind-ip 127.0.0.1 --rpc-login ****

**Comment by digitalhuman** [comment]
Again tried with: monero-wallet-cli --log-level 1,*rpc*:DEBUG,*wallet*:DEBUG --daemon-host 127.0.0.1

No error, no entry in the logfile, nothing on screen

**Comment by moneromooo-monero** [comment]
That last message doesn't look like a monero error message. Do you have some MITM software that's maybe intercepting data ?

**Comment by digitalhuman** [comment]
@moneromooo-monero No thats just the HTML browser output. Nothing special

**Comment by moneromooo-monero** [comment]
OK, so a HTML browser will not speak JSON RPC. The RPC end point is at json_rpc anyway.
You didn't run monerod with the full log command btw.

**Comment by digitalhuman** [comment]
Hoever I do see my attempts. Is the RPC auth string for --rpc-login correct? What did I miss for 'full log' then?

018-01-11 16:37:02.190     7fe637121740        INFO    msgwriter       src/common/scoped_message_writer.h:102  Background refresh thread started
2018-01-11 16:37:02.270     7fe637121740        ERROR   net.http        contrib/epee/include/net/http_client.h:421      Client has incorrect username/password for server requiring authentication

**Comment by digitalhuman** [comment]
Apperently I had --daemon-login not identical to the --rpc-login value when starting monerod.

**Comment by antechdemo** [comment]
Hi, @digitalhuman !
How are you?
Did you solve the Wallet-CLI problem: not able to connect with Wallet-CLI.

Error: wallet failed to connect to daemon: 127.0.0.1:28081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.

**Comment by ff0255** [comment]
JM2C
This error messages of monero-wallet-cli could be more informative and less misleading... I spent several hours trying to figure out what's wrong with daemon until found this issue...

**Comment by blackout314** [comment]
> JM2C This error messages of monero-wallet-cli could be more informative and less misleading... I spent several hours trying to figure out what's wrong with daemon until found this issue...

and error is?
