### ISSUE TITLE
Signature mismatch, connection will be closed

### ISSUE THREAD

**Issue by SpliffyMap** [monero-project/monero#3106]
Hello. I working on Monero app for android for couple a weeks. So first I need to understand how Monero source code works. I compiled it and it works, great! And suddenly I understand that current blockchain is 27 GB. Little too large for testing on my testing seed nodes, testnet not good too.

So what I did. I changed Network ID and it's not downloading current chain anymore. Great!
![selection_032](https://user-images.githubusercontent.com/35120072/34845901-258a02ee-f71f-11e7-9a4d-0630d07bb574.png)

I have only two testing nodes so looks like I need to change min nodes. Also IP addresses.
![selection_034](https://user-images.githubusercontent.com/35120072/34845913-2f0aead6-f71f-11e7-9936-1017608f1f99.png)

Just in case removed DNS node lists.
![selection_033](https://user-images.githubusercontent.com/35120072/34845955-5b725f6e-f71f-11e7-9fd5-8b27e985413f.png)

So it started new chain. Good start for testing! But no, android library doesn't working. I was thinking, maybe I do something wrong. Just in case tested monero-ui. Compiled, connected to node ip and got this error.
![selection_042](https://user-images.githubusercontent.com/35120072/34846110-cb83af24-f71f-11e7-990a-cb0e0f9ac7be.png)

So my question, how Network ID change made this signature mismatch problem and how to deal with it and fix it? Thank you, I'm very new guy here!

**Comment by dEBRUYNE-1** [comment]
As a sidenote, it's more trivial to set up a private testnet. Guide here (needs some tweaking though, as it's fairly outdated):

https://moneroexamples.github.io/private-testnet/

**Comment by SpliffyMap** [comment]
But if I choose my way, how to make signature match?

**Comment by jtgrassie** [comment]
This smells like coin-fork questions.

**Comment by dEBRUYNE-1** [comment]
@SpliffyMap Is this for a fork of Monero or?

**Comment by jtgrassie** [comment]
Why else would someone need to change the network ID? And be asking about genesis block creation on another Monero fork (https://github.com/sumoprojects/sumokoin/issues/56)? IMO this issue needs closing as invalid.

**Comment by SpliffyMap** [comment]
No matter, just downloaded 54 GB of data :+1: All good :+1:
