### ISSUE TITLE
Failed to import outputs: Transaction extra has unsupported format at index 17

### ISSUE THREAD

**Issue by bullno1** [monero-project/monero#3109]
I could not import outputs using monero-cli 0.11.1.

First I export outputs from a monero-cli connected to an online and synced monerod: `export_outputs outputs`.

Then I move that `outputs` file to the offline machine, start monero-wallet-cli and do: `import_outputs outputs`

All I get is:

> Failed to import outputs: Transaction extra has unsupported format at index 17

So I tried to `rescan_bc` on the hot wallet and the outputs still can't be imported. Now both the hot and cold wallet are showing different balances because outputs can't be imported and I believe my wallet is unusable now that outputs aren't properly tracked in the hot/cold wallet. I have already tried to export key images and importing to hot wallet anyway in case that error is just a warning but the balances shown still differ.

Monero version: 0.11.1.0 for Linux 64bit.

OS of monerod: ArchLinux

OS of monero-wallet-cli: Fedora-25 guest inside QubesOS 3.2.

I am willing to provide viewkey if needed.

**Comment by bullno1** [comment]
I dig through the code base and found the problem here:

https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L8643

If I understood this correctly an invalid extra field which can totally be set by a sender can render my wallet unusable? Is it safe to ignore this check? How important are extra field? I tried looking up here https://github.com/monero-project/monero/blob/master/src/cryptonote_basic/tx_extra.h#L186 but the names are totally cryptic.

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/monero/pull/3065

+resolved
