### ISSUE TITLE
Build fails on Ubtunu 16.04 AMD64 - miniupnpc issue?

### ISSUE THREAD

**Issue by qskousen** [monero-project/monero#3111]
When building from a clean version of master, make returns this error:

<code>
[ 48%] Linking CXX executable ../../bin/monerod
/usr/bin/ld: ../../external/miniupnpc/libminiupnpc.a(miniupnpc.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../../external/miniupnpc/libminiupnpc.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
</code>

**Comment by SpliffyMap** [comment]
Here you go not merged yet fixes #3103 & #3099 :+1:

**Comment by qskousen** [comment]
that was fast. thank you!
