### ISSUE TITLE
prevent user from `export_key_images` to a filename that will overwrite .keys file

### ISSUE THREAD

**Issue by PsychicCat** [monero-project/monero#3117]
I have seen a couple sorry users report on reddit with problems because they executed `export_key_images` overwriting their .keys file without knowing what it was doing. 

Perhaps the command could check if they are about to write to a filename that is the same as their wallet and error out beforehand.

**Comment by stoffu** [comment]
#3118

**Comment by moneromooo-monero** [comment]
+resolved
