### ISSUE TITLE
How to import blockchain into directory on a different drive. 

### ISSUE THREAD

**Issue by picklesos** [monero-project/monero#3122]
I downloaded the `Windows, 64-bit CLI v 0.11.1.0`. I tried syncing the blockchain but it was taking too long so I downloaded the `blockchain.raw` but when I put the command in CMD it imports it into its default location. I have my blockchain and everything on another drive. How would I import the blockchain onto that drive not the default C: drive directory.

**Comment by moneromooo-monero** [comment]
--data-dir /path/you/want

Further help is available on #monero on Freenode, or reddit. This is a bug tracker.

+invalid
