### ISSUE TITLE
Please update to the current version of easylogging++

### ISSUE THREAD

**Issue by yurivict** [monero-project/monero#3124]
On FreeBSD I have the external package installed, and would rather use it, but monero is incompatible with the current version.

**Comment by moneromooo-monero** [comment]
It wouldn't help as we have patches over it to add logging categories.

**Comment by yurivict** [comment]
> It wouldn't help as we have patches over it to add logging categories.

Why don't you submit these patches to easylogging++  for inclusion?

**Comment by moneromooo-monero** [comment]
Because they change the way their hierarchical logging works, which I doubt is wanted.

**Comment by moneromooo-monero** [comment]
I'll still update it at some point, though.

**Comment by MaxXor** [comment]
Bump, maybe update it before the next release @moneromooo-monero ?

**Comment by moneromooo-monero** [comment]
After it.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4713

**Comment by moneromooo-monero** [comment]
+resolved
