### ISSUE TITLE
Log origin IP in HTTP parsing error messages.

### ISSUE THREAD

**Issue by Maxithi** [monero-project/monero#3127]
@hyc encountered the following error after a possible telnet:
```
[RPC1]  ERROR   net.http        contrib/epee/include/net/http_protocol_handler.inl:365  simple_http_connection_handler<t_connection_context>::handle_invoke_query_line(): Failed to match first line: ^V^C
[RPC1]  ERROR   net.http        contrib/epee/include/net/http_protocol_handler.inl:303  simple_http_connection_handler::handle_char_out: Error state!!!
```

The error should at least state the originating IP. We might consider to auto-blacklist these kind of connections after certain amount of attempts.

**Comment by moneromooo-monero** [comment]
+easy

Can you rename this to something sensible please :) Like, log origin IP in HTTP parsing error messages or somesuch.

**Comment by garwahl** [comment]
I'd like to make an attempt at this if no one has had a shot. Where would I begin?

**Comment by moneromooo-monero** [comment]
Find those messages (git grep). See if you can access the connection context, which holds the IP. Change the log message (there are log macros which automatically use the context to display source).

**Comment by moneromooo-monero** [comment]
+resolved
