### ISSUE TITLE
monerod does DNS lookups and attempts to connect to other nodes, even if specifying an exclusive node

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero#3128]
I tried launching `monerod` on `node A` with these args:

```sh
"$MONEROD" \
    --add-exclusive-node 127.0.0.1:18090 --allow-local-ip \
    --p2p-bind-ip 127.0.0.1 \
    --rpc-bind-ip 127.0.0.1 \
    --no-igd \
    --hide-my-port \
    --db-sync-mode safe
```

Port 18090 is forwarded from my other `node B` via SSH.

Still, `monerod` on `node A` does DNS lookups on the [seed nodes](https://github.com/monero-project/monero/blob/c611cca4624e3556a5e68b745acbcfbfab71618a/src/p2p/net_node.h#L127-L130) using Google DNS (8.8.4.4) and tries to connect to the various nodes returned.
This is a privacy issue and should not happen when `--add-exclusive-node` is used.

__EDIT__:
Fix Google DNS IP, `monerod` is not using 8.8.8.8.

**Comment by moneromooo-monero** [comment]
Which commit hash are you running ?

As for DNS lookups, ifyou don't want them, use DNS_PUBLIC=somethinginvalid or tcp://127.0.0.1

**Comment by leonklingele** [comment]
> Which commit hash are you running ?

Latest stable release (793bc973746a10883adb2f89827e223f562b9651)

> As for DNS lookups, ifyou don't want them

Why do I need to opt-out for privacy? DNS lookups are not required when `--add-exclusive-node ` is used.

**Comment by leonklingele** [comment]
> tcp://127.0.0.1

That wouldn't help if I had a local DNS resolver running, right?

**Comment by moneromooo-monero** [comment]
Then it's fixed by 054054c92f5d6fe6c598a31c64c215485a7f4995.

Why do you think --add-exclusive-node is a DNS option ? It is not.

**Comment by leonklingele** [comment]
> Why do you think --add-exclusive-node is a DNS option ? It is not.

Why would the daemon need to connect to a DNS server if it only needs to connect to a single IP which was specified via a command line arg?

**Comment by moneromooo-monero** [comment]
To get updates and checkpoints.

**Comment by leonklingele** [comment]
Where does it check for updates / try to retrieve checkpoints from? I assume it uses other nodes. Why is the exclusive node I'm providing not sufficient enough to do that?

**Comment by leonklingele** [comment]
OK, doesn't look like it. I will try to start `monerod` with `--check-updates disabled`. Is there a way to disable checking for checkpoints via DNS?

**Comment by moneromooo-monero** [comment]
It appears not. --offline disables those, but a "just for DNS" switch would seem useful.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3143

**Comment by leonklingele** [comment]
I'm now starting `monerod` with the above flags including `--check-updates disabled --disable-dns-checkpoints`, however it still looks up `seeds.moneroseeds.*`

**Comment by moneromooo-monero** [comment]
Try --seed-node SAMEIP:SAMEPORT

**Comment by moneromooo-monero** [comment]
Or:

```
diff --git a/src/p2p/net_node.inl b/src/p2p/net_node.inl
index 269a9ba..1423518 100644
--- a/src/p2p/net_node.inl
+++ b/src/p2p/net_node.inl
@@ -1107,7 +1107,7 @@ namespace nodetool
   template<class t_payload_net_handler>
   bool node_server<t_payload_net_handler>::connect_to_seed()
   {
-      if (m_seed_nodes.empty() || m_offline)
+      if (m_seed_nodes.empty() || m_offline || !m_exclusive_peers.empty())
         return true;
 
       size_t try_count = 0;
```

**Comment by leonklingele** [comment]
> Try --seed-node SAMEIP:SAMEPORT

Didn't help, even with the patch applied it still does DNS lookups.

**Comment by moneromooo-monero** [comment]
Can you tell what it is trying to resolve ?

**Comment by leonklingele** [comment]
- seeds.moneroseeds.ae.org: type A, class IN
- seeds.moneroseeds.li: type A, class IN
- seeds.moneroseeds.se: type A, class IN
- seeds.moneroseeds.ch: type A, class IN

**Comment by moneromooo-monero** [comment]
Ah, I see it. Fixing...

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3145

**Comment by leonklingele** [comment]
Didn't help :( Just to be sure: I've applied #3143 and #3145 and am passing these args:

```sh
"$MONEROD" \
    --add-exclusive-node 127.0.0.1:18090 --allow-local-ip \
    --p2p-bind-ip 127.0.0.1 \
    --rpc-bind-ip 127.0.0.1 \
    --no-igd \
    --hide-my-port \
    --db-sync-mode safe \
    --check-updates disabled \
    --disable-dns-checkpoints
```

**Comment by leonklingele** [comment]
Seems to be fixed, see https://github.com/monero-project/monero/issues/3146#issuecomment-358286989

**Comment by moneromooo-monero** [comment]
I updated 3145, it was checking exclusive nodes before parsing the command line.

**Comment by moneromooo-monero** [comment]
+resolved
