### ISSUE TITLE
multiple wallets and wallet-rpc 

### ISSUE THREAD

**Issue by crazy-logic** [monero-project/monero#3131]
When calling the wallet-RPC in the --wallet-dir mode, so that multiple wallets can be opened. 

1. Can I have more than one wallet open at a time?
2. Is there a way to ensure that one connection to the server doesn't get information from another wallet and vice versa? 

Basically I would like to have multiple wallets open and be abel to read from each of them, but only have one wallet-rpc running on the host. Is this possible?

**Comment by crazy-logic** [comment]
It does seem a pretty big security flaw to me for the wallet and password not to be passed in each transaction. do you have any idea how online wallets are preforming this functions for their users?

**Comment by moneromooo-monero** [comment]
If you're reporting a security flaw, please be precise. I've no idea what you're trying to say here.

**Comment by crazy-logic** [comment]
The flaw goes something like this. 

script A opens a wallet A using rpc then makes calls. 
script B opens a wallet B using rpc then makes calls. 
script C - which is actually the same end user as scrip A, makes further calls expecting wallet A to be open, but receives data for wallet B. 

The lack of defining which wallet is used on each RPC request along with some authentication means that if a wallet hosting server is compromised/badly coded and it is using the wallet-rpc to access wallet data, then potentially the wrong responses are being sent to the user/script. Which means that the waller-rpc isn't suitable for hosting multiple wallets with concurrent multiple users? I hope that I have missed something here.

**Comment by moneromooo-monero** [comment]
Well, that's a bug in whatever drives those scripts.

**Comment by crazy-logic** [comment]
Well yes - it would be is there any other way I can access multiple wallets concurrently (with security) without having to spin up many instances of the wallet-rpc?

**Comment by moneromooo-monero** [comment]
No. It's not meant to do that.

**Comment by emesik** [comment]
I think the fastest way to have it running would be to maintain a pool of `monero-wallet-rpc` processes in single-wallet mode. Writing a manager that spins up and shuts down instances for requested wallets would be the biggest challenge but far from rocket science. You'd probably like to resync unused wallets in idle time, so they go up faster when needed.

A single instance in wallet-dir mode is useless while resyncing a freshly opened wallet. With multiple instances you may use that time with order another one working on different wallet.

**Comment by moneromooo-monero** [comment]
Why, though ? Is there an actual use for this (beyond guarding against some break in subadresses) ?

**Comment by crazy-logic** [comment]
yeah @emesik that's my thoughts exactly. 

@moneromooo-monero well if you want to host people's wallets for them as a web service, you'ld need to be able to sync wallets and query them concurrently.

**Comment by moneromooo-monero** [comment]
Fair enough. Not meant for that then :)

**Comment by crazy-logic** [comment]
it would appear that way - so far i cannot find anything that is suitable - which makes me wonder how others are actually doing it.

**Comment by moneromooo-monero** [comment]
I see three different ways:

- use integrated addresses, so it's a single account, and you have a DB keeping track of everyone's balance
- mymonero has custom scanning code, which only scans a view key when the user logs in
- things like freewallet just scam the user

**Comment by hyc** [comment]
monero-wallet-rpc isn't meant for multiuser services. It's meant for a single user. The create_wallet/open_wallet functionality only exists to round out the feature set and facilitate GUI wrappers like the old java wallet from jwinterm. I.e. it's only purpose is to allow someone to do everything monero-wallet-cli does, from a separate process.

**Comment by moneromooo-monero** [comment]
No monero bug here.

+invalid
