### ISSUE TITLE
The 'do_not_relay' flag in /sendrawtransaction daemon RPC method is both undocumented AND defaults to 'true'

### ISSUE THREAD

**Issue by emesik** [monero-project/monero#3132]
This looks weird. When submitting a raw transaction to the daemon, it stays in mempool and isn't relayed further by default. What's worse, the behavior and the flag [aren't documented](https://getmonero.org/resources/developer-guides/daemon-rpc.html#sendrawtransaction).

For starters, I [updated the docs](https://github.com/monero-project/monero-site/pull/556) but I'm still wondering:

1. Why the default value is `true`?
2. What is the purpose of not relaying transactions at all? Do we need it?

**Comment by moneromooo-monero** [comment]
There is no default value. If you don't give it, it's uninitialized. We can give default values since fairly recently though, I'll do that. Not relaying txes is needed if you want to mine the tx.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3136 should fix it.

**Comment by moneromooo-monero** [comment]
+resolved
