### ISSUE TITLE
[Wallet API] Plan for upgrading restoreFromKeys

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero#3149]
As per https://github.com/monero-project/monero/pull/3104#issuecomment-357505047:

1. **(done, #3104)** Introduce a new function `restoreFromKeysWithPassword`, and mark `restoreFromKeys` as deprecated.

2. After one release cycle, remove `restoreFromKeys`. All API users should be using `restoreFromKeysWithPassword` at this point.

3. After another release cycle, bring back `restoreFromKeys` again which is just an alias to `restoreFromKeysWithPassword`, and mark `restoreFromKeysWithPassword` as deprecated.

4. After another release cycle, remove `restoreFromKeysWithPassword`. All API users should be using `restoreFromKeys` with the upgraded functionality at this point.

**Comment by moneromooo-monero** [comment]
That sounds like a lot of trouble. I'd rather we don't treat this as a stable API since it's obviously far from stable yet, but then if someone wants to do the work I won't stop them.

**Comment by stoffu** [comment]
@moneromooo-monero 
I also had a similar opinion (https://github.com/monero-project/monero/pull/3104#issuecomment-357429844):

> Now I'm wondering - is it really necessary to keep the deprecated version for backward compatibility? AFAIK only software products that use the wallet API are Monerujo and monero-wallet-gui. Can't we just introduce the new function signatures and force the users (Monerujo & monero-wallet-gui) to upgrade their code?

but it wasn't supported. CC @dEBRUYNE-1 @m2049r

**Comment by m2049r** [comment]
let's pretend it's stable and see how it goes :)

**Comment by moneromooo-monero** [comment]
So this was abandoned.

+invalid

**Comment by m2049r** [comment]
? so you are keeping the totally unsecure ```restoreFromKeys```? it should have the functionality of ```restoreFromKeysWithPassword```. and so ```restoreFromKeysWithPassword``` has no purpose any longer.
