### ISSUE TITLE
working on chinese translation of moner daemon

### ISSUE THREAD

**Issue by hqwrong** [monero-project/monero#3150]
Hi,

I'm working on the chinese translation of monero daemon now. It will likely take several days. I'm wondering is there a place I can place a mark in case that someone else tries to do the same thing which of course will cause a waste of time.

I'm not sure this is the right place to ask, but I've seen the Taiga and seems that a guest like me doesn't have a right to post a issue.

**Comment by ordtrogen** [comment]
@erciccione will help you get access to Taiga ...   :-)

**Comment by moneromooo-monero** [comment]
Do you mean the daemon or the wallet ?
The wallet has translation support, but we don't really want the daemon to be translated, as this would pull all logs.

**Comment by erciccione** [comment]
Hi @hqwrong , thank you for contributing. You are right you cannot open an issue or task as a guest, but if you send a message to the project with your email or email me directly to erciccione (at) protonmail.com, i can add you and you can start managing your own tasks/issues.

Thanks fort the ping @ordtrogen :)

**Comment by hqwrong** [comment]
@moneromooo-monero Hi, I'm talking about adding a chinese translation file like tranlations/monero_zh-cn.ts to monero project.  I saw there have been monero_fr.ts and monero_it.ts, guess a chinese version is alse needed.    Did I get it wrong?

**Comment by hqwrong** [comment]
@erciccione I've sent a message to project in Taiga :)

And thanks for your help :) @ordtrogen

**Comment by erciccione** [comment]
Just received, but doesn't include your email. Can you send another message specifying it or i cannot add you

**Comment by moneromooo-monero** [comment]
> I'm talking about adding a chinese translation file like tranlations/monero_zh-cn.ts to monero project.

That's correct, and that's for the wallet (monero-wallet-cli), not the daemon. Thank you.

**Comment by hqwrong** [comment]
I've already been added to the Taiga project. Thank you guys.
