### ISSUE TITLE
Which password limitations do exist?

### ISSUE THREAD

**Issue by DavidBruchmann** [monero-project/monero#3152]
I refer with my question primary to length, based on bytes because a sign in UTF-8 can have 1-4 bytes.
Furthermore some special signs like control-signs might not be allowed.
This question is related to bulk-creation of wallets, so it's not about my personal desire or needs but only about technical limitations.
Please, if you've any information about limited field-lengths in databases of exchange- or trading-platforms, that's welcome too as it's indirectly related to my question.
Also password limitations of any monero-related software are welcome.

**Comment by moneromooo-monero** [comment]
This is a bug tracker, this kind of question is a good fit for monero.stackexchange.com.
I can't think of a restriction beyond OS input restriction though.

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by DavidBruchmann** [comment]
https://monero.stackexchange.com/questions/7351/which-password-limitations-do-exist
