### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#3166]
> For this to be worthwhile, the machine should have one core and about 2GB of RAM available per thread

Correct is "... should have more than one core ..."

**Comment by hyc** [comment]
The previous sentence says "if your machine has several cores" so it's already established that you have one core. This sentence is correct - you must have [one core and 2GB of ram] per thread.

**Comment by iamsmooth** [comment]
Ah, it makes sense read that way although not necessarily accurate either.
Hyperthreading often shows gains on compiles, which wouldn't require a full
hardware core per thread.

**Comment by moneromooo-monero** [comment]
So... "your machine should have one thread per thread" ? :)

**Comment by hyc** [comment]
When RAM is not a constraint, compiles tend to be I/O bound for reading source/headers and writing tmp files. In that case, hyperthreading can yield a gain on compile times. On a machine with plenty of RAM I usually run "make -jX" where X is 50% more than available CPU cores, to minimize CPU idle time. On a machine where RAM is tight, there's no advantage.

**Comment by iamsmooth** [comment]
> On a machine with plenty of RAM and effective OS caching I usually run "make -jX" where X is 50% more than available CPU cores

Which is not what the README suggests. Not a big deal though, people can figure out it and Monero compiles tend not to take an inordinately long time on decent hardware at this point anyway.

**Comment by iamsmooth** [comment]
I'm closing this as the original issue of a typo was mistaken. If someone wants to _improve_ the compile instructions in the readme they don't need this issue to do so.
