### ISSUE TITLE
Help on compiling for Win64

### ISSUE THREAD

**Issue by onemoreitguy** [monero-project/monero#3167]
Hello guys,
I've followed the instructions to build on a Windows 7 (and also 10) but I get compile errors over and over.
first: I got the openssl
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY  OPENSSL_INCLUDE_DIR)
I manage to overcome by installing OpenSSL and setting manually the variable location paths on CMakeCache.txt
But the errors of libraries not found keep going over and over as more as I 

I assume that I'm doing something wrong from the beginning. Any can provide some clues?

**Comment by moneromooo-monero** [comment]
Install the others too ?

**Comment by onemoreitguy** [comment]
ANSWER: just install everything on the defaults (root of the C: drive) ;)

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/monero/pull/3155

**Comment by onemoreitguy** [comment]
I was about to write that.
I guess I didn't dig enough on the info.

Thanks and continue the good work ;)

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by vans163** [comment]
This issue is present if you compile from /d/ or if msys is on /d/ drive or a combo of both.
