### ISSUE TITLE
monerod: Couldn't connect to daemon

### ISSUE THREAD

**Issue by Phoettinave** [monero-project/monero#3176]
When trying to run `monerod status` when a monero daemon is already running (started with `--detach`), I keep getting the following error message (reproducible across all my servers with v0.11.1.0 and latest master (5f09d6c8333b0b0d07252dc157b9e794f6278662)):

```sh
$ monerod status
Error: Couldn't connect to daemon: 127.0.0.1:18081
Height: 1493720/1493720 (100.0%) (...)
```

It gets more interesting with the `print_cn` command:

```sh
$ monerod print_cn
2018-01-23 22:17:25.908	    7fb166619bc0	ERROR	net.http	contrib/epee/include/storages/http_abstract_invoke.h:118	RPC call of "" returned error: -32601, message: Method not found
Error: Couldn't connect to daemon: 127.0.0.1:18081
```

**Comment by Phoettinave** [comment]
This is how I start monerod:

```
ExecStart=/root/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --restricted-rpc --p2p-bind-ip 0.0.0.0 --fluffy-blocks --detach
```

**Comment by moneromooo-monero** [comment]
Remove --restricted-rpc if you want to access restricted RPC.

+invalid

**Comment by Phoettinave** [comment]
@moneromooo-monero @fluffypony @dEBRUYNE-1 please open again, its not fixed! "Error: Couldn't connect to daemon" shouldnt appear.
