### ISSUE TITLE
Monero wallet rescan blockchain

### ISSUE THREAD

**Issue by Revinand** [monero-project/monero#3177]
How often `rescan_blockchain` method should be called? Suppose I process payments in a cronjob, which runs every 10 minutes. Do I need to rescan blockchain each call?

**Comment by Revinand** [comment]
Hm, just noticed: wallet receives new transactions and blocks automatically, which means `rescan_blockchain` should be called only in case when wallet was offline for a long period, am I right? IIRC wallet didn't update automatically before

**Comment by stoffu** [comment]
As evident in the code (https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L3944), `rescan_bc` has the same effect as deleting your wallet cache file (the file without any file extension like .keys or .address.txt) and opening the .keys file again to recreate the cache file from scratch. The wallet cache file stores some private data that exist only locally (i.e. not on the blockchain), such as the tx secret keys, the recipient addresses, the address book, etc. Usually you don't want/need to use `rescan_bc`; I guess it exists mainly for debugging/testing purposes.

**Comment by hyc** [comment]
+invalid

The issue tracker is for actual bug reports, not for questions and answers.

**Comment by Revinand** [comment]
@hyc sorry for that.
@stoffu thanks for the clarification
