### ISSUE TITLE
Possible Mempool spam attack

### ISSUE THREAD

**Issue by cmaves** [monero-project/monero#3189]
Currently if somebody makes a simple modification to the monero-wallet, they can generate a transaction that is about 360kb in size. If this transaction is low priority, the transaction will be relayed as valid but will not be confirmed unless the median blocksize grows. One could use this to flood the mempool with transactions.

After doing a bit of math it appears that a normal priority transaction of this size would be confirmed, so the nodes just fail to account for the case where a transaction is both large and low priority.

**Comment by moneromooo-monero** [comment]
There's been some talk about limiting txes to a percentage of the block size for this reason. Not done, though. I also wanted to start dumping the lowest fee/byte txes from the txpool as new txes are received.
The first one would be consensus, the second one not.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3205
