### ISSUE TITLE
Add sweep_all_mixable command

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero#3202]
Currently the sweep_all button will try to include unmixable outputs as well. It'll subsequently fail because those unmixable outputs don't have sufficient ring partners. Now, typically one can make unmixable outputs mixable with the `sweep_unmixable` command. However, in some cases these unmixable outputs can't pay for themselves (per moneromooo, note that some tiny mixable outputs may also not be able to pay for themselves), which then creates a potential problem for the `sweep_all` command. Therefore, it might be beneficial if we had a `sweep_all_mixable` command too that only sweeps mixable outputs.

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by jcktm** [comment]
Gave this an attempt at pull request https://github.com/monero-project/monero/pull/3680

**Comment by stoffu** [comment]
Isn't it strange in the first place that `sweep_all` tries to send both mixable and unmixable outputs, when the tx is required to have a minimum ring size (so trying to send unmixable outputs will always fail)?

**Comment by selsta** [comment]
Should be resolved with #3991
