### ISSUE TITLE
ReadME updating

### ISSUE THREAD

**Issue by Duiesel** [monero-project/monero#3203]
Hello guys.
Readme has no information about minimal requirements for building monero from source. I can't build monero on the system which has 2 GB of RAM and 2 GB of swap. Only 10 GB swap helps in this case. At the same time there's no information about libpgm-dev. The target can't be built without it.

Thanks.

**Comment by moneromooo-monero** [comment]
I can build with ~3 GB of RAM and way less 10 GB of swap, so this is something on your system.
The libpgm mention is done.

+resolved
