### ISSUE TITLE
Help me to call wallet rpc from other ip

### ISSUE THREAD

**Issue by top1st** [monero-project/monero#3212]
![image](https://user-images.githubusercontent.com/23559697/35576380-c8b445fc-0619-11e8-8514-9e3c8ebede30.png)

I installed command line tool on ubuntu 16.04
I cannot see wallet rpc port listine on 18082
Domain Rpc works but wallet RPC not listening 
I refered this documents
https://getmonero.org/resources/developer-guides/wallet-rpc.html
https://getmonero.org/resources/developer-guides/wallet-rpc.html#getbalance

**Comment by moneromooo-monero** [comment]
And this is a bug tracker, not a help forum. I'll leave that open since someone's trying to help, but please don't again, there's IRC or reddit for this.

**Comment by top1st** [comment]
above image is when i run  $ ./monerod 

and next is when is tried --rpc-bind-ip and --confirm-external-bind
![image](https://user-images.githubusercontent.com/23559697/35599045-d9fd6922-0661-11e8-8b3b-efb24fa5024a.png)

![image](https://user-images.githubusercontent.com/23559697/35599084-037ff9fe-0662-11e8-8d2d-fff3c3e7ac6b.png)

**Comment by leonklingele** [comment]
I've misread your post, sorry. You're trying to start the `wallet` RPC, but `monerod` is not your wallet :) 

There's a dedicated binary called `monero-wallet-rpc` inside the same folder which you can start with the following args: `--rpc-bind-port 18082 --prompt-for-password --wallet-file PATH/TO/WALLET_KEY`.
__Do not__ use `--rpc-bind-ip` unless you know what you're doing. Make sure to have a daemon running.

**Comment by moneromooo-monero** [comment]
+invalid
