### ISSUE TITLE
Proposal - add optional #of outputs to sweep commands

### ISSUE THREAD

**Issue by hyc** [monero-project/monero#3213]
E.g.
> sweep_all [index=&lt;N1>[,&lt;N2>,...]] [&lt;priority>] [&lt;ring_size>] [&lt;outputs>] &lt;address> [&lt;payment_id>]

Cause the result to be divided into &lt;outputs> equal amounts for the generated outputs.
With &lt;outputs> defaulting to 1.

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by Mansarde** [comment]
@hyc 
Just curious, would <outputs> at 1 then still create a zero-change output?

**Comment by hyc** [comment]
@Mansarde probably. My point is just to provide a way to have multiple coins in the result, so you're not stuck locking your entire balance the next time you want to spend some amount.

Was also thinking we could automatically break amounts into denominations, like 1/5/10/50/100/500/1000 but that's probably more trouble than it's worth.

Alternatively we could change the default from (1 + zero-change) to 2 equal outputs.

**Comment by moneromooo-monero** [comment]
+resolved
