### ISSUE TITLE
Segmentation fault when pressing Ctrl-C in prompt for password

### ISSUE THREAD

**Issue by heptathlon** [monero-project/monero#3218]
1.) Start monero-wallet-cli and unlock wallet with your password
2.) Run 'password' command (will ask for your password again)
3.) __Do not enter your password__. Press Ctrl-C instead

Output is:

Wallet password:
Error: invalid password
Error: Your original password was incorrect.
Segmentation fault: 11

**Comment by moneromooo-monero** [comment]
Does https://github.com/monero-project/monero/pull/3222 fix it ? I could not repro the segfault here.

**Comment by vtnerd** [comment]
https://paste.debian.net/1008610/

One of the stack traces is too large, and the other is for something else.

**Comment by moneromooo-monero** [comment]
Should be fixed by https://github.com/monero-project/monero/pull/3249, can you confirm ?

**Comment by heptathlon** [comment]
@moneromooo-monero thanks, fixed.
