### ISSUE TITLE
request: add function monero-wallet-rpc::close_wallet() [+1]

### ISSUE THREAD

**Issue by DavidBruchmann** [monero-project/monero#3227]
The function close_wallet() would be appreciated as it enables the possibility still to work with the rpc-daemon without risking to manipulate any wallet without intention or getting wrong results.
Furthermore the function open_wallet() shouldn't work as long as there is still one wallet open IMHO, but that's a minor issue.

The function stop_wallet() is shutting the rpc-daemon completely down, that's not desired always, so close_wallet() still would add a small functional layer.

EDIT:
IMHO it's quite uncommon that authentication is done by an RPC-daemon.
Surely it has to offer a method but it seems the wallet-RPC-daemon was just concepted for a single wallet, daemons usually offer to serve several accounts and just offer the methods to connect to those. Also connection to the daemon could be done by several clients where surely not everyone is working with the same wallet. While adding the desired function closeWallet() it's also desired that the requirement to open directly a wallet is removed, like this the daemon can just do what daemons usually do: waiting for commands and serving on request.

**Comment by nsbk** [comment]
+1

**Comment by moneromooo-monero** [comment]
+resolved
