### ISSUE TITLE
transfer by wallet-rpc only working randomly rarely

### ISSUE THREAD

**Issue by DavidBruchmann** [monero-project/monero#3233]
Having commands like this in a loop
```
curl -u "monero":"monero" --digest -s -S -X POST http://127.0.0.1:28083/json_rpc -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"wallet-dir\":\"/home/monero-wallets/\",\"method\":\"transfer\",\"params\":{\"destinations\":[{\"amount\":\"01000000000000\",\"address\":\"9sMgrW7guKiYKpttTGwQeDc5re8dkNFUQQDDqHbQrTd64WXZNakGzzjAyMEqZjAyfiMYvqueKR8qsLE4bdMm6gYFKEuFbFJ\"}],\"get_tx_key\":"true"}}" -H 'Content-Type: application/json'
```
I got 2 or 3 transfers and could control it in the wallets, but this is failing in more than 90% of cases.
I get mostly the response:
```
ERROR: -4: transaction was rejected by daemon
```
Is there any reason for that response and anything I can do about it?

**Comment by DavidBruchmann** [comment]
Now I remarked that waiting some minutes between the commands I can send when entering the commands directly on commandline:
```
curl -u "monero":"monero" --digest -s -S -X POST http://127.0.0.1:28083/json_rpc -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"wallet-dir\":\"/home/monero-wallets/\",\"method\":\"transfer\",\"params\":{\"destinations\":[{\"amount\":\"01000000000000\",\"address\":\"9sMgrW7guKiYKpttTGwQeDc5re8dkNFUQQDDqHbQrTd64WXZNakGzzjAyMEqZjAyfiMYvqueKR8qsLE4bdMm6gYFKEuFbFJ\"}],\"get_tx_key\":true}}" -H 'Content-Type: application/json'
{
  "error": {
    "code": -4,
    "message": "not enough unlocked money"
  },
  "id": "0",
  "jsonrpc": "2.0"
}
```
Waiting some time ...

```
> curl -u "monero":"monero" --digest -s -S -X POST http://127.0.0.1:28083/json_rpc -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"wallet-dir\":\"/home/monero-wallets/\",\"method\":\"tansfer\",\"params\":{\"destinations\":[{\"amount\":\"01000000000000\",\"address\":\"9sMgrW7guKiYKpttTGwQeDc5re8dkNFUQQDDqHbQrTd64WXZNakGzzjAyMEqZjAyfiMYvqueKR8qsLE4bdMm6gYFKEuFbFJ\"}],\"get_tx_key\":true}}" -H 'Content-Type: application/json'
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "fee": 3816720000,
    "multisig_txset": "",
    "tx_blob": "",
    "tx_hash": "666cfd75a0aeac2d18a0cdbfd2f551a70c3eba724713db5535d30eae0fac1ead",
    "tx_key": "b7ef7c54c894f669da7d3ec8194ee8edde1a497d322bcef9fbd1b58ea23d6a0d",
    "tx_metadata": ""
  }
}
```
Also the reason for rejecting is on commandline different, it's "not enough unlocked money".
Question is why monero-wallet-rpc reacts so unreliable and cranky and how to deal with it?

**Comment by moneromooo-monero** [comment]
Change is locked for 10 blocks.

You hint there are two different cases where it fails, is that right ? If so, please describe how they differ. In one of those you say you get "not enough unlocked money", and you imply in the other you don't.

**Comment by DavidBruchmann** [comment]
In the first case (very top, first post) the command is send by a script, and the answer I got was `transaction was rejected by daemon`.
As I echoed the curl-command too I just copied that and used it in the second post directly onn commandline. Both commands there are the same, just for the second one I waited some time and the answer differs then as the last one is executed without error.

**Comment by DavidBruchmann** [comment]
Mhm, so the lock is at least directly independent from time, but related to blocks.
Any way to circumvent or shorten that somehow?
Or is it possible to use further blocks?

**Comment by moneromooo-monero** [comment]
It's not about blocks, but outputs. It'll be blocks if you have just one or two outputs. Split your outputs if you want to send repeatedly. That is, run "set merge-destinations 0" in monero-wallet-cli, then send yourself 10% of your balance 10 times in the same tx. Then set min-output-count 100 and set min-output-value 1 in monero-wallet-cli to avoid re-coalescing.

**Comment by DavidBruchmann** [comment]
Ok, thank's will try to completely understand and realize it.

**Comment by moneromooo-monero** [comment]
For a fiat analogy:

Alice and Bob both have $100, and they want to pay $10 to both Charlie and Donna.

Alice has 10 $10 bills. She gives one to Charlie, and one to Donna.

Bob has a single $100 bill. He gives it to Charlie, and waits while Charlie looks for change. Bob has nothing left during that time. Later on, once he got change back, he pays Donna.

**Comment by DavidBruchmann** [comment]
What could be a reason that a command is declined by the wallet-rpc but accepted by wallet-cli?  
I entered this one several times this day by wallet-rpc and got always the message:  
ERROR: -4: transaction was rejected by daemon  
now I entered it directly a few seconds afterwards and get a confirmation with tx-details.

This is the command:
```
curl -u "monero":"monero" --digest -s -S -X POST http://127.0.0.1:28083/json_rpc -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"wallet-dir\":\"/home/monero-wallets/\",\"method\":\"transfer\",\"params\":{\"destinations\":[{\"amount\":\"00900000000000\",\"address\":\"9sJBGmoSHET4VFvxAD7T1ZV7fohZdXukcbM1s8nUfJ6G7Frr1VEoNnFbY88WAkc7eQ6SeWLRSqLgN4vf6A3CnRx8AyQ1V5D\"},{\"amount\":\"01000000000000\",\"address\":\"9sMgrW7guKiYKpttTGwQeDc5re8dkNFUQQDDqHbQrTd64WXZNakGzzjAyMEqZjAyfiMYvqueKR8qsLE4bdMm6gYFKEuFbFJ\"}],\"get_tx_key\":true}}" -H 'Content-Type: application/json'
```

**Comment by moneromooo-monero** [comment]
set_log 1 in the daemon will tell you why your tx is rejected.

**Comment by DavidBruchmann** [comment]
I got it working, "transaction was rejected by daemon" is raised if blocks are not yet confirmed and "not enough unlocked money" is raised if the own part of the balance is not yet written back to the own wallet. Background is that the remaining amount in the wallet is send to the own wallet as transfer too.
