### ISSUE TITLE
Pub/sub notifications for new blocks

### ISSUE THREAD

**Issue by oliverw** [monero-project/monero#3236]
It would be quite handy for mining pools to be able to receive push notifications about new network blocks  instead of having to resort to aggressive polling intervals. Most Bitcoin derived coins already have that feature via the <code>zmqpubhashblock</code> daemon parameter and Parity implemented something similar for Ethereum based currencies using Websocket push.

**Comment by moneromooo-monero** [comment]
Filed near the start of the issues list.

+duplicate

**Comment by oliverw** [comment]
@moneromooo-monero Sorry didn't spot it.
