### ISSUE TITLE
Installing Monero via Snap - Unknown Connections

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [monero-project/monero#3237]
Hey, I installed Monero via the snap package and when I check out connections via netstat I see a bunch of a connections that the client makes even when it's not running... one of them is to:

echomike.de:18080 for instance

Is the Snap package mining on my server? Why is it running even before I run it?

**Comment by moneromooo-monero** [comment]
Monero makes connections when it's not running ? I'm sure you don't mean this. Please explain.

**Comment by lh1008** [comment]
I have not been able to run monero from a snap package. I´m using ubuntu 16.04.3 LTS. I´m able to see the monero snap package in terminal but can´t find the repository or which command to open monero. Sorry if this is not the correct post, but saw the title and thought someone could help.

**Comment by juliavi** [comment]
running 
`sudo snap start monero`
Doesn't start syncing, and doesn't allow to add the --testnet flag.
What would be the right way to run a testnet node from the snap?

**Comment by TimeTravelersHackedMe** [comment]
The Snap package is named monero.monero-wallet-cli (and
monero.monero-wallet-rpc)

- Brian

**Comment by juliavi** [comment]
So snap doesn't support the latest build of monerod?
monerod replaced the former wallet-cli

**Comment by moneromooo-monero** [comment]
I'm confused by the above.
The connection in the first post looks like a normal P2P connection at first glance. I'll assume that monerod is running and it's the user being confused. If monerod wasn't running, then it's something else that's connecting there, and thus not our problem in the first place :P

+invalid
