### ISSUE TITLE
[Fork Attack Mitigation] add sweep_all_fork that accepts two destination addresses

### ISSUE THREAD

**Issue by nasaWelder** [monero-project/monero#3265]
The following idea assumes that the same ring members would be able to be used for both transactions, and that the fork cli would accept the signed tx as is. If not, I'll delete this issue.  

    sweep_all_fork <fee> <ringsize> moneroaddress forkaddress

The monero cli would submit the monero tx instantly, and save the fork transaction to file as signed_monerofork_tx.
The user could then use fork CLI to submit_transfer (after renaming it to whatever it needs to be).

Heavy use of explicit confirmation dialogs is suggested.

This is a "give them clean needles" approach.

**Comment by nasaWelder** [comment]
I figure "we" wouldn't need to rely on attackers forking this feature because monero cli would be making the transaction for submission to fork network. I guess they could find a way to prevent that. I yeild, and I'll close.

**Comment by moneromooo-monero** [comment]
If they actively try to prevent this, our fallback method is: spend in the fork, use set_ring in monero's monero-wallet-cli to record the ring that got used, spend in monero.

**Comment by moneromooo-monero** [comment]
I kinda like this approach though because it also uses the same inputs for both txes. It would need knowing their address format, and is ultimately not scalable, so both pros and cons.
