### ISSUE TITLE
Broken file: translations/monero.ts  from simplewallet.cpp

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero#3279]
(I'm pasting a screen pic as I don't know how angle brackets and whatnot are handled in this edit field)

On rows 530 and 964, "<payment_id>" should be "&amp;lt;payment_id&amp;gt;", otherwise it breaks the XML. I have looked at the corresponding place in ../src/simplewallet/simplewallet.cpp and how this may have happened. 

![image](https://user-images.githubusercontent.com/15184875/36329235-8ee68e44-1365-11e8-8af7-987e75a50d0f.png)

**Comment by iDunk5400** [comment]
#3275

**Comment by ordtrogen** [comment]
Thanks, @iDunk5400 
I only checked if any issue had been reported and forgot to look for any PR in progress.

**Comment by moneromooo-monero** [comment]
+resolved
