### ISSUE TITLE
warning that deamon should be updated for scheduled hard fork

### ISSUE THREAD

**Issue by amicrod** [monero-project/monero#3280]
I didn't find any documentation on this... are these warnings serious?

![forks](https://user-images.githubusercontent.com/32557232/36335617-38f0b7fa-134f-11e8-9bb3-6fe30b448c7c.png)

**Comment by moneromooo-monero** [comment]
The hard fork will happen in march, the exact block height is not decided yet. We're just a bit late on the release, but your daemon does not know so tells you it's time. Just keep an eye on monero news and update when the release is made.

**Comment by moneromooo-monero** [comment]
Related: there will be a 0.12.1.0 soon too. This will be detected by monerod shortly after available.

+invalid
