### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [monero-project/monero#3282]
Hello, I would like to collaborate with the Spanish translation, is it done?

**Comment by erciccione** [comment]
Hi, sure, somebody already offered to help with the spanish localization, but i haven't heard from him yet. see #3262

**Comment by dbucci24** [comment]
Then can i do translations or i need autorizathion?

**Comment by erciccione** [comment]
You don't need any authorization, you can start working on it, was just to avoid double works.  Please use the updated .ts file at #3275

**Comment by dbucci24** [comment]
@erciccione How can I know which files need translation into Spanish and which ones are already made?

**Comment by erciccione** [comment]
There is no spanish localization at the moment. You only need to make a copy of the `monero-core.ts` file (taken from #3275 ) rename it `monero-core_es.ts` and start translating. You can find more instructions [on Taiga](https://taiga.getmonero.org/project/erciccione-monero-localization/wiki/instructions-for-daemon)

**Comment by dbucci24** [comment]
sounds great. I will do it, thank you very much

**Comment by erciccione** [comment]
Thank you. Contact me if you need help

**Comment by moneromooo-monero** [comment]
To be clear: this is about monero-wallet-cli. GUI translations would be dealt with in https://github.com/monero-project/monero-core

**Comment by erciccione** [comment]
o yes sorry, i mixed the two repo. The file you need to make a copy and edit for the CLI wallet is `monero.ts` in https://github.com/monero-project/monero/tree/master/translations

**Comment by moneromooo-monero** [comment]
Please just make PRs whenever you have something ready.

+invalid

**Comment by lh1008** [comment]
@dbucci24  are you around?

**Comment by lh1008** [comment]
Let me share you the #monero-es communication channels so you could join us and help us coordinate things you would like to do, or help us out through the #monero-es community is work, you decide: [mattermost #monero-es chat channel](https://mattermost.getmonero.org/monero/channels/monero-es), telegram [@MoneroEsp](https://t.me/MoneroEsp) or IRC [Freenode](https://webchat.freenode.net/) #monero-es channel. BTW, the telegram chat is where you can find the most Monero Spanish community members gathering around, so you could add yourself to the chat room. There is a lot to be done through the #monero-es  community, we would like you to join us so we can coordinate the translations if you would like, or if you have different plans, just meet the community so you could get support if you need any. :) 

*We are doing some Spanish reviews, and the monero site needs more translations.

**Comment by lh1008** [comment]
@dbucci24 if you need any help just message me in those channels. We could help us around to get different things done. :) 

*I'm also on reddit with the same username if you hang over there also.
