### ISSUE TITLE
Testnet not syncing (searching on port 18080, not 28080)

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero#3283]
Built from source @ commit 4f80c50

./monerod --testnet

https://paste.fedoraproject.org/paste/saEwKma8NWdOyWlDM5l4cA

**Comment by moneromooo-monero** [comment]
Is it fixed by https://github.com/monero-project/monero/pull/3196 ?

**Comment by xmr-eric** [comment]
3196 did not fix it.

**Comment by moneromooo-monero** [comment]
Does reverting https://github.com/monero-project/monero/pull/3170 fix it ?

**Comment by mrwhythat** [comment]
That's on me. I'm really sorry but it seems like I accidentally removed an assignment to `m_testnet` at line 265 in `p2p/net_node.inl` during rebase. I will PR the fix in a few minutes.

**Comment by xmr-eric** [comment]
Fixed with #3290. I'm closing this.
