### ISSUE TITLE
Windows build broken by #3170

### ISSUE THREAD

**Issue by iDunk5400** [monero-project/monero#3296]
Since #3170 was merged, building in MSYS2 fails like this:
[https://build.getmonero.org/builders/monero-static-win64/builds/3757/steps/compile/logs/stdio](https://build.getmonero.org/builders/monero-static-win64/builds/3757/steps/compile/logs/stdio)

I managed to make it build by substituting `command_line::has_arg` with `!command_line::is_not_defaulted` [here](https://github.com/monero-project/monero/blob/master/src/daemonizer/windows_daemonizer.inl#L114), but I think it's better the author fix any code or template issues properly. (@mrwhythat)

**Comment by stoffu** [comment]
#3318

**Comment by iDunk5400** [comment]
#3318 does fix the build failure. Thanks.

**Comment by moneromooo-monero** [comment]
+resolved

**Comment by mrwhythat** [comment]
@stoffy, thanks for fixing this for me. Sorry I couldn't respond in time, as I don't have any Windows machines at hand.
