### ISSUE TITLE
Free disk space displayed incorrectly

### ISSUE THREAD

**Issue by brad-richards** [monero-project/monero#3306]
When there is too little disk space to expand the blockchain db, monerod executes the code (monero/src/blockchain_db/lmdb/db_lmdb.cpp line 454)
```
boost::filesystem::space_info si = boost::filesystem::space(path);
    if(si.available < add_size)
    {
      MERROR("!! WARNING: Insufficient free space to extend database !!: " << si.available / 1LL << 20L);
      return;
    }
```
The calculation in the error message is incorrect: it divides the available disk space by 1, then multiplies it by 2^20, giving an unreasonably large number. If the goal is to display it in MB, then something like `si.available >> 20` would be better. The message should then also display the unit (i.e. "MB").

**Comment by moneromooo-monero** [comment]
Thanks, https://github.com/monero-project/monero/pull/3307

**Comment by moneromooo-monero** [comment]
+resolved
