### ISSUE TITLE
monero.ts : Various typos

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero#3310]
A couple typos. I'll try to create a PR myself for it

"RFC" instead of "RPC":
![image](https://user-images.githubusercontent.com/15184875/36627789-80a80b44-1948-11e8-98df-fd927392896b.png)

Simplewallet.cpp, line 1680
too -> to
![image](https://user-images.githubusercontent.com/15184875/37132142-857de678-228c-11e8-8c7e-1582a916c456.png)

**Comment by moneromooo-monero** [comment]
+resolved
