### ISSUE TITLE
wallet with a respend shows spent 18.4 million monero

### ISSUE THREAD

**Issue by williams-r** [monero-project/monero#3341]
GUI wallet with a respend (both transactions were to the same wallet as sent it) shows spent 18.4 million monero when restoring from a specific block height.
spendable amount is normal.
the same mnemonic restored from genesis block in a new wallet file shows unconfirmed extra balance from the respend, but no 18.4 million spent coins.

**Comment by moneromooo-monero** [comment]
Was it restored from a block after it started being used ? If so, that's why, it's missing data.

**Comment by williams-r** [comment]
yes. thanks.

**Comment by williams-r** [comment]
i close this now?
