### ISSUE TITLE
WARNING,net:FATAL,net.p2p:FATAL ...

### ISSUE THREAD

**Issue by wmoreno3** [monero-project/monero#3342]
I have this information on `monerod.log`

`INFO    logging contrib/epee/src/mlog.cpp:148   New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO,logging:INFO,msgwriter:INFO`

How I can fix it?

**Comment by moneromooo-monero** [comment]
set_log SETTINGYOUPREFER

**Comment by wmoreno3** [comment]
Thanks you

**Comment by fluffypony** [comment]
@wmoreno3 just butting in to say you have the most appropriate surname;)
