### ISSUE TITLE
Monero Wallet RPC

### ISSUE THREAD

**Issue by jinglics** [monero-project/monero#3352]
The latest version monero-wallet-rpc doesn't support argument --prompt-for-password?
Is there anyway in which I can protect the password?
Thanks

**Comment by moneromooo-monero** [comment]
Please give details of what you've tried, and what/how did not work, and any errors.

**Comment by jinglics** [comment]
monero-wallet-rpc --config-file /root/.bitmonero/bitmonero_wallet.conf --prompt-for-password
Error: Failed to parse arguments: unrecognised option 'prompt-for-password'

**Comment by moneromooo-monero** [comment]
Are you sure you're using a recent version ? It's in the --help here, and works when used. Recent version possibly means more recent than the current binaries.

**Comment by jinglics** [comment]
I used this version: v0.11.1.0

**Comment by moneromooo-monero** [comment]
OK, then you just need to use a newer version. If you want to use binaries, there will be new ones within the next two weeks

+invalid
