### ISSUE TITLE
monero-wallet-cli seems to append ".keys" to wallet input, and fails to find the wallet

### ISSUE THREAD

**Issue by grubles** [monero-project/monero#3363]
v0.11.1.0-master-c7ace5fa

Example:
```
Error: failed to load wallet: file not found "yourwallet.keys-watchonly.keys"
```
When the wallet is actually named `yourwallet.keys-watchonly`

**Comment by grubles** [comment]
Actually, the issue is that `monero-wallet-cli` saves watch-only wallets in that naming format, but apparently does not recognize it if specified with `--wallet-file`

**Comment by moneromooo-monero** [comment]
That file is a keys file. You have to rename it to something.keys, which admittedly is a bit naff and will be changed when I get to it.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3369
