### ISSUE TITLE
how to build monero with xcode??

### ISSUE THREAD

**Issue by 15963** [monero-project/monero#3366]
I try with cmake ./ -G "Xcode" . 
The project has been successfully created,but the compilation is wrong.
Help me , thank you !
Error info :

PhaseScriptExecution CMake\ Rules build_for_xcode/src/blockchain_utilities/monero.build/Release/blockchain_import.build/Script-3F7E2C46A49B4964A5A72EB6.sh
    cd /Users/fu/Desktop/work/monero
    /bin/sh -c /Users/fu/Desktop/work/monero/build_for_xcode/src/blockchain_utilities/monero.build/Release/blockchain_import.build/Script-3F7E2C46A49B4964A5A72EB6.sh

cd /Users/fu/Desktop/work/monero/src/blockchain_utilities && touch stub.c && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -o stub.o -c stub.c
cd /Users/fu/Desktop/work/monero/src/blockchain_utilities && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -z noexecstack -z noexecheap -r -sectcreate __DATA __blocks_dat ../blocks/checkpoints.dat -o /Users/fu/Desktop/work/monero/build_for_xcode/src/blockchain_utilities/blocksdat.o stub.o && rm -f stub.*
ld: unknown option: -z
make: *** [/Users/fu/Desktop/work/monero/build_for_xcode/src/blockchain_utilities/blocksdat.o] Error 1
Command /bin/sh failed with exit code 2

**Comment by jtgrassie** [comment]
Firstly, building with the Xcode IDE is not a supported build method. Supported method is outlined in the README.

Secondly, if you must try and get the project into Xcode, I suggest you take a look in the Makefile to ensure you are passing the required options to cmake. Of note, you really need to do an out-of-source build (run cmake from a directory like build/release). But honestly, why bother at all. Just build from the command-line.

**Comment by moneromooo-monero** [comment]
This looks like your linker does not like -z.
It might be necessary to update the option detection system.
Please paste the output of the following commands:

echo "int main(void){return 0;}" | gcc -c -x c -o a.o -
ld -z noexecheap a.o

**Comment by moneromooo-monero** [comment]
No further info, reopen if supplied.

+invalid
