### ISSUE TITLE
Error: failed to generate new wallet: failed to save file "./home/wallet1.keys"

### ISSUE THREAD

**Issue by kevingwang** [monero-project/monero#3394]
So many issues about  "failed to save  file ..." , but no body solve this problem , why ?

root@VM-0-2-ubuntu:/snap/bin# pwd
/snap/bin
root@VM-0-2-ubuntu:/snap/bin# ll -t
total 12
drwxrwxrwx 3 root root 4096 Mar 13 10:25 ./
drwxrwxrwx 2 root root 4096 Mar 13 10:25 home/
lrwxrwxrwx 1 root root   13 Mar 13 09:21 monero.monero-wallet-cli -> /usr/bin/snap*
lrwxrwxrwx 1 root root   13 Mar 13 09:21 monero.monero-wallet-rpc -> /usr/bin/snap*
drwxr-xr-x 5 root root 4096 Mar 13 09:21 ../

root@VM-0-2-ubuntu:/snap/bin# ./monero.monero-wallet-cli --log-level 3 --generate-new-wallet home/wallet1
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /root/snap/monero/3
Enter new wallet password: ******
Confirm Password: ******
List of available languages for your wallet's seed:
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
Enter the number corresponding to the language of your choice: 1
Error: failed to generate new wallet: failed to save file "home/wallet1.keys"
root@VM-0-2-ubuntu:/snap/bin# 
root@VM-0-2-ubuntu:/snap/bin# 
root@VM-0-2-ubuntu:/snap/bin# ./monero.monero-wallet-cli --log-level 3 --generate-new-wallet /home/wallet1
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /root/snap/monero/3
Enter new wallet password: ******
Confirm Password: ******
List of available languages for your wallet's seed:
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
Enter the number corresponding to the language of your choice: 1
Error: failed to generate new wallet: failed to save file "/home/wallet1.keys"
root@VM-0-2-ubuntu:/snap/bin# 
root@VM-0-2-ubuntu:/snap/bin# ./monero.monero-wallet-cli --log-level 3 --generate-new-wallet ./home/wallet1
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /root/snap/monero/3
Enter new wallet password: ******
Confirm Password: ******
List of available languages for your wallet's seed:
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
Enter the number corresponding to the language of your choice: 1
Error: failed to generate new wallet: failed to save file "./home/wallet1.keys"

**Comment by moneromooo-monero** [comment]
You probably don't have a home directory in snap/bin, so path not found. Either give a path to somewhere you have write permissions to, or run the wallet from somewhere you do.

**Comment by kevingwang** [comment]
I have home directory in snap/bin and the permission is 777.

root@VM-0-2-ubuntu:/snap/bin# pwd
/snap/bin
root@VM-0-2-ubuntu:/snap/bin# ll -t
total 12
drwxrwxrwx 3 root root 4096 Mar 13 10:25 ./
drwxrwxrwx 2 root root 4096 Mar 13 10:25 home/
lrwxrwxrwx 1 root root 13 Mar 13 09:21 monero.monero-wallet-cli -> /usr/bin/snap*
lrwxrwxrwx 1 root root 13 Mar 13 09:21 monero.monero-wallet-rpc -> /usr/bin/snap*
drwxr-xr-x 5 root root 4096 Mar 13 09:21 ../

**Comment by kevingwang** [comment]
I try to use 
home/wallet1
or
/home/wallet1
or
./home/wallet1

, it doesn't work.

**Comment by kevingwang** [comment]
Could you please it on Ubuntu ? Thanks!

**Comment by kevingwang** [comment]
Always  failed to save file

root@VM-0-2-ubuntu:/snap/bin# ./monero.monero-wallet-cli --log-level 3 --generate-new-wallet  wallet1
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /root/snap/monero/3
Enter new wallet password: ******
Confirm Password: ******
List of available languages for your wallet's seed:
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
Enter the number corresponding to the language of your choice: 1
Error: failed to generate new wallet: failed to save file "wallet1.keys"

**Comment by moneromooo-monero** [comment]
Can you with with strace:

strace -o OUT ./monero.monero-wallet-cli --log-level 3 --generate-new-wallet wallet1

Then check what syscall fails with what error code in the OUT file.

**Comment by kevingwang** [comment]
I  downloaded another one from 
https://getmonero.org/downloads/#linux
and now it works normally.

That one with "failed to save file" bugs was downloaded from github:
https://github.com/monero-project/monero

**Comment by moneromooo-monero** [comment]
OK,so a new bug.
Can you try with the github version, but reverting one patch:
git revert 430268224d71bfc6a359f20c6db712462ce0bb25

**Comment by bigjay4465** [comment]
Trying to login and this is what I am getting ERROR : Failed to upgrade to HD and save wallet Please help me with solution so I can pay  my school fees please thanks jk1070460@gmail.com

**Comment by pkudel4** [comment]
just use the absolute path - there is no bug

**Comment by moneromooo-monero** [comment]
Doesn't looks like a monero error message. Report to whatever software you're using,
