### ISSUE TITLE
Fee in testnet v8 does not change across different priority settings

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero#3397]
Here is the same 0.00101 fee across priorities 1, 4, and 2: https://paste.fedoraproject.org/paste/5LaUb7jDdo5WtvzgTQEiKg

Likely this is just because the fee algorithm hasn't been created for multi input bulletproofs (or whatever the term is), but I thought I'd throw up this issue just in case.

**Comment by stoffu** [comment]
This is a bug fixed by #3398.
Thank you for reporting!

**Comment by xmr-eric** [comment]
@stoffu Thank you for fixing it
