### ISSUE TITLE
Will updating the PoW two times a year be enough to ban ASICs?

### ISSUE THREAD

**Issue by gvgit** [monero-project/monero#3400]
Are the producers of the new found ASICs fast enough to build new ASICs to monopolize the market again?
What do you guess?

**Comment by fluffypony** [comment]
I’ve spoken to several ASIC specialists and to two manufacturers, even in a best case scenario a very quick manufacturer would maybe, possibly take delivery of an initial batch around the 5 month mark after they started design work. Any minor hiccup pushes that out to 6+ months.

**Comment by iamsmooth** [comment]
Even if they could build instantly (hyperbole of course), reducing the useful lifespan to six months (or, realistically, significantly less than that) would severely damage the economics of it. That doesn't apply if other coins with high value start using the same or previous algorithms though.

**Comment by gvgit** [comment]
Thanks
