### ISSUE TITLE
CLI wallet stuck at creating wallet with windows10 new console

### ISSUE THREAD

**Issue by Lafudoci** [monero-project/monero#3401]
The screen hanged at creating wallet while listing seed languages

![cmd stuck](https://user-images.githubusercontent.com/10460270/37405459-9e34dea4-27cf-11e8-88f3-3b31676fad1a.PNG)

But I found if I switch the cmd to legacy console, it works without this issue.
(this pic is from web, mine is in Chinese)
![legacy-cmd-console](https://user-images.githubusercontent.com/10460270/37405643-2133fb3c-27d0-11e8-87b0-a29f4cc63ff8.png)
![cmd no stuck](https://user-images.githubusercontent.com/10460270/37405668-30d405d2-27d0-11e8-8dfd-c058dad9f829.PNG)

I believe it's about screen (output?) issue. Because if I press 1 and enter, it can still generate wallet file. 
Here is the log while stuck: https://pastebin.mozilla.org/9079987
OS: Win10 x64 1709

**Comment by moneromooo-monero** [comment]
You mean it seems to work normally, except there's no output after the startup ?
Seed languages have some non ASCII characters, that might confuse it if it misinterprets them (ie, it thinks it's control codes and not UTF-8).

**Comment by Lafudoci** [comment]
Yes, it seems works (observe by the log) if I blindly type command. I tried switch to UTF-8 but same issue.

**Comment by Lafudoci** [comment]
BTW, if I open an existing wallet, it works normally. It only happens in generating wallet for me.

**Comment by Lafudoci** [comment]
Yes, that change fixes it.

**Comment by moneromooo-monero** [comment]
If you undo the test change above, and revert 430268224d71bfc6a359f20c6db712462ce0bb25 ("git revert 430268224d71bfc6a359f20c6db712462ce0bb25"), does this fix it too ?

**Comment by moneromooo-monero** [comment]
In the meantime, there is a workaround in https://github.com/monero-project/monero/pull/3426

**Comment by Lafudoci** [comment]
The git revert 4302682 doesn't fix. I'll try the workaround.

**Comment by Lafudoci** [comment]
The workaround in #3426 works good.

**Comment by moneromooo-monero** [comment]
Thanks. It's been merged already. A long term fix will be needed, if we find a windows coder who gets the problem.

+resolved
