### ISSUE TITLE
How can I test the new v7 PoW?

### ISSUE THREAD

**Issue by zzh1996** [monero-project/monero#3406]
I have my own fork of a mining software. But I am not sure whether it will work correctly and generate valid shares after the PoW change on March 28.

Are there any mining pools which I can connect my miner to, and test for the new PoW?

Or any guide to run a v7 blockchain locally, solo mining on the low difficulty chain?

Thanks

**Comment by moneromooo-monero** [comment]
There is a testnet pool at killallasics.moneroworld.com.

**Comment by zzh1996** [comment]
It works. Thanks
