### ISSUE TITLE
Required changes to PoW validation for upcoming V7 hardfork

### ISSUE THREAD

**Issue by oliverw** [monero-project/monero#3411]
The team working on [Miningcore](https://github.com/coinfoundry/miningcore) and most likely other pool software developers would like to start on working on the required changes to the PoW code to support the upcoming V7 hardfork. Is a reference implementation available somewhere?

**Comment by jtgrassie** [comment]
I believe it's this https://github.com/monero-project/monero/commit/608fd6f14a6b9c0eeba2843fb14cbb235be0034f commit.

**Comment by oliverw** [comment]
@jtgrassie Thanks a lot!

**Comment by dEBRUYNE-1** [comment]
+resolved
