### ISSUE TITLE
Using curl to call monero-wallet-rpc api , the result is  401 Unauthorized

### ISSUE THREAD

**Issue by kevingwang** [monero-project/monero#3417]
ubuntu@ip-172-31-42-19:~$ curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'
<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>ubuntu@ip-172-31-42-19:~$

**Comment by moneromooo-monero** [comment]
Either disable authentication (--disable-rpc-login), or authenticate (digest method).

+invalid

**Comment by kevingwang** [comment]
And how to transfer by programming  (for example , by php programming ) ?
There is no username and password parameters  for the JSON-RPC function of transfer() .

**Comment by kevingwang** [comment]
ubuntu@ip-172-31-42-19:~$ curl  -u "wallet1":"123456" --digest -s -S  -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'
<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>ubuntu@ip-172-31-42-19:~$
