### ISSUE TITLE
After solving the ASIC-issue end of march, what about FPGAs?

### ISSUE THREAD

**Issue by gvgit** [monero-project/monero#3423]
Is there any threat coming from FPGAs?

**Comment by moneromooo-monero** [comment]
This is a bug tracker. Discussion can do on IRC (#monero on Freenode), Reddit, or monero.stackexchange.com for precise non-opinion questions.

+invalid

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by gvgit** [comment]
sorry
