### ISSUE TITLE
About  tag of Monero V7 release

### ISSUE THREAD

**Issue by netmebtc** [monero-project/monero#3427]
xmr-stak‘s  auther said that you should release a offcial tag of Monero V7 POW,  otherwise they will not release a cryptonightV7 version for cpu and gpu miner.

What a  tag is ?   You and xmr-stak's auther ignore all of the cpu and gpu miners ， each shirk wrangling with each other?

https://github.com/fireice-uk/xmr-stak/issues/1163#issuecomment-373930158
https://github.com/fireice-uk/xmr-stak/issues/1160#issuecomment-373966408

**Comment by netmebtc** [comment]
I beg you release that shit tag as as soon as possible，please！

**Comment by moneromooo-monero** [comment]
A tag will be made very soon. We're not ignoring miners, whether cpu or gpu. Patches were made for most of the miners (we knew of).

**Comment by fireice-uk** [comment]
Thanks! As you can see having such a major change without finalising the release code is getting everyone nervous.

**Comment by moneromooo-monero** [comment]
The fork was pushed to the 6th for that reason (1546000). The need to add mitigations for the key reusing fork pushed a lot of work needing doing for the release too. Ah well. Maybe next time will be on time.

**Comment by netmebtc** [comment]
hi @moneromooo-monero  and  @fireice-uk . I am very glad to see that your  consideration of all cpu and gpu miners. hope a very perfect and offcial  release version  before 28 march. Thank you very much!

**Comment by sx5486510** [comment]
Is that mean, xmring 2.5 is not a release version?
And xmring said, the change will  move to April 6? [https://github.com/xmrig/xmrig/blob/master/README.md](url)
Realy?

**Comment by moneromooo-monero** [comment]
The release-v0.12 branch is now on github.

**Comment by gituser** [comment]
hi! how to build new version?

it doesn't recognize anymore `BOOST_ROOT` for some reason and trying to use system libboost 

```
export BOOST_ROOT=/home/build/monero/boost/boost.build DEVELOPER_LOCAL_TOOLS=1
make release-static
```

**Comment by gituser** [comment]
the new error for me is:

```
-- Using C security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- AES support enabled
-- Found Boost Version: 106200
-- Found Readline: /usr/include  
-- Looking for rl_copy_text
-- Looking for rl_copy_text - not found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - not found
-- Looking for rl_copy_text
-- Looking for rl_copy_text - found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - found
-- Found readline library at: /usr
-- Found Git: /usr/bin/git
Doxygen: graphviz not found - graphs disabled
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.8") 
-- Performing Test HAVE_C11
-- Performing Test HAVE_C11 - Success
-- Configuring done
CMake Error at src/CMakeLists.txt:98 (add_library):
  Cannot find source file:

    /home/build/monero/source/build/release/version.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  src/CMakeLists.txt:86 (monero_add_library_with_deps)
  src/CMakeLists.txt:109 (monero_add_library)


-- Build files have been written to: /home/build/monero/source/build/release
Makefile:68: recipe for target 'release-static' failed
make: *** [release-static] Error 1
Build Failed.
```

**Comment by moneromooo-monero** [comment]
Please file bugs in new issues, or it's going to be very confusing and hard to track.

**Comment by gituser** [comment]
https://github.com/monero-project/monero/issues/3463

done, sorry for that!

**Comment by moneromooo-monero** [comment]
For the record, a tag was made yesterday.

**Comment by moneromooo-monero** [comment]
+invalid
