### ISSUE TITLE
Fee too high (Priority Low)

### ISSUE THREAD

**Issue by juanpc2018** [monero-project/monero#3436]
https://github.com/m2049r/xmrwallet/issues/211

call me crazy, but a fee of 0.0025-0.0029 XMR seems too much!
Ringsize5-Ringsize26.
that was one of the problems with Bitcoin, & one of the reasons Bitcoin Cash was born.

if Bitcoin dies, and Monero becomes the New Standard. or if XMR price reach BTC price of today.
0.0025 will become $2Ousd. Fee. for a $8Ousd. transaction. 25% is crazy.

WesternUnion will go extinct like BlockBuster, but Only if fees are Same or Lower.
WU fee is 1%~3%.

¿is this a Monerujo problem or a Monero design flaw? i´m New to this.
¿How much is the Monero Coin limit?
something is not right, does not add up.

**Comment by Gingeropolous** [comment]
as monero usage increases, the fees decrease. So the best we can hope for is more users. 

Its a chicken and egg problem, but it is what it is.

**Comment by moneromooo-monero** [comment]
This is a bug tracker. Try #monero on Freenode or Reddit.

+invalid
