### ISSUE TITLE
Monero-Gui default screen, and Items order...

### ISSUE THREAD

**Issue by juanpc2018** [monero-project/monero#3437]
seems to me that the Top Left Menu in the GUI, should be History...
inside History: Send, Receive & Address.

Send 1st does not make sense.
Address Hidden also strange... at least should be outside, like Send & Receive.

**Comment by moneromooo-monero** [comment]
Please file GUI bugs on the GUI repo: https://github.com/monero-project/monero-core/issues

+invalid
