### ISSUE TITLE
Windows Monero-GUI Address & Send Menu does not Load QR codes...

### ISSUE THREAD

**Issue by juanpc2018** [monero-project/monero#3438]
few desktops have webcams, or HDMI recorders,
but could load .jpg .png, etc...

Tablets have cameras, like Microsoft Surface Pro 2 & HP Stream7, but the "webcam" are "low quality", good enough for QR.

take for example: Dogecoin semi-Light desktop wallet MultiDoge 0.1.7
it can understand QR codes in Desktop, Drag & Drop, etc...

http://multidoge.org/release-notes.html
https://github.com/langerhans/multidoge

OBS has the code to "understand" Webcams, "cut & paste"
https://obsproject.com
https://github.com/obsproject/obs-studio

**Comment by moneromooo-monero** [comment]
Please file GUI bugs on the GUI repo: https://github.com/monero-project/monero-core/issues

+invalid
