### ISSUE TITLE
Daemon Stop at here

### ISSUE THREAD

**Issue by jinglics** [monero-project/monero#3440]
Now is hundreds of blocks delay.

![screenshot from 2018-03-19 17-05-54](https://user-images.githubusercontent.com/3910258/37586603-d9309b9e-2b97-11e8-87d1-e00a06205328.png)

**Comment by jinglics** [comment]
I use Helium Hydra, Point Release 1

**Comment by moneromooo-monero** [comment]
Restart monerod with `--log-level 1` to see whether blocks are being rejceted, and why.

**Comment by gituser** [comment]
I had the same issue - restart helped for me. I'll look into logs later and report back.

**Comment by moneromooo-monero** [comment]
All known sync bugs are now fixed in release-0.12. Reopen if it happens again with it.

+resolved
