### ISSUE TITLE
Using curl to call monero-wallet-rpc api, the result is   401 Unauthorized

### ISSUE THREAD

**Issue by kevingwang** [monero-project/monero#3449]
Start monero-wallet-rpc  successfully : 

./monero-wallet-rpc --rpc-bind-port 18082 --wallet-file wallet1
Monero 'Helium Hydra' (v0.11.1.0-release)
2018-03-20 07:58:33.069	    7fdfa8233780	INFO 	global	contrib/epee/include/net/http_server_impl_base.h:70	Binding on 127.0.0.1:18082
2018-03-20 07:58:33.110	    7fdfa8233780	WARN 	wallet.rpc	src/wallet/wallet_rpc_server.cpp:1898	Starting wallet rpc server

Then call the rpc api , the result is  <h1>401 Unauthorized</h1>

ubuntu@ip-172-31-42-19:~$ curl -u "wallet1":"123456" --digest -s -S -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'
<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>ubuntu@ip-172-31-42-19:~$ 
ubuntu@ip-172-31-42-19:~$ 
ubuntu@ip-172-31-42-19:~$ 
ubuntu@ip-172-31-42-19:~$ curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'
<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>ubuntu@ip-172-31-42-19:~$

**Comment by kevingwang** [comment]
If i use  --disable-rpc-login  option to start  monero-wallet-rpc, the result is correct: 

ubuntu@ip-172-31-42-19:~$ curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getbalance"}' -H 'Content-Type: application/json'
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "balance": 0,
    "unlocked_balance": 0
  }



so, how to use programming language( for example , php ) to call rpc api to transfer money? Always use 
--disable-rpc-login  to start  monero-wallet-rpc  ?

**Comment by moneromooo-monero** [comment]
Works for me. Are you sure you copied the login/password correctly from the file it generates ?

**Comment by krtschmr** [comment]
Hi @kevingwang 

this is how to do CURL correctly with the RPC client

https://github.com/krtschmr/monero/blob/master/lib/monero/client.rb#L8

**Comment by krtschmr** [comment]
Hi @kevingwang 

this is how to do CURL correctly with the RPC client

https://github.com/krtschmr/monero/blob/master/lib/monero/client.rb#L8

Pls make sure to start correct

Start your daemon `./monerod --testnet`

Start your RPC Client `./monero-wallet-rpc --testnet --rpc-bind-port 18081 --rpc-bind-ip 127.0.0.1 --rpc-login username:password --log-level 4 --wallet-dir ./`

**Comment by moneromooo-monero** [comment]
If no further comment soon, I'll assume this was user error and close.

**Comment by moneromooo-monero** [comment]
+invalid
