### ISSUE TITLE
How to generate GENESIS_TX and GENESIS_NONCE?

### ISSUE THREAD

**Issue by 15963** [monero-project/monero#3451]
How to generate GENESIS_TX and GENESIS_NONCE? 
Does GENESIS_NONCE have any special meaning?

 demo:
    std::string const GENESIS_TX = "013c01ff0001ffffffffffff0302df5d56da0c7d643ddd1ce61901c7bdc5fb1738bfe39fbe69c28a3a7032729c0f2101168d0c4ca86fb55a4cf6a36d31431be1c53a3bd7411bb24e8832410289fa6f3b";
    uint32_t const GENESIS_NONCE = 10002;

**Comment by hyc** [comment]
This issue tracker is for bug reports, it's not a help desk. Try monero.stackexchange.com.
+invalid

**Comment by 15963** [comment]
@hyc do you have qq or wechat??

**Comment by sebseb7** [comment]
use some other daemon that supports "--print-genesis-tx" , compile that daemon with your coin parameters to get a correct genesis tx

**Comment by 15963** [comment]
I  use cryptonote , it supports --print-genesis-tx.
url is : https://github.com/cryptonotefoundation/cryptonote.

is it generated, can it be used in Monroe?
@sebseb7

**Comment by sebseb7** [comment]
"is it generated, can it be used in Monero?"

you can use a genesis tx from forknote in monero as long as the coin parameters are the same
