### ISSUE TITLE
[SOLVED] Stagenet  all shares rejected as low difficulty shares

### ISSUE THREAD

**Issue by Admiral-Noisy-Bottom** [monero-project/monero#3456]
I've been testing and developing a pool for the past week without any issues with mining. All of a sudden, yesterday (20th of March in Australia) all shares submitted by test miners are rejected - every one of them.

I ran my miner on another site and go the same problem, so I did some research. Found something about an upgrade taking place on the 28th of March and also found that XMRIG had been update to work with the new monero upgrade.

I ran the miner on a normal monero pool with out issue. But on my stagenet pool, every share is rejected.

Any ideas?

**Comment by Admiral-Noisy-Bottom** [comment]
Turns out the issue was cause by my own stupidity!

The version of node.js had changed. Once it was back to the recommended version, using the Node Version Manager, the problem went away.

You're dismissed, carry on.

**Comment by moneromooo-monero** [comment]
Good to see all is well :)

+invalid
