### ISSUE TITLE
What is the affect if I set Maturity Depth lower?

### ISSUE THREAD

**Issue by Admiral-Noisy-Bottom** [monero-project/monero#3481]
I'm running a test pool on TESTNET to confirm miners get paid. But it takes so long to confirm blocks because they require a depth of 60.

What will be the effect of changing that to a lower number? 

I know blockchains rely on previous blocks to ensure things are correct, but if a block is added with lower confirmation will that have any adverse affects.

I'm a CPU miner, but on TESTNET a block hasn't been found for 11 hours. It is going to take another week to confirm the blocks I'm waiting on. :(

**Comment by moneromooo-monero** [comment]
Such questions are good for monero.stackexchange.com.

**Comment by Admiral-Noisy-Bottom** [comment]
You're probably right, but I was referring to the blockchain. I'm guessing by your answer that Monero doesn't have the maturity of 60 hard coded, therefore I can change it. The question was about Monero rather than the pool, I only mentioned the pool for informational purposes :)

Thanks, I'll change it to make my life easier during testing.

**Comment by moneromooo-monero** [comment]
+invalid
