### ISSUE TITLE
--restricted-rpc does not allow transfer (testnet)

### ISSUE THREAD

**Issue by m2049r** [monero-project/monero#3484]
when running ```monerod --restricted-rpc```, ```monero-wallet-cli``` can sync but not transfer.
```
[wallet A2WSSD]: transfer A2RJ1VpwWJ37sGzLSph1YGfTkBgxuy4dHepMum6vL8zNQBAtU8NLYawNWJZVeSDoNaj4ngNWMjLYj1aUcD25Jrt95p8keZX 0.5
Wallet password: 
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
Error: no connection to daemon. Please make sure daemon is running.
Error: There was an error, which could mean the node may be trying to get you to retry creating a transaction, and zero in on which outputs you own. Or it could be a bona fide error. It may be prudent to disconnect from this node, and not try to send a tranasction immediately. Alternatively, connect to another node so the original node cannot correlate information.
[wallet A2WSSD]: 
```

when running without ```--restricted-rpc```, transfer works just fine.

**Comment by Admiral-Noisy-Bottom** [comment]
My reading of the --restriced-rpc is that it allows read-only access. Transfer would be a read-write I would have thought. I could be wrong, I'm kind of new to Monero.

**Comment by moneromooo-monero** [comment]
That's the new output distribution RPC which is fairly heavy, and needed for the mitigations.

**Comment by Lafudoci** [comment]
@moneromooo-monero  So how can I can safely provide public node for others without `--restricted-rpc` ?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3486

**Comment by moneromooo-monero** [comment]
It was not intended, see above patch which fixes it.

**Comment by m2049r** [comment]
confirmed.
