### ISSUE TITLE
12.0 does not build on OSX 10.13.3

### ISSUE THREAD

**Issue by BigslimVdub** [monero-project/monero#3495]
Tried master, release zip, and release tar.gz and all 3 give the following issue with GTest:

CMake Warning at /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:786 (find_package)

-- Found Boost Version: 106600
-- Looking for rl_copy_text
-- Looking for rl_copy_text - not found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - found
-- Could not find GNU readline library so building without readline support
-- Found Git: /usr/local/bin/git
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- GTest not found on the system: will use GTest bundled with this source
Doxygen: graphviz not found - graphs disabled
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Performing Test HAVE_C11
-- Performing Test HAVE_C11 - Success
-- Configuring incomplete, errors occurred!

I do not get errors building from brew (but that is only updated for 11.1.0 not 12.0)
I do not get errors building from brew

**Comment by MarkusZoppelt** [comment]
You will need some more dependencies, run:

`brew install zeromq`
`brew install --HEAD andresv/gnuradio/cppzmq`

Then try `make` again

**Comment by BigslimVdub** [comment]
I already have zeromq installed and zpp file in the folder as listed in install wiki. 

I have installed aeon cli amd rebase cli and a few others with no issues after installing all dependencies. I’ve never seen this issue before.

**Comment by onodera-punpun** [comment]
I'm having the same error on Linux:

```CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:786 (find_package)


CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:786 (find_package)


CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:786 (find_package)


CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:786 (find_package)


-- Found Boost Version: 106600
-- Looking for rl_copy_text
-- Looking for rl_copy_text - found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - found
-- Found readline library at: /usr
-- Found Git: /usr/bin/git
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.14") found components:  doxygen dot
-- Performing Test HAVE_C11
-- Performing Test HAVE_C11 - Success
-- Configuring incomplete, errors occurred!
```

**Comment by erkmos** [comment]
Had the same issue and it seems it's easier to use Boost 1.65 instead. cmake seemingly has some hack that needs to be updated for every boost version. Didn't dig deeper, but this works for me.

**Comment by onodera-punpun** [comment]
I tried cmake 3.10.3 and 3.11 (still in beta), both don't work. The thing is, I haven't had any problems compiling other programs with boost 1.66.

**Comment by blockchainbuzz** [comment]
I think you have is missing dependencies, such as 'readline', 'doxygen', and 'gtest'. It is requested when you compile it with cmake not with brew.  I slowly fix the compiling error. one by one by installing missing dependencies. It might be related with my ticket. #3506

**Comment by onodera-punpun** [comment]
https://github.com/monero-project/monero#compiling-monero-from-source

I have all the non-optional dependencies installed.

**Comment by danrmiller** [comment]
I can build on osx 10.13 with boost 1.66. 
https://build.getmonero.org/builders/monero-static-osx-10.13/builds/3
This is from 'master', I'll setup a job to build from the release tag shortly.
It is supposed to build fine without the optional dependencies readline and doxygen that @blockchainbuzz mentions, and if gtest is not found it uses the "vendored" code included in the monero tree.

**Comment by danrmiller** [comment]
I know this was already asked in this thread, but can you please confirm that you cloned recursively?

**Comment by erkmos** [comment]
Should add that I had the issue when building with the Dockerfile supplied by the v0.12.0.0 release, not with homebrew. Just changing to boost 1.65 fixed the issue for me.

**Comment by BigslimVdub** [comment]
Honestly I just downloaded the binaries and running that now.  monero-mac-x64-v0.12.0.0.tar.bz2 and it seems to be working fine. Unfortunately GUI isn't built yet so I will have to use CLI for now.

**Comment by moneromooo-monero** [comment]
Those cmake warnings about boost are OK, they're not fatal. There must have been another error.

**Comment by moneromooo-monero** [comment]
Please post the rest of the cmake output, as the error is likely there.

**Comment by dEBRUYNE-1** [comment]
@BigslimVdub - Did you checkout the v0.12.1.0 tag?

**Comment by BigslimVdub** [comment]
I did not add the tag before building. This was related to 12.0 so if you want to close that’s fine. When I get time I can try 12.1

**Comment by moneromooo-monero** [comment]
Doesn't matter, we can keep it open till you confirm.

**Comment by BigslimVdub** [comment]
successful build on 10.13.4 using : 

```
git checkout tags/v0.12.1.0
```

Can you add that line to the compile instructions? I am closing this due to it building now.
