### ISSUE TITLE
Unable to make import_multisig_info: Daemon claims reorg below last checkpoint

### ISSUE THREAD

**Issue by naughtyfox** [monero-project/monero#3505]
I'm playing around with monero multisignatures and encountered the error in current master:
```
[wallet 49yJuz]: export_multisig_info info1
Wallet password: 
File info1 already exists. Are you sure to overwrite it? (Y/Yes/N/No): y
Multisig info exported to info1
[wallet 49yJuz]: import_multisig_info info2 info3
Wallet password: 
Error: Failed to import multisig info: Daemon claims reorg below last checkpoint
[wallet 49yJuz]: 
```
This happens because wallet wants to `detach_blockchain` on height where the first multisignture output is met (which is 1520XXX), but there is new checkpoint on height 1530000 so sanity check inside the function throws the error.

**Comment by moneromooo-monero** [comment]
Good catch!

I can't try it right now, but this should fix it (you'll have to delete the wallet cache first):

```
diff --git a/src/wallet/wallet2.cpp b/src/wallet/wallet2.cpp
index dab2129..d22f72f 100644
--- a/src/wallet/wallet2.cpp
+++ b/src/wallet/wallet2.cpp
@@ -3822,6 +3822,10 @@ void wallet2::load(const std::string& wallet_, const epee::wipeable_string& pass
 void wallet2::trim_hashchain()
 {
   uint64_t height = m_checkpoints.get_max_height();
+  for (const transfer_details &td: m_transfers)
+    if (td.m_block_height < height)
+      height = td.m_block_height;
+
   if (!m_blockchain.empty() && m_blockchain.size() == m_blockchain.offset())
   {
     MINFO("Fixing empty hashchain");
```

**Comment by naughtyfox** [comment]
deleted `mainnet-1` file (is this considered as cache file?), remained only `mainnet-1.keys` and `mainnet-1.address.txt`, applied the patch, built and this didn't help.

**Comment by moneromooo-monero** [comment]
Yes, that's the cache file.
I'll try to repro when I can then.
