### ISSUE TITLE
Compiling monero v0.12 Ubuntu 16.04 gtest Error

### ISSUE THREAD

**Issue by blockchainbuzz** [monero-project/monero#3506]
I am new with with gtest. I had the following error. What does the error means? Any idea idea how to solve it?

[ 84%] Linking CXX executable unit_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1205: recipe for target 'tests/unit_tests/unit_tests' failed
make[3]: *** [tests/unit_tests/unit_tests] Error 1

**Comment by moneromooo-monero** [comment]
As the error says: you need a libgtest compiled with -fPIC. Uninstalling your own will cause the embedded one to be used, and that one does.

**Comment by blockchainbuzz** [comment]
thanks problem is solved by compiled libgtest with -fPIC. 
add following lines in libgtest cmake file:
```
`set(CMAKE_C_FLAGS` "${CMAKE_C_FLAGS} -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}-fPIC")``
```

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by bymagnum** [comment]
help!

where did you insert these lines? I can't compile properly

**Comment by BandAlD** [comment]
For Ubuntu(Debian?)

apt-get install libgtest-dev
cd /usr/src/gtest
vim CMakeCache.txt
Change **`CMAKE_CXX_FLAGS:STRING=`** to **`CMAKE_CXX_FLAGS:STRING=-fPIC`**
Change **`CMAKE_C_FLAGS:STRING=`** **`CMAKE_C_FLAGS:STRING=-fPIC`**
write and quit
cmake .
make
mv libg* /usr/lib/

That should clear the error and allow you to compile monero

**Comment by bymagnum** [comment]
Thanks a lot!
It Worked!
