### ISSUE TITLE
Vendored unbound not present in the source code tar release

### ISSUE THREAD

**Issue by onodera-punpun** [monero-project/monero#3507]
See title :). All other vendored dependencies are, except for unbound.

**Comment by moneromooo-monero** [comment]
Probably because it got moved to a submodule.
AFAIK, the tarballs are made by github themselves, so unsure how to fix..

**Comment by anonimal** [comment]
@onodera-punpun `$ git clone --recursive`

**Comment by onodera-punpun** [comment]
@anonimal The thing is when you download the tar release that's not possible.

**Comment by anonimal** [comment]
Then clone.

**Comment by moneromooo-monero** [comment]
Fixed in 0.13.0.4.

+resolved
