### ISSUE TITLE
Define default port for wallet RPC

### ISSUE THREAD

**Issue by arnuschky** [monero-project/monero#3509]
Previous (unofficial?) default port was 18082, which has now been assigned to the zmq rpc. The wallet's help doesn't specify a default port.

I think that default ports are useful for easing deployment / installation. Looking at what happened with the zmq rpc, maybe we should offset the wallet's ports from the daemon, eg starting at 18088 or 18090.

Opinions?

**Comment by jtgrassie** [comment]
```
src/cryptonote_config.h:  uint16_t const P2P_DEFAULT_PORT = 18080;
src/cryptonote_config.h:  uint16_t const RPC_DEFAULT_PORT = 18081;
src/cryptonote_config.h:  uint16_t const ZMQ_RPC_DEFAULT_PORT = 18082;
```

**Comment by arnuschky** [comment]
Yes, these are the daemon default ports. I am talking about defining this for the wallet too.

**Comment by jtgrassie** [comment]
You mean the monero-wallet-rpc? There is no default port assigned to that looking at the source. You specify with `--rpc-bind-port`

**Comment by arnuschky** [comment]
Yes, I mean monero-wallet-rpc (see title). Yes there is no default port assigned to it. This issue is about defining a default port.

**Comment by jtgrassie** [comment]
Sorry title was ambiguous as normal wallet uses RPC to connect to daemon. Anyway...

I'm not sure defining a default port for monero-wallet-rpc is needed (or advisable). Opens up an easy port scanning security issue.

**Comment by stoffu** [comment]
AIUI the default port for wallet RPC is left undefined on purpose, so that uneducated users can’t easily make mistakes and lose money.

**Comment by arnuschky** [comment]
Ah ok, I didn't think of that reason. Good point. Closing.

**Comment by jtgrassie** [comment]
Indeed. It's a required parameter.
