### ISSUE TITLE
First conditional way to block over performance ASCII miner...  >=100KH

### ISSUE THREAD

**Issue by manfire** [monero-project/monero#3517]
if the worker(real physical unit) is over then >=100KH with 1 single thread, no graphic card can do this.  just block over then hash rate and it a good condition rule to block the ascii miner, I know you can bypass this but for more 50% user it over. 5 time trying to connect in 15 minutes, just add temporary ban list IP for stop hammering.

** sorry for user buy X3 from bitmain or (DragonMint X2 if exist) you need to understand the reel sense of Monero.

Monero cryptocurrency is a free world / not centralized .

**Comment by moneromooo-monero** [comment]
Peers have no way to know whether a block was mined by a fast machine. What you suggest seems to be designed for pools, but a fast miner can run their own.

+invalid
