### ISSUE TITLE
We need RawImport for Testnet

### ISSUE THREAD

**Issue by krtschmr** [monero-project/monero#3519]
currently the Testnet sync can take up to 8 hours.

Either we restart the testnet once a month (not a good idea tho) or we have an official testnet download

**Comment by fluffypony** [comment]
Testnet and stagenet aren't mainnet-critical components, so I'd suggest someone host an unofficial download. If they go rogue and attack testnet and stagenet it's not a big deal.

**Comment by raxbg** [comment]
I vote for the testnet download

**Comment by krtschmr** [comment]
That's true. Let me talk to moneroworld, maybe he can do :)

**Comment by digianarchist** [comment]
http://www.mediafire.com/file/4rc78pb8ed21bk1/monero_testnet_v8_1070681.raw

**Comment by selsta** [comment]
Closing as I think there aren't any plans for an official blockchain.raw file for testnet / stagenet.
