### ISSUE TITLE
cc1plus.exe: out of memory allocating 3154664 bytes

### ISSUE THREAD

**Issue by italocoin-project** [monero-project/monero#3521]
I tried to compile branch V12 on a win32 machine with mingw and i always get this error, any ideas?

[ 75%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.obj

cc1plus.exe: out of memory allocating 3154664 bytes
make[3]: *** [src/wallet/CMakeFiles/obj_wallet.dir/build.make:63: src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.obj] Error 1
make[3]: Leaving directory '/home/xxx/monero-core/monero/build/release'
make[2]: *** [CMakeFiles/Makefile2:2281: src/wallet/CMakeFiles/obj_wallet.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

**Comment by moneromooo-monero** [comment]
Add memory or swap, or set TMPDIR to a non tmpfs directory.

+invalid

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by italocoin-project** [comment]
I have memory 8GB of ram and CPU was never over 50%, this may be a files header is to large, this must be diagnosed!

**Comment by moneromooo-monero** [comment]
8 GB should be way more than enough. Is that how much is free, or how much is in your machine ?

**Comment by italocoin-project** [comment]
My machine has 8GB but it never surpass 35% usage

**Comment by italocoin-project** [comment]
So for future reference i've resolved the issue, i will post it here maybe others will need it. You need to have at least 4GB of ram!

If your OS is 32bit, then in cmd (as Admin) put bcdedit /set IncreaseUserVa 3072
Install [masm32](http://masm32.com/download.htm);
open cmd (as admin too); 
put `cd C:\msys64\mingw32\lib\gcc\i686-w64-mingw32\[VERSION]`
put `C:\masm32\bin\editbin.exe /LARGEADDRESSAWARE cc1plus.exe`

Be sure to find out which cc1plus.exe you are using, this is for mingw if you use QT add its own pat, usually

put `cd C:\Qt\Tools\mingw492_32\libexec\gcc\i686-w64-mingw32\4.9.2`
put `C:\masm32\bin\editbin.exe /LARGEADDRESSAWARE cc1plus.exe`

That's all. Hope it will be helpful:)

**Comment by italocoin-project** [comment]
+resolved

**Comment by moneromooo-monero** [comment]
Can you make a PR to the build instructions for windows ?

**Comment by italocoin-project** [comment]
@moneromooo-monero i don't think this is a common problem, can you confirm is common? If you can test it on another machine and confirm i'll make a PR, let me know

**Comment by moneromooo-monero** [comment]
I have no idea whether it's common. You're the one using windows :)

**Comment by italocoin-project** [comment]
@monero-project `You're the one using windows` this was a low blow 🥇 We need more people to test it out, if they get the same results i will make a PR

**Comment by danrmiller** [comment]
yes i have the same issue on windows 32-bit

**Comment by danrmiller** [comment]
The steps here fix the problem for me too (windows 32-bit)

https://github.com/monero-project/monero/issues/3521#issuecomment-377466568
