### ISSUE TITLE
The wallet altered my mnemonic during importing

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero#3527]
I generated a 25-word mnemonic seed with [xmr.llcoins.net's Cryptonote Address Tests tool](https://github.com/luigi1111/xmr.llcoins.net/blob/master/site/addresstests.html) by using a custom hexadecimal seed (inserted into box no. 2 and pressed `Gen 1.`). Importing this certain mnemonic into Monero Core via the GUI changed almost all of the words in the mnemonic by the time I got to the last step of the import wizard, and this changed version was stored by the wallet as well. Thankfully, the public address is the same as the one I can derive in the tool.

I can't replicate the behavior with other mnemonics generated by the tool. (I tried with ones generated from other custom hexadecimal seeds, and also with random mnemonics generated with the `Random` button next to box no. 1.)

Why did this happen?

Paging @luigi1111 as it may be related to their code.

**Comment by moneromooo-monero** [comment]
A random hex number is not necessarily a valid canonical secret key. A valid secret key is less than l (the curve order). If your hex key is larger, then its corresponding secret key is itself modulo l. You can check whether this is your problem by calculating your data modulo l in python, and checking whether it's your new secret key. l is... hmm...

    static const key L = { {0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10 } };

**Comment by leafcutterant** [comment]
Could it be problematic if my secret key is modulo l? What are the implications?

And could you give hints on what non-technical tools to use to do this calculation?

**Comment by moneromooo-monero** [comment]
No, it causes problems if it is NOT modulo l.
Non technical tool -> monero-wallet-cli or xmr.llcoins.net or 
https://github.com/moneromooo-monero/monero-wallet-generator/

**Comment by leafcutterant** [comment]
Well, the llcoins tool always gives a private spend key that is `hexSeed mod l`, so it conforms to that. What I meant is this: if a private spend key is derived from a hex seed greater than `l`, will that be more, less, or equally secure compared to one completely generated by e.g. the reference client?

**Comment by moneromooo-monero** [comment]
I think you're getting it wrong: what you call "a hex seed greater than l" is not a valid secret key.

**Comment by leafcutterant** [comment]
Am I? Following the [llcoin tool](https://xmr.llcoins.net/addresstests.html)'s logic, `hexSeed` is not always equal to `privateSpendKey`, because `privateSpendKey` = `hexSeed` mod `l`. Therefore, for every `hexSeed` ≥ `l`, `hexSeed` ≠`privateSpendKey`.

Our misunderstanding may be stemming from the fact that you equate `hexSeed` with `privateSpendKey`.

**Comment by moneromooo-monero** [comment]
OK. I thought you were equating a hex seed with a private spend key, since your original question was "I generated a 25-word mnemonic seed with xmr.llcoins.net's Cryptonote Address Tests tool by using a custom hexadecimal seed", and you didn't mention reducing the value. If you had reduced, then it should have given you a valid key. Did you reduce (ie, modulo l) ?

**Comment by leafcutterant** [comment]
Yeah, sorry, I'm not in loop with the canon, I just used the terminology I found on the llcoins GUI.

I didn't do any reduction myself, but I believe the [llcoins Cryptonote Address Tests tool](https://xmr.llcoins.net/addresstests.html) does that automatically. E.g. if you put a hex value equal or greater than `l` into box no. 2 (what it calls "Hexadecimal Seed") and press `Gen 3. & 4.`, then the result in box no. 3 (what is calls "Private Spend Key") will be different and lesser than the starting hex value.  And in my experience, what it calculates is modulo `l`.  Inputting `edd3f55c1a631258d69cf7a2def9de1400000000000000000000000000000010` (which is `l`) produces `0000000000000000000000000000000000000000000000000000000000000000`, `l` - `1` produces `l` - `1` (so the same value), and `l` + `1` produces `0000000000000000000000000000000000000000000000000000000000000001`. Furthermore, in the case of my initial value that inspired this issue, pasting the reduced value back to box no. 2 and generating a mnemonic from it (`Gen 1.` button) gives the same mnemonic as the one I saw at the end of the import wizard in the Monero wallet.

(From this I infer that the reference client likes to store only the private spend key, not the mnemonic, and it doesn't deal with the concept of llcoins's "hex seed", so for every mnemonic that translates to a value equal to or greater than `l`, it reduces that and generates a new mnemonic from that reduced value -- and that's why the mnemonic alteration happens. If this is considered to be the standard, maybe @luigi1111 wants to modify how the tool works, or at least display a warning when a mnemonic is generated from a "hex seed" that is equal to or greater than `l`.)

So it looks like it checks out, but I'm not sure my tests are proper so review from your side would be warmly welcome.

So, getting back to the main point: I am wondering if using such a private spend key, which is generated via modulo `l` from a 256-bit value equal to or greater than `l` with the llcoins tool, has the same cryptographic strength as a private spend key generated with the reference client. (I'm presuming the 256-bit value is securely random.)

**Comment by moneromooo-monero** [comment]
The wallet code indeed does not store the seed. It is recreated whenever needed from the secret spend key. Mnemonic seeds translate to a key value that's less than l, by construction. This also means not all 25 word lists are valid seeds (though they'll be transformed to a valid one in the way I suspect yours was).  As far as I know, whether your original 256 bit random value is lower than l or not has no (unreasonable) influence on the security of the key modulo l. Some keys are more likely to be created than others due to the modulo operation, but I believe that is negligible for security. luigi will know way more about this though.

**Comment by moneromooo-monero** [comment]
Re-reading, it seems like user error: starting from an invalid hex string interpreted as a secret key.
Fine to close, or is there something more to this ?

**Comment by leafcutterant** [comment]
From the point of view of the Monero Core, it can be interpreted as user error. It is indeed the xmr.llcoins.net tool which needs fixing. They mystery was that llcoins doesn't do a reduction when a mnemonic is generated from `hexSeed` ≥ `l`. When the invalid mnemonic is imported to Monero Core, the reduction occurs. Both tools give the same public address in the end, so in theory it should be all fine if you don't do the reduction with Monero Core, but please don't trust me on this and always do the reduction first, just in case.

If anyone has a comment on the security of keys like this, chime in here later.

Mystery solved, thanks, I'm closing.
