### ISSUE TITLE
linking error bin/monero-wallet-cli.exe windows 7 monero v0.12

### ISSUE THREAD

**Issue by blockchainbuzz** [monero-project/monero#3537]
stuck on this error, don't know how to fix it. any suggestion? it could not find `licuio` `licuin` `licuuc` `licudt` `licutu` . I don't have a problem when compiling in linux. any idea how to solve it?

`[ 92%] Linking CXX executable ../../bin/monero-wallet-cli.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licuio
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licuin
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licuuc
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licudt
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licutu
collect2.exe: error: ld returned 1 exit status
make[3]: *** [src/simplewallet/CMakeFiles/simplewallet.dir/build.make:134: bin/monero-wallet-cli.exe] Error 1
`

**Comment by moneromooo-monero** [comment]
The icu libs changed name recently. Find what they are on your system, and change the makefiles to match. Ideally make a patch to detect both and use the right one ^_^
