### ISSUE TITLE
enhancement request: ability to create offline transactions

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#354]
Suggested by RealBitcoin on bitcointalk:

"i want to create a transaction safely from cold storage offline PC, sign it offline with private key, then transfer that signed TX via QR code scanner, air gapped, to the online PC where I can broadcast it."

https://bitcointalk.org/index.php?topic=1125666.msg11980887#msg11980887

**Comment by moneromooo-monero** [comment]
+resolved
