### ISSUE TITLE
Dark theme: LeftPanel MenuButton symbol displayed in an awkward position

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero#3544]
After the merge of dark theme, the character symbols that show up when pressing Ctrl (or Command on mac) are positioned in the center of the whole column:

![screen shot 2018-04-03 at 19 51 31](https://user-images.githubusercontent.com/26077532/38245455-198bc32a-3779-11e8-9322-3aaddf9a7bdb.jpg)

Before the dark theme, these symbols were shown on top of the small circles on the left of the menu texts.

**Comment by dEBRUYNE-1** [comment]
This should be on the GUI repository?

**Comment by stoffu** [comment]
Sorry :-P
