### ISSUE TITLE
ALT-CHAIN PURPOSE?

### ISSUE THREAD

**Issue by 0xA01** [monero-project/monero#3546]
Hi there!
We are indie Blockchain Startup Incubator from Eastern Europe called CryptoForgery.
First of all, **thanks for great software**!
Recently we Forked **Vanilla Monero 0.12.0 Lithium Luna** and create new Genesis block but our blockchain now is REALLY LIKE ATTACK by some alt-chains. Sometimes it's count is up to 30. What is the point with them? What is the purpose?
Blockchain Height is over 1500 but I'm receiving alternative block for height 700 for example, is this OK in theory?
Please, do not close this issue, I'm not asking you to do my job, I'm asking you for advice: what solutiong would be better in our case, maybe suspend alt-chains and growth network for some height to get own checkpoints? It is 10+ seeds wide now but alt-chains appering again and again and this taking too much processor time of node to reorganize blocks...

**Comment by anonimal** [comment]
>CryptoForgery
>Forgery

Yep, sounds about right.

**Comment by 0xA01** [comment]
Wow such a tech answer.

**Comment by 0xA01** [comment]
So your network will use broken software in 4 days yeah?

**Comment by moneromooo-monero** [comment]
You know, I was about to reply to that, but seeing you being an ass on IRC, I'm not going to.
