### ISSUE TITLE
All forknote-pool blocks are orphaned

### ISSUE THREAD

**Issue by 0xA01** [monero-project/monero#3547]
What pool sofrware is compatible with git-trunk (0.12.0 lithium luna)? Forknote-pool seems to produce all orphaned blocks.

**Comment by moneromooo-monero** [comment]
zone117x's and snipa's are. I don't know about forknote-pool.

More/better info on monero.stackexchange.com

**Comment by 0xA01** [comment]
Thanks, there are some tricks but it is OK.

**Comment by Admiral-Noisy-Bottom** [comment]
Zone117's has crappy admin panel with next to no usable information. Forknote has a pretty good admin, but I can't get it to work with the new Monero. Bad hash from miner, even though it's the up to date xmr-stak and xmrig.

@0xA01 I've looked on stackexchange for answers but found none. What did you have to do to get forknote pool working?
