### ISSUE TITLE
wallet-dir option occurs rpc server error on windows

### ISSUE THREAD

**Issue by pandakiki11111** [monero-project/monero#3548]
I need to use <create wallet api> on rpc server. so I add --wallet-dir option when I start wallet rpc server like this ↓

monero-wallet-rpc --rpc-bind-ip 0.0.0.0 --rpc-bind-port 18082 --log-level 4 --disable-rpc-login --confirm-external-bind --daemon-port 18081 --trusted-daemon --password password --shared-ringdb-dir ringdb --testnet --wallet-file testWallet --wallet-dir walletDir

but it occurs error like this ↓

INFO 	net	contrib/epee/include/net/abstract_tcp_server2.inl:802	Set server type to: 1 from name: RPC, prefix_name = RPC
INFO 	global	contrib/epee/include/net/http_server_impl_base.h:76	Binding on 0.0.0.0:18082
DEBUG	net	contrib/epee/include/net/abstract_tcp_server2.inl:731	start accept
DEBUG	net.p2p	contrib/epee/src/connection_basic.cpp:163	Spawned connection p2p#0 to 0.0.0.0 currently we have sockets count:1
DEBUG	net	contrib/epee/include/net/abstract_tcp_server2.inl:83	test, connection constructor set m_connection_type=1
DEBUG	net	contrib/epee/include/net/net_helper.h:512	Problems at cancel: wrong file handle
DEBUG	net	contrib/epee/include/net/net_helper.h:515	Problems at shutdown: wrong file handle
WARN 	wallet.rpc	src/wallet/wallet_rpc_server.cpp:3001	Starting wallet RPC server
INFO 	net.http	contrib/epee/include/net/http_server_impl_base.h:89	Run net_service loop( 1 threads)...
DEBUG	net	contrib/epee/include/net/abstract_tcp_server2.inl:827	Run server thread name: RPC
DEBUG	net	contrib/epee/include/net/abstract_tcp_server2.inl:834	JOINING all threads

this error occurs only when I add wallet-dir option on command
it works fine when I add <wallet-file> option instead of <wallet-dir> option

**Comment by moneromooo-monero** [comment]
Do you have a stack trace in the log showing where the wrong file handle exception comes from ?

**Comment by pandakiki11111** [comment]
@moneromooo-monero I think it is "invalid file handle" error from windows. That message comes out with Korean. that log is all I got. it copied from < monero-wallet-rpc.log >

**Comment by moneromooo-monero** [comment]
New wallets will be put in that directory. I think that's all, but I've not used this before so I'm not sure.

**Comment by hyc** [comment]
The `--wallet-dir` option is mutually exclusive with the `--wallet-file` option, as the `--help` indicates. I suppose we should add an error message for this case, currently there is none and any passed in wallet-file is ignored when wallet-dir is used.

When `--wallet-dir` is used the client must send open_wallet or create_wallet RPC before doing anything else.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4337

**Comment by moneromooo-monero** [comment]
+resolved
