### ISSUE TITLE
sub-addresses created with the cli are unrecognized by the gui and vice versa

### ISSUE THREAD

**Issue by jonahar** [monero-project/monero#3554]
I have some sub-addresses created with the cli which are not recognized by the gui, and sub-addresses created by the gui which are not recognized by the cli.
It's like each of them looks at a different set of sub-addresses.

**Comment by moneromooo-monero** [comment]
Are you running one on big endian and another on little endian ?
Define "recognized".

**Comment by jonahar** [comment]
I guess I didn't explain properly. By "recognized" I meant "shows" or "lists".
When opening the same wallet file both in the cli and in the gui:
- The cli only lists sub-addresses that were created in the cli.
- The gui only lists sub-addresses that were created in the gui.

I used the official download for Linux 64-bit. I run both of them on the same Linux machine, so I think the answer to the endianness question is no.

**Comment by jonahar** [comment]
Thank you for the clarification.
Indeed, when the default account is chosen in the cli, `address all` shows the addresses created in the gui.

**Comment by moneromooo-monero** [comment]
So all  is working as expected, just confusing, right ?

**Comment by jonahar** [comment]
Yes

**Comment by moneromooo-monero** [comment]
+invalid
