### ISSUE TITLE
Blurred white typface on GUI 0.12.0.0

### ISSUE THREAD

**Issue by allegro101** [monero-project/monero#3569]
Using Win 7 64 bit local node the white typeface is blurred against black background see attached image. GUI working fine otherwise but lack of resolution compared to last release is a concern.

![guinotclear](https://user-images.githubusercontent.com/24720449/38429042-4cd95382-398b-11e8-9e9a-b0248b8a9d27.JPG)

**Comment by cryptochangements34** [comment]
Wrong repo. Please report this in https://github.com/monero-project/monero-gui/issues

**Comment by dEBRUYNE-1** [comment]
+invalid
