### ISSUE TITLE
Monerod error

### ISSUE THREAD

**Issue by rmbb** [monero-project/monero#3580]

**Comment by rmbb** [comment]
Got this error running monerod after 4 hours:

SYNCHRONIZATION started
2018-04-07 16:01:35.432 12156   ERROR   ringct  src/ringct/rctSigs.cpp:361
point conv failed
2018-04-07 16:01:35.441 12156   ERROR   ringct  src/ringct/rctSigs.cpp:361
point conv failed
2018-04-07 16:01:35.450 12156   ERROR   ringct  src/ringct/rctSigs.cpp:361
point conv failed

status
Height: 1546134/1546134 (100.0%) on mainnet, mining at 16 H/s, net hash 645.63 MH/s, v7, up to date, 7(out)+12(in) connections, uptime 0d 5h 17m 18s

**Comment by moneromooo-monero** [comment]
Someone sent an invalid transaction, and some of the data in it is being rejected. This can be ignored.

**Comment by moneromooo-monero** [comment]
Not a bug, just a noisy log, which was recently toned down.

+resolved
