### ISSUE TITLE
[Security] Bundle both GUI & CLI on github for users

### ISSUE THREAD

**Issue by ghost** [monero-project/monero#3585]
Is it possible you could bundle (within separate folders) both the CLI & GUI within "monero-linux-x64-v0.12.0.0.tar.bz2" file on Github with its correct hash?
Would much appreciate this. Some people prefer downloading straight from Github instead of monero.org

**Comment by danrmiller** [comment]
Just a note that monero.org is not associated with the Monero Project, which uses getmonero.org

**Comment by 2SI3NX** [comment]
Sorry i meant getmonero.org NOT monero.org
