### ISSUE TITLE
stagenet dumps its logs into the same folder as mainnet

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#3603]
this was fixed for testnet a while ago, to put the log file in /bitmonero/testnet ..

i bet I could make a patch using the web git GUI ...

**Comment by Gingeropolous** [comment]
seems to be due to using a configuration file, because if I launch normally, the bitmonero.log file ends up in the stagenet subdirectory

**Comment by Gingeropolous** [comment]
also happens with testnet

**Comment by stoffu** [comment]
Could you provide the content of your config file so that the problem can be reproduced?

**Comment by Gingeropolous** [comment]
```user@node:~$ cat /etc/test_monerod.conf 
log-level=0
rpc-bind-ip=0.0.0.0
out-peers=1024
limit-rate-up=65536
limit-rate-down=65536
confirm-external-bind=1
rpc-restricted-bind-port=28089
add-priority-node=5.9.100.248:28080
testnet=1
```

@stoffu ^ ping

**Comment by stoffu** [comment]
#3636

**Comment by DinoStray** [comment]
While I put "log-file=xxx" in bitmonero.conf file, issue like this happened, too.

**Comment by moneromooo-monero** [comment]
+resolved
