### ISSUE TITLE
Cannot start daemon

### ISSUE THREAD

**Issue by dmgmaker** [monero-project/monero#3608]
[monero-wallet-gui.log](https://github.com/monero-project/monero/files/1897620/monero-wallet-gui.log)
I downloaded a new monero folder because i messed up with my last, i also deleted the old blockchain data to get all new. Now i try to start daemon with node.monerworld.com but after a time i get a message which says  daemon cannot connect, sometimes the programm collapses while starting daemon. I put the log in here too maybe someone can find out what is wrong. Thank you for any help.

**Comment by dmgmaker** [comment]
i did node.moneroworld.com as host and as a port i tried 8880 then the daemon said it cant start. When i tried using port 18089 the programm collapsed.

**Comment by dmgmaker** [comment]
But the most irritating thing is, that i cant open the gui anymore it takes hours to load but never finishes. i think i try to delete all folders i know from monero and try to reinstall it.

**Comment by dmgmaker** [comment]
ok somehow i have another problem. I cant start my monero wallet at all. When i try to run the exe it crashes

**Comment by moneromooo-monero** [comment]
Then please post a stack trace:

ulimit -c unlimited
echo core | sudo tee /proc/sys/kernel/core_pattern
Run monero-wallet-gui until it crashes
gdb /path/to/monero-wallet-gui /path/to/core
bt

**Comment by dmgmaker** [comment]
> ulimit -c unlimited
echo core | sudo tee /proc/sys/kernel/core_pattern
Run monero-wallet-gui until it crashes
gdb /path/to/monero-wallet-gui /path/to/core
bt

> 
i dont really get what i need to do

**Comment by moneromooo-monero** [comment]
Are you on Linux, Mac, Windows, other ?

**Comment by dmgmaker** [comment]
I am on Windows

**Comment by moneromooo-monero** [comment]
Then if you know how to get a stack trace from a crash on windows, please do so. If you don't, then we're stuck.

**Comment by dmgmaker** [comment]
yeah i dont know how to get that, but when u say i need it i will look it up and try to do it. Will post when i were successful

**Comment by moneromooo-monero** [comment]
I'm told WinDbg is the tool for that, but I don't know how to use it.
I've added https://github.com/monero-project/monero/issues/3620 to get instructions added to the README for future use. If you find out how to use it before someone else does, maybe you could document the steps :)

**Comment by lashmi57** [comment]
I have the same problem, can't start deamon. on the main site it says:
**Download the new binaries from the official website or Github.**
then: Extract the new binaries to a new directory of your liking.
(a directory where..?? and you can't extract..but you can do a save as..!)
Then: Copy over the wallet files from the old directory (the one that contains the v0.11.0.0 or v0.11.1.0 binaries).
How can you expect the general population to take to this if you keep it techie, I've worked with
software guys over the years...they never get this..!! they write as they program and it might make
sense to them.....but for the non techies it doesn't work.!

**Comment by dEBRUYNE-1** [comment]
@lashmi57:

>I have the same problem, can't start deamon. on the main site it says:

Which operating system are you using?

>Download the new binaries from the official website or Github.

The binaries are the `.zip` file (Windows) or the `.tar.bz2` file (Mac OS X and Linux). 

>(a directory where..??

"To your liking" insinuates that it doesn't matter where you extract the binaries. 

>but you can do a save as..!)

What do you mean here? The `.zip` file or `.tar.bz2` file first has to be saved, but subsequently has to be extracted to properly use the software. 

>Then: Copy over the wallet files from the old directory (the one that contains the v0.11.0.0 or v0.11.1.0 binaries).

This *merely* applies to the *CLI*. The wallet files are `<walllet-name>` (the file without extension), `<wallet-name>.keys`, and `<wallet-name>.address.txt`. 

>How can you expect the general population to take to this if you keep it techie, I've worked with
software guys over the years...they never get this..!! they write as they program and it might make
sense to them.....but for the non techies it doesn't work.!

It's a work in progress.

**Comment by lashmi57** [comment]
Thanks for that...I've actually got the wallet to work in a "fashion". the balance comes up with 2 orange lines  at the bottom of the wallet saying "wallet is synchronised" and "Daemon is synchronised". However the balance at the top is saying **unlocked balance (waiting for block)** 
Does this mean something is not working..??

**Comment by lashmi57** [comment]
I think I'm progressing (apologies, my confusion was with the CLI and GUI instructions getting mixed)
However, I now start up "monerod" it kicks off no problem. I then open up the monero Gui-V12. 
I don't connect the Daemon because after 5/10 minutes "Monerod" seems to take control and switch the Daemon on and off as it "synchronizes". Well this morning it told me that I had 20 blocks to synchronization and it seems to be going backward as it's now 111 blocks to go..??
Can you tell me if I'm on the right track..??
![screenshot 2018-04-30 10 40 50](https://user-images.githubusercontent.com/38524400/39422012-8123ca4c-4c63-11e8-9b25-5bf7df2ab3a8.png)

**Comment by lashmi57** [comment]
dEBRUYNE-1

Hi, just a quick note to say Thank you..!! Truly, Im still not sure how I got the wallet working...but after 3 days of pulling my hair out.
I came across a post of yours in in "Monero Beta" with the heading "I forgot to upgrade from GUI-v11 to Gui V12"
You gave instruction about popping blocks:-   ./monero-blockchain-import --pop-blocks 16500
Well I did this, nothing seem to happen I ran "monerod" it said the instruction stopped at an error location. I shut all the Monero processes and then started up Monero GUI.....It seemed to be frozen then it fired into life with "synchronizing wallet" zipping down from 12000 blocks to zero in about 5 minutes..!! My balance went up by the transaction that happened last week..!! I done a small transaction through shapeshift just to make sure it was working, yes..went through..!! 
So, thank you again, I'm off for a beer and a nervous breakdown..!!

**Comment by lashmi57** [comment]
@dEBRUYNE-1

**Comment by moneromooo-monero** [comment]
Looks like this got resolved long ago, closing.
