### ISSUE TITLE
Index out of bounds of hashchain

### ISSUE THREAD

**Issue by mmitech** [monero-project/monero#3611]
I am trying to sync Monero and get it to work for the last couple of days, I checked up the journalctl today and found this:

```
Apr 11 18:44:27 monero-wallet-rpc[28083]: 2018-04-11 18:44:27.433            7fb59ec25740        ERROR        wallet.wallet2        src/wallet/wallet2.cpp:2288        pull_blocks failed, try_count=3
Apr 11 18:44:27 monero-wallet-rpc[28083]: 2018-04-11 18:44:27.433            7fb59ec25740        ERROR        wallet.rpc        src/wallet/wallet_rpc_server.cpp:2990        Wallet initialization failed: Index out of bounds of hashchain
```
Wallet rpc would crash after this. (v0.12.0.0-master-release)

**Comment by moneromooo-monero** [comment]
This can happen if the wallet tries to reorg past a checkpoint, which should never happen, except if you've been on a fork for quite a long time and it only resolved then. Was this the case ?

**Comment by mmitech** [comment]
I have no idea if this was the case, it could be possible since I am doing this on testnet and it seems like chaos there.

**Comment by moneromooo-monero** [comment]
Do you still have a wallet+cache showing this happening ?

**Comment by moneromooo-monero** [comment]
Probably fixed in https://github.com/monero-project/monero/pull/3716/commits/9875f126bde384123458e9967a58652caf4dd437

Was this on testnet btw ?

**Comment by mmitech** [comment]
Thanks, It is working now, I wanted to update you on the issue right away, but for the life of me, I can't remember what I did.
