### ISSUE TITLE
Generating a Private Key

### ISSUE THREAD

**Issue by quantumproducer** [monero-project/monero#3612]
What are the technical specifications of a private key?

https://getmonero.org/technical-specs/ doesn't say.

https://en.bitcoin.it/wiki/Private_key shows: "In Bitcoin, a private key is a 256-bit number, which can be represented one of several ways. Here is a private key in hexadecimal - 256 bits in hexadecimal is 32 bytes, or 64 characters in the range 0-9 or A-F. "

I need to generate a private key by coin flipping.

**Comment by moneromooo-monero** [comment]
That's a good question for monero.stackexchange.com, try there, and not here, which is a bug tracker.

+invalid

**Comment by quantumproducer** [comment]
@moneromooo-monero I consider this a documentation bug. The wiki . https://github.com/monero-project/monero/wiki does not have this information whereas the Bitcoin wiki does.
For anyone reading, I'm seeing reports of 64 bit Hexadecimal.

**Comment by fluffypony** [comment]
64 hexadecimal characters is 256 bits. If you think it should be in the wiki then please add it.

**Comment by quantumproducer** [comment]
Thanks @fluffypony , I will when I get confirmation on monero.stackexchange
