### ISSUE TITLE
Funds of 0.11 wallet are not showing in 0.12 wallet

### ISSUE THREAD

**Issue by Zettt** [monero-project/monero#3614]
After upgrading to the 0.12 chain, my funds were not showing anymore in my wallet. I had an issue upgrading directly to the 0.12 chain and I now have a `.unportable` file in my 0.11 wallet directory. I recreated the wallet from its seed to check whether the funds would show up eventually, but they didn't. Upgrading the chain – only running 0.12 `monerod` – I also had some issues apparently. So I deleted the entire blockchain itself, downloaded the raw blockchain again, and reimported it using the CLI tool. The funds still not show up, and I'm a little clueless, at to what I can still try. Thanks for your help!

**Comment by moneromooo-monero** [comment]
Type "set" and check the value of refresh-from-block-height. If it's after the first tx for that wallet, set it to earlier (or even 0), then rescan_bc.

**Comment by selsta** [comment]
Closing as no reply from the issue creator and no longer relevant.
