### ISSUE TITLE
Wallet RPC (transfer): Transaction Key (tx_key) returns empty value

### ISSUE THREAD

**Issue by cookiedumper** [monero-project/monero#3623]
I run into an issue where when submitting an RPC request to the `transfer` method,
the `tx_key` (that helps prove a tx was made) is not being returned.

Sample request:

    array (
      'destinations' => 
      stdClass::__set_state(array(
         'amount' => '0.01314010',
         'address' => '44P8rkTRW5u1i...cEePYi4J5Vr3QLimydCX',
      )),
      'mixin' => 4,
      'get_tx_hex' => true,
      'get_tx_key' => true,
      'payment_id' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    )

What is being returned is:

    stdClass::__set_state(array(
       'amount' => 1140160000,
       'fee' => 10785600000,
       'multisig_txset' => '',
       'tx_blob' => '',
       'tx_hash' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
       'tx_key' => '',
       'tx_metadata' => '',
    ))

As you can see the `tx_key` property was returned empty. This isnt' the desired nor correct behavior.
Any ideas?

**Comment by stoffu** [comment]
I can't reproduce this behavior. Could be a bug.

**Comment by moneromooo-monero** [comment]
This data is (1) not saved unless store-tx-info is true in the settings, and (2) not restorable if you delete the cache, or restore from seed, rescan_bc, etc.

**Comment by moneromooo-monero** [comment]
Re-reading this, I see:

> 'amount' => '0.01314010',

Maybe the software you're feeding this to convert, but monero expects a canonical number of atomic units, not a floating point value.

**Comment by moneromooo-monero** [comment]
Is it till happening with current master or 0.13.x.y ?

**Comment by moneromooo-monero** [comment]
ping

**Comment by moneromooo-monero** [comment]
Works here. Reopen if it still happens with master, and without the extra layer you're using.

+invalid
