### ISSUE TITLE
couldn't find zmq.hpp (FreeBSD)

### ISSUE THREAD

**Issue by monerorus** [monero-project/monero#3644]
If you have error about zmq on FreeBSD while building from source, then you need install port **net/cppzmq**.  
Where is few ports about zmq(net/czmq, net/libzmq3, net/libzmq4 and etc.), but you need just **net/cppzmq**
Tested on FreeBSD 10.3

**Comment by moneromooo-monero** [comment]
I'm not sure what the bug is here.
If you're reporting which exact package is needed for FreeBSD, then there is a list in README.md which gives that list for some OSes, and you could add FreeBSD to the list along with the exact packages for each dep.

**Comment by monerorus** [comment]
Are you about PR changes in README.md file?
You right, this is not a bug issue, just for info.
