### ISSUE TITLE
After create new address, pools not accept this address

### ISSUE THREAD

**Issue by Ales999** [monero-project/monero#3654]
Hello!
My primary address started with 42... and good using all pools.
After upgrade wallet to 'Lithium Luna', create new address.
New address started with 84... and this address not valid, example for pool supportxmr.com:
"error: Invalid payment address provided"
Why ? 
Today add new address, this started with 86...
It's normal ?

PS Using MAC OS 10.12.6, GUI version, and remote daemon.

**Comment by moneromooo-monero** [comment]
The pools aren't maintained here. If you want them to support subaddresses, file a bug in their own repos. I'm not sure which are the best maintained versions, but https://github.com/zone117x/node-cryptonote-pool is the original repo for the main pool software.

**Comment by Ales999** [comment]
Ah, these are subaddresses. Understood thanks. Then close this.
