### ISSUE TITLE
After v0.12 upgrade, wallet RPC transfer calls sometimes return an empty response

### ISSUE THREAD

**Issue by solidus1** [monero-project/monero#3655]
After upgrading to v0.12, with get_tx_key set to true and mixin set to 6, transfers out are generally succeeding, but approximately 1 of 4 transfer RPC calls are returning an empty response. Without a txid clients are unable to determine whether a transfer was successful.

Running rescan spent and sweep unmixable on our wallet showed no improvement.

**Comment by stoffu** [comment]
Does the daemon print anything in response to that failed transfer RPC?

**Comment by moneromooo-monero** [comment]
Are you sure it's not a timeout from the wallet side ?
How much time does the call take when it "return[s] an empty response" ?

**Comment by solidus1** [comment]
As slow as it sounds, the client timeout was set to 120 seconds, but upping that value considerably seems to be avoiding the issue now

**Comment by moneromooo-monero** [comment]
Great. #3584 should help for some speedup too. It'll be made a lot faster by caching in the db in the future.

**Comment by moneromooo-monero** [comment]
And that's merged now, so I'll call this fixed. Please reopen if you're still seeing it after that.

+resolved
