### ISSUE TITLE
Blockhain rollback

### ISSUE THREAD

**Issue by khelle** [monero-project/monero#3669]
When using utility of `monero-blockchain-import --pop-blocks=X` is it needed to clean any additional stuff for wallets data? Or does it clean both full-node and rpc-wallet info? My case is that I received some payments on altchain and hope the rollback will flush wallet info on this invalid payments as well. Will it?

**Comment by moneromooo-monero** [comment]
It will not by itself. Notice you don't give it any wallet password :)
However, when the wallet refreshes and reorgs from that daemon, it *should* do this. I don't think it's tested a lot with large reorgs, but if it fails you can always delete the cache.

**Comment by khelle** [comment]
So it should reorganize the data itself, but there is possibility to have wrong cache. Ok, thanks for answer. I checked the transfers database and seems the cache has been also cleared. My wallet do not report altchain txs anymore.
