### ISSUE TITLE
monero-wallet-rpc: get_transfers does not show transactions from sub-accounts

### ISSUE THREAD

**Issue by mmorrell** [monero-project/monero#3678]
I sent Monero to a sub-account. During/after the blockchain confirmations, I am unable to see the transaction in the output of get_transfers API call in monero-wallet-rpc (all params set to true).

It appears that get_transfers only returns incoming transfers to the main account.

**Comment by krtschmr** [comment]
i can confirm.

**Comment by moneromooo-monero** [comment]
Did you set account_index to whatever you want to get ?

**Comment by mmorrell** [comment]
Thanks @moneromooo-monero . you are right again. The documentation site was out of date which was missing some of the parameters:

`      bool filter_by_height;
      uint64_t min_height;
      uint64_t max_height;
      uint32_t account_index;
      std::set<uint32_t> subaddr_indices;
`

I'll look into getting the documentation site updated.
