### ISSUE TITLE
monero-wallet-rpc: Add sub-address parameters to make_integrated_address API

### ISSUE THREAD

**Issue by mmorrell** [monero-project/monero#3679]
Currently, the "make_integrated_address" API in monero-wallet-rpc only generates an integrated address for the main account (at address_index 0). 

There should be a version of "make_integrated_address" which can work on sub-addresses. Such as make_integrated_address(address_index) and/or make_integrated_address(address).

This could be done adding by optional parameters to the existing make_integrated_address API.

e.g.

```
{
	"jsonrpc":"2.0","id":"0",
	"method":"make_integrated_address",
	"params": {
		"address_index": 3
	}
}
```

**Use case:** User wants to track individual payments to each subaddress.

**Comment by moneroexamples** [comment]
You mean making integrated sub-addresses? If so, this has been discussed already and the idea of integrated sub-addresses has been dropped. 

https://github.com/monero-project/monero/pull/2056#issuecomment-318844037

**Comment by krtschmr** [comment]
subadresses don't have payment IDs, or am i wrong?

**Comment by moneromooo-monero** [comment]
Subaddresses are supposed to obsolete payment ids.

**Comment by mmorrell** [comment]
Fair enough. I'll look into creating an issue for some first-class subaccount support (such as in the "transfer" API), if it is warranted. Thanks for looking into this.
