### ISSUE TITLE
build help for ubuntu 16.04 

### ISSUE THREAD

**Issue by kenken64** [monero-project/monero#3688]
[ 80%] Linking CXX executable unit_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1205: recipe for target 'tests/unit_tests/unit_tests' failed

**Comment by dEBRUYNE-1** [comment]
Your error message explains how to resolve this issue:

    against `.rodata' can not be used when making a shared object; recompile with -fPIC

**Comment by kenken64** [comment]
[ 63%] Linking CXX executable net_load_tests_clt
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/net_load_tests/CMakeFiles/net_load_tests_clt.dir/build.make:128: recipe for target 'tests/net_load_tests/net_load_tests_clt' failed
make[3]: *** [tests/net_load_tests/net_load_tests_clt] Error 1
make[3]: Leaving directory '/media/kenneth/b13ae9f7-5727-4bc0-94fe-77d72079f2ee/monero/build/release'
CMakeFiles/Makefile2:4625: recipe for target 'tests/net_load_tests/CMakeFiles/net_load_tests_clt.dir/all' failed
make[2]: *** [tests/net_load_tests/CMakeFiles/net_load_tests_clt.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/media/kenneth/b13ae9f7-5727-4bc0-94fe-77d72079f2ee/monero/build/release'
[ 63%] Built target wallet
make[3]: Leaving directory '/media/kenneth/b13ae9f7-5727-4bc0-94fe-77d72079f2ee/monero/build/release'

**Comment by kenken64** [comment]
yeah -fPIC where to pass this argument ? make -fPIC

**Comment by kenken64** [comment]
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-fPIC

**Comment by aventadorm** [comment]
Was this an issue with googletest being compiled without -fPIC ?
