### ISSUE TITLE
How to run monero-wallet rpc?

### ISSUE THREAD

**Issue by zeshanvirk** [monero-project/monero#3693]
I downloaded monero-cli for windows, i double clicked monerod, when its synchronized i double clicked moneo-wallet-cli, i created wallet, then i clicked monero-wallet-rpc, it gets closed within a second, i tried to hit wallet rpc methods using postman but could not get any response, but when i hit daemon rpc methods which are on 18081 as per official documentation, it gave me response... what i am doing wrong while accessing wallet-rpc methods?

**Comment by moneromooo-monero** [comment]
You need to at least give it the port to which to bind. Also add --wallet-file /path/to/wallet/cache, maybe auth options if necessary.
There are instructions in the README.md file, and the --help option lists all options.
Run from the terminal rather then clicking on things if you want to be able to read the error messages before windows takes them away.

**Comment by mattcode55** [comment]
> then i clicked monero-wallet-rpc, it gets closed within a second

That means it isn't running :)

Try running it with command prompt, you should get a help message showing all of the switches and parameters you can pass to start it.

You probably want something like `monero-wallet-rpc.exe --wallet-file my-wallet --prompt-for-password --rpc-bind-port 16969`. Remember to use a different port for the daemon RPC and wallet RPC.

**Comment by zeshanvirk** [comment]
i tried the solution but my wallet stuck at a point Starting wallet RPC server... how can i resolve this issue? as i saw an issue related to this but didn't got any help from that issue.

**Comment by moneromooo-monero** [comment]
Stuck how ? Doesn't answer to RPC ? That message is the one that happens after init is done, when the wallet starts listening to RPC, so if it's stuck there, it may be some network problem.

**Comment by zeshanvirk** [comment]
Solved, It was giving unauthorized access which is solved "--disable-rpc-login"

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by josephnicholas** [comment]
Hmm… If you can post the command here it would be great. But just to make sure, did you run the wallet rpm this way `./aeon-wallet-rpc --wallet-file {wallet-file} --prompt-for-password --rpc-bind-port {port} —disable-rpc-login`? The port should be different from the daemon port.
