### ISSUE TITLE
Possibly memory leak in slow-hash.c on Windows

### ISSUE THREAD

**Issue by aivve** [monero-project/monero#3694]
Please review, memory leak is possible here:
https://github.com/monero-project/monero/blob/8fdf645397654956b74d6ddcd79f94bfa7bf2c5f/src/crypto/slow-hash.c#L527

The correct expression suggested: `VirtualFree(hp_state, 0, MEM_RELEASE);`

It was reported by @mgurgev here: https://github.com/seredat/karbowanec/issues/41, his proposal fixes memory leak.

He refers to: https://msdn.microsoft.com/en-us/library/windows/desktop/aa366892(v=vs.85).aspx

**Comment by hyc** [comment]
Looks like you're right, according to the M$ docs.

**Comment by moneromooo-monero** [comment]
+resolved
