### ISSUE TITLE
Monero GUI on Win 10 64 needs computer reboot after opening then closing the application

### ISSUE THREAD

**Issue by Simplexletalis** [monero-project/monero#3699]
Could not find a similar issue on this, so thought I'd open a new one.

After opennig the Monero wallet and using it, then closing and trying to re-open the GUI, the application crashes right away.

My tests were on Windows 10 x64. A reboot resolves the problem.

**Comment by moneromooo-monero** [comment]
Please file on the GUI repo: https://github.com/monero-project/monero-core
