### ISSUE TITLE
Mainnet wallet cannot be oppend as testnet wallet

### ISSUE THREAD

**Issue by zeshanvirk** [monero-project/monero#3715]
I ran monerod by typing command in cmd **"./monerod --testnet"**, it syncs the whole blockchain and i started monero-wallet-cli using command **"./monero-wallet-cli set_daemon 28081"** and i created a wallet, then i tried to run the rpc wallet but got error mainnet wallet cannot be oppend as testnet wallet. My command is 
**"./monero-wallet-rpc --testnet --wallet-file file-name --password ***** --rpc-bind-port 28090**

**Comment by moneromooo-monero** [comment]
You clearly ran monero-wallet-cli without --testnet above. Or is that a typo and you did use --testnet ?

**Comment by zeshanvirk** [comment]
Fixed, i forgot to run cli too with --testnet, i didn't read it anywhere to run the cli too on testnet. running cli too on testnet works for me. Thanks

**Comment by moneromooo-monero** [comment]
+invalid
