### ISSUE TITLE
Static builds fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [monero-project/monero#3728]
This recipe fails:

```
git clone --recursive https://github.com/monero-project/monero
cd monero && git submodule init && git submodule update
make debug-static-all # fails, says it requires -fPIC flag
rm -r build
make release-static # fails, also wants -fPIC
```

While you guys verify this issue, can you please tell me why you're not using CI on github? I see CI flags on github's readme.md, but most of them fail. I tried to contribute to monero and tried to build it in Qt Creator (which supports cmake out of the box)... and it was mission impossible. I always got undefined reference to `libblockchain` when compiling in debug mode. Apparently, this dependency path is not specified in reference to build directory... I don't know... I'm guessing here because Qt Creator uses shadow directories (directories at the same level) for building. Can someone try this and verify too?

**Comment by moneromooo-monero** [comment]
Then build whatever it's telling you about with -fPIC. We can't do that for you.

**Comment by moneromooo-monero** [comment]
Or build shared (which is the default). Shared libraries are always built with -fPIC so you don't have to rely on your distribution to be nice.

**Comment by TheQuantumPhysicist** [comment]
> You're missing the point. monero builds with -fPIC. It just needs its deps to also be built with -fPIC (like, say, boost, openssl, etc).

I guess you're right. There's nothing to be done from your side. Apologies for the incorrect report.

About CI. I understand the reports are overwhelming. But maybe just look whether it passed or not, and if doesn't pass, then maybe something is wrong. Just a friendly suggestion :-)

Cheers!

**Comment by moneromooo-monero** [comment]
Yes, you're correct, but there are so many false positives at some point you just want to strangle that thing till it shuts up :P

**Comment by TheQuantumPhysicist** [comment]
This probably means that many contexts are mixed together. I don't know if this is the case for Monero, just guessing here. For example, I believe that mixing unit-tests with build tests is a bad idea exactly for this reason. It gets overwhelming very quickly.
