### ISSUE TITLE
Address doesnt appear to be valid

### ISSUE THREAD

**Issue by zeshanvirk** [monero-project/monero#3754]
I ran monerod on testnet using monerod --testnet, then i ran monero-wallet-cli --testnet, and then i ran the wallet-rpc... I got an address of a wallet which is 9toKxFCzLmzSVHwEgqRPeJj8HVyk6knyhQLgh4qLxnBVHsDpDHPwGNNfvAKYaoDsuG3SBzUbrLZEHetLUsqZbAgPKX31ugM.

i tried to get some monero using http://monerofaucet.info but it gave me error of Address doesnt appear to be valid. What am i doing wrong in generating a testnet address of a wallet?

**Comment by moneromooo-monero** [comment]
The address is valid.

**Comment by zeshanvirk** [comment]
Then can you send me some testnet balance?

**Comment by stoffu** [comment]
Sent 1.23 in `2bb0696950bb8039aff68cc7b4972fbc67b4bf0ef3db5a1db9c75ad3bb878ade`

**Comment by moneromooo-monero** [comment]
+invalid
