### ISSUE TITLE
[ 96%] Linking CXX executable unit_tests error

### ISSUE THREAD

**Issue by nicebbs** [monero-project/monero#3760]
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1206: recipe for target 'tests/unit_tests/unit_tests' failed
make[3]: *** [tests/unit_tests/unit_tests] Error 1

**Comment by dEBRUYNE-1** [comment]
Your logs are fairly explanatory:

>recompile with -fPIC

**Comment by moneromooo-monero** [comment]
For libgtest, you can also uninstall the system one, monero can use its internal one (which it builds with -fPIC).

+invalid

**Comment by calidion** [comment]
@moneromooo-monero 
any detailed steps?
