### ISSUE TITLE
Run Monero Daemon as service

### ISSUE THREAD

**Issue by 5-digits** [monero-project/monero#3777]
How to run Monero Daemon as service ?

each time when start running the node i make it like this
`./monerod`
 when type monerod it doesn't works, so I will necessarily execute it like a linux executable
./app because i'm using ubuntu 16
but when hit [ CTRL + C ] every thing is stopped 
So how to run it like Zcash and bitcoin just by calling ( bitcoind --testnet for example )

**Comment by moneromooo-monero** [comment]
You mean make it fork like a daemon ? Add --detach.

**Comment by gene-telligent** [comment]
If you're on Ubuntu and want to run it as a proper service managed by systemd, I'd also recommend using this https://github.com/monero-project/monero/blob/master/utils/systemd/monerod.service as a starting point!

**Comment by Low-power** [comment]
However the forking model is not a recommended service type in systemd; it is better to add an option to stop the program from reading from the stdin, so it will suitable to run as a daemon without fork(2) and detach.

**Comment by 5-digits** [comment]
Doesn't work properly 
```
● monerod.service
   Loaded: loaded (/etc/systemd/system/monerod.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-05-09 10:09:37 MDT; 6s ago
 Main PID: 11376 (monerod)
   CGroup: /system.slice/monerod.service
           └─11376 /home/Dragon/monerohss/monero-v0.12.0.0/monerod --testnet --config-file /home/Dragon/monerohss/monero-v0.12.0.0/monero.conf

May 09 10:09:42 server monerod[11376]: 2018-05-09 16:09:42.080            7f975c29c740        INFO         global        src/cryptonote_core/cryptonote_core.cpp:525        Loading checkpoints
May 09 10:09:42 server monerod[11376]: 2018-05-09 16:09:42.080            7f975c29c740        INFO         global        src/daemon/core.h:92        Core initialized OK
May 09 10:09:42 server monerod[11376]: 2018-05-09 16:09:42.080            7f975c29c740        INFO         global        src/daemon/rpc.h:74        Starting core RPC server...
May 09 10:09:42 server monerod[11376]: 2018-05-09 16:09:42.080        [SRV_MAIN]        INFO         global        src/daemon/rpc.h:79        core RPC server started ok
May 09 10:09:42 server monerod[11376]: 2018-05-09 16:09:42.082        [SRV_MAIN]        INFO         global        src/daemon/p2p.h:78        Starting p2p net loop...
May 09 10:09:42 server monerod[11376]: 2018-05-09 16:09:42.082        [SRV_MAIN]        INFO         global        src/daemon/p2p.h:80        p2p net loop stopped
May 09 10:09:43 server monerod[11376]: 2018-05-09 16:09:43.090        [SRV_MAIN]        INFO         global        src/daemon/rpc.h:84        Stopping core RPC server...
May 09 10:09:43 server monerod[11376]: 2018-05-09 16:09:43.091        [SRV_MAIN]        INFO         global        src/daemon/daemon.cpp:189        Node stopped.
May 09 10:09:43 server monerod[11376]: 2018-05-09 16:09:43.091        [SRV_MAIN]        INFO         global        src/daemon/rpc.h:96        Deinitializing core RPC server...
May 09 10:09:43 server monerod[11376]: 2018-05-09 16:09:43.092        [SRV_MAIN]        INFO         global        src/daemon/p2p.h:90        Deinitializing p2p...

```
the Monerod service file :: 

```
testnet=1
rpc-bind-ip=127.0.0.1
rpc-bind-port=18556
p2p-bind-port=18555
p2p-bind-ip=127.0.0.1
rpc-login=user:password
```
and when connecting to the wallet through the (monero-wallet-cli)


 ./monero-wallet-cli --testnet
 

> Error: wallet failed to connect to daemon: http://localhost:28081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or change the daemon address using the 'set_daemon' command.

**Comment by moneromooo-monero** [comment]
You don't seem to be using --detach as I said above.

**Comment by 5-digits** [comment]
i'm also trying with --detach flag but the result is the same  
```
ExecStart=/home/Dragon/monerohss/monero-v0.12.0.0/monerod --testnet   --config-file /home/Dragon/monerohss/monero-v0.12.0.0/monero.conf \
   --detach
```

**Comment by papadave66** [comment]
you can run monerod with ` --non-interactive ` .and you can ctrl+z  +bg to run in background

**Comment by baryluk** [comment]
With systemd you can leave it attached (it is actually even better), and even make it output log data to stderr or stdout, systemd will take care of it. Do not run it as root tho, but normal your account or separate user.

If you want easier route, just use crontab, either `crontab -e` and then add:
```text
@reboot cd /home/xyz/monero-directory && ./monerod --options --options --detach
```

Or if you want to make it smarter and automatically start it if it crashes, make a separate script that checks if it is started and if not start it, and then run it from crontab every 5 minutes.

**Comment by moneromooo-monero** [comment]
No monero bug here.

+invalid
