### ISSUE TITLE
 List of all transactions against wallet with payment id..

### ISSUE THREAD

**Issue by zeshanvirk** [monero-project/monero#3781]
I've integrated monero wallet in a web, i ran monero full node but i'm unable to get list of all transactions against my wallet address with payment_id too in responce. i'm using incoming_transfers method and passing transfers type: all to get list of all with payment id, but i receive response without payment id like this
```

"transfers": [
 { 
"amount": 1230000000000, 
"global_index": 384388, "key_image": "", 
"spent": false, "subaddr_index": 0, "tx_hash": "2bb0696950bb8039aff68cc7b4972fbc67b4bf0ef3db5a1db9c75ad3bb878ade", 
"tx_size": 160 
}
 ]
```

**Comment by moneromooo-monero** [comment]
That's because you're using the wrong RPC. Use get_transfers, not incoming_transfers. Where did you find this reference to incoming_transfers to use with type:all ?

**Comment by zeshanvirk** [comment]
and get_transfers method returning empty array, shouldn't the incoming transfers be returned using get_transfer too? 

using this code

 curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_transfers","params":{"pool":true}}' -H 'Content-Type: application/json'

**Comment by moneromooo-monero** [comment]
Ah, yes, this is also valid, but "all" here refers to spent and unspent. I got confused.
So you want get_transfers, and set booleans to true for whatever type of tx you want: in. out, pool, pending...

**Comment by zeshanvirk** [comment]
which transactions are pool transactions?

**Comment by cryptochangements34** [comment]
Pool transactions are unconfirmed transactions in the mempool

**Comment by stoffu** [comment]
Pool is incoming, pending is outgoing.

**Comment by moneromooo-monero** [comment]
+invalid
