### ISSUE TITLE
2 wallets 1 local node; transfer problems

### ISSUE THREAD

**Issue by Staz1st** [monero-project/monero#3795]
I made 2 different xmr-wallets using same local node. 
Wanted to transfert all xmr from wallet1 to wallet2 but getting following errorcode (dutch content says "transaction error") 

> Transactie kan niet worden aangemaakt: no connection to daemon. Please make sure daemon is running.

 But daemon is running, wallet is correctly synced. Running and syncing of both wallets seem to work fine. What am I missing? Is there another way to transfer between 2 wallets on same blockchain.db?

**Comment by moneromooo-monero** [comment]
Use current release-0.12 code, it's likely a timeout which was fixed there.

**Comment by Staz1st** [comment]
I'm sorry I should have mentioned i'm using _monero-gui-v0.12.0.0_
Which I think is the version you mention

**Comment by dEBRUYNE-1** [comment]
Moneromooo means that you ought to compile the release-v0.12 branch.

**Comment by Staz1st** [comment]
updated files in GUI-dir to v0.12. Still same error.

**Comment by moneromooo-monero** [comment]
Does "updated files in GUI-dir to v0.12" mean you're now using the current release-0.12 branch code ? It is not the same as a v0.12.0.0 tag nor the prevuilt 0.12.0.0 binaries.

**Comment by Staz1st** [comment]
I took latest release: **v0.12.0.0 - c29890c** and used _monero-win-x64-v0.12.0.0.zip_ to extract in the GUI-v0.12.0.0 map. Do you mean I used v0.12.0.0 tag? 
I think you mean this page [[https://github.com/monero-project/monero/tree/release-v0.12](https://github.com/monero-project/monero/tree/release-v0.12)] which means I have to compile of which I have very little experience.

**Comment by moneromooo-monero** [comment]
Yes, you used that tag, which is not what I asked. If you can't/won't build, then you can also pluck a build from the build.getmonero.org site, or wait for a new release.

**Comment by Staz1st** [comment]
Problem solved itself...
