### ISSUE TITLE
 A single payment id is allowed per transaction

### ISSUE THREAD

**Issue by zeshanvirk** [monero-project/monero#3805]
I'm trying to send some tokens to an integrated address with a payment id but getting this error 

`  "code": -5,
    "message": "A single payment id is allowed per transaction"`

if i remove the id, transaction done successfully, i'm using transfer method

**Comment by stoffu** [comment]
Just as the error message says. This is a restriction with the payment ID, not an error.

**Comment by el00ruobuob** [comment]
The integrated address includes a payment id. If you only use the integrated address and try not to add a second id is it working? From the OP I'll say yes.

**Comment by stoffu** [comment]
@el00ruobuob Ah that explains it.

**Comment by zeshanvirk** [comment]
yes if i not include the id it works, did the wallet itself adds the paymentID that is generated along with integrated address?

**Comment by iDunk5400** [comment]
Integrated addresses are addresses that integrate a (short) payment id.

From monero-wallet-cli:
```
[wallet 4BFQiD]: help integrated_address
Command usage:
  integrated_address [<payment_id> | <address>]

Command description:
  Encode a payment ID into an integrated address for the current wallet public address (no argument uses a random payment ID), or decode an integrated address to standard address and payment ID
```

**Comment by stoffu** [comment]
You can use this tool https://xmr.llcoins.net/addresstests.html to see the short payment ID integrated in an integrated address.

**Comment by dEBRUYNE-1** [comment]
+resolved
