### ISSUE TITLE
monero-wallet-cli frozen after confirming transfer command

### ISSUE THREAD

**Issue by vertangelx** [monero-project/monero#3813]
Tried to use `monero-wallet-cli`(Monero 'Lithium Luna' (v0.12.0.0-master-release)
) on my Ubuntu system to send some XMR out of my wallet.

However after confirming that no payment id is included, it just freezes there.

    [wallet 46yPyn]: transfer unimportant 47SQNwzYsD5Pfry6CtpNcFfwWp3u5hNQ9PhrYkVx8WRHToS81ifwgNuLdudTUWorQH6R5aozAPqXXXXXXXXXXXXXXXXXXXX 0.013
    Wallet password:
    No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y

Is something wrong?

**Comment by moneromooo-monero** [comment]
Probably a timeout with a slow RPC. Try with https://github.com/monero-project/monero/pull/3815

**Comment by athenawisdoms** [comment]
@moneromooo-monero I am experiencing the same slowness when doing a transfer from both monero-wallet-cli and monero-wallet-rpc.

Do you mind elaborating on how we can make use of issue #3815 to solve the slowness/timeout?

Thank you so much

**Comment by moneromooo-monero** [comment]
You just apply the commit in that PR.

git fetch origin pull/3815/head:PR3815
git cherry-pick PR3815

That will apply the commit to your current branch. You may want to switch branches to a temporary one first if you're on master.

**Comment by athenawisdoms** [comment]
@moneromooo-monero Tried your instructions and re-compiled the binaries after applying the new PR3815 commits to a new branch. 

Now when I try to send some funds `transfer unimportant xxx 0.1 yyy`, it prompts for wallet password, then nothing happens and I get sent back to the wallet's yellow command prompt. Waited for over 20 minutes and running the command `balance` shows the same locked and unlocked balance.

Did I do something wrong?

**Comment by athenawisdoms** [comment]
@moneromooo-monero Tried your instructions and re-compiled the binaries after applying the new PR3815 commits to a new branch.

Now when I try to send some funds transfer unimportant xxx 0.1 yyy this time with payment ID, it prompts for wallet password, then nothing happens just like before...

**Comment by moneromooo-monero** [comment]
Yes. It'll be fixed later.

**Comment by moneromooo-monero** [comment]
Also, I updated 3815 to add another case, make sure you're running the current one.

**Comment by athenawisdoms** [comment]
`segregation_height = 0`

Tried sending again today (without your new update to PR3815) and it appears faster. Not sure what was the difference compared to the slow one yesterday when using  PR3815 fix.

**Comment by moneromooo-monero** [comment]
The cache is now in 0.12.2.0, it should be fast unless you override segregation height. If you still get slowness with the default, please reopen.

+resolved

**Comment by blankclemens** [comment]
On Windows 10, using 0.12.2.0 I experience the same: The moment I answer the payment id question (with Y), the cli freezes.
