### ISSUE TITLE
How to make a original transaction ?????

### ISSUE THREAD

**Issue by liyanhrxy** [monero-project/monero#3818]
In the offical developer guides ,I saw the method `sendRawtranstion`,so  I want to know how to use it ?? How can I get the parameter for it ???

**Comment by moneromooo-monero** [comment]
https://getmonero.org/resources/developer-guides/daemon-rpc.html#sendrawtransaction

**Comment by stoffu** [comment]
You can generate hex strings of raw txes by:

- `monero-wallet-rpc`: transfer command with `do_not_relay` and `get_tx_hex` options (see https://getmonero.org/resources/developer-guides/wallet-rpc.html#transfer)
- `monero-wallet-cli`: launch the program with `--do-not-relay` flag, which causes the `transfer` command to save the raw tx hex string to `raw_monero_tx`

**Comment by liyanhrxy** [comment]
What is  the `raw_monero_tx` means ???  If I have to sign it ,if not when to sign ??

**Comment by stoffu** [comment]
@liyanhrxy 

> What is the `raw_monero_tx` means ??? If I have to sign it ,if not when to sign ??

It's a file saved to the current directory, just like other kind of files such as key images and unsigned transactions.

**Comment by liyanhrxy** [comment]
> It's a file saved to the current directory, just like other kind of files such as key images and unsigned transactions.
It seems taht I have got your idea !!! But  I want to know when to make a signature ???,so I can make a 
transaction offline ，and then I can broadcast it  to online-node anywhere

**Comment by liyanhrxy** [comment]
> It's a file saved to the current directory, just like other kind of files such as key images and unsigned transactions.

I have got your idea ,but I want to make a transaction offline like bitcoin `creatRawtractions`--`sign`
 and then I can call `sendRawtractions` anywhere ???

**Comment by stoffu** [comment]
There’s also the cold signing feature using the watch-only wallet. I don’t know what you want to do and I’m not familiar with bitcoin.

**Comment by liyanhrxy** [comment]
anyway,thank you so much

**Comment by jtgrassie** [comment]
@liyanhrxy 
> I have got your idea ,but I want to make a transaction offline like bitcoin creatRawtractions--sign
and then I can call sendRawtractions anywhere ???

@stoffu answered the [first part](https://github.com/monero-project/monero/issues/3818#issuecomment-389777554) of this (creating the raw tx) and @moneromooo-monero  answered the [second part](https://github.com/monero-project/monero/issues/3818#issuecomment-389772476) (for the sending).

In future, as @moneromooo-monero pointed out, use other channels for help / support. This is a bug tracker.

**Comment by moneromooo-monero** [comment]
+invalid
