### ISSUE TITLE
Monero mining

### ISSUE THREAD

**Issue by wmoreno3** [monero-project/monero#3850]
`monero-cli-0.12.0.0_2
monerod status
Height: 1579519/1579519 (100.0%) on mainnet, mining at 50 H/s, net hash 435.67 MH/s, v7, up to date, 9(out)+0(in) connections, uptime 1d 9h 47m 21s`

I am minig monero, but how I can see my minering ? Where goes monero that I am minering?

**Comment by moneroexamples** [comment]
>  Where goes monero that I am minering?

To the address you specified or your wallet from which you are mining.

**Comment by moneromooo-monero** [comment]
This is a bug tracker.

+invalid
