### ISSUE TITLE
Node getting stuck

### ISSUE THREAD

**Issue by emesik** [monero-project/monero#3860]
My node which I use to get stats from to create [mempool graphs](https://pooldata.xmrlab.com/) apparently got stuck and suffered a mempool swell.

After restarting, it synced up blocks and cleared the pool. [This picture](https://imgur.com/a/bnqj72J) shows the mempool swell and cleanup after restart.

[Here on reddit](https://www.reddit.com/r/Monero/comments/8m0lao/mempool_is_swelling/dzjvbej/) I made a hypothesis on what could have happened, but it's not supported by log analysis, just a guess.

The node is running 0.12.0.0

Logs covering that period, including the restart: [1](http://salaban.info/~emes/monero.1.log.gz) and [2](http://salaban.info/~emes/monero.2.log.gz)

**Comment by moneromooo-monero** [comment]
Believed fixed in 0.12.1.0.

**Comment by moneromooo-monero** [comment]
+resolved
