### ISSUE TITLE
monero-wallet-rpc: Add account_index parameter to query_key API

### ISSUE THREAD

**Issue by mmorrell** [monero-project/monero#3864]
Currently the "query_key" API only returns the mnemonic/viewkey/spendkey of the main account (account index 0).

I think there would be value in adding a parameter for "account_index" so that you can query the keys of subaccounts, if this is possible.

**Comment by stoffu** [comment]
That does not any make sense. All subaddresses are derived solely from the original view/spend keys and the index. Finding money transfers to subaddresses is handled by the wallet internal code. There is absolutely no need to present secret keys corresponding to subaddresses to the user.
