### ISSUE TITLE
Testnet: Failed to submit a cold signed tx due to double spend error

### ISSUE THREAD

**Issue by zhongqiuwood** [monero-project/monero#3868]
Is there any one encounter <Error: Reason: double spend, invalid input> by cold transaction signing?

It happend to me on **testnet** after I doing below(all done by the monero-wallet-cli):

-  I set up a cold wallet and a hot wallet that are a pair for the same account. And run the 2 wallets on 2 compters. The cold wallet has no Internet access.
-  Produce <unsigned_monero_tx> file by the hot wallet(a view only wallet that has only secret view key) by command [transfer priority $TARGET_ADDRESS $AMOUNT]
-  Copy the <unsigned_monero_tx> to the cold wallet(generated by secret spend key) computer.
-  Sign the <unsigned_monero_tx> by command [sign_transfer], and then <signed_monero_tx> file produced by the cold wallet.
-  Copy the <signed_monero_tx> to the hot wallet computer.
-  Use hot wallet to send the tx to the network by command [submit_transfer]
-  Then I was told it has an error double spend :

        ```
        Loaded 1 transactions, for 17.000000000000, fee 0.152975640000, sending 0.100000000000 to A1puKBLCKkdgB8D2LkGzQPYU8mYjVohwEgoAqcLKjQ2PCgAci6T5wMsVHhXekcPP7sEYqkR4KBGddAbErMTJhd737f9oAAD, 16.747024360000 change to 9u7McB2tQJQQbd2jrncdRW43m72Y5vbrQDt459FQB7SHbyCCnwuaBhSgvmdnQykqQecpguE8Csnms9nzoAK5QxzMGF75xqj, with min ring size 7, no payment ID. 5 key images to import.
        Error: transaction <6cb4e7b17bc13c830b4130f85de59711ea2ba1a2e4253f44cb9c2f7fcf184fcb> was rejected by daemon with status: Failed
        Error: Reason: double spend, invalid input
        ```
I did not run any command of below:
```
import_outputs
export_outputs
export_key_images
import_key_images
```

**Comment by stoffu** [comment]
You generally need to run those 4 commands in order for the view only wallet to correctly identify spent and unspent outputs. Otherwise, the view only wallet can potentially try to spend outputs that appear unspent but are spent in reality, causing the double spend error.

**Comment by zhongqiuwood** [comment]
@stoffu Many thanks

**Comment by zhongqiuwood** [comment]
Hi @stoffu, one more question:

The 4 operations **export_outputs/import_outputs/export_key_images/import_key_images** on hot & cold wallets handle **all the history outputs** of the account every time before making a valid cold sign.

It will take a very very long time if there are many outputs.

I am not sure if it is necessary that do them from the first transfer output of the account every time. 

Is there a way that only does the 4 operations on **delta** outputs and can still make a valid cold sign afterwards? 

So that we do not waste time on the outputs already handled.

**Comment by stoffu** [comment]
@zhongqiuwood 
There's a lot of redundancy in the import/export process, yes. Your idea of incremental update sounds reasonable. Please open a new ticket and describe your proposal.

**Comment by stoffu** [comment]
Ah you already did it in #3905. Thanks!
