### ISSUE TITLE
Failed to send funds to another address via RPC

### ISSUE THREAD

**Issue by i3bitcoin** [monero-project/monero#3869]
I'm getting this error while trying to send funds to another address.
Any suggesions how can it be fixed?

[RPC0]  ERROR   wallet.wallet2  src/wallet/wallet2.cpp:6233     !real_out_found. THROW EXCEPTION: error::wallet_internal_error

[RPC0]  WARN    net.http        src/wallet/wallet_errors.h:794  /root/monero/src/wallet/wallet2.cpp:6233:N5tools5error21wallet_internal_errorE: Daemon response did not include the requested real output

**Comment by moneromooo-monero** [comment]
Run both daemon and wallet with --log-level 2, and post the logs to fpaste.org or pastebin.mozilla.org or paste.debian.net. The wallet log will contain some private info, so you may want to set a password on fpaste.org and PM it to me on Freenode (moneromooo).
Also post the commit hash of the code you are running and the RPC command and parameters you are using.

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/monero/pull/3882

**Comment by dEBRUYNE-1** [comment]
+resolved
