### ISSUE TITLE
monero-wallet-rpc sometimes freezes.

### ISSUE THREAD

**Issue by onodera-punpun** [monero-project/monero#3870]
See title. I can no longer quit it using either `ctrl+c` or `pkill monero-wallet-rpc`. `pkill -9 monero-wallet-rpc` however works.

This started happening since 0.12.1.0.

**Comment by moneromooo-monero** [comment]
When it does this:
gdb /path/to/monero-wallet-rpc \`pidof monero-wallet-rpc\`
thread apply all bt

**Comment by onodera-punpun** [comment]
I want to provide more info, but it seems to happen at random. Ill try doing this.

**Comment by moneromooo-monero** [comment]
Any luck ?

**Comment by onodera-punpun** [comment]
I haven't run into this issue anymore, I'll  close it and re-open if it happens again.
