### ISSUE TITLE
Ask two questions about interactive protocol and operational principle of mining?

### ISSUE THREAD

**Issue by truelv** [monero-project/monero#3873]
1. what is the diffence and connection with this project and Xmrig or xmr-stak ? 
2. I can't find any help handbook about the details of interactive protocol between miner and the mining pool , could you give me some?
3. I also can't be sure about the details of mine's work?  The details I means is the each field of the interactive protocol and the operational principle of mining . 

I am a developer , so I can't do my job without catching the details of operational principle. Also I am not so familiar with English , so I can't understand complex explanation .

Hope for you reply ! Thanks Very Much ~~

**Comment by stoffu** [comment]
This is a bug tracker where your questions don't seem very suitable. Try asking on https://monero.stackexchange.com.

**Comment by truelv** [comment]
Sorry for that . I don't know the website you have mentioned before.

Thx a lot .
