### ISSUE TITLE
Wallet 1GB file size limit problem.

### ISSUE THREAD

**Issue by miningpoolhub** [monero-project/monero#3877]
This code blocks wallet file loading when file is bigger than 1GB
https://github.com/monero-project/monero/blob/master/contrib/epee/include/file_io_utils.h#L162

I can't launch wallet-rpc program as it exceeded 1GB already.
I just changed this numbers, compiled and working well but worried a bit with this issue.

Any idea for improving this part?
Maybe not using simple file read operation in one large buffer, but use file mapping would be better.

I think pool, exchange service will reach 1GB sooner or later.

**Comment by moneromooo-monero** [comment]
AFAIK this is safe, at least two others have done this, and no reports of anything falling over :)

In the future, the wallet cache will be a LMDB database, so this will be mooted.

**Comment by moneromooo-monero** [comment]
I'll fix this for now just for wallet caches.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3878 should do it (still building).

**Comment by miningpoolhub** [comment]
Great!
