### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by knkrth** [monero-project/monero#3885]
Hi, How can I generate this HEX Value for creating new coin & Is it random or it is the IP Address?
```
boost::uuids::uuid const NETWORK_ID = { {
      0x12 ,0x30, 0xF1, 0x71 , 0x61, 0x04 , 0x41, 0x61, 0x17, 0x31, 0x00, 0x82, 0x16, 0xA1, 0xA1, 0x10
    } }; // Bender's nightmare
```

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help desk. However, there's info about doing this on monero.stackexchange.com.

+invalid

**Comment by knkrth** [comment]
Ok, Thanks.
