### ISSUE TITLE
Feature Request - Actual log rotation, better log management

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#3895]
The current log management is ..... ok. It now creates 100 MB files. If a node is left to run... for a while... you end up with literally a bajillion log files, so many that you need to use a special trick to delete them all because using bitmonero.log-* exceeds bash's whatever whatever.

Thus, if monerod is going to do logrotation, can it do it properly? E.g., only write 50 files, and then delete the old ones as new ones are written? And this could be tunable. Yes, I know, setting the logfile limit to 0 allows the logfile to grow as it used to and then the system logrotate can manage it properly, but i don't think the base behavior of monerod should be to balloon log files until there are so many files a user can't delete them easily.

**Comment by stoffu** [comment]
#3897

**Comment by moneromooo-monero** [comment]
+resolved
