### ISSUE TITLE
tx is not possible

### ISSUE THREAD

**Issue by axeoman** [monero-project/monero#3898]
Hi there! 
I need to automate sending funds, so I am using monero-wallet-rpc JSON-RPC API call "transfer" for that. But unfortunately after about 5 sending, API start returning error with text "tx not possible". Usually it disapears after half an our.
Anyone have a clue why is it happening?
Thank you.

**Comment by moneromooo-monero** [comment]
You'll get more info if you run "set_log 1" in monerod.
In any case, 0.12.2.0 is out soon (tomorrow probably) and fixes a few issues with sending.

**Comment by dEBRUYNE-1** [comment]
Posted this on reddit:

>By default, outputs are locked for 10 blocks. Note that this includes change outputs which are sent back to your own wallet. Thus, if you're sending transactions in rapid succession, eventually all your outputs will be locked. A quick workaround is splitting up your outputs into smaller outputs and sending them to yourself. For instance, let's say you have an output of 1 XMR and want to split it up into 10 0.1 outputs. You'd have to execute the following command.

>    transfer <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1 <own-address> 0.1

>Hopefully this clears up some confusion.

**Comment by axeoman** [comment]
Thank you very much for the information, I think I got it.
