### ISSUE TITLE
Error building on Ubuntu 18.04

### ISSUE THREAD

**Issue by mkanakis** [monero-project/monero#3901]
Hey, 

I am trying to build monero on Ubuntu 18.04 and I get the following error:

![virtualbox_ubuntu 18 04_01_06_2018_14_41_30](https://user-images.githubusercontent.com/7622185/40857890-d8d28606-65dc-11e8-9be3-ebdd5f7c5c57.png)

The dependencies are installed as supposed to.
Anyone else having this kind of problem?

Thanks.

**Comment by moneroexamples** [comment]
No problems for me.

What version are you compiling? Current monero master branch, or previous releases?

**Comment by daniel-levin** [comment]
I suggest correcting the system clock first, to see if that makes any difference.
What about your version of gcc? 

Have you made sure to run ``git submodule update --init``?

**Comment by moneromooo-monero** [comment]
It looks like a compiler problem.
If no answer is given soon to the questions above, I'll close as invalid since it works for others.

**Comment by mkanakis** [comment]
Sorry for the late response.
Problem is solved, there was an incosistency with some of the dependencies and their versions.
Thanks.
