### ISSUE TITLE
Taking too long to make a cold sign due to export_outputs file size is big if there are too many outputs.

### ISSUE THREAD

**Issue by zhongqiuwood** [monero-project/monero#3905]
The 4 operations export_outputs/import_outputs/export_key_images/import_key_images on hot & cold wallets handle all the history outputs of the account every time before making a valid cold sign.

It will take a very very long time if there are many outputs.

I am not sure if it is necessary that do them from the first transfer output of the account every time.

Is there any way that only does the 4 operations on delta outputs and can still make a valid cold sign afterwards?

So that we do not waste time on the outputs already handled.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4720

**Comment by zhp1254** [comment]
dose the[ wallet rpc api](https://ww.getmonero.org/resources/developer-guides/wallet-rpc.html#export_outputs) has the params txid? 
the document show me the export_outputs has none params and return all outputs

**Comment by moneromooo-monero** [comment]
No, there is no txid parameter to export_outputs.
If you want to get help about monero, try #monero on Freenode. This is a bug tracker.

**Comment by selsta** [comment]
#4720 and #8179
