### ISSUE TITLE
Permission denied error for monero-blockchain-blackball

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero#3915]
Original post on StackExchange [here](https://monero.stackexchange.com/questions/8485/permission-denied-error-for-monero-blockchain-blackball).

I'm attempting to run the monero-blockchain-blackball utility in PureOS, and I'm running into a permission error.

I used the syntax to select the tool, then the Monero blockchain, then a forked blockchain (I'm using Monero v6 for testing). The syntax is described [here](https://monero.stackexchange.com/questions/8225/how-can-i-use-monero-blockchain-blackball-to-improve-my-privacy).

Upon running the command, I receive the following text:

[![Failed to create a transaction for the db: Permission denied][1]][1]

  [1]: https://i.stack.imgur.com/orfSs.png

I deleted the `/.shared-ringdb` folder, but the error persists.

**Comment by stoffu** [comment]
#3919

**Comment by stoffu** [comment]
It turns out that the above patch is still not enough for processing the old v6 chains due to DB version mismatch, see #3923
