### ISSUE TITLE
gcc8 build still broken in v0.12.2.0

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero#3929]
Why hasn't this been applied yet? ae6a40dfd76f5fb024b48a83d900cf5e6d02db93

**Comment by moneroexamples** [comment]
On Arch?

**Comment by anonimal** [comment]
Yes. I've applied proper patches though. https://aur.archlinux.org/cgit/aur.git/log/?h=monero.

**Comment by moneroexamples** [comment]
Can compile using the followng for the time being:

> make CXXFLAGS="-Wno-error=class-memaccess" CFLAGS="-Wno-error=class-memaccess"

**Comment by moneromooo-monero** [comment]
AFAIK the last GCC 8 fix is now in master. Can you confirm (or anyone else with GCC 8) ?
If there's still more, run with -k to get ALL the errors.

**Comment by stoffu** [comment]
Confirmed that everything builds fine with GCC 8.1.1 (on Manjaro).

**Comment by moneromooo-monero** [comment]
Thanks

+resolved
