### ISSUE TITLE
wallet-cli: unable connect monero-wallet-cli to v0.12.2.0 daemon

### ISSUE THREAD

**Issue by coneiric** [monero-project/monero#3930]
After successfully building, migrating database, and syncing with peers, `monero-wallet-cli` gives the following error:
```
Error: wallet failed to connect to daemon: http://localhost:18081. Daemon either is not started or wrong port was passed. Please make sure daemon is running or change the daemon address using the 'set_daemon' command.
```
Error occurs with old and newly created wallets. Looking through the logs, some potentially relevant errors: [https://pastebin.mozilla.org/9086988](https://pastebin.mozilla.org/9086988)

**Comment by moneromooo-monero** [comment]
That error is unrelated.

I assume you can reach the daemon via telnet from where you're running the wallet. If not, fix it.
Then run the dameon with --log-level 2, and post the log excerpt when you run the wallet.

**Comment by coneiric** [comment]
> I assume you can reach the daemon via telnet from where you're running the wallet

Awesome, that worked! Apologies for the non-issue, and thanks for the help.
