### ISSUE TITLE
license missing for SUPERCOP ref10

### ISSUE THREAD

**Issue by jonassmedegaard** [monero-project/monero#3942]
Hi,

the file src/crypto/crypto_ops_builder/README.md states that

> The majority of the work we are using is from SUPERCOP, and copyrights and attribution fall to those developers and cryptographers.

I fail to locate any license grant from the authors of SUPERCOP - neither in Monero project nor upstream in <http://hyperelliptic.org/ebats/supercop-20141124.tar.bz2>

Please clarify under which license the SUPERCOP code has been included.

**Comment by moneromooo-monero** [comment]
http://ed25519.cr.yp.to/software.html says:

"The Ed2519 software is available as the crypto_sign/ed25519 subdirectory of the SUPERCOP benchmarking tool [,,,]"

and:

The ed25519 software is in the public domain.

Looking at the source, it seems that the ref10 source in monero is the crypto_sign/ed25519 software, modulo two small files, "description" and "designers".

**Comment by jonassmedegaard** [comment]
Thanks!

The piece I was missing was the existence of web page http://ed25519.cr.yp.to/software.html

I suggest to extend file "description" (which seemingly is already edited by you - by copying ../descrition from upstream tarball and adding a line linking to the tarball URL) with a line pointing to http://ed25519.cr.yp.to/software.html as homepage of the upstream code and mention that its (non-)license is stated there.

Example:

  Homepage (listing the code as being in the public domain): http://ed25519.cr.yp.to/software.html

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4021

**Comment by moneromooo-monero** [comment]
+resolved
