### ISSUE TITLE
non-free licensed RFC document in source

### ISSUE THREAD

**Issue by jonassmedegaard** [monero-project/monero#3943]
Hi,

Source contains the file src/crypto/crypto_ops_builder/ietf.txt which restricted by a license deemed non-free e.g. by Debian.

Please omit that file from source - if for nothing else then to ease redistribution by others who might have a more strict view on licensing complicance.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4357

**Comment by moneromooo-monero** [comment]
+resolved
