### ISSUE TITLE
source contains PNG file with embedded non-free ICC profile

### ISSUE THREAD

**Issue by jonassmedegaard** [monero-project/monero#3944]
Hi,

File contrib/snap/setup/gui/icon.png contains an embedded color calibration (ICC) profile which is copyright Hewlett Packard but lack license.

Please strip that ICC profile (since it is used to declare the sRGB colorspace which is commonly assumed by default for graphics files omitting any ICC profiles).

One way to examine metadata of embedded ICC profiles is by use of the commandline tool "exiftool", part of Perl module Image::ExifTool.

**Comment by moneromooo-monero** [comment]
If you know how to do that, a patch is welcome.

**Comment by jonassmedegaard** [comment]
This should work: `optipng -force -strip all contrib/snap/setup/gui/icon.png`.

Alternatively pngcrush should work too.

Sorry, I won't do a PR as a principle due to Github terms of service. I can put up a git clone elsewhere but guess it is far less work to run above command compared to fetching from a remote git.

**Comment by moneromooo-monero** [comment]
OK, thanks. I have that tool in my distro's repo, I'll do that.

What terms of service in particular, out of curiosity ?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3947

**Comment by jonassmedegaard** [comment]
This (arguably only an ambiguity, but still chilling) is my reason for not doing PRs on Github: https://anarc.at/blog/2017-03-22-github-tos-update/

**Comment by moneromooo-monero** [comment]
Thanks, informative.

**Comment by jonassmedegaard** [comment]
Also, more generally, I believe Free softare needs Free tools (see https://mako.cc/writing/hill-free_tools.html and https://www.youtube.com/watch?v=U_nK6nP_RCY ) so keep my interactions with non-free tools to a limit.

**Comment by moneromooo-monero** [comment]
+resolved
