### ISSUE TITLE
I have got error when i used 12.2 monerod version

### ISSUE THREAD

**Issue by seniorwebsdeveloper** [monero-project/monero#3952]
ERROR   cn      src/cryptonote_core/cryptonote_core.cpp:1223    Exception at [core::handle_incoming_block()], what=DB error attempting to fetch block index from hashMDB_BAD_TXN: Transaction must abort, has a child, or is invalid

**Comment by moneromooo-monero** [comment]
That looks like a corrupt DB. Did your OS crash, or computer lose power ?

**Comment by dEBRUYNE-1** [comment]
Going to close this in favor of #3961 

+invalid
