### ISSUE TITLE
Multiple RPC calls raises error message

### ISSUE THREAD

**Issue by wowario** [monero-project/monero#3959]
I run a perl script that makes multiple RPC calls to extract difficulty and timestamp data. When script is ran on Monero v0.12.2.0, the script stalls, the deamon pushes CPU usage over 100%, and I get the following error:

`ERROR	net	contrib/epee/include/net/abstract_tcp_server2.inl:1117	Exception at [boosted_tcp_server<t_protocol_handler>::connect], what=open: Too many open files`

Issue might be related to commit https://github.com/monero-project/monero/commit/4d158647289088ef316da44cc06146f049179137

https://github.com/wownero/wownero/issues/50

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3962

**Comment by wowario** [comment]
Issue resolved. Thank you @moneromooo-monero.
