### ISSUE TITLE
Update Boost

### ISSUE THREAD

**Issue by jonatanrinckus** [monero-project/monero#3960]
Please, update boost on windows(Msys) to use the last version(1.67), the last version do not have some files, like thread.hpp that is imported on monero code and we can't install the 1.58 on msys with pacman

**Comment by moneromooo-monero** [comment]
What commt hash are you running ?

**Comment by jonatanrinckus** [comment]
Didnt understand, what?

**Comment by dEBRUYNE-1** [comment]
@jonatanrinckus - Post the output of `monerod.exe --version` here. That will show the commit hash.

**Comment by jonatanrinckus** [comment]
I'm trying to compile this source on windows, there is no monerod.exe yet
