### ISSUE TITLE
Any special reason why Blockchain::get_transactions is template member function?

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#3967]
The template is defined here
https://github.com/monero-project/monero/blob/master/src/cryptonote_core/blockchain.h#L688

but the the definition and explicit initialisation are done only for std::list as second and third parameter.
https://github.com/monero-project/monero/blob/master/src/cryptonote_core/blockchain.cpp#L4561

This is very confusing especially since documentation says:

```
 * @tparam t_tx_container a standard-iterable container
 * @tparam t_missed_container a standard-iterable container
```

and at present you can't call get_transaction with only vectors for example. You have to call it with vector as first argument and lists as second and third one. This is problematic because list and vector don't have same api. Lists don't have subcript operators for example.

**Comment by moneromooo-monero** [comment]
For the record, it's changing to vector/vector in the wallet refresh code.

**Comment by moneroexamples** [comment]
Do you know when this change is going to take place?

**Comment by moneromooo-monero** [comment]
No.

**Comment by moneromooo-monero** [comment]
Though I just rebased #3716 (which contains this change) so it's not ready for review.

**Comment by moneroexamples** [comment]
Thanks.
