### ISSUE TITLE
Build instructions for submodules

### ISSUE THREAD

**Issue by CjS77** [monero-project/monero#3968]
This gets me every time the submodule dependencies change, mainly because `git submodule` is pretty unintuitive.

So this doesn't seem to work when compiling an update, though one feels it should:
`cd monero && git submodule init && git submodule update` and then compilation fails.

but

`cd monero && git submodule update --init --recursive`

seems to do the trick.

I would also stick this command in the [Build Instructions](https://github.com/monero-project/monero#build-instructions) rather than the setup instructions because 
1) it's idempotent
2) You need to run it pretty often when compiling a new release.

**Comment by moneromooo-monero** [comment]
The build system now tells you about it.

+resolved
