### ISSUE TITLE
Monerod Building issue

### ISSUE THREAD

**Issue by seniorwebsdeveloper** [monero-project/monero#3978]
when I type "make" command to build moneroD, i got issue following:

CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:778 (find_package)

CMake Error at CMakeLists.txt:56 (message):
  Could not find Boost libraries, please make sure you have installed
  Boost or libboost-all-dev (1.58) or the equivalent
Call Stack (most recent call first):
  CMakeLists.txt:782 (die)

**Comment by moneroexamples** [comment]
Monero requires at least boost version 1.58. What OS are you using? You could always try building newer boost yourself.

**Comment by seniorwebsdeveloper** [comment]
now i am using ubuntu

**Comment by moneroexamples** [comment]
Guess its pre ubuntu-16.04 version? 16.04 has already boost in 1.58

**Comment by seniorwebsdeveloper** [comment]
but i can't install boost 1.58 on ubuntu
there is no package

**Comment by moneroexamples** [comment]
Your ubuntu is too old.

**Comment by seniorwebsdeveloper** [comment]
how can i solve?

**Comment by moneroexamples** [comment]
upgrade your ubuntu or compile boost 1.58 on your older version youself. Eitherway these are not issues related to monero.

**Comment by seniorwebsdeveloper** [comment]
i should change server?

**Comment by homdx** [comment]
Try manually update boost
```
tar -xvf boost_${BOOST_VERSION}.tar.bz2 
 && cd boost_${BOOST_VERSION} \
    && ./bootstrap.sh \
    && ./b2 
ENV BOOST_ROOT /usr/local/boost_${BOOST_VERSION}
```

**Comment by moneromooo-monero** [comment]
As mentioned above, missing deps, see README.

+invalid
