### ISSUE TITLE
[Linux] Latest boost-libs update broke monero-wallet-cli

### ISSUE THREAD

**Issue by ElecM8** [monero-project/monero#3984]
Title's pretty self-explanatory, but boost and boost-libs recently got an update (1.67) and everytime I try to launch monero-wallet-cli I get this error:

`error while loading shared libraries: libboost_chrono.so.1.66.0: cannot open shared object file: No such file or directory`

Downgrading both back to 1.66 fixes the issue.

**Comment by moneromooo-monero** [comment]
If you update deps, you have to rebuild monero.

+invalid

**Comment by ElecM8** [comment]
Well, building doesn't work either: https://pastebin.com/vp4WLrkP
Building after downgrading the deps works perfectly though.
