### ISSUE TITLE
Dockerfile fails to build in 0.12.2.0

### ISSUE THREAD

**Issue by tannerdsilva** [monero-project/monero#3988]
It appears as though the variable `MONERO_HASH` is incorrect in Dockerfile 0.12.2.0, resulting in a container that will not build.

When I download the 0.12.2.0 source and run `docker build`, step 28 exits `1` as a result of the following comparison

``test `git rev-parse HEAD` = ${MONERO_HASH} || exit 1``
``test e2c39f6b59fcf5c623c814dfefc518ab0b7eca32 = c29890c2c03f7f24aa4970b3ebbfe2dbb95b24eb``

When I change MONERO_HASH to reflect the hash returned from `git rev-parse HEAD`, the container successfully builds. I posted about this issue on the [monero subreddit](https://www.reddit.com/r/Monero/comments/8qahgc/is_it_just_me_or_is_the_01220_dockerfile_broken/), and at the time of writing, didn't have any evidence from users that the 0.12.2.0 container has been successfully built from source.

**Comment by tannerdsilva** [comment]
I realize that the very act of releasing a fix for this bug will fix the problem, as a new HEAD hash would be generated. Just wanted to point out the problem, for whatever its worth.

**Comment by homdx** [comment]
My commit is can help and run Docker?
https://github.com/monero-project/monero/pull/3879
