### ISSUE TITLE
variant 2

### ISSUE THREAD

**Issue by KlausT** [monero-project/monero#4001]
Take a look at this code from Stellite:
https://github.com/stellitecoin/Stellite/blob/894ba4036069682d190f2282c2df08fd45177f9d/src/crypto/slow-hash.c#L56
I guess when Monero will be using variant 2 then it will not be the same as Stellite variant 2, right?

**Comment by moneromooo-monero** [comment]
No, it won't.

**Comment by moneromooo-monero** [comment]
It will very likely be based upon https://github.com/SChernykh/xmr-stak-cpu/commit/9169ef624250e8ab73ec362d7905abcb00ba91a4

Then a couple other small tweaks will be made closer to release to keep the "ASIC design" period short.

**Comment by moneromooo-monero** [comment]
See #4218 

Not a bug, closing.

+invalid
