### ISSUE TITLE
mingw to build dll on windows breaks

### ISSUE THREAD

**Issue by goldsun888** [monero-project/monero#4002]
Anybody ever built dlls on windows successfully? It prompts multiple definitions error. After added -Wl,--allow-multiple-definition, I still got the message below:

[ 85%] Linking CXX shared library libp2p.dll
CMakeFiles/p2p.dir/objects.a(net_node.cpp.obj):net_node.cpp:(.data+0x30): undefined reference to `cryptonote::arg_testnet_on'
CMakeFiles/p2p.dir/objects.a(net_node.cpp.obj):net_node.cpp:(.data+0x38): undefined reference to `cryptonote::arg_stagenet_on'

It looks that the cryptonote_core.dll doesn't link correctly. I attached the dll export screenshot.

![dll](https://user-images.githubusercontent.com/18001163/41457413-208eed02-70b6-11e8-9173-7fb2180e8091.png)

**Comment by stoffu** [comment]
You seem to be trying to build Windows binaries that are dynamically linked which is not supported. Only statically linked build is supported for Windows, where libp2p.a etc are generated instead of libp2p.dll.

**Comment by moneromooo-monero** [comment]
+invalid
