### ISSUE TITLE
[Feature request] [monerod] Display how many blocks left when syncing

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero#4014]
For now you see two huge numbers with each new set of blocks that you download while you're catching up. This makes it difficult to tell how far you are from getting fully synced. Displaying a `Blocks left: XXXX` at the end of each sync info line would make life easier for non-GUI users.

**Comment by leafcutterant** [comment]
Thanks, you're awesome and very quick! Closing this.

**Comment by leafcutterant** [comment]
I'm reopening this as the solution implemented is insufficient.

What #4020 does is it displays percentage progress and how blocks are left *below a level of progress* (99% of the full blockchain height).

If the user has less than 1% of the full height to sync, this function won't help them to get a picture about their progress.

I strongly propose always displaying how many blocks are left.

An additional improvement could be what I described in the second paragraph of my comment [here](https://github.com/monero-project/monero/pull/4020#issuecomment-407210275).

**Comment by moneromooo-monero** [comment]
It does display the number of blocks left to sync now.

+resolved
