### ISSUE TITLE
[Need Lib Update] Libssl incompatible with 1.0.2 (porting to libssl1.0.2 or libssl1.1)

### ISSUE THREAD

**Issue by Jorropo** [monero-project/monero#4016]
I was setuping an node on debian but monerod doesn't support libssl1.0.2, just 1.0.0, but libssl1.0.0 isn't any more in the stable repo.
So for not use an very old package that starting to be removed from repo and make installation very much easier, an update to libssl1.0.2 or the best libssl1.1 need to be consider.
PS: libssl1.1 is in debian stable, ubuntu 18.04 repo's

**Comment by moneromooo-monero** [comment]
Post the errors. I am using one of the 1.0.2...

**Comment by pazos** [comment]
@Jorropo: Debian Stretch & Ubuntu Bionic ship the same version (1.0.2-n). From my ubuntu box: 

```
apt-cache madison libssl1.0-dev
libssl1.0-dev | 1.0.2n-1ubuntu5 | http://es.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

This works ok for build this repo and can coexist with libssl1.1

**Comment by moneromooo-monero** [comment]
If no evidence of the claims soon, I'll close since it works for me.

**Comment by moneromooo-monero** [comment]
ping, last chance

**Comment by Jorropo** [comment]
I retry on same condition and the bug doesn't appear anymore
