### ISSUE TITLE
relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by kamuluprashanth** [monero-project/monero#4019]
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1206: recipe for target 'tests/unit_tests/unit_tests' failed
make[3]: *** [tests/unit_tests/unit_tests] Error 1
make[3]: Leaving directory '/home/ubuntu16/Desktop/masari/build/release'
CMakeFiles/Makefile2:4348: recipe for target 'tests/unit_tests/CMakeFiles/unit_tests.dir/all' failed
make[2]: *** [tests/unit_tests/CMakeFiles/unit_tests.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu16/Desktop/masari/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu16/Desktop/masari/build/release'
Makefile:64: recipe for target 'release-all' failed
make: *** [release-all] Error 2

please give me solution

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by blackrangersoftware** [comment]
Why then, isn't the code set to always look for the built-in version of gtest with the suggested switch  -fPIC??

I have another coin daemon that runs on the same host for business reasons that requires the version installed on the system.

I built and successfully tested this  version of Monero on a fresh build of Ubuntu without a single error, and now this error crashes a build at 95% time after time on my production build.

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

You can also uninstall libgtest from your system if nothing else uses it, monero has its own copy, which it builds with -fPIC
