### ISSUE TITLE
[P2P9]	WARN 	blockchain	src/cryptonote_core/blockchain.cpp:3914	invalid hash for blocks 1545984 - 1546239

### ISSUE THREAD

**Issue by lh1008** [monero-project/monero#4022]
Hi guys,

I started syncing from scratch several days ago and everything went fine until I got to blocks 1545984 - 1546239 and an ERROR(invalid hash) shows up. The deamon still synchronizes itself but this error shows up even though it keeps on running. 

Here are the 162 last lines of the bitmonero.log.

https://paste.fedoraproject.org/paste/36SmDYQEN6gC5xD~WG7ifg

Is there any problem? Can it get fixed? 

Thank you :).

**Comment by Jorropo** [comment]
Hi, the interesting things is this problem is isolated, so this is probably on your side.
Please, what is your :
Os
Deamon version
And Arch ?

**Comment by lh1008** [comment]
Thanks,

OS - Ubuntu 16.04 LTS
Deamon 12.02
Intel Core i3 Toshiba Satellite C655 laptop

**Comment by Jorropo** [comment]
Do you try to remove these blocks (5k blocks arround) with Blockchain utils ?

**Comment by lh1008** [comment]
I don't know how to remove blocks with Blockchain utils.

**Comment by Jorropo** [comment]
Right now I have only my phone so I can't help you right now, but I will help you asap.

**Comment by lh1008** [comment]
ok thank you :)

**Comment by moneromooo-monero** [comment]
Don't remove anything, it seems to be syncing fine, you can just ban the peer that's sending you these bad blocks. It's probably a peer on a fork that hasn't updated to the current software and so mining invalid blocks.

**Comment by lh1008** [comment]
@moneromooo-monero, how can I ban the peer who is sending these bad block?

**Comment by moneromooo-monero** [comment]
set_log 1
You will get a "Got NEW blocks..." message just before these bad hash messages. It will include the node's IP. Then:
ban THATIPADDRESS
This will ban it for 24 hours.

**Comment by lh1008** [comment]
I was not able to get the IP to ban it. In the bitmonero.log directory, 2 different bitmonero.log files(bitmonero.log-2018-06-18-23-50-50/bitmonero.log-2018-06-19-04-10-43) were created and I was not sure where to find the IP. 
I'm closing the issue because what I did was close the deamon and started syncing the next day. Then the Invalid Hash ERROR was no longer showing up. @Jorropo and @moneromooo-monero thank you a lot for your support and assistance. If I encounter another error I will open another Issue, I'll be closing this one.

Thank you :).
