### ISSUE TITLE
Please support skipping network-related tests

### ISSUE THREAD

**Issue by jonassmedegaard** [monero-project/monero#4026]
Hi,

Two tests in the testsuite - <tests/unit_tests/address_from_url.cpp> and <tests/unit_tests/dns_resolver.cpp> - depend on network access.

Some build environments - Debian build daemons in particular - deliberately have no network access to ensure reproducibility.

Please support skipping network-related tests - preferably using an environment flag, so that same precompiled tests are possible to be easily rerun in another environment.

**Comment by moneromooo-monero** [comment]
You can do this with the --gtest_filter option, or the GTEST_FILTER env var.

**Comment by jonassmedegaard** [comment]
oh. Sorry for turning this into a support channel, that was unintended! Clearly there's no issue, then.
