### ISSUE TITLE
[feature request] password method for wallet-rpc

### ISSUE THREAD

**Issue by artyomsol** [monero-project/monero#4027]
A possibility to change the  wallet  password is a "must have" feature of any wallet implementation. 
It is missed in the wallet-rpc API though implemented in [wallet-cli](https://github.com/monero-project/monero/blob/v0.12.2.0/src/simplewallet/simplewallet.cpp#L711).

**Comment by moneromooo-monero** [comment]
That seems dangerous, no ?

**Comment by artyomsol** [comment]
I don't think it could be more dangerous than doing so with CLI or GUI.
Double checking of a new password is a duty of UI, but back end API should be able to handle the query to provide the same functionality as CLI.
IMHO, manual creation of the new one wallet (loosing the metadata collected in the previous one) just to change the password (regular operation to provide the securirty) is a bit overhead and anti pattern from the RPC point of view.

**Comment by Zarkoob** [comment]
What kind of meta data would we be losing?

**Comment by artyomsol** [comment]
@Zarkoob tx private keys

**Comment by moneromooo-monero** [comment]
+hacktoberfest
