### ISSUE TITLE
Daemon connection issues recently

### ISSUE THREAD

**Issue by BKdilse** [monero-project/monero#4037]
I am having intermitent connection issues with monerd, running on Ubuntu 16.04.

The logs show:

COMMAND_HANDSHAKE Invoke Failed -4, LEVIN_ERROR_CONNECTION_TIMEOUT

On occasions it works, and randomly stops with the above issue.  All other internet activity works fine.  I can successfully telnet into the remote node which is falling on.

Any ideas what is going on here?

**Comment by moneromooo-monero** [comment]
Does https://github.com/monero-project/monero/pull/3962 help ?

**Comment by BKdilse** [comment]
Thanks, I'll try and give it a go and see.

**Comment by BKdilse** [comment]
seems to be a connection issue with my network, so closing.
