### ISSUE TITLE
How to restore tx key in cli from mymonero ? cmds needed

### ISSUE THREAD

**Issue by Gyng3r** [monero-project/monero#4038]
Hello, 
i need the tx key from a transaction which i sent from mymonero.com. Currently I have the cli version  0.12.2.0 downloaded and synchronized with the blockchain. What are the commands for the cli to restore the cache where the TX Key is located ? When i use this tutorial https://www.monero.how/tutorial-how-to-prove-payment , i become a error no tx found.

**Comment by stoffu** [comment]
That functionality is nonexistent AFAIK. You can tag this issue as “feature request”.

**Comment by moneromooo-monero** [comment]
If you sent it with mymonero, mymonero would have it (and AFAIK it doesn't keep them). They're not on the blockchain. Pleae keep this bug tracker for bug reports. You can get help on reddit, or #monero on Freenode.

+invalid

**Comment by stoffu** [comment]
I think I misunderstood the intent of the question. No, it's not possible to recover tx secret keys when you restore your wallet from seed, as @moneromooo-monero explained.

I thought about the ability to import tx keys from outside services like MyMonero to wallets restored using the CLI/GUI useful, which would then enable generating tx proofs. But this use case may be fairly niche, I suppose.
