### ISSUE TITLE
ZeroMQ issues

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#404]
1. You can't type in any commands to the daemon. 

2. I've only found 1 wallet command that doesn't work. refresh works, but rescan_spent doesn't work
http://hastebin.com/raw/lihoziteqa

**Comment by Gingeropolous** [comment]
http://hastebin.com/raw/uceravuyay

pretty sure this is a crash

**Comment by fluffypony** [comment]
Since we're redoing 0MQ I'm closing this
