### ISSUE TITLE
Ringsize / mixin still mixed up here and there

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#4040]
Is there a reason for this? I don't know exactly where, but according to 

https://www.reddit.com/r/Monero/comments/8sz02k/update_monerujo_159_maximum_nacho/e1402ag/

and from what i've seen on the block explorers, there must be some cases in the code where they are still referring to mixin and not ringsize, because there are some ringsize 8 transactions that are frequently pumped out. 

so someone is clearly feeding 7 into a parameter that is mixin, so the total ringsize is 8. 

is there a reason its not unified / standardized?

**Comment by shopglobal** [comment]
wallet_rpc_server is using ring_size but some pool software is using mixin and so we should just add some logic to accept both

**Comment by moneromooo-monero** [comment]
Reopen if you have some tangible information about something being wrong. I know of nothing missing.

+invalid
