### ISSUE TITLE
compiling Dependencies as Static

### ISSUE THREAD

**Issue by Copterrichie** [monero-project/monero#4046]
I have an issue of trying to compile the Monero wallet on older i5 Ubuntu 16.04
Server edition machine. I was able to compile xmr on my I5 ubuntu version 18 after installing all of the Dependencies. However upon repeating the same on this process on the Server machine, it complains "**/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_chrono.a(chrono.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC**" Reading the docs, it stated the Dependencies need to compiled static using the gcc -fPIC flag. any suggestions on how to do this or resolve this problem?

Thank you.

**Comment by moneromooo-monero** [comment]
To build boost with -fPIC, read boost docs.
Typically, for most software, you set custom CFLAGS when configuring.

**Comment by moneromooo-monero** [comment]
+invalid

**Comment by blackrangersoftware** [comment]
https://github.com/monero-project/monero/issues/4019

This is a duplicate of the issue in 4019 and 3099, and yet the code I pulled again last night still produces this error.

Why then, isn't the code set to always look for the built-in version of gtest with the suggested switch -fPIC??
