### ISSUE TITLE
RPC create wallet from seed 

### ISSUE THREAD

**Issue by julesGoullee** [monero-project/monero#4058]
What is the right way to restore wallet from seed with the rpc api ?

**Comment by moneromooo-monero** [comment]
Such questions are a good for for monero.stackexchange.com. More generally, help can be asked in #monero on Freenode, or reddit.

**Comment by stoffu** [comment]
Currently there's no such functionality implemented for the RPC. The CLI has the full set of functionalities, while the RPC only supports some subset of them.

The RPC has the command `create_wallet` which lets you create a new wallet, but other commands for wallet restoration (from seed, from device, etc) are not implemented. IIRC there was some debate about the design of the RPC program regarding the management of multiple wallets, and the discussion didn't end with a decisive conclusion. CC: @hyc

**Comment by hyc** [comment]
I guess there's no reason not to add this to the RPC, I just didn't think of it when adding `create_wallet`.

**Comment by artyomsol** [comment]
+1 for RPC API wallet restoration from seed

**Comment by moneromooo-monero** [comment]
in fact, this could be merged with the generate-from-json code, so we get everything.

**Comment by moneromooo-monero** [comment]
+hacktoberfest

**Comment by omani** [comment]
hi all,
please see #4746.

**Comment by moneromooo-monero** [comment]
+resolved
