### ISSUE TITLE
CLI wallet disconnects from node when creating transaction

### ISSUE THREAD

**Issue by dprestegard** [monero-project/monero#4059]
Hello!

I'm on 0.12.2.0 on both node and cli wallet. The node is on Ubuntu, the wallet is on windows.

I'm running the node as follows (on a VM):

`monerod --data-dir $pathToBlockchain --rpc-bind-ip 0.0.0.0 --restricted-rpc --confirm-external-bind --rpc-login $credentials`

I'm running the wallet as follows (locally)

`monero-wallet-cli --daemon-host $nodeIp --daemon-login $credentials`

It connects, I load my wallet, and it shows my balance. I try to transfer some monero, and I get an error like this:

`"Error: Wallet failed to connect to daemon: http://$nodeIp:18081`

I turned off the firewall to be sure, same result. When I curl http://$nodeIp:18081 I get a a 401 Unauthorized Access error.

This used to work, I just haven't sent any monero in awhile.

Switching to the 0.12.1.0 wallet works fine.

**Comment by dprestegard** [comment]
Verified the issue still occurs using the client from https://build.getmonero.org/builders/monero-static-win64/builds/4766

**Comment by dEBRUYNE-1** [comment]
That build, most likely, does not include #3962, which supposedly fixes your particular issue.

**Comment by dEBRUYNE-1** [comment]
@dprestegard - I suppose I can mark this as resolved then?

**Comment by dprestegard** [comment]
Yep, I suppose so!
