### ISSUE TITLE
slow sync with blockchain import

### ISSUE THREAD

**Issue by yura-sutnuk** [monero-project/monero#4085]
I downloaded the monero and blockchain from the official site and I try to start importing the blockchain for faster synchronization but the synchronization is still slower than if I just started the daemon.
i run import with command 

`sudo ./monero-blockchain-import --input-file ./blockchain.raw  --guard-against-pwnage 0`
i do something wrong?

**Comment by moneromooo-monero** [comment]
Yes, you're using --guard-against-pwnage 0 with a file you got from the internet. Why are you doing this when the name is clearly telling you it's dangerous ?

**Comment by yura-sutnuk** [comment]
but if the file is obtained from a reliable source (in this case, the official site), then you can turn it off to speed up the synchronization or am I wrong?

**Comment by moneromooo-monero** [comment]
It's reliable till it's not. The Gentoo github repo was just pwned for instance.
Anyway, it should speedup, yes.
When you say "slow", can you quantify that a bit ?
Are you using a HDD or SSD ?

**Comment by moneromooo-monero** [comment]
Try a larger --batch-size

**Comment by yura-sutnuk** [comment]
increased batch-size to 100,000, the speed increased to 600 blocks per minute, in 20 minutes I saw the inscription Killed and the process was closed
