### ISSUE TITLE
little help

### ISSUE THREAD

**Issue by laugh26** [monero-project/monero#4086]
Am helping a friend move his cryptonote coin from cryptonote original to cryptonote heavy algorithm to prevent asic miners. i just have one single problem which is coinbase transaction doesn't use full amount of block reward:  spent: 703687.44177663,  block reward 1407374.88355327(1407374.88355327+0.00000000). block reward at block zero is 703687.44177663 but the reward tells me its 1407374.88355327 that is 2 * 703687.44177663, i have looked around with no luck. Any help. What am i not doing correctly

**Comment by moneromooo-monero** [comment]
This is a bug tracker. To get help, try monero.stackexchange.com, or reddit.

+invalid

**Comment by laugh26** [comment]
thanks @moneromooo-monero

**Comment by laugh26** [comment]
did everything again and i discover my problem, solved. Thanks monero for your open source code. I have help out at least
