### ISSUE TITLE
Unauthorized Access Monero RPC

### ISSUE THREAD

**Issue by 5-digits** [monero-project/monero#4099]
I Configured the monero rpc with the command with the following command lines:

1/ First I run the monero daemon : [ ./monerod --testnet --rpc-bind-ip=x.x.x.x --rpc-bind-port=28081 --rpc- login user:password --confirm-external-bind](url)

2/Then I configured the monero-rpc : [ ./monero-wallet-rpc --wallet-file testwallet --password test --rpc-bind- port 28082 --rpc-bind-ip=x.x.x.x --daemon-address x.x.x.x.x:28081 - -testnet --daemon-login user:password --log-level 4 --confirm-external-bind
] (credit to Wejden )

Result : The RPC server Connetc Succefully but when request any like ( getheight ), it return an "Unauthorized Access" .

**Comment by moneromooo-monero** [comment]
Are you sure you're authenticating ?

**Comment by 5-digits** [comment]
For sure i'm authenticating

**Comment by moneromooo-monero** [comment]
You're saying monero-wallet-rpc can connect to monerod, but RPC actually fails, right ?
monero-wallet-rpc logs should include the HTTP data sent to the daemon. Find it, and post it.

**Comment by moneromooo-monero** [comment]
If no further comment, I'll be assuming you didn't auth correctly and close.

**Comment by moneromooo-monero** [comment]
Closing then. Please reopen if you have further info.

+invalid
