### ISSUE TITLE
[Feature request] Add option to the wallet to set a higher number of rounds for the KDF

### ISSUE THREAD

**Issue by garlicgambit** [monero-project/monero#4100]
Please consider to add an option to the wallet to set a higher number of rounds for the KDF (key derivation function). Allow the user to only increase the number over the default value and configure it based in seconds.

Example:
```monero-wallet-cli --unlock-time 20```

This example would unlock the wallet after 20 seconds.

**Comment by moneromooo-monero** [comment]
Not based on time. It needs to be deterministic. But a custom multiplier can be done.

**Comment by stoffu** [comment]
I've made a WIP #4103 which introduces a new flag `--kdf-rounds <N>`.

The practical problem with this code is that the heavy KDF computation gets triggered every time the user enters the wallet password (e.g. when making transfers and when changing wallet settings). This could be mitigated by caching the resulting encryption key, but I'm not sure if it's a good practice.

**Comment by MaxXor** [comment]
Where is the current amount of rounds documented?

**Comment by moneromooo-monero** [comment]
It is 1.

**Comment by moneromooo-monero** [comment]
+resolved
