### ISSUE TITLE
Monero seed "encryption" is vulnerable to known-plaintext key recovery

### ISSUE THREAD

**Issue by fireice-uk** [monero-project/monero#4104]
https://github.com/ryo-currency/ryo-writeups/blob/master/monero-seed-encryption.md

I know we are all having a fairly busy week, but I brought forward the publication date for that since it would be a fairly dick move to let you do a release and publish that in a few days.

**Comment by anonimal** [comment]
> since it would be a fairly dick move to let you do a release and publish that in a few days

The only dick move is this [incredibly weak claim](https://github.com/ryo-currency/ryo-writeups/blob/master/monero-seed-encryption.md#why-not-report-it-though-moneros-vrp-or-hackerone) for which everyone can read and see that you're mentally unstable.

>I don't consider the money to be worth the aggro

Bounty is optional. Bounty has nothing to do with responsible disclosure. Try actually reading the [VRP](https://github.com/monero-project/meta/blob/master/VULNERABILITY_RESPONSE_PROCESS.md).

[8/9 people haven't complained about bounty](https://hackerone.com/monero/hacktivity?sort_type=latest_disclosable_activity_at&filter=type%3Aall%20to%3Amonero&page=1&range=forever), so the excuse you're giving is a very poor one (literally).

**Comment by fireice-uk** [comment]
> The only dick move is this incredibly weak claim for which everyone can read and see that you're mentally unstable.

Yup, that's pretty much the response I have been expecting.

**Comment by cryptochangements34** [comment]
Insults aside, this seems like something that should be addressed but isn't particularly high priority as this is only useful if the attacker has the encrypted key and some extra information about the target's wallet. Because users are repeatedly warned to never give away the seed and keep it stored securely, regardless of whether it is encrypted or not, I seriously doubt that anybody's funds are at risk because of this.

**Comment by moneromooo-monero** [comment]
This is technically true, but this is not supposed to be a generic encryption system. It's for seeds, and is a kind of one time pad -ish.  Using more words would defeat the purpose of an encrypted seed looking like (and being) any other valid seed.

**Comment by moneromooo-monero** [comment]
And yeah, the insulting's not needed, but given the linked post trolls right off the bat, well...

**Comment by fireice-uk** [comment]
@moneromooo-monero 

I agree, **this is some kind of sky-is-falling event** (as some people on reddit are making it out to be). Most users are not using that feature, but if someone does you will let him or her down badly. 

I posted it now so that you have the opportunity to remove (or fix if you can come up with it in that short of a time) it in the upcoming point release.

**Comment by moneromooo-monero** [comment]
Understood, thanks for the note.

**Comment by moneromooo-monero** [comment]
I've changed the wording from "seed encryption" to "seed offset", so people can't get confused.

**Comment by moneromooo-monero** [comment]
+resolved
