### ISSUE TITLE
Remove or update the snap package

### ISSUE THREAD

**Issue by zone117x** [monero-project/monero#4112]
In addition to unresolved issues from https://github.com/monero-project/monero/issues/3299
The snap package appears to be unmaintained and using a non-working older version of monero. [v0.11](https://github.com/monero-project/monero/blob/master/contrib/snap/snapcraft.yaml#L2) from what I can tell. 
If this is the case, every person who attempts setup with the snap package is in for quite the waste of time syncing to the pre-fork monero chain(s).

**Comment by moneromooo-monero** [comment]
This got removed.

**Comment by selsta** [comment]
#6475
