### ISSUE TITLE
Error: internal error: histogram reports more recent outs than outs for 0

### ISSUE THREAD

**Issue by tobtoht** [monero-project/monero#4121]
Operating system: Tails
Wallet: monero-linux-x64-v0.12.2.0
Remote node: xmrag4hf5xlabmob.onion:18081

Restored wallet from pre-fork seed. Wallet refreshed successfully.

When trying to send a transaction:
"Error: internal error: histogram reports more recent outs than outs for 0"

**Comment by moneromooo-monero** [comment]
Add --log-level 2, and post the relevant part of the log, showing the counts.

**Comment by tobtoht** [comment]
I'm posting this issue on someone else's behalf.
I suggested they try GUI 12.0, which worked fine without issue. I will contact them and ask if they can provide the log.

**Comment by tobtoht** [comment]
Just had a second person report this issue. Same conditions. Asking them for logs as well.

**Comment by gigafunk** [comment]
I had a working 11 wallet x64 linux, synced to a point a month or so before the fork.   installed 12.2 gui, seemed to sync from there and be fine, then trying to send funds I got this error.  Here is the output on the cli with log-level 2.  I can go to the log if requested and pull whatever anyone wants to see. 

I am behind a vpn on my router if it matters, I didnt expect it to sync behind it, but it did so I assumed it was fine. I expected when I looked up this error I would find it was related to vpn.   

https://pastebin.com/TYUx38tc

**Comment by stoffu** [comment]
Some easy things to try:

- Disable the key-reuse mitigation schemes by doing `set segregate-pre-fork-outputs 0` and `set key-reuse-mitigation2 0` in `monero-wallet-cli`

- Use different versions of `monerod` (0.12.x)

If these things make differences, it hints where the problem lies.

**Comment by dselyuzhitskiy** [comment]
We had the same issue, there was only one error  on monero wallet log

`ERROR	wallet.wallet2	src/wallet/wallet2.cpp:6024	num_recent_outs > num_outs. THROW EXCEPTION: error::wallet_internal_error`

Monero daemon 0.12.1.0
Monero wallet 0.12.1.0

**Comment by moneromooo-monero** [comment]
As the second comment says. Without logs, I can't tell what's wrong.

**Comment by moneromooo-monero** [comment]
All the cases I've seen before were when using mismatched node and wallet version. If nothing else comes in with matching versions, I'll close this later since everything will be using compatible versions very soon anyway due to the coming update.

**Comment by moneromooo-monero** [comment]
Use matched wallet+daemon versions.

+invalid
