### ISSUE TITLE
[Feature request] Push-on-update in wallet RPC

### ISSUE THREAD

**Issue by lessless** [monero-project/monero#4124]
Hi,

There is an obvious demand to scan blockchain for transactions for multiple wallets and from time to time it manifests itself as a feature requests to add multiple wallet support to monero-json-rpc.

What is possible to do instead is to implement push-on-update feature in rpc service which will send a balance update to the provided endpoint. It's much easier to implement and strikes right balance between scalability and engineering complexity.

Of course it was expected as a part of 0mq integration which makes sense because it will work perfect over pub/sub http://zguide.zeromq.org/page:all#Chapter-Advanced-Pub-Sub-Patterns but it's fairly broad topic and a simple HTTP  POST with update details in payload will be enough.

/cc @hyc @moneromooo-monero

**Comment by xiphon** [comment]
I'm sure it should be done by running multiple Monero Wallet RPC instances, one for each wallet you want to monitor, and them fetch them for balance updates. 

Is not possible to add support for multiple wallets to Monero Wallet RPC without breaking RPC backward compatibility. 

Although could be implemented as a separate tool, but the use case is too narrow in my opinion.

**Comment by lessless** [comment]
@xiphon running a pool of wallets is a current go to solution and it's not a problem. The real bottleneck in that scenario is a polling which is an I/O heavy process and impose a significant limit on how many monero-wallet-rpc processes it's possible to run per machine. 

Instead, if monero-wallet-rpc can notify service about balance update it will be a real game changer.

**Comment by vtnerd** [comment]
There was/is an outstanding FFS request to implement PUB/SUB from `monerod`, but the person attached with that request is no longer doing work on Monero. It is something that I will get to eventually, should no one else pick up the task, as its useful for several projects. That will probably get implemented before any PUB/SUB in `monero-wallet-rpc`.

There is also an open-source implementation for a view-only wallet server (i.e. non custodial). It will be compatible with MyMonero iOS and desktop applications. Most of the code is public (but you have to hunt for it) - its not listed anywhere yet as I ran into some DB design issues (it uses LMDB), so some re-working has been done. I've been thinking about PUB/SUB for these modes too, as it should reduce load on these view-only servers too.

**Comment by lessless** [comment]
Ah, so I had a wrong assumption that 0mq was integrated in the monero-rpc-service. Anyways, simple POST request  will work and it's an easiest option possible.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4333 (not RPC, but external process spawn, which can be turned into a RPC call back)

**Comment by Cactii1** [comment]
> #4333 (not RPC, but external process spawn, which can be turned into a RPC call back)

A suitable workaround has been suggested fr this feature request.

Propose to close this, a new issue can be opened in the future if necessary.

**Comment by selsta** [comment]
Please also see https://github.com/monero-project/monero/blob/master/docs/ZMQ.md
