### ISSUE TITLE
monero-wallet-rpc height is less than monerod height

### ISSUE THREAD

**Issue by skinderis** [monero-project/monero#4132]
Hi,
I am running _monero-wallet-rpc_ and _monerod_ on separate docker containers. Wallet container is connecting to _monerod_ container. But the weird thing happens that when i run `getheight` command on _monero-wallet-rpc_ it shows less height than height showed in by `monerod` (`get_height` method). Sometimes I stop wallet and open it again and it suddenly synchnorizes, but usually not and `getheight` < `get_info`

For example, wallet height is **1143125** and daemon height is **1143155**, so **30** blocks are not synced on monero wallet. (I am running testnet now)

Is there any way for the wallet to be all the time updated and synced with blockchain? 
And, if my wallet is stopped, is it syncing or when I `open_wallet` it, then it starts to sync (that means if long time not opened wallet might take time to sync when it opened again)?

Thanks!

**Comment by skinderis** [comment]
Additional info:
Two times called getheight method in a row and they returned different values. First time:
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "height": 1143160
  }
}

```
Second time:
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "height": 1143125
  }
}
```

**Comment by skinderis** [comment]
I solved the problem by using RPC method `store` on wallet. But one more issue that I am facing is that wallet sometimes shows message `{'code': -38, 'message': 'no connection to daemon'}`. This error makes a lot of problems for me as I can't automate `transfer` method. My code is trying to send some monero and when it shows this error I have to fix it by hand.

The error `{'code': -38, 'message': 'no connection to daemon'}` is not showing all the time it's 50% of succedding. What can I do?

Maybe someone has working `monerod` and `monero-wallet-rpc` docker images (where wallet is connected to daemon and works without this error) here? it would be very helpful!

**Comment by moneromooo-monero** [comment]
Use 0.12.2.3.0, it's easier on timeouts.

User error (exiting without saving), so closing.

+invalid
