### ISSUE TITLE
 Failed to invoke COMMAND_HANDSHAKE, closing connection.

### ISSUE THREAD

**Issue by kamuluprashanth** [monero-project/monero#4143]
i want to connect my crypto coin project with ip address 172.110.28.195

but it is connected to other ip address

please give me solution
2018-Jul-16 18:41:20.843252 WARNING Failed to HANDSHAKE with peer 167.114.209.190:11204
2018-Jul-16 18:41:21.121835 ERROR   [45.63.122.67:11204 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Jul-16 18:41:21.122092 WARNING Failed to HANDSHAKE with peer 45.63.122.67:11204
2018-Jul-16 18:41:24.767831 ERROR   [88.214.241.183:11204 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Jul-16 18:41:24.768164 WARNING Failed to HANDSHAKE with peer 88.214.241.183:11204
2018-Jul-16 18:41:27.042301 ERROR   [94.130.222.213:11204 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.

**Comment by moneromooo-monero** [comment]
There is nothing abnormal here, at least with the information provided.

+invalid
