### ISSUE TITLE
~BlockchainLMDB() throws if is opened in readonly mode (DBF_RDONLY)

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#4144]
I just wonder if this is expected or I misunderstand how it all works?

The `BlockchainLMDB::~BlockchainLMDB()` calls `BlockchainLMDB::close()` which in turn calls `BlockchainLMDB::sync()`. Subsequently `BlockchainLMDB::sync()` throws exception `throw0(DB_ERROR(lmdb_error("Failed to sync database: ", result).c_str()));` as lmdb is open in read only mode.

This is problematic, because you can't delete BlockchainLMDB() instances open in DBF_RDONLY mode, which leads to application crash as exception is thrown from its destructor or memory leaks. 

For instance,  `blockchain_export` utility  which opens lmdb in DBF_RDONLY mode. It uses `new` to create `BlockchainLMDB`, but never tries to `delete` it. In this case there is memory leak, because you cant `delete` the object.

**Comment by stoffu** [comment]
This should be fixed in #4129.

**Comment by moneroexamples** [comment]
Cool. So no just waiting till it gets merged. Closing the issue.
