### ISSUE TITLE
how to run monero-wallet-rpc background in Ubuntu server? 

### ISSUE THREAD

**Issue by navneetboghani** [monero-project/monero#4149]
I want to run monero-wallet-rpc in background. i am using now below command

./monero-wallet-rpc --wallet-file monero22 --password Monero11 --rpc-bind-port 18083 --rpc-bind-ip 0.0.0.0 --daemon-host 0.0.0.0 --disable-rpc-login --confirm-external-bind

**Comment by shopglobal** [comment]
That command is not safe

**Comment by shopglobal** [comment]
The monero-wallet-rpc should safely be run locally. Running the monero
wallet or RPC API open node commands with a 'hot wallet' could very well
leave you open to attack.

Try this instead

./monero-wallet-rpc --wallet-file monero22 --password Monero11
--rpc-bind-port 18083 --rpc-bind-ip 127.0.0.1 --disable-rpc-login

Look into making use of PM2 or something like forever for Ubuntu to run
monerod and utilities in the background.

**Comment by navneetboghani** [comment]
yes monerod is ruing in background in Ubuntu. so tell me how to access monero wallet rpc call to another server. for that i want to command to run wallet in background?

**Comment by shopglobal** [comment]
To run the local rpc or cli wallet from a daemon on another server you may
utilize the ```--daemon-host``` or ```--daemon-address``` flag and add
connection to a remote node.

Suppose then node is moneroworld.com:18090

You can run the wallet with ``` --daemon-address
http://moneroworld.com:18090```

You can run alternatively run a full node monerod and then connect wallet
or RPC to it in the way you're describing.

Hope this helps.

**Comment by navneetboghani** [comment]
you are right. but i am saying that if server is close then wallet rpc is not ruining in background. so i want to solution for run wallet rpc in background.

**Comment by jtgrassie** [comment]
Please keep GitHub issues to bug tracking not general usage questions. This question is already answered on the Monero StackExchange site. https://monero.stackexchange.com/a/3481/7493

**Comment by dEBRUYNE-1** [comment]
+resolved
