### ISSUE TITLE
[Feature request]: wallet RPC: get_address_index to retrieve the index of an address 

### ISSUE THREAD

**Issue by artyomsol** [monero-project/monero#4169]
As soon as main part of RPC methods accepts accont/subaddress index as a parameter It would be convenient to have a method to retrieve the subaddress index (major and minor) having the address provided. Only if the address belongs to the one of wallet's accounts obviously.
It should be a method reversal to the `get_address`.
#### Inputs
* `address` - string; The 95-character hex address string.
#### Outputs
* `subaddr_index` - (Optional) subaddress index if found:
* * `major` - unsigned int; Account index for the subaddress.
* * `minor` - unsigned int; Index of the subaddress in the account.

**Comment by stoffu** [comment]
#4170

**Comment by moneromooo-monero** [comment]
+resolved
