### ISSUE TITLE
wallet_rpc: invalid jsonrpc value of error response

### ISSUE THREAD

**Issue by artyomsol** [monero-project/monero#4175]
Wallet _RPC response contains empty string in `jsonrpc` member of error response. 

Build version affected: `0.12.3.0`

#### Steps to reproduce
1. Post improper JSON query to RPC 
```
{"jsonrpc":"2.0","id":"0",
	"method":"transfer",
	"params":{
		"destinations": [
				{
					"amount": 1000000000000000000000000,
					"address": "SOME VALID ADDRESS"
				}
			]
	}
}
```
2. Get the error response
```
{
  "error": {
    "code": -32700,
    "message": "Parse error"
  },
  "id": 0,
  "jsonrpc": ""
}
```
See the `"jsonrpc": ""` which [MUST](https://www.jsonrpc.org/specification#response_object) be `"2.0"`

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4177

**Comment by moneromooo-monero** [comment]
+resolved
