### ISSUE TITLE
Ledger Nano S not found, Fedora Linux

### ISSUE THREAD

**Issue by conclusionmurray** [monero-project/monero#4184]
f77bb740	ERROR	default	src/device/device.cpp:60	device not found in registry: 'Ledger'

when creating wallet, gui and cli

**Comment by moneromooo-monero** [comment]
You built it yourself, and without building ledger in, didn't you ?
If so, build again, making sure ledger is audit in. Check the output by cmake. It needs libpcsc-lite at least.

**Comment by conclusionmurray** [comment]
I downloaded the latest release, should have mentioned that. I tried the x64 version cli and that gave me; Error: failed to generate new wallet: Fail SCard API : (2148532253) Service not available. Device=0, hCard=0, hContext=0

I can try to compile it myself. The ledger is working with ledger live and other applications (tronscan)

**Comment by moneromooo-monero** [comment]
That's odd, this'd mean those binaries were built without ledger support. I'll ask around.

**Comment by dEBRUYNE-1** [comment]
@conclusionmurray - Have you properly followed all sufficiently prepared steps (i.e. the 5 steps after "We first have to ensure that we're sufficiently prepared. This entails the following:")?

https://monero.stackexchange.com/questions/8503/how-do-i-generate-a-ledger-monero-wallet-with-the-cli-monero-wallet-cli

**Comment by TheCharlatan** [comment]
@conclusionmurray what is the output, if you run `pcsc_scan` in the terminal?

**Comment by conclusionmurray** [comment]
@TheCharlatan
 Reader 0: Ledger Nano S [Nano S] (0001) 00 00
  Card state: Card inserted
@dEBRUYNE-1 you did not derive that from my previous statement that I have the ledger working with other apps? I followed https://monero.stackexchange.com/questions/8695/how-do-i-on-windows-generate-a-ledger-monero-wallet-with-the-cli-and-subsequen

**Comment by dEBRUYNE-1** [comment]
@conclusionmurray - The "sufficiently prepared" steps can differ for other coins. For instance, for Bitcoin on Mac OS X, it's simply plug-and-play, whereas for Monero you have to follow a quite technical guide in order to ensure it works properly. On Windows, Monero is supposed to be plug-and-play though, but your initial comment did not list the operating system you were using. Anyway, paging @cslashm.

**Comment by conclusionmurray** [comment]
@dEBRUYNE-1 thank you for the second link, it complements @TheCharlatan post asking for a pcsc_scan result. pcscd is not installed by default on Fedora so I installed that and started the service.

Looking at your second link I can confirm the settings are there although the <key>ifdFriendlyName</key> has the value <string>Ledger Token</string>. Since the error is cannot find 'Ledger' in the registry I changed the value to that and restarted the service. same error, change it to 'Ledger Token' for good measure, no change.

I am very familiar with the nano and can tell you that there are no suprises when it comes to using monero. The 'sufficiently prepared' steps are equevilent to "have you unboxed your modem", "here is how to connect a power cord". 

https://gist.github.com/ptantiku/e53eaae96e5503a77774636b1f948424
Is required to get the device recognized for fedora, and if you look closely you see that the udev rules that ledgerwallet provides has a nonexistent user under fedora, hence the sed to whoami.
pcscd is not required for other applications (simplEOS, Tronscan and Ledger live (and previously chrome apps) ) to function, reading the information it is not clear to me that it is for the Monero app to interface with the ledger hardware.

**Comment by moneromooo-monero** [comment]
Somthing that seems really odd to me is that the "device not found in registry" and "Fail SCard API : (2148532253) Service not available." logs seem to be impossible to get at the same time. Please post the actual log (level 1,device\*:TRACE).

**Comment by conclusionmurray** [comment]
@moneromooo-monero I realised that one error came from the x64 and I have continued with the x86.
I tried, realising I have the service installed and running, and it is currently generating my wallet.

This would mean my problem is solved by installing pcsc-tools and starting pcscd and using the x64 version. I did try the command line option to start with so I will be using that wallet with the gui.

**Comment by joshpurvis** [comment]
Just wanted to drop a comment here for future searchers who land on this issue...

I was running into very similar problems on Manjaro Linux, I tried what @conclusionmurray suggested with `pcscd`, but no success. `pcsc_scan` was failing to detect the device, and when I ran `pcscd` in debug mode (using `pcscd -fd`), it said:

```
00000062 hotplug_libudev.c:729:HPRegisterForHotplugEvents() No bundle files in pcsc drivers directory: /usr/lib/pcsc/drivers
00000006 hotplug_libudev.c:730:HPRegisterForHotplugEvents() Disabling USB support for pcscd
```

I finally solved the problem by installing the latest `ccid` package (ccid-1.4.29-3-x86_64)

This is what tipped me off to the `ccid` package might needing updated: https://ludovicrousseau.blogspot.com/2013/11/linux-nfc-driver-conflicts-with-ccid.html
