### ISSUE TITLE
more rpc documentation

### ISSUE THREAD

**Issue by Herry143** [monero-project/monero#4211]
I want to know when the rpc documentation come?I need it very much because of my work!!!
![image](https://user-images.githubusercontent.com/24546264/43567442-651fcc24-9664-11e8-9b81-c9ae04022c92.png)

**Comment by el00ruobuob** [comment]
Daemon RPC is up to date. Walker RPC still needs à refresh.
By the way monero github issues is for big tracking. This should be asked specifically in monero-site repo.

**Comment by dEBRUYNE-1** [comment]
Please reopen this issue on the `monero-site` repository:

https://github.com/monero-project/monero-site

+invalid
