### ISSUE TITLE
Talos Security Advisory for Epee Levin Packet (TALOS-2018-0637)

### ISSUE THREAD

**Issue by regiwils** [monero-project/monero#4212]
TheCisco Talos team found a security vulnerability impacting Epee Levin Packet customers. As this is a sensitive security issue, this message is to request a PGP key for further communication. If a key is not received or is unavailable, an unencrypted report will be sent to this address in two business days. 

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. http://www.cisco.com/web/about/security/psirt/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

**Comment by moneromooo-monero** [comment]
Keys are in the tree. See https://github.com/monero-project/meta/blob/master/VULNERABILITY_RESPONSE_PROCESS.md

**Comment by hippich** [comment]
How bad it is?
