### ISSUE TITLE
Re-enumerating devices while monerod running with --data-dir on a USB drive causes the blockchain to become corrupt.

### ISSUE THREAD

**Issue by malixg** [monero-project/monero#4213]
I am running monerod on Windows 10 x64. My C: drive SSD doesn't have room for the blockchain on it, so I run monerod with --data-dir parameter referencing an external USB hard drive. I have to re-enumerate devices often, and if I ever forget to exit monerod while it's running, before re-enumerating, the whole blockchain becomes corrupt and I have to re-synch from scratch. This has happened to me 4 times and it's very frustrating. Thanks

**Comment by moneromooo-monero** [comment]
Please define "re-enumerate devices".

**Comment by malixg** [comment]
Go to Windows Device Manager, right click the root node (whatever your Computer Name is) and do Scan For Hardware Changes

**Comment by moneromooo-monero** [comment]
So I guess this just umounts and mounts the filesystem again or something like that. Looks like a Windows filesystem layer bug then.

I'd say "don't run monero until you've finished tinkering with your hardware" and "report a bug to MS' bug tracker if they have one" :)

**Comment by dEBRUYNE-1** [comment]
@moneromooo-monero: Would the `--db-sync-mode=safe` flag guard against a corruption in this particular scenario?

**Comment by moneromooo-monero** [comment]
No idea, you'd have to try it and see, but I doubt it does given mmap is used in all cases (that said, it's windows, so maybe there is a difference there).

In any case, if Windows somehow allows writes without error when they corrupt the file, it's a Windows bug (unless LMDB writes directly to the device, but I doubt it does).

**Comment by selsta** [comment]
There were no other reports about having to "re-enumerate devices", so I'll close this. If this continues to be an issue please comment and I can reopen.
