### ISSUE TITLE
Monero CLI wallet on Whonix

### ISSUE THREAD

**Issue by poopaapoopaa** [monero-project/monero#4222]
I run the following on Whonix 13 workstation:

>torsocks ./monero-wallet-cli --daemon-host xmrag4hf5xlabmob.onion:18081 --restore-height -1

Most features work well. But when I run a transaction using:

>transfer [addr] [amt] [payment_id]

I get the following error, multiple times:

>libunbound[12335:0] error: can’t create socket: Operation not permitted

The transaction actually works though. Is this error something that should concern me, and is there a way to avoid it? I saw that there are specific settings for Tails, but I'm not sure if they're relevant for Whonix.

**Comment by moneromooo-monero** [comment]
You can ignore, it's very likely to be a DNS check for a TXT record to get the "segregation height", which is not so relevant now. When this fails, it uses the hardcoded default, which is still good.
