### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by D4nte** [monero-project/monero#4226]
Hi,

When running `make release-test` the unit test fails. v0.12.3.0 from git. 
On Ubuntu 18.04 LTS, compiled locally. No special flags passed. All dev dependencies installed via apt.

```
$ uname -a
Linux nuc 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
The following tests FAILED:
          4 - unit_tests (Failed)
Errors while running CTest
Makefile:85: recipe for target 'test' failed
make[1]: *** [test] Error 8
```

Let me know what info you need.

[release_test.txt](https://github.com/monero-project/monero/files/2260248/release_test.txt)

**Comment by moneromooo-monero** [comment]
Run manually and see which one(s) fail(s). If it's just the DNS one, you can ignore it.

**Comment by radfish** [comment]
Also see PR #4165 regarding ringdb unit test failing.
Also, if you're running on an NFS share, Serialization.portability_wallet will also fail.

**Comment by D4nte** [comment]
No NFS share. It is indeed the DNS ones:
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] AddressFromURL.Failure
[  FAILED  ] DNSResolver.DNSSECSuccess
[  FAILED  ] DNSResolver.DNSSECFailure
```

**Comment by moneromooo-monero** [comment]
+duplicate
