### ISSUE TITLE
Failure to Access Ledger Wallet on Linux ( Fail SCard API error )

### ISSUE THREAD

**Issue by bbelo** [monero-project/monero#4237]
When trying to access my Ledger wallet created with monero-v0.12.2.0 I get this error:

`Couldn't open wallet: Fail SCard API : (2148532227) Invalid handle. Device=0, hCard=0, hContext=2090181845`

in both monero-gui-v0.12.3.0 and monero-v0.12.3.0

I have since found out, that switching the USB port helps to solve this issue. I believe that the concerned USB port producing this error is a USB3 port.

OS: ubuntu 16.04 LTS
HW: Generic Toshiba notebook

**Comment by wuzzap** [comment]
I have the same Issue. On every Usb Port i have. Cant solve it -.-

OS: Arch Linux
HW: Dell E7240 , Dell e6430, Asrock Z77

**Comment by moneromooo-monero** [comment]
So this problem is not with monero, but wit the pcsd software/config ?
