### ISSUE TITLE
LMDB v3 data format

### ISSUE THREAD

**Issue by troublesomepony** [monero-project/monero#4238]
After I merged latest git trunk from this repo to my codebase and did first launch Monero reformatted Blockchain database twice (from 1 to 2 and from 2 to 3). But now seems I lost compatibility with application software used Monero partially too. Please point me where you set this format param so I could check everythins (explorer is broken for example). Thanks.

**Comment by moneromooo-monero** [comment]
It's not clear what you're asking, but if you have software which reads off the database directly, then fix it to match. See the git log on src/blockchain_db/lmdb/db_lmdb.cpp for the specific changes.

+invalid

**Comment by stoffu** [comment]
@troublesomepony
If you want to make the explorer able to read the new db format, you need to rebuild it with the new Monero core library.
