### ISSUE TITLE
balance change

### ISSUE THREAD

**Issue by Herry143** [monero-project/monero#4239]
1,I have saved the wallet file in my computer,
2.and then someone send some monero to my wallet,
3.I use the code to check the balance of wallet,the result is that balance do not change?I want to know why
"
const monero = require('monero-nodejs-libwallet');
monero.openWallet({
	'path': path.join(__dirname, 'test-wallet'),
	'password': '123', 
	'network': 'mainnet',
	'daemonAddress': 'localhost:18081',
}).then((wallet) => console.log('New wallet succesfully created: ' + wallet.balance()))
   .catch((e) => console.log('Failed to create new wallet: ' + e));
"

**Comment by jtgrassie** [comment]
I was about to direct you to the monero-nodejs-libwallet github as this is not the place to ask about a 3rd party library, but you have already cross-posted.

Suggest you close this issue here.

**Comment by moneromooo-monero** [comment]
Does the problem happen without the javascript layer ?

**Comment by moneromooo-monero** [comment]
If there's no further information, I'll close this later.
In particular, whether the tx was mined already, and whether it behave the same without the javascript layer.

**Comment by moneromooo-monero** [comment]
No further info, closing. It's likely the wallet just needs refreshing.

Reopen if more info is available, and make sure the wallet is refreshed first.

+invalid
