### ISSUE TITLE
RPC Transfer Error -> No destinations for this transfer

### ISSUE THREAD

**Issue by i3bitcoin** [monero-project/monero#4244]
Hello, after the last update v0.12.3.0 I cannot send XMR to another addresses via Wallet RPC.

Inputs:

Array
(
    [destinations] => Array
        (
            [amount] => 210000000000
            [address] => Address
        )

    [payment_id] => Payment ID
    [mixin] => 0
    [unlock_time] => 0
)

Outputs:

Array
(
    [code] => -20
    [message] => No destinations for this transfer
)

**Comment by moneromooo-monero** [comment]
Please post the JSON you're sending.

**Comment by moneromooo-monero** [comment]
transfer does not have a destinations parameter. transfer_split does.
If you want to use transfer, use the destination parameter, but transfer_split is probably what you want.

**Comment by i3bitcoin** [comment]
The docs should be fixed then
https://github.com/monero-project/monero/wiki/Wallet-RPC-Documentation#transfer

Thanks for you help

**Comment by moneromooo-monero** [comment]
Actually, I was wrong. It's destinations. I must be confusing with something else.

**Comment by stoffu** [comment]
@i3bitcoin Your JSON is in a wrong format. `destinations` is supposed to be an array of object consisting of `address` and `amount`, so instead of 

```json
{"id":1,"method":"transfer","params":[{"destinations":{"amount":210000000000,"address":"address"},"payment_id":"payment_id","mixin":0,"unlock_time":0}]}
```

it should be

```json
{"id":1,"method":"transfer","params":{"destinations":[{"amount":210000000000,"address":"address"}],"payment_id":"payment_id","mixin":0,"unlock_time":0}}
```

**Comment by i3bitcoin** [comment]
@stoffu okay, now it works great!
Thank you guys!
