### ISSUE TITLE
[Clarification/Feature Request] Usage clarification/monero-blockchain-blackball RPC/CLI --FLAG Import/Export

### ISSUE THREAD

**Issue by Wigmnd** [monero-project/monero#4246]
**Clarification**

1. Usage of monero-blockchain-blackball to obtain known spent outputs between monero and the coins which hard forked off of it must be a on going event and not just preformed within a window of time after a coin hard forks correct?

**Feature Request**

1. --import-blackball-file arg (=FILE)    Flag for monero-wallet-cli to import a file containing outputs to blackball

2. RPC call to import blackballed output by output 

3. --export_blackball arg  (=FILE)     Flag for monero-wallet-cli to export the contents of .shared-ringdb to a file

4. RPC call to export the contents of .shared-ringdb to a file

3. This is dependent on if during importation of outputs to blackball a duplicity check is preformed between .shared-ringdb and the target file or user defined single output. If a duplicity check **is** preformed then a settable optional flag to disable checks for duplicates. In general and also to .1&.2 above

**Comment by Nathapon8899** [comment]
@Wigmnd   #Howto copy the text from the phone # because of the phone call /
#Thank you#

**Comment by moneromooo-monero** [comment]
You can  import a blackball file using the "blackball" command in monero-wallet-cli. If you want to add to the set, rather than replace the set, add "add" at the end. See the help.

You can export the backball list with:
```
mdb_dump -s blackballs-418015bb9ae982a1975da7d79277c2705727a56894ba0fb246adaabb1f4632e3 ~/.shared-ringdb/ | awk '/^ [0-9a-f]{64}/{print $1}'
```

**Comment by moneromooo-monero** [comment]
You can (and should) update the blackball list regularly. The current code works incrementally, but that's a new feature. There's also more code that's not PRed yet which decreases the amount of memory needed by a fair amount, which makes it much more usable (there's more work to do there though).
Ideally you'd run it again before you intend to make transactions, if you transact seldom.

**Comment by Wigmnd** [comment]
@moneromooo-monero , Thank you for the clarification and the method of how to export the blackball list from the shared-ringdb. I am closing the issue at this time as the request for the remaining features will be handled via a privately funded bounty with a pull request to follow.
