### ISSUE TITLE
 Arch gcc 8.2: fatal error: ustat.h: No such file or directory  #include <ustat.h>

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#4265]
```
/home/mwo/monero/src/common/util.cpp:41:10: fatal error: ustat.h: No such file or directory
 #include <ustat.h>
```
From what I found `ustat.h` has been deprecated in glibc and finally got removed in Arch. 

Found this https://github.com/zatrazz/glibc/blob/master/NEWS

> The obsolete function ustat is no longer available to newly linked
  binaries; the headers <ustat.h> and <sys/ustat.h> have been removed.  This
  function has been deprecated in favor of fstatfs and statfs.

**Comment by moneroexamples** [comment]
I removed the `ustat.h` and it it goes through compilation until some other errors which seem not related to ustat at all. 

```diff
diff --git a/src/common/util.cpp b/src/common/util.cpp
index 5e0d2726..25312bdd 100644
--- a/src/common/util.cpp
+++ b/src/common/util.cpp
@@ -38,7 +38,6 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <sys/resource.h>
-#include <ustat.h>
 #include <unistd.h>
 #include <dirent.h>
 #include <string.h>
```

**Comment by jtgrassie** [comment]
https://github.com/monero-project/monero/pull/4274
