### ISSUE TITLE
monerod in testnet says it needs upgrading ?

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#4277]
Hi.

I've just build latest `master` branch and monerod status gives me that there is an update needed (for some reason):

```
 monero-testnet-dev:~$ ./monerod --testnet status
Height: 1166281/1166281 (100.0%) on testnet, not mining, net hash 339 H/s, v8, update needed, 14(out)+0(in) connections, uptime 0d 0h 0m 41s
```

Any idea how to fix this?

**Comment by moneromooo-monero** [comment]
You can either ignore it, or comment out the message in the source. I'll go away when a new fork is set up, within about a month.

+invalid
