### ISSUE TITLE
Monero for Windows build exiting with Segmentation Fault error instantly

### ISSUE THREAD

**Issue by 0xA01** [monero-project/monero#4279]
Steps to Reproduce the bug:
 - Launch Windows10 in VirtualBox or Real Hardware
 - Prepare MSYS2 build environment following `README.md`
 - Run `make debug-static-win64` or `relese-static-win64`
 - Launch any binary from `build/(debug|release)/bin/` folder

![Monero Segmentation Failed Error](https://i.imgur.com/zRDbtQO.png)

Any thoughts on this? Some 3rd library may cause this error? What I should to downgrade first?

**Comment by moneromooo-monero** [comment]
Run with --log-level 4, see if anything gets printed.

Does it generate a core file?

**Comment by malbit** [comment]
Problem is with gcc. You probably did compile it with gcc 8.2 which under Msys2 building corrupted binaries. Compilation is finishing with no errors but binary file doesnt work. I did use mingw64 posix gcc 7.3 and compilation did finish normally with less warnings and bunaries works as them should
ttps://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.3.0/threads-posix/seh/x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z
After unpacking it just copy output folder to msys64 installation folder and replace files when ask for it. Default gcc included at msys2 toolchain has gcc 8.2 which has plenty issues

**Comment by iDunk5400** [comment]
This is a workaround
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index cab85358..56d7d500 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -567,10 +567,12 @@ else()
   add_cxx_flag_if_supported(-Wformat-security CXX_SECURITY_FLAGS)

   # -fstack-protector
-  add_c_flag_if_supported(-fstack-protector C_SECURITY_FLAGS)
-  add_cxx_flag_if_supported(-fstack-protector CXX_SECURITY_FLAGS)
-  add_c_flag_if_supported(-fstack-protector-strong C_SECURITY_FLAGS)
-  add_cxx_flag_if_supported(-fstack-protector-strong CXX_SECURITY_FLAGS)
+  if (NOT WIN32)
+    add_c_flag_if_supported(-fstack-protector C_SECURITY_FLAGS)
+    add_cxx_flag_if_supported(-fstack-protector CXX_SECURITY_FLAGS)
+    add_c_flag_if_supported(-fstack-protector-strong C_SECURITY_FLAGS)
+    add_cxx_flag_if_supported(-fstack-protector-strong CXX_SECURITY_FLAGS)
+  endif()

   # linker
   if (NOT WIN32)
```

**Comment by iDunk5400** [comment]
Looks like MSYS2 mantainer is running into issues with GCC 8,2 as well Alexpux/MINGW-packages#4283
While this is not the same type of issue, I got an internal compiler error with -fstack-clash-protection when testing #4178 with GCC 8.2.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4290

**Comment by moneromooo-monero** [comment]
It is currently included. I don't understand the second question. I don't use that software.

**Comment by 0xA01** [comment]
@moneromooo-monero nevermind on second question; Windows build seems still broken; I will notice on details later but `-fstack-protector` patch is not enough I guess.

**Comment by 0xA01** [comment]
@malbit please help seems file you linked is removed now! I need it for automated build( do you have a copy?

**Comment by 0xA01** [comment]
@malbit or maybe just wrong escaping: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.3.0/threads-posix/seh/x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z/download is still there sorry

**Comment by 0xA01** [comment]
@moneromooo-monero @fluffypony we can build @monero-project for Windows using AppVeyor and develop some basic automated acceptance test suite for example to look a version output using "monero-wallet-cli.exe --version" to check binary are **runnable** is it good idea or completely unnecessary  trash?

**Comment by moneromooo-monero** [comment]
I don't know that software. If you think it has value and you're volunteering to do this, then feel free.
Note that the monero buildbot has a windows machine and runs tests.

**Comment by iDunk5400** [comment]
#4290 has not yet been merged to master. It, along with #4295 (if you remembered to run `git submodule update` after #4105 was merged), enable building of Windows binaries that actually run.

**Comment by moneromooo-monero** [comment]
Oh, sorry, re-reading I missed the "fix" in the question :D

**Comment by moneromooo-monero** [comment]
It's now merged.

**Comment by 0xA01** [comment]
Yeah patch works
