### ISSUE TITLE
unable to build with 16.04

### ISSUE THREAD

**Issue by calidion** [monero-project/monero#4281]
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1206: recipe for target 'tests/unit_tests/unit_tests' failed
make[3]: *** [tests/unit_tests/unit_tests] Error 1
make[3]: Leaving directory '/home/eric/monero/build/release'
CMakeFiles/Makefile2:4425: recipe for target 'tests/unit_tests/CMakeFiles/unit_tests.dir/all' failed
make[2]: *** [tests/unit_tests/CMakeFiles/unit_tests.dir/all] Error 2
make[2]: Leaving directory '/home/eric/monero/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/eric/monero/build/release'
Makefile:64: recipe for target 'release-all' failed
make: *** [release-all] Error 2

**Comment by iDunk5400** [comment]
Seeing that you have tried to search for the answer, the way to compile tests is
```
sudo apt remove libgtest-dev
make clean
make
```
