### ISSUE TITLE
monero-wallet-rpc callback subscription

### ISSUE THREAD

**Issue by Revinand** [monero-project/monero#4284]
Hello, I found that some callback is called on a payment received or a new block in the wallet

https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L1416
https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L1717

but I can't find how to subscribe to these notifications. Is it possible somehow? And if yes, how can I do this?

**Comment by moneromooo-monero** [comment]
You override those functions on your derived class, like simplewallet does.

**Comment by Revinand** [comment]
so, to listen for a wallet events in a node.js app I should use https://github.com/exantech/monero-nodejs-libwallet for example? There is no zeromq implementation or some kind of bitcoin `walletnotify` option out of the box, right?

**Comment by Revinand** [comment]
ok, I got it. Thank you for the info
