### ISSUE TITLE
show_transfers bug

### ISSUE THREAD

**Issue by carrie143** [monero-project/monero#4285]
1.I have started the monero-wallet-cli service,"/monero-wallet-cli  --wallet-file /root/wallet_file/test-wallet --password xxxx"
2.I run the comand," show_transfers":to find the transaction history,the result follows:
![t](https://user-images.githubusercontent.com/24546264/44338097-7ee57880-a4af-11e8-8f16-04d263ac3d23.png)
My questions is that why the transctions which in red block have the "to" address detail,and the other transaction do not show the destination address?I guess may be ,these transactions is created before I restored wallet,so I create two new outgoing transactions,Still do not show the  destination address.I have no idea

**Comment by moneromooo-monero** [comment]
You are correct.

**Comment by Herry143** [comment]
why new transaction still do not show the destination address.?

**Comment by moneromooo-monero** [comment]
Oh I see, the two ones below the highlighted ones you mean ?
If you type "set", what value is there for "store-tx-info" ?

**Comment by iDunk5400** [comment]
The other sends were most likely done using a different wallet cache file.

**Comment by moneromooo-monero** [comment]
Or maybe crash/kill. Is this the case ?

**Comment by Herry143** [comment]
@iDunk5400 ,I use the same  wallet cache file to send the transactions

**Comment by Herry143** [comment]
1.yes,the two ones are new transactions that I send using the same the wallet file
2.what do you mean"If you type "set", what value is there for "store-tx-info"",I have no idea about the command "store-tx-info",where I should run it?

**Comment by moneromooo-monero** [comment]
After sending the transactions with the missing destination, did the wallet crash, or did you kill it without saving ?

store-tx-info is not a command. set is a command which will show a number of settings, including one called store-tx-info.

**Comment by moneromooo-monero** [comment]
ping

**Comment by fgimenez** [comment]
Sorry for reviving this old issue but i have the same problem, `set` shows `store-tx-info = 1` but i sill get `- 0 -` in the address field for most of the outgoing transactions, when i try `get_tx_key` on any of them I get `Error: no tx keys found for this txid`.

Any idea @moneromooo-monero ?

**Comment by fgimenez** [comment]
Running cli on `monero-x86_64-linux-gnu-v0.17.1.9`

**Comment by selsta** [comment]
No reply, closing.
