### ISSUE TITLE
please update root-zone trust-anchors in dns_utils.cpp

### ISSUE THREAD

**Issue by RoyArends** [monero-project/monero#4287]
Users of your software that enable DNSSEC will not be able to validate DNS after October the 11th 2018.

Your repository contains a dns_utils.cpp file without the new DNSSEC trust-anchors:

. IN DS 19036 8 2 49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
It should also include:

. IN DS 20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

More information can be found at: https://www.icann.org/resources/pages/ksk-rollover

Please don’t hesitate to get in touch.

Warmly,

Roy Arends
ICANN

**Comment by moneromooo-monero** [comment]
When should "IN DS 19036 8 2 49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5" be untrusted (we'll likely have both in use in next release) ?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4309

**Comment by mweinberg** [comment]
IF the client performs DNSSEC validation, THEN the client will not be able to perform DNS lookups against any signed records.  For example, I see that the client make TXT queries to updates.moneropulse.(net|org|se|co).  If the code performs DNSSEC validation (unclear to me), then this query will fail after the root zone is signed with KSK-2017 on Oct 11.

**Comment by moneromooo-monero** [comment]
Do you mean before the patch, or also after it ?

**Comment by mweinberg** [comment]
If nothing changes in the code, then starting on Oct 11 the client will not be able to do DNS queries on signed records IF DNSSEC validation is enforced.  If you add the second DS record (per Roy's recommendation above), then you won't have any problems on Oct 11 or afterward.

If you do not enforce DNSSEC validation, then nothing breaks.  But you should add the second DS record no matter what (good DNS hygiene).

**Comment by moneromooo-monero** [comment]
Do you mean if nothing changes in the code with the patch, or if nothing changes in the code without the patch ?

**Comment by mweinberg** [comment]
If you do not add the second DS record to dns_utils.cpp, then starting on Oct 11 the client will not be able to do DNS queries on signed records IF DNSSEC validation is enforced. 

Does the code enforce DNSSEC validation?

**Comment by moneromooo-monero** [comment]
OK, I'll take this to mean it's fine rather than infinite loop on this.

The code does enforce validation if there is a DNSSEC signature, but accepts unsigned data IIRC.

**Comment by mweinberg** [comment]
Then you will have a problem starting Oct 11.  For example, queries for updates.moneropulse.(net|org|se|co) will fail because this record is DNSSEC-signed.  I don't know what other important DNS queries are made by the client?  

Happy to help further as needed.

**Comment by mweinberg** [comment]
Sorry, I'm trying to be helpful and am supportive of Monero.  I now see:  https://github.com/monero-project/monero/pull/4309/commits/5083614ffa84109fccd754ee5509b25030bec9a6

Yes, this patch will fix the problem if it's applied to all clients before Oct 11.  Any client that is not patched will have the problem.

**Comment by moneromooo-monero** [comment]
OK, thanks. Since I can't test whether this actually works, it's blind :)
There should be a release in time, since we're forking on the 18th, a week later.

**Comment by mweinberg** [comment]
OK, good luck.  I'd stress to users that the forthcoming patch is important.  :-)  Go Monero!
