### ISSUE TITLE
Exchange

### ISSUE THREAD

**Issue by laugh26** [monero-project/monero#4289]
I want to add monero to my exchange, bitcoin and its family are working fine but monero is not. bitcoin have bitcoin.conf file with 
server=1
rpcport=18523
rpcallowip=11.11.11.11/0
rpcuser=bitcoinrpc
rpcpassword=12345
walletnotify=/var/www/html/cron/receive.sh %s

please how do i set monero.conf file. Thanks

**Comment by moneromooo-monero** [comment]
This is a bug tracker.

+invalid

**Comment by laugh26** [comment]
really ok, i have brain to do it myself.
