### ISSUE TITLE
Trouble generating cold wallet on PiZero - Illegal instruction

### ISSUE THREAD

**Issue by KnoAll** [monero-project/monero#4297]
I am trying to create a cold wallet on a PiZero. This is an ARMv6 processor, and I'm getting 'Illegal instruction' when running monero-wallet-cli. In my searching this appears to be an ARMv6 vs ARMv7 issue with the precompiled code. The Pi does not have any networking capabilities, so I'm following the instructions for how to compile on another Pi of the same ARMv6 that does have networking.
The instructions (including the part for building on Raspian Jessie) have gone smoothly so far, but at the 'make release' step i'm getting an error. 
Makefile:53: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 1

in the log file i see (among others)
CheckSymbolExists.c:(.text+0x38): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_a5c2a.dir/build.make:97: recipe for target 'cmTC_a5c2a' failed
make[2]: *** [cmTC_a5c2a] Error 1

**Comment by moneromooo-monero** [comment]
You want to link against libpthread. Does this work ?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3b93988..c9fcca7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -810,6 +810,8 @@ elseif(NOT MSVC)
   set(EXTRA_LIBRARIES ${RT})
 endif()
 
+set(EXTRA_LIBRARIES ${EXTRA_LIBRARIES} pthread)
+
 list(APPEND EXTRA_LIBRARIES ${CMAKE_DL_LIBS})
 
 option(USE_READLINE "Build with GNU readline support." ON)

```

**Comment by KnoAll** [comment]
I get an error when running this diff --git a/CMakeLists.txt b/CMakeLists.txt

diff: unrecognized option '--git'

**Comment by moneromooo-monero** [comment]
You use it by saving the patch in a file, then:

patch -p1 < filename-you-saved-it-in

**Comment by dEBRUYNE-1** [comment]
@KnoAll - You have to create a new text file in your working directory with moneromooo's patch. Practically speaking this works as follows:

1. Create a new text file in your working directory.

2. Add moneromooo's patch from this comment -> https://github.com/monero-project/monero/issues/4297#issuecomment-415714324

3. Save the file as patch.txt

4. In the terminal, type patch -p1 < patch.txt

5. The patch should now be applied and you can recompile thereafter.

**Comment by KnoAll** [comment]
Thank you @dEBRUYNE-1 that was very helpful. That did work and got me past the errors I was seeing previously.  Unfortunately now I am getting errors farther down the line.

`~/monero# make release
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 32-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled (using easylogging++)
-- Using OpenSSL include dir at /usr/include
-- Found miniupnpc API version 10
-- Using in-tree miniupnpc
CMake Error at external/CMakeLists.txt:42 (add_subdirectory):
  add_subdirectory given source "miniupnp/miniupnpc" which is not an existing
  directory.


CMake Error at external/CMakeLists.txt:44 (set_property):
  set_property could not find TARGET libminiupnpc-static.  Perhaps it has not
  yet been created.


CMake Error at external/CMakeLists.txt:48 (set_property):
  set_property could not find TARGET libminiupnpc-static.  Perhaps it has not
  yet been created.


-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 32-bit LMDB from source tree
-- Using PCSC include dir at /usr/include/PCSC
-- Building on armv6l for native
-- Using C security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- AES support not available on ARMv6
-- Setting FPU Flags for ARM Processors
-- Selecting VFP for ARMv6
CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:781 (find_package)


-- Found Boost Version: 106400
-- Found readline library at: /usr
-- Found Git: /usr/bin/git
-- Configuring incomplete, errors occurred!
See also "/root/monero/build/release/CMakeFiles/CMakeOutput.log".
See also "/root/monero/build/release/CMakeFiles/CMakeError.log".
Makefile:53: recipe for target 'cmake-release' failed
make: *** [cmake-release] Error 1
root@:~/monero#
`

**Comment by moneromooo-monero** [comment]
git submodule init && git submodule update, from the readme.

**Comment by moneromooo-monero** [comment]
You're out of memory. Use more memory. Kill firefox. Add swap. Don't use -j if you did.

**Comment by KnoAll** [comment]
@moneromooo-monero Unfortunately I was never able to get this working. I changed my approach and simply used your offline generator html package as all i was trying to do was create an offline wallet. 
Thanks for your help, and thanks for the html package too!
