### ISSUE TITLE
Demon log issue

### ISSUE THREAD

**Issue by wojtasss** [monero-project/monero#4300]
When I type any command and press enter, scroll is going to start of log and I need scroll down to see command result it is really annoying 

Monero Wallet GUI v0.12.3.0

**Comment by moneromooo-monero** [comment]
I this monerod, or the GUI itself ? If it's the GUI, then please file in https://github.com/monero-project/monero-core. If monerod, which platform ?

**Comment by wojtasss** [comment]
Yes, it is GUI that as I wrote on end of post

**Comment by moneromooo-monero** [comment]
The GUI binaries include monerod :)

**Comment by moneromooo-monero** [comment]
+invalid
