### ISSUE TITLE
Gnome GUI bug

### ISSUE THREAD

**Issue by devbordecraft** [monero-project/monero#4301]
There is a bug in the gnome desktop environment when two titles bars where displayed.
Here is the screenshot :
![screenshot](https://user-images.githubusercontent.com/36452299/44586330-a427fe80-a7af-11e8-9af5-ae473f5294ba.png)

**Comment by Gingeropolous** [comment]
the monero GUI is on a separate repo: https://github.com/monero-project/monero-gui

also, try finding the custom animations button in advanced settings.

**Comment by devbordecraft** [comment]
Ok, thank you

**Comment by moneromooo-monero** [comment]
It depends on whether the window manager heeds the "no decorations" hint AFAIK. And as Gingeropolous said.
