### ISSUE TITLE
monerod crashed

### ISSUE THREAD

**Issue by kenken64** [monero-project/monero#4303]
Uncaught exception! Error adding hard fork version to db transaction: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid

./monerod --log-level 3 --testnet --data-dir /mnt/d/bdata/monero --hide-my-port --no-igd

**Comment by kenken64** [comment]
Running on master branch windows 10 ubuntu 16.04 with admin rights

**Comment by moneromooo-monero** [comment]
32 bit or 64 bit OS ?

Did your machine/OS crash before, or did the power go out and you don't have a battery/UPS ?

**Comment by kenken64** [comment]
somehow i restart my windows 10 it works now !
