### ISSUE TITLE
sign_multisig error via JSON-RPC

### ISSUE THREAD

**Issue by sneurlax** [monero-project/monero#4327]
When attempting to sign a multisig tx via JSON-RPC, the error

```bash
{ error:
   { code: -35,
     message:
      'Failed to sign multisig tx: This signature was made with stale data: export fresh multisig data, which other participants must then use' },
  id: '0',
  jsonrpc: '2.0' }
```

is given erroneously.  The same sequence used in `monero-wallet-cli` is successful.  I've using my library [monerojs](https://github.com/monerojs/monerojs) but have confirmed that using regular curl commands doesn't work, either, as shown in [this snippet](https://www.irccloud.com/pastebin/jeJoGND9/)

[monero-wallet-rpc log level 2](https://dpaste.de/t5Qn) (some erroneous `boost::filesystem::exists(m_wallet_file, ignored_ec). THROW EXCEPTION: error::file_exists`s because [my unit tests](https://github.com/sneurlax/monerojs/blob/feature/multisig-tests/test/index_test.js#L1651-L2000) attempt to `create_wallet` every time)

**Comment by sneurlax** [comment]
This error originates from [wallet_rpc_server.cpp#L3110](https://github.com/monero-project/monero/blob/2e7bfd0de545d3031deb6242a1d1b219066f9465/src/wallet/wallet_rpc_server.cpp#L3110) which calls [wallet2::sign_multisig_tx](https://github.com/monero-project/monero/blob/13a34faeb09814121140e14e0af442714fa985f9/src/wallet/wallet2.cpp#L5658-L5758).  The error looks to steam from [line 5703's](https://github.com/monero-project/monero/blob/13a34faeb09814121140e14e0af442714fa985f9/src/wallet/wallet2.cpp#L5703) call to [wallet2::get_multisig_k](https://github.com/monero-project/monero/blob/13a34faeb09814121140e14e0af442714fa985f9/src/wallet/wallet2.cpp#L10632-L10645), which actually throws the `multisig_export_needed` error (`Failed to sign multisig tx: This signature was made with stale data...`)

As for a patch, I'll have to attempt it when I get back.

**Comment by moneromooo-monero** [comment]
Works for me (with two processes). You don't save your wallet after loading the multisig data, so when you reload it, you have stale data... Try again after saving the data where appropriate, and it should work.

**Comment by sneurlax** [comment]
I'll try that when I get back to my desk, thanks (and sorry if this was
frivolous.)

**Comment by sneurlax** [comment]
I found that the wallet state should be stored after both export and import.  Apologies again for being a noob
