### ISSUE TITLE
Unable to create genesis block (could not start syncing on empty blockchain)

### ISSUE THREAD

**Issue by 0xA01** [monero-project/monero#4343]
**Steps to reproduce**

1) Build Monero from git trunk
2) Run on empty blockchain (--data-dir folder)

**Solution fix** (if this is not _The Company Politics Feature_) 😅

> just additional m_height > 0 check to prevent -1 height index access

https://github.com/flakechain/flake-core/commit/b2ff1d75b76c3b2ced08d3a741becf17d975947b

**Comment by moneromooo-monero** [comment]
Works for me. Looking at the patch, it should only by buggy if you changed the code to have a version >= 4 right at the start, which should be forbidden by the consensus rules.

**Comment by jtgrassie** [comment]
This is not a Monero issue.

+ Invalid

**Comment by fluffypony** [comment]
Closed as invalid

**Comment by moneromooo-monero** [comment]
That said, I'd be OK adding such a change as a guard for forks which change rules this way, if a PR is made.

**Comment by 0xA01** [comment]
I thought Monero is more than just database slice but universal solution to manage Blockchain databases. Sorry guys you may be right sure.

**Comment by 0xA01** [comment]
It's like MySQL or MongoDB would work only with single database and you can't change some part of data for example always have table `test1` 😁.
