### ISSUE TITLE
[RYO Backport] Proper Unicode support on Windows

### ISSUE THREAD

**Issue by fireice-uk** [monero-project/monero#4351]
The approach that you took to read UCS2 glyphs from Windows command line doesn't work. Just try to create and restore a wallet with a Russian seed. The description of the problem is here https://github.com/ryo-currency/ryo-currency/pull/102 

Let me know if you want us to open source the fix.

**Comment by moneromooo-monero** [comment]
If it doesn't come with strings, sure. We've been waiting for a Windows coder to show up for ages.

**Comment by moneromooo-monero** [comment]
BTW, I had a quick look at the repo you linked, and it looks like one of your contributors is PRing some of our patches with attribution removed. Very not nice at all:
https://github.com/ryo-currency/ryo-currency/commit/aac5f3b1ddfd0555034ff14cfe138d264ad8949b

**Comment by moneromooo-monero** [comment]
Hmm, the patch is actually a bit different, though it does point to our patch. Hopefully most patches aren't that way.

**Comment by fireice-uk** [comment]
> BTW, I had a quick look at the repo you linked, and it looks like one of your contributors is PRing some of our patches with attribution removed. Very not nice at all: ryo-currency/ryo-currency@aac5f3b

Would you like us to add the relevant person as a co-author? Cherry-picking between the project is actually impossible since we use different code styling rules.

**Comment by psychocrypt** [comment]
`ash on my main` I added each time the original pull request to the commit description but have not used the co-author feature. I will do it next time more clean, sry.

**Comment by moneromooo-monero** [comment]
If you PR this, can you please put the line input in util directly (moved from simplewallet) ? It's useful for other bits.
