### ISSUE TITLE
`wallet2::import_multisig` doesn't signal about error if refresh failed

### ISSUE THREAD

**Issue by naughtyfox** [monero-project/monero#4359]
We encountered the following bug - if refresh error happens like wallet disconnected from daemon when  multisig wallets exchange with multisig key images `wallet2::import_multisig` function does not indicate that operation is failed. Client code cannot determine if operation has been successful. This happens because sync exception just captured and wasn't propogated to the calling code (https://github.com/monero-project/monero/blob/fad88e18a9795b377676ad6f63c1772868e0d761/src/wallet/wallet2.cpp#L10881).

This kind of error occurs especially often on mobile devices where connectivity may be not stable.

**Comment by moneromooo-monero** [comment]
+resolved
