### ISSUE TITLE
monerod log-file spamming by <boost::bad_weak_ptr>

### ISSUE THREAD

**Issue by trasherdk** [monero-project/monero#4365]
I'm currently running 3 nodes and 2 wallets (cli). Both wallets connected to a separate node,
with mining running on their respective nodes. No problem, nothing in the log-file.
Issuing stop_mining in one wallet, triggered the following log entries, that keeps repeating.
The node is still syncing, and functioning, but only the excessive logging, roughly 10-15 min. apart.

	
	 [miner 0] INFO global  src/cryptonote_basic/miner.cpp:508  Miner thread stopped [0]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:124  Exception: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_weak_ptr> >
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:125  Unwound call stack:
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [1] ${HOME}/bin/monerod:tools::log_stack_trace(char const*)+0x9e2 [0x565036352842]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [2] ${HOME}/bin/monerod:__cxa_throw+0x14b [0x5650363543eb]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [3] ${HOME}/bin/monerod+0x62cc95 [0x5650360c5c95]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [4] ${HOME}/bin/monerod:epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::safe_shared_from_this()+0xd9 [0x565036110ff9]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [5] ${HOME}/bin/monerod:epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::close()+0x95 [0x565036139585]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [6] ${HOME}/bin/monerod:epee::levin::async_protocol_handler_config<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> >::close(boost::uuids::uuid)+0x358 [0x5650360ef758]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [7] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::do_handshake_with_peer(unsigned long&, nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context>&, bool)+0x622 [0x5650361773e2]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [8] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::try_to_connect_and_handshake_with_new_peer(epee::net_utils::network_address const&, bool, unsigned long, nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::PeerType, unsigned long)+0xa1c [0x56503619939c]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [9] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::connect_to_seed()+0x30b [0x56503619d8fb]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [10] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::connections_maker()+0x523 [0x56503619ea83]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [11] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::idle_worker()+0x15e [0x5650360d5aae]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [12] ${HOME}/bin/monerod:epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::global_timer_handler(boost::shared_ptr<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::idle_callback_conext_base>)+0x67 [0x56503610b8e7]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [13] ${HOME}/bin/monerod:boost::asio::detail::wait_handler<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::shared_ptr<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::idle_callback_conext_base> >, boost::_bi::list2<boost::_bi::value<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >*>, boost::_bi::value<boost::shared_ptr<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::idle_callback_conext_base> > > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x265 [0x5650360d6865]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [14] ${HOME}/bin/monerod:epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::worker_thread()+0x10ee [0x56503610685e]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [15] /usr/lib64/libboost_thread.so.1.59.0+0x115a5 [0x7fc0ddb675a5]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [16] /lib64/libpthread.so.0+0x7684 [0x7fc0dd0a4684]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163  [17] /lib64/libc.so.6:clone+0x6d [0x7fc0dcddaeed]
	 [P2P4] INFO stacktrace src/common/stack_trace.cpp:163
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:124  Exception: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_weak_ptr> >
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:125  Unwound call stack:
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [1] ${HOME}/bin/monerod:tools::log_stack_trace(char const*)+0x9e2 [0x565036352842]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [2] ${HOME}/bin/monerod:__cxa_throw+0x14b [0x5650363543eb]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [3] ${HOME}/bin/monerod+0x62cc95 [0x5650360c5c95]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [4] ${HOME}/bin/monerod:epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::safe_shared_from_this()+0xd9 [0x565036110ff9]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [5] ${HOME}/bin/monerod:epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::close()+0x95 [0x565036139585]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [6] ${HOME}/bin/monerod:epee::levin::async_protocol_handler_config<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> >::close(boost::uuids::uuid)+0x358 [0x5650360ef758]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [7] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::do_handshake_with_peer(unsigned long&, nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context>&, bool)+0x622 [0x5650361773e2]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [8] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::try_to_connect_and_handshake_with_new_peer(epee::net_utils::network_address const&, bool, unsigned long, nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::PeerType, unsigned long)+0xa1c [0x56503619939c]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [9] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::connect_to_seed()+0x30b [0x56503619d8fb]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [10] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::connections_maker()+0x523 [0x56503619ea83]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [11] ${HOME}/bin/monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::idle_worker()+0x15e [0x5650360d5aae]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [12] ${HOME}/bin/monerod:epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::global_timer_handler(boost::shared_ptr<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::idle_callback_conext_base>)+0x67 [0x56503610b8e7]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [13] ${HOME}/bin/monerod:boost::asio::detail::wait_handler<boost::_bi::bind_t<bool, boost::_mfi::mf1<bool, epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::shared_ptr<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::idle_callback_conext_base> >, boost::_bi::list2<boost::_bi::value<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >*>, boost::_bi::value<boost::shared_ptr<epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::idle_callback_conext_base> > > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x265 [0x5650360d6865]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [14] ${HOME}/bin/monerod:epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::worker_thread()+0x10ee [0x56503610685e]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [15] /usr/lib64/libboost_thread.so.1.59.0+0x115a5 [0x7fc0ddb675a5]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [16] /lib64/libpthread.so.0+0x7684 [0x7fc0dd0a4684]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163  [17] /lib64/libc.so.6:clone+0x6d [0x7fc0dcddaeed]
	 [P2P8] INFO stacktrace src/common/stack_trace.cpp:163

**Comment by moneromooo-monero** [comment]
Do you have 979105b ?

**Comment by trasherdk** [comment]
Yes, I have applied (979105b) patch. 
The second wallet, when issuing stop_mining, did not do anything to the second node, other than stopping mining. Repeated start/stop mining with no extra logging ??? Something else is triggering this.

**Comment by trasherdk** [comment]
My setup:
xmr-stak (win 10) -> monero-stratum -> node-1 -> node-2 (node-2 <-> node-3)
wallet-1 -> node-2
wallet-2 -> node-3
Does that make any sense?

Stopping/Starting "node-2", caused "node-3" to freak out. Same log output as above.
Seems like node-3 didn't like to be alone, without any peers.

**Comment by moneromooo-monero** [comment]
Looking at the code, it seems to behave as expected.

**Comment by trasherdk** [comment]
What is the right method to shut down a detached monerod?
So far I've been using SIGHUP.

**Comment by moneromooo-monero** [comment]
monerod exit

**Comment by moneromooo-monero** [comment]
I've looked and this is all fine.

**Comment by moneromooo-monero** [comment]
Those are fine.

**Comment by moneromooo-monero** [comment]
Fixed in #6269
