### ISSUE TITLE
sign_transfer method not found!

### ISSUE THREAD

**Issue by lhfly5201314** [monero-project/monero#4367]
Hi,everyone!
I tried to use the sign_transfer function to sign my raw-transaction in javascript code,but it returned the below error:
{ error: { code: -32601, message: 'Method not found' }

I tried the sign_transfer command in monero-wallet-cli,it works.

Why does it show 'method found' when I used in my javascript??
I reviewed the source code.The sign_transfer exist in the wallet_rpc_server.cpp file.
https://github.com/monero-project/monero/blob/master/src/wallet/wallet_rpc_server.cpp
And Why the monero-wallet-rpc docs don't list the sign_transfer func???Only describe the sign() func...
https://getmonero.org/resources/developer-guides/wallet-rpc.html#sign
It's really strange!

One more question,if I wanna use the curl + sign_transfer to test,what param keys should I use??The docs really suck!

Thanks,guys!

**Comment by moneromooo-monero** [comment]
Since there's no information apart from a single sentence, I assume you're sending a JSON request to the wallet RPC server. Post the JSON query you're sending. Also double check you're actually asking the wallet RPC server (yes, some people do happen to ask the wrong server). Also state which version of monero you're running (commit hash if possible, human readable version otherwise).

**Comment by lhfly5201314** [comment]
Any help???

**Comment by lhfly5201314** [comment]
@moneromooo-monero Hi,friend!Thanks for your advice!Yes,I am trying to send a JSON request to the monero-wallet-rpc server.My monerod and  monero-wallet-rpc both are version  v0.12.3.0.
I tried to curl some other rpc functions to the wallet-rpc server,such as getheight,getbalance ,sign and transfer.They work well.
But when I tried the sign_transfer,I don't know how to write the params,
curl -X POST http://127.0.0.1:15000/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"sign_transfer","params":{""}' -H 'Content-Type: application/json'
When I send empty "params",it returned "Parse error".

monero-wallet-rpc server runs on the 15000 port.Have u ever tried to use the sign_transfer method with curl or in javascript code,not in the monero-wallet-cli???
I tried to use the sign_transfer in js code.It returns "Method not found",not "parse error"
I couldn't get any info about the sign_transfer on the Wallet RPC doc:
https://getmonero.org/resources/developer-guides/wallet-rpc.html
only sign() exists!

**Comment by moneromooo-monero** [comment]
For sign_transfer, there should be one parameter called unsigned_txset, containing the hexadecimal representation of the transaction data to be signed (which you get from the transfer calls when your wallet does not have a spend key).

Note that I think "params":{""} is invalid. If params are empty for a given call, use "params":{} instead.

**Comment by lhfly5201314** [comment]
@moneromooo-monero Hi,friend!.Why isn't  there  any info about the sign_transfer func on the official moneor-wallet-rpc doc??I tried it in the javscript code again,still "Method not found",and the sign() works well!

**Comment by moneromooo-monero** [comment]
Too new I guess. Are you using a recent master ?

**Comment by lhfly5201314** [comment]
Yeah,I am using the latest version..
Maybe I should try some older version???

**Comment by xiphon** [comment]
> curl -X POST http://127.0.0.1:15000/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"sign_transfer","params":{""}' -H 'Content-Type: application/json'
> When I send empty "params",it returned "Parse error".

You have to pass `unsigned_txset` param.

```
curl -X POST http://127.0.0.1:15000/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"sign_transfer","params":{"unsigned_txset":"UNSIGNED_TX_HEX"}' -H 'Content-Type: application/json'
```

**Comment by el00ruobuob** [comment]
@lhfly5201314 the doc is being refreshed. A pull request is pending reviews. You can find the up-to-date instructions there https://github.com/monero-project/monero-site/pull/854

**Comment by lhfly5201314** [comment]
> > curl -X POST http://127.0.0.1:15000/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"sign_transfer","params":{""}' -H 'Content-Type: application/json'
> > When I send empty "params",it returned "Parse error".
> 
> You have to pass `unsigned_txset` param.
> 
> ```
> curl -X POST http://127.0.0.1:15000/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"sign_transfer","params":{"unsigned_txset":"UNSIGNED_TX_HEX"}' -H 'Content-Type: application/json'
> ```

Thanks,friend!

**Comment by lhfly5201314** [comment]
> @lhfly5201314 the doc is being refreshed. A pull request is pending reviews. You can find the up-to-date instructions there [monero-project/monero-site#854](https://github.com/monero-project/monero-site/pull/854)

Thanks!Really good job!
