### ISSUE TITLE
monero-wallet-cli logical error!

### ISSUE THREAD

**Issue by ncnylon** [monero-project/monero#4370]
Hi there:

I was authorized by an crypto currency exchange to take a penetration testing for the current version (v0.12.3.0) of Monero wallet, I was following the method which posted by [this,](https://hackerone.com/reports/379049) and I can confirmed that the wallet was operating correctly and there is no any side effects on our customer's services.

After that, I want to transfer ~1.685XMR back to my another account, but the command line tool of Monero wallet cannot process correctly. Here's my steps to get the error message:

\[wallet <wallet_addr>\]: version
Monero 'Lithium Luna' (v0.12.3.0-release)
[wallet <wallet_addr>]: show_transfers
 1657607     in       2018-09-09       0.690000000000 <txid1> 0000000000000000 0 - 
 1657622     in       2018-09-09       1.000223730000 <txid2> 0000000000000000 0 - 
 1657635    out       2018-09-09       1.500000000000 <txid3> <16 chars HEX code> 0.002195060000 <dummy_addr>: 1.500000000000 0 - 
 1657660     in       2018-09-09       1.497255825000 <txid4> 0000000000000000 0 - 
[wallet <wallet_addr>]: transfer_original <dest_addr> 1.685                                                                     
Wallet password: 
Error: internal error: the tx uses funds from multiple accounts
Error: There was an error, which could mean the node may be trying to get you to retry creating a transaction, and zero in on which outputs you own. Or it could be a bona fide error. It may be prudent to disconnect from this node, and not try to send a tranasction immediately. Alternatively, connect to another node so the original node cannot correlate information.
[wallet <wallet_addr>]:

Also, I tried used another mobile app to transfer, no go. Because they are calling the monero-wallet-rpc command.

Until now, I can only receive XMR from others but fail to send. Is that mean my 1.686 XMR was freeze?

**Comment by moneromooo-monero** [comment]
Don't use transfer_original, it's obsolete and unmaintained, and about to be removed. Can you repro it with transfer ?

**Comment by ncnylon** [comment]
> 
> 
> Don't use transfer_original, it's obsolete and unmaintained, and about to be removed. Can you repro it with transfer ?

If using the transfer command, output was: 

> transaction was not constructed.

Then no any relating logs found in bitmonero.log.

I think the problem is: when the wallet calculate the unlocked balance, there is an error on previous transactions which is notated by <dummy_address>, so it will not be approved by the remote node and cannot be processed further.

**Comment by moneromooo-monero** [comment]
In the wallet:
set_log 2
Then try again
Then post the resulting log to fpaste.org or paste.debian.net or a gist.

**Comment by ncnylon** [comment]
I am using the command:

> sweep_all <dist_addr> <payment_id>

then get the result in [http://paste.debian.net/1042086/](url)

Thanks for your reply.

**Comment by moneromooo-monero** [comment]
That's fixed in #4330.

**Comment by moneromooo-monero** [comment]
+resolved
