### ISSUE TITLE
Dockerfile build problem

### ISSUE THREAD

**Issue by opsxcq** [monero-project/monero#4396]
While trying to build the current `Dockerfile` I get the following error

```
Removing intermediate container 36e7352bd87c
 ---> f4bc1ff22822
Step 35/40 : COPY --from=builder /src/build/release/bin/* /usr/local/bin/
COPY failed: no source files were specified
```

Since there isn't any file to be copied (Build files are stored on `/src/build/Linux/master/release`) the build fails.

**Comment by moneromooo-monero** [comment]
+resolved
