### ISSUE TITLE
monero-wallet-rpc get_incoming_transfers does not provide the account index

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#4403]
Per the [RPC](https://getmonero.org/resources/developer-guides/wallet-rpc.html#incoming_transfers) documentation, `incoming_transfers` does not return the account index so it is not possible to associate the transaction with an account.

This structure which is consistent with other methods is recommended:

```
"subaddr_index": {
  "major": 0,
  "minor": 1,
}
```

**Comment by woodser** [comment]
Ok so it is possible to associate returned transactions with the account because it's either 0 or the account index specified in the request.  Thank you.

The documentation should be updated to indicate it defaults to 0.  I can make that PR.

It probably does not make sense to return all transactions across all accounts since this behavior is inconsistent with the other transfer methods.

It would be my preference that the account index be returned like the other transfer methods but I understand this changes the return structure.

**Comment by el00ruobuob** [comment]
No need to create a new PR, just give your thoughts on the actual one https://repo.getmonero.org/monero-project/monero-site/merge_requests/854  
But I keep in mind to add the default to 0 on every account_index input.

**Comment by moneromooo-monero** [comment]
https://github.com/moneromooo-monero/bitmonero/tree/airpc should fix it. Can you check it works on your test case ?

**Comment by woodser** [comment]
This will work on my test case although it does introduce additional inconsistency in the API.  Perhaps down the road we will want to release a new version of the API or some of its methods with a focus on consistency?

Can `address` be added as a field returned from incoming transfers also?

**Comment by moneromooo-monero** [comment]
What inconsistency does it add ?

**Comment by woodser** [comment]
Unless I'm mistaken the return structure will be:

```
{
  "subaddr_index": 0,
  "account_index": 0
  ...
}
```

Unlike the others which are:
```
"subaddr_index": {
  "major": 0,
  "minor": 1,
},
...
```

**Comment by moneromooo-monero** [comment]
I see. Easy to fix.

**Comment by moneromooo-monero** [comment]
I've updated the tree to return the pair as subaddr_index as other RPCs do. I'll deem it fine since we have an incompatible wallet RPC change anyway (from v1 to v2) so I'll ride on its coattails. Not quite optimal but hey.
