### ISSUE TITLE
Error starting server: bind: Cannot assign requested address

### ISSUE THREAD

**Issue by dawiepoolman** [monero-project/monero#4415]
Hi guys

w.r.t setup guide [here](https://pinode.weebly.com/monero-node-for-pi-3-or-armv7-devices-no-lcd-display.html)

I am trying to launch monerod for the first time on my RPi3B+ and binding my laptop over ssh to port 4008 with cmd:

./monero-v0.12.3.0/monerod --rpc-bind-ip=192.168.1.22 --rpc-bind-port=4008 --confirm-external-bind

I get error:

FATAL net contrib/epee/include/net/abstract_tcp_server2.inl:849 Error starting server: bind: Cannot assign requested address

Any ideas why my laptop from where I ssh into the pi cant seem to get its IP assigned?  Any port fwd required on my router (sounds unlikely on the LAN)?

Thx

**Comment by moneromooo-monero** [comment]
Are you sure 192.168.1.22 is the IP assigned to a local interface you are allowed to bind to ?
Does "ifconfig" confirm ?

**Comment by dawiepoolman** [comment]
Hi moneromoo
Indeed it does:
![image](https://user-images.githubusercontent.com/2351212/45917517-2ff97d00-be79-11e8-96ee-631fbfab40c8.png)

**Comment by moneromooo-monero** [comment]
Can you bind any other daemon to that IP address from the same user account ?

**Comment by moneromooo-monero** [comment]
You'd install something like a small http server that your distro knows about for instance, and hope they have a way to bind to a specific address.

**Comment by dawiepoolman** [comment]
Ty, while I try and Google like the noob I am to this, herewith a full screenshot of the error just to make sure I am not missing anything else that might be obvious:
![image](https://user-images.githubusercontent.com/2351212/45917792-1fe39c80-be7d-11e8-9ac0-f23ab645e5d4.png)

**Comment by moneromooo-monero** [comment]
Try: nc -l 192.168.1.22 4008

**Comment by dawiepoolman** [comment]
nc: Cannot assign requested address

**Comment by iDunk5400** [comment]
I might be missing something here, but why are you trying to bind monerod on your Pi to your Windows laptop address ?

**Comment by dawiepoolman** [comment]
I preferably want the gui (and wallet) to live client side on my laptop like the installation instructions in the op post

**Comment by iDunk5400** [comment]
But you need to bind monerod on your Pi to your Pi IP, not your Windows laptop IP.

**Comment by dawiepoolman** [comment]
Thank you!
It works now.  I guess the guide was ambiguous when it said:

 To run the node for the first time type

                             ./monero-v0.12.3.0/monerod --rpc-bind-ip=192.168.XX.XX --rpc-bind-port=4008 --confirm-external-bind

​**Where XX.XX is the IP address you have been using to SSH to the Pi.

**Comment by iDunk5400** [comment]
Yes, not the source address you're sshing from, but the destination address you're sshing to :)

**Comment by dawiepoolman** [comment]
Facepalm.  Makes sense now ty.  Sorry for posting this drama.
So I learn every day.  You guys were super responsive.
Thx again.  Amazing community.
