### ISSUE TITLE
Streamline pull request review process

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero#4421]
A bunch of pull requests were merged by @fluffypony which did not receive a single mark of approval (except of fluffy's). This "review process" needs to be improved.
Monero is a community project and it is unacceptable to merge obviously broken changes such as this one: https://github.com/monero-project/monero/pull/4401/files#diff-04c6e90faac2675aa89e2176d2eec7d8R119

**Comment by moneromooo-monero** [comment]
Review it then ?

**Comment by leonklingele** [comment]
The PR I've linked to was open for a mere 3 days. It wasn't critical to merge that early.
Why not add a bot which pings various GitHub accounts if a pull request didn't receive any reviews within 7 days or so. Something similar to [this](https://github.com/facebookarchive/mention-bot) maybe? I can help in creating a custom one too.

**Comment by plavirudar** [comment]
What's wrong with the PR you linked? I don't see anything "obviously broken" with it.

**Comment by TheCharlatan** [comment]
@plavirudar conflict markers were left inside the commit for example.

**Comment by moneromooo-monero** [comment]
The reason it was merged early is that we need to release asap now. Otherwise PRs stay open for ~10 days at least. But even then, some PRs stay unreviewed for weeks. The people who review more than the occasional PR are myself, stoffu, and sometimes vtnerd. It will only become better if more people (with the skills to do do obviously) start reviewing. You don't even have to review everything, just PRs that didn't get reviewed yet. It adds up.

**Comment by Gingeropolous** [comment]
@leonklingele , yes make the bot! just do it. don't ask permission, seek approval, confer with the spirits, throw the I ching... just do it. 

unofficial monero dev slogan, hacked from nike: just code it

**Comment by TheCharlatan** [comment]
I suggest that labels are added to the pull requests. I could then easily sort through them and look for changes to the build system for example. This is something maintainers would have to do though.

**Comment by leonklingele** [comment]
While examining various GitHub bots, I found the following which might be of interest:

1. https://github.com/probot/stale Auto-replies to Pull Requests after a period of inactivity
2. https://github.com/facebookarchive/mention-bot @-mentions potential reviewers (based on their previous contributions and reviews)
3. https://probot.github.io/apps/minimum-reviews/ Prevents merging of unreviewed Pull Requests

Who can set them up?

**Comment by selsta** [comment]
Our CI setup is way better these days. I'm closing this as I don't think there will be much more discussion here. Personally I'm not a fan of bots that just add noise.
