### ISSUE TITLE
get_transfer_by_txid RPC method still returns single transfer when multiple are present 

### ISSUE THREAD

**Issue by magnoliafan** [monero-project/monero#4436]
Monero transaction can contain multiple transfers to different subaddresses of one account. In this case not all transfers can be shown. Maybe, wallet rpc should have get_transfers_by_txid, that shows all transfers of a transaction related to wallet, or chosen account?

**Comment by magnoliafan** [comment]
Or add filter_by_txid flag and txid param to get_transfers

**Comment by moneromooo-monero** [comment]
Works for me. Are you sure you passed the right account_index ?

**Comment by magnoliafan** [comment]
Yes. But single transaction have two outputs, first to subaddress no1, and second to subaddress no2. Same account index 0.

**Comment by moneromooo-monero** [comment]
Ah, I had misunderstood, I sent to different accounts from the same wallet. It does seem buggy now.

**Comment by magnoliafan** [comment]
What do you think about get_transfers_by_txid i've descibed above?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4484

**Comment by moneromooo-monero** [comment]
+resolved
