### ISSUE TITLE
 Help with  Parameters that is needed!

### ISSUE THREAD

**Issue by jdscott0** [monero-project/monero#4442]
Having trouble with my monero wallet gui 0.12.3.0 , the issue is Exactly one parameter is needed: check, download, or update. How to fix this

**Comment by moneromooo-monero** [comment]
Not much info. Describe what you did, and where is this message showing.

**Comment by jdscott0** [comment]
Okay, I went to setting because  my balance is 0.00, and then  to show status [9/25/2018 3:22 PM] Height: 502372/502372 (100.0%) on mainnet, not mining, net hash 17.51 MH/s, v1, update needed, 0(out)+0(in) connections, uptime 0d 0h 4m 27s. Then I went to th powershell window and I retrieve this Exactly one parameter is needed: check, download, or update.So now I stuck also receive this  [0m
2018-09-25 20:18:06.115 [P2P0]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1380    [1;31m**********************************************************************[0m
2018-09-25 20:18:06.171 [P2P0]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1381    [1;31mLast scheduled hard fork time shows a daemon update is needed soon.[0m
2018-09-25 20:18:06.228 [P2P0]  WARN    global  src/cryptonote_core/cryptonote_core.cpp:1382    [1;31m**********************************************************************[0m
help
Monero 'Lithium Luna' (v0.12.3.0-release)

**Comment by moneromooo-monero** [comment]
Your daemon is synced to about a third of the blockchain, and doesn't have any network connection. You seem to have an OK version so not sure why it could not find any in 4 minutes.

About the "one parameter is needed: check, download, or update." message, what is outputting it ? It's not clear in your post.

**Comment by iDunk5400** [comment]
The easiest way to fix that issue is not to type `update` in the daemon window of your GUI.

**Comment by jdscott0** [comment]
> The easiest way to fix that issue is not to type `update` in the daemon window of your GUI.

**Comment by jdscott0** [comment]
> Your daemon is synced to about a third of the blockchain, and doesn't have any network connection. You seem to have an OK version so not sure why it could not find any in 4 minutes.
> 
> About the "one parameter is needed: check, download, or update." message, what is outputting it ? It's not clear in your post.

The GUI and I taught when you have 100% you was connect to the network, so what I have to do next?
