### ISSUE TITLE
Monerod 0.12.3.0 seg fault on MacOS 10.13.6

### ISSUE THREAD

**Issue by Zaphod101010** [monero-project/monero#4454]
node had been running for a few weeks.  I woke up this morning and it had crashed at some point over night.

[monerod_2018-09-25-183645.log](https://github.com/monero-project/monero/files/2419955/monerod_2018-09-25-183645.log)

**Comment by moneromooo-monero** [comment]
Looks like an internal boost function called when a network operation has completed. It could be a boost bug, or monerod deleting an object which a boost async function still references. Is there anything interesting in the log shortly before the crash ?

**Comment by Idealist42** [comment]
Nothing interesting in the logs.

I have rpc turned on, in restricted mode with a username and password, so I can use my node with cake wallet...  but other than that everything is normal.

**Comment by moneromooo-monero** [comment]
This has happened once only ?

**Comment by Idealist42** [comment]
Yes, this has only happened once.

**Comment by selsta** [comment]
There were a lot of crash related fixes in the last releases, please try v0.17.3.0 and open a new issue if you continue to have issues.
