### ISSUE TITLE
Cannot open legacy (v0.12) Ledger wallets

### ISSUE THREAD

**Issue by m2049r** [monero-project/monero#4455]
v0.13 has introduced a new field ```device_name``` in the keys file. It is set to "Ledger" for Ledger-backed keys.

So opening a legacy (v0.12) Ledger wallets fails with
```
ERROR	default	src/device/device.cpp:73	Device not found in registry: ''. Known devices: 
ERROR	default	src/device/device.cpp:75	 - Ledger
ERROR	default	src/device/device.cpp:75	 - default
```

Hardcoding ```m_device_name="Ledger"``` in an else block at https://github.com/monero-project/monero/blob/8bf5a00564ad0e86b4698008418e28036013ef9f/src/wallet/wallet2.cpp#L3285-L3288 seems to "fix" the problem.

As I don't understand the purpose of this new field I don't know how to fix this correctly. @ph4r05 ?

**Comment by ph4r05** [comment]
I will take a look. Could you please try `--hw-device Ledger` parameter as a workaround?

**Comment by ph4r05** [comment]
@m2049r is `m_key_device_type` set correctly when the opening wallet v0.12 file?

**Comment by ph4r05** [comment]
@m2049r So the workaround:

- Start wallet with `--hw-device Ledger`. You can use the wallet file with this argument as normally.
- Regenerate wallet key file by changing the password. Type `password`.
- Exit the wallet and reopen. The device name is stored, argument is not required anymore.

**Comment by m2049r** [comment]
Thanks @ph4r05 .

This PR has effect on the wallet API classes. Users of the API cannot use old Ledger wallets because they cannot ```--hw-device Ledger```.

Please fix ASAP.

I also don't understand the purpose of this field. Why was the old way of asking what device is plugged in changed?

Don't know if this is related @cslashm but
https://github.com/monero-project/monero/blob/8bf5a00564ad0e86b4698008418e28036013ef9f/src/device/device_ledger.cpp#L333-L338
is strange because ```full_name``` seems never to be set.

**Comment by moneromooo-monero** [comment]
+resolved
