### ISSUE TITLE
monerod stuck on RPi3

### ISSUE THREAD

**Issue by dawiepoolman** [monero-project/monero#4466]
Hi guys

My RPi3 has been progressing nicely syncing up with he network for about a week now but it started giving some errors then I rebooted.  Now monerod seems to be stuck 12hrs on startup:

![image](https://user-images.githubusercontent.com/2351212/46241509-46449300-c3bb-11e8-8546-ca128a108e07.png)

anything I can validate for corruption?

**Comment by moneromooo-monero** [comment]
Please provide those error messages, and anything relevant that happened shortly before (eg, did it crash, did you do something unuual, etc). This goes for any bug you report in the future, whether to monero or other software.

If it's not stuck, start it with "--log-level 1", wait for it to be stuck again, then paste those logs too.

When done, you can try starting it with "--db-salvage", which might get past the corruption.

**Comment by dawiepoolman** [comment]
Hi moneromoo

Apologies, I was away for the weekend.  Thx for the guidance.
I ran the log and got a bus error:

<img width="1106" alt="monerod-bus-error" src="https://user-images.githubusercontent.com/2351212/46309454-b1a98300-c5bc-11e8-996e-b8c257e746bd.PNG">

and then when starting with --db-salvage it just hangs again

![image](https://user-images.githubusercontent.com/2351212/46309507-d140ab80-c5bc-11e8-93ef-791512014039.png)

I take the dbse is corrupt?

**Comment by dawiepoolman** [comment]
no worries, I will try and re-download from scratch

**Comment by hyc** [comment]
Actually Bus error is pretty rare, it typically only occurs on misaligned data accesses. Usually a corrupted DB will cause a SIGSEGV. And I know of no situations where a corrupted DB can cause a startup hang.

**Comment by dawiepoolman** [comment]
thx for the pop in hyc
I do recall some blocks seemed to being downloaded and then a few blocks later it looped back and re-downloaded again
