### ISSUE TITLE
v0.13.0.1-RC1 + Whonix: sync stalls, need manual restart

### ISSUE THREAD

**Issue by qubenix** [monero-project/monero#4469]
OS: Qubes r4.0 + Whonix 14 (Debian Stretch)

Related: #4468

When using `torsocks` I get stacktrace spam and syncing will always quit at some point requiring a manual restart (even though outbound connections still exist).

Stacktrace spam is likely #4365. I'm pretty sure unrelated to the sudden stop in syncing since I've seen them happen independent each other, but I mention it just in case it's relevant.

log-level 1, quit syncing: http://termbin.com/3gxl
log-level 4, quit syncing: http://termbin.com/mutz

**Comment by moneromooo-monero** [comment]
Does 4469b0c41e8a2428cd2b5d34bd217d1ae339b096 make any difference ?

**Comment by qubenix** [comment]
No, that commit was already in my build.

I've got another log here, not run by `systemd`, where even a stop signal is not recognized: http://termbin.com/nmyg.

Previous to this comment all my logs were run by `systemd` and always responded to a `systemctl stop/restart`.

**Comment by moneromooo-monero** [comment]
So you tried with it, and... not without it ? Then you do not know if it makes a difference, right ?

**Comment by qubenix** [comment]
Correct, I'll try without it and report back.

**Comment by qubenix** [comment]
Without that commit I can't get any connections: http://termbin.com/jh1m.
