### ISSUE TITLE
monero-wallet-cli's generate-from-json with password is broken

### ISSUE THREAD

**Issue by xnum** [monero-project/monero#4480]
version: `release-v0.13`

execute `monero-wallet-cli --testnet --generate-from-json data.json` with following content in `data.json`

```
{"version":1,"filename":"/tmp/xmr.keys","scan_from_height":0,"password":"xxxxxxxx","viewkey":"...","spendkey":"...","address":"9x...."}
```
after the keys file was generated, open wallet with this file. 

`monero-wallet-cli --testnet --wallet-file xmr.keys`. 

I typed the password which is same as json specifics. then It always shows `Error: failed to load wallet: invalid password`

and demo here https://asciinema.org/a/IQYG6DKnjwLqvzP4vowzZCSiO

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4482

**Comment by moneromooo-monero** [comment]
+resolved
