### ISSUE TITLE
Let's participate to the 5th Hacktoberfest

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero#4488]
Also this year Github and digitaloceans are launching the "Hacktoberfest" which will last for the whole month of October.

The point of this initiative is to get poeple contribute to open source projects. Who subscribe to the "challenge" and open 5 valid Pull Requests on github within october, will get a free t-shirt.
This event is interesting because project maintainers can add the label 'Hacktoberfest' to any issue in the repo and that issue will be listed on the website of the contest and will be browsable by potential contributors.

I propose to participate to the event, we could label small issues that could be easily fixed. This could attract new developers and fix some long standing problems that devs had no time to fix yet.

At the end would be a totally effortless move from our developers (it's literally enough to add a label), but with only potential gains.

More info: https://hacktoberfest.digitalocean.com/

Edit: 5 Pull Requests are needed, not 3 as i initially wrote

**Comment by danrmiller** [comment]
+Hacktoberfest

**Comment by danrmiller** [comment]
-Hacktoberfest

**Comment by erciccione** [comment]
We are now partecipating with both [this repo](https://github.com/monero-project/monero/labels/hacktoberfest) and [monero-gui](https://github.com/monero-project/monero-gui/labels/Hacktoberfest)

:)
