### ISSUE TITLE
[Feature Request] Wallet-RPC Call to Decode/Describe Unsigned Transaction

### ISSUE THREAD

**Issue by MatteBru** [monero-project/monero#4504]
I have been working on an XMR cold-storage solution that relies on use of `monero-wallet-rpc` running on both the hot and cold side of the operation. Obviously at this point there is a rather well defined process for cold-signing, but I feel that the security of the process could be improved with a method that decodes the `unsigned_txset`, and displays the tx construction data in a human readable format.

Such a call would be very useful when hosting the view wallet on a VPS (or really, any potentially vulnerable internet-connected machine). Currently if a malicious actor were to gain access to the server they could either alter the wallet-rpc source, or whatever external code formats the parameters for the creation of the unsigned TX to use their own destination address. If this compromised unsigned tx is introduced into the signing environment, there is not a clean way of verifying that the destination address is that of the intended recipient.

I think the addition of a decoding call that could be used on the `unsigned_txset` before signing it would be very beneficial to the security of the cold-signing process.

**Comment by MatteBru** [comment]
@moneromooo-monero

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4539

**Comment by moneromooo-monero** [comment]
The tx keys are stored in the cold wallet's cache if you need them. They're not included in the out data since that goes back to the hot wallet. Maybe they can be included separately in the RPC though.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4552

**Comment by moneromooo-monero** [comment]
+resolved
