### ISSUE TITLE
what is the use of cn_slow_hash_prehashed  here?

### ISSUE THREAD

**Issue by calidion** [monero-project/monero#4537]
by searching cn_slow_hash_prehashed to know that it is only a definition.
```
eric@eric-laptop:~/Monero/monero$ grep cn_slow_hash_prehashed . -Rn
./src/crypto/hash.h:78:  inline void cn_slow_hash_prehashed(const void *data, std::size_t length, hash &hash, int variant = 0) {
```

**Comment by moneromooo-monero** [comment]
Is there a bug here ?

**Comment by moneromooo-monero** [comment]
Ignore prehashed, always set it to 0. variant 0 is the original CN. 1 is what monero is using now. 2 is what monero will be using from v8.

See https://github.com/monero-project/monero/pull/4218

**Comment by calidion** [comment]
@moneromooo-monero 

Thanks.

I set the last two parameter to 0, 0 for cn_slow_hash,
but it still not work with the old network.

you can checkout code from https://github.com/vigcoin/coin

where master can not update while old branch can.


the only difference is the cn_slow_hash.

**Comment by calidion** [comment]
@moneromooo-monero 

by `make clean` and `make` again.
the new compiled works with the old network now.

Thank you very much.

**Comment by moneromooo-monero** [comment]
+invalid
