### ISSUE TITLE
Error attempting to sync testnet in v0.13.0.2

### ISSUE THREAD

**Issue by oliverw** [monero-project/monero#4554]
I've just built v0.13.0.2 from source in Ubuntu 16.04 (WSL). Upon starting monerod with an empty data directory the following happens:

> oliver@DESKTOP-2GKAJGE: $ rm -rf .bitmonero/
> oliver@DESKTOP-2GKAJGE: $ monero/build/Linux/_HEAD_detached_at_v0.13.0.2_/release/bin/monerod --testnet
> 2018-10-10 19:04:23,918 INFO  [default] Page size: 4096
> 2018-10-10 19:04:24.923     7fcd21ae0780        INFO    global  src/daemon/main.cpp:287 Monero 'Beryllium Bullet' (v0.13.0.2-release)
> 2018-10-10 19:04:24.923     7fcd21ae0780        INFO    global  src/daemon/protocol.h:53        Initializing cryptonote protocol...
> 2018-10-10 19:04:24.927     7fcd21ae0780        INFO    global  src/daemon/protocol.h:58        Cryptonote protocol initialized OK
> 2018-10-10 19:04:24.927     7fcd21ae0780        INFO    global  src/daemon/p2p.h:63     Initializing p2p server...
> 2018-10-10 19:04:27.597     7fcd21ae0780        INFO    global  src/daemon/p2p.h:68     p2p server initialized OK
> 2018-10-10 19:04:27.597     7fcd21ae0780        INFO    global  src/daemon/rpc.h:63     Initializing core RPC server...
> 2018-10-10 19:04:27.597     7fcd21ae0780        INFO    global  contrib/epee/include/net/http_server_impl_base.h:76       Binding on 127.0.0.1:28081
> 2018-10-10 19:04:27.597     7fcd21ae0780        INFO    global  src/daemon/rpc.h:69     core RPC server initialized OK on port: 28081
> 2018-10-10 19:04:27.597     7fcd21ae0780        INFO    global  src/daemon/core.h:86    Initializing core...
> 2018-10-10 19:04:27.598     7fcd21ae0780        INFO    global  src/cryptonote_core/cryptonote_core.cpp:447       Loading blockchain from folder /home/oliver/.bitmonero/testnet/lmdb ...
> 2018-10-10 19:04:27.601     7fcd21ae0780        WARN    blockchain.db.lmdb      src/blockchain_db/lmdb/db_lmdb.cpp:75     Error attempting to retrieve a hard fork version at height 0 from the db: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid
> 2018-10-10 19:04:27.605     7fcd21ae0780        FATAL   daemon  src/daemon/daemon.cpp:195       Uncaught exception! Error adding hard fork version to db transaction: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid
> 2018-10-10 19:04:27.605     7fcd21ae0780        INFO    global  src/daemon/rpc.h:96     Deinitializing core RPC server...
> 2018-10-10 19:04:27.605     7fcd21ae0780        INFO    global  src/daemon/p2p.h:90     Deinitializing p2p...
> 2018-10-10 19:04:28.685     7fcd21ae0780        INFO    global  src/daemon/core.h:103   Deinitializing core...
> 2018-10-10 19:04:28.688     7fcd21ae0780        INFO    global  src/daemon/protocol.h:75        Stopping cryptonote protocol...
> 2018-10-10 19:04:28.688     7fcd21ae0780        INFO    global  src/daemon/protocol.h:79        Cryptonote protocol stopped successfully

**Comment by moneromooo-monero** [comment]
32 bit machine ?

**Comment by oliverw** [comment]
It's Ubuntu in Windows Subsystem for Linux (WSL): 

> $ uname -a
> Linux DESKTOP-2GKAJGE 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

I never had compatibility problems with it but you never know.

**Comment by moneromooo-monero** [comment]
o_O

Does this filesystem support (non buggy) mmap ?

**Comment by iDunk5400** [comment]
https://github.com/Microsoft/WSL/issues/658

**Comment by oliverw** [comment]
@iDunk5400 @moneromooo-monero  Allright that explains it. Closing.

**Comment by hyc** [comment]
@iDunk5400 LMDB doesn't attempt to mmap zero length files (we already ran into that bug years ago and worked around it). This is more likely a more recent bug https://github.com/nimiq-network/core/issues/387#issuecomment-401835135

I worked with the NIMIQ guys to diagnose the problem.
https://twitter.com/hyc_symas/status/1013800256088215552
