### ISSUE TITLE
Build failed on ARMv7: c++: error: missing argument to ‘-march=’

### ISSUE THREAD

**Issue by Lafudoci** [monero-project/monero#4559]
Build failed on ASUS tinkerboard (an ARMv7 clone board of raspberry pi, worked well before update to v0.13)
Error after `make release`.
```
Scanning dependencies of target epee
make[3]: Leaving directory '/home/linaro/monero/build/Linux/master/release'
make[3]: Entering directory '/home/linaro/monero/build/Linux/master/release'
[ 15%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o
c++: error: missing argument to ‘-march=’
contrib/epee/src/CMakeFiles/epee.dir/build.make:62: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o' failed
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o] Error 1
make[3]: Leaving directory '/home/linaro/monero/build/Linux/master/release'
CMakeFiles/Makefile2:397: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/all' failed
make[2]: *** [contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[2]: Leaving directory '/home/linaro/monero/build/Linux/master/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/linaro/monero/build/Linux/master/release'
Makefile:78: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by Lafudoci** [comment]
@xiphon OK, here it is.
https://paste.fedoraproject.org/paste/01orcBgX-biyA~ZoYz3MpA

**Comment by xiphon** [comment]
1. Run `make clean` and apply the first patch, check the compilation.
2. Run `make clean` once again and apply the second patch, check the compilation.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1bffd29b..50f32217 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -523,7 +522,7 @@ else()
     endif()
   endif()
   message(STATUS "Building on ${CMAKE_SYSTEM_PROCESSOR} for ${ARCH}")
-  if(ARCH STREQUAL "default")
+  if(NOT ARCH OR ARCH STREQUAL "default")
     set(ARCH_FLAG "")
   elseif(PPC64LE)
     set(ARCH_FLAG "-mcpu=power8")
```

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1bffd29b..50f32217 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -534,6 +533,8 @@ else()
   elseif(IOS AND ARCH STREQUAL "arm64")
     message(STATUS "IOS: Changing arch from arm64 to armv8")
     set(ARCH_FLAG "-march=armv8")
+  elseif(ARM7)
+    set(ARCH_FLAG "-march=armv7")
   else()
     set(ARCH_FLAG "-march=${ARCH}")
     if(ARCH STREQUAL "native")
```

**Comment by NanoAkron** [comment]
This patch shouldn't really work, because you'll never hit ARCH STREQUAL "arm64" with an ARM7 processor...

**Comment by TheCharlatan** [comment]
I think the problem is that in the current way it is setup, there is a different branch in the cmake logic taken between native and cross arm compilation. It's kind of annoying that these differences are needed at all. Would be nice to have a default native path and a cross compilation path.

**Comment by xiphon** [comment]
> This patch shouldn't really work, because you'll never hit ARCH STREQUAL "arm64" with an ARM7 processor...

The comment doesn't seem valid to me. Please take a closer look at what the patch does.

**Comment by xiphon** [comment]
@TheCharlatan 
Think the issue is related to:
1. We don't have a default/native ARCH fallback if none of the ARCH-definition rules were met
2. We don't set `-march=armv7` flag

**Comment by Lafudoci** [comment]
@xiphon, Thanks for your help, first patch built well. The second patch build is running, but it has passed the previous fail point. I'll report once it finish.

**Comment by Lafudoci** [comment]
@xiphon Second patch built successfully as well. Thank you.

**Comment by shyrwall** [comment]
The patch does not work for me. Before applying same errors as Lafudoci . After ,

[ 27%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o
/root/monero/contrib/epee/src/hex.cpp:1:0: error: target CPU does not support ARM mode
 // Copyright (c) 2017-2018, The Monero Project

contrib/epee/src/CMakeFiles/epee.dir/build.make:62: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o' failed

---

 
model name      : ARMv7 Processor rev 4 (v7l)
Linux a 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

**Comment by shyrwall** [comment]
> 
> 
> The patch does not work for me. Before applying same errors as Lafudoci . After ,
> 
> [ 27%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o
> /root/monero/contrib/epee/src/hex.cpp:1:0: error: target CPU does not support ARM mode
> // Copyright (c) 2017-2018, The Monero Project
> 
> contrib/epee/src/CMakeFiles/epee.dir/build.make:62: recipe for target 'contrib/epee/src/CMakeFiles/epee.dir/hex.cpp.o' failed
> 
> model name : ARMv7 Processor rev 4 (v7l)
> Linux a 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

--march=armv7-a  works.

There must be some better way of doing this or does every arch need to be added? :D How was it before this release?

**Comment by xiphon** [comment]
@shyrwall 

Please apply this one without any additional changes and report back the results.

https://github.com/monero-project/monero/pull/4565/commits/0aa14285eb262a1aa965db1350c2e81973deaafe

**Comment by xiphon** [comment]
@shyrwall

1. Run `make clean`
2, Apply the patch from #4565
3. Report back the results. 

Would be nice to see the logs if a build fails.

**Comment by shyrwall** [comment]
Sorry for the late reply. Looks good so far. Takes like 10h to compile.. 💃

**Comment by moneromooo-monero** [comment]
+resoled
