### ISSUE TITLE
Code coverage not updated ?

### ISSUE THREAD

**Issue by calidion** [monero-project/monero#4589]
I searched coverall by `grep coverall -Rn` only found it in the README.md file.

Does it mean code coverage info currently generated automatically but not  updated to coveralls.io?
```
./README.md:48:| Coveralls | [![Coveralls Status](https://coveralls.io/repos/github/monero-project/monero/badge.svg?branch=master)](https://coveralls.io/github/monero-project/monero?branch=master)
```

**Comment by calidion** [comment]
I am trying to add code coverage report badge to my project.
So I am referencing monero. 
It is sad to know that monero is not updated on coverage report either.

**Comment by moneromooo-monero** [comment]
I don't know it, but it would probably be useful, thanks.

**Comment by moneromooo-monero** [comment]
Is this something you still want to do at some point ?

**Comment by selsta** [comment]
Closing as we currently don't use coveralls.
