### ISSUE TITLE
DB conversion error

### ISSUE THREAD

**Issue by netxecute** [monero-project/monero#4599]
My db was converting - it was about halfway (2630000) and then when I came home the cmd prompt window was gone. Tried starting again and get this error when it gets to the DB conversion

2018-10-12 03:47:15.525 5504 ERROR blockchain.db.lmdb src/blockchain_db/lmdb/db_lmdb.cpp:4232 Output found claiming height >= blockchain height

2018-10-12 03:47:15.525 5504 WARN blockchain.db.lmdb src/blockchain_db/lmdb/db_lmdb.cpp:75 Failed to build rct output distribution

2018-10-12 03:47:15.525 5504 ERROR cn src/cryptonote_core/cryptonote_core.cpp:548 Error opening database: Failed to build rct output distribution

**Comment by moneromooo-monero** [comment]
Are there interesting things from when it crashed in the log ? An exception maybe ?

**Comment by netxecute** [comment]
Sorry not sure I follow - you want a different part of the log or is this some action you want me to take?

**Comment by moneromooo-monero** [comment]
Add that line before the error (db_lmdb.cpp:4232), compile, run, post those logs again.

**Comment by netxecute** [comment]
? I didn't compile
This is just the win 64bit binary cli trying to upgrade the blockchain db

**Comment by moneromooo-monero** [comment]
I'm not saying you compiled it, I'm saying compile it now with that patch :)
If you can't/won't compile it now, then fair enough, but I can't help further.

**Comment by netxecute** [comment]
Ah, I see.  No sorry can't compile this.  Could you expand on the error a bit?

Do I need to re-sync the blockchain from scratch?  Is it an issue with the CLI or with the db?

thanks

**Comment by moneromooo-monero** [comment]
I don't know yet.

**Comment by selsta** [comment]
Closing due to lack of reports by others users and age of the issue.
