### ISSUE TITLE
Long wait for response from RPC

### ISSUE THREAD

**Issue by devnull00000** [monero-project/monero#4606]
When using the transfer method, the answer does not come for a long time (about 10 seconds). In my application, after 8 seconds of waiting, a timeout is triggered, and the transaction is considered unsuccessful, but the transaction is completed successfully after the timeout. Perhaps the problem is in HDD. There will be an SSD on prodaction, but still I’m worried about the fact that a similar problem can happen again on the SSD, which will make the application work incorrectly. Should I worry?
p.s. 
Monero 0.13.0 "Beryllium Bullet" Release
Node on localhost
Other methods works fine

**Comment by moneromooo-monero** [comment]
There is scope for speeding this up, but if you're concerned about a spurious timeout detection, increase the timeout. Part of that time is used by waiting for the daemon to supply fake output info (so will be sped up by using a SSD), but the wallet also does some wasteful work (which won't).

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4663 will help a bit.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4664 will help a little bit too.

**Comment by devnull00000** [comment]
Many thx. Tell me, can the count of sub-addresses affect the response time?

**Comment by moneromooo-monero** [comment]
Yes for things like getbalance, which can return per address data.

**Comment by moneromooo-monero** [comment]
Those are merged now. That's the low hanging fruits done AFAICT.

**Comment by prybus** [comment]
@monero-project Is it posible? I have response transfer method after 120 second? This is very strange. 
Other methods works properly.

**Comment by moneromooo-monero** [comment]
It should now be much faster.

+resolved
