### ISSUE TITLE
upgrade to Beryllium Bullet

### ISSUE THREAD

**Issue by bitcodernull** [monero-project/monero#4611]
i update my node to Beryllium Bullet
when i start the node ,i get the following logs, and log stop .
i am not sure it is ok?
If it is ok, how long will i wait for db upgrade

![image](https://user-images.githubusercontent.com/35094762/47005073-9797a500-d165-11e8-9c06-8d624549810c.png)

**Comment by moneromooo-monero** [comment]
Is it throwing errors or somehow behaves wrongly/weirdly ?

**Comment by moneromooo-monero** [comment]
It may take a while to upgrade the database. It should continue once it's done with that step.

**Comment by bitcodernull** [comment]
thanks
it is ok now
