### ISSUE TITLE
Enabling tracking checkbox in 0.13.0.3 GUI causes UI to be unresponsive

### ISSUE THREAD

**Issue by Engelberg** [monero-project/monero#4614]
After checking the tracking checkbox, the interface slows down where clicking and typing a character takes several seconds to respond.

Only way I've found to regain responsiveness is to switch the receive view to an unused subaddress, and then the UI becomes sufficiently responsive to disable tracking again, at which point the UI returns to normal.

This is the Windows 64-bit GUI version.

**Comment by moneromooo-monero** [comment]
Please file GUI bugs on https://github.com/monero-project/monero-core

+invalid
