### ISSUE TITLE
How to use new config: block-notify.

### ISSUE THREAD

**Issue by DinoStray** [monero-project/monero#4633]
I use it in config file:
block-notify=/root/scripts/new_block_callback.sh

then, in new_block_callback.sh:
```
#!/usr/bin/env bash

echo "hi" >> /root/lyl
```

then, nothing happened.

**Comment by xiphon** [comment]
Should be something like
`--block-notify='bash root/scripts/new_block_callback.sh'`

**Comment by DinoStray** [comment]
> Should be something like
> `--block-notify='bash /root/scripts/new_block_callback.sh'`

block-notify='bash /root/scripts/new_block_callback.sh'
Still, nothing happened.

If I run  /root/scripts/new_block_callback.sh directly， everything is OK.

**Comment by moneromooo-monero** [comment]
/usr/bin/bash

**Comment by moneromooo-monero** [comment]
And you should have got an error message about it when monerod started. Did you not ?

**Comment by DinoStray** [comment]
> And you should have got an error message about it when monerod started. Did you not ?

And a lot of defunct thread

**Comment by moneromooo-monero** [comment]
Please expand.
