### ISSUE TITLE
Why is mixin even and total signatures odd?

### ISSUE THREAD

**Issue by ChloeMackey** [monero-project/monero#4652]
Sorry if this has been answered before. I must be confused, If half of the mixen is from 1.8 days and the other half is after 1.8 days, wouldn't it be trivial to half your security by looking at which group is higher, the pre 1.8 days vs post 1.8 days group? Today, the mixen is 10 so total signatures 11, that means if i make a transaction after a day, 6 of my total sig will be pre 1.8 days and 5 would be post 1.8 days.

**Comment by ChloeMackey** [comment]
Is what I'm talking about a legacy problem and we have since switched to a gamma distribution decoy picking? https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L6996

**Comment by SamsungGalaxyPlayer** [comment]
Yes

**Comment by ChloeMackey** [comment]
Answered my own question, looks like we switched to gamma distribution.

"Furthermore, Monero has redesigned their GUI settings, implemented a faster wallet refresh and gamma distribution for ring selection"

https://blocklr.com/news/monero-xmr-hard-fork/

**Comment by ChloeMackey** [comment]
Thanks!

**Comment by moneromooo-monero** [comment]
The code allocated the right amount depending on the age of the real output:

      if (td.m_global_output_index >= num_outs - num_recent_outs && recent_outputs_count > 0)
        --recent_outputs_count; // if the real out is recent, pick one less recent fake out

**Comment by moneromooo-monero** [comment]
Also, "whole chain" can pick in the last 1.8 days too.

**Comment by ChloeMackey** [comment]
Thank you, how did we get the gamma parameters? https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L6779

**Comment by moneromooo-monero** [comment]
They are from a paper from Miller et al, I don't have a link right now.

**Comment by ChloeMackey** [comment]
https://arxiv.org/pdf/1704.04299/ this guy?

**Comment by moneromooo-monero** [comment]
That's the one (well, a previous version) - fig 11.

**Comment by moneromooo-monero** [comment]
+invalid
