### ISSUE TITLE
Borromean range proofs are not allowed after v8

### ISSUE THREAD

**Issue by nox956** [monero-project/monero#4668]
Hi, I'm running monero daemon v0.13.0.2 and seen this line of error keep showing up in the console, does that mean there is something wrong or just some node sending me old txs?

BTW, my node is already forked to v9 up to date and connecting to other nodes correctly.

**Comment by dEBRUYNE-1** [comment]
>or just some node sending me old txs?

Correct.

**Comment by nox956** [comment]
@dEBRUYNE-1 Thanks for answering!
