### ISSUE TITLE
wallet-rpc: Write subaddresses to wallet file instantly when created

### ISSUE THREAD

**Issue by moonsikpark** [monero-project/monero#4673]
Wallet-rpc does not write sub-addresses to file instantly. instead, it saves them when it 'cleanly' exits.

In a production environment which we keep the rpc daemon for months there is a possibility of it failing. When it fails the unsaved sub-addresses will be lost and has to be created manually by restoring the wallet through wallet-cli. Creating 6000 sub-addresses takes hours and we can't check the payment. It's a nightmare.

#3994 Monero locks the wallet file as of v0.13 and I think it can save sub-addresses every time at creation.

**Comment by moonsikpark** [comment]
+feature

**Comment by moneromooo-monero** [comment]
Since this would take quite a long time saving all the time, I'll close this.

+invalid
