### ISSUE TITLE
Dockerfile seems to be broken

### ISSUE THREAD

**Issue by korjavin** [monero-project/monero#4675]
I tried to build node by docker build by it has ended with:
`
Step 33/41 : RUN set -ex &&     git submodule init && git submodule update &&     rm -rf build &&     if [ -z "$NPROC" ] ;     then make -j$(nproc) release-static ;     else make -j$NPROC release-static ;     fi
 ---> Running in cbd0b24e0045
+ git submodule init
+ git submodule update
+ rm -rf build
+ [ -z  ]
+ nproc
+ make -j2 release-static
make: *** No rule to make target 'release-static'.  Stop.
The command '/bin/sh -c set -ex &&     git submodule init && git submodule update &&     rm -rf build &&     if [ -z "$NPROC" ] ;     then make -j$(nproc) release-static ;     else make -j$NPROC release-static ;     fi' returned a non-zero code: 2
Exited with code 2

`

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4591

+resolved

**Comment by korjavin** [comment]
Nope, it doesn't help.
I already had this git submodule in my Dockerfile.

There is the full log of building in circle-ci
[build_9_step_104_container_0.txt](https://github.com/monero-project/monero/files/2514903/build_9_step_104_container_0.txt)
