### ISSUE TITLE
Tabbing between fields in GUI wallet doesn't work -- inserts literal tab

### ISSUE THREAD

**Issue by sectioneight** [monero-project/monero#4682]
OS: Linux
Wallet version: v0.13.0.3 (Qt 5.7.0)

![tabbing-2018-10-21_04 28 22](https://user-images.githubusercontent.com/97087/47266369-4f241280-d4ea-11e8-96a1-760f74de2b79.gif)

Expected behavior: switch to next field, like on a website.

I'm assuming this is unintended since URLs/Ports shouldn't have tabs in them.

I realize this is low priority, and I'm happy to fix if y'all would like

**Comment by erciccione** [comment]
Thank you @sectioneight, but this is the wrong repo, can you close this PR and reopen it on monero-project/monero-gui ?

**Comment by sectioneight** [comment]
Whoops! Sorry
