### ISSUE TITLE
dis.gratis always return "Invalid amount"

### ISSUE THREAD

**Issue by ztlovemst11** [monero-project/monero#4712]
Who can help me solve this problem?

**Comment by ztlovemst11** [comment]
![image](https://user-images.githubusercontent.com/27879437/47417910-98ef5000-d7ab-11e8-83eb-1dfef5f40719.png)

**Comment by moneromooo-monero** [comment]
Try #monero on Freenode, maybe someone knows whose site that is.

+invalid
