### ISSUE TITLE
How to call /get_random_rctouts.bin API?

### ISSUE THREAD

**Issue by meiyoung** [monero-project/monero#4723]
I use postman to call this API, but got 404.

**Comment by moneromooo-monero** [comment]
It does not exist, it was removed.
Use get_outs.bin instead.

**Comment by meiyoung** [comment]
can you update the docs in https://src.getmonero.org/resources/developer-guides/daemon-rpc.html#get_random_outsbin

so many API is out of date

**Comment by moneromooo-monero** [comment]
https://repo.getmonero.org/monero-project/monero-site/merge_requests/944
