### ISSUE TITLE
monerod v0.13.0.4 being killed / crashed randomly it seems

### ISSUE THREAD

**Issue by patoshii** [monero-project/monero#4725]
Below is the screenshot of when it got killed and also the bitmonero.log file. 

I started monerod with the command:

**./monerod --block-sync-size 10**

What could the issue be? 

[![enter image description here][1]][1]

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/RfN1C.png
  [2]: https://i.stack.imgur.com/dfxGr.png

**Comment by moneromooo-monero** [comment]
That's the OOM killer. Free more memory.

**Comment by moneromooo-monero** [comment]
And btw you'll see more info in dmesg about it when it happens.

+invalid
