### ISSUE TITLE
name convention?

### ISSUE THREAD

**Issue by calidion** [monero-project/monero#4737]
Currently types are using names like public_key,  ec_point, private_key.

which is very hard to distinguish them from variables.

And some even confusing  types are `secret_keyV`.

It seems there is no rule for how to define a clear class, struct, function, variable?

**Comment by calidion** [comment]
for structs.

1. struct type one: full lower case

```
  struct block_complete_entry
  {
    blobdata block;
    std::vector<blobdata> txs;
    BEGIN_KV_SERIALIZE_MAP()
      KV_SERIALIZE(block)
      KV_SERIALIZE(txs)
    END_KV_SERIALIZE_MAP()
  };
```

2. struct type two: full upper case
```
  struct NOTIFY_NEW_BLOCK
  {
    const static int ID = BC_COMMANDS_POOL_BASE + 1;

    struct request
    {
      block_complete_entry b;
      uint64_t current_blockchain_height;

      BEGIN_KV_SERIALIZE_MAP()
        KV_SERIALIZE(b)
        KV_SERIALIZE(current_blockchain_height)
      END_KV_SERIALIZE_MAP()
    };
  };
```

**Comment by moneromooo-monero** [comment]
There is indeed no such hard convention, but foo_bar is usually used, and preferred, though if you define new types in a series, such as a new message type, follow the existing code.
A fairly common thing is to add "_t" at the end of a type when a typical variable is going to collide often, but that's usually for short types.

**Comment by calidion** [comment]
It would be much better if `_t` is added.

**Comment by moneromooo-monero** [comment]
Please don't send such a patch :) Though if you need to add new types, that'd be fine.

**Comment by fluffypony** [comment]
I think we’re generally fine with refactor as you go. If you have a PR that interacts with a poorly named struct then by a means rename it, but don’t rename for renaming’s sake.

**Comment by moneromooo-monero** [comment]
If it's local, sure. If it involve renamings in random other places, I would say no. But hey, depends on the particulars.

**Comment by calidion** [comment]
I have renamed a lot of types from the original cryptonote code.
The process is made easy with the bash script:

https://github.com/vigcoin/coin/blob/master/replace-types.sh

Feel free to use it when necessary:)

**Comment by moneromooo-monero** [comment]
+wontfix
