### ISSUE TITLE
{newline} symbol missed in daemon after block counter

### ISSUE THREAD

**Issue by Seriy-A** [monero-project/monero#4741]
every message after block counter appears like NumberDateStamp
examples:
`block 174070 / 16878202018-10-27 15:41:51.975   16284   INFO    global  src/blockchain_db/lmdb/db_lmdb.cpp:600  [batch] DB resize needed`
`block 225270 / 16878202018-10-27 16:45:05.761   16284   WARN    net.dns src/common/dns_utils.cpp:519    WARNING: no two valid MoneroPulse DNS checkpoint records were received`

logfile looks nice (all \n correct, new record==new line), so it seems thats counter bug

**Comment by moneromooo-monero** [comment]
This is one of the export/import tools, right ?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4742 should fix it.

**Comment by Seriy-A** [comment]
> 
> 
> This is one of the export/import tools, right ?

v.13 only import tool tested yet, v.12 was in monerod too

**Comment by moneromooo-monero** [comment]
+resolved
