### ISSUE TITLE
release v0.13.0.4 have double spending issue

### ISSUE THREAD

**Issue by Vaidas737** [monero-project/monero#4745]
I tested the new release with monero-wallet-rpc and transfer_split method. As the result the wallet send the same amount twice.

monero-linux-x64-v0.13.0.4

**Comment by moneromooo-monero** [comment]
Can you give more info about what you are doing ? I just tried a transfer_split here, and the correct amounts were sent and received.

**Comment by moneromooo-monero** [comment]
Including anwers to:
- twice as many outputs,  twice as many txes, or  outputs with amount twice as large ? Or other ?
- do you have the JSON that was sent ?
- do you have the JSON that was returned ?

**Comment by Vaidas737** [comment]
here the txids if it can help
4f4c224b1547634e34773b96ae239facb506739ae129ab3d6b4fb78a400de62b
6156cf32837ab97d9d2361f94c8bc07f79453a7fa8e8b747a5dc27527c12d20a

JSON sent
{
  "jsonrpc": "2.0", 
  "id": "0", 
  "method": "transfer_split",
  "params": {
    "destinations": [
      { "amount": 400000000, "address": "*****" }
    ],
    "mixin": 3,
    "get_tx_key": true,
    "new_algorithm": true
  }
}

JSON returned
{"amount_list":[400000000],"fee_list":[46120000],"multisig_txset":"","tx_hash_list":["4f4c224b1547634e34773b96ae239facb506739ae129ab3d6b4fb78a400de62b"],"unsigned_txset":""}

**Comment by moneromooo-monero** [comment]
Do you have the log from monero-wallet-rpc ?

**Comment by moneromooo-monero** [comment]
I sent that same JSON (replacing the address), and it behaves as expected, one single tx.
The code that relays the tx to the daemon adds the txid to the list at the same time, so it the JSON reply has only one txid, it implies only one tx got sent. Could be a bug though, we'd likely see that in the monero-wallet-rpc log.
Is it possible two JSON requests were made in short order ?

**Comment by Vaidas737** [comment]
I can send the logs, it's too long to post it here.

**Comment by moneromooo-monero** [comment]
You can post to fpaste.org or paste.debian.net and paste the URL here.

**Comment by moneromooo-monero** [comment]
Lucky this log has a lot of information.

If you run:
grep -E handle_accept\|sent\ to\ daemon\|transfer_split log | less -SR

Then you see two different calls to transfer_split, one at 20:21:54.088, the other at 20:22:07.064.
It looks like whatever sends the JSON sent it twice.

The handle_accept is when a new connection is received by the HTTP server.

**Comment by Vaidas737** [comment]
I see, thanks for clarification

**Comment by moneromooo-monero** [comment]
No problem.
Your situation makes me think we could have a "unique id" in the transfer RPC, so that monero-wallet-rpc would ignore any duplicate. That would save you the dupe call, assuming the caller would send it twice exactly the same.

**Comment by Vaidas737** [comment]
That will be great, I like the idea.
