### ISSUE TITLE
How could I build and send transaction from scratch by pure daemon-rpc call?

### ISSUE THREAD

**Issue by wuzheman88** [monero-project/monero#4752]
I want to build, sign and send transaction by pure daemon-rpc call without wallet or generated tx file, in another word to implement a simple wallet operating unspent output directly with rpc-call, anyone can help me?

**Comment by moneromooo-monero** [comment]
Read and understand the code. Basically create_transactions_2 and everything it calls.

But this is a bug tracker, use this to report bugs, not get help. If you need help using the monero code, try #monero on freenode. If you're trying to contribute to monero, try #monero-dev on Freenode.

+invalid
