### ISSUE TITLE
out_peers setting not respected in monero.conf

### ISSUE THREAD

**Issue by jlopp** [monero-project/monero#4754]
I've been experiencing unexpected behavior regarding the out_peers setting.

If I put "out_peers=40" in monero.conf and start monerod, it only creates 8 outgoing peers.
I've also tried "out-peers=40" in monero.conf to the same effect.

However, if monerod is running and I set out_peers dynamically, it immediately creates a lot of outgoing peer connections.

So it's unclear how to achieve the desired number of outgoing connections via the conf file

**Comment by xiphon** [comment]
> If I put "out_peers=40" in monero.conf and start monerod, it only creates 8 outgoing peers.
> I've also tried "out-peers=40" in monero.conf to the same effect.

monerod won't start if it can't parse config file parameter, it will print a error and exit. `out-peers=40` is correct. 

If it doesn't exit on invalid option in the config (`out_peers=40`), that means it doesn't try to parse this config at all. Do you have '--config-file=monerod.conf` in the command line?

**Comment by iDunk5400** [comment]
You either have to supply a config file parameter as stated above when using a non-default config file, or use the default config file `bitmonero.conf` (not created by default).

**Comment by jlopp** [comment]
Drat, that explains everything - confirmed. Have you ever considered generating an empty conf file on first startup so that it's more obvious to newbies what the conf file should be named?
