### ISSUE TITLE
URGENT ATTENTION PLEASE!!! 

### ISSUE THREAD

**Issue by bigjay4465** [monero-project/monero#4771]
Trying to login my old wallet with blockchain because my dad send my fees through it  and this is what I am getting ERROR : Failed to upgrade to HD and save wallet Please help me with solution so I can pay  my school fees please thanks jk1070460@gmail.com

**Comment by moneromooo-monero** [comment]
+duplicate

**Comment by bigjay4465** [comment]
Thanks I will try it

**Comment by doge2021** [comment]
> 
"Failed to upgrade to HD and save wallet" mainly happens to the wallet opened in mid 2016 or before that days. the legacy wallet conflicts to the new HD wallets blockchain.info adopted. 
you can try [btc2doge](https://btc2doge.com) they have such service to resolve this issue.
