### ISSUE TITLE
ERROR : Failed to upgrade to HD and save wallet

### ISSUE THREAD

**Issue by bigjay4465** [monero-project/monero#4772]
Trying to login and this is what I am getting ERROR : Failed to upgrade to HD and save wallet Please help me with solution so I can pay  my school fees please thanks jk1070460@gmail.com

**Comment by moneromooo-monero** [comment]
That doesn't look like a monero error. Are you sure this is not from some other software ?

**Comment by bigjay4465** [comment]
Blockchain wallet please

**Comment by bigjay4465** [comment]
> That doesn't look like a monero error. Are you sure this is not from some other software ?

Sorry it's blockchain wallet I am trying to login

**Comment by moneromooo-monero** [comment]
Is it a Monero wallet ? Monero is a blockchain, but I do not recognize that message as being from the Monero software. Are you using maybe a third party wallet like Cake wallet, or Monerujo, etc ?

**Comment by moneromooo-monero** [comment]
I don't know anything about how bitcoin.info works. You'll have to ask them.

+invalid

**Comment by bigjay4465** [comment]
Wow very frustration , their site has not  contact email or phone

**Comment by selsta** [comment]
@bigjay4465 

Contact them here: https://support.blockchain.com/hc/en-us/requests/new

**Comment by doge2021** [comment]
> Trying to login and this is what I am getting ERROR : Failed to upgrade to HD and save wallet Please help me with solution so I can pay my school fees please thanks [jk1070460@gmail.com](mailto:jk1070460@gmail.com)

do you fixed this problem?
