### ISSUE TITLE
problems with transferring the blockchain to an external drive

### ISSUE THREAD

**Issue by gittyhupbub** [monero-project/monero#4773]
im having some issues with the monero wallet. I was installing a wallet on a new cpu and ran out of disk space. I changed the block chain location to an external drive by creating a new directory D:\MoneroBlockchain\lmdb (this is properly shown in the client directory) I copied the data.mbd file to the new folder but when i reopen the client it starts downloading the chain to the pre-existing path. Ive tried clearing the cache as well. Any suggesstions? thanks.

**Comment by moneromooo-monero** [comment]
Did you add --data-dir D:\MoneroBlockchain ?

**Comment by dEBRUYNE-1** [comment]
@gittyhupbub - This is basically a bug tracker and not a support forum. Therefore, please see:

https://monero.stackexchange.com/questions/7225/how-do-i-move-the-blockchain-data-mdb-to-a-different-directory-during-or-afte

If you have any further questions, please open a new thread on the monerosupport subreddit:

https://www.reddit.com/r/monerosupport/

**Comment by dEBRUYNE-1** [comment]
+invalid

**Comment by gittyhupbub** [comment]
Thank you that fixed my issue! However i ran into another problem. ive been stuck in the 89% sync range for 6+ hours doing a consistent small 20 block chunks for a long period of time. My connection is good and it never took this long when i first started syncing to the network. Appreciate your help.
