### ISSUE TITLE
miniupnpc not static upnpDiscover change

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#480]
/build/bitmonero-git/src/bitmonero/src/p2p/net_node.inl:446:69: error: too few arguments to function 'UPNPDev\* upnpDiscover(int, const char_, const char_, int, int, unsigned char, int_)'
   UPNPDev_ deviceList = upnpDiscover(1000, NULL, NULL, 0, 0, &result);
                                                                     ^
In file included from /build/bitmonero-git/src/bitmonero/src/p2p/net_node.inl:58:0,
                 from /build/bitmonero-git/src/bitmonero/src/p2p/net_node.h:288,
                 from /build/bitmonero-git/src/bitmonero/src/rpc/core_rpc_server.h:39,
                 from /build/bitmonero-git/src/bitmonero/src/rpc/core_rpc_server.cpp:35:

Change format for upnpDiscover if MINIUPNPC_API_VERSION >= 14
https://github.com/bitcoin/bitcoin/commit/9f3e48e5219a09b5ddfd6883d1f0498910eff4b6.patch

From
upnpDiscover(int delay, const char \* multicastif,
             const char \* minissdpdsock, int sameport,
             int ipv6,
             int \* error)

To
upnpDiscover(int delay, const char \* multicastif,
             const char \* minissdpdsock, int localport,
             int ipv6, unsigned char ttl,
             int \* error)

Sorry , I am not competent for code change in CMake and .inl

**Comment by warptangent** [comment]
Addressed in #422.

**Comment by perl5577** [comment]
Work perfectly :)
I can submited PKGBUILD to AUR archlinux ans close issues
https://aur.archlinux.org/packages/bitmonero-git

**Comment by NanoAkron** [comment]
Hi @perl5577 is this still an issue for you or can this be closed?

**Comment by moneromooo-monero** [comment]
+resolved
