### ISSUE TITLE
ArchARM RPi: messages_map.hpp:47:10: fatal error: messages/messages.pb.h: No such file or directory

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#4822]
```
[ 42%] Building CXX object src/device_trezor/CMakeFiles/obj_device_trezor.dir/device_trezor.cpp.o
In file included from /home/mwo/monero/src/device_trezor/trezor/transport.hpp:49,
                 from /home/mwo/monero/src/device_trezor/trezor.hpp:36,
                 from /home/mwo/monero/src/device_trezor/device_trezor.hpp:43,
                 from /home/mwo/monero/src/device_trezor/device_trezor.cpp:30:
/home/mwo/monero/src/device_trezor/trezor/messages_map.hpp:47:10: fatal error: messages/messages.pb.h: No such file or directory                                                                                 
 #include "messages/messages.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [src/device_trezor/CMakeFiles/obj_device_trezor.dir/build.make:63: src/device_trezor/CMakeFiles/obj_device_trezor.dir/device_trezor.cpp.o] Error 1                                                  
make[3]: Leaving directory '/home/mwo/monero/build/release'
make[2]: *** [CMakeFiles/Makefile2:3540: src/device_trezor/CMakeFiles/obj_device_trezor.dir/all] Error 2
make[2]: Leaving directory '/home/mwo/monero/build/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/mwo/monero/build/release'
make: *** [Makefile:95: release-all] Error 2
```

It fails becasue https://github.com/monero-project/monero/tree/master/src/device_trezor/trezor/messages is empty. 

All compiles well on normal arch, so don't know at present why Arch ARM for Raspberry Pi fails. Any ideas?

**Comment by moneromooo-monero** [comment]
Is the build log complaining about not finding "protoc" earlier ?

**Comment by moneroexamples** [comment]
Haven't seen any such message. But Im rebuilding again. It takes ages on RPi2, so will know more in few hours.

**Comment by moneroexamples** [comment]
`python-protobuf` was missing. Its interesting because I don't have it installed on my regular arch. 

Anyway, maybe its good time to actually revisit https://github.com/monero-project/monero#dependencies , as I wanted to provide one liners for fedora and arch as well, and update the table since, e.g., hidapi, is missing from dependencies.

**Comment by jtgrassie** [comment]
This should probably be reopened. It not only creates a dependency of python-protobuf, but also python 3. Without both these dependencies, builds can fail.

**Comment by moneroexamples** [comment]
I don't have `python-protobuf` on my arch, and build works for me. I only encountered this issue on archarm. On regular arch I have:

```
yay -Qs protobuf
local/protobuf 3.6.1-1
    Protocol Buffers - Google's data interchange format
local/protobuf-c 1.3.1-1
    Protocol Buffers implementation in C
```

**Comment by jtgrassie** [comment]
I was getting build errors on OSX because the default python was 2.7 and trezor cmake requires 3+ and the python protobuf bindings. Easy enough to work around but a default compile should not try to build in non-essential code (trezor in this case) if it cannot meet the requirements. That's why I wanted this issue open again, to remind me to have a look at fixing the trezor cmake file for the case I was encountering.

**Comment by jtgrassie** [comment]
```
CMake Warning at src/device_trezor/CMakeLists.txt:79 (message):
  Trezor protobuf messages could not be regenerated (err=No such file or
  directory, python ).OUT: , ERR: .Please read
  src/device_trezor/trezor/tools/README.md

```

Followed by a bunch of undefined errors later during build:
```
[ 53%] Linking CXX executable ../../bin/monero-wallet-rpc
Undefined symbols for architecture x86_64:
  "hw::trezor::MessageMapper::get_message_wire_number(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
...
  "hw::trezor::device_trezor_base::disconnect()", referenced from:
      hw::trezor::device_trezor::~device_trezor() in libdevice_trezor.a(device_trezor.cpp.o)
```

Which is happening because the trezor cmake file is still trying to compile and link device_trezor.cpp even though the protobuf messages failed to be generated.

**Comment by moneroexamples** [comment]
I had the same issue. Though I don't understand why python-protobuf is required. Is it fallback?

**Comment by jtgrassie** [comment]
No it seems a requirement. Both python3 and python-protobuf. The cmake file is the issue though - it should just disable trezor support when trezor dependencies are not met.

**Comment by jtgrassie** [comment]
Looks like this is fixed in #4839

**Comment by ph4r05** [comment]
It should be fixed also in the earlier, already approved PR #4824. Can you give it a try?

**Comment by ph4r05** [comment]
Anyway, assuming #4824 - There is no `python-protobuf` dependency. CMake check is now more robust. If message generation fails Trezor is not compiled.

In order to compile Trezor the protobuf library is needed (`libprotobuf-dev` on Ubuntu) and simple Python3. The #4824 also enables to use Python2 for the compilation if no Py3 is present:

```bash
export PYTHON3=python
pip install backports.tempfile
```

**Comment by jtgrassie** [comment]
#4824 doesn't address properly. The later #4839 does.

**Comment by ph4r05** [comment]
> #4824 doesn't address properly. The later #4839 does.

How come? Is the build failing for you if there is a problem with missing protobuf?

**Comment by jtgrassie** [comment]
#4824 was not picking up python. #4839 resolves.

**Comment by ph4r05** [comment]
#4824 is updated so it contains the full fix.
