### ISSUE TITLE
monero-blockchain-export: Failed to create a transaction for the db: Permission denied

### ISSUE THREAD

**Issue by coneiric** [monero-project/monero#4826]
This problem was reported by a user on IRC. Here is a [paste of their logs](https://paste.ee/p/4Erhk).

Have had similar issues manually moving, then trying to import the moved blockchain. Get the same error.

**Comment by hyc** [comment]
Sounds like it's quite plainly a file permissions problem with the blockchain database.

**Comment by hyc** [comment]
If you're sure the file permissions are OK, then try running with strace and see which actual system call returned EPERM.

**Comment by coneiric** [comment]
Alright, just ran monero-blockchain-export/import tools. Seems to complete exporting/importing the database fine, but core dumps with unhandled exception `boost: mutex lock failed in pthread_mutex_lock: Invalid argument`. Looks like the same error addressed [here](https://github.com/monero-project/monero/pull/4785).

Good times...
