### ISSUE TITLE
Again seeing high CPU load on mainnet

### ISSUE THREAD

**Issue by arnuschky** [monero-project/monero#4835]
We're again experiencing high CPU load on all our mainnet instances. Seems to be coming in spikes:

![image](https://user-images.githubusercontent.com/179920/48313503-db8f9580-e5bd-11e8-87d7-300b5701e496.png)

Present since ~Friday, worse today. Anyone else seeing this?

Related: #4618  (we're running the patched version, so this isn't the problem)

**Comment by moneromooo-monero** [comment]
Same info needed :) perf top output and a few stack traces in the culprits.

**Comment by dEBRUYNE-1** [comment]
>worse today

Note that there have been a lot of transactions today with a huge amount of inputs (i.e. >100).

**Comment by arnuschky** [comment]
Ah that's the kind of info I was hoping for. Was too lazy to start tracing immediately. ;)

Admittedly I should have had a look in the pool first. I'll verify that this is the cause; if not I'll trace.

**Comment by moneromooo-monero** [comment]
Not really. If you only look at the data if there's no tx load, then those slow bits won't get fixed :)

**Comment by arnuschky** [comment]
Spikes are gone, so it must have been the transactions @dEBRUYNE-1 mentioned. Closing this. Thanks everyone.
