### ISSUE TITLE
Want to fork my own monero, what and how does NETWORK_ID WORK ?

### ISSUE THREAD

**Issue by reliefs** [monero-project/monero#4856]
Hi, 

I have forked cryptonote and got it all up and running, but i see a difference between how the deamon connect to the blockchain. 

In crytonote they do it this way.
//TODO Add here your network seed nodes
const std::initializer_list<const char*> SEED_NODES = {
  //"your_seed_ip1.com:8080",
  //"your_seed_ip2.com:8080",

Monero do it like this
boost::uuids::uuid const NETWORK_ID = { {
      0x12 ,0x30, 0xF1, 0x71 , 0x61, 0x04 , 0x41, 0x61, 0x17, 0x31, 0x00, 0x82, 0x16, 0xA1, 0xA1, 0x10
    } };

But what is network id, how does it work, can i just make my own network id, compile 2 monero and they connect without an ip ?

Thanks and sorry for the noob question, i have searched on google for answer without any luck.

**Comment by fluffypony** [comment]
No.

**Comment by reliefs** [comment]
we will see

**Comment by reliefs** [comment]
So whats the next step ?

Do i make the nework id sync my ip or ?

**Comment by trasherdk** [comment]
You might want to take questions like this to [stackoverflow](https://monero.stackexchange.com/tags/monero-forks/hot)
