### ISSUE TITLE
Run node on SSD and store blockchain on HDD?

### ISSUE THREAD

**Issue by nox956** [monero-project/monero#4861]
If I run my monero node on SSD and use `--data-dir path/of/HDD` to store blockchain data on HDD, will it still increase the efficiency of syncing with network? 

Because I really don't have that much space for entire blockchain data on SSD, it will be great if I can store these huge file on my hard disk even with less efficiency than running the whole thing on SSD.

Thanks!

**Comment by nioroso-x3** [comment]
I just let it sync using a SSD, then copy the synced folder back to HDD. Faster than syncing on the HDD from zero.

**Comment by nox956** [comment]
My node is actually synced, but when a new block is mined on the monero network, read/write files will cause high iowait, and that is my major concern.

**Comment by nox956** [comment]
@moneromooo-monero Got it, thanks!
