### ISSUE TITLE
Sync get stuck

### ISSUE THREAD

**Issue by ElLamparto** [monero-project/monero#4867]
Monero 'Beryllium Bullet' (v0.13.0.4-release), Debian Stretch 32bit.

DB migration failed: 
[MoneroFailedDBConversion.txt](https://github.com/monero-project/monero/files/2593067/MoneroFailedDBConversion.txt)

Then I synced from scratch. After a couple of weeks, it got stuck at 97.7% at height: 1651112.
I deleted the last 10 blocks: monero-blockchain-import --pop-blocks 10
and restarted monerod. It quickly resynchronized the 10 blocks and got stuck again.

What can I do?
Thanks for any hint.

**Comment by moneromooo-monero** [comment]
Start monerod with --log-level 2, wait it to get stuck again, post the logs to fpaste.org or similar.

**Comment by ElLamparto** [comment]
[bitmonero.log.zip](https://github.com/monero-project/monero/files/2598757/bitmonero.log.zip)

**Comment by moneromooo-monero** [comment]
If I post a patch adding more logs, can you build with it and post the extra logs to help debug ?

**Comment by moneromooo-monero** [comment]
Here's the patch. Save to PATCH and apply with : patch -p1 \< PATCH

<pre>
diff --git a/src/cryptonote_core/blockchain.cpp b/src/cryptonote_core/blockchain.cpp
index fa23b6bd2..3d6fb3677 100644
--- a/src/cryptonote_core/blockchain.cpp
+++ b/src/cryptonote_core/blockchain.cpp
@@ -638,6 +638,7 @@ block Blockchain::pop_block_from_blockchain()
 
   m_blocks_longhash_table.clear();
   m_scan_table.clear();
+MDEBUG("clearing");
   m_blocks_txs_check.clear();
   m_check_txin_table.clear();
 
@@ -2258,12 +2259,14 @@ bool Blockchain::get_tx_outputs_gindexs(const crypto::hash& tx_id, std::vector<u
 //------------------------------------------------------------------
 void Blockchain::on_new_tx_from_block(const cryptonote::transaction &tx)
 {
+MDEBUG("on_new_tx_from_block: db height " << m_db->height() << ", m_blocks_hash_check size " << m_blocks_hash_check.size() << ", tx " << get_transaction_hash(tx));
 #if defined(PER_BLOCK_CHECKPOINT)
   // check if we're doing per-block checkpointing
   if (m_db->height() < m_blocks_hash_check.size())
   {
     TIME_MEASURE_START(a);
     m_blocks_txs_check.push_back(get_transaction_hash(tx));
+MDEBUG("pushed, now " << m_blocks_txs_check.size());
     TIME_MEASURE_FINISH(a);
     if(m_show_time_stats)
     {
@@ -3450,9 +3453,14 @@ leave:
     {
       // ND: if fast_check is enabled for blocks, there is no need to check
       // the transaction inputs, but do some sanity checks anyway.
+const bool flag = tx_index >= m_blocks_txs_check.size();
       if (tx_index >= m_blocks_txs_check.size() || memcmp(&m_blocks_txs_check[tx_index++], &tx_id, sizeof(tx_id)) != 0)
       {
         MERROR_VER("Block with id: " << id << " has at least one transaction (id: " << tx_id << ") with wrong inputs.");
+MERROR_VER("tx_index: " << tx_index << ", flag " << flag);
+MERROR_VER("tx_id: " << tx_id);
+MERROR_VER("m_blocks_txs_check: " << m_blocks_txs_check.size());
+for (const auto &h: m_blocks_txs_check) MERROR_VER("  : " << h);
         //TODO: why is this done?  make sure that keeping invalid blocks makes sense.
         add_block_as_invalid(bl, id);
         MERROR_VER("Block with id " << id << " added as invalid because of wrong inputs in transactions");
@@ -3468,6 +3476,7 @@ leave:
     cumulative_block_weight += tx_weight;
   }
 
+MDEBUG("clearing");
   m_blocks_txs_check.clear();
 
   TIME_MEASURE_START(vmt);
@@ -3591,6 +3600,7 @@ bool Blockchain::add_new_block(const block& bl_, block_verification_context& bvc
     LOG_PRINT_L3("block with id = " << id << " already exists");
     bvc.m_already_exists = true;
     m_db->block_txn_stop();
+MDEBUG("clearing");
     m_blocks_txs_check.clear();
     return false;
   }
@@ -3602,6 +3612,7 @@ bool Blockchain::add_new_block(const block& bl_, block_verification_context& bvc
     bvc.m_added_to_main_chain = false;
     m_db->block_txn_stop();
     bool r = handle_alternative_block(bl, id, bvc);
+MDEBUG("clearing");
     m_blocks_txs_check.clear();
     return r;
     //never relay alternative blocks
@@ -3759,6 +3770,7 @@ bool Blockchain::cleanup_handle_incoming_blocks(bool force_sync)
   TIME_MEASURE_FINISH(t1);
   m_blocks_longhash_table.clear();
   m_scan_table.clear();
+MDEBUG("clearing");
   m_blocks_txs_check.clear();
   m_check_txin_table.clear();
 
</pre>

**Comment by ElLamparto** [comment]
Do you want me to recompile monerod? If so, I prefer that you give me an executable or you add the extra traces to the next release of monero.

**Comment by moneromooo-monero** [comment]
Yes. I'll PR this to a temp branch so the build machine creates a binary. I'll post again when that's ready.

**Comment by moneromooo-monero** [comment]
What version are you running now ?

**Comment by ElLamparto** [comment]
Monero 'Beryllium Bullet' (v0.13.0.4-release), Debian Stretch 32bit.

**Comment by moneromooo-monero** [comment]
https://build.getmonero.org/downloads/monero-567b5fd9-win32.tar.gz

**Comment by moneromooo-monero** [comment]
Run with: --log-level 2

**Comment by ElLamparto** [comment]
Win32? I am on Linux 32bit. Sorry.

**Comment by ElLamparto** [comment]
[bitmonero.zip](https://github.com/monero-project/monero/files/2617220/bitmonero.zip)
Here is the log. Good luck!

**Comment by ElLamparto** [comment]
It is syncing again. Good work!. Thank you.

**Comment by ElLamparto** [comment]
Ok, I'll let you the honor...

**Comment by moneromooo-monero** [comment]
Now merged.

+resolved
