### ISSUE TITLE
rpc /getblocks.bin return 404

### ISSUE THREAD

**Issue by meiyoung** [monero-project/monero#4886]
rpc API  /getblocks.bin return 404.

I call  it like following:
```
{"start_height":1095530, "prune": true, "block_ids":[]}
```

How to fix it? 

Can someone give me an example to call this RPC?

**Comment by meiyoung** [comment]
`/get_o_indexes.bin` is 404

**Comment by moneromooo-monero** [comment]
It's a binary call, not a JSON call. If you want to use JSON calls, don't use the bin ones.

**Comment by moneromooo-monero** [comment]
You are sending JSON. Text.

**Comment by meiyoung** [comment]
thank you.

can you give me an example?

**Comment by moneromooo-monero** [comment]
You can look at wallet2.cpp, which calls those. But it's binary code, you have to send binary data, that means serialization, a fair bit of code.

Or you could use the JSON RPC, like getblockheaderbyheight, etc.

**Comment by moneromooo-monero** [comment]
+invalid
