### ISSUE TITLE
Code patterns issues

### ISSUE THREAD

**Issue by calidion** [monero-project/monero#4893]
monero  600 issues.

https://app.codacy.com/project/calidion/monero/dashboard

FYI.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4894

I hesitated about the prefix iterator increments, but those will most likely be optimized away anyway and aren't in hot paths.

**Comment by moneromooo-monero** [comment]
I'll try to check that link again from time to time in case it finds more stuff.

+resolved
