### ISSUE TITLE
rpc wallet: histogram reports no unlocked rct outputs, not even ours

### ISSUE THREAD

**Issue by mmorrell** [monero-project/monero#4904]
I'm using a modified `monero-wallet-rpc` with the required confirmations to unlock reduced to 1.

e.g. `#define CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE             1`

Frequently when I try to call `transfer` using `monero-wallet-rpc` I get the message: "histogram reports no unlocked rct outputs, not even ours".

Is this expected and/or is there a workaround? For now, I am using retry logic. When it eventually succeeds, all the ring members are from the same date, consistently.

**Comment by moneromooo-monero** [comment]
You found the issue, since you closed this ?
