### ISSUE TITLE
Why the Bullet range proof always has T1 = rct::scalarmultKey(T1, INV_EIGHT)?

### ISSUE THREAD

**Issue by woshidadashi** [monero-project/monero#4905]
I am reading the source code of Monero. In the Bullet range proof, there is always a line like T1 = rct::scalarmultKey(T1, INV_EIGHT), why there is always a INV_EIGHT mult the point? Can anyone help me? Thank you.

**Comment by moneromooo-monero** [comment]
This is a bug tracker. Please use it for bugs and other issues.

If you want to ask this, try monero.stackexchange.com, this is a good place for this.

+invalid
