### ISSUE TITLE
running two monerod

### ISSUE THREAD

**Issue by AndrVdov** [monero-project/monero#4910]
Now there is a working monerod.
It is necessary to run another one, but with a block chain from another directory.
run:
./monerod --data-dir /home/user/MoneroBlockchain --p2p-bind-port 18500 --rpc-bind-port 18550

get err:
**Error creating ZMQ Socket: Address already in use
Failed to add TCP Socket (127.0.0.1:18082) to ZMQ RPC Server**

How start two demons so that they do not interfere with each other?

**Comment by moneromooo-monero** [comment]
This is not a bug. It is telling you the zmq port is already used. Did you try to tell it to use another one ?
--help shows:
--zmq-rpc-bind-port arg (=18082, 28082 if 'testnet', 38082 if 'stagenet')

**Comment by AndrVdov** [comment]
it helped, thanks

**Comment by moneromooo-monero** [comment]
+invalid
