### ISSUE TITLE
usage of tx-notify

### ISSUE THREAD

**Issue by peterpan0708** [monero-project/monero#4911]
I want to listen all the incoming transactions to my wallet, and I plan to use tx-notify, I will generate an address for each user ,  but all I can get from tx-notify is a tx_hash, can i know how much and which address of my wallet the user send to me?thanks very much!

**Comment by peterpan0708** [comment]
I got it. I can use rpc method get_transfer_by_txid to do that.

**Comment by dEBRUYNE-1** [comment]
@peterpan0708 - Can this be closed?

**Comment by peterpan0708** [comment]
@dEBRUYNE-1  I have a question, when i config --tx-notify, for every incoming transaction, it triggers more than 10 times , that's to much for me, do i have a choice to config it.

**Comment by dEBRUYNE-1** [comment]
Can you illustrate your issue with an example?
