### ISSUE TITLE
gettransactions: unconfirmed tx (in mempool) show very high block_height

### ISSUE THREAD

**Issue by got3nks** [monero-project/monero#4916]
When a tx is not confirmed yet and you retrieve it through the monerod's RPC `/gettransactions` call, `block_height` and `block_timestamp` are very large number.

```
      'block_height' => '18446744073709551615',
      'block_timestamp' => '18446744073709551615',
```

I wonder how they are calculated? I guess the documentation should be updated: https://www.getmonero.org/resources/developer-guides/daemon-rpc.html

**Comment by hyc** [comment]
That's MAX_ULONG. Doesn't mean anything.

**Comment by got3nks** [comment]
I would rather expect it to be a null value for an unconfirmed tx.
Or update the documentation, I guess?

**Comment by xiphon** [comment]
1. Check `in_pool` field first.
2. The code explicitly sets `block_height` and `block_timestamp` to `MAX_ULONG` if tx is in pool.

**Comment by moneromooo-monero** [comment]
Not a bug.

+invalid
