### ISSUE TITLE
[master] Ledger transfer broken

### ISSUE THREAD

**Issue by selsta** [monero-project/monero#4917]
Using git-bisect, d6937e373b32628fff414c7d8a07e4323593c6a0 broke transfer using Ledger.

```
[wallet xxxxx]: transfer xxx 0.1
Wallet password: 
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
Error: unexpected error: Wrong Device Status : SW=6911 (EXPECT=9000, MASK=ffff)
```

**Comment by moneromooo-monero** [comment]
Does this come with an exception (and stack) in the log ?

**Comment by selsta** [comment]
The wallet does not crash.

**Comment by moneromooo-monero** [comment]
I forgot the logs are off by default now. Log level 0 should be enough.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4921

**Comment by moneromooo-monero** [comment]
+resolved
