### ISSUE TITLE
Private testnet - getblocktemplate returns invalid (previous) prev_hash

### ISSUE THREAD

**Issue by jakubschimer** [monero-project/monero#4922]
I'am running Monero (v0.13.0.4-release) private testnet from height 1.
I'am periodically calling getblocktemplate via RPC. After few successfull block submits (1 to 4),
the prev_hash field in getblocktemplate response doesen't change - it stays on the same value which of course results in new block submits being rejected. (----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT N message in monerod). On the other hand, when i run start_mining <wallet_addr> on monerod, prev_hash field in getblocktemplate result seems to be changing as it's supposed to.

Iam running testnet nodes as:
monerod --testnet --no-igd --hide-my-port --data-dir ~/testnet/node_01 --p2p-bind-ip 0.0.0.0 --log-level 1 --add-exclusive-node 127.0.0.1:38080 --add-exclusive-node 127.0.0.1:48080 --fixed-difficulty 199 --detach
monerod --testnet --p2p-bind-port 48080 --rpc-bind-port 48081 --zmq-rpc-bind-port 48082 --no-igd --hide-my-port  --log-level 1 --data-dir ~/testnet/node_03 --p2p-bind-ip 0.0.0.0 --add-exclusive-node 127.0.0.1:28080 --add-exclusive-node 127.0.0.1:38080 --fixed-difficulty 199 --detach 
monerod --testnet --p2p-bind-port 38080 --rpc-bind-port 38081 --zmq-rpc-bind-port 38082 --no-igd --hide-my-port  --log-level 0,blockchain:DEBUG,*rpc*:DEBUG --data-dir ~/testnet/node_02 --p2p-bind-ip 0.0.0.0 --add-exclusive-node 127.0.0.1:28080 --add-exclusive-node 127.0.0.1:48080 --fixed-difficulty 199

Log output from node to which i'am connecting via RPC can be found here:
https://paste.fedoraproject.org/paste/csSp6In4lX2UPxVg-LgPxQ

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4928

I could repro the problem. I did not see if after the patch. Given it's race, this does not prove it's 100% fixed though. Please check whether you can still see it.

**Comment by moneromooo-monero** [comment]
Can you confirm it fixed your problem ?

**Comment by jakubschimer** [comment]
Hello,
Yes, your patch fixed the problem.

Thank you
Jakub

**Comment by moneromooo-monero** [comment]
+resolved
