### ISSUE TITLE
Error: Couldn't open wallet: Unable to enumerate device

### ISSUE THREAD

**Issue by bitofdon** [monero-project/monero#4937]
Ledge Nano S + gui v0.13.0.4

I tried to replicate after it happened twice when using the Nano S and latest gui. I got it to work after restarting daemon, opening gui, then proceeding with the Nano S. 

Was wondering if any others have run into this occurrence. 

![error](https://user-images.githubusercontent.com/24719710/49419007-ef5c9080-f752-11e8-9c0f-cc818238bfae.PNG)

**Comment by selsta** [comment]
Which operating system are you using?

**Comment by dEBRUYNE-1** [comment]
I guess your USB cable or USB port might be slightly damaged, which occasionally causes this error to be thrown.

**Comment by bitofdon** [comment]
@selsta Windows 10

@dEBRUYNE-1 haven't been able to recreate the issue, but will note it if i do
