### ISSUE TITLE
Feature: Invitation only blockchain

### ISSUE THREAD

**Issue by speakeasy** [monero-project/monero#4961]
I have a feature request for the ability to make an invitation only monero based blockchain. This is useful for privatized use of the blockchain on the public internet, guarding against bankers trying to take over network investment and massive mining operations.

**Comment by moneroexamples** [comment]
And who would be "the authority" give out such permissions?

**Comment by speakeasy** [comment]
I guess it depends on the organizational structure of the blockchain that anyone wanted to make.. It would need to be distributed, and may possibly be issued to users as invites much like a private tracker (e.g. gazelle) or to certain classes of users (acl)

**Comment by moneromooo-monero** [comment]
This goes against the goals of monero (decentralized, permissionless, open to all).

I'll close this sometime later after others had time to add pertinent arguments if they so wish.

**Comment by speakeasy** [comment]
Ah I understand. It isn't exclusive and therefore can be harnessed by the government/banking cartels to the enslavement of mankind. Nice goals.

**Comment by moneromooo-monero** [comment]
Exactly, similarly to you being allowed to live and dumb down humanity.

**Comment by speakeasy** [comment]
It seems that you're the one dumbing everyone down. It's okay I'm not offended you work for the us banking cartel and the nwo

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a toilet.

+invalid

**Comment by speakeasy** [comment]
Yeah if I knew who you were I would kill you myself.
