### ISSUE TITLE
 Two request make this error

### ISSUE THREAD

**Issue by reliefs** [monero-project/monero#4975]
After two request i start to get this error, did this not happen a few weeks ago?

018-11-29 00:41:46.706 [RPC0] ERROR wallet.wallet2 src/wallet/wallet2.cpp:4582 !is_keys_file_locked(). THROW EXCEPTION: error::wallet_internal_error

I talked with other devs, they say it's a problem with monero rpc.

https://github.com/monero-integrations/monerophp/issues/80

**Comment by moneromooo-monero** [comment]
What monero version ? What requests ? What other pertinent information ?

**Comment by reliefs** [comment]
When i run two instance of the same key with rpc i get this error. No issue from version 12 and before, started after release of 12.

**Comment by moneromooo-monero** [comment]
By "key" you mean "wallet file" ?

**Comment by reliefs** [comment]
yes the wallet file, I just woke up.. I will get better logs files soon, sorry for that.

**Comment by moneromooo-monero** [comment]
Then it's normal. Do not run two wallet programs on the same wallet file at the same time.

**Comment by moneromooo-monero** [comment]
+invalid
