### ISSUE TITLE
RPC createwallet method does not remove filelock on completion

### ISSUE THREAD

**Issue by Brandantl** [monero-project/monero#4990]
Version: https://github.com/monero-project/monero/releases/tag/v0.13.0.4

Monero RPC (monero-wallet-rpc WIN32/LINUX) method `create_wallet` does not release the file lock after it returns from creating the wallet. Thus the newly created wallet cannot be opened by both Monero RPC or deleted by the system administrator. 

RPC `create_wallet` POST DATA
`{ "id" : "0", "jsonrpc" : "2.0", "method" : "create_wallet", "params" : { "filename" : "Discord-User-431682365832691722", "language" : "English", "password" : "" } }`

RPC `create_wallet` JSON return 
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
  }
}
```

When you try to open newly created wallet from the same RPC that created it.
`2018-12-17 17:54:15.416 [RPC0]  ERROR   wallet.wallet2  src/wallet/wallet2.cpp:4582     !is_keys_file_locked(). THROW EXCEPTION: error::wallet_internal_error`

Requires RPC that created the wallet to be terminated/restarted before the wallet can be opened.

**Comment by moneromooo-monero** [comment]
That's because it is open. If you want to open it again, close it first.

**Comment by Brandantl** [comment]
Oh has the behavior of the rpc changed to auto open the wallets on create wallet? It didnt always do that.

**Comment by moneromooo-monero** [comment]
I don't know. Reading the code, it currently does not close it.
It closes the old wallet if the new one's creation succeds. If it fails, the old wallet is kept open.

**Comment by Brandantl** [comment]
Thanks ill close this unless you think it needs to stay open.
