### ISSUE TITLE
monero-wallet-rpc export_key_images returns unexpected result

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#4992]
monero-wallet-rpc `export_key_images` returns a response like `{id=0, jsonrpc=2.0, result={offset=311}}` which does not include `signed_key_images` as [documented](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#export_key_images).

Environment: latest master, Mac OSX

**Comment by moneromooo-monero** [comment]
Did you import outputs beforehand ? export_key_images will export those *new* ones which were imported.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5012 allows you to get all key images.

**Comment by woodser** [comment]
No I didn't import outputs beforehand.  The need to import outputs then call export_key_images to return new images was unknown to me as it's not documented for wallet RPC.  +1 on the ability to get all key images (#5012)

**Comment by woodser** [comment]
Resolved by #5012
