### ISSUE TITLE
is there any golang or python sdk here

### ISSUE THREAD

**Issue by zhp1254** [monero-project/monero#4996]
i want to create transaction use vin on golang  is there any golang or python sdk here

**Comment by ehanoc** [comment]
I was able to create python bindings for monero's main tree, but haven't had time to maintain it or expose more api's. 

If you have some C++ / python skills, this might help. https://github.com/ehanoc/pymonero

**Comment by johnalanwoods** [comment]
@ehanoc nice work.

**Comment by erciccione** [comment]
@ehanoc Would you consider transfer and develop your pymonero project on the [Monero Ecosystem project](https://github.com/monero-ecosystem/meta)? I think it could give much more exposure and attract more contributors.

**Comment by ehanoc** [comment]
@erciccione yes, totally

**Comment by erciccione** [comment]
I'm gonna open an issue on the meta repo in the Monero Ecosystem proposin to add your repo, we have our own [governance process]() to add new project. Will ping you there

**Comment by moneromooo-monero** [comment]
Not a bug

+invalid
