### ISSUE TITLE
How do I find the PUBKEY address and SCRIPT address? Or where is it located in the codebase?

### ISSUE THREAD

**Issue by ipabz** [monero-project/monero#4997]

**Comment by fluffypony** [comment]
Neither of those terms make sense with Monero. Are you thinking of Bitcoin? Some context might be useful.

**Comment by ipabz** [comment]
On bitcoin I have the pubkey and scriptkey to validate the address. Do we have something similar for monero?

**Comment by fluffypony** [comment]
Nope. In Monero your address *is* a pair of public keys (public viewkey and public spendkey). The address is valid as long as it passes the checksum baked into it. Monero doesn’t have script or anything like it.

There are more details on Monero’s address format on the Monero StackExchange, and there’s a Monero key tools client-side JS site that has code that is worth parsing.

**Comment by ipabz** [comment]
Thanks you very much 👍
