### ISSUE TITLE
monero-wallet-cli doesn't accept password at command line

### ISSUE THREAD

**Issue by jacoblyles** [monero-project/monero#4998]
`monero-wallet-cli` isn't allowing me to supply the wallet password with a command line argument. This hinders automation. 

For example, the following command will pause and ask me for the password:

`$ monero-wallet-cli --wallet-file wallet_4 --password "" --command prepare_multisig`

The output is:

```2018-12-19 19:14:47,179 INFO  [default] Page size: 4096
This is the command line monero wallet. It needs to connect to a monero
daemon to work correctly.
WARNING: Do not reuse your Monero keys on another fork, UNLESS this fork has key reuse mitigations built in. Doing so will harm your privacy.

Monero 'Beryllium Bullet' (v0.13.0.4-release)
Logging to monero-wallet-cli.log
Opened wallet: 49PNTCFicPUcbFhVSE6sWZQoJsdef11TTBFP7J7cDtk7ZpaJep3bbHJXtXsZYEW1ssVXrgAJcX56xTPhnkdLfUdNMDGpfid
**********************************************************************
Use the "help" command to see the list of available commands.
Use "help <command>" to see a command's documentation.
**********************************************************************
Wallet password:
```

**Comment by rbrunner7** [comment]
I can't reproduce this problem with current HEAD, on a Debian Linux variant: It does not ask for a password but correctly complains that the `prepare_multisig` command needs parameters to execute (if I just use the command as listed above).

I tried with an empty password, as suggested by the command line, and also with a password set.

**Comment by fluffypony** [comment]
Just to be clear - is this with a blank password or not? Also do you have to run release builds or can you run head?

**Comment by jacoblyles** [comment]
Do you think this could be a Mac vs. Linux thing? I could spin up a linux box somewhere and see if I get what you get.

**Comment by rbrunner7** [comment]
> prepare_multisig does not require parameters. When I supply the password, it returns the expected multisig data.

Yes - I think chose one of the other multisig commands by accident.

I just tried with 0.13.0.4 release on Windows and could reproduce the problem. As I tried with **HEAD** on Linux I would guess that one of the commits since release corrects the problem. Command-line parsing is so simple it's very hard to imagine that there are accidental or unexpected differences between Linux and MacOS there.

**Comment by dethos** [comment]
> but I suspect you can bypass that particular password prompt by setting the wallet to not ask (set ask-password 0).

This actually solves the reported problem. 
The issue with the initial command is that the `--password` argument is used to "open" the wallet file, but running the `prepare_multisig` command also requires the password and that is the one being asked on the provided output example.

**Comment by moneromooo-monero** [comment]
+invalid
