### ISSUE TITLE
3-of-5 multisig creation results in 5 different addresses

### ISSUE THREAD

**Issue by jacoblyles** [monero-project/monero#5002]
I attempted to create a 3-of-5 multisig wallet. When I finished, opening the wallets with `monero-wallet-cli` shows that each of them has a different address. 

I attempted to `export_multisig_info` and `import_multisig_info` to create a transaction. I received the error message `Error: Failed to import multisig info: Multisig info is for a different account`

Testing on commit https://github.com/monero-project/monero/commit/ed54ac8fdfe332c4ec6b9fd9331024d862ecad51

**Comment by jacoblyles** [comment]
It seems like I was using the wrong APIs to make these wallets. According to [this comment ](https://github.com/monero-project/monero/issues/5000#issuecomment-449515006) I should be using `exchange_multisig_keys` for (n-m)+1 rounds instead of using  `finalize_multisig` if m < n-1. 

In that case `finalize_multisig` should probably return an error instead of making malformed wallets.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5004 does now.

**Comment by jacoblyles** [comment]
I confirmed the software rejects improper calls to `finalize_multisig` now. This issue can be closed when #5004 is merged
