### ISSUE TITLE
Write a test about cn_serialize and cn_deserialize for bulletproof failed.

### ISSUE THREAD

**Issue by woshidadashi** [monero-project/monero#5024]
I write a test case for cn_serialize and cn_deserialize for bulletproof, but this case failed, is there any problem about the code?
`TEST (bulletproofs, valid_random) {
   
        rct::Bulletproof proof = bulletproof_PROVE(crypto::rand<uint64_t>(), rct::skGen());
        std::string strString = serilizationProofs::cn_serialize(proof);
        rct::Bulletproof proofAfterDeser;
        serilizationProofs::cn_deserialize(strString, proofAfterDeser);
        GTEST_ASSERT_EQ(rct::bulletproof_VERIFY(proofAfterDeser), true);
    
}`

**Comment by moneromooo-monero** [comment]
Wrong repo ? serilizationProofs::cn_serialize is not monero code.

**Comment by woshidadashi** [comment]
Yes, it is. It is on the path monero/src/device_trezor/trezor/protocol.hpp

**Comment by woshidadashi** [comment]
serilizationProofs:: is just copy it to test file and rename the namespace

**Comment by moneromooo-monero** [comment]
I see a protocol::cn_deserialize there. If that's what you're using, then bulletproofs are not self contained, they drop some data which can be recovered from the rest of the transaction (for blockchain space reasons). See expand_transaction_1.

**Comment by woshidadashi** [comment]
OK, thanks. I know what you mean.

**Comment by moneromooo-monero** [comment]
Not a bug (though admittedly confusing).

+invalid
