### ISSUE TITLE
Long wait for response

### ISSUE THREAD

**Issue by yura-sutnuk** [monero-project/monero#5038]
Hi, i have my wallet-rpc and daemon on a different servers, in my application basically i need only create transaction method and generate new address but avarage time waiting for response is 10-15 seconds. On both servers i have HDD and i have few question:
1) wich one i should upgrade to SSD for speed up?
2) can i some how speed up without upgrade to SSD?

Also can monero proceed several request at one time or it put users in queue?

Monero 'Beryllium Bullet' (v0.13.0.2-release)

**Comment by moneromooo-monero** [comment]
The blockchain wants to be on a SSD for speed. The wallet file is irrelevant here. Use a recent monero for speedups. If you want to keep using a release, try 0.13.0.4, though I'm not sure how many such speedups it has.
RPC are processed sequentially.

**Comment by yura-sutnuk** [comment]
so i need SSD only for server with daemon? ok thanks.

**Comment by yura-sutnuk** [comment]
can you also say which server requirement have monero for stable work? on your site i see requirement for 2014 year, is they still actual?

**Comment by yura-sutnuk** [comment]
Ok, Thanks
