### ISSUE TITLE
"status" command does not show peer counts

### ISSUE THREAD

**Issue by GoodEn0ugh** [monero-project/monero#5040]
I recently have run into an issue where my full node will not show me peer counts when running "status":

`Height: 1741006/1741006 (100.0%) on mainnet, not mining, net hash 378.72 MH/s, v9, up to date, 0(out)+0(in) connections`

This started around the same time I spun up another node on the same network and exposed on a different p2p port, but I'm not 100% sure it's related.

Some addition logs:

[print_cn (run immediately after the above "status")](https://paste.fedoraproject.org/paste/mE8ey2TWZzlHlqnGgUznxA)

If there are any other logs I can supply or things I can do to test please let me know!

**Comment by GoodEn0ugh** [comment]
Some environment notes:

- I am running on CentOS 7
- I have compiled from scratch with GCC 8.2/CMake 3.12.2
- I am currently running v0.13.0.0-master-e344d93 (compiled today, on 01/03)

**Comment by GoodEn0ugh** [comment]
Attached below is a debug log at log_level 1, during which I did both "status" and "print_cn".

I also left in a few lines before the start of the increased log level that show a trace/error of some sort, wasn't sure if that was pertinent. Let me know what else I can provide!

[monerod_debug.log.gz](https://github.com/monero-project/monero/files/2726006/monerod_debug.log.gz)

**Comment by moneromooo-monero** [comment]
Are you running with restricted RPC ?

**Comment by GoodEn0ugh** [comment]
Yes, running with the following args:

`./monerod --rpc-bind-ip 0.0.0.0 --rpc-bind-port 18089 --confirm-external-bind --restricted-rpc --disable-dns-checkpoints --log-file monerod.log`

**Comment by moneromooo-monero** [comment]
Then don't for now. There will be an override for the local daemon, which currently uses that same code path, and that connection information is restricted.

**Comment by moneromooo-monero** [comment]
Well, actually, don't don't, since you bind to 0.0.0.0. Just ignore the 0/0 report, it'll get fixed in the medium term.

**Comment by GoodEn0ugh** [comment]
Ok, awesome! I'll leave it and ignore that for now.

Closing.
