### ISSUE TITLE
is there any sdk that can create transaction and sign hex without rpc api?

### ISSUE THREAD

**Issue by ruanqunfeng** [monero-project/monero#5057]
is there any sdk that can create transaction and sign hex without rpc api?

**Comment by jtgrassie** [comment]
No. In future, questions to either https://monero.stackexchange.com/ or https://www.reddit.com/r/monerosupport/ please. GitHub issues are for bug/issue tracking, not general Monero questions.

**Comment by moneromooo-monero** [comment]
Not a bug report, closing.

+invalid
