### ISSUE TITLE
Game theoretic formal peer reviewed paper about XMR tail emissions needed

### ISSUE THREAD

**Issue by electricatom** [monero-project/monero#5059]
To: Monero Research Labs

Tail emissions within XMR are an enormous game theoretic concept that we don't see in other (major) cryptocurrencies. However, there's no game theoretic paper that's been formally peer reviewed within Monero or the crypto community though. Everyone, including XMR contributors and MRL researchers, have opinions on tail emissions and nothing more than opinions. This is a serious matter that the MRL should be working on providing the community as it entails the future of XMR. It's tremendously brushed off as fine and all who challenge it are ridiculed, including by XMR contributors and Monero subreddit moderators, into the ground with no real proof behind their ridiculing rather than their opinions.

Eventually, a game theoretic paper within the crypto community might prove that XMR tail emissions is inefficient or unnecessary for the long term, and that zero-knowledge based decentralized self sovereign identity (SSI) will act as a natural "tail emissions" within capped supplies (of all crypto's) to provide proper redistribution and stability, so the ideology of immutability is sound (if you're trying to become anonymous 'digital cash' and not an anonymous 'payment network' which is what I think XMR should be gunning for as it would create its own utility-niche (captures a giant multi-trillion dollar market) rather than competing/testing with/for Bitcoin, Zcash, fiat, continuously evolving formal peer reviewed papers, etc... As both, a governance system within Monero and this highly game theoretic topic evolve it shouldn't be off the table within any logically centralized governance system, full of an expanding pool of users (decentralization), of any decentralized crytocurrency project, when maturity of the network has reached a certain point, to make a final decentralized political decision (of reassurance) on the supplied direction of the project for the long term. The community could even vote to leave everything as it is... All projects learn with time, mistakes are initially made and variables change. It shouldn't even be off the table to create a sustainable politically based supply schedule for the users to vote on periodically (e.g.: immutably every 10, 20, 30, 50, 100, etc years or so... A final decision could also be voted on to immutably never change a thing or to immutably only allow the one final decision indefinitely...).

**Comment by moneromooo-monero** [comment]
This is a bug tracker for the monero sofware. Try #monero-research-lab on Freenode IRC.
Or the MRL have a repo at https://github.com/monero-project/research-lab/ where this would be on topic.

+invalid
