### ISSUE TITLE
Transaction notifications comes too often

### ISSUE THREAD

**Issue by KraxCZ** [monero-project/monero#5066]
I'm using new notification system (via tx_notify). It seems to me that notifications about the same transaction comes too often (every about 20 seconds) until the transaction is mined. 
I have the experience with bitcoind where transaction is reported once when it arrives to mempool and for the second time when it is mined.
What's worse, it seems that the notifications are triggered every time get_transfer_by_txid RPC method is invoked.
Are both of the described cases intended? At least the second one seems to me as a bug.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5069 should fix it.

**Comment by moneromooo-monero** [comment]
+resolved

**Comment by moneromooo-monero** [comment]
+resolved
