### ISSUE TITLE
Remove `mixins` option from the Wallet's transfer RPC method

### ISSUE THREAD

**Issue by lessless** [monero-project/monero#5071]
Hi,

According to recent discussion with @moneromooo-monero  on IRC `mixing` option in  `transfer` call is no longer relevant. 
https://ww.getmonero.org/resources/developer-guides/wallet-rpc.html#transfer

**Comment by jtgrassie** [comment]
I think a documentation update would be more beneficial to start with.

**Comment by moneromooo-monero** [comment]
+resolved
