### ISSUE TITLE
Can wallet-rpc serve multiple requests in parallel

### ISSUE THREAD

**Issue by kim0** [monero-project/monero#5077]
Say I have 10 different accounts. Is it possible to initiate 5 transfers (each between a pair of accounts) such that they are done in parallel (i.e. NOT waiting till transfer 1 is done, to start transfer 2 ...etc). Thanks

**Comment by hyc** [comment]
No.

**Comment by kim0** [comment]
well, I was building an API that interacts with wallet-rpc. The API should handle more than one request at a time. Not sure what my options are now? Thanks for helping

**Comment by webzorg** [comment]
Pitty, I have problems with multi threaded access too, seems like wallet-rpc cannot accomodate parralel requests.
