### ISSUE TITLE
Daemon crashed after error "BDB4531 transaction has active cursors"

### ISSUE THREAD

**Issue by osensei** [monero-project/monero#508]
The daemon had been running for almost 3 days on my RPi2 with current master's HEAD (4061a32082554f3b18429b85b35398469b061faa) when it crashed with the following output:

```
BDB4531 transaction has active cursors 
BDB0061 PANIC: Invalid argument 
Segmentation fault (core dumped)
```

**Comment by moneromooo-monero** [comment]
Berkeley DB support is now removed as LMDB supports all our targets.

+resolved
