### ISSUE TITLE
Anybody found there has a quick increase of hashrate？

### ISSUE THREAD

**Issue by eastera1** [monero-project/monero#5083]
Anybody found there has a quick increase of hashrate? With such high hashrate under current low coin price, making profit is almost impossible. Apparently it impacts miners' interest in minging Monero coins, in turn impacts security of the  Monero ecosystem. 
Looking back the whole network hashrate in previous year, it is surpprisely to find a similar hash rate jump after Bitman released its Monero ASIC miner at the begining of 2018. After that time the whole network hashrate maintains a high value and doesnt drop down until Monero issued a hard fork later (Apr. 2018). I remeber some guys called a 'tweak' added in the POW algo with which makes ASIC mining broken.
 
In fact， under such low coin price and inceasing of hashrate so much dont make sense. is it possible ASIC miners coming back? and is it possbile to add a tweak in current algo to keep miners armed with ASIC from our ecosystem, just like before?

**Comment by moneromooo-monero** [comment]
This is a bug tracker. Please try #monero on Freenode, or Reddit.

+invalid
