### ISSUE TITLE
Fork to Argon/ArgonNight

### ISSUE THREAD

**Issue by ClashLuke** [monero-project/monero#5085]
Regarding the current hype for Argon and Monero's and Aeon's IoT friendliness.
It would certainly be possible to make a move in the direction of Argon or ArgonNight.
As of right now, the only major projected I noticed working towards this goal would be Turtlecoin.
Since I personally don't know whether this has scientific reasoning or if you were busy with other things, I will propose a change of CryptoNight (or CryptoNight-Lite in case of Aeon) to Argon2d or even ArgonNight.
An unclean reference implementation can be found in here:
https://github.com/Tax-Project/Test-Tax/blob/master/src/crypto/slow-hash.c#L862

If argon would be preferred over ArgonNight, it would certainly be possible to remove everything apart from what currently is the initialization. If you really want to have the optimal cycles per byte and don't care about ASICs, you could always go with Argon without any support such as the keccak which still is there in ArgonNight.

Advantages of Argon and ArgonNight over CryptoNight would be the following:
-- Increased IoT friendliness
-- Increased Hashrate
---- Increased Verification Speeds
---- Increased Security against (D)DoSing
-- Increased ASIC resistance
-- Easier Rebalancing of CPU Hashrate to GPU Hashrate
-- Higher Modularity and therefore a higher chance that people will tweak variables or implement slight changes to further increase ASIC resistance of the whole CryptoNote ecosystem.

Thanks for reading this proposal, and not to worry, I could implement Argon or ArgonNight into Monero, in case its decided to be the next algorithm. It is only about whether or not the community would like to see it implemented.

**Comment by hyc** [comment]
>-- Increased Hashrate
>---- Increased Verification Speeds

Hash rate is not what secures a network, energy is. This is moronic.
