### ISSUE TITLE
Genesis block question

### ISSUE THREAD

**Issue by Franzferdinan51** [monero-project/monero#5088]
okay so trying to learn here and build my own custom monero by doing so but im trying to generate a genesis block okay so odd question im trying to fork and i guess most wouldnt wanna help but its mainly educational,
i have made it to starting my daemon and when i do i get failed to add genesis transaction okay so i know --print-gensis-tx or something like that used to work but doesnt? i havent found alot of info on this because obviously most dont want you to fork i assume but i could use a point in the right direction  how to get the gensis transaction tx key/block

**Comment by Franzferdinan51** [comment]
ive tried https://monero.stackexchange.com/questions/8468/how-can-i-get-my-own-genesis-tx-to-use-in-my-monero-fork?rq=1

but theirs very little info on the subject and so i put it at the end of the specfied file and it doesnt work so im at a loss where to even put that

**Comment by fluffypony** [comment]
This is a bug tracker not a scamcoin creation helpline.

**Comment by Franzferdinan51** [comment]
thats kinda harsh dont you think?
