### ISSUE TITLE
daemon rpc get_peer_list returns uninitialized values for every peer

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#5093]
Daemon RPC's `get_peer_list` returns the following for every peer under `gray_list` and `white_list`:

`{ host: '<none>', id: 0, ip: 0, last_seen: 0, port: 0 }`

Method: POST
URI: http://localhost:38081/get_peer_list

The daemon being tested was updated from master yesterday and it works as expected on a previous build from 12/18.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5094

**Comment by moneromooo-monero** [comment]
The code got rewritten in the meantime.

+resolved
