### ISSUE TITLE
Issue creating then relaying transaction with wallet RPC

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#5107]
Steps to reproduce:

1. Use wallet RPC to create a non-relayed transaction (e.g. invoke `transfer` with the `do_not_relay` flag)
2. Use wallet RPC `relay_tx` to relay the hex

Since accepting changes from master committed between 1/21 and 1/28, wallet RPC consistently returns “-4: Failed to commit tx” and the daemon logs “tx verification failed: invalid input”.

Environment: Mac OSX.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5122

**Comment by moneromooo-monero** [comment]
+resolved
