### ISSUE TITLE
add RPC method to validate address

### ISSUE THREAD

**Issue by vladyslavstartsev** [monero-project/monero#5138]
Can you please add method to validate public address is right by RPC call.
I mean all the the address that I will give the node should pass all the rules of address.
Similar to 
BTC http://chainquery.com/bitcoin-api/validateaddress
WAVES https://nodes.wavesplatform.com/api-docs/index.html#!/addresses/validate_2
NEO https://github.com/neo-project/docs/blob/master/en-us/node/cli/2.9.3/api/validateaddress.md

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5141

**Comment by moneromooo-monero** [comment]
+resolved
