### ISSUE TITLE
Monero Fork: Blocks are not mining for morethan 20 Hrs

### ISSUE THREAD

**Issue by niyas-beldex** [monero-project/monero#5142]
I have forked Monero V0.13.0.4 and changed the networkid and genesis tx. The Blockchain was running fine for a week, after that I have noticed that there were some serious delay in the block creation, sometimes it took 3hrs to mine a block. Day by day the time delay for block creation has increased and now its been more than 20hrs and the blocks are not mined yet.

Currently the blockchain is running on Monero v7, Below is the detailed info about the network.

Network Hashrate: 5.083 MH/s Pool Hashrate: 6.03 MH/s Difficulty: 609932199 Block Height: 10498

I have also noticed that the blocks created after the delayed time are created pretty quickly. The delay in block creation is happening once in a day.

Any help regarding this will be really helpful.

Thank you in Advance

**Comment by fluffypony** [comment]
This is a bug tracker not a scamcoin support helpline.
