### ISSUE TITLE
wallet rpc outgoing transfers always return subaddress index 0

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#5171]
Querying wallet rpc `get_transfers` with a subaddress index > 0 will return outgoing transfers, presumably from that subaddress, but their subaddresses are always indicated as 0.

This issue is to return the correct subaddress index for outgoing transfers.  Given that they are returned when querying with specific subaddress indices, this should be possible.

**Comment by moneromooo-monero** [comment]
That is because a transfer can be made with many subaddress indices as inputs.
In that case, there should be a list rather than a single number.

**Comment by moneromooo-monero** [comment]
There's also an address field. There could be an additional addresses field too to match. Not sure that's needed though, since I'm not even sure what address is doing here.

**Comment by moneromooo-monero** [comment]
+resolved
