### ISSUE TITLE
Trust Wallet + Monero to provide better privacy for the users!

### ISSUE THREAD

**Issue by vikmeup** [monero-project/monero#5189]
Hey @fluffypony, following up from the Twitter thread. It's quite funny, I met you once in las vegas back in 2017 at Defcon, since then I was heavily involved in improving current UX of crypto and bring more adoption on mobile. 

Last week we opened source [wallet-core](https://github.com/TrustWallet/wallet-core), which is a library that will support all the blockchains in the world and will be lightweight for anyone to use, it generates code for Swift, Java and Javascript, makes it easy to use for anyone to integrate any blockchain or build a wallet. 

We recently created an issue to integrate [Monero](https://github.com/TrustWallet/wallet-core/issues/21) and would like one of your engineers to help us move this forward, we very limited in terms of engineers ourselves, only 2 engineers to support this project and don't have much insight into Monero implementation and how to integrate it yet. Would you be able to delegate one engineer to make this happen? 

We have telegram group as well if you guys can join to discuss: https://t.me/walletcore

**Comment by moneromooo-monero** [comment]
If you have monero development related questions, you can ask in #monero-dev on Freenode. Any actual bug reports can be filed on github.

**Comment by fluffypony** [comment]
@vikmeup Monero is an open-source project, it doesn't have any engineers working for it that it can direct. Maybe what's best is for you to have a full write-up of exactly what you need from the development community, and then pitch it to them in #monero-dev on Freenode, as @moneromooo-monero suggest. In the meantime, closing this as it's not a but, but you're welcome to continue the conversation here.
