### ISSUE TITLE
Add CNv4 code generation for ARM

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#5209]
If someone familiar with ARM asm wanted to add JIT for ARM, is seems like a fairly simple task.

**Comment by nioroso-x3** [comment]
I could backport the JIT I shoehorned into XMRIG here, but it would be for PPC.

**Comment by moneromooo-monero** [comment]
If it's simple enough, why not.

**Comment by nioroso-x3** [comment]
Created pull request #5540

**Comment by moneromooo-monero** [comment]
That never got finished, and we're now on randomx anyway, so there's not much point in this anymore, closing.
