### ISSUE TITLE
v0.14.x branch is expected

### ISSUE THREAD

**Issue by zhongqiuwood** [monero-project/monero#5220]
We are to merge the new official v0.14.x code into our own repo by a pull merge requet. 
Can you cut a v0.14.x branch(not a tag)？

**Comment by moneromooo-monero** [comment]
This is release-v0.13, which is a branch.
Maybe an unfortunate naming, but 0.14.0.0 is very similar to 0.13.0.x so it was decided to use that branch.

**Comment by zhongqiuwood** [comment]
Thank you, @moneromooo-monero .

**Comment by fluffypony** [comment]
More info here: https://lists.getmonero.org/hyperkitty/list/monero-announce@lists.getmonero.org/thread/SJ4PSKTAPKUZBJQK6GXHFUV2E6YBBR63/

**Comment by gituser** [comment]
I'm sure there will be soon a new branch `remotes/origin/release-v0.14` same as the monero guys with earlier releases:
```
  remotes/origin/release-v0.11.0.0
  remotes/origin/release-v0.12
  remotes/origin/release-v0.13
```

Just give them some time.
