### ISSUE TITLE
`Illegal instruction: 4` on monero-wallet-cli run.

### ISSUE THREAD

**Issue by Domol** [monero-project/monero#5230]
Hey!
I just downloaded new command-line tools but I have problem running it. All I get as a response is:
`Illegal instruction: 4`
Mac OS: Mojave(10.14.1)
Monero CLI version: 0.14.0.0

**Comment by moneromooo-monero** [comment]
What architecture/processor (as detailed as you can get) ?

**Comment by selsta** [comment]
@Domol Do you have an anti-virus program running?

**Comment by TheCharlatan** [comment]
@Domol can you run monerod? Does it run with just  `-- help` as an argument?

**Comment by Domol** [comment]
Hey guy sorry for not responding. I started using Docker and linux release. Anyway the problem is gone with v0.14.0.2-release. 
If you still want some info let me know.
