### ISSUE TITLE
Problem with monero-wallet-cli.exe

### ISSUE THREAD

**Issue by angryFlo** [monero-project/monero#5233]
I'm using windows 10 x64. i downloaded the newest client and get the following error:

c:\...\monero-win-x86-v0.14.0.0> .\monero-wallet-cli.exe
2019-03-05 15:52:24.120 9516    ERROR   wallet.simplewallet     src/simplewallet/simplewallet.cpp:8196  Exception at [main], what=boost::filesystem::path codecvt to wstring: error

The Daemon synced the chain successfully.
What can i do to solve the problem ?

**Comment by moneromooo-monero** [comment]
What version were you using before that ?

**Comment by angryFlo** [comment]
I don't know exactly maybe version 11.0

**Comment by selsta** [comment]
Please try to use the latest version and comment if you continue to have issues, then I can reopen it.
