### ISSUE TITLE
Cannot compile monerod on MacOS 10.14.1

### ISSUE THREAD

**Issue by scrammy** [monero-project/monero#5234]
Installed all required dependancies (not the optional ones) and followed instructions such as they were documented and get 71% and always fails with a linker error (marked in bold):

[ 71%] Linking CXX executable cnv4-jit-tests
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
**ld: library not found for -lcrypto**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [tests/crypto/cnv4-jit-tests] Error 1
make[2]: *** [tests/crypto/CMakeFiles/cnv4-jit-tests.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release-all] Error 2

I checked and libsodium is installed and the most current version - is the crypto library something else?

Also tried to use the pre-compiled versions available and simply get an "illegal instruction: 4" message back (See issue #5230).  The previous version (v13) ran fine in this machine (Mac Pro 5,1  6-Core 3.33 GHz)

**Comment by moneromooo-monero** [comment]
It is openssl.

**Comment by scrammy** [comment]
openssl is installed (version 1.0.2q) via homebrew

**Comment by moneromooo-monero** [comment]
Not sure what's going on here. Previous programs linked, and that one test does not do anything with openssl...

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/monero/pull/5241

**Comment by moneromooo-monero** [comment]
+resolved
