### ISSUE TITLE
How to set testnet for CryptonightR

### ISSUE THREAD

**Issue by DinoStray** [monero-project/monero#5245]
I wanna test CryptonightR for v0.14.
How to run testnet config?
Now "getblocktemplate" return
"blocktemplate_blob": "0b0bb68c82e4053d50f89f7991db941a338a20a62ade1418b3c6c48dacc552edbc25cc0ff320210000000002f6aa4701ffbaaa47018b9297bdfbc701023781552f559a7cfcd6186a3b1b644d5812be7ffda77a0ea45c46ef5145e185432b01b2b4b77c4e6dbab45b0c2dd7d43d2bc0feea05768be30ef9c86ccd15b0badeef020800000000000000000000"

the major_version is 0b -> 11, But I wanna 0a -> 10 for 0.14

**Comment by moneromooo-monero** [comment]
The public testnet is already at v11, so using CNv4 (Cryptonight-R based). v10 was active for just one day, it's a technical double fork to ensure the txpool does not get wiped out on fork, but v11 is what you want for testing CNv4.

**Comment by moneromooo-monero** [comment]
As intended, not a bug.

+resolved
