### ISSUE TITLE
wtf  monero-gui transfer too long time

### ISSUE THREAD

**Issue by vae520283995** [monero-project/monero#5246]
Transfer page has been waiting 
show creating transaction
wtf

**Comment by T-MacFbMa** [comment]
Transfer page has been waiting
show creating transaction
wtf

I have the same problem!

**Comment by bentiancai629** [comment]
Transfer page has been waiting
show creating transaction
wtf

**Comment by T-MacFbMa** [comment]
> Transfer page has been waiting
> show creating transaction
> wtf

I have the same problem

**Comment by bentiancai629** [comment]
Transfer page has been waiting
show creating transaction
wtf

I have the same problem!

**Comment by roy500** [comment]
wtf !  me too ！I have the same problem

**Comment by moneromooo-monero** [comment]
Then file this on the GUI repo: https://github.com/monero-project/monero-core/issues

And no need to post many times about it.

+invalid

**Comment by zq2665213** [comment]
yeah, after update the version, i get this problem .  does anyone have a solution to resolve it?

**Comment by vae520283995** [comment]
> Then file this on the GUI repo: https://github.com/monero-project/monero-core/issues
> 
> And no need to post many times about it.
> 
> +invalid

@moneromooo-monero Not only gui , moneor-wallet-rpc The same is true. And after each transfer, you have to wait until the transfer is confirmed
