### ISSUE TITLE
Test fails: notify.works

### ISSUE THREAD

**Issue by vicsn** [monero-project/monero#5261]
The notify test fails for me. You can invoke it via: `./tests/unit_tests/unit_tests --gtest_filter=notify.works`

It looks like I need to add an executable file `[build_folder]/tests/unit_tests/test_notifier` which should then point to the given temporary file `name_template`. Do you have a template for the test_notifier, and could this be placed in e.g. `monero/tests/unit_tests` to ensure people have access to it?

**Comment by moneromooo-monero** [comment]
Which platform, and what commit hash ?

**Comment by vicsn** [comment]
Platform: Ubuntu 18.0.4.2, 64 bit, Intel i7
Commit hash: `49afbd0c53d29656689f319c7d3543204ead4e59`

**Comment by moneromooo-monero** [comment]
How did you build it ?
What is the output of: find build -name test_notifier

**Comment by vicsn** [comment]
Brilliant, I should've seen the test_notifier executable earlier in CMakelists.txt 

I assumed it was a shell script and was taking a shortcut by building using `make -jx unit_tests`, which caused the test_notifier not to be built.
