### ISSUE TITLE
'transfer' RPC question

### ISSUE THREAD

**Issue by Crypto2** [monero-project/monero#5265]
In the transfer RPC call, it says subaddr_indices defaults to 0, does this mean it is only going to spend from the one single index 0 address, or will it spend randomly from all subaddresses? (The latter would definitely be preferred and/or have an option to do so since subaddresses are being pushed so hard in lieu of payment IDs/integrated addresses.)

**Comment by moneromooo-monero** [comment]
subaddr_indices does not default to 0. It defaults to empty, in which case all subaddresses within the account are considered. Please send a patch to those docs :)

**Comment by el00ruobuob** [comment]
My bad. I create a PR right away to correct it on the dev-guides.

**Comment by el00ruobuob** [comment]
PRd in https://repo.getmonero.org/monero-project/monero-site/merge_requests/1013

Sorry for this misunderstanding.

**Comment by Crypto2** [comment]
No worries, thanks for the clarification :)
