### ISSUE TITLE
Wallet GUI stucks on Block 1788047 but it says "synchronized". Last scheduled hard fork time shows a daemon update is needed soon.

### ISSUE THREAD

**Issue by kinza1509** [monero-project/monero#5268]
Wallet GUI stucks on Block 1788047 but it says "synchronized". Last scheduled hard fork time shows a daemon update is needed soon.
What should i do?

**Comment by moneromooo-monero** [comment]
Are you running 0.14.0.x ? If you're running a 0.13.x.y series, you need to update, 0.13 is too old and will not be able to follow the network.

**Comment by kinza1509** [comment]
How do i get 0.14.0? I downloaded the latest version one week ago on the monero Page. 
But if i download it now in getmonero.org, then i get also the 0.13.0 folder.?

**Comment by kinza1509** [comment]
What can i do? And how can i do this?

**Comment by el00ruobuob** [comment]
Your browser may had caching issue as the 0.14 has been on the website for more than a week. Go to the release tab on this repository to download the latest 0.14.0.2. After you start it, it will resync correctly and you'll be fine.

**Comment by mmbyday** [comment]
@kinza1509 https://www.reddit.com/r/Monero/comments/ayshug/gui_v01400_boron_butterfly_released/

**Comment by dEBRUYNE-1** [comment]
@kinza1509 - Upgrading to GUI v0.14.0.0 should solve your issue. Please take notice of the following though:

>This version, if using your own (local) node, requires a database conversion, which may take 5-10 minutes and the GUI will show that it's Disconnected (or unable to connect) from the daemon (monerod). I'd advise to simply let it run and after the database conversion has completed the GUI will connect back to the daemon (monerod).
