### ISSUE TITLE
Very low hashrate in CLI/GUI miner

### ISSUE THREAD

**Issue by JustFranz** [monero-project/monero#5278]
OS: Win 10
CPU 3770K stock clocks. It is a 4c 8t cpu with 8 MB cache.

1 thread - 11-14 H/s mostly stable at 14
2 threads 21-28 H/s mostly stable at 27-28
3 threads 32-41 H/s seems to be mostly at 38-39, but unstable
4 threads 37-44 H/s unstable in that range, mostly around 38-40 H/s, sometimes dips into mid and low 30s

With XMRig I get ~65 H/s per thread for a total of 260 H/s. There is no instability and hashes do not go down as I use more threads.

**Comment by moneromooo-monero** [comment]
Pool miners work a lot of speed, so they'll likely always be faster.

You can try these too:

#5252 
https://github.com/moneromooo-monero/bitmonero/commits/minerad2

The first one will speed up a bit. The second one might, let me know whether it does.
Also make sure you have the env var MONERO_USE_CNV4_JIT set to 1.
The second patch has a "auto" setting for number of threads, ie:
start_mining ADDRESS auto
It will try to find the best number of mining threads.

**Comment by JustFranz** [comment]
Using MONERO_USE_CNV4_JIT = 1 improved it

1 thread 28-31 H/s seems to be mostly stable at 29-30 H/s
2 threads 54-58 H/s mostly at 57-58 H/s
3 threads 83-90 H/s unstable in that range with dips into low 70s
4 threads 99-107 H/s stableish in the 100-104 range with some dips into mid 90s and mid 80s
5 threads 87-92 H/s with dips into mid 70s
6 threads 80-87 H/s stableish at 86-87 H/s, saw dips to 30, mid 50s and 0 (flukes?) otherwise stableish
7 threads 84-88 H/s very stable 
8 threads 89-91 H/s very stable

The GUI detects the optimal threads correctly at 4, so this is not needed https://github.com/moneromooo-monero/bitmonero/commit/8298f42e9d9c4d81792d7ab344efbe424e9b9ba2

The stabilization as more cores/threads are loaded would indicate some scheduler/core pinning issue? So this should help? https://github.com/moneromooo-monero/bitmonero/commit/25eea61a030bc08f7e1d4b26349c01cde5ce3841

Or the individual threads bouncing around averages out the displayed H/s? I don't know.

I did not try #5252 or the 2 other changes, unless there is a binary with the changes implemented? I'd like to try it out to get to the bottom of this.

Why isn't MONERO_USE_CNV4_JIT = 1 set automatically? Manually adding environment variables that you need to find on the internet is so user unfriendly.

**Comment by moneromooo-monero** [comment]
It's not default because it might be buggy.

**Comment by JustFranz** [comment]
XMRig 15 minute test
1 thread 77 H/s
2 threads 2x78 H/s
3 threads 3x 77 H/s
4 threads 4 x 65 H/s (3x77 = 231 4x65=260)

I'll edit post with 5 6 7 and 8 thread results

**Comment by moneromooo-monero** [comment]
The difference used to be nowhere that large IIRC.

You want the option to mine with monerod, otherwise you're not really strengthening the network, the pool op is deciding whether you do.

Given the large gap in performance, it's worth looking at speeding it up I think.

**Comment by moneromooo-monero** [comment]
Given we now use randomx, I'm going to close this. Reopen a new bug if you still have large performance gaps using randomx (say, 10%), which should not be the case.
