### ISSUE TITLE
[CLI] Can't transfer from cli with payment_id on v0.14.0.2

### ISSUE THREAD

**Issue by gituser** [monero-project/monero#5279]
Hi. 

When trying to make a transfer on `v0.14.0.2` with payment_id (16 hex symbols) cli errors:

```
transfer xxx 0.5 1234567890abcdef
Wallet password:                                                                                                                                                                                           
Error: Invalid last argument: 1234567890abcdef
```

Same transfer via JSON-RPC perfectly works.

**Comment by gituser** [comment]
Ping @moneromooo-monero 

This is quite urgent because many users are using CLI instead of GUI to transfer monero.

**Comment by moneromooo-monero** [comment]
This is not a valid payment id here. It was previously possible to send with a short payment id, but this was a bad idea. Short payment ids are embedded inside an integrated address, and are not meant to be used "free". I'll fix the RPC to disable those too.

**Comment by moneromooo-monero** [comment]
And... is there an exchange actually asking for a freeform short payment id ? Which one ?

**Comment by gituser** [comment]
What do you mean not valid payment_id?
Well I can provide you with a valid payment_id (which was generated via monero-wallet-rpc) but it doesn't work either.

Here is an example:
```
[wallet yyy] integrated_address
Random payment ID: <4f8dd5f06b0cb492>                                                                                                                                                                      
Matching integrated address: xxx
```

Now transfer:
```
[wallet yyy]: transfer xxx 0.5 4f8dd5f06b0cb492
Wallet password:                                                                                                                                                                                           
Error: Invalid last argument: 4f8dd5f06b0cb492
```

**Comment by gituser** [comment]
>And... is there an exchange actually asking for a freeform short payment id ? Which one ?

Yes, there is and I'm sure there are still many exchanges relying on payment_ids instead of subaddresses as the transition is not that easy and well documented with examples in all programming languages.

**Comment by moneromooo-monero** [comment]
It's not a valid free form payment id. They should be 32 byte (64 hexadecimal characters). The command you posted clearly gives you an integrated address for that random short payment id. If a recipient gives you just the short payment id, ask them for the actual integrated address.

**Comment by gituser** [comment]
So, to re-iterate now:
1. 16 byte (32 hexadecimal characters) payment_id is only valid for integrated address
2. 32 byte (64 hexadecimal characters) payment_id is only a valid payment_id if used with the regular address combination
3. Default GUI and CLI only accept integrated address as of `v0.14.0.2`
4. If you tick in the GUI an option `use OBSOLETE payment_id` it will work again and display a field for sending transactions with payment_id
5. Is there any option for CLI to make the same behavior of transfer command?

**Comment by moneromooo-monero** [comment]
8 byte (16 hex) are only valid when inside an integrated address. Those still work fine.
32 byte ones are obsolete, and can be used freeform.
32 byte ones can only be used to send if --long-payment-id-support in the CLI, and I think the GUI has a check box for this.
--long-payment-id-support

**Comment by gituser** [comment]
Thank you!

**Comment by gituser** [comment]
There are multiple issues with the new monerod `v0.14.1.2`:

* i can't send anymore transactions with payment_id 8 byte (16 hex) - and there is no option to make it possible to send such
* there is no option for `monero-wallet-rpc` `--long-payment-id-support` to send 32 byte (64 hex) payment_id transactions, the only option i can see there is for `monero-wallet-cli`

**Comment by moneromooo-monero** [comment]
As I said above, standalone payment IDs are 256 bit (32 bytes), not 8/16. Fixed size. Or do you mean you can't send to an integrated address ? I *assume* that when you saud monerod you mean the monero wallet, not monerod. If you really meant monerod, please confirm.

As for monero-wallet-rpc, AFAICT it does not need a --long-payment-id-support flag currently, as those are enabled by default. If something is not working there, please be specific.

**Comment by gituser** [comment]
@moneromooo-monero every integrated address have a usual address + payment_id (16 hex).

So if we split the integrated address into the standard address + payment_id we are not able to send a transaction - getting an error.

If we use integrated address instead - it works.

It's just that sometimes users specify standard address + payment_id instead of the integrated address.

**Comment by moneromooo-monero** [comment]
Yes, that is all correct, except that for "sometimes users specify standard address + payment_id instead of the integrated address" those users are doing wrong.

**Comment by moneromooo-monero** [comment]
Everything is as expected AFAICT. Using 8 byte payment ids manually was an unfortunate misfeature which was corrected. I'll close this soon unless you can point to something that's actually a bug.

**Comment by gituser** [comment]
@moneromooo-monero ok, closing this one, thanks for the clarification once again.

**Comment by gituser** [comment]
Hi @moneromooo-monero 

I have the issue with v0.15.0.0:

When I try to transfer to regular Monero address + 32 byte (64 hex or 256 bit) payment_id I get this error:

```
'result' => 
  array (
    'code' => -5,
    'message' => 'Standalone payment IDs are obsolete. Use subaddresses or integrated addresses instead',
  ),
```

I do not see `--long-payment-id-support` in `monero-wallet-rpc` binary and before the upgrade it did work just fine. 

Can you fix this or add this option as many of our users still send to exchanges which require regular monero address + 32 byte (256 bit) payment_id (64 hex)

**Comment by moneromooo-monero** [comment]
There's no command line support option anymore. This will not be added again. It would defeat the purpose of tiered obsoletion. People should migrate when it *starts* being deprecated, not after it is eventually removed. Those users can send to themselves or somewhere which does not require plaintext payment ids,

**Comment by dEBRUYNE-1** [comment]
@gituser - It has been known for quite some time that long payment IDs would be phased out this year (basically with the upcoming scheduled network upgrade of November 30). See:

https://web.getmonero.org/2019/06/04/Long-Payment-ID-Deprecation.html

**Comment by gituser** [comment]
@moneromooo-monero it seems to me that it's too early that you closed this function.

Many exchanges are still relying on payment_id, why not make additional option until everyone migrates to the integrated address / subaddress? 

It's not a default option just an optional for those who still rely on payment_id's.

@dEBRUYNE-1 I know about that I'm just saying that right now it's too early to cut this ability off completely as top players didn't migrate yet.

**Comment by hyc** [comment]
> it seems to me that it's too early that you closed this function.

Exchanges have literally had over 5 months to migrate. You should be complaining to your exchanges that they've waited so long to migrate, this is all their responsibility to fix.

**Comment by gituser** [comment]
@hyx I understand your position, but the reality is: exchanges are very slow to implement such changes, e.g. Binance still requires payment_id for the address. 

And many users won't be able to transfer with this new monero version.

For those who are having this issue and want to quickly fix it here is a patch I made (based on the other commit by @moneromooo-monero):

https://gist.github.com/gituser/28610a676df7bf7a8a2c2610f94da0c4

**Comment by selsta** [comment]
Binance confirmed that they will upgrade before November 30.

**Comment by gituser** [comment]
@selsta the reason that we've updated earlier in order to test the new monero version and not to miss the network upgrade and got this issue.

Thanks for the info regarding Binance.

**Comment by xiphon** [comment]
> Exchanges have literally had over 5 months to migrate

Even more, they actually have had 9 months to migrate.
Long payment ids are marked obsolete since [Boron Butterfly v0.14.0.0 release 25 Feb 2019](https://github.com/monero-project/monero/releases/tag/v0.14.0.0).

**Comment by moneromooo-monero** [comment]
What exchange are you running, so we know which one is actively trying to prevent privacy improvements from being adopted in monero by making patches meant to counter them ?

**Comment by gituser** [comment]
@moneromooo-monero  you probably misunderstood me.

We're runnning not exchange but instant exchange service. And from the start we've integrated monero without payment_ids (when nobody knew about this feature). The issue is only for users who are exchanging through us to withdraw to 3rd party exchanges which are not supporting yet integrated addresses but requiring payment_id.

It's not my call to stall the upgrade, it's our users demand. Hopefully after November 30 everyone will upgrade and we will remove payment_id support on our exchange form as we don't like it either.

Thank you.

**Comment by gituser** [comment]
I'll close the issue as there is a workaround for now for some time until everyone will be supporting payment_id's.
