### ISSUE TITLE
Can not start monero-wallet-rpc (boost::bad_any_cast: failed conversion using boost::any_cast)

### ISSUE THREAD

**Issue by cearsmehul** [monero-project/monero#5293]
Can not start **monero-wallet-rpc** using command

I tried bellow command to connect but it return error
`./monero-wallet-rpc --wallet-file=test --password=test --rpc-bind-port=18083  --disable-rpc-login`

error is :
`ERROR   wallet.rpc      src/wallet/wallet_rpc_server.cpp:4069   Exception at [main], what=boost::bad_any_cast: failed conversion using boost::any_cast`

Please help me as soon as possible.

**Comment by dEBRUYNE-1** [comment]
Can you rename the wallet cache (the file without extension) from `<wallet-name>` to `<wallet-name>-old` and retry?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5280

**Comment by cearsmehul** [comment]
@dEBRUYNE-1 it's not working.
This screen shot of after creating new wallet.
![image](https://user-images.githubusercontent.com/45064429/54429419-7c49b980-4746-11e9-8229-4703b9c55e9f.png)

This screen shot of 2nd try after change wallet file, As you say @dEBRUYNE-1
![image](https://user-images.githubusercontent.com/45064429/54429455-a1d6c300-4746-11e9-9ac0-02cf5e9bf467.png)

**Comment by dEBRUYNE-1** [comment]
@cearsmehul - Please see moneromooo's comment (i.e. recompile with #5280 included).

**Comment by cearsmehul** [comment]
Thanks a lot guys, 
For helping me.
