### ISSUE TITLE
'error.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by mariodian** [monero-project/monero#5296]
Hey! Trying to build the master on Mac (for Trezor support) and it gives me the following error:

```
Building CXX object src/common/CMakeFiles/obj_common.dir/timings.cc.o
/Users/mariodian/Source/Monero/monero/src/common/timings.cc:2:10: error: 'error.h' file not found with <angled> include; use "quotes" instead
#include <error.h>
         ^~~~~~~~~
         "error.h"
1 error generated.
make[3]: *** [src/common/CMakeFiles/obj_common.dir/timings.cc.o] Error 1
make[2]: *** [src/common/CMakeFiles/obj_common.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release-all] Error 2
```

When I change `#include <error.h>` to `#include "error.h"` in `src/common/CMakeFiles/obj_common.dir/timings.cc.` it compiles without errors.

I've been having this issue for quite some time now (can't be more specific sorry). 

Running MacOS 10.14.3 with Xcode 10.1

**Comment by moneromooo-monero** [comment]
It's not the right file though, you want #5249.

**Comment by mariodian** [comment]
Oh I see. Thanks!

**Comment by moneromooo-monero** [comment]
+resolved
