### ISSUE TITLE
Monero balance after full sync. says 0. 

### ISSUE THREAD

**Issue by kinza1509** [monero-project/monero#5300]
Hallo
My Balance at gui wallet is 0 after full sync. I am using the new Version 0.14.0
What can i do?

**Comment by kinza1509** [comment]
Can anyone Help me?

**Comment by dEBRUYNE-1** [comment]
Are you using the GUI in conjunction with a Ledger device? Also, have you looked at this guide?

https://monero.stackexchange.com/questions/6640/i-am-missing-not-seeing-a-transaction-to-in-the-gui-zero-balance

**Comment by kinza1509** [comment]
No no connection with the ledger. i did not find the problem, so i deleted all monero files.
Now i want to install the latest version and recover my wallet with my seed.
That should work or?
Can you tell me the latest version of gui wallet?
On getmonero.com there are 3 types of things i can download forwindows 64bit? i don´t know the difference and if it is the newest version?
Thx for answering :)

**Comment by dEBRUYNE-1** [comment]
>That should work or?

Yes. However, make sure to set a sensible `Restore height`

https://monero.stackexchange.com/questions/7581/what-is-the-relevance-of-the-restore-height

>Can you tell me the latest version of gui wallet?

The latest version of the GUI wallet is v0.14.0.0. 

>On getmonero.com there are 3 types of things i can download forwindows 64bit? 

If you want the GUI, you need `Windows, 64-bit` or `Windows, 64-bit Installer` 

> i don´t know the difference 

The first one is a portable version, whereas the second one is an installer. 

>and if it is the newest version?

Yes. To reiterate, most recent version for the *GUI* is v0.14.0.0.

**Comment by kinza1509** [comment]
So now i tried to recover my wallet with seed on a other computer also local note. The old transactions are here But the new ones are not here. And the Balance says 0. But i had also some monero bevor the new transactions? 
Also the Error come that There are 0 incoming connection on Port 18080. Can that be the reason that my Balance is 0 and the new transactions do not came in? Please Help.

**Comment by kinza1509** [comment]
Restore height i Set  at 01.01.2019.

**Comment by kinza1509** [comment]
So now i tried to recover my wallet with seed on a other computer also local note. The old transactions are here But the new ones are not here. And the Balance says 0. But i had also some monero bevor the new transactions?
Also the Error come that There are 0 incoming connection on Port 18080. Can that be the reason that my Balance is 0 and the new transactions do not came in? Restore height i Set 01.01.2019.
Please Help.

**Comment by dEBRUYNE-1** [comment]
>Also the Error come that There are 0 incoming connection on Port 18080

This is a warning which you can safely ignore, as it doesn't inhibit the daemon (monerod) from syncing properly. 

>Please Help.

Can you type `status` in `monerod` and post the output here?

**Comment by kinza1509** [comment]
Ok i thought that could be the reason that i have the new transactions not in my wallet.
Yes there is the post.
![Unbenannt](https://user-images.githubusercontent.com/48460347/54690585-036da780-4b22-11e9-86fb-b43897557c67.PNG)

**Comment by kinza1509** [comment]
Further i do not see any transactions in my wallet.

**Comment by dEBRUYNE-1** [comment]
Do you remember when you made the first transaction to this particular wallet?

**Comment by dEBRUYNE-1** [comment]
@kinza1509 - ping.

**Comment by dEBRUYNE-1** [comment]
Author has not responded. As such, I am going to close this.

**Comment by dEBRUYNE-1** [comment]
+resolved
