### ISSUE TITLE
Monero Gui Wallet Balance 0 no incoming connections

### ISSUE THREAD

**Issue by kinza1509** [monero-project/monero#5301]
Hello
My monero gui wallet shows balace 0 when i am fully synconized. Before it fully syncronize it shows my old balance. 
When i type in status it says: Height: 1792058/1792058 (100.0%) on mainnet, not mining, net hash 263.16 MH/s, v11, up to date, 8(out)+0(in) connections, uptime 0d 0h 1m 41s
this means no connections in.
What can i do?

**Comment by kinza1509** [comment]
Does anyone have an idea?

**Comment by dEBRUYNE-1** [comment]
Please only open one issue. Let's continue at #5300.

**Comment by dEBRUYNE-1** [comment]
+invalid
