### ISSUE TITLE
Transaction made with pre-fork xmr-cli on post-fork network

### ISSUE THREAD

**Issue by vprcs** [monero-project/monero#5312]
Hi, 

last week I totally forgot about Monero network upgrade and I have sent a transaction with xmr-cli v0.13.0.4 couple of days *after* the network switched. I can see the balance of the account being the same, however when i want to repeat the transaction or do anything with the account i get a "double spend error". Is there a way to recover the funds ? 

thanks !

**Comment by moneromooo-monero** [comment]
The tx might be in your daemon. flush_txpool, refresh, refresh, try again.

**Comment by vprcs** [comment]
Thanks for the quick reply. Should i do it with the new v0.14.0.2 client or with the old one ? Are you implying that the trasaction should go through even with the old client on a new network ?

**Comment by moneromooo-monero** [comment]
New one. If you sent with an old wallet and daemon, what probably happened is that your daemon accepted it. After you update, you need to tell your daemon to remove that tx. It might do that automatically, not sure. But if not, flush_txpool, and double refresh in the wallet. If your tx was not mined on the blockchain, you will be able to send your monero normally.

**Comment by dEBRUYNE-1** [comment]
You should be able to resolve your issue with this guide:

https://monero.stackexchange.com/questions/7993/i-forgot-to-upgrade-from-cli-or-gui-v0-13-to-cli-or-gui-v0-14-and-created-pe

**Comment by vprcs** [comment]
@moneromooo-monero thanks for advice. i will add that this only works when you operate on the same wallet files as when you created the tx. i had a earlier backup of the wallet (pre bad tx), to which i reverted and flush_pool wasnt working with it, i had to do it with the post-bad tx wallet. terminology lol. thanks anyway, here have some love <3 :100:

**Comment by vprcs** [comment]
@dEBRUYNE-1 yes, found it only after opening this issue. sorry :)

**Comment by moneromooo-monero** [comment]
flush_txpool, not flush_pool, and it's a daemon command, not wallet. The two refresh calls after that are wallet commands. It should have worked, if the above is kept in mind.

**Comment by dEBRUYNE-1** [comment]
@vprcs - No problem. To be clear, your issue is resolved now?

**Comment by dEBRUYNE-1** [comment]
I am going to close this, as the author has not responded for over a week. 

+resolved
