### ISSUE TITLE
clear screen command

### ISSUE THREAD

**Issue by maogo** [monero-project/monero#5315]
When print too much , how to clear ，
Like "CLS" command in DOS,  already exists or not?

**Comment by moneromooo-monero** [comment]
"clear" on bash/sh.

In monero tools themselves, no. But since it's multitasking nowadays, you can just run monerod in a shell and do other stuff in others. You can use the --log-level option if you want less logs too, though 
I think that's not really what you're asking.

**Comment by maogo** [comment]
Thank you reply，I mean the wallet not  daemon
