### ISSUE TITLE
BUG sign_transfer throws "failed to connect to deamon" when offline signing

### ISSUE THREAD

**Issue by dnaleor** [monero-project/monero#5368]
It's just a small annoyance, but when I recently (CLI 14.0.2) tried to sign a transaction offline, it failed and I got the message "failed to connect to deamon".

The workaround was starting monerod (even though it was unsynced) and then signing the raw transaction.

As far as I remember, this wasn't the behaviour of the CLI before.

**Comment by moneromooo-monero** [comment]
Fixed in 5277.

+duplicate
