### ISSUE TITLE
Failed to create a transaction for the db: Permission denied

### ISSUE THREAD

**Issue by moneroexamples** [monero-project/monero#5438]
Just found this issue in my projects, but now I see it also affects monero's blockchain utilities. 

For example, running `./monero-blockchain-export` produces the following error:

```
mdb/db_lmdb.cpp:75	Failed to create a transaction for the db: Permission denied
2019-04-14 06:12:07.065	    7fe3e4f38bc0	ERROR	bcutil	src/blockchain_utilities/blockchain_export.cpp:204	Exception at [Export error], what=Failed to create a transaction for the db: Permission denied
```

I think it has something to do that the blockchain is being opened in read only mode (DBF_RDONLY).

**Comment by moneromooo-monero** [comment]
I merged the fix in https://github.com/monero-project/monero/pull/5400

**Comment by moneroexamples** [comment]
Thanks! Its working. I will leave the issue open till the PR gets merged.

**Comment by moneromooo-monero** [comment]
+resolved
