### ISSUE TITLE
Add a monero-wallet-rpc method for getting users' latest transaction info

### ISSUE THREAD

**Issue by WooKeyWallet** [monero-project/monero#5468]
Hi, we are WooKey team, a dev team of Monero wallet. 
By now, to reduce the synchronization time of restoring a wallet, almost all wallets require their users to fill block height or date. However, the user experience in this way is not good.

Could you please provide a PRC method, which is possible to get the date or block height of the lastest transation at a given address. Even if it's not accurate to day, just accurate to month would be enough.

**Comment by moneromooo-monero** [comment]
Do you mean a wallet RPC, or a daemon RPC ?
If the former, call incoming_transfers, and check the block height field of the last entry you get.
If the latter, then no. The daemon has no access to your secret keys. You want mymonero instead.

**Comment by moneromooo-monero** [comment]
Actually the block height is in prevent in that RPC. https://github.com/monero-project/monero/pull/5470 adds it.

**Comment by WooKeyWallet** [comment]
> Actually the block height is in prevent in that RPC. #5470 adds it.

Thank you for that . We will continue to work on the wallet for monero.

**Comment by moneromooo-monero** [comment]
I'm not sure whether this is invalid or resolved :) I'll choose resolved.

+resolved
