### ISSUE TITLE
Different balance between rpc and cli wallet on stagenet

### ISSUE THREAD

**Issue by Lafudoci** [monero-project/monero#5475]
Using 0.13 branch `Monero 'Boron Butterfly' (v0.14.0.2-8039b8d9)`

CLI result:
```
Opened wallet: 54met3zKz82aisZhYYwKTPUJvCLfyDFuVRpcoM24DKabY2wfN63x1d5HWqr8QvzeY2a13ScJuVFQsbC5GgRBpTXfEEoPGgv
...
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 129335.775859628002, unlocked balance: 129072.841896183588
```

RPC result:
```
{
    'balance': 59255280680460286,
    'multisig_import_needed': False,
    'per_subaddress': [
    {
        'address': '54met3zKz82aisZhYYwKTPUJvCLfyDFuVRpcoM24DKabY2wfN63x1d5HWqr8QvzeY2a13ScJuVFQsbC5GgRBpTXfEEoPGgv',
        'address_index': 0,
        'balance': 59255280680460286,
        'label': 'Primary account',
        'num_unspent_outputs': 55,
        'unlocked_balance': 59255280680460286
    }],
    'unlocked_balance': 59255280680460286
}
```
When rpc says no unlock balance after spending, I can still spend on cli wallet. To me the cli seems more make sensible, it's stagenet mining wallet so there's lots outputs. But rpc often shows not enough outputs to spend. That's why I found this issue.

**Comment by moneromooo-monero** [comment]
Are you really sure the RPC wallet is up to date ?

**Comment by moneromooo-monero** [comment]
ie, call the refresh RPC on it to make sure.

**Comment by Lafudoci** [comment]
> ie, call the refresh RPC on it to make sure.
Here is the refresh result:
```
{'id': '0', 'jsonrpc': '2.0', 'result': {'blocks_fetched': 0, 'received_money': False}}
```

**Comment by moneromooo-monero** [comment]
Can you share the wallet keys and cache files ? Like upload to github ?

**Comment by Lafudoci** [comment]
> Can you share the wallet keys and cache files ? Like upload to github ?
I have try deleting cache file many times, but no effect. I'll provide the rpc and cli files and maybe PM you the password by IRC?

**Comment by moneromooo-monero** [comment]
Can you also send me the RPC request ?

**Comment by Lafudoci** [comment]
> Can you also send me the RPC request ?

https://github.com/Lafudoci/hexo-xmrtw/tree/gh-pages/other/issue5475
Are these what you need?

**Comment by moneromooo-monero** [comment]
I meant the JSON you sent to get the result above.

**Comment by moneromooo-monero** [comment]
Nevermind, looks like it's all there, thanks.

**Comment by moneromooo-monero** [comment]
The wallet you use for RPC is set to refresh-type=no-coinbase, so it's not seeing incoming coinbase.

**Comment by Lafudoci** [comment]
> The wallet you use for RPC is set to refresh-type=no-coinbase, so it's not seeing incoming coinbase.

Oh, I remenber it's for the exchange vulnerability event. So should recover it now? It seems the bug has been patched in 0.14? But I don't know if it's also in the v0.13 branch? Didn't expect this setting has bad effect on rpc.

**Comment by moneromooo-monero** [comment]
It's fixed in 0.14.0.2. The fix has the same effects in rpc and non rpc.

**Comment by Lafudoci** [comment]
I simply change the rpc's key with cli one, re-sync the cache. It seems resolved now. But I don't know if this issue is expected behavior. If it is, this issue could be closed, thank you.
```
{
    'id': '0',
    'jsonrpc': '2.0',
    'result':
    {
        'balance': 129335775859628002,
        'multisig_import_needed': False,
        'per_subaddress': [
        {
            'address': '54met3zKz82aisZhYYwKTPUJvCLfyDFuVRpcoM24DKabY2wfN63x1d5HWqr8QvzeY2a13ScJuVFQsbC5GgRBpTXfEEoPGgv',
            'address_index': 0,
            'balance': 129335775859628002,
            'label': 'Primary account',
            'num_unspent_outputs': 3414,
            'unlocked_balance': 129335775859628002
        }],
        'unlocked_balance': 129335775859628002
    }
}
```

**Comment by moneromooo-monero** [comment]
Well, you told it to ignore coinbase transactions, so it ignored them. It's expected.

+invalid
