### ISSUE TITLE
invalid payment id

### ISSUE THREAD

**Issue by randy86** [monero-project/monero#5517]
how to generate 64 char payment id, i've already using 
**openssl rand -hex 32**
and generate this
curl -X POST http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"make_integrated_address","params":{"payment_id":"a2ad26b5fa357de021b05a01309004575e2c4da9dfee97f08b267aa8cf391c2d"}}' -H 'Content-Type: application/json'

but result still Invalid Payment ID

**Comment by pallas1** [comment]
64 bits, not 32 bytes.

**Comment by moneromooo-monero** [comment]
Needs to be 8 bytes (16 hex chars).

+invalid
