### ISSUE TITLE
encrypted_seed passwords do not match

### ISSUE THREAD

**Issue by selsta** [monero-project/monero#5520]
```
[wallet 59aZUL]: encrypted_seed
Wallet password: 
Enter optional seed offset passphrase, empty to see raw seed: 
Confirm password: 
Passwords do not match! Please try again.
```
I can’t get this to work. If I understand it correctly, I enter my password first, then enter my seed offset (that I can choose freely) and then I enter my password again. I always get “Passwords do not match”. The only way I can get this to work is if I enter my password as seed offset passphrase.

**Comment by moneromooo-monero** [comment]
If I understand what you said, you entered X Y X instead of Y X X ?
It wants you to confirm the *new* encryption password, not the one from two steps before.

**Comment by selsta** [comment]
I totally misunderstood this, I thought it was asking for my wallet password. Thanks for clarifying.
