### ISSUE TITLE
"output received" message pops up over and over, refresh has no effect

### ISSUE THREAD

**Issue by aStableTripod** [monero-project/monero#5533]
There seems to be a difference between the mechanism that makes the message pop up (which seems to include mempool txs) and the refresh command (which seems to not include them).

When you receive new outputs from a tx, you get the following message in the CLI wallet:

> Password needed (output received) - use the refresh command

If the tx is still in the mempool, "refresh" does nothing and the message pops up again and again, until it is included in a block, at which point it works as intended.

So either the message should not be displayed for mempool txs, or refresh should include mempool txs. Otherwise this behaviour makes it seem like the wallet is not working correctly, confusing people.

**Comment by moneromooo-monero** [comment]
Did you try this with current master ? AFAIK this is fixed.

**Comment by aStableTripod** [comment]
You're right, this is fixed in master, my bad for not testing that in the first place.
