### ISSUE TITLE
exception when signing offline transactions

### ISSUE THREAD

**Issue by JustHereToHelp** [monero-project/monero#5537]
I have no idea what's going on.

I'm on 14.0.0.2, and this worked the last time I did it back in November

ERROR	wallet.wallet2	src/wallet/wallet2.cpp:571	*status != CORE_RPC_STATUS_OK. THROW EXCEPTION: tools::error::wallet_generic_rpc_error

**Comment by moneromooo-monero** [comment]
This is because you're not running a daemon on that machine. You should not have to, but this is a bug in 0.14.0.2, which is fixed in master (there will be a release soon including the fix).

**Comment by moneromooo-monero** [comment]
+resolved
