### ISSUE TITLE
size in blob 6048 not have not zero modulo for sizeof(value_type) = 30

### ISSUE THREAD

**Issue by myaeon-ru** [monero-project/monero#5579]
./monerod --version
Monero 'Boron Butterfly' (v0.14.1.0-7973fb6a)

2019-05-28 12:20:55.475	[P2P1]	INFO	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1364	Synced 1844517/1844517
2019-05-28 12:20:55.475	[P2P1]	INFO	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:2021	SYNCHRONIZED OK
**2019-05-28 12:22:02.678	[P2P6]	ERROR	default	contrib/epee/include/serialization/keyvalue_serialization_overloads.h:164	size in blob 6048 not have not zero modulo for sizeof(value_type) = 30, type N8nodetool19peerlist_entry_baseINS_19network_address_oldEEE**

Is this error? And what actual release of monero at now moment should be used?! if last release was
Latest release
 v0.14.0.2
 6cadbdc
Boron Butterfly, Minor Point Release 0.2
@fluffypony fluffypony released this on 8 Mar · 1501 commits to master since this release

**Comment by moneromooo-monero** [comment]
This error can be ignored. You can't talk with another peer, there was a comms change which did not keep backward compat here. This will go away once all/most nodes have updated.
You are using the right version.

**Comment by moneromooo-monero** [comment]
Innocuous.
