### ISSUE TITLE
Help ! One year mining lost...

### ISSUE THREAD

**Issue by fred62mail** [monero-project/monero#5599]
Hi,

I made a transfert from mymonero wallet to Coinomi wallet.
The tranfert done and accepted on mymonero but  2 transferts received in Coinomi and "unprocessed".......

The tranfert seems to be block....
My two wallets are empty ;-(

Help please !!!
![Tranfert Mymonero Coinomi 1](https://user-images.githubusercontent.com/42404798/58757766-29e09380-8512-11e9-84a9-afc59696768e.jpg)
![Tranfert Mymonero Coinomi 2](https://user-images.githubusercontent.com/42404798/58757767-2ea54780-8512-11e9-9f89-fde57abfde0f.jpg)

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help desk. Try #monero on Freenode or reddit.

+invalid
