### ISSUE TITLE
Monroe handles raw transactions too slowly

### ISSUE THREAD

**Issue by gzlkylin** [monero-project/monero#5604]
Why is the max number of threads in tools::threadpool always 0? 
The m_incoming_tx_lock critical section is too large, causing on_send_raw_tx rpc to be a serial processing transaction.
How to modify the code to deal with raw transaction quickly?

**Comment by moneromooo-monero** [comment]
What platform (precisely), and what version of boost ?
Are you sending lots of transactions at once ?

**Comment by gzlkylin** [comment]
my first question 
monero\src\common\threadpool.h
`namespace tools
{
//! A global thread pool
class threadpool
{
public:
  static threadpool& getInstance() {
    static threadpool instance;
    return instance;
  }
//...
  ~threadpool();

  private:
    threadpool(unsigned int max_threads = 0);
//...
};
}
`
You can see max_thread = 0 here，and can't be modified.

I send lots of transactions at once, and one node with some connection.
CentOS Linux 7

`Thread 21 (Thread 0x7ffadb520700 (LWP 12250)):
#0  0x00007ffb1e5ac51d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007ffb1e5a7e36 in _L_lock_870 () from /lib64/libpthread.so.0
#2  0x00007ffb1e5a7d2f in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00005562dda46ca4 in cryptonote::core::handle_incoming_txs() (...)
#4  0x00005562dda48698 in cryptonote::core::handle_incoming_tx(...)
#5  0x00005562dd8d7733 in cryptonote::core_rpc_server::on_send_raw_tx`
View thread information, blocked here.

**Comment by moneromooo-monero** [comment]
This is a misunderstanding. The max number of threads is not 0. It is what boost thinks your processor can do (number of cores).

About sending many txes, some of the work could be done without the tx lock, but it's more complex for a corner case, so I don't think I'm going to change that for now. Though if someone does the work and it's solid, we'll merge.

**Comment by gzlkylin** [comment]
Thanks reply
If I want to contribute code, which branch is best based？

**Comment by moneromooo-monero** [comment]
Please use master. Feel free to pop by #monero-dev if you have questions on that code.
