### ISSUE TITLE
[Question] How to use Monero over i2p

### ISSUE THREAD

**Issue by ghbjklhv** [monero-project/monero#5628]
**Question**: I read online that Monero can be used over i2p (source might be false).
This would provide obvious advantages. Are there any tutorials or projects pursuing this?

Source: https://en.wikipedia.org/wiki/I2P#Crypto-Currency

**Comment by moneromooo-monero** [comment]
Did you read https://github.com/monero-project/monero/blob/master/ANONYMITY_NETWORKS.md ? If so, please feel free to update it for clarity, etc.

Note that you need the current code from master for this to work, 0.14.0.2 is too old. There will (hopefully) be a release with the necessary code very soon.

**Comment by MaxXor** [comment]
@moneromooo-monero Will v0.14.1.0 work with I2P?

**Comment by moneromooo-monero** [comment]
Probably.

**Comment by jtgrassie** [comment]
> Will v0.14.1.0 work with I2P?

Yes it does. Use i2p-zero, create a socks tunnel (bound to a port like 4444) and a server tunnel (bound to port 18081). When starting your daemon, specify `--proxy i2p,127.0.0.1:4444`, `--anonymous-inbound your-server-tunnel.b32.i2p:18081,127.0.0.1:18081`. If you know any other peers running via i2p, you can also add them with `--add-peer some-other.b32.i2p:18081`. And read the docs.

**Comment by xanoni** [comment]
can be closed
