### ISSUE TITLE
src/cryptonote_core/blockchain.cpp

### ISSUE THREAD

**Issue by gzlkylin** [monero-project/monero#5630]
https://github.com/monero-project/monero/blob/fd0cf689ddb62c07fa9d86ca6e070860c51669cc/src/cryptonote_core/blockchain.cpp#L309

Before the output has been taken from the database, is it a bit redundant here?

**Comment by moneromooo-monero** [comment]
Why do you think it is redundant ?

**Comment by moneromooo-monero** [comment]
ping
