### ISSUE TITLE
Segfault when saying "No" to restoring from current estimated block height (possibly Trezor-related)

### ISSUE THREAD

**Issue by fullmetalScience** [monero-project/monero#5655]
Is this okay? (Y/Yes/N/No): N
    [1] 28951 segmentation fault (core dumped) monero-wallet-cli --log-file=`mktemp` --trusted-daemon --hw-device=Trezor

Stacktrace: [gdb_when_saying_No.txt](https://github.com/monero-project/monero/files/3294371/gdb_when_saying_No.txt)

**Comment by fullmetalScience** [comment]
Here's the backtrace from **after** applying [your patch](https://paste.debian.net/hidden/2a92b7c2/).

**Comment by moneromooo-monero** [comment]
What does it log though ? :)

**Comment by ph4r05** [comment]
Thanks for the report. The bug may manifest itself when using Trezor but from the log it seems the crash is triggered by `http_simple_client_template` by some response returned by the Trezor bridge. The bug may be in the http client code handling http responses.

**Comment by moneromooo-monero** [comment]
Same as https://github.com/monero-project/monero/issues/7784
