### ISSUE TITLE
How to custom integrate Monero with a DEX Exchange

### ISSUE THREAD

**Issue by DasMupp** [monero-project/monero#5657]
Hey,
I have a DEX Exchange, and its not possible to integrate Monero without custom integrate the functions. Is this tricky to do? Can you guide me please?

**Comment by moneromooo-monero** [comment]
This is a bug tracker, not a help desk. Try #monero on freenode, or reddit, or, for well delineated technical questions, monero.stackexchange.com. See also https://web.getmonero.org/resources/developer-guides/ for RPC doc (a bit out of date, but mostly good).

+invalid
