### ISSUE TITLE
why transaction type failed

### ISSUE THREAD

**Issue by vae520283995** [monero-project/monero#5667]
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "transfer": {
      "address": "469yWRhGbihfSBX3WwciNgEc3e8gVhJkpGFFYerFnSBgc4LCbiStL453FqzBH1KdxpePqXcEfkwRF6Ju4sbp1bvRHCT6KMD",
      "amount": 1592000000000,
      "confirmations": 1854648,
      "double_spend_seen": false,
      "fee": 32200000,
      "height": 0,
      "note": "",
      "payment_id": "d4ae08d4a13053b4f098759603dbff3c5dbb16e367f748d61234567890abeefe",
      "subaddr_index": {
        "major": 0,
        "minor": 0
      },
      "suggested_confirmations_threshold": 1,
      "timestamp": 1560565893,
      "txid": "24bf7964915b187c8e947b7cc02f634379125296549b502acedc0038a1846a1d",
      "type": "failed",
      "unlock_time": 0
    },
    "transfers": [{
      "address": "469yWRhGbihfSBX3WwciNgEc3e8gVhJkpGFFYerFnSBgc4LCbiStL453FqzBH1KdxpePqXcEfkwRF6Ju4sbp1bvRHCT6KMD",
      "amount": 1592000000000,
      "confirmations": 1854648,
      "double_spend_seen": false,
      "fee": 32200000,
      "height": 0,
      "note": "",
      "payment_id": "d4ae08d4a13053b4f098759603dbff3c5dbb16e367f748d61234567890abeefe",
      "subaddr_index": {
        "major": 0,
        "minor": 0
      },
      "suggested_confirmations_threshold": 1,
      "timestamp": 1560565893,
      "txid": "24bf7964915b187c8e947b7cc02f634379125296549b502acedc0038a1846a1d",
      "type": "failed",
      "unlock_time": 0
    }]
  }
}

why type failed?

**Comment by moneromooo-monero** [comment]
It means it was not mined and got dropped from the txpool. This can be due to double spend, wrong ring size, too low fee and nobody mined it, etc.

**Comment by vae520283995** [comment]
> It means it was not mined and got dropped from the txpool. This can be due to double spend, wrong ring size, too low fee and nobody mined it, etc.

thank you very much
