### ISSUE TITLE
blockchain export: Failed to create a transaction for the db: Permission denied

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#567]
My current blockchain_utilities.h

//define SOURCE_DB DB_MEMORY
#define SOURCE_DB DB_LMDB
// to use global compile-time setting (DB_MEMORY or DB_LMDB):
// #define SOURCE_DB BLOCKCHAIN_DB

I got this:

e5405@e5405-G31M-ES2L:~/bitmonero_20151226/bitmonero/build/release/bin$  ./blockchain_export --output-file 20151226_blockchain.raw  
2015-Dec-26 15:40:21.116600 Starting...  
2015-Dec-26 15:40:21.116702 Setting log level = 0  
2015-Dec-26 15:40:21.116783 Export output file: 20151226_blockchain.raw  
2015-Dec-26 15:40:21.116855 Initializing source blockchain (BlockchainDB)  
2015-Dec-26 15:40:21.116953 Loading blockchain from folder /home/e5405/.bitmonero/lmdb ...  
2015-Dec-26 15:40:21.177531 Failed to create a transaction for the db: Permission denied  
terminate called after throwing an instance of 'cryptonote::DB_ERROR'  
  what():  Failed to create a transaction for the db: Permission denied  
Aborted (core dumped)  
e5405@e5405-G31M-ES2L:~/bitmonero_20151226/bitmonero/build/release/bin$

troubleshooting attempts:

tried without flags, tried stopping the daemon and then performing. All fail.

**Comment by moneroexamples** [comment]
Seems to be working now.

**Comment by NanoAkron** [comment]
Hi @Gingeropolous and @moneroexamples - is this still an active issue or can it be closed?

**Comment by Gingeropolous** [comment]
I'm assuming fixed considering all the work done with the DB.
