### ISSUE TITLE
get_transfer_by_txid confusion

### ISSUE THREAD

**Issue by aaronovz1** [monero-project/monero#5671]
What would cause `get_transfer_by_txid` to return an object that has no `destinations` field? The `type` of the tx is `in`, and it was created as part of a multisig transaction. The top level `address` and `amount` fields are what I would expect to be in the destinations array.

**Comment by moneromooo-monero** [comment]
All in transfers have no destinations, since we don't know what they were as we did not send them (if we did them them, they're classed as an out tx).

**Comment by moneromooo-monero** [comment]
Not a bug for in txes. Reopen if you think it is, and give more information if so.

+invalid
