### ISSUE TITLE
Clarification on if  --prune-blockchain is required permanently

### ISSUE THREAD

**Issue by BKdilse** [monero-project/monero#5680]
Please clarify if the switch  `--prune-blockchain` is required on Daemon start up each time, after the database has already been pruned?

I've read that you must use the switch each time the monerd is restarted, else future blocks will not be pruned. I've also read else where, that it is a one time requirement.

Which is it please?

**Comment by moneromooo-monero** [comment]
It's a one time thing. Once pruned, it stays pruned as it syncs.

+invalid
