### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [monero-project/monero#5692]
I'm a little bit overwhelmed by the README.

## Expected

Some short intro, a "build from source", pointers to further information (manuals, user-resources, dev-resources, ...)

## Possible Solutions

Introduce a "docs" folder (with separate files per topic, for easier maintenance), or simply move most of the information as-is (flat) to a dedicated file outside of the README.

**Comment by moneroexamples** [comment]
I actually like everything is in one file. Its easier to search for specific information with plain `Ctrl+F` functionality in a browser.

**Comment by lazaridiscom** [comment]
Then possibly add the API docs to the README?

**Comment by lazaridiscom** [comment]
An example for the "Other Extreme": https://github.com/stellar/stellar-core/issues/2171
