### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [monero-project/monero#5693]

**Comment by SamsungGalaxyPlayer** [comment]
Better for meta? https://github.com/monero-project/meta/issues

**Comment by lazaridiscom** [comment]
Nah, I've the tendency to stick to the repo which causes me the problems.

**Comment by lazaridiscom** [comment]
(but github has a "issue move" feature nowadays, so the maintainers here can move it over anyways)

**Comment by lazaridiscom** [comment]
> Better for meta?

for this here ("(Additionally, the team should think about making a process in order to avoid ancient issues)"), meta it is!!!

**Comment by moneromooo-monero** [comment]
Age is no reason to close an issue. It should be closed if fixed, or if we decide not to do anything about it, or if mooted. The question you linked might be mooted, but it'd require checking.

That said, if you see anything that's either fixed or moot, feel free to comment on it saying so and it'll get closed.

Something that we might want to do is close N-1 bugs about "the DB is corrupted" to keep just one, linking to others as duplicates.

**Comment by lazaridiscom** [comment]
>That said, if you see anything that's either fixed or moot, feel free to comment on it saying so and it'll get closed.

this is far too much effort for a newcomer. The existent team must process the issues.

> Age is no reason to close an issue.

Please read with greater precision. "Revise/Triage" (and not close)

I try to contribute, and the first barrier are very old issues, where I'm not sure if they are actual or just kept open out of sloppiness.

Be aware that the current status of the issues-tracker makes a very unprofessional impression.
