### ISSUE TITLE
export_outputs should export all outputs

### ISSUE THREAD

**Issue by hokkjoy** [monero-project/monero#5716]
`export_outputs` only actually exports outputs that haven't been exported before, leading to an incomplete file.

When we try to use this file on a prestine wallet (`import_outputs <outputs_file>`), the command fails with the following error message:

`Error: Failed to import outputs outputs_file: Failed to import outputsImported outputs omit more outputs that we know of`

#5418 apparently solved this **for RPC**. However, for **CLI**, the issue remains.

I would also argue that exporting all outputs should be the *default* for CLI.

**Comment by moneromooo-monero** [comment]
The default should be incremental, since that's what most people will need. I'll add an option to export all.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5722

**Comment by hokkjoy** [comment]
> The default should be incremental, since that's what most people will need.

How come and how do you know?

**Comment by moneromooo-monero** [comment]
It takes a lot of time to duplicate that work for large wallets, and files get big.

**Comment by hokkjoy** [comment]
I suppose with "large" you refer to one with many tx's. My cold wallet is always freshly opened from seed in a live OS environment with no previous files available. That tends to be the safest way and is a sensible default for individual users (the majority). Exchanges (probably those with "large" wallets - the minority) will not have much trouble to find out that an optional `incremental` switch may make their live easier.

**Comment by dnaleor** [comment]
Tend to agree with hokkjoy here. If you see a command called "export_outputs" you would expect that all outputs are exported. I use a similar system for my cold storage, I always use a fresh clean OS and wallet.

**Comment by moneromooo-monero** [comment]
Any other opinions here ?

**Comment by moneromooo-monero** [comment]
After thinking about this, I think it may be best to change this as requested. Along with a message telling you whether the export was full or partial, so the user can redo if necessary.

**Comment by Adreik** [comment]
How does one export a particular owned output?

The help simply states "export_outputs [all] <filename>" is the usage.

For example, say I want to export an output associated with a specific pubkey?

**Comment by moneromooo-monero** [comment]
You can't.

**Comment by jonathancross** [comment]
Seems this can be closed now?

**Comment by jonathancross** [comment]
> After thinking about this, I think it may be best to change this as requested. Along with a message telling you whether the export was full or partial, so the user can redo if necessary.

@moneromooo-monero Sorry, I mistakingly thought this was already implemented (default to "all") based on your comment.
Personally I think this would be a very useful change and would avoid some confusing behavior for users.
Larger files for those who are too lazy to specify "incremental" seems like a fine tradeoff.
