### ISSUE TITLE
Release monero-linux-x64-v0.14.1.0.tar.bz2 == invalid bzip2 file (rather gzip)

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero#5730]
It seems the Linux cli v0.14.1.0 release has been compressed using gzip rather than bzip2:

```
$ curl https://downloads.getmonero.org/cli/monero-linux-x64-v0.14.1.0.tar.bz2 --output monero-linux-x64-v0.14.1.0.tar.bz2

$ openssl dgst -sha256 monero-linux-x64-v0.14.1.0.tar.bz2
SHA256(monero-linux-x64-v0.14.1.0.tar.bz2)= 2b95118f53d98d542a85f8732b84ba13b3cd20517ccb40332b0edd0ddf4f8c62

$ bunzip2 monero-linux-x64-v0.14.1.0.tar.bz2
bunzip2: monero-linux-x64-v0.14.1.0.tar.bz2 is not a bzip2 file.

$ file monero-linux-x64-v0.14.1.0.tar.bz2
monero-linux-x64-v0.14.1.0.tar.bz2: gzip compressed data, max compression, from Unix
```

**Note:** *gzip* rather than *bzip2* as in previous releases.

**Comment by moneromooo-monero** [comment]
Yes, it is known. I expect it'll change for next release. You can file it on the monero-site repo also since that's where those files live.

+invalid

**Comment by jonathancross** [comment]
Moved to: https://repo.getmonero.org/monero-project/monero-site/issues/964

**Comment by jonathancross** [comment]
Seems this needs to be fixed in the gitian yml files (eg [/contrib/gitian/gitian-linux.yml](https://github.com/monero-project/monero/blob/master/contrib/gitian/gitian-linux.yml)), so it might make more sense to have this open here?

**Comment by teran-mckinney** [comment]
I noticed this as well, caught me by surprise.

Nice change, not a big fan of bzip2. xz would make sense if you wanted better compression than gzip, though.
