### ISSUE TITLE
2 additional spaces added after passphrase is pasted from clipboard in dialogue

### ISSUE THREAD

**Issue by bosomt** [monero-project/monero#5736]
2 additional spaces added after passphrase is pasted from clipboard in dialogue
Please see screenshot.
If paste your passphrase wallet will add 2 more spaces.
This will generate completely different wallet/account/address compared to passphrase that you enter via keyboard 
![image](https://user-images.githubusercontent.com/31506317/60710846-dea41100-9f13-11e9-8725-c5028300249e.png)

![image](https://user-images.githubusercontent.com/31506317/60710708-9b49a280-9f13-11e9-96c5-a533297142d3.png)

**Comment by moneromooo-monero** [comment]
Please file on the GUI repo: https://github.com/monero-project/monero-gui

I assume you double checked you did not copy those spaces in the first place (if, if you paste into a text editor, you don't get the spaces) ? It might also be a newline, these should be filtered out I guess.

+invalid

**Comment by bosomt** [comment]
@moneromooo-monero sorry, i will open it there. No there is no space included and this problem is there since we started to test Trezor integration
