### ISSUE TITLE
Bug report: offline signing

### ISSUE THREAD

**Issue by dnaleor** [monero-project/monero#5741]
When trying to do offline signing, I get this error: 

> imported outputs omit more outputs than we know of

To be clear: I had a fully synced view wallet with all imported keyimages and created an unsigned transaction. Then I went to the offline PC, imported my seed and tried to sign this transaction.

This always worked in the past. Now it didn't.

Workaround: export outputs and import them to the cold wallet before trying to sign the transaction.

edit: viewwallet was on Linux 64bit system; cold wallet was on Rpi3 (Armv7)

**Comment by moneromooo-monero** [comment]
Does it work between armv7 and armv7, or between what I asume is x86_64 and x86_64 ?

**Comment by dnaleor** [comment]
issue wasn't really an issue. Combination of misunderstanding export_outputs, which data "piggybacked" with an unsigned_transaction and maybe a change in my cold signing routine. 

solved my issue, i'll close it.
