### ISSUE TITLE
make: *** [Makefile:88: cmake-release] Error 1

### ISSUE THREAD

**Issue by gamingwithrage** [monero-project/monero#5752]
I get this error when trying to "make release"

My cmake and make are both updated and everything I double checked. I can't find anything online to fix this error.

**Comment by moneromooo-monero** [comment]
Please paste the actual error before that, not just the ending boilerplate.

**Comment by gamingwithrage** [comment]
> Please paste the actual error before that, not just the ending boilerplate.

`See also /home/pi/monero/build/Linux/_HEAD_detached_at_v0.14.1.0_/release/CMakeFiles/CMakeOutput.log
See also /home/pi/monero/build/Linux/_HEAD_detached_at_v0.14.1.0_/release/CMakeFiles/CMakeError.log
make: *** [Makefile:88: cmake-release] Error 1`

**Comment by moneromooo-monero** [comment]
Paste the actual error. Look above. You might as well paste the entire thing since it appears to be failing in cmake so there shouldn't be too much.

**Comment by moneromooo-monero** [comment]
ping

**Comment by moneromooo-monero** [comment]
I'll close this in a few days unless I get the requested logs before then. You just pasted the "followup" messages, not the original error.

**Comment by moneromooo-monero** [comment]
Reopen if you can supply the log.

+invalid
