### ISSUE TITLE
Add possibility to activate language files before using them

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero#5753]
Right now if a language is added to `/translations` it gets automatically picked by the CLI. This is problematic because most of the time translators submit just a partial translation and if that gets automatically picked we would end up with a new language file containing a partial translation.

Would be better to be able to activate languages, so that even if they are commited to the repo (and uploaded in `/translations`) we can choose the right time to make them available in the wallet. This will give us more control over the language files and make the integration with Weblate not painful.

As discussed with @moneromooo-monero, probably the best approach is to create a list of languages in a file which can be activated when needed. Something similar to what we already do [with the GUI](https://github.com/monero-project/monero-gui/blob/master/lang/languages.xml).

**Comment by erciccione** [comment]
self-reminder: after this is resolved, commit unpushed translated strings of the unactivated languages from Pootle.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5757

**Comment by erciccione** [comment]
Resolved
