### ISSUE TITLE
Should I update to v0.14.1.0?

### ISSUE THREAD

**Issue by yanpl** [monero-project/monero#5758]
Is v0.14.1.0 a release version?
Where can I find a version change log?

thanks

**Comment by dEBRUYNE-1** [comment]
Yes, you can find the release thread here (with change log). Github should be updated later this week.

https://www.reddit.com/r/Monero/comments/c0w3cp/cli_v01410_boron_butterfly_released/

**Comment by dEBRUYNE-1** [comment]
+resolved
