### ISSUE TITLE
Where is the doc files about how to use the executable file.

### ISSUE THREAD

**Issue by ScottGold** [monero-project/monero#5759]
The monero-wallet-rpc need a wallet file, how to generate a wallet file?

**Comment by moneromooo-monero** [comment]
Either use monero-wallet-cli to create one (--help for the list of command line parameters, "help" while in monero-wallet-cli), or use monero-wallet-rpc (see the list of RPC in https://web.getmonero.org/resources/developer-guides/wallet-rpc.html).

**Comment by ScottGold** [comment]
Thanks for reply.
I'm confusing why monerod and monero-wallet-rpc both listening on the port 18082

**Comment by moneromooo-monero** [comment]
They should not listen on the same port. They indeed cannot. You connect to the daemon RPC if you want to call a daemon RPC, and to the wallet if you want to call a wallet RPC. Daemon RPC deal with the blockchain, wallet RPC deal with your keys.

**Comment by ScottGold** [comment]
Thanks.
