### ISSUE TITLE
Raspberry Pi 3 B+ ARMv8 build with NO_AES

### ISSUE THREAD

**Issue by Kryptoxic** [monero-project/monero#5782]
Hi, I have been having trouble with the armv8 prebuilt binaries so I decided to do some research and I ended up finding the following issue.

https://github.com/monero-project/monero/issues/2858

One of the solution that was mentioned in that particular issue is to build monero with NO_AES. I was just wondering, how do I run cmake with the NO_AES flag. I have tried "cmake NO_AES ." and it does not work. Thanks in advance!

**Comment by vtnerd** [comment]
Try `cmake -DNO_AES`.

**Comment by Kryptoxic** [comment]
It didn't work. After it compiled, I kept getting a core dumped. Either way, I switched back to using armv7 on my raspberry pi
