### ISSUE TITLE
Mining on Testnet seems to be broken

### ISSUE THREAD

**Issue by krtschmr** [monero-project/monero#5785]
1. sync daemon `--testnet`
2. create wallet with `--testnet` 

3. daemon: `start_mining ADDR` 
-> found several blocks, balance always 0

4. wallet-cli `start_mining` 
-> found several blocks, balance always 0

is this just me?

**Comment by dEBRUYNE-1** [comment]
Did you wait until the blocks matured (i.e. 60 blocks)?

**Comment by krtschmr** [comment]
absolutely. still no balance. it's >150 blocks

**Comment by trasherdk** [comment]
I'm mining on testnet, no problems.
```
Height 1268005, txid <3b983d6124bd427de4885d25e8d28cd137d59b181e2c9a4445ae90d81d04a0fb>, 10.803137894759, idx 0/0
Height 1268011, txid <4ceab180eba2fba9df322c5d84d4be44845482bffeadf1a1aa54ec6b712d73b3>, 5.401480538990, idx 0/0
Height 1268017, txid <781ec3a9ff63ee9f31c06cc42994420673cd5c262d0aef16bd173ce757408715>, 27.007114226205, idx 0/0
Height 1268024, txid <61a3da83ad669b58a813b75d8e560f843dce899a5a7a77ac6ae28db19ffac880>, 10.802724122744, idx 0/0
[wallet 9zwQfv]: balance        
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 17743.621771749103, unlocked balance: 17732.819047626359 (6 block(s) to unlock)
```
![image](https://user-images.githubusercontent.com/5003891/62291444-29bb3080-b48e-11e9-8ea1-d7788093937b.png)

**Comment by dEBRUYNE-1** [comment]
@krtschmr - Can you check what the wallet creation height is (use `set`)?

**Comment by krtschmr** [comment]
@dEBRUYNE-1 it's all from today in the morning. so 12 hours ago. 
i don't have access to it right now can tell you tomorrow morning (so in 12 hours)

**Comment by moneromooo-monero** [comment]
It's very likely your creation height is bogus as dEBRUYNE said.

**Comment by krtschmr** [comment]
yes. this was the same issue.
