### ISSUE TITLE
c++: internal compiler error: Killed (program cc1plus) - Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by lh1008** [monero-project/monero#5791]
Hi everyone, 

Building from source I get this error. Any help is really appreciated.

[ 78%] Built target daemon_rpc_server
[ 79%] Building CXX object src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
/home/raver/monero/src/wallet/wallet2.cpp: In member function ‘void tools::wallet2::get_outs(std::vector<std::vector<std::tuple<long unsigned int, crypto::public_key, rct::key> > >&, const std::vector<long unsigned int>&, size_t)’:
/home/raver/monero/src/wallet/wallet2.cpp:7729:12: warning: variable ‘existing_ring_found’ set but not used [-Wunused-but-set-variable]
       bool existing_ring_found = false;
            ^~~~~~~~~~~~~~~~~~~
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
src/wallet/CMakeFiles/obj_wallet.dir/build.make:62: recipe for target 'src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o' failed
make[2]: *** [src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o] Error 4
CMakeFiles/Makefile2:2401: recipe for target 'src/wallet/CMakeFiles/obj_wallet.dir/all' failed
make[1]: *** [src/wallet/CMakeFiles/obj_wallet.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

>:)

**Comment by lh1008** [comment]
I read the other related issues but there is no clear answer on how to solve this issue. It says is a memory problem but I have 2,8GB of RAM.

**Comment by lh1008** [comment]
Tried again and got this message:

ring_found’ set but not used [-Wunused-but-set-variable]
       bool existing_ring_found = false;
            ^~~~~~~~~~~~~~~~~~~
virtual memory exhausted: Cannot allocate memory
src/wallet/CMakeFiles/obj_wallet.dir/build.make:62: recipe for target 'src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o' failed
make[2]: *** [src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o] Error 1
CMakeFiles/Makefile2:2401: recipe for target 'src/wallet/CMakeFiles/obj_wallet.dir/all' failed
make[1]: *** [src/wallet/CMakeFiles/obj_wallet.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hyc** [comment]
Like it says, you're out of memory.

If you want to proceed, either install more RAM, or add about 2GB of swap space.

**Comment by hyc** [comment]
+invalid

**Comment by lh1008** [comment]
@hyc it worked. Learned something new today. Thank you very much :).

**Comment by WonderSimiliar** [comment]
there is more convenient option you should try:
$ catkin_make -j1
this command use single-thread compilation to avoid memory insufficiency caused by multiple threads.
