### ISSUE TITLE
Deployed to github-pages 

### ISSUE THREAD

**Issue by txchangecoin-project** [monero-project/monero#5792]
Its good to create an environment for monero README page by deploying it to github page, after deployment you have url of [https://monero-project.github.io/monero/](https://monero-project.github.io/monero/). You can view my example here [https://txchangecoin-project.github.io/txchangecoin/](https://txchangecoin-project.github.io/txchangecoin/).

**Comment by moneromooo-monero** [comment]
What are you asking or saying here ? Something's broken in how the README is displayed on github ?

**Comment by erciccione** [comment]
I think would be completely useless to deploy a github-page just for showing the readme. I don't see any value or reason to do it.

**Comment by moneromooo-monero** [comment]
So there doesn't seem to be any bug here, right ?

**Comment by erciccione** [comment]
Yeah, can be closed IMO.

**Comment by moneromooo-monero** [comment]
+invalid
