### ISSUE TITLE
Dear Developer monero can not Continuous transfer

### ISSUE THREAD

**Issue by vae520283995** [monero-project/monero#5795]
I am an exchange platform and need to integrate monero Wallet,When I transfer once, I have to wait for 10 confirmations to transfer the next one.
Can you help me

**Comment by thomasvaughan** [comment]
@vae520283995  There's a discussion on reddit that you may find helpful:
 [https://www.reddit.com/r/Monero/comments/bel9w1/question_regarding_locked_balance_per_transaction/](https://www.reddit.com/r/Monero/comments/bel9w1/question_regarding_locked_balance_per_transaction/)

**Comment by vae520283995** [comment]
> @vae520283995 There's a discussion on reddit that you may find helpful:
> https://www.reddit.com/r/Monero/comments/bel9w1/question_regarding_locked_balance_per_transaction/

thank you

**Comment by moneromooo-monero** [comment]
You can use min-outputs-* settings to avoid consolidating your outputs needlessly.
Values of, eg, 10 for count and 1 for value means the wallet will try to keep at least 10 outputs of value >= 1 monero. You only have to wait when you've spent the last of your outputs.
