### ISSUE TITLE
How Much Transaction will max return by get_transfer 

### ISSUE THREAD

**Issue by rajajwaliya** [monero-project/monero#5837]
hello i m using get_transfer rpc api. i want to know how much maximum transaction this api can return ??

**Comment by moneromooo-monero** [comment]
I assume you mean get_transfers. In that case, it's whatever number of transactions your wallet has for the categories you selected. Limited by memory I suppose.

**Comment by dEBRUYNE-1** [comment]
Answered here:

https://monero.stackexchange.com/questions/11564/whats-the-maximum-amount-of-transactions-returned-by-the-get-transfer-rpc-metho

**Comment by dEBRUYNE-1** [comment]
+resolved
