### ISSUE TITLE
Allow ringCT type 3 after V11 

### ISSUE THREAD

**Issue by jtomtan** [monero-project/monero#5845]
Hi,  I am from Ownbit Wallet team. 

I think ringCT type 3 should be allowed in V11 and later. We should always have the backward compatibility. If want the most TX upgrade to type4,  we can charge more fees for type 3. 

Now the existing JS implement for monero are only for type 3. It's difficult for all wallets upgrade to type 4 in short time. 

Bitcoin always have backward compatibility.  And I also recommend the Monero official team to provide a JS library for offline signing (with ringCT type 4)

**Comment by moneromooo-monero** [comment]
No good reason to, except cater for people who use custom code and don't update it. It's a fingerprinting vector, and adds unnecessary extra storage and verification time.

**Comment by jtomtan** [comment]
> No good reason to, except cater for people who use custom code and don't update it. It's a fingerprinting vector, and adds unnecessary extra storage and verification time.

Is there any document or guide to describe how to implement type4. I have JS code for type3. What  change should I do to make it become type 4? 

As I understand, type 3 is bulletproof v1 and type 4 is bulletproof v2 , right? What's the detailed difference between them? Any detailed code to show me the difference? Thanks very much.

**Comment by moneromooo-monero** [comment]
There are three changes, one of them trivial, and the others fairly simple:
cdc3ccec5fd7925d93babff8a9a421c538f3cce0
99d946e6191056f747225d36a2408085624b516e
7d375981584e5ddac4ea6ad8879e2211d465b79d

**Comment by jtomtan** [comment]
> There are three changes, one of them trivial, and the others fairly simple:
> [cdc3cce](https://github.com/monero-project/monero/commit/cdc3ccec5fd7925d93babff8a9a421c538f3cce0)
> [99d946e](https://github.com/monero-project/monero/commit/99d946e6191056f747225d36a2408085624b516e)
> [7d37598](https://github.com/monero-project/monero/commit/7d375981584e5ddac4ea6ad8879e2211d465b79d)

I tried to implement the changes bases on a JS codebase which can work for bulletproof(v1), but still get error message: verRctMGSimple failed for input 0 when send_raw_transaction. Code changes are as follows:

![monero1](https://user-images.githubusercontent.com/11899268/63649321-be077300-c76e-11e9-8501-6069004d89b1.jpeg)
![monero2](https://user-images.githubusercontent.com/11899268/63649323-c364bd80-c76e-11e9-9fe4-323d343d2498.jpeg)
![monero3](https://user-images.githubusercontent.com/11899268/63649325-c8297180-c76e-11e9-900e-c97a8d272a90.jpeg)
![monero4](https://user-images.githubusercontent.com/11899268/63649326-cb246200-c76e-11e9-9e7b-6fe0e3b2b0ee.jpeg)
![monero5](https://user-images.githubusercontent.com/11899268/63649328-ce1f5280-c76e-11e9-8815-507b46172dac.jpeg)
![monero6](https://user-images.githubusercontent.com/11899268/63649329-d11a4300-c76e-11e9-8990-990a231c5f5d.jpeg)
![monero7](https://user-images.githubusercontent.com/11899268/63649331-d4153380-c76e-11e9-8a36-11e6f4d04315.jpeg)

the generated Hex is: 

02000102000bf1eeae01f585d20191d242ca9e1986dc23fddf24ffe355a1df0efbb92da29a12de8c0e7a0a7dac7acc43a1b694ecac6c28feaf47ee061e8e2e9b0cd6edb85535f64af3020002979a666a15c05661c5d6e24d4f1243e2d5d1b5dc24073376a11f29387cf4561e0002a02a964eb72525612ade738254e4d6d4577fe2fd8f16d74405a561b326c4fd592101c3113724a748098de703642a74377599be0eac248a0a44bcd889e84458580b4204e0eef110875e6570b0fdd1644b867949096a982748231baff0a5aa795bb4d5ad4863302b16a1cf859204aefbb88bf17e31910a22d7edb9235deccf02dd75a556f1d594783888424779d9692ef01df424327590f2014d2201404a32ff903446202129dd180e82fe2a46ca3c5524fcf9e962059fa3f5dce71bde9b2e7a422b997167e19c4c98410b33d43931fabb46e03d4012b0f3528526e1619bb4692304a9bf9ba8e95c93fd7ea18e37b49b4b38aa2e007e7cc3e32a40cbf63c7a49b7ac2a7d79fddce9ab60f2c2c2b474233909a79b60a66c5af4d294a9f2236b90495e0e7e5aff57ab54c59dcbfe4169727af680c040a65bbe0de9baf9444b939d207a6134c3779ded3b5ead1be5b83b0989462c071aa45dfb0207e4becd9b7d5e8cbccf75d161dc0bd98989ea17cb749ab9b5e6d6bda898430a3cadbf57467308681571805fd80162cfdcc154684c949eb89612cb20b3c69ad65ba75b25797199469bf05b5fee2eb23ce74aa7e7c00ba40b58d23607c2890ce70dffa16969dd2dea91011c81dc21809a64cf6b78ea730993c81d5639384bb39d9e00634c555591bb89adea36612367e0d9d38dd837bb9147952092be6a7f47ca9eb301d663cb023d63c0fc2afe6bba699b053da4eb9a47f8052a24fdde16727548d25819d69498d5f90583d6bb0736466a9227a2a0e7df5fec2f9b591d0f75caec07c5521b4b01ee0f673ba8524d9969a474b4582f7364a50e5a9479c4ac47b75ff6ab82aad2685340c95ab8e59ac413ddf17eb4fd5cf7c4ecff8e1729a8a6c12b0c7eca60c2bab268c4c6628d695907f778613fc79be0eeabe9f55837134879730d40a08cca797b4f288b94c6368f119d1fa013c2e568a6c0ab511abbcfbc899ded51ed7b7b4cf80975d0497d136a16e3fbb7b9c942a3815b74959c0b6ff4c308383fa43a542093eb554b2f44a42391f2ea525a60b5ddd71e53e7920aa5ffec7e4e3aeb069c151a7bd30fd9d55805097a4cba8ce47e283f389f4475bb94eee695ce465cad5b2d0f69331104d223670b25b70be24e2dfb1fd84242dca35a6d359609c131f55226537a8784358b54f818df5c51c50b51684e8735e4b414d441b7790dfa92cde1563dc6562da22f5d2a58cea6e8bab331ddb43d307a4c86f932d05d02fd7908446119a30d76b2bf9862f0b9ed4ec2816af9cc6b5e17e6d1e00d4f980288315d1b41174f1907c04b91f6eaac337d071eacc4405428bd819eb088b1000c845ae29d4f390f6fb252820d49c7fc5c2f650ff01ca88aaab9bafa533b4c2f037c495a7af3104563f52f009d88e9e19856dac4692f02dcf94ed7a6760ad6d1017b9cf784859a72d49f211413740211257e70fae3faf3a503af11c39f8f50940ed7af4b54188fc05a501fd18923695eaa2be3d75f0fa77c64c3197a07252dc100893d871f421c1c227e2e428bfe1de7119c8555e264d84c4b85d67fadb8f58601fa17de4b98f960aba5efe906f81419264a7fdafb6e0fc9210be02bdd186120056f429d93e998c47e85340d31af8c011de10fb304e8a88700ab25fdd4c30f7b0127db3c617eb53e198938b1888cc66a4f26747d00e6c3590e8b3f6b52e783cf0f61851e57266fa849c1d93ca0f8b527852fb46d57f6f751586ad6900dcd8ba302bb39ce673927a7aaaff8373e2a83be6a057c86efccfc4637dc096c9ba9eac00bb660a2fe5505581653a3c3d4fb5b52be4cee3fe7a63ef522611ddcfe86072c0d44cc00ef4a83fc9a115ac3702968f7c6a108af855db71f33cc486f23d8269b098b9fe0e4fe0755cb297fe8b1f1a5edb75811db7c9d5304dbf5d7531426b99607439976bd9e09505d51ff31b6c41a7fbd93ea1a43d90549a2bb25fa5dcc0a7502ab4ca98a918982f195dd78cc140e9b36bce2b15680fda6b5c09b4d57cbb2b8071469b97fee9eded9daba291a23bd88035610b15ca1d2ce40e0ad19893f16990b0a5f8bff8be729881142df637d6902925d267035f749efe6e3d91f62aa3a4303f3008b8aa8b9a177cfbd567c9b7643cea890ea80d7f3e077c76d164fcdd4270316517d4d4fbc053f12feb0147c7e4aed66eb241d259a45306558421f33e35503b94dc04fea5b078c67ae5b5cef3c7ebe20e569a9f4f0e8b2c88ad7ac4d457d04fdc0091e5dd206076451d4343ec7b701f318ab577255acd039277f22dc4a3e0309bcd3fc83a7d1b299b522f1310f9755cdd5235d13586d541f9ff97dc2b0ea13

Am I wrong for something or ? Thanks for help.

**Comment by moneromooo-monero** [comment]
While I'm not going to debug your javascript, one thing that jumps at me is that you seem to be using the salts as hex dumps, rather than raw. If this is indeed what is being done, this is wrong.

**Comment by jtomtan** [comment]
> While I'm not going to debug your javascript, one thing that jumps at me is that you seem to be using the salts as hex dumps, rather than raw. If this is indeed what is being done, this is wrong.

When spending a bulletproof2 output, to generate the signature, a inSk is needed. As I understand, 
inSk {
x: --> the one time private key for the real_output
a: --> the mask
}
What is the mask for inSk of bulletproof2 to fill? Since now the mask is deterministic, what to fill here?

**Comment by moneromooo-monero** [comment]
```
    key genCommitmentMask(const key &sk)
    {
        char data[15 + sizeof(key)];
        memcpy(data, "commitment_mask", 15);
        memcpy(data + 15, &sk, sizeof(sk));
        key scalar;
        hash_to_scalar(scalar, data, sizeof(data));
        return scalar;
    }
```

sk is the result of derivation_to_scalar from the output's derivation.

**Comment by jtomtan** [comment]
> ```
>     key genCommitmentMask(const key &sk)
>     {
>         char data[15 + sizeof(key)];
>         memcpy(data, "commitment_mask", 15);
>         memcpy(data + 15, &sk, sizeof(sk));
>         key scalar;
>         hash_to_scalar(scalar, data, sizeof(data));
>         return scalar;
>     }
> ```
> 
> sk is the result of derivation_to_scalar from the output's derivation.

Great, it works! Thanks a lot for the guidance. The first pure JS code for bulletproof2 is now working. We will first use it in the Ownbit wallet. And later we may open source it, thanks for the help!
