### ISSUE TITLE
monero-wallet-rpc JSON RPC interface unusable

### ISSUE THREAD

**Issue by abyssal0** [monero-project/monero#5860]
The title
After executing the start command:
./bin/monerod
The call to daemon RPC was successful
The call to wallet RPC failed
How can I solve the problem?

**Comment by xiphon** [comment]
You also have to start the wallet `monero-wallet-rpc`.

**Comment by abyssal0** [comment]
the option '--rpc-bind-port' is required but missing
I added,but prompt:
This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly
How can I start the wallet `monero-wallet-rpc` right

**Comment by xiphon** [comment]
Please provide the command you ran and the output

**Comment by abyssal0** [comment]
command : ./bin/monero-wallet-rpc
output: Failed to parse arguments: the option '--rpc-bind-port' is required but missing
command : /bin/monero-wallet-rpc --rpc-bind-port 18082
output: This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly.

**Comment by xiphon** [comment]
Something is odd then. There should be another error message. Literally ` Must specify --wallet-file or --generate-from-json or --wallet-dir`

**Comment by moneromooo-monero** [comment]
This is not an error fwiw, someone thought it best to print this at every run. But this is a bug tracker, not a help desk. If there's no bug you can point to, I'll be closing this. For help using monero, try #monero on Freenode.

**Comment by abyssal0** [comment]
> Something is odd then. There should be another error message. Literally ` Must specify --wallet-file or --generate-from-json or --wallet-dir`

yes,You're right
E Must specify --wallet-file or --generate-from-json or --wallet-dir
