### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jakehemmerle** [monero-project/monero#5862]
The word 'battery' is spelled 'batttery' in 43 places.

**Comment by xiphon** [comment]
40 of them are autogenerated translations

**Comment by moneromooo-monero** [comment]
Be very quick if you want this in the release branching about... now :)

**Comment by jakehemmerle** [comment]
@moneromooo-monero Thanks for the ping! PR is in at referenced issue above. New to github so I'm not sure how to link the two :)

**Comment by moneromooo-monero** [comment]
Thank, it'll get merged soon.

**Comment by jakehemmerle** [comment]
Should I close? #6030 #6031
