### ISSUE TITLE
add an "unprune_blockchain" command for the daemon

### ISSUE THREAD

**Issue by fuwa0529** [monero-project/monero#5873]
Mostly for symmetry and aesthetic.

**Comment by dEBRUYNE-1** [comment]
You cannot unprune a blockchain file, as the data that is needed to 'restore' the full blockchain has literally been thrown away.

**Comment by dEBRUYNE-1** [comment]
+invalid

**Comment by fuwa0529** [comment]
I feel some positive imagination has been strangled here.
