### ISSUE TITLE
deamon synced OK, no blocks warning persists

### ISSUE THREAD

**Issue by DanielBullimore** [monero-project/monero#5880]
So I have read through all bug label issues. This one isn't there. (some other label?)

Running release 14.1.0 monerod.exe... windows 10

Looks like daemon is sending warning message every two minutes when it should send new top block message. See attached image.
Has been doing this for days. Recently removed --public_node as a result daemon has stopped claiming to be off-line.  Yet still sends 'no blocks in 90' error. 

no probs getting in and out peers
rpc works fine have sent and received funds

![Untitled](https://user-images.githubusercontent.com/50190195/64220585-00267680-cf1e-11e9-98aa-b8b41eec108a.png)

Is this a known/patched bug? I don't want to waste time debugging for a pull request that has been resolved.

**Comment by moneromooo-monero** [comment]
It is not a known bug. Is your computer time off ?

**Comment by DanielBullimore** [comment]
Oh my you were not even kidding. monerod.exe uses system clock. My servers clock had inverse am/pm. Fresh install on a built for purpose machine and not setting the clock messed me up.
Hopefully the next person can read this and _quickly_ solve.
Thanks moneromooo-monero your a total asset to this project.
