### ISSUE TITLE
Proving official monero GUI wallet as flatpak package on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [monero-project/monero#5903]
Hi. 
Dears why you do not make your official GUI wallet available as flatpak package on FlatHub ?
If you provide it as flatpak on FlatHub, then it will be available in secure trusted way for nearly all Linux users .....

**Comment by dEBRUYNE-1** [comment]
Please reopen on the Monero GUI repository:

https://github.com/monero-project/monero-gui/issues

**Comment by dEBRUYNE-1** [comment]
+invalid
