### ISSUE TITLE
What about exa wallet? Is it trusted?

### ISSUE THREAD

**Issue by Nokia808** [monero-project/monero#5904]
Hi. There is new wallet called exanwallet:
https://wallet.exan.tech/
Currently, they have their mobile wallet available on Google play:
https://github.com/exantech/exa-wallet-android
& for iOS:
https://github.com/exantech/exa-wallet-ios

Is it trusted? Can you verify it?

**Comment by dEBRUYNE-1** [comment]
This is a bug tracker. You can ask your question in the weekly discussion thread on Reddit:

https://www.reddit.com/r/Monero/comments/d0u9us/rmonero_weekly_discussion_september_07_2019_use/

**Comment by dEBRUYNE-1** [comment]
+invalid
