### ISSUE TITLE
fast_exit followed by exit resulted in "segmentation fault: 11"

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero#592]
```
fast_exit
Daemon stopped
exit
2016-Jan-02... [node] Stop signal sent
...
Deinitializing rpc server...
```

Segmentation fault: 11

On El Capitan.

**Comment by moneromooo-monero** [comment]
I think we could just remove fast_exit now, since (1) there is no lengthy save op on exit anymore and (2) the wait-forever-on-network bug is fixed.

On Linux, fast_exit doesn't stop anyway, it seems to fail, and exit after that works fine.
