### ISSUE TITLE
--proxy doesn't seem to work

### ISSUE THREAD

**Issue by teran-mckinney** [monero-project/monero#5925]
I'm running 0.14.1.0 like this: `monerod --non-interactive --no-igd --hide-my-port --proxy tor,127.0.0.1:9050,100`

If I do a `lsof -p` on the pid, it has direct connections to nodes and no connection to 127.0.0.1:9050. Didn't see any relevant messages in the logs.

Not sure yet if this is fixed in 0.14.1.2.

Can someone else confirm this behavior? Seems like a pretty major issue given the privacy expectations.

**Comment by vtnerd** [comment]
It is working as written, although that behavior may not be expected/obvious. The best source to read is the [anonymity networks markdown](https://github.com/monero-project/monero/blob/master/ANONYMITY_NETWORKS.md).

`monerod` is written to work in "dual" mode currently when i2p/tor are configured. P2p control traffic and transaction broadcasting is done over i2p/tor, while everything else is done over the public networks. There are concerns of eclipse attacks and blocking nodes over i2p/tor.

Currently you have to manually specify an i2p/tor node. We are working on seeding nodes - not sure if this will be GUI only or CLI too. Instructions are in that markdown.

**Comment by moneromooo-monero** [comment]
Maybe you should rename --proxy to --txproxy ?

**Comment by teran-mckinney** [comment]
Ah, gotcha. I was expecting all outbound traffic would go through the proxy.

Thanks for confirming. Definitely could be better documented in the --help.

**Comment by moneromooo-monero** [comment]
It's now renamed.

+resolved

**Comment by teran-mckinney** [comment]
Thank you!

**Comment by teran-mckinney** [comment]
I actually think this is broken. My sent transactions seem to never get out of pending if I use --tx-proxy tor,127.0.0.1:9050,100 in 0.15.1. Either that or it's very brittle.

**Comment by vtnerd** [comment]
What is the state of the Tor? Is it initialized? Are there errors printed in the log?

**Comment by vtnerd** [comment]
Nevermind, I know the issue.

There aren't any default seeds, and you most likely haven't explicitly listed a hidden service on the command line. Its a known "issue" as we haven't completely enabled i2p/tor "out-of-the-box". I/we were hoping to come up with a way to spread hidden services over the public network so that new seed nodes would not have to be specified. There are some privacy concerns, and I haven't come up with a good mitigation.

The GUI was considering adding some default nodes in so that it "just-worked" .. @selsta  ?

**Comment by teran-mckinney** [comment]
Ah, gotcha. Thank you.

**Comment by selsta** [comment]
> The GUI was considering adding some default nodes in so that it "just-worked" .. @selsta ?

I did not look into I2P / Tor. Maybe @jtgrassie @xmrdsc ?
