### ISSUE TITLE
[Request] add transaction decoding to wallet-rpc

### ISSUE THREAD

**Issue by mirathewhite** [monero-project/monero#5953]
It would be very helpful to be able to validate transactions signed in cold storage prior to broadcast.  (Basically, a last minute sanity check in the view wallet).  

Input: a signed transaction hex,
Output: recipient address, tx amount, and fee.  Alternatively, the meta-data that the daemon-rpc returns for get_transactions.

**Comment by moneromooo-monero** [comment]
Do you know about describe_transfer, and does it not fit your needs ?

**Comment by mirathewhite** [comment]
Yes!  Thank you. Do you know when `describe_transfer` will be added to monero-wallet-rpc?

**Comment by moneromooo-monero** [comment]
It was added in the past. Is it not working ?

**Comment by jtgrassie** [comment]
@mirathewhite it's just not documented in the guide. `describe_transfer` takes a string parameter of either `unsigned_txset` or `multisig_txset`.

**Comment by erciccione** [comment]
> I think someone is paid to update the docs from time to time so it'll get there.

AFAIK currently nobody is paid or have an open CCS proposal for that. An update of the dev guides is very needed tho, so if somebody wants to take care of that, please do. I would also totally support a CCS with that goal. 

If you find other important stuff is missing in the docs, plese open an issue [on gitlab](https://repo.getmonero.org/monero-project/monero-site) or let us know somehow, so we can keep track of what needs to be updated. In the meantime i will open an issue about this one.
