### ISSUE TITLE
Why ability to add custom remote node working !!!

### ISSUE THREAD

**Issue by panagiotos** [monero-project/monero#5961]
While using remote node feature it automatically selects a remote node. Unable to provide my custome node.

**Comment by panagiotos** [comment]
![imageedit_1_5754906903](https://user-images.githubusercontent.com/46250897/66252991-b381c580-e77f-11e9-8d0c-4305f90c6144.gif)

**Comment by panagiotos** [comment]
after editing that remote node to my node it automatically switches to unknown remote node. not cool.

**Comment by erciccione** [comment]
This is related to the GUI, wallet. Which is here: https://github.com/monero-project/monero-gui

Please reopen this issue in the correct repository.
