### ISSUE TITLE
Monero-wallet-cli: Says mined funds are locked even when they aren’t 

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#5975]
I’m mining on testnet and mined a fair amount of testnet XMR. When I open my wallet after a few days away, monero-wallet-cli will say a loooong list of things like this:

Height 1245678, txid <123456abcde>, 5.175835, idx 0/0
NOTE: This transaction is locked, see details with: show_transfer efghi09876

The issue is that it is saying this for both locked and unlocked mined XMR. So some of the more recently mined XMR is indeed locked for 60 blocks or whatever, but the message also exists for mined XMR thousands of blocks back, which are very much unlocked. 

Is it possible to have the “Note: This transaction is locked” message for only mined XMR that is actually locked?

**Comment by moneromooo-monero** [comment]
They're locked at the time. The message should probably be removed for coinbase txes though.

**Comment by SomaticFanatic** [comment]
Right. Locked at the time. But logging into my wallet after many days away displays the message even though the funds have long been unlocked. Or maybe I’m not understanding something.

**Comment by moneromooo-monero** [comment]
Yes, that it's saying that at the time its blockchain hasn't progressed past the block the tx is in.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/5977
