### ISSUE TITLE
Current master failing on Ubuntu 19.04 VPS

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#5976]
https://pastebin.com/USjXGY7s

**Comment by dEBRUYNE-1** [comment]
Have you tried building with #5969?

**Comment by SomaticFanatic** [comment]
Fixed the previous crash but now there's a new one: https://pastebin.com/FUb5k4wf

**Comment by dEBRUYNE-1** [comment]
Can you try again after the recent merges? Or did you already include those?

**Comment by erciccione** [comment]
@SomaticFanatic try again with the latest master. #5978 should have solved your problem.

**Comment by moneroexamples** [comment]
I compiles fine on 19.04. Just checked as well.

**Comment by SomaticFanatic** [comment]
Fixed
