### ISSUE TITLE
monerod version command should get running daemon's version via RPC

### ISSUE THREAD

**Issue by ndorf** [monero-project/monero#5994]
One would expect[1] the command `monerod version` (as opposed to the _option_ `monerod --version`) to get the running daemon's version via RPC. Instead, it simply prints the version from the binary that was invoked, just like the `--version` option:

```
$ ./release-v0.14/release/bin/monerod version
2019-10-16 19:27:46.202     I Monero 'Boron Butterfly' (v0.14.1.2-release)
2019-10-16 19:27:46.208  I Generating SSL certificate
Monero 'Boron Butterfly' (v0.14.1.2-release)
$ ./master/release/bin/monerod version
2019-10-16 19:28:04.548   I Monero 'Boron Butterfly' (v0.14.1.2-d66db18c0)
2019-10-16 19:28:04.553        I Generating SSL certificate
Monero 'Boron Butterfly' (v0.14.1.2-d66db18c0)
```

No attempt at RPC is made when the command is `version` (this would fail with any other command, e.g. `status`):

```
$ ./master/release/bin/monerod --rpc-bind-port=0 version
2019-10-16 19:33:05.577   I Monero 'Boron Butterfly' (v0.14.1.2-d66db18c0)
2019-10-16 19:33:05.583        I Generating SSL certificate
Monero 'Boron Butterfly' (v0.14.1.2-d66db18c0)
```

It doesn't seem that an RPC to support this exists -- [get_version](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_version) doesn't return a version string, but rather some opaque unsigned int. It seems reasonable to add one, though. Of course, it should be disabled for restricted RPC. Any objections?

[1]: `monerod --help` says `Usage: ./master/release/bin/monerod [options|settings] [daemon_command...]`. So, when invoking `monerod version`, `version` is the `daemon_command` argument, not an "option."

**Comment by trasherdk** [comment]
So when running different versions on main/stage/testnet, which one should return it's version?

**Comment by xiphon** [comment]
> So when running different versions on main/stage/testnet, which one should return it's version?

* `./monerod --version`
should print `./monerod` version
* `./monerod version`
should print mainnet daemon version
* `./monerod version --testnet`
should print testnet daemon version

**Comment by trasherdk** [comment]
Okay.

So, `./monerod --version` is `file version`
and `./monerod version` is `what is running`

Right?

**Comment by xiphon** [comment]
Yep, should be that way

**Comment by moneromooo-monero** [comment]
> It doesn't seem that an RPC to support this exists

get_info

**Comment by ndorf** [comment]
> get_info

This one currently returns the same string "v0.14.1.2" for both master and release-v0.14. I assume it'd be okay to change it to the full version string (with -release or commit hash suffix)?

In any case, it seems that string (as reported by e.g. --version) isn't getting updated after an incremental build, but only a clean one. Looking into that.

**Comment by moneromooo-monero** [comment]
I think I'd be OK with that as long as it stays restricted.

**Comment by hyc** [comment]
> In any case, it seems that string (as reported by e.g. --version) isn't getting updated after an incremental build, but only a clean one. Looking into that.
You have to manually delete build/version.cpp; it is not getting rebuilt automatically. Getting cmake to cooperate on that has proved quite challenging.
