### ISSUE TITLE
Implement support for connecting through proxy

### ISSUE THREAD

**Issue by Jojatekok** [monero-project/monero#60]
This is a requirement for both daemon and the wallet.

![Proxy support](https://cloud.githubusercontent.com/assets/1928320/3568328/7dbeedca-0b2e-11e4-8f0a-6fed1353d1f8.png)

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by moneromooo-monero** [comment]
vtnerd added support for tor and i2p proxies, and I think it also works with "normal" SOCKS proxies.

**Comment by vtnerd** [comment]
Yup, they both provide a normal socks proxy server that has special logical for ".onion" and ".i2p" domains. Right now only the wallet provides a proxy in the normal sense though, the daemon uses proxies only for i2p / tor connections. In other words, the wallet will proxy all HTTP connections to the daemon via the proxy, whereas the daemon proxies only p2p connections that are destined for i2p or tor.

**Comment by xanoni** [comment]
Can be closed, see here https://github.com/monero-project/monero/pull/7616
