### ISSUE TITLE
Error - couldn't connect to daemon (from RPC) for status command

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#604]
I think this is similar to a bug that has been fixed and then unfixed a couple of times. 

http://fpaste.org/309344/51457314/

So, with the old self-compiled binaries (bitmonero v0.8.8.7-0193bfc), I'm able to use "./bitmonerod --bind-rpc-ip (IP ADDRESS) status " to get the status of the daemon. 

With a new compile (Monero 'Hydrogen Helix' (v0.9.0.0-10cc6a8)) and hydrogen helix release, I can't use that command.

Oddly enough, in all versions,  print_cn and diff work.

**Comment by moneromooo-monero** [comment]
Works here. Can you try with latest ? Also, you don't need --bind-rpc-ip here.

**Comment by Gingeropolous** [comment]
Pastie dead, and I think this was fixed at some point.
