### ISSUE TITLE
Inactivity lock seems too strict

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#6043]
I can't even finish reading the list of commands inside the help command without my CLI wallet locking me out with the cow due to inactivity. Can we make the lock time a little less strict, or better yet, have an option to turn it off completely in the "set" command?

**Comment by moneromooo-monero** [comment]
It's a minute and a half by default. That seems fairly long. Is yours shorter ? You can disable it by setting the timeout to 0 in the settings.

**Comment by SomaticFanatic** [comment]
90 seconds seems too strict to me. I suppose this is a subjective measurement. But I would prefer it be closer to 3 minutes by default.

**Comment by ndorf** [comment]
I also found the 90 second timeout annoying, but I think it's an appropriate default nonetheless. The default should err on the side of safety, and it's only a minor inconvenience to type `set inactivity-timeout 180` or even 0 if you want it completely off.

Perhaps the lock message should include a short blurb like "You can configure this locking behavior, type `help set` for more info?"

**Comment by SomaticFanatic** [comment]
`inactivity-timeout` is not listed in the `help set` menu

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6076
