### ISSUE TITLE
./monero-blockchain-stats binary fails on pruned node 

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#6073]
I simply ran the `./monero-blockchain-stats --testnet` command and it errored out without finishing.

I have no idea what this command does. I'm just testing stuff for the 0.15 release.

https://pastebin.com/FFQHz9Jw

**Comment by SomaticFanatic** [comment]
Be aware, I ran monero-blockchain-prune and ./monero-blockchain-prune-known-spent-data beforehand

**Comment by SomaticFanatic** [comment]
I unpruned my node and ran it again and it worked fine. Maybe we need an error message like we have for ./monero-blockchain-export "Sorry we can't do this you have a pruned node"

**Comment by moneromooo-monero** [comment]
I don't even remember what it's supposed to do now.

**Comment by hyc** [comment]
What was pasted is what it did - it spits out counters of blockchain stats to stdout, in CSV format.

> Why is the first entry into monero-blockchain-stats for testnet from 1970? :)

The genesis block has a timestamp of 0.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6094 should fix it.
