### ISSUE TITLE
Will dev team consider Σ-protocols ? 

### ISSUE THREAD

**Issue by shine0108** [monero-project/monero#6101]
It seams that Σ-protocols is better than Ring-Sign, will the dev team of monero condider Σ-protocols ?

**Comment by moneromooo-monero** [comment]
This is not really the place. You'll want to ask on Freenode in #monero-research-lab, or in https://github.com/monero-project/research-lab if you prefer github. I'll still keep this open for now in case a mathematician with an informed opinion on this pops in.

**Comment by SarangNoether** [comment]
What sigma protocol(s) in particular?

**Comment by shine0108** [comment]
Here is the paper (https://eprint.iacr.org/2014/764.pdf) which the sigma protocol based on.
Using the sigma protocol mentioned in the paper, we can improve anonymity set size to N with only aboult 4 logN proof size.
So, I think sigma protocol can work better than ring sign for hiding the relationship between sender and receiver, since the computational complexity and anonymity set size are a linear relationship if we use Ring-Sign, but they are logarithmic relation while sigma protocol is used.
And Zcoin have already used the sigma protocol. 
https://github.com/zcoinofficial/zcoin

**Comment by SarangNoether** [comment]
That particular sigma protocol deals with single lists of commitments, for which an application to Zerocoin was proposed. Work is currently underway to extend this particular construction (and a generalization by Bootle et al.) to handle the case of both amount commitments and signing keys simultaneously. Other sublinear transaction protocols have also been proposed.

**Comment by SarangNoether** [comment]
Also note that the verifier complexity in this construction is still linear in the size of the anonymity set (with a slight reduction possible using multiexponentiation techniques).

**Comment by shine0108** [comment]
Thank you very much. I think it can be closed, since no any others continue to discuss this issue.
