### ISSUE TITLE
v0.15 Binary Release Date?

### ISSUE THREAD

**Issue by Fenny** [monero-project/monero#6109]
Building on linux keeps hanging on core_rpc_server.cpp.o for hours, I rather wait for the official binaries. 

When can we expect this to be released on the website?

**Comment by moneromooo-monero** [comment]
This file (and wallet2.cpp and chaingen_main.cpp) require a lot of resources. If it hangs on those, you likely need more RAM, as it's likely starting to swap, which cuts performance hard.

**Comment by dEBRUYNE-1** [comment]
@Fenny - Should be available soon. If you are particularly impatient, the direct download link is already available:

https://downloads.getmonero.org/cli/monero-linux-x64-v0.15.0.0.tar.bz2

Given that the binary was built deterministically, the hash should match the hashes posted by others in this thread:

https://www.reddit.com/r/Monero/comments/drj72w/cli_v01500_carbon_chamaeleon_has_been_tagged_you/

**Comment by trasherdk** [comment]
I just had to try.
https://downloads.getmonero.org/gui/monero-gui-win-x64-v0.15.0.0.zip
Nothing there :^)

**Comment by dEBRUYNE-1** [comment]
@trasherdk - Only applies to the CLI.

**Comment by dEBRUYNE-1** [comment]
CLI v0.15.0.0 release binaries are available now.

**Comment by dEBRUYNE-1** [comment]
+resolved
