### ISSUE TITLE
Wallet unresponsive when trying to make a transaction after unlocking the inactivity lock

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero#6113]
Right after unlocking with my password, i get a series of `[wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]: [wallet XXXX]:`

if now i try to use the `transfer` command the wallet become unresponsive.

**Steps to reproduce:**

1. Open the wallet and wait until the safety lock activates
2. Unlock with wallet password (and notice the series of `[wallet XXXX]:` appearing)
3. Use `transfer` command (eg `transfer 43b7TPk6yRxaeau3zeVsKW4tyMaztEJ1Ag9x79eQDcw71Qe4kXAywgxdeW6UzaQS8kLAMjGRLW9vUYhGfibd4Hc97QqLQYH 1`)
4. Insert password
5. Wallet is now unresponsive. The 'enter' button has no effect and if i press it again i get `Error: invalid password` and right after `Error: Unknown command 'MYPASSWORD', try 'help'` (note that MYPASSWORD is actually my password but without the first and last character)

**System:**
Self compiled v0.15.0 on Debian Buster

**Comment by selsta** [comment]
Can you test if you get the same behaviour with the getmonero.org release binary?

**Comment by erciccione** [comment]
@selsta. Sure, but I'm going out now. I will be able to test again in some hours.

**Comment by moneromooo-monero** [comment]
Sounds like buggy readline.

**Comment by erciccione** [comment]
Just tested with the official binaries and everything went fine (no bug).

@moneromooo-monero i built static binaries using https://github.com/erciccione/monero-static-docker, which is an edited version of the Dockerfile in this repo. If readline is the problem i think would be better to suggest a newer version (now the Dockerfile [uses version 8.0](https://github.com/monero-project/monero/blob/master/Dockerfile#L94)). If that's the issue i could make some tests and suggest a newer version of readline that doesn't create problems.

**Comment by hyc** [comment]
The version of readline isn't the problem. It's how it got built, and which terminfo/termcap library it got linked against, and whether that library includes correct terminal descriptions for the terminal you're currently running on.
