### ISSUE TITLE
Unsafe clearing of secrets

### ISSUE THREAD

**Issue by bertptrs** [monero-project/monero#6129]
In a few locations across the codebase, `memset` is used to clear secrets from memory before discarding the memory. However, most compilers will see this as a dead-store and remove the `memset` call. It is therefore better to use `memset_s` (from C11) or similar to actually clear those secrets. The actual locations are:

- ~autotrust.c~ part of a submodule, let's ignore it for now
- ~getentropy_linux.c~ part of a submodule, let's ignore it for now
- md5_l.h
- blake256.c (several times)

I'm working on a patch that fixes those issues, but reading your contributing guidelines, I thought I should open an issue first. Is that correct?

**Comment by moneromooo-monero** [comment]
md5_l.h is not used. blake is only used for PoW, so nothing secret. Normally you'd use memwipe, but this is in epee, which crypto does not depend on.

**Comment by moneromooo-monero** [comment]
And generally, there is not need for an issue unless you want to ask something, gauge opinions, etc. If you're sure about what to do in a patch, a patch only is fine.

**Comment by moneromooo-monero** [comment]
Cryptonight (the PoW hash which uses blake) is also used as a KDF, where the blake clearing could potentially matter.

**Comment by moneromooo-monero** [comment]
Actually crypto already depends on epee. Patch looks good, thanks.

**Comment by moneromooo-monero** [comment]
OMG. md5 is actually used now. For HTTP auth :S

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6540

**Comment by moneromooo-monero** [comment]
Merged
