### ISSUE TITLE
Wallet: Distinguish transfers made to a subaddress in a single transaction while in txpool

### ISSUE THREAD

**Issue by tmoravec** [monero-project/monero#6163]
Imagine we have multiple transfers made to a single subaddress in a single transaction:

    transfer <addr1> <amount1> <addr1> <amount2>

We can distinguish these transfers in `incoming_transfers`. Unfortunately, `incoming_transfers` is not available for txpool transactions because such transactions don't include all info that `incoming_transfers` needs (e.g., global output indices).

The appropriate method for learning about txpool transactions is `get_transfers`. Unfortunately, `get_transfers` doesn't distinguish between multiple outputs aiming to a single subaddress (see https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L1779).

To learn about individual outputs in txpool transactions, Moneromooo suggested enhancing the `get_transfers` output with `std::vector<uint64_t> amounts;` in addition to the regular `amount`.

I'll try to implement this.

**Comment by stoffu** [comment]
What is the use case of this feature?

**Comment by tmoravec** [comment]
What's the usecase of several outputs then? If we can do it, the software should be able to distinguish it. It makes little sense to have a feature on the sending side if it's hidden on the receipient side.

**Comment by stoffu** [comment]
In my understanding, the suggested command

    transfer <addr1> <amount1> <addr1> <amount2>

is only useful when you want to split your fewer larger outputs into more smaller outputs by sending funds to yourself. I don't see any other situation where this would be useful.

When you're splitting your outputs, you're the one who initiated the tx, so you have the full knowledge about the tx. Why do you care about being able to see your individual outputs coming to you in that tx in the tx pool?

> It makes little sense to have a feature on the sending side if it's hidden on the receipient side.

"It makes little sense" alone isn't a good enough reason to make changes to the code, especially for sensitive parts which shouldn't receive frequent changes. Any proposed changes must be supported by real demand and use case.

**Comment by tmoravec** [comment]
For instance Minko if you're familiar with that. Minko uses this feature so players can play multiple bets of the same color in a single transaction. But this applies to any automated system where the buyer is to receive a specific piece (physical or digital) from seller for each output. If goods has its own subaddress, in order to buy multiple pieces of the goods in a single transaction, the seller needs to distinguish the outputs.

**Comment by arnuschky** [comment]
Isn't just consistency a good enough reason? I mean, this information is available for confirmed tx through `incoming_transfers`. Making the same functionality available for unconfirmed pool payments seems only consistent to me.

**Comment by stoffu** [comment]
@tmoravec 
> For instance Minko if you're familiar with that. Minko uses this feature so players can play multiple bets of the same color in a single transaction. But this applies to any automated system where the buyer is to receive a specific piece (physical or digital) from seller for each output. If goods has its own subaddress, in order to buy multiple pieces of the goods in a single transaction, the seller needs to distinguish the outputs.

Oh, I never thought of such use cases. Now I'm fine with your proposal.

BTW Minko already seems to be able to distinguish individual incoming outputs in a single unconfirmed tx, indicating that they use some modified version of wallet2 to enable that. It'd be nice if the developer of Minko could share that patch with us. Perhaps @binaryFate knows something?

@arnuschky 
I personally think that every non-trivial code change (such as this one touching wallet2 scanning) should come with tangible benefit such as new use cases or increased performance, because otherwise the commit log could get cluttered unnecessarily and potentially bugs or malicious code could be introduced.

**Comment by binaryFate** [comment]
@stoffu Currently Minko uses some features from https://github.com/moneroexamples/onion-monero-blockchain-explorer additionally to the vanilla daemon, to be able to distinguish each output and also their respective order. So I'm afraid there is no "nice" or useful patch we can share.

The proposed patch here would be a nice simplification in practice for anyone needing that specific feature -- I did not check the proposed code itself though.

**Comment by stoffu** [comment]
@binaryFate Thank you for responding.
