### ISSUE TITLE
[RELEASE] Wallet API accepts only long payment id format

### ISSUE THREAD

**Issue by naughtyfox** [monero-project/monero#6167]
When we try to set short payment id to a transaction we get the following error: 
```
payment id has invalid format, expected 64 character hex string
```

Despite support of long payment ids is deprecated it appears to be the only acceptable format if you use `wallet2_api.h` interface. It was deleted in this commit - https://github.com/monero-project/monero/commit/def703abecbd55fdb358b31250bd722766aa24d1.

**Comment by selsta** [comment]
Can you use integrated addresses?

**Comment by naughtyfox** [comment]
Yes, we can use integrated addresses. But I think this is a bug nevertheless.

**Comment by selsta** [comment]
AFAIK support for separate short payment IDs has been removed everywhere in the codebase.

**Comment by naughtyfox** [comment]
IIRC integrated address is just an address + payment id. As long as integrated addresses are supported the payment ids should also be. I know for sure that long payment id format is deprecated, but not short one.

**Comment by selsta** [comment]
I did only support 64 bit payment IDs intentionally in def703a. Maybe someone else can comment if this is wrong, but I thought that short payment IDs should **always** use the integrated format.

**Comment by hyc** [comment]
That was my understanding as well, always integrated format.

**Comment by naughtyfox** [comment]
Ok, sorry then.
