### ISSUE TITLE
rpc_payments not working via bootstrapped daemon

### ISSUE THREAD

**Issue by sebseb7** [monero-project/monero#6171]
does not seem to work via bootstrapped daemon

**Comment by moneromooo-monero** [comment]
Not enough details to know what you're reporting.

**Comment by sebseb7** [comment]
I have a cli wallet connected to a daemon which is connected to another daemon (with rpc payments enabled) via --bootstrap-daemon-address, branch release-v0.15 ,

**Comment by sebseb7** [comment]
a direct connection to the payments-enabled daemon works

**Comment by moneromooo-monero** [comment]
I can repro, will fix.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6173

**Comment by sebseb7** [comment]
works for me,
