### ISSUE TITLE
Error while opening wallet with hardware key (Ledger Nano S)

### ISSUE THREAD

**Issue by marcinulan** [monero-project/monero#6181]
1. Open monero wallet app
2. Choose to open a wallet created in previous version with hardware key (Nano S)
3. Plug-in Ledger Nano S, unlock it and open Monero App on Ledger
4. Type in password
5. Click 'Ok'

Expected result: wallet is opened
Actual result: I get an error "Couldn't open wallet: Wrong Device Status: SW=6930 (EXPECT=9000, MASK=ffff)"

Software versions:
Mac OS X 64-bit: 0.15.0.1 Carbon Chamaeleon
Ledger firmware: 1.6.0 (Secure Element), 1.11 (MC)
Monero App on the Ledger: 1.4.1

![Zrzut ekranu 2019-11-25 o 17 45 47](https://user-images.githubusercontent.com/13141685/69560611-4be03d80-0fac-11ea-9996-c4e3e6071369.png)

**Comment by rating89us** [comment]
You are using monero-gui, and here is the repository of monero-cli
There is already an issue for your problem here:
https://github.com/monero-project/monero-gui/issues/2480

**Comment by selsta** [comment]
v1.4.2 is now out: https://www.reddit.com/r/Monero/comments/e1k7dg/ledger_monero_app_142_is_out/
