### ISSUE TITLE
xmr rpc 401 Unauthorized

### ISSUE THREAD

**Issue by NoBugBoy** [monero-project/monero#6186]
--rpc-login

There is no problem with the specified user name and password. Now an error is reported:

<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>

Does anyone have java source code to see how to connect

![image](https://user-images.githubusercontent.com/33510892/69608722-ff0b6e00-1062-11ea-8b4e-d8bcde15ffde.png)

![image](https://user-images.githubusercontent.com/33510892/69608814-22ceb400-1063-11ea-81b9-d52d5cd39d4b.png)

**Comment by vtnerd** [comment]
This might be a CORs issue depending on how you are connecting.

**Comment by binlaniua** [comment]
it's not basic auth, it's use digest auth

**Comment by moneromooo-monero** [comment]
If no further information showing there's likely a bug, I'll close.
