### ISSUE TITLE
Can't build release v0.15

### ISSUE THREAD

**Issue by 4NobleTruths** [monero-project/monero#6189]
Using instructions:
https://github.com/monero-project/monero/tree/release-v0.15#compiling-monero-from-source

On Debian 9 Qubes 4

Error log attached.
[CMakeError.log](https://github.com/monero-project/monero/files/3895125/CMakeError.log)
[CMakeOutput.log](https://github.com/monero-project/monero/files/3895130/CMakeOutput.log)

**Comment by vtnerd** [comment]
pthreads does not appear to be installed.

**Comment by 4NobleTruths** [comment]
Installing libevent-core for pthreads doesn't fix it.
To me, seems like it's all those lines that say "c++: error: unrecognized command line option"

**Comment by vtnerd** [comment]
The first error was to a missing link on `pthread_create`. The output from the standard console would be useful too because it differs from this I think.

**Comment by 4NobleTruths** [comment]
Then I guess something is missing from the list of dependencies on that  page.

This is what it wrote from console redirect:
[make.log](https://github.com/monero-project/monero/files/3895288/make.log)

The only failures are regarding the fcf unrecognized commands.

**Comment by moneromooo-monero** [comment]
Works for me from a fresh vm.

**Comment by 4NobleTruths** [comment]
I'm building in a Debian-9-minimal VM template, with just the minimal networking and the Monero dependencies listed on above release page.

If a VM is created from it, has the same errors.

**Comment by 4NobleTruths** [comment]
It builds from the git clone, but not from the zip archive of that release branch.
