### ISSUE TITLE
Wallet: Export transfers to CSV

### ISSUE THREAD

**Issue by tmoravec** [monero-project/monero#6191]
Having the option to export the transfers history into CSV is something that would be tremendously useful for people and companies building services on top of Monero. I offer to implement it.

**Comment by arnuschky** [comment]
Not much more to say. 
 - export the content of `show_transfers` to a `.csv` file (simple write the same table separated with `,`) to a file
 - write a heading first
 - command could be `export_csv <filename>`
 - should also be accessible via command line for scripting

I think that's about it. I wouldn't bother doing more (ie messing with configurable separators or similar)

Is that sufficient detail?

**Comment by fuwa0529** [comment]
Not in wallet with C++ please. There's already `wallet-rpc` that can export structured JSON array, which is also very business friendly like CSV.

**Comment by fluffypony** [comment]
@fuwa0529 what does C++ have to do with it? Producing CSV is pretty trivial, and I've never heard of an accounting system like Xero allowing you to import random JSON. I don't see a problem with this feature request, imho.

**Comment by moneromooo-monero** [comment]
export_transfers

**Comment by fluffypony** [comment]
Closed because it already exists :)

**Comment by fuwa0529** [comment]
@fluffypony there are many problems with too much C++, but I'll save it since it's closed..
