### ISSUE TITLE
Where can I find the password for wallets created by generate_from_keys?

### ISSUE THREAD

**Issue by normoes** [monero-project/monero#6193]
I start the Monero RPC basically like this:
```
monero-wallet-rpc --stagenet --disable-rpc-login --wallet-dir /monero/wallets
```

I create a watch-only wallet like this:
```
curl -i -X POST http://localhost:38083/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"generate_from_keys", "params":{"viewkey":"c007....", "address":"57P8...", "filename": "wallet", "password": "empty"}}'
```

I tried it with and without `, "password": "empty"`.

That call returns a valid response in both cases:
```
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "address": "57P8...",
    "info": "Watch-only wallet has been generated successfully."
  }
}
```

The problem is, I cannot use the wallets created that way, since I don't know the password.
Using the CLI or the RPC just returns:
> Error: failed to load wallet: invalid password

**Comment by normoes** [comment]
You can find the related code [here](https://github.com/monero-project/monero/blob/master/src/wallet/wallet_rpc_server.cpp#L3436).

**Comment by normoes** [comment]
Also this method seems quite buggy to me.

I experience this issue https://github.com/monero-project/monero/issues/5852.

Also the Monero RPC just stops doing anything when generating a wallet using the same file name.

**Comment by moneromooo-monero** [comment]
I'm not sure what you're saying between:
- I forgot the passord
- I know the password, but it does not work when reopening the wallet

If the former: you're suppose to keep the password if you want to reuse it. The wallet doesn't keep it in some alternate place, it'd defeat the purpose.
If the latter: are you using non 7 bit ASCII characters in the password ?

I'll check the filename reuse hang.

**Comment by normoes** [comment]
I tried both ways, with and without password using `generate_from_keys`.
The password I explicitly specified is the string `empty` in the second example.

I expected:
 * To not need a password in case I don't set one.
 * or to use `empty` as password, if set.

Neither works. I did not forget the password.

**Comment by moneromooo-monero** [comment]
I generated a testnet wallet from my main test wallet using the generate_from_keys RPC, using a simple 7 bit ASCII password. Worked.
I close it, and tried to open it with monero-wallet-cli. Worked.
I exited monero-wallet-cli, and tried to generate it again, with the same parameters. Errored with:
AssertionError: {u'jsonrpc': u'2.0', u'id': u'0', u'error': {u'message': u'Wallet already exists.', u'code': -1}}

So it looks like you're doing odd things.
Note that monero-wallet-rpc might have been busy scanning your wallet for a while, that could cause a hang till it's done if it's got a lot to refresh.

Double check passwords.

**Comment by normoes** [comment]
Ok,I'll check again. Thanks for testing.

**Comment by moneromooo-monero** [comment]
I noticed you were using a view only wallet. I had tried a full wallet. I just tried a view only one and it also worked.

**Comment by normoes** [comment]
OK.
I created the wallet:
```
curl -i -X POST http://localhost:38083/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"generate_from_keys", "params":{"viewkey":"c007...", "address":"57P...", "filename": "test1", "password": "p"}}'
```

Doing it again now returns the proper message `Wallet already exists.`.

And then tried to open the wallet:
```
curl -i -X POST http://localhost:38083/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"open_wallet", "params": {"filename": "test1", "password":"p"}}'
```

with the following result:
```
{
  "error": {
    "code": -1,
    "message": "Failed to open wallet"
  },
  "id": "0",
  "jsonrpc": "2.0"
}
```

and the Moneor RPC:
```
2019-11-28 14:12:40.090	I Generating SSL certificate
2019-11-28 14:12:40.670	I Generating SSL certificate
2019-11-28 14:12:41.593	E !r. THROW EXCEPTION: error::invalid_password
```

---


Is this the right way to pass a password (`"password": "p"`)?
Not passing a password like done above also returns `invalid password` when trying to open the wallet with an empty password.

**Comment by normoes** [comment]
I can successfully open already existing wallets using `open_wallet` .

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by moneromooo-monero** [comment]
I tried your command above, with changed viewkey and address and port, and it works.

**Comment by moneromooo-monero** [comment]
Upload a monero-wallet-rpc level 2 log I guess. Might show something interesting.

**Comment by normoes** [comment]
Here you can find a `level=4` log.
1) I created the wallet using `generate_from_keys`
2) I tried to open it.

https://bin.privacytools.io/?fd9303ed1411fa82#Vyw8mU6FKpx/YT59oobTYfWsteJct0g/1cKXMZOh5rw=

**Comment by moneromooo-monero** [comment]
This wants javascript.

**Comment by normoes** [comment]
Sorry:
https://paste.debian.net/1118396/

**Comment by moneromooo-monero** [comment]
Try with this: https://paste.debian.net/hidden/6f0bf05f/

**Comment by normoes** [comment]
I tried it again: https://paste.debian.net/hidden/fcba442c/
Same procedure:
1) generate_from_keys
2) open_wallet

**Comment by normoes** [comment]
You know what..
I tried to generate the wallet with the public viewkey. This results in the above situation.

I just now tried it with the secret viewkey, that worked.

I guess, I am missing some basic knowledge about cryptography?

**Comment by dEBRUYNE-1** [comment]
View-only wallet requires the private view key in order to be able to look for transactions belonging to your wallet. Put differently, it is required to decrypt the shared secret.

**Comment by moneromooo-monero** [comment]
Better error for this case:

https://github.com/monero-project/monero/pull/6194

**Comment by normoes** [comment]
Well, thanks a lot for the explanation and the help.
