### ISSUE TITLE
monerod and monero-wallet-gui don't use the same directory with data-dir

### ISSUE THREAD

**Issue by goin2mars** [monero-project/monero#6195]
Hi not sure if this is intended behavior or not. Using ./monerod --data-dir 'path' makes a folder 'lmdb' to put the db into and monero-wallet-gui set to go to the same path as the data-dir goes into 'LMDB'. I'd attempted to rename the folder, but long story short here I'm re-downloading the entire blockchain because I've since inadvertently deleted the wrong folder so I wasn't able to verify if renaming one to the other and feeding it to the other program will work. Using linux, monero 0.15.0.1

**Comment by moneromooo-monero** [comment]
Not intended. The GUI setting is passed to monerod though, which makes the case switch puzzling.

**Comment by goin2mars** [comment]
Turns out I've done this to myself. I'd decided it was smart to name the chains intended resting place to be descriptive yet not actually say monero and also not be more than a word long and in stupidity settled on 'LMDB' and named the folder that myself then continued to be confused for a bit.
