### ISSUE TITLE
new rpc payments flags not working with --restricted-rpc-port

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#6196]
there's 2 ways to have restricted rpc.... one with --restricted-rpc whcih restricts all ports, and one with --restricted-rpc-port VALUE that allows you to confine restrictions to one port.

i just tried launching with the new payments flags on a conf file that had the port one, and it exited out saying that it needed a restricted rpc.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6198

**Comment by moneromooo-monero** [comment]
Fixed
