### ISSUE TITLE
Privacy: DNS leak when running with torsocks

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero#6218]
It seems `monerod` tries to connect to the [default DNS servers](https://github.com/monero-project/monero/blob/633f14b9766f0aa9786147c0c151322380bb5c18/src/common/dns_utils.cpp#L45-L52) directly (i.e. circumventing the Tor SOCKS proxy) when running it with `torsocks`:

```sh
# Running with torsocks
export DNS_PUBLIC=tcp
torsocks "$MONEROD" \
    --p2p-bind-ip 127.0.0.1 \
    --rpc-bind-ip 127.0.0.1 \
    --no-igd \
    --hide-my-port \
    --db-sync-mode safe \
    --check-updates disabled \
    --disable-dns-checkpoints

# Now observe DNS traffic
```

Related: https://github.com/monero-project/monero/issues/3128

**Comment by moneromooo-monero** [comment]
monerod tries to do *everything* directly. That's the point of torsocks, it intercepts normal TCP calls to route them through Tor. Are you saying the DNS ones are missed when using TCP mode ?
The second example does not have torsocks btw, forgot ?

**Comment by leonklingele** [comment]
> it intercepts normal TCP calls to route them through Tor.

It doesn't for those TCP DNS requests, i.e. circumventing the Tor proxy, that was my point :) 

> The second example does not have torsocks btw, forgot ?

No it's using `--tx-proxy` instead

**Comment by moneromooo-monero** [comment]
torsocks docs hint it could be the call is a direct syscall, which it cannot intercept.
In any case, the DNS queries are for the update mechanism and the checkpoints, they're not really needed so you can use "--disable-dns-checkpoints" and "--check-updates disabled", which should stop any DNS request (can you confirm ?). I'll add this to the README too for now.

**Comment by moneromooo-monero** [comment]
Wait, you have these. It shouldn't do any extra DNS requests in the first place...

**Comment by moneromooo-monero** [comment]
I'm not super familiar with this, but dumping traffic on port 53, I don't see anything when running with torsocks (and I did not use "--disable-dns-checkpoints" nor "--check-updates disabled"). I didn't set DNS_PUBLIC either, just: ./build/release/bin/monerod --no-igd --p2p-bind-ip 127.0.0.1 --rpc-bind-ip 127.0.0.1 --hide-my-port
To scan for DNS traffic, I used: tcpdump 'tcp port 53'
What do you use, and is this missing some traffic ?

**Comment by leonklingele** [comment]
I was using tcpdump too. `monerod` is trying to resolve the [seed nodes](https://github.com/monero-project/monero/blob/411f1b0ee30f1d424621eb856841dc82d2f161c2/src/p2p/net_node.h#L282-L288).

> is this missing some traffic ?

What do you mean by that?

BTW, I'm on Mac OS, Monero 6def88ad405b39f632a91afa3aacbb92ecc63c1f and Torsocks 2.3.0

**Comment by moneromooo-monero** [comment]
I meant, is my usage doing to capture only part of it. Like, can DNS traffic sometimes go not through 53, etc. That is, do you see anything in my command which would miss some traffic you're seeing.

torsocks 2.3.0 here, on master plus various changes but none relating to DNS.

But I've just realized that I'm on Qubes, which has a funky DNS forwarder, so quite possibly port 53 is not getting the traffic it would ohterwise have...

**Comment by leonklingele** [comment]
Your command looks just fine, I'm using it exactly the same way.

> I'm on Qubes

That indeed might be the "problem" here ;)

**Comment by fuwa0529** [comment]
torsocks will likely redirect dns queries to the tor dns resolver, rather then the normal ones defined in `resolved.conf`, for resolving `.onion` addresses at least.

**Comment by fuwa0529** [comment]
Also it's probably not a leak, since the tor dns resolver still needs to consult local dns. It's probably just normal upstream forwarding, since these are not `.onion` addresses.

**Comment by hyperreality** [comment]
I can't reproduce this on Debian 10, DNS requests are forwarded through torsocks the correct way. @leonklingele can you give more details about your setup? 

As a side note, it's weird how when you directly query seeds.moneroseeds.* URLs, you get a SERVFAIL, but querying the domain directly (without the subdomain) gives you the list of nodes.

**Comment by leonklingele** [comment]
Sorry for the delay.

So far I've only tried to reproduce this on OS X (haven't updated the OS in a quite while). I'm launching monerod using a script (see https://github.com/monero-project/monero/issues/6218#issue-533300053) which has been working fine before, i.e. without leaking DNS queries.

The leaking DNS queries are issued right after logging `Using public DNS server(s): [..]` if that's of any use (I use Little Snitch, a firewall for OS X, which halts the queries as long as they weren't confirmed using a visual GUI prompt).

What has been tested so far:

- Switched back to an older version of torsocks which I was using when DNS leaks were not occurring (to no avail)
- Tried to compile older versions of monerod, but lack some outdated compile-time dependencies (mainly `boost`) which have been upgraded since. I will try to install the older ones again asap

I also found an old version (`monerod-v0.11.1.0-master-35d5aa36` compiled on `12 Jan  2018`) which works fine and doesn't leak anything, so it's either a new bug inside monerod or in one of its updated dependencies.

**Comment by moneromooo-monero** [comment]
If you use torsocks, it can't be a monerod bug since the point of torsocks is to intercept *non tor* requests, so monerod is meant to connect normally without tor.

**Comment by leonklingele** [comment]
> it can't be a monerod bug

Yes it can. It is possible to somehow bypass the Tor SOCKS proxy when using `torsocks`, I've seen that happening before.

**Comment by leonklingele** [comment]
Interesting, removing local `libunbound v1.9.6` headers (which makes monero compile with https://github.com/monero-project/unbound/tree/0f6c0579d66b65f86066e30e7876105ba2775ef4) has resolved the issue.
The DNS leak was introduced to `libunbound` between `v1.9.4` and `v1.9.5`. Starting a bisect now.

**Comment by leonklingele** [comment]
That was fast.. Only 2 commits were made to `libunbound` between `v1.9.4` and `v1.9.5`

The issue was probably introduced by https://github.com/NLnetLabs/unbound/commit/b83d9f8d0481918253ef178629daccc2e66afe93.

**Comment by leonklingele** [comment]
Actually, the issue was introduced between the `v1.9.4` and `v1.9.5` release of Homebrew's `unbound`. It is caused by compiling it with `--enable-tfo-client`, an option to enable TCP Fast Open. Will file an issue on the torsocks tracker.

Sorry for the abuse.
