### ISSUE TITLE
Trezor not found on v0.15.0.1

### ISSUE THREAD

**Issue by Quaternioneer** [monero-project/monero#6226]
Monero GUI reports, Couldn't open wallet: device not found: Trezor". The Trezor works with v0.14.1. In the previous version I would run start-gui.sh which is not in this version, so I run monero-wallet-gui.

Trezor: Model T
Ubuntu: 18.04 LTS

**Comment by selsta** [comment]
Fixed in v0.15.0.2 which should be out today or in the next days.

**Comment by moneromooo-monero** [comment]
Wrong repo, already reported to the GUI repo, and since fixed, so closing.

+invalid
