### ISSUE TITLE
E Transaction spends at least one output which is too young

### ISSUE THREAD

**Issue by kl1059** [monero-project/monero#6228]
since the fork monerod kicks out this error from time to time - FYI

2019-12-12 17:47:33.038	E Transaction spends at least one output which is too young

**Comment by moneromooo-monero** [comment]
Is it one of your transactions (ie, when you send one) ?

**Comment by kl1059** [comment]
I don't think it is - I have periodically no transactions roughly 3 days or so but the daemon kicks out that message every few hours.

**Comment by moneromooo-monero** [comment]
Then it's someone sending a bad tx, and if your node is still syncing fine, you can ignore it.

**Comment by moneromooo-monero** [comment]
No bug here. Reopen if you think there is, with more info.
