### ISSUE TITLE
RingCT 3.0

### ISSUE THREAD

**Issue by lfrickel** [monero-project/monero#6239]
Hello dear developers,

Is there a plan to transfer Monero to RingCT 3.0 (https://eprint.iacr.org/2019/508.pdf)?
Is there any test implementation in RingCT 3.0 computer code or at least parts of it?
The authors' arguments seem to me quite convincing.

Thanks in advance for your reply.
Yours sincerely,
Leo

**Comment by moneromooo-monero** [comment]
This is a bug tracker. Ask on IRC, reddit or bitcointalk.

It's being looked at though, along with a few other candidates.

+invalid
