### ISSUE TITLE
peer claims higher version that we think (60 for 1998284 instead of 12) - we may be forked from the network and a software upgrade may be needed

### ISSUE THREAD

**Issue by TheBudda** [monero-project/monero#6249]
I have been running a monero for many years now. I am now getting this error below. I have tried compiling from the master with no issues. I have tried your pre-compiled binary files and still get the same errors below  

peer claims higher version that we think (60 for 1998284 instead of 12) - we may be forked from the network and a software upgrade may be needed

monerod is running on an OVH dedicated server
Monero 'Carbon Chamaeleon' (v0.15.0.1-release)
OS: Ubuntu Linux 18.04.3

Please see attached screenshot

Kind regards
TheBudda
![monderod_Screenshot](https://user-images.githubusercontent.com/16983376/71046537-80b95d80-2130-11ea-9235-ea154655e543.png)

**Comment by TheBudda** [comment]
My server system is running the correct time clocks set to London, United Kingdom

**Comment by hyc** [comment]
+invalid

This is not an error, ignore it.

**Comment by ahook** [comment]
FYI, the handful of peers currently sending version 60 for forks are Monero Classic nodes that connected to the wrong network.

https://github.com/monero-classic/monero/blob/master/src/cryptonote_core/blockchain.cpp#L112
