### ISSUE TITLE
Regression in Monero daemon RPC interface

### ISSUE THREAD

**Issue by bartMarinissen** [monero-project/monero#6258]
The following pull request: https://github.com/monero-project/monero/pull/5964/ Introduced a regression into the RPC interface of the Monero daemon.

Specifically, after this commit the get_block command now returns an empty string in the root field .miner_tx_hash in the response. The same data can still be found at .block_header.miner_tx_hash, but this was an interface change. I've since fixed my import scripts to handle this.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6259 should fix it.

**Comment by moneromooo-monero** [comment]
Fixed
