### ISSUE TITLE
Windows x64 is misnamed in latest release assets

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#6261]
Windows x64 zip has a file name of 15.0.1.1 not as it should be 15.0.1 (extra .1)

**Comment by selsta** [comment]
Where did you download the .zip ?

**Comment by SomaticFanatic** [comment]
From GitHub. The assets list the Windows x64 file with an extra .1 but the GPG signed list of hashes doesn’t

**Comment by selsta** [comment]
ping @luigi1111 

https://github.com/monero-project/monero/releases/tag/v0.15.0.1

**Comment by SomaticFanatic** [comment]
Not to FUD, but the current file should be checked against coin stealing like previous binaries had

**Comment by luigi1111** [comment]
@selsta thanks, fixed.

**Comment by selsta** [comment]
> Not to FUD, but the current file should be checked against coin stealing like previous binaries had

I confirmed that the hash was matching, just a typo in the filename.
