### ISSUE TITLE
if wallet opened but not connet success,then do disconnect,the thread will blocked.

### ISSUE THREAD

**Issue by forever00010110** [monero-project/monero#6264]
in  accounts.cpp  141  line, example  in android device

  //-----------------------------------------------------------------
  void account_base::deinit()
  {
    try{
      m_keys.get_device().disconnect();
    } catch (const std::exception &e){
      MERROR("Device disconnect exception: " << e.what());
    }
  }
  //-----------------------------------------------------------------

**Comment by moneromooo-monero** [comment]
Ia this ledger, trezor, other ?

**Comment by forever00010110** [comment]
> Ia this ledger, trezor, other ?

build it and running in android device,in wallet  software

**Comment by forever00010110** [comment]
> > Ia this ledger, trezor, other ?
> 
> build it and running in android device,in wallet software

in api close wallet

**Comment by moneromooo-monero** [comment]
Is this using a Ledger hw wallet, or a Trezor hw wallet ?

**Comment by forever00010110** [comment]
> Is this using a Ledger hw wallet, or a Trezor hw wallet ?

https://github.com/monero-project/monero/blob/master/src/wallet/api/wallet.cpp  line  760，deinit()  function

 In android device，not ledger，the old version don’t have this code，it not have this probelm

**Comment by moneromooo-monero** [comment]
For non ledger/trezor, the disconnect call does nothing. That's why I asked. Did you change the source by any chance ?

**Comment by moneromooo-monero** [comment]
Also, when it blocks, run gdb into the process, ie:
gdb /path/to/your/binary `pidof yourbinaryname`
yourbinaryname will likely be monero-wallet-cli or monero-wallet-rpc
Then:
thread apply all bt

There will be multiple pages, press enter till it's finished displaying all.

**Comment by forever00010110** [comment]
It block in other function，not in deinit()，I will closed it.
