### ISSUE TITLE
Build broken if ALLOW_DEBUG_COMMANDS is undefined

### ISSUE THREAD

**Issue by ahook** [monero-project/monero#6271]
The ALLOW_DEBUG_COMMANDS macro is meant to hide/expose a few p2p commands meant only for debugging: COMMAND_REQUEST_STAT_INFO, COMMAND_REQUEST_NETWORK_STATE, and COMMAND_REQUEST_PEER_ID.

As of about 5 years ago (https://github.com/monero-project/monero/commit/1829966fe#diff-75dbb84a608233b878963350f63597e1R102), this macro was defaulted to be defined.

Since then, code has been added/modified which breaks the build if the macro is undefined. Specifically:
- the net_node::check_trust header should be wrapped in an ifdef
- initializing net_node::m_last_stat_request_time should be in an ifdef
- p2p_protocol_defs::get_proof_of_trust_hash should be in an ifdef
- p2p_protocol_defs::COMMAND_REQUEST_SUPPORT_FLAGS should NOT be in an ifdef
- a couple places are relying on a transitive include that is in an ifdef, these files should explicitly include crypto/crypto.h

I have a patch ready to fix these issues: https://github.com/ahook/monero/commit/c8ba8456ef3953c99497e38c707c8607201a708b

However, it also raises a couple questions about this code. That patch gets everything into working order, but:
- Should we just do away with the macro altogether? Seems not to have been a problem having it defined all these years, and the two important functions are guarded by check_trust()
- Do we even need/want these commands any more? Seems like this admin-level access might be better as an rpc?

**Comment by moneromooo-monero** [comment]
I'm fine removing them since they're unusable due to the key being zeroed.

**Comment by moneromooo-monero** [comment]
Fixed
