### ISSUE TITLE
(stagenet)get_transfer_by_txid  can not return wallet address tx

### ISSUE THREAD

**Issue by binlaniua** [monero-project/monero#6274]
i use gui send xmr to wallet-rpc-cli, but when i use get_transfer_by_txid return -8
--------
![image](https://user-images.githubusercontent.com/5960462/71609305-489b2b80-2bc2-11ea-97ce-eb5d70a6a85e.png)
--------
![image](https://user-images.githubusercontent.com/5960462/71609320-62d50980-2bc2-11ea-90a0-ee7b138e5019.png)
--------
![image](https://user-images.githubusercontent.com/5960462/71609329-797b6080-2bc2-11ea-875c-9016b097eaf7.png)

**Comment by binlaniua** [comment]
get_transfer_by_txid  default use **account_index: 0**, what can i do **get_transfer_by_txid** by any account_index

**Comment by binlaniua** [comment]
if i have many account, how to check tx is belong my wallet, loop check?

**Comment by moneromooo-monero** [comment]
I suppose we could return all if the account_index parameter is not specified. I'm not sure it's a good idea though, since it would further merge accounts, and keeping them separate is a privacy feature.

**Comment by binlaniua** [comment]
> I suppose we could return all if the account_index parameter is not specified. I'm not sure it's a good idea though, since it would further merge accounts, and keeping them separate is a privacy feature.

thanks reply。may be provider another argument **"all_account: true | false"**  :)
