### ISSUE TITLE
Feature request: add ConnectionStatus_Connecting state

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero#6308]
Currently the wallet returns the following connection states:
- `ConnectionStatus_Connected`
- `ConnectionStatus_WrongVersion`
- `ConnectionStatus_Disconnected`

It would be nice to have an additional `ConnectionStatus_Connecting` state, so we could display in monero GUI a "Connecting..." message, which would mean that the wallet is currently disconnected, but trying to connect.

**Comment by moneromooo-monero** [comment]
Those are GUI things (or at least I don't recognize the names) so should be filed in the GUI repo.

**Comment by xiphon** [comment]
Yep, implemented this on the GUI side https://github.com/monero-project/monero-gui/pull/2747
