### ISSUE TITLE
Usage question/problem

### ISSUE THREAD

**Issue by braindamagedjustnow** [monero-project/monero#6316]
How is one supposed to use "--seed-node" command?
I've tried different ways and none seems to work.
I've tried with Windows 10 and 7. Monerod and GUI running as admin and not etc.
When I run the command from the GUI I usually get:

[2/5/2020 10:53 PM] 2020-02-06 06:52:54.203 I Monero 'Carbon Chamaeleon' (v0.15.0.1-release) 
2020-02-06 06:52:54.203 I Initializing cryptonote protocol... 
2020-02-06 06:52:54.203 I Cryptonote protocol initialized OK 
2020-02-06 06:52:54.203 I Initializing core... 
2020-02-06 06:52:54.203 I Loading blockchain from folder C:\ProgramData\bitmonero\lmdb ... 
2020-02-06 06:52:54.998 I Loading checkpoints 
2020-02-06 06:53:01.107 I Core initialized OK 
2020-02-06 06:53:01.107 I Initializing p2p server... 
2020-02-06 06:53:02.371 F Error starting server: Failed to bind IPv4 (set to required) 
2020-02-06 06:53:02.371 I Deinitializing core... 
2020-02-06 06:53:02.391 I Stopping cryptonote protocol... 
2020-02-06 06:53:02.391 I Cryptonote protocol stopped successfully 
2020-02-06 06:53:02.391 E Exception in main! Failed to initialize p2p server.

**Comment by dEBRUYNE-1** [comment]
Can you post the full exact command you are trying to utilize?

**Comment by braindamagedjustnow** [comment]
From the GUI I go to settings then on log I type:
--seed-node 192.168.1.1
I am using another IP of course.

I also tried it with the monerod.exe as a startup command

**Comment by trasherdk** [comment]
More often than not, the `Failed to bind IPv4` means something is using the port already.

**Comment by braindamagedjustnow** [comment]
Well I also tried running it on a clean VM so it's confusing

**Comment by trasherdk** [comment]
Or trying to connect to a non existing or firewalled ip-address/port

**Comment by braindamagedjustnow** [comment]
I've also tried with couple of IPs labeled as white which I get from "print_pl"

**Comment by ndorf** [comment]
--seed-node is an option, not a command. Without a command, you are attempting to start a second instance of the daemon, which fails because another one is already running and using the local ports.
 It should work if you stop the main daemon first, then run it with the option. In this mode it will exit after getting the peerlist, after which you can start the main daemon again.

**Comment by braindamagedjustnow** [comment]
So from CMD running:
"monerod --data-dir D:\Monero\ --seed-node 192.168.1.1"

should do the job?

**Comment by trasherdk** [comment]
You probably want `monerod --data-dir D:\Monero --seed-node 192.168.1.1`

**Comment by braindamagedjustnow** [comment]
Well I still think something is wrong.
I delete p2pstate.bin and then I start the monerod with the following options:
monerod --data-dir D:\Monero --seed-node 192.168.1.1
I use IP labeled as white in print_pl
So I print the peers list with print_pl and save the output to a txt file.
Then I delete the p2pstate.bin again and start the same command with the same IP.
Then I print the peers list and save it to another text file.
Theoretically I should get the same peers list since I am getting in from same source but I am getting different lists?

**Comment by moneromooo-monero** [comment]
Why do you think the same source should give you the same list ?

**Comment by braindamagedjustnow** [comment]
> 
> 
> Why do you think the same source should give you the same list ?

Theoretically I should get the same peers list since I am getting in from same source - isn't this correct? It's not like the node is making up some ips and sending them up. It has a list with known white and grey ips and it should send that list when asked. Or I am just missing something.

**Comment by moneromooo-monero** [comment]
This it not correct. You should expect a different list from the same peer.

**Comment by braindamagedjustnow** [comment]
Well although I can't understand the logic behind this I guess I'll close the issue. Thank you moneromooo-monero!
