### ISSUE TITLE
Manually adding sub addresses to wallet

### ISSUE THREAD

**Issue by godfuture** [monero-project/monero#6323]
I have transferred/recovered my wallet created on desktop to my Android phone. It simply worked, my main account was available on both devices...but...once you create a sub address on desktop or phone, you will not be able to see this sub address on the other device.

This could be easily solved by allowing to add the missing sub address manually.

v0.15.0.1

**Comment by moneromooo-monero** [comment]
And... it fails to ?

**Comment by ndorf** [comment]
@godfuture subaddresses are deterministic and generated in the same order. So, if you generate one in the new wallet, it will be the same as the first one (index=1) from your old wallet.

**Comment by godfuture** [comment]
> @godfuture subaddresses are deterministic and generated in the same order. So, if you generate one in the new wallet, it will be the same as the first one (index=1) from your old wallet.

Maybe this is not about subaddresses. I am speaking of the feature "create new address". I have compared these additional addresses on desktop and android. They are not the same. Should I rename the topic?

**Comment by moneromooo-monero** [comment]
Yes. They're supposed to be the same. First though, double check you're really checking addresses with the same indices.

**Comment by moneromooo-monero** [comment]
ping

**Comment by godfuture** [comment]
Instead of adding a new random account, I would like to specify the key myself, for the reason mentioned above. I have my wallet on both devices. As the blockchain is anyhow the same, two wallets would not really add benefit, but more complexity (coins distributed over multiple places, additional backup, more addresses).
![grafik](https://user-images.githubusercontent.com/4669278/81754688-175b3200-94b7-11ea-9188-fbb489d17d2b.png)

**Comment by moneromooo-monero** [comment]
You can do that in the CLI by specifying the account/subaddress indices. If you mean adding *arbitrary* keys, then that's not how monero works, so no to that. Subaddresses (including accounts) are deterministic, so if you generate some in two wallet files that have the same keys, you'll get the same subaddresses in both. Not sure if that's what you were asking.

**Comment by godfuture** [comment]
> Subaddresses (including accounts) are deterministic, so if you generate some in two wallet files that have the same keys, you'll get the same subaddresses in both. Not sure if that's what you were asking.

Yes, this is what I meant. Lets suppose you are using the same wallet on desktop but also in android, but you add subaddresses only on desktop, then my experience is that these new subaddresses do not show up in android wallet.
