### ISSUE TITLE
Errors code & messages list for wallet RPC ?

### ISSUE THREAD

**Issue by billyadelphia** [monero-project/monero#6331]
Where can I see errors code & messages list for wallet RPC ?

**Comment by moneromooo-monero** [comment]
src/wallet/wallet_rpc_server_error_codes.h

Messages are informative only, don't try to parse them (or very few known ones like "OK", but even sometimes success is not just "OK").

**Comment by moneromooo-monero** [comment]
Not a bug

+invalid
