### ISSUE TITLE
Error while sending XMR from monero wallet

### ISSUE THREAD

**Issue by green41k** [monero-project/monero#6340]
Hey! I just wanted to send some XMR from my monero wallet on my Iphone (official app) to some wallet. But the app not letting me do that. I see an error while sending - "en error occurred. pls try again later....' And im like -WTF. Have no idea why this is happing and why this app not letting me send my own money. Also 2 days ago everything was ok. only last 20 hr
pls help

**Comment by paulshapiro** [comment]
Which app are you using?

**Comment by green41k** [comment]
> Which app are you using?

monero app.
free wallet
looks like they server not working currently 
https://freewallet.org/statuspage

**Comment by trasherdk** [comment]
Freewallet => [Distrusted by the Community](https://www.reddit.com/r/monero/wiki/avoid/#wiki_mobile_wallets)

**Comment by paulshapiro** [comment]
They should use MyMonero for their wallet support. 🤣

**Comment by dEBRUYNE-1** [comment]
Please repost your issue on the monerosupport subreddit (in case you still have issues):

https://www.reddit.com/r/monerosupport/

**Comment by dEBRUYNE-1** [comment]
+invalid
