### ISSUE TITLE
Is it not so important...?

### ISSUE THREAD

**Issue by infoelektron** [monero-project/monero#6385]
![Screenshot_2020-03-13 monero-project monero](https://user-images.githubusercontent.com/48728875/76599981-606a2680-6506-11ea-9aad-8b622fcdcb92.png)

You must write "IMPOSSIBLE TO BUILD AND WE DO NOT WANT TELL YOU HOW TO COMPILE IN A RIGHT WAY!".

Please remove all the code and don't make people waste time. The developer has to be paid for working things not for the time that deliberately makes you lose ...

**Comment by selsta** [comment]
v0.15.0.5 builds fine on all platforms. If you only post a rant without details no one will be able to help you.
