### ISSUE TITLE
Please provide me with a testnet remote node

### ISSUE THREAD

**Issue by SpookyPool** [monero-project/monero#6389]
Hello,

I would like to know if there is a remote node for testnet.
Syncing a whole testnet (on a hdd) for just some small development is not gonna do it for me.
Would me awesome if someone could give me one. 
I tried the testnet remote node on https://moneroworld.com/ but that didnt work.

-Appeljuice

**Comment by selsta** [comment]
https://community.xmr.to/nodes.html

**Comment by SpookyPool** [comment]
> https://community.xmr.to/nodes.html

Thank you very much! Appreciate it!
