### ISSUE TITLE
Regarding the two security vulnerabilities disclosed by the Monroe project

### ISSUE THREAD

**Issue by GongSuiLi** [monero-project/monero#6390]
Regarding the two security vulnerabilities disclosed by the Monroe project:
1. https: //hackerone.com/reports/766963
The Monero node running on my server is v0.15.0.0. Do I have to upgrade to v0.15.0.5? I follow your discussion here: https://github.com/monero-project/monero/issues/6380, should be about this vulnerability. But I am not sure if it will affect our nodes. How do I know if I need to upgrade?
2. https: //hackerone.com/reports/803028
This vulnerability should be related to the GUI of Monero Wallet. If you don't use Monroe Wallet, you don't need to upgrade, right?

**Comment by trasherdk** [comment]
> How do I know if I need to upgrade?

If your running version is older than latest version, upgrade.

**Comment by dEBRUYNE-1** [comment]
1. To err on the side of caution, I'd advise to upgrade to v0.15.0.5 (the tag has already been set), as it contains the security fix.

2. Correct.

**Comment by GongSuiLi** [comment]
> 1. To err on the side of caution, I'd advise to upgrade to v0.15.0.5 (the tag has already been set), as it contains the security fix.

I have read your discussion on this issue. If it is a common Monero node, shall we need to force upgrade to v0.15.0.5? Including monero nodes and monero-cli?

**Comment by moneromooo-monero** [comment]
By now you might as well wait for 0.16, which should be in the next couple weeks.

Anyway, no bug here, so closing.
