### ISSUE TITLE
Linux build issue with v0.15.0.5

### ISSUE THREAD

**Issue by kalibox** [monero-project/monero#6412]
Hi,

I've followed the linux build instructions but always keep getting this error message:

[ 87%] Building CXX object tests/unit_tests/CMakeFiles/unit_tests.dir/hmac_keccak.cpp.o
In file included from /usr/include/gtest/gtest.h:62,
                 from /home/xmr/Downloads/Temp/monero/tests/unit_tests/hmac_keccak.cpp:29:
/home/xmr/Downloads/Temp/monero/tests/unit_tests/hmac_keccak.cpp:126:1: error: static assertion failed: test_name must not be empty
  126 | TEST(keccak_hmac, )
      | ^~~~
make[3]: *** [tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:388: tests/unit_tests/CMakeFiles/unit_tests.dir/hmac_keccak.cpp.o] Error 1
make[3]: Leaving directory '/home/xmr/Downloads/Temp/monero/build/Linux/release-v0.15/release'
make[2]: *** [CMakeFiles/Makefile2:4759: tests/unit_tests/CMakeFiles/unit_tests.dir/all] Error 2
make[2]: Leaving directory '/home/xmr/Downloads/Temp/monero/build/Linux/release-v0.15/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/xmr/Downloads/Temp/monero/build/Linux/release-v0.15/release'
make: *** [Makefile:103: release-all] Error 2

Please can someone assist.

Thanks

**Comment by sumogr** [comment]
I dont know why you get this error on building tests, you shouldnt though, anyhow bypass building tests.
dont run `make release-all` , `make release` should be enough

**Comment by xiphon** [comment]
https://github.com/monero-project/monero/pull/6346

**Comment by kalibox** [comment]
> I dont know why you get this error on building tests, you shouldnt though, anyhow bypass building tests.
> dont run `make release-all` , `make release` should be enough

Thanks but I get this when building using "make" alone.

**Comment by sumogr** [comment]
> > I dont know why you get this error on building tests, you shouldnt though, anyhow bypass building tests.
> > dont run `make release-all` , `make release` should be enough
> 
> Thanks but I get this when building using "make" alone.

clone again including @xiphon 's open PR that fixes this or like i said run `make release` it will exclude the tests (that are included by default in `make` or make `release-all`)

**Comment by kalibox** [comment]
Ah I see, Got it. Thank you.

**Comment by moneromooo-monero** [comment]
That's because it's using the OS' gtest, and they recently added a constraint on names.

**Comment by kalibox** [comment]
Yes, "make release" works ok. My node is now running v0.15.0.5.

Out of interest, when's the next release scheduled for?

Cheers all

**Comment by moneromooo-monero** [comment]
Not known yet.
