### ISSUE TITLE
Error "wrong miner tx in block"

### ISSUE THREAD

**Issue by AntlerDM** [monero-project/monero#6419]
A few days ago, I got the following error message...

`2020-03-31 17:09:55.436	E wrong miner tx in block: <fb877ea3400f731c2b948e87655368f1c0486e3c114bb3f8f3839bec1b2f9596>, b.miner_tx.vin.size() != 1`

The exact same message appeared again today (with the same block hash)...

`2020-04-02 06:17:42.401	E wrong miner tx in block: <fb877ea3400f731c2b948e87655368f1c0486e3c114bb3f8f3839bec1b2f9596>, b.miner_tx.vin.size() != 1`

I am using the pre-compiled CLI Wallet from getmonero.org (v.0.15.0.5) on a MacPro. Mining is being done by xmrig v.5.10.0.

**Comment by moneromooo-monero** [comment]
You likely connected to a peer that's sending you a bad block. You can ignore that. I assume your node is otherwise synced, and not dropping off the network ?

**Comment by AntlerDM** [comment]
I believe sync is okay (I get 'SYNCRONIZATION OK' messages) , but I am also getting a fairly frequent warning...

`2020-04-02 06:46:32.732	W No incoming connections - check firewalls/routers allow port 18080`

Even though the firewall has a rule allowing port 18080 to the computer. Maybe the firewall rule is not correct?

**Comment by moneromooo-monero** [comment]
I wouldn't know. You might also need to set routers in the way to forward.
If you set log level to 1, you'll likely get the IP address from which that block is coming from, should it happen again. Chances are it'll be the same.

**Comment by ronohara** [comment]
I just got the **exact** same message ...

2020-06-04 10:34:13.427	E wrong miner tx in block: <fb877ea3400f731c2b948e87655368f1c0486e3c114bb3f8f3839bec1b2f9596>, b.miner_tx.vin.size() != 1

So completely different node ...and I am on 'Nitrogen Nebula' (v0.16.0.0-release)  ... whereas 3 months ago you would have been on v0.15  ...

**Comment by mooleshacat** [comment]
For the firewall issue because I use UFW I did ```ufw reload``` and I think it fixed it because it started working and I could see port open with canyouseeme
