### ISSUE TITLE
Openssl download in Dockerfile

### ISSUE THREAD

**Issue by normoes** [monero-project/monero#6437]
The Dockerfile in the repository uses `openssl1.1.b` . This is downloaded from https://www.openssl.org/source/openssl-1.1.1b.tar.gz.

See here: https://github.com/monero-project/monero/blob/master/Dockerfile#L61

This URL is returning `404`, because the file was moved to https://www.openssl.org/source/old/1.1.1/openssl-1.1.1b.tar.gz

This causes the build (using the Dockerfile) to break.

~~I will provide a PR for that.~~

**Comment by selsta** [comment]
Note that there are already 2 PRs open to fix this :)

**Comment by normoes** [comment]
Less work for me ;)

**Comment by erciccione** [comment]
Linking to those PRs for reference: #6428 #6420

**Comment by normoes** [comment]
Closing this.
