### ISSUE TITLE
Regarding simplewallet's new "address one-off <major> <minor>" command

### ISSUE THREAD

**Issue by sumogr** [monero-project/monero#6448]
https://github.com/monero-project/monero/pull/6394 seems buggy.
steps to replicate
Create a new wallet, create an one-off subaddress by setting a non existing major index (say 1) and any minor, it still creates a sub address, send some coins back to this address, poof! no key to find them **(do that on testnet of course not with actual xmr :P)**

**Comment by moneromooo-monero** [comment]
Yes, it's annoying. Maybe it should create an account to go with it. Doing so optionally means you can get money and still keep it "hidden" until such time you want to spend it.  Thoughts ?

**Comment by sumogr** [comment]
> Yes, it's annoying. Maybe it should create an account to go with it. Doing so optionally means you can get money and still keep it "hidden" until such time you want to spend it. Thoughts ?

I can think of no other way than creating a new major index (when the chosen account does not exist) along with the one-off. Just think of a way to remind people that they keep hidden money in that account cause there is going to be confusion :D

**Comment by moneromooo-monero** [comment]
That'd be counter productive, wouldn't it. It would not be hidden by definition :P

**Comment by sumogr** [comment]
> That'd be counter productive, wouldn't it. It would not be hidden by definition :P

I guess,  if possible, just a check then that the major index selected for the one-off already exists

**Comment by moneromooo-monero** [comment]
Maybe a "sweep_account" command would be better, since you really don't want to create an account with a very high index, it'd take a lot of time (and space).

**Comment by sumogr** [comment]
true the command can easily be abused. well the advantages of it start to seem less than the disadvantages. I dont know i cant think of anything clever

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6449
