### ISSUE TITLE
Mac Monero GUI 15.0.4 + Monero 15.0.5 Update

### ISSUE THREAD

**Issue by clipse2004** [monero-project/monero#6458]
Hi Guys, 
I use the Monero GUI 15.0.5 with embedded Monero Version 15.0.1. I have seen there is a new Monero Version 15.0.5 online. How can I update this? Only Copy and Paste into the GUI File?
Or is it not necessary to update this?

Thanks

**Comment by selsta** [comment]
Where did you download the GUI v0.15.0.5? We will release v0.15.0.5 GUI on getmonero.org soon.

**Comment by clipse2004** [comment]
I downloaded it here https://web.getmonero.org/de/blog/ im a little bit confused because the different versions. So the newest Version from GUI is 15.0.4 right? I thought I need copy Monero into Monero GUI for updating :/

**Comment by selsta** [comment]
CLI and GUI are separate program.

CLI is at v0.15.0.5 and GUI is at v0.15.0.4. GUI v0.15.0.5 will be out soon. You simply have to download it from getmonero.org once it is released, no copying is required.

**Comment by clipse2004** [comment]
ah okay thanks now I understand :)
