### ISSUE TITLE
Couldn't open wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)

### ISSUE THREAD

**Issue by vitormilagres1992** [monero-project/monero#6462]
Hi, I have been getting this error for quite a while now:
Couldn't open wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)

This happens when I connect my Ledger Nano X wallet to my GUI Monero version:
monero-gui-v0.15.0.4

How do I fix this?

Thanks

**Comment by vitormilagres1992** [comment]
I just realized it works with version 14.1.0, so I assume it's an issue with compatibility.
Shouldn't there be a fix for this by now? Version 15.X.X came out a long time ago

**Comment by selsta** [comment]
Update the Ledger Monero app.
