### ISSUE TITLE
start monero-wallet-rpc.exe command report a error with" No message store file found: testwallet.mms"

### ISSUE THREAD

**Issue by niukouMan** [monero-project/monero#6482]
start monero-wallet-rpc.exe command in windows environmentreport a error with" No message store file found: testwallet.mms" 

**Execute the command as follows** :
D:\softwar\wallet\monero-win-x64-v0.15.0.5\monero-x86_64-w64-mingw32-v0.15.0.5> .\monero-wallet-rpc.exe --stagenet --rpc-bind-ip 0.0.0.0 --rpc-bind-port 38089 --confirm-external-bind --rpc-login test:123456 --daemon-address monero-stagenet.exan.tech:38081 --password 123 --wallet-file testwallet
This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly.

Monero 'Carbon Chamaeleon' (v0.15.0.5-release)
Logging to D:\softwar\wallet\monero-win-x64-v0.15.0.5\monero-x86_64-w64-mingw32-v0.15.0.5\monero-wallet-rpc.log
2020-04-27 10:07:43.219 W Loading wallet...
2020-04-27 10:07:43.228 I Generating SSL certificate
2020-04-27 10:07:44.091 I Generating SSL certificate
2020-04-27 10:07:44.997 W Loaded wallet keys file, with public address: 57XTcQx7eVmGm8AMWs3fWNTBTQ8W1kukt9hGicdge8sCZk3cB752YYCNmWWsVmjRwpfBe3E6gHuAA8xJzPNTTvB37vGKyiS
2020-04-27 10:07:45.028 E No message store file found: testwallet.mms

**Comment by selsta** [comment]
You can ignore the `No message store file found` error message.

I don’t see a relevant error in the logs. What is the exact problem?
Can you try a different stagenet node? E.g. from here https://community.xmr.to/nodes.html

**Comment by niukouMan** [comment]
./monero-wallet-rpc.exe --stagenet  --rpc-bind-port 38089 --confirm-external-bind --rpc-login test:123456 --daemon-address node.xmr.to:38081  --password 123 --wallet-file testwallet

This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly.
Monero 'Carbon Chamaeleon' (v0.15.0.5-release)
Logging to F:\Collin\monero-win-x64-v0.15.0.5\monero-x86_64-w64-mingw32-v0.15.0.5\monero-wallet-rpc.log
2020-04-27 15:13:42.853 W Loading wallet...
2020-04-27 15:13:43.169 I Generating SSL certificate
2020-04-27 15:13:43.653 I Generating SSL certificate
2020-04-27 15:13:45.015 W Loaded wallet keys file, with public address: 59kGwHD7XxHjarpCvp7i4dSeErRRQaXA7dwvSZSQQpFH54dDB3V4KzCh2fsKXHJK1SLV88S7yAP7xUPgLx8QphyD65WQezw
2020-04-27 15:13:45.114 E ****No message store file found: testwallet.mms**


![QQ截图20200427231354](https://user-images.githubusercontent.com/18626089/80388900-04ecd000-88dd-11ea-9d28-263c7c95aeb9.png)
**

**Comment by niukouMan** [comment]
@selsta

**Comment by selsta** [comment]
What is your exact goal with monero-wallet-rpc? I don’t see any relevant errors in the logs.

**Comment by niukouMan** [comment]
There was an error in execution _monero-wallet-rpc.exe_ command 
the error is " No message store file found: testwallet.mms"
i do not known the file **.mms is for
his file was not generated when execute _monero-wallet-cli.exe_ command to created the wallet 
![QQ截图20200427233456](https://user-images.githubusercontent.com/18626089/80391030-c9073a00-88df-11ea-8324-be039aaaed0c.png)
@selsta

**Comment by moneromooo-monero** [comment]
Is your report just "there is this line that gets printed" or "there is this line that gets printed and something does not work" ? The mms file is used for high level mulisig ops, it gets created if you use these ops.

**Comment by rbrunner7** [comment]
I think the confusing thing is that it is output as an **error**. I see this as a mistake now that I take responsibility for. It should be a warning at most, as in 99% of all cases there won't be a `.mms` file because people don't do multisig with the help of the MMS, and that missing file is perfectly ok.

I will make a PR to change that.

**Comment by moneromooo-monero** [comment]
There is already one.

**Comment by moneromooo-monero** [comment]
Fixed.
