### ISSUE TITLE
Trezor T passphrase prompt in Monero GUI

### ISSUE THREAD

**Issue by requestor1607** [monero-project/monero#6491]
Currently a driver update has been rolled out by Trezor, since then the prompt for input of passphrases is not on the Trezor anymore. In the Monero GUI only at startup the passphrase is requested via the wallet. Then several times the Trezor blinks to enter the passphrase, but Monero does not show a dialog box. 
The end result: no synchronized wallets and lots of people afraid loosing their transactions etc.

People who use the command line editor force the Trezor to use the Trezor, solving the issue. However, people who donwload the GUI are most probable not able to do that.

https://www.reddit.com/r/monerosupport/comments/gb1981/enter_passphrase/

**Comment by selsta** [comment]
This should be solved with v0.15.1.0 which should be out in 1-2 weeks.

**Comment by requestor1607** [comment]
> This should be solved with v0.15.1.0 which should be out in 1-2 weeks.

That sounds great! Did not know it was already on the radar.

**Comment by selsta** [comment]
There are both CLI and GUI PRs that should fix this.
