### ISSUE TITLE
spelling errors in monero binaries

### ISSUE THREAD

**Issue by adrelanos** [monero-project/monero#6492]
wrong right

offets offsets
additionnal additional
enought enough
droppped dropped
requred required
Distrubution Distribution
unsuported unsupported

That's just what `lintian` is telling me.

grep -r unsuported

Binary file usr/bin/monero-blockchain-ancestry matches
Binary file usr/bin/monero-blockchain-usage matches
Binary file usr/bin/monero-blockchain-mark-spent-outputs matches
Binary file usr/bin/monero-blockchain-export matches
Binary file usr/bin/monero-blockchain-import matches
Binary file usr/bin/monero-blockchain-depth matches
Binary file usr/bin/monero-blockchain-prune matches
Binary file usr/bin/monero-wallet-cli matches
Binary file usr/bin/monerod matches
Binary file usr/bin/monero-blockchain-stats matches
Binary file usr/bin/monero-blockchain-prune-known-spent-data matches
Binary file usr/bin/monero-gen-ssl-cert matches
Binary file usr/bin/monero-wallet-rpc matches
Binary file usr/bin/monero-gen-trusted-multisig matches

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6565

Some of those don't appear to be ours.

**Comment by moneromooo-monero** [comment]
Fixed for those in our code. Open a new bug if you find more.
