### ISSUE TITLE
cli wallet strange little bug

### ISSUE THREAD

**Issue by sumogr** [monero-project/monero#6496]
using latest release (15.0.5): on entering the wrong password upon opening an existing wallet  
`Error: failed to load wallet: invalid password` good

using compiled bins from latest master: on entering the wrong password upon opening an existing wallet 
` Error: failed to load wallet: std::exception`
it doesnt grab the e.what(). 
why?

**Comment by sumogr** [comment]
nevermind its due to the wallet2.h for wasm restructuring i found what caused it

**Comment by selsta** [comment]
Are you going to open a PR to fix it?

**Comment by sumogr** [comment]
> Are you going to open a PR to fix it?

ok
