### ISSUE TITLE
How to judge whether the transaction was sent to me by confusing the address and viewing the private key?

### ISSUE THREAD

**Issue by wshhz** [monero-project/monero#6517]
I want to implement a local wallet, and I do n’t know how to determine whether the transaction was sent to me by obfuscating the address and viewing the private key. How can I implement the algorithm?

**Comment by moneromooo-monero** [comment]
I have no idea what you're asking, but this is a bug tracker. I suggest trying #monero on Freenode, or reddit.

**Comment by UkoeHB** [comment]
@wshhz to get a better understanding of how Monero works, you may want to check out [Zero to Monero 2nd Ed.](https://web.getmonero.org/library/Zero-to-Monero-2-0-0.pdf).
