### ISSUE TITLE
Add json-rpc endpoint for monerod command: rpc_payments

### ISSUE THREAD

**Issue by t-900-a** [monero-project/monero#6521]
When I have rpc payments enable I can get info from the monerod daemon via command: rpc_payments

Example output is:

Client Id | Balance | Total mined | Good | Stale | Bad | Dupes | Last update
-- | -- | -- | -- | -- | -- | -- | --
exampleclientid | 666 | 666 | 100 | 0 | 0 | 0 | 40 seconds ago
1 clients with a total of 26466 credits |   |   |   |   |   |   |  
Aggregated client hash rate: 1 H/s |   |   |   |   |   |   |  

I would like to be able to query this information via rpc.

Example rpc method request:
curl -X POST 127.0.0.1:18081/json_rpc -H 'Content-Type:application/json' --data "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"rpc_payments\"}"

Example returned output:
{
  "aggregate_client_hash_rate": "40 H/s",
  "num_clients": 1,
  "total_credits": 26466,
  "clients": [
    {
      "client_id": "exampleclientid1",
      "balance": 666,
      "total_mined": 666,
      "good": 100,
      "stale": 0,
      "bad": 0,
      "dupes": 0,
      "last_update": "2 seconds ago"
    },
    {
      "client_id": "exampleclientid2",
      "balance": 2344,
      "total_mined": 2370,
      "good": 2100,
      "stale": 0,
      "bad": 0,
      "dupes": 0,
      "last_update": "40 seconds ago"
    }
  ]
}

Edit: Also wondering what level of difficulty it would be to add this.

**Comment by moneromooo-monero** [comment]
There is one, it's called rpc_access_data.

**Comment by t-900-a** [comment]
Thanks, I'm having issues with this so I created a post on stackexchange.
https://monero.stackexchange.com/questions/12193/using-the-rpc-access-data-method-daemon-rpc

I'll close the post as the functionality is already there.
