### ISSUE TITLE
Consider adjusting default nblocks-per-sync

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#654]
In #653 the current default of 1000 is reported to be 10x slower than 10000 on a HD. 

If the default is increased, users with low memory requirements could always set it lower as needed. 

However, we should at least identify the minimum memory requirement for 10000 and ensure it is reasonable mainstream before doing this.

Also, possibly some intermediate value would be a better tradeoff between performance and memory use.

**Comment by NanoAkron** [comment]
#1129

**Comment by luigi1111** [comment]
@NanoAkron #1129 is about number of blocks to request from a peer; this issue is about DB sync (the former is 200, the latter is 1000).

**Comment by NanoAkron** [comment]
@luigi1111 What's the right way to proceed here?

**Comment by luigi1111** [comment]
I guess change it here if there is need https://github.com/monero-project/monero/blob/29735c8f8fda032833924285c2da7ea9b15a77c7/src/cryptonote_core/cryptonote_core.cpp#L328

**Comment by Gingeropolous** [comment]
@iamsmooth , this has been fixed, right? or am I still conflating the two things as mentioned above....

**Comment by iamsmooth** [comment]
This is old enough and was a performance issue. The database code is sufficiently different now that it should just be closed and another specific issue opened if there is an identified problem with the current code.
