### ISSUE TITLE
import_key_images not working

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#6547]
To recreate issue:

1. Clone master. Create a fresh testnet wallet. Move over some tXMR. Send a single tx so your wallet has a mixture of sent and received funds. 

2. Create an associated view wallet. In the view wallet type `refresh`. View wallet will say `Balance: 123.456790123456, unlocked balance: 123.456790123456 (Some owned outputs have missing key images - import_key_images needed)`

3. Open original wallet. Type `export_key_images keyimagefile`. Wallet will say `Signed key images exported to keyimagefile`.

4. Open view wallet back up. Type `import_key_images keyimagefile`. Wallet will say `Signed key images imported to height [height], 0.000000000000 spent, 123.456790123456 unspent`

   0.000 spent? For some reason it isn't showing the spent funds in imported key images.

5. Type `refresh` in view wallet. Wallet will still say `Balance: 123.456790123456, unlocked balance: 123.456790123456 (Some owned outputs have missing key images - import_key_images needed)`

**Comment by moneromooo-monero** [comment]
Did you export/import outputs in the other direction first ?

**Comment by SomaticFanatic** [comment]
No. I’ve exported key images before and the above process worked fine. Why is it important to export outputs from a view wallet?

**Comment by moneromooo-monero** [comment]
Because the cold wallet calculates key images on the outputs it gets from the hot wallet.

**Comment by SomaticFanatic** [comment]
Interesting. It works! Perhaps the message can be edited to say “export_outputs then import_key_images needed”

**Comment by moneromooo-monero** [comment]
FWIW, this is done automatically when you make a tx (outputs and key images piggy back on the tx signing files).
