### ISSUE TITLE
rpc call too slow.

### ISSUE THREAD

**Issue by redred77** [monero-project/monero#6563]
I call rpc call to 15151 port like below

```
curl -X POST http://127.0.0.1:15151/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: application/json'
```
```
curl -X POST http://127.0.0.1:15151/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getlastblockheader"}' -H 'Content-Type: application/json'
```

It's so slow that consumes more than few seconds for each call. Sometimes it took 2 minutes to get the result.
When my program calls this jsonrpc several times, monero wallet start to break and gets out of sync.

It didn't happen like this before. It started to fall few days ago.
I updated to latest monerod but still not fixed.

**Comment by moneromooo-monero** [comment]
Do you have something else hammering the RPC in the meantime ? Other even the P2P port ?
Can you run "sudo perf top -a" or other profiler to see anything's pushing the machine, or if it's stuck waiting for I/O, that kind of thing ?

**Comment by vtnerd** [comment]
Also the [poor mans profiling](https://poormansprofiler.org/) technique might be able to highlight what function is dominating the call.

**Comment by moneromooo-monero** [comment]
FWIW I have pstack on a 4.x kernel.

**Comment by selsta** [comment]
No reply from the issue creator, closing.
