### ISSUE TITLE
Do the docker builds for Android actually work?

### ISSUE THREAD

**Issue by trurebel** [monero-project/monero#6564]
I have MacOS docker and decided to try out the two (32 and 64 bit) docker build scripts, my internet is wobbly so I cannot be 100% I am not to blame, but certainly the 32 bit build fails with something that looks like a bug, though I cannot guess where that comes from.

`Step 43/43 : RUN cd /src     && CMAKE_INCLUDE_PATH="${PREFIX}/include"        CMAKE_LIBRARY_PATH="${PREFIX}/lib"        ANDROID_STANDALONE_TOOLCHAIN_PATH=${TOOLCHAIN_DIR}        USE_SINGLE_BUILDDIR=1        PATH=${HOST_PATH} make release-static-android-armv7 -j${NPROC}
 ---> Running in 32f7228b917f
make: *** No rule to make target 'release-static-android-armv7'.  Stop.`

Got the equivalent message on 64 bit

`Step 43/43 : RUN cd /src     && CMAKE_INCLUDE_PATH="${PREFIX}/include"        CMAKE_LIBRARY_PATH="${PREFIX}/lib"        ANDROID_STANDALONE_TOOLCHAIN_PATH=${TOOLCHAIN_DIR}        USE_SINGLE_BUILDDIR=1        PATH=${HOST_PATH} make release-static-android-armv8 -j${NPROC}
 ---> Running in 10efcd626111
make: *** No rule to make target 'release-static-android-armv8'.  Stop.
The command '/bin/sh -c cd /src     && CMAKE_INCLUDE_PATH="${PREFIX}/include"        CMAKE_LIBRARY_PATH="${PREFIX}/lib"        ANDROID_STANDALONE_TOOLCHAIN_PATH=${TOOLCHAIN_DIR}        USE_SINGLE_BUILDDIR=1        PATH=${HOST_PATH} make release-static-android-armv8 -j${NPROC}' returned a non-zero code: 2`

**Comment by moneromooo-monero** [comment]
release-static-android-armv7 and release-static-android-armv8 are valid targets, so it looks like it's not seeing the right Makefile.

**Comment by hsyia** [comment]
#3039 3039

**Comment by selsta** [comment]
Use `gitian´ to create Android binaries.
