### ISSUE TITLE
daemon rpc `relay_tx` returning code 0, blank message

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#6596]
Since updating to v0.16.0.0, this response is returned from daemon rpc `relay_tx`: `{error={code=0, message=}, id=0, jsonrpc=2.0}`

It works when the daemon is switched back to v0.15.0.5.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6599

**Comment by moneromooo-monero** [comment]
Merged
