### ISSUE TITLE
Segmentation fault on freshly compiled v0.16

### ISSUE THREAD

**Issue by kalibox** [monero-project/monero#6602]
Hi, I've just built the new daemon via pulling the git down and it completed successfully without any errors. Upon running it, it launches OK but crashes out. Error message is:

Segmentation fault 

I have the following switches on and run a local shell script to launch the daemon:

--data-dir 
--rpc-bind-ip
--rpc-bind-port
--confirm-external-bind
--log-level  
--max-log-files 5

Thoughts please?

Thanks

**Comment by kalibox** [comment]
Edit: looking at logs I see this:

2020-05-31 02:18:37.243 E Setting timer on a shut down object

Thanks.

**Comment by kalibox** [comment]
And these:

2020-05-31 02:26:21.783 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:133  Exception: std::runtime_error
2020-05-31 02:26:21.783 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:134  Unwound call stack:
2020-05-31 02:26:21.786 [P2P2]  INFO    stacktrace      src/common/stack_trace.cpp:172      [1]  0x113) [0x5582a544fd50]:__cxa_throw+0x113) [0x5582a544fd50]

**Comment by vtnerd** [comment]
This is very little information. Is it possible to post anything more from the log?

**Comment by kalibox** [comment]
Hi, thanks for the reply. Yes, sure. Let me know what you need and I'll get it for you.

Thanks.

**Comment by moneromooo-monero** [comment]
gdb /path/to/monerod core

Use the path to monerod, and the name of the core file. Might have numbers after it (ig, core.4832).
If your OS does not generate core files:
ulimit -c unlimited
echo core | sudo tee /proc/sys/kernel/core_pattern

Then try again.

Once in gdb after it crashed:

bt

Then post the multi page output.

**Comment by moneromooo-monero** [comment]
And the last ~100 lines of the log.

**Comment by kalibox** [comment]
Thanks. I've not done this before so not sure if I would end up doxxing myself. Does this produce any identifiable information?

**Comment by moneromooo-monero** [comment]
There'll be the path to wherever you put monero. This likely includes your home directory. Feel free to replace it with a placeholder. That should be all.

You do not need to resync the chain (unless it's corrupted somehow, but that's orthogonal to the version).

**Comment by moneromooo-monero** [comment]
ping ?

**Comment by kalibox** [comment]
Hey @moneromooo-monero, we can defo close this issue as v0.17.x has fixed my issues I had with v0.16. All good now. Many thanks.

**Comment by moneromooo-monero** [comment]
Alright, good to know.
