### ISSUE TITLE
bg-mining-miner-target does not seem to get applied.

### ISSUE THREAD

**Issue by ronohara** [monero-project/monero#6604]
2020-05-31 11:21:52.016	I Monero 'Nitrogen Nebula' (v0.16.0.0-release)

With this in the .conf file:

bg-mining-enable=1
bg-mining-ignore-battery=1
bg-mining-miner-target=65
mining-threads=8

mining_status shows..

Smart mining enabled:
  Target: 40% CPU
  Idle threshold: 90% CPU
  Min idle time: 10 seconds
  Ignore battery: yes

The miner Target is the default value, not the parameter setting.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6607
