### ISSUE TITLE
Wallet v0.16 refresh command throwing errors before completed.

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#6605]
When running the refresh command in the CLI wallet v0.16 it will scan a chunk of blocks and then exit with Error: refresh failed: payment required.. Blocks recieved: 29230. When I run the refresh command again it resumes from where it ended with the error but then throws the error again after scanning another chunk of blocks. When I start the wallet it gives error right away:
Error: refresh failed: payment required.. Blocks received 0 
Background refresh thread started 

OS: Centos 8
Kernel: 4.18.0-147.8.1

**Comment by downystreet** [comment]
When I restart the wallet it says 'Starting background refresh...'. Does using the refresh command interfere with this?

**Comment by moneromooo-monero** [comment]
Did you have enough credits for that node to begin with ? It's possible your balance depleted, then you found a good enough hash, which allowed you to get some more blocks.

**Comment by downystreet** [comment]
You have to have credits for your wallet to sync to the blockchain?

**Comment by moneromooo-monero** [comment]
If you're connected to a daemon that requires it, yes. Are you connected to a daemon that requires it ? You can see with "rpc_payment_info".

**Comment by downystreet** [comment]
I'm using my daemon. I have the full blockchain downloaded. rpc_payment_info gives this output:
Using daemon: http://localhost:18081
Payments required for node use, current credits: 250
Credits target: 50000
Credits spent this session:5500
Credit discrepancy this session: 0 (0%)
Difficulty: 1000, 250 credits per hash found, 0.25 credits/hash
Mining for payment at 45.9H/s
Estimated time till 50000 credits target mined: 1 hours

**Comment by moneromooo-monero** [comment]
Odd. The default is to not require payment. And you mentioned you did not know it was possible so you clearly did not set it up. In any case, that daemon appears to be set up to require payment, and your wallet is mining for it, so that explains the refresh stopping and restarting once it's got more credits.
What is your monerod command line ?

**Comment by downystreet** [comment]
I set the daemon to require payment. running --restricted-rpc --rpc-payment-address 49....  --rpc-payment-credits 250 --rpc-payment-difficulty 1000.

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by downystreet** [comment]
Alright I just restarted the daemon and ran it regularly and it syncs fine now. Thanks for the help.

**Comment by moneromooo-monero** [comment]
No bug here, closing.
