### ISSUE TITLE
Wallet v0.16 does not accept date for restore height.

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#6606]
When I restored a wallet with keys and it comes to the restore from height, it is not accepting the date format. I tried 2020-01-01 and it was throwing error.

**Comment by moneromooo-monero** [comment]
You're not saying anything about what prompt or option or anything you're using.

**Comment by downystreet** [comment]
I used the ./monerod --restore-deterministic-wallet. It looks like it only asks this when restoring a wallet and it said something like what height do you want to restore from or you can enter a date in the form of (yyyy-mm-dd). I tried entering 2020-01-01 and (2020-01-01) and it was giving me error.

**Comment by moneromooo-monero** [comment]
I just tried here, and 2020-01-01 works.
```
Restore from specific blockchain height (optional, default 0),
or alternatively from specific date (YYYY-MM-DD): 2020-01-01
Restore height is: 1372596
Is this okay?  (Y/Yes/N/No): 
```
Maybe you're adding some spaces or other characters ? The parsing is unforgiving for this, I'll make it a bit more lenient.

**Comment by downystreet** [comment]
I entered it just like that but I'm thinking maybe my daemon settings were affecting it.

**Comment by moneromooo-monero** [comment]
Paste the actual output please.

**Comment by moneromooo-monero** [comment]
Oh, and make sure you use normal ASCII - signs, not fancy ones.

**Comment by downystreet** [comment]
I just tried it again and it works fine, I don't know what was going on earlier.

**Comment by downystreet** [comment]
Wait I think it is because I'm just running the regular daemon now without all of the rpc payment stuff.

**Comment by moneromooo-monero** [comment]
I don't see why that'd affect the date parsing. Try again with the rpc payment enabled maybe ?

**Comment by downystreet** [comment]
Ok, when I run it with the rpc stuff and use the date to restore it says Error: failed to get blockchain height

**Comment by moneromooo-monero** [comment]
Ah, that explains it :)
Since your wallet does not have credits yet to pay for RPC, the daemon rejects your RPC, and the wallet can't check what height corresponds to which date.
