### ISSUE TITLE
TROJAN after installing CLI Wallet windows 64

### ISSUE THREAD

**Issue by githubnesys** [monero-project/monero#6617]
Hello,

I have just installed CLI WALLET for windows 64.

I have done all pgp verification which worked fine.

However, after unzipping the monero-win-x64-v0.16.0.0.zip

I have been warned by windows defender of those malicious programm appearence :

win32/wacatac.D!ml
win32/wacatac.B!ml
win32/Uwasson.A!ml

I am wondering if this is safe to use CLI WALLET and what is happening generally here?

**Comment by selsta** [comment]
Windows Defender flags the included miner. If you verified the hashes then you can safely ignore it.

**Comment by githubnesys** [comment]
Hello,

can somebody else confirm this ?

This is weird that something is happening in win32 directory whereas all the files I have unzipped must remain in the unzipped folder.

Do you check that some malicious hackers are not participing to the project coding?

**Comment by MaxXor** [comment]
`win32/XXX` are only names for the type of threat. It doesn't mean they are in the win32 directory.

**Comment by githubnesys** [comment]
But those are well-known trojan. how can you explain?

**Comment by erciccione** [comment]
@githubnesys Monero binaries often get labelled as malware (see https://github.com/monero-project/monero-gui/issues/1747). It's a problem and we are currently discussing solutions.

**Comment by trasherdk** [comment]
@githubnesys It would be more fair to ask anti-virus software providers, why they are flagging valid software as well-known trojan malware.

**Comment by githubnesys** [comment]
I know people that have been scammed with https://www.xmrwallet.com which is not reliable. so It is better to be carefull with any software dealing by monero.

The best thing would be to develop a browser based tool like coinb.in for BTC which allow to build transaction offline then to broadcast it. As a result one is sure that private key is not interacting with the web. why this doesn't exist yet for monero??

**Comment by selsta** [comment]
> The best thing would be to develop a browser based tool like coinb.in for BTC which allow to build transaction offline then to broadcast it. As a result one is sure that private key is not interacting with the web. why this doesn't exist yet for monero??

The private key is also not interacting with the web if you use one of the desktop wallets. Also see: https://xmrchain.net/rawtx

**Comment by githubnesys** [comment]
Is NOT interacting with the web what is NOT connected to the web. so forget about desktop wallets.

**Comment by Marticoin** [comment]
monero wallets gui and cli are infected with trojans ~ the downloaded exe's are severe threats, windows defender says .  So how to I safely store xmr on nano s ? Will ledger live hold xmr soon ?

**Comment by erciccione** [comment]
@Marticoin did you read the conversation above before commenting? The Monero binaries don't contain malware.

**Comment by githubnesys** [comment]
can you sign transaction offline with CLI Wallet?

**Comment by moneromooo-monero** [comment]
Yes. See monero.stackexchange.com, which has a list of steps for this.

**Comment by dEBRUYNE-1** [comment]
@githubnesys - See:

https://monero.stackexchange.com/questions/2868/is-there-any-way-to-construct-a-transaction-manually
