### ISSUE TITLE
Integrate RingCT

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero#662]
***Assigned To:*** @warptangent and @fluffypony

***Notes:***

Reference implementation is here: https://github.com/ShenNoether/MiniNero/tree/master/brief

@fluffypony will get some implementation notes from @ShenNoether.

Assigned to @warptangent to do the actual implementation.

To be implemented as a testnet hardfork first, for a later mainnet fork.

**Comment by ShenNoether** [comment]
reference implementation is actually here: https://github.com/ShenNoether/RingCT

**Comment by fluffypony** [comment]
I guess we can close this now - thanks, @ShenNoether and @moneromooo-monero and all others that worked on it:)
