### ISSUE TITLE
Potential soft fork issue

### ISSUE THREAD

**Issue by VanGrx** [monero-project/monero#6620]
Hello,
I am worried about [this handling of exceptions.](https://github.com/monero-project/monero/blob/master/src/cryptonote_core/blockchain.cpp#L3996-L4012)

If a transaction failed here, the txs before the one that failed(and miner tx also) is not removed from the blockchain so that node becomes invalid for the rest of the network.

**Comment by moneromooo-monero** [comment]
If either trigger, this is run:
> m_batch_success = false;
In cleanup_handle_incoming_blocks, if this flag is false, this is run:
> m_db->batch_abort();
which will abort the db txn, so anything tentatively written to the db is discarded.
Do you think there's bug which can make this discard not happen ? If so, can you be more precise ?

**Comment by VanGrx** [comment]
Hello,
Thanks for reply!
Sorry, I checked again and here is [a potential problem that I found.](https://github.com/monero-project/monero/blob/master/src/cryptonote_protocol/cryptonote_protocol_handler.inl#L1477)
As this is the only place where the cleanup is not called right after the handle_incoming_block function it seems like a potential theoretical problem for soft fork. Right?

**Comment by moneromooo-monero** [comment]
Looks like it's called in all cases. Maybe not if an exception happens in the connection dropping or logging I suppose, so some armour plating could be added. Can you see a path where it's not called ?

**Comment by VanGrx** [comment]
[This](https://github.com/monero-project/monero/blob/master/src/cryptonote_protocol/block_queue.cpp#L95) is the assert that I found while doing connection dropping. 

Is there a reason why cleanup is not called right after the handle_incoming_block but actually added in every case of ifs?

**Comment by moneromooo-monero** [comment]
Oooh, that's bad. Aby more info about this assert, like logs ?

The reason why it's not called right after adding is that if you call one block at a time, all the db stuff be slow I think. Batching blocks speeds up.

As for the exception, it looks like it should not leave the db in a bad state: if cleanup is not called, the incoming tx stays locked, and the next call locks up. Meanwhile, the interrupted db txn never gets committed either.

Did you end up with a bad db ?

**Comment by VanGrx** [comment]
`Did you end up with a bad db ?`
Actually no, I am working on a project that is based on monero codebase, so after finding some project-specific issue, I took some time to check if monero project has some theoretical potential issues and wanted to give help to this project if possible. :)

**Comment by moneromooo-monero** [comment]
Appreciated :)

The assert is definitely a bug if you get more info about it.
As for the tx being leftover in the db, I don't think that can happen but if you find a way, please tell.

**Comment by moneromooo-monero** [comment]
I'll be closing this soon if you don't come up with an actual way for it to happen. If you're planning to look into it some more, say so and I'll leave it open.

**Comment by VanGrx** [comment]
I don't think I'll check this more any time soon. I'll close it and when I get time, I'll open an issue with more accurate info. Thank You for all the feedback.
