### ISSUE TITLE
How to view the private key except the primary address

### ISSUE THREAD

**Issue by hitczw** [monero-project/monero#6624]
I have a Monroe wallet and applied for several addresses. When I want to view the private key in the settings, it seems that I can only see the private key of the primary address. Is there any way to see the private key of other addresses in the account? My wallet is created in simple mode, and the new address is added through the "creat a new account" button

**Comment by moneromooo-monero** [comment]
I don't think there is. There's not much point in it. Do you have a use for it ?

**Comment by hitczw** [comment]
Sometimes it takes hours to synchronize data. I want to export the private key to other wallets

**Comment by moneromooo-monero** [comment]
How do you think knowing the subaddress secret keys might help here ?

**Comment by hitczw** [comment]
I used to collect the Monero at my sub address. But when I want to transfer with a sub address, I find that I have to wait a long time to synchronize the data (possibly due to China's network control). I want to export the private key to other wallets, such as monerujo. There is a VPN software on my mobile phone witch can break the network control. But now that the problem is solved, I waited all morning to complete the data synchronization and transfer

**Comment by moneromooo-monero** [comment]
This is not related to the subaddress secret key AFAICT. Do you think it is, and if so, why ?

**Comment by binaryFate** [comment]
You cannot create a new wallet just for a specific existing subaddress of yours. You would have to export the seed and recreate the entire wallet.

Your long sync time has nothing to do with funds being sent to subaddress or not. When your wallet scan the missing blocks (which is probably what you are waiting for), it does not matter to which address the funds are going.

**Comment by fluffypony** [comment]
Subaddresses aren't the same as an HD wallet in Bitcoin.

**Comment by rbrunner7** [comment]
I am not sure, but I think behind this question is a simple assumption: That a single Monero wallet has more than 1 secret key pair (spend key + view key) if there are more addresses than the main address, and/or accounts added.

This assumption is **false**. One Monero wallet always only has one such secret key pair, regardless of how many addresses / subaddresses and accounts are configured and in use. Everything gets derived from **one** secret spend key.

**Comment by UkoeHB** [comment]
Having more subaddresses that own funds in a wallet doesn't affect scanning speed, so building a new wallet out of the subaddress keys would not improve anything afaik.
