### ISSUE TITLE
Sweep_single Trezor not working

### ISSUE THREAD

**Issue by ReadandSweepm** [monero-project/monero#6635]
CLI 16.0 with Trezor then sweep_single not working

Try it (sweep_single unimportant <key image> <destination address>) and you'll get the CLI saying: 
  Error: transaction <txid> was rejected by daemon
  Error: Reason: invalid input
and the daemon saying:
  E Bad key image
  W [on_send_raw_tx]: tx verification failed: invalid input

Suspect trezor because sweep_single perfectly possible with just cli wallet.

**Comment by selsta** [comment]
Are you using the latest Trezor firmware?

**Comment by ReadandSweepm** [comment]
Yes

**Comment by selsta** [comment]
ping @ph4r05

**Comment by ph4r05** [comment]
@selsta thanks for the notification. I will check what I can do. 
@ReadandSweepm are other transaction methods working well?

**Comment by ReadandSweepm** [comment]
> @ReadandSweepm are other transaction methods working well?

Yes

**Comment by ph4r05** [comment]
@ReadandSweepm  thanks for info. OK so it will be problem just in the `sweepp_single`, thats a good sign :)

I will look into in next week probably as this one is quit busy for me.

**Comment by ph4r05** [comment]
@ReadandSweepm just an idea, can you pls try running `hw_key_images_sync` to make sure the key images are computed correctly and then rerun `sweep_single` with the newly computed key image? It would help me diagnose the culprit.

How did you obtain the key image for the UTXO you want to transfer with `sweep_single`?

**Comment by ReadandSweepm** [comment]
This should be easy to reproduce. Are you able to?

**Comment by ph4r05** [comment]
@ReadandSweepm I was looking at it but haven't finished it at the moment. I will get to that soon. (it took quite some time to sync all the projects and setup the local testnet)

**Comment by ph4r05** [comment]
It seems the `sweep_single` does not even hit the Trezor, the generated transaction returns key image `0100000000000000000000000000000000000000000000000000000000000000` which is obviously wrong (probably due to zero spending key).

The fix should be quite easy. I will look into it later next week.

**Comment by ph4r05** [comment]
I consider this issue fixed as #6677 and #6681 are fixing it and @selsta tested it (thanks!)

**Comment by ReadandSweepm** [comment]
Thanks for fixing this, confirmed it works. I noticed from the release note you fixed it thanks much
