### ISSUE TITLE
request for more log info on i2p connections by default

### ISSUE THREAD

**Issue by MoneroArbo** [monero-project/monero#6640]
Here is a [bitmonero.log](https://github.com/monero-project/monero/files/4764401/bitmonero.log.txt) snippet from this morning. 

Viewing this log, it is impossible for me to tell when I actually have an outbound i2p connection I can send transactions over. If there were log entries saying when outbound i2p connections go from 0 to >0, it would be really helpful.

I suppose if #6631 and #6590 were fixed this would be less of an issue, but I still think it would in general be good to report when the state that caused a warning has ended.

**edit:** Okay so apparently you can call for example 'print cn' on a detached daemon by running 'monerod print_cn'. Gonna refrain from closing this because it still seems maybe good to report when a state that causes a warning ends?

But like, not a big deal. Feel free to close.

**Comment by selsta** [comment]
Closing this, both issues you linked should be resolved in v0.18.0.0.
