### ISSUE TITLE
Monerod report

### ISSUE THREAD

**Issue by Cideg** [monero-project/monero#6649]
does anyone know what that means in the deamon

2020-06-12 18:47:01.761 I END DUMP
2020-06-12 18:47:01.761 I Please send moneromooo on Freenode the contents of this log, from a couple dozen lines before START DUMP to END DUMP

**Comment by moneromooo-monero** [comment]
It means the log contains information to help debug a particular issue that you experienced, and that START DUMP and END DUMP mark the start and end of that information, and that I would like to get that information. Please either paste it here, or on a paste site (without javascript, does not reject tor), or send it to moneromooo on Freenode. Please also try to inlcude a couple dozen lines before the START DUMP line, in case there's interesting things going on before the trigger.

**Comment by Cideg** [comment]
@moneromooo-monero
https://paste.ubuntu.com/p/BCTzXqSzdX/

**Comment by moneromooo-monero** [comment]
Thanks, you can paste from the start marker (a few dozen lines before it even).

**Comment by Cideg** [comment]
https://paste.ubuntu.com/p/RbRSFNMJVV/

**Comment by Cideg** [comment]
> Danke, können Sie von der Startmarkierung aus einfügen (ein paar Dutzend Zeilen davor sogar)?
https://paste.ubuntu.com/p/RbRSFNMJVV/

**Comment by moneromooo-monero** [comment]
Thanks.
Can you paste the entirety of the data between START DUMP and END DUMP ? 
If it's too large, it can go on a temp git repo.

**Comment by Cideg** [comment]
https://github.com/Cideg/Monero-log/blob/master/dump.log

**Comment by moneromooo-monero** [comment]
Excellent, thanks!
Hopefully that'll help me fix this bug.
In the meantime, your blockchain probably has an incorrect difficulty value.
You may to pop 1000 blocks and let it resync those:
pop_blocks 1000

**Comment by Cideg** [comment]
OK thank you,

I will sync again with:

/ monero-blockchain-import - pop_blocks 20000

**Comment by moneromooo-monero** [comment]
The logs were very useful, thanks. I think I fixed the bug, see https://github.com/monero-project/monero/pull/6650

**Comment by selsta** [comment]
Fix has been merged.
