### ISSUE TITLE
CLI Wallet v0.16.0.0-Error: failed to generate new wallet: failed to save file "test.keys"

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#6654]
OS: CentOS 8, CLI-wallet verion: v0.16.0.0 
After downloading the Monero CLI from getmonero.org and starting up the wallet I go through the various steps of name and password, once it gets to the point where it asks you what language you you want and you enter a number and hit enter, the wallet exits with error code: Error: failed to generate new wallet: failed to save file "test.keys". I just downloaded this same file on my main computer without any problems and yet when I download it to the server it fails with error. Both computers are CentOS 8 with the only difference being that the server has no GUI.

**Comment by moneromooo-monero** [comment]
Are you sure you have write permissions on that directory for the user you're running as ?

**Comment by downystreet** [comment]
Ok, you are correct, for some reason the directory didn't have write permissions. The wallet appears to be working normally as well.
