### ISSUE TITLE
Failed to commit a transaction to the db: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid                      

### ISSUE THREAD

**Issue by Pibacco** [monero-project/monero#6655]
data.mdb was corrupted from sleep cycle, please close issue.

**Comment by dEBRUYNE-1** [comment]
You can close it yourself (please check the interface, there should be a button to close it). In case anyone else stumbles upon this, please see:

https://monero.stackexchange.com/questions/6586/daemon-shuts-down-on-startup-mdb-bad-txn-transaction-must-abort-has-a-child
