### ISSUE TITLE
Device and cryptonote_basic cyclic dependency, debug build fails

### ISSUE THREAD

**Issue by ph4r05** [monero-project/monero#6666]
Debug compilation (with shared lib compilation) fails due to the: 

```
[ 95%] Linking CXX shared library libdevice.dylib
Undefined symbols for architecture x86_64:
  "cryptonote::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&)", referenced from:
      hw::core::device_default::get_transaction_prefix_hash(cryptonote::transaction_prefix const&, crypto::hash&) in device_default.cpp.o
ld: symbol(s) not found for architecture x86_64
```

The problem is that the `device` module contains `device_default` and `device_ledger` while those are using `cryptonote_basic` functions. `cryptonote_basic` depends on the `device` module (probably due to the interfaces defined in the module). So `device` cannot depend on the `cryptonote_basic` to fix the compilation error as the cyclic dependency would be created.

A similar problem happened to me several times. It would be maybe better to leave only basic interfaces in the `device` and separate implementations to a new module which could depend on the `cryptonote_basic` and other modules.

What do you think @moneromooo-monero @selsta ?
(I am aware that statical linking is a valid workaround)

**Comment by moneromooo-monero** [comment]
Is this a new change ?

**Comment by ph4r05** [comment]
I am getting this error on master b3d6382d406e660b1d4ad503d63bfae89056925c on `make debug`. Can you pls reproduce it?

**Comment by moneromooo-monero** [comment]
Unlikely, it only showed up on Mac before.

**Comment by ph4r05** [comment]
Ah interesting. It is happening on Mac/clang, true. I've just checked that GCC 8.3.0 passes without problems.

**Comment by xmrdsc** [comment]
can reproduce on master 5d850dde99ca282d2c6f9a1b1eb00a3812cb15be, osx, `-DCMAKE_BUILD_TYPE=Debug`, `Apple LLVM version 10.0.1 (clang-1001.0.46.3)`

**Comment by KamiD** [comment]
it can reproduce on https://github.com/monero-project/monero/commit/76cc82c29234fc2805f936f0fc53d48acc9cedf7 under macos 10.15.3, gcc version is 4.2.1

**Comment by KamiD** [comment]
it alos reproduced even i upgrade gcc to 7.2.5

**Comment by akildemir** [comment]
getting the same error on mac os building in debug. Is there quick fix?
