### ISSUE TITLE
monero gui win64 install suggested download hash does not match

### ISSUE THREAD

**Issue by drinkyd** [monero-project/monero#6680]
I'm getting a different hash. Could there be a error on the hash page? D/L from the gui suggestion link.

**Comment by selsta** [comment]
Which hash are you getting and which hash is getting displayed? Seems ok here.

**Comment by drinkyd** [comment]
From this site: https://web.getmonero.org/downloads/hashes.txt

0820aeb30b39bb86b550ff5d6e641c16491cff3cff2b9ab9873bdc05acc6a041  monero-gui-install-win-x64-v0.16.0.0.exe

After I run "certUtil -hasfile monero-gui-install-win-x64-v0.16.0.0.exe" in CMD, I get this: 

SHA1 hash of monero-gui-install-win-x64-v0.16.0.0.exe:
43626772be9503770d0499f5030c5130ff4ffcb4
CertUtil: -hashfile command completed successfully.

Am I doing it wrong?

**Comment by selsta** [comment]
You are comparing SHA1 and SHA256

**Comment by drinkyd** [comment]
How do I compare the SHA256?

**Comment by xiphon** [comment]
> How do I compare the SHA256?

`certutil.exe -hashfile monero-gui-install-win-x64-v0.16.0.0.exe SHA256`
