### ISSUE TITLE
Why are clients connected to my node not paying any rpc hashes?

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#6682]
When running the monero daemon and using the rpc_payments command it produces a long list of 403 clients. All of these clients have paid 0 hashes except for my own wallet. I was trying to find some information on this and the only thing I found was saying that the rpc payments function was not integrated into the gui wallets yet? I just wanted to make sure that everything is functioning normally here and I'm not leaving out some command that is causing connected clients to not mine hashes.

**Comment by moneromooo-monero** [comment]
I expect most people to not want to pay anything. For now, they'll use another free node. Hopefully there will be fewer of those,and ultimately none, pushing those people to either pay or use their own. That might take time though.

AFAIK the GUI does not have this system yet.
