### ISSUE TITLE
Bug in the GUI using IPV6 

### ISSUE THREAD

**Issue by luisan00** [monero-project/monero#6684]
#### Setup in the remote daemon is:
- daemon version: `monero-x86_64 linux-gnu-v0.16.0.0`
- IP address: `fc00:db9::1` 
```
# monerod.conf
public-node=1
rpc-use-ipv6=1
rpc-bind-ip=0.0.0.0                                         
rpc-bind-ipv6-address=::0                                     
rpc-restricted-bind-port=18089  
confirm-external-bind=1
```
#### In my computer:
- GUI version: `monero-x86_64 linux-gnu-v0.16.0.0`
- IP address: `fc00:db8::1`

#### Steps: 

- Run the GUI
- Click on `Remote Node` under `node` tab
- Set address to:  `[fc00:db9::1]`, port to: `18089` and click on `connect`

The connection seems successful, but the fields `address` and `port` are not showing the right info, so please look at the screen capture.

![image](https://user-images.githubusercontent.com/10358374/85338460-9e51f000-b4e2-11ea-8c57-d49df11adc1f.png)

**Note**: if we put the address without `[]`, the connection doesn't seem to be successful

**Comment by SomaticFanatic** [comment]
The GUI is in a different repo: https://github.com/Monero-project/Monero-gui

**Comment by luisan00** [comment]
Open: https://github.com/monero-project/monero-gui/issues/2971

**Comment by luisan00** [comment]
Wrong repo, the issue was moved to Monero-Gui  repo.
