### ISSUE TITLE
Internal wallet error, casting problem

### ISSUE THREAD

**Issue by grcasanova** [monero-project/monero#6699]
Compiled _monero_ project on Mac OSX, started the daemon and the wallet roc, as soon as I run "open wallet" I get:
_E static_cast<uint8_t>(m_nettype) != field_nettype. THROW EXCEPTION: error::wallet_internal_error_

The wallet exists and can be opened on another computer, what's wrong with this newer install?

**Comment by sumogr** [comment]
You are trying to run a wallet created on testnet on mainnet or vice versa.

**Comment by grcasanova** [comment]
no I'm running both the daemon and the wallet rpc on testnet, I think it has something to do with boost libraries being updated a few days ago

**Comment by sumogr** [comment]
both daemon and rpc are run with the --testnet flag on right? what boost libraries?

**Comment by grcasanova** [comment]
Yes flag on both. I solved with reinstalling boost, apparently brew didn't fetch dependencies correctly.
