### ISSUE TITLE
Missing payment in show_transfers

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero#670]
From villabacho on BCT (https://bitcointalk.org/index.php?topic=583449.msg13886614#msg13886614):

Hi, I just noticed that the amounts reported by the two simplewallet commands

1) "show_transfers in"
2) "incoming_transfers"

do not sum up to the same value. The second one sums to the same value as what "balance" says (I didn't have any outgoing transfers from this wallet),
while the first one is missing one transaction with two outputs.

I'd like to use the first of the to commands as it nicely groups the outputs of each transaction and tells me the block height as well,
but if it misses transactions I'll have to stick with the second one for now.

Anything that I should know? Is the "show_transfers" command kind of experimental?

Thanks!

**Comment by moneromooo-monero** [comment]
One enumerates the outputs, the other enumerates the per tx sums (for received), or something else for sent, can't recall just now. so incoming_transfers is authoritative, in case of discrepancy.

**Comment by luigi1111** [comment]
@moneromooo-monero Is this still relevant? :)

**Comment by moneromooo-monero** [comment]
Well... Assuming it wasn't user error, I don't think anything was fixed there, so it'd probably still be relevant. Stuff changed though, so it could be something got fixed "by mistake" :) If you want to close this, I'm fine with it.

**Comment by moneromooo-monero** [comment]
While trawling through the bug list, I'm now reminded that show_transfers will only show transfers when scanned with code after this patch was merged. This could very well be the reason for the difference.

**Comment by moneromooo-monero** [comment]
That was most likely that. There was also a more recent bug with the "refresh from height" being subject to underflow, but this got added later. Since I never saw this and the code seems to preclude it, I'll call it invalid.

+invalid
