### ISSUE TITLE
 monerod is crashing  when solo mining

### ISSUE THREAD

**Issue by maogo** [monero-project/monero#6704]
2020-07-12 15:33:34.053	11120	INFO	logging	contrib/epee/src/mlog.cpp:273	New log categories: *:WARNING,net:FATAL,net.http:FATAL,net.ssl:FATAL,net.p2p:FATAL,net.cn:FATAL,daemon.rpc:FATAL,global:INFO,verify:FATAL,serialization:FATAL,daemon.rpc.payment:ERROR,stacktrace:INFO,logging:INFO,msgwriter:INFO

**Comment by moneromooo-monero** [comment]
Do you have a stack trace for the crash ?

**Comment by maogo** [comment]
and sometimes got this:
![6UXM7_0N2)~S6D@V$6QZDVW](https://user-images.githubusercontent.com/20197997/87252614-0cb51d00-c4a7-11ea-9f31-1eb8bbdff5fc.png)

**Comment by trasherdk** [comment]
Looks like a pruned blockchain. Mine does the same, but everything seems to work.
```
2020-07-12 18:06:42.096        E   failed to find tx meta
2020-07-12 18:06:42.096        E   failed to find tx meta
2020-07-12 18:06:42.096        E   failed to find tx meta
2020-07-12 18:06:42.096        E   failed to find tx meta
2020-07-12 18:06:42.096        E   failed to find tx meta
2020-07-12 18:06:42.096        E   failed to find tx meta
2020-07-12 18:06:42.096        E   failed to find tx meta
status 
Height: 621501/621501 (100.0%) on stagenet, not mining, net hash 1.27 kH/s, v12, 3(out)+4(in) connections, uptime 6d 12h 24m 57s
```

**Comment by moneromooo-monero** [comment]
You can ignore the meta message, it's harmless.

**Comment by maogo** [comment]
> Do you have a stack trace for the crash ?

I can't debug , is there any other way?

**Comment by maogo** [comment]
> Looks like a pruned blockchain.  
 local blockchain DB is full

**Comment by moneromooo-monero** [comment]
What platforn is it running on ?

**Comment by maogo** [comment]
> What platforn is it running on ?

Windows 10 professional  64 bit , version number 2004.   v0.15 work well .

**Comment by moneromooo-monero** [comment]
Is it a Ryzen CPU ?

**Comment by maogo** [comment]
Yes , Ryzen 1800X

**Comment by moneromooo-monero** [comment]
Some Ryzen CPUs are known to be buggy in a way that makes them crash on randomx. IIRC there may be a workaround to do with disabling something to do with micro-op caching. I'll ask around.

**Comment by SChernykh** [comment]
> Some Ryzen CPUs are known to be buggy in a way that makes them crash on randomx. IIRC there may be a workaround to do with disabling something to do with micro-op caching. I'll ask around.

Disabling opcache in BIOS helps.

**Comment by maogo** [comment]
I  have  disabled opcache  control in BIOS  but look the same.

**Comment by SChernykh** [comment]
The opcache fix is only for when it crashes during mining.

**Comment by maogo** [comment]
Within seconds the monerod will crash

**Comment by SChernykh** [comment]
Disabling opcache should've helped. You can try solo mining with XMRig, it supports mining directly to monerod and it has a fix for this crash.

**Comment by SomethingGettingWrong** [comment]
> > Some Ryzen CPUs are known to be buggy in a way that makes them crash on randomx. IIRC there may be a workaround to do with disabling something to do with micro-op caching. I'll ask around.
> 
> Disabling opcache in BIOS helps. Or running without JIT.

Ryzen Cpu's are like the "ONLY" profitable Cpu's for the most part. if you disable micro-op caching the proccesor will be bad at everything else  and only good FOR mining. which means if you want to only dedicate a percentage of your cores to solo your pc will be much slower. thats a shame.  why is it only some ryzen cpu's? 
Which one should i avoid if i wnat to mine monero solo?

**Comment by SChernykh** [comment]
>  why is it only some ryzen cpu's?

There's a hardware bug in some early 1st-gen Ryzen CPUs, but not all of them. XMRig has a workaround for it and can mine even with enabled opcache.

**Comment by moneromooo-monero** [comment]
Would you mind adding the workaround to monerod ? It'd be a shame if someone people can't solo mine and are forced to use pools in order to mine :)

**Comment by SChernykh** [comment]
@moneromooo-monero It's quite invasive workaround and it messes with low-level exception handling. It made sense in a specialized miner software for performance reasons, but I think it's not worth adding it to monerod for just a small fraction of 1st-gen Ryzens. Besides, that crash was always fixed by disabling opcache, so I'm not sure if it's the same crash here.
