### ISSUE TITLE
Can't exit from password prompt

### ISSUE THREAD

**Issue by benmoss** [monero-project/monero#6725]
When the CLI becomes locked due to inactivity, it presents a password prompt. Often I just want to exit the program rather than re-enter my password to unlock, but I can't seem to by the normal ways I know how. Both Ctrl-C (SIGINT) and Ctrl-D (EOF) just result in "Error: failed to read wallet password". In filing this bug I learned that Ctrl-\ is also a thing and sends SIGQUIT, which does in fact work.

**Comment by selsta** [comment]
Are you using screens / ssh?

**Comment by benmoss** [comment]
No, not using any muxer thing, and yeah readline normally works. Ctrl-C does work on the initial password prompt when I load the CLI as well. Probably worth mentioning this is against `Monero 'Nitrogen Nebula' (v0.16.0.0-25419b4bf)`

**Comment by benmoss** [comment]
[![asciicast](https://asciinema.org/a/349968.svg)](https://asciinema.org/a/349968)

**Comment by selsta** [comment]
https://github.com/monero-project/monero/issues/6192

**Comment by benmoss** [comment]
Closing as duplicate, thanks @selsta
