### ISSUE TITLE
Transaction sanity check failed with a larger amount TX

### ISSUE THREAD

**Issue by Lafudoci** [monero-project/monero#6726]
When I was trying to move all funds from my old wallet to a new one, it showed `internal error: Transaction sanity check failed`. I've tried to delete wallet cache, recover a new wallet from 25 words and change different remote nodes. None of them worked.

But when I sent a smaller amount likes 1 XMR instead, the TX went through without any issue.

Here is the log, any idea?
https://pastebin.ubuntu.com/p/xPWvhG3vgn/

**Comment by selsta** [comment]
Can you try to do a transaction and if it fails do the following:

`unset_ring <txid>`

and then try again?

**Comment by Lafudoci** [comment]
> Can you try to do a transaction and if it fails do the following:
> 
> `unset_ring <txid>`
> 
> and then try again?

Could you please explain more? The failed tx didn't provide txid.

**Comment by moneromooo-monero** [comment]
From the message, it's failing to even create a tx, it's the wallet failing before actually making a tx, not the daemon. xiphon added retry code, but it looks like it's failing this, which seems very very unlikely, so there is probably a bug in this code.

**Comment by Lafudoci** [comment]
> From the message, it's failing to even create a tx, it's the wallet failing before actually making a tx, not the daemon. xiphon added retry code, but it looks like it's failing this, which seems very very unlikely, so there is probably a bug in this code.

I see. Is there a temporary workaround that I can move all my fund? Will splitting into small amount txs do the trick?

**Comment by selsta** [comment]
Please see #6815, might be related.

**Comment by Lafudoci** [comment]
> Please see #6815, might be related.

Yes, I finally got my XMR successfully sent. The issue was resolved by PR 6815. Thank you.
