### ISSUE TITLE
Use the Monroe wallet node command "create"_ It takes 10 minutes to create a sub address. What's the problem?

### ISSUE THREAD

**Issue by niukouMan** [monero-project/monero#6730]
Use the Monroe wallet node command "create"_ It takes 10 minutes to create a sub address. What's the problem?

**Comment by selsta** [comment]
Can you give more infos?

Which version are you using?

Which OS?

Are you using Ledger / Trezor?

What kind of hardware?

**Comment by moneromooo-monero** [comment]
There is not create. Do you mean create_wallet, create_address, create_account ?
I assume this is RPC. Can you post the JSON you're sending ?

**Comment by niukouMan** [comment]
> 您可以提供更多信息吗？
> 
> 您正在使用哪个版本？
> 
> 哪个操作系统？
> 
> 您在使用Ledger / Trezor吗？
> 
> 什么样的硬件？



> There is no create. Do you mean create_wallet, create_address, create_account ?
> I assume this is RPC. Can you post the JSON you're sending ?

Use the "Create Address" RPC command

**Comment by niukouMan** [comment]
Use the "Create Address" RPC command but It takes 10 minutes for the node to respond to the result

**Comment by niukouMan** [comment]
> There is no create. Do you mean create_wallet, create_address, create_account ?
> I assume this is RPC. Can you post the JSON you're sending ?

i use the "Create Address" RPC command It takes 10 minutes for the node to respond to the result

**Comment by niukouMan** [comment]
> > 您可以提供更多信息吗？
> > 您正在使用哪个版本？
> > 哪个操作系统？
> > 您在使用Ledger / Trezor吗？
> > 什么样的硬件？
> 
> > There is no create. Do you mean create_wallet, create_address, create_account ?
> > I assume this is RPC. Can you post the JSON you're sending ?
> 
> Use the "Create Address" RPC command

The operating system is Ubuntu and the XMR node is 16.0.1

**Comment by niukouMan** [comment]
> Can you give more infos?
> 
> Which version are you using?
> 
> Which OS?
> 
> Are you using Ledger / Trezor?
> 
> What kind of hardware?

The operating system is Ubuntu and the XMR node is 16.0.1 ,

**Comment by niukouMan** [comment]
> Can you give more infos?
> 
> Which version are you using?
> 
> Which OS?
> 
> Are you using Ledger / Trezor?
> 
> What kind of hardware?

The operating system is Ubuntu and the XMR node is 16.0.1
Use the RPC command to call the node's "create Address" command and wait 10 minutes to respond to the result

**Comment by moneromooo-monero** [comment]
Which account_indes are you trying to create ? Is it a very large number ?

**Comment by niukouMan** [comment]
> account_index

account_index is 0

**Comment by selsta** [comment]
Please try the latest version.

Closing as there were no other reports about this, so could be some issue with the local system. If you continue to have this issue comment here and I can reopen the issue.
