### ISSUE TITLE
monero-blockchain-stats underreports size of prunable txs

### ISSUE THREAD

**Issue by hyc** [monero-project/monero#6732]
Patch coming shortly

**Comment by intj440** [comment]
monero-blockchain-stats output for 2020-07-28: Txs/day = 8976, Bytes/day = 3781848.  The ratio is 421 bytes/tx which is ~4-5x smaller than expected (~1.9kB and ~2.5kB for 1in-1out and 2in-2out txs per @SarangNoether).  Coinbase txs could not explain this as they were <10% of the tx for that day (Blocks/day = 760).
