### ISSUE TITLE
xmr节点生成新的地址耗时5分钟

### ISSUE THREAD

**Issue by yzn5555** [monero-project/monero#6743]
节点进入命令行执行address new 执行结果耗时较长，
服务是：4核 16G
但是在执行生成地址操作的时候发现cpu使用率在单核100%，总使用率最高25%，想问下服务器多个有使用多核的办法吗？

**Comment by ZRFLDF** [comment]
对于我来说，生成地址功能几乎是瞬间完成的，几乎不占用CPU。
服务器多个什么意思？多个核心吗？你如果没有手工设置  --max-concurrency ，钱包应该默认CPU多线程并行计算。

你用的什么操作系统还有确定CLI钱包占用的CPU？

**Comment by yzn5555** [comment]
我是用的是ubuntu1.18版本的 
操作步骤：1、使用monero-wallet-cli进入命令行    2、在命令行执行address new     执行完这个服务器cpu会突然暴增，但是4核服务器cpu使用率达到25%就无法增高了，通过top命令查看程序cpu使用率发现
![企业微信截图_15966181312171](https://user-images.githubusercontent.com/36029121/89411033-510aa480-d757-11ea-8941-17be16e8e98a.png)
