### ISSUE TITLE
[P2P8]  ERROR   default src/common/threadpool.cpp:118   wait should have been called before waiter dtor - waiting now

### ISSUE THREAD

**Issue by LordSquigles** [monero-project/monero#6744]
Every time, just before finishing syncing, I get this error, "[P2P8]  ERROR   default src/common/threadpool.cpp:118   wait should have been called before waiter dtor - waiting now." I have built and rebuilt the source, downloaded the build from the getmonero page and am yet to not get this error, which is preventing me from syncing.

Here is a Reddit thread where somebody experienced the same issue: https://www.reddit.com/r/monerosupport/comments/hm0sck/error_cli_01601_nitrogen_nebula_released/.

I am on Ubuntu 18.04.4, using monero 0.16 and am very stuck. Any help would be appreciated! Thanks.

**Comment by moneromooo-monero** [comment]
Can you detail the circumstances for how to get this ?

**Comment by LordSquigles** [comment]
Sure. I am running monerod as a systemd service with torsocks. However, I don't think the issue is with torsocks, as I got the same error before using it. I've attached the monerod.service file, monerod.config file, and monerod.log file (pasted into text documents).



[monerod.config.txt](https://github.com/monero-project/monero/files/5029616/monerod.config.txt)

[monerod.service.txt](https://github.com/monero-project/monero/files/5029717/monerod.service.txt)

[monerod.log.txt](https://github.com/monero-project/monero/files/5029612/monerod.log.txt)



I am running Ubuntu (bionic beaver 18.04.4) on a VMware virtual machine and using the latest release of monero (nitrogen nebula 0.16).

**Comment by LordSquigles** [comment]
Any luck finding immediate issues? If there's any more information that you need, feel free to ask

**Comment by moneromooo-monero** [comment]
I've not looked at it yet, sorry.

**Comment by moneromooo-monero** [comment]
Can you try again, and once it's stuck:

gdb /path/to/monerod \`pidof monerod\`   (replace the path with the actual path)
thread apply all bt

And post the multi-page results.

**Comment by LordSquigles** [comment]
Will do. Not at my computer at the moment. I will post the output later. Thanks

**Comment by LordSquigles** [comment]
Here you go:

[gdb.txt](https://github.com/monero-project/monero/files/5048343/gdb.txt)

**Comment by moneromooo-monero** [comment]
Do you see any exception in the log file thrown shortly before this ?

**Comment by LordSquigles** [comment]
No. Log is the same as the one I sent you. Would you like me to log with a higher verbosity?

**Comment by moneromooo-monero** [comment]
No, it would appear at default.

**Comment by LordSquigles** [comment]
Log looks just like the one I posted earlier

**Comment by moneromooo-monero** [comment]
I might have found it. Does the following patch fix it ?

```
diff --git a/src/ringct/rctSigs.cpp b/src/ringct/rctSigs.cpp
index 2e3e7007e..7a2bb39da 100644
--- a/src/ringct/rctSigs.cpp
+++ b/src/ringct/rctSigs.cpp
@@ -1056,6 +1056,7 @@ namespace rct {
         }
         if (!proofs.empty() && !verBulletproof(proofs))
         {
+          waiter.wait(&tpool);
           LOG_PRINT_L1("Aggregate range proof verified failed");
           return false;
         }
```

**Comment by LordSquigles** [comment]
Sorry, I accidentally deleted the blockchain file. I will tell you if this worked when it is done syncing (or I get the same error). Thanks

**Comment by LordSquigles** [comment]
I added the line of code, rebuilt everything, and unfortunately got the same error. Would you like me to sync from the start with the new code? Is there anything else I can do to help?

**Comment by moneromooo-monero** [comment]
Don't sync from start, please try to keep the state as unchanged as you can. I guess I'm going to make a patch that logs everything about the threadpool and hope it'll shed some light on the bug.

**Comment by LordSquigles** [comment]
Sounds good.

**Comment by moneromooo-monero** [comment]
https://paste.debian.net/hidden/aff321af/

This will spam stdout, hopefully it locks up fast for you.

**Comment by LordSquigles** [comment]
Alright, I rebuilt with all the patches, and sent stdout to the file below:

[stdout.txt](https://github.com/monero-project/monero/files/5059416/stdout.txt)

**Comment by moneromooo-monero** [comment]
Can you get me the same, but from the log file ? It's got extra thread info.

**Comment by LordSquigles** [comment]
Sure. Here is the log file:

[monerod.log](https://github.com/monero-project/monero/files/5059648/monerod.log)

**Comment by moneromooo-monero** [comment]
Please apply this patch on top of what you have already applied:

```
diff --git a/src/common/threadpool.cpp b/src/common/threadpool.cpp
index a1737778c..f1cf50ddf 100644
--- a/src/common/threadpool.cpp
+++ b/src/common/threadpool.cpp
@@ -166,7 +179,8 @@ void threadpool::run(bool flush) {
     lock.unlock();
     ++depth;
     is_leaf = e.leaf;
-    e.f();
+    try { e.f(); }
+    catch (const std::exception &e) { try { MERROR("Exception in threadpool job: " << e.what()); } catch (...) {} }
     --depth;
     is_leaf = false;
 
```

Then run again, and post the log file again.

**Comment by LordSquigles** [comment]
Here you go:

[monero3.txt](https://github.com/monero-project/monero/files/5060099/monero3.txt)

**Comment by moneromooo-monero** [comment]
Did it fix it ?

**Comment by LordSquigles** [comment]
The error went away! But, now I have this one: "E Exception in threadpool job: mprotect failed."

**Comment by moneromooo-monero** [comment]
Are you sure it's still breaking, and you waited a bit to see if it'd continue ?

**Comment by moneromooo-monero** [comment]
Ah, I see. Try running with: MONERO_RANDOMX_UMASK=16

**Comment by LordSquigles** [comment]
I added the, "--MONERO_RANDOMX_UMASK=16," flag. But, unfortunately still got the same error (mprotect failed). I will give it some time to see if its hanging there. Let me know of there is any more detailed information you would like. Thanks

**Comment by moneromooo-monero** [comment]
It's an enviroment variable. Run like this;
MONERO_RANDOMX_UMASK=16 ./monerod --whatever

**Comment by LordSquigles** [comment]
Silly me! I built another source, passing,"MONERO_RANDOMX_UMASK=16," as an environment variable, and with just the first and last patches (not the ones for more detailed stdout), so that I could get more focused logging. I seem to still get the, "E Exception in threadpool job: mprotect failed," error. Here is my log:

[monero4.txt](https://github.com/monero-project/monero/files/5064063/monero4.txt)

I noticed this exception:

2020-08-12 15:58:57.943	[P2P8]	INFO	stacktrace	src/common/stack_trace.cpp:133	Exception: std::runtime_error

Any idea of what might be causing this? Thanks a lot for your patience and the fantastic help.

**Comment by moneromooo-monero** [comment]
What is your exact command line ?

**Comment by LordSquigles** [comment]
I am running it as a systemd service:

[monerod.service1.txt](https://github.com/monero-project/monero/files/5064997/monerod.service1.txt)

**Comment by LordSquigles** [comment]
Just realized it was the, "MemoryDenyWriteExecute=true," line in my systemd service file. Not an issue with monero. Apologies. Thanks alot for your amazing help. After applying the two patches, it syncs fine. Will these patches be implemented in a future version of monero, or is this issue uniquely mine?

**Comment by moneromooo-monero** [comment]
They will be, though they would not fix the systemd stuff by themselves, they're still good to have.

**Comment by LordSquigles** [comment]
Great. Again, thanks for the help. Really appreciated

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6757
