### ISSUE TITLE
Compiling Master Error

### ISSUE THREAD

**Issue by italocoin-project** [monero-project/monero#6764]
When i compile the master i get this error

`[ 11%] Building CXX object external/qrcodegen/CMakeFiles/qrcodegen.dir/QrCode.cpp.o
In file included from /usr/include/c++/5/array:35:0,
                 from /root/monero/external/qrcodegen/QrCode.hpp:26,
                 from /root/monero/external/qrcodegen/QrCode.cpp:32:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
`

**Comment by selsta** [comment]
Which compiler are you using?

**Comment by italocoin-project** [comment]
> Which compiler are you using?

Hi, here is the compiler

`c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
and cmake version 3.5.1`

**Comment by selsta** [comment]
As an easy workaround use a newer compiler.

To properly fix this I think the CMake file needs a change.

**Comment by italocoin-project** [comment]
> As an easy workaround use a newer compiler.
> 
> To properly fix this I think the CMake file needs a change.

i need this compiler so i can't change it

**Comment by sumogr** [comment]
@italocoin-project at external/qrcodegen/CMakeLists.txt change this
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")`
into
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++11 -O2")`

**Comment by italocoin-project** [comment]
> @italocoin-project at external/qrcodegen/CMakeLists.txt change this
> `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")`
> into
> `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++11 -O2")`

Hi thanks for the help, i know how to fix it i was just raising the issue to be fixed.

**Comment by sumogr** [comment]
> > @italocoin-project at external/qrcodegen/CMakeLists.txt change this
> > `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")`
> > into
> > `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++11 -O2")`
> 
> Hi thanks for the help, i know how to fix it i was just raising the issue to be fixed.

open a PR then ;)

**Comment by italocoin-project** [comment]
> > > @italocoin-project at external/qrcodegen/CMakeLists.txt change this
> > > `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")`
> > > into
> > > `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++11 -O2")`
> > 
> > 
> > Hi thanks for the help, i know how to fix it i was just raising the issue to be fixed.
> 
> open a PR then ;)

i've fixed it exactly how you wrote it above, i don't know if it would work fine on other Cmake/c++ versions tho

**Comment by selsta** [comment]
@italocoin-project 

Can you check if #6766 solves the issue?

**Comment by italocoin-project** [comment]
> @italocoin-project
> 
> Can you check if #6766 solves the issue?

Works fine!
