### ISSUE TITLE
Build fails with Boost 1.74

### ISSUE THREAD

**Issue by 00-matt** [monero-project/monero#6765]
* Boost 1.74.0
* GCC 9.3.0
* Monero c108c5e (also happens with latest release, v0.16.0.3)

##### Logs

[build.log](https://github.com/monero-project/monero/files/5080500/build.log)
[configure.log](https://github.com/monero-project/monero/files/5080501/configure.log)

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6767
