### ISSUE TITLE
signed binaries - trust verification

### ISSUE THREAD

**Issue by skironDotNet** [monero-project/monero#6776]
I think any new member's key should be generated and signed by **fluffypony.asc** as trusted signature
It would be easier to trust 6 year old key. 
Now if hackers or gov got access to git repo they can upload any pgp key and sign binaries with that key, all nice and matching but how the community can be sure the whole project hasn't been corrupted recently?

gpg --verify hashes.txt
gpg: Signature made Thu 13 Aug 2020 11:39:27 AM CDT
gpg:                using RSA key 81AC591FE9C4B65C5806AFC3F0AF4D462A0BDF92
gpg: Good signature from "binaryFate <binaryfate@getmonero.org>" [unknown]
gpg: WARNING: **This key is not certified with a trusted signature!**
gpg:          **There is no indication that the signature belongs to the owner.**
Primary key fingerprint: 81AC 591F E9C4 B65C 5806  AFC3 F0AF 4D46 2A0B DF92

Something to think about... 
Thanks!

**Comment by vtnerd** [comment]
You are potentially asking these people to personally meet fluffypony for verification. So I'm not sure if this could be in practice.

**Comment by selsta** [comment]
> but how the community be sure the whole project hasn't been corrupted recently?

By following the repo, checking commits and also participating in building reproducible binaries, see https://github.com/monero-project/gitian.sigs

**Comment by skironDotNet** [comment]
@vtnerd I think it's possible to sign a key using his pub key, so he is not needed, but maybe I'm wrong maybe his priv key is needed, in such a case maybe emailing him about new members and signing for new members, maybe he would do...

**Comment by moneromooo-monero** [comment]
The commits adding the keys are signed by fluffypony's key.
Granted, it might be less secure than straight signing the key with GPG.
Still worth doing I guess if pony's up for it.

**Comment by selsta** [comment]
As moneromooo said, all commits that add a new key are signed by a maintainer. The binaries are always signed by the same key and if that would change there would be an announcement first.

Also all our builds are reproducible and every participant signs his hashes: https://github.com/monero-project/gitian.sigs

I don't think the existing keys will change, but the trusted signature is something to keep in mind for the future.
