### ISSUE TITLE
Testnet multisig wallet block height is higher than the daemon's height

### ISSUE THREAD

**Issue by OxMarco** [monero-project/monero#6796]
When creating a 2/3 set of multisig wallets using _monero-gen-trusted-multisig_ under testnet and later opening the wallets I always get:
`
The wallet's refresh-from-block-height setting is higher than the daemon's height: this may mean your wallet will skip over transactions
`
Moreover, the balance is stuck at 0 despite sending multiple XMR. The daemon was working and synchronised with testnet.

**Comment by dEBRUYNE-1** [comment]
By typing `set` in `monero-wallet-cli` you will be able to see the wallet creation height (I think it is called refresh height in the CLI). You will further be able to change it to a value that is in advance of the first transaction to your wallet. The wallet will, thereafter, perform a rescan and your transactions should properly appear. 

For debugging purposes, can you list the initial value of the wallet creation height?

**Comment by grcasanova** [comment]
The restore height is 1556332

**Comment by moneromooo-monero** [comment]
set refresh-from-block-height N
rescan_bc

Did you have a daemon up when you created the wallets ? If not, it'll try to guess at the current height using the local time, and this estimation is a bit wonky for testnet as it was forcibly reorged a number of times.

**Comment by grcasanova** [comment]
Yes I had the daemon synchronised and running on testnet. Do I need monero-wallet-rpc too?

**Comment by moneromooo-monero** [comment]
Assuming you did not create the wallets with monero-wallet-rpc, no. The wallet should connect to the daemon to get the current height. Maybe it's buggy then. Can you detail the steps youu took to create those wallets ?

**Comment by grcasanova** [comment]
I think it may be due to the local daemon not working.
As of now 11:15 GMT, this is the info:

```
print_height
1543985
version
0.16.0.3-release
status
Height: 1543985/1543985 (100.0%) on testnet, not mining, net hash 3.51 kH/s, v12, 8(out)+0(in) connections, uptime 1d 0h 15m 10s
```
while the current block height is 1545264

**Comment by selsta** [comment]
@grcasanova Testnet forked to v14, you have to compile latest git master to connect to testnet currently. This happened yesterday so it does not explain your initial issue.

**Comment by ProkhorZ** [comment]
Don't we have a stagenet for this type of testing? The testnet is rather wild because it's used to test protocol development. Either I'm missing something, or you're all too clever to give the obvious answer.
