### ISSUE TITLE
Conflicting libraries

### ISSUE THREAD

**Issue by leopoldoorsini** [monero-project/monero#6799]
```
duplicate symbol '_randombytes' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-randombytes.o)
duplicate symbol '_randombytes_close' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-randombytes.o)
duplicate symbol '_sodium_init' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-core.o)
duplicate symbol '_crypto_stream_salsa20_xor' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-stream_salsa20.o)
duplicate symbol '_crypto_stream_salsa20' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-stream_salsa20.o)
duplicate symbol '_randombytes' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-randombytes.o)
duplicate symbol '_randombytes_close' in:
    /usr/local/lib/libzmq.a(src_libzmq_la-tweetnacl.o)
    /usr/local/lib/libsodium.a(libsodium_la-randombytes.o)
```

**Comment by ndorf** [comment]
Which platform are you using? Did you install the sodium and zmq libraries using your platform's package manager, build them yourself, or some other method?

**Comment by leopoldoorsini** [comment]
Mac OS, previously installed with brew

**Comment by vtnerd** [comment]
The ZeroMQ static build includes a good chunk of libsodium, causing the conflicts. You will need to either:
  * Rebuild ZeroMQ with the libsodium symbols marked as private (not exported)
  * Rebuild ZeroMQ without libsodium support. The daemon is not using CurveZMQ currently anyway
  * Use shared libraried for ZeroMQ and libsodium

**Comment by leopoldoorsini** [comment]
It still gives me several errors like
```
(.text+0x21c): undefined reference to `gss_release_cred'
/usr/bin/ld: (.text+0x230): undefined reference to `gss_release_name'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-gssapi_server.o): in function `zmq::gssapi_server_t::~gssapi_server_t()':
```

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6845 should fix this one (it's in 0.17.0.1).

**Comment by xmrdog** [comment]
> #6845 should fix this one (it's in 0.17.0.1).

On my macOS Mojave today, I get exactly these same "duplicate symbol" issues between libzqm and libsodium. I was checked out on the 0.17.0.1 tag and did "make release-static" there. Can this be investigated further?

**Comment by xmrdog** [comment]
(It's worth mentioning that only "make" works fine (on macOS Mojave, tag 0.17.0.1 as before). It would be cool if "make release-static would also work.)

**Comment by moneromooo-monero** [comment]
You need to build your libzmq with libsodium support. Ohterwise it uses a separate tweetnacl lib which uses the same routine names, so they conflict.

**Comment by selsta** [comment]
I used this to build libzmq on Mac:

```
sodium_CFLAGS=-I/usr/local/opt/libsodium/include sodium_LIBS=-L/usr/local/opt/libsodium/lib ./configure --enable-static --disable-libunwind --disable-perf --with-pic --without-docs --with-libsodium --prefix=/path/to/prefix
```

**Comment by xmrdog** [comment]
@moneromooo-monero Thanks - that is working. Using @selsta comment as base, I solved it with "brew edit zeromq", adding these at the obvious places in the file:

    ENV["sodium_CFLAGS"] = "-I/usr/local/opt/libsodium/include"
    ENV["sodium_LIBS"] = "-L/usr/local/opt/libsodium/lib"
    "--enable-static", "--with-libsodium"

Finally "brew reinstall --build-from-source zeromq".

After this "make release-static" works.
