### ISSUE TITLE
Readme.md introduction suggestions

### ISSUE THREAD

**Issue by garlicgambit** [monero-project/monero#6807]
The following sentence is inaccurate:  
"Wallet files are encrypted with a passphrase to ensure they are useless if stolen."  
  
If a user doesn't set a password/passphrase or sets a weak one it is trivial to unlock the wallet.  
  
Suggest to change it to something like:  
"Wallet files can be encrypted with a strong passphrase to ensure they are useless if stolen."  
  
Or (with some variations):  
"Wallet files can be encrypted/protected with a strong passphrase to make it extremely hard/infeasible to unlock the wallet with brute force password cracking."  
  
Or remove the line.  
  
Suggest to drop "absolutely" from the following sentence:  
"This ensures that your purchases, receipts, and all transfers remain absolutely private by default."

**Comment by selsta** [comment]
#6873
