### ISSUE TITLE
I need help please, someone. anyone.

### ISSUE THREAD

**Issue by pres-code** [monero-project/monero#6832]
I recently got a new ledger wallet and I was trying to set up the Monero gui with it, I transferred some coin to the wallet address it has on  my gui but It hasn't shown up and its been a few days now. Im not a blockchain expert at all but can someone please help me find it? I don't know what to do

**Comment by selsta** [comment]
Which wallet mode are you using? (Simple mode / advanced mode)? You can check inside Settings -> Info.

**Comment by pres-code** [comment]
Advancced

**Comment by selsta** [comment]
Are you using a local node or a remote node?

If local:

Are you fully synchronized? You can check in the bottom left corner.

If remote node:

Which remote node are you using? Can you try a different one?

**Comment by pres-code** [comment]
Local and no its not fully synchronized

**Comment by selsta** [comment]
You have to be fully synchronized before your funds show up.

**Comment by pres-code** [comment]
It was synced on my other computer I thought. I just bought this one and don't think its had time to do it yet.
Will the funds still show up when I do get fully synchronized?

**Comment by selsta** [comment]
> Will the funds still show up when I do get fully synchronized?

Yes, if not please report back.

**Comment by pres-code** [comment]
ok. thank you.

**Comment by moneromooo-monero** [comment]
I assume it worked. Reopen if not.
