### ISSUE TITLE
release archive does not include supercop

### ISSUE THREAD

**Issue by bjacquin** [monero-project/monero#6859]
Hi,

Building release from tarball available in https://github.com/monero-project/monero/releases/tag/v0.17.0.1 fails due to the lack of supercop module inclusion in the tarball:

```
$ curl -sL https://github.com/monero-project/monero/archive/v0.17.0.1.tar.gz | tar tvz | fgrep -F external/supercop/
drwxrwxr-x root/root         0 2020-09-26 00:19 monero-0.17.0.1/external/supercop/
```

```
-- Found readline library at: /usr
CMake Error at CMakeLists.txt:1003 (include):
  include could not find load file:

    external/supercop/functions.cmake


CMake Error at src/crypto/wallet/CMakeLists.txt:38 (monero_crypto_autodetect):
  Unknown CMake command "monero_crypto_autodetect".


-- Configuring incomplete, errors occurred!
```

Would it be possible to release tarball that contain all the required submodules to remove the need for git ?

**Comment by selsta** [comment]
The tarball is auto generated by github, we can’t disable it and we can’t add sumodules to it.

**Comment by bjacquin** [comment]
This is correct, however did you consider adding a CMake target to create tarball and various singnature which could be uploaded manually to GitHub

**Comment by fluffypony** [comment]
@bjacquin we did generate complete source tarballs as part of the release engineering. Nobody used them except the auto-updater in instances where you're not on a tagged release, so it looks like nobody bothered generating a source tarball since 0.15.0.1🤷🏻‍♂️

**Comment by moneromooo-monero** [comment]
Out of our hands.
