### ISSUE TITLE
Ledger Nano X wrong device status after upgrading to 0.17.0.1

### ISSUE THREAD

**Issue by mountassir** [monero-project/monero#6861]
Hi, 

After upgrading to the GUI 0.17.0.1, the wallet can no longer open the hardware wallet, these are the errors I see in the logs:

```
ERROR	device.ledger	src/device/device_ledger.cpp:484	Wrong Device Status: 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), MASK 0xffff
ERROR	WalletAPI	src/wallet/api/wallet.cpp:719	Error opening wallet: Wrong Device Status: 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), MASK 0xffff
ERROR	frontend	src/wallet/api/wallet.cpp:416	Error opening wallet with password:  Wrong Device Status: 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), MASK 0xffff
```

The Ledger app is on version 1.6.

Thanks

**Comment by mountassir** [comment]
Apparently this error means the the app does not support the client's version, I see a new version of the Ledger app 1.7.2 was released a few days ago, hopefully that will fix the issue. Ledger Live still show 1.6 as the latest version for now.

**Comment by dEBRUYNE-1** [comment]
v0.17 can only be run in conjunction with Ledger Monero App v1.7.x, which is currently only available in *developer mode*.

**Comment by mountassir** [comment]
Ok thanks for confirming!
