### ISSUE TITLE
Cannot use `show_transfers in` without being connected to daemon

### ISSUE THREAD

**Issue by muff1nman** [monero-project/monero#6878]
With an offline wallet `--offline`, that I've imported outputs for, I cannot show my incoming transfers:

```
[ wallet XXXXXX (no daemon)]: show_transfers in
Error: Failed to get pool state:no connection to daemon
```

**Comment by moneromooo-monero** [comment]
Works for me, with --offline and with both a daemon running and not.

**Comment by jonathancross** [comment]
I see `Error: Failed to get pool state:no connection to daemon` as well in v0.17.1.1 (wallet is on a system that is air-gapped)

**Comment by moneromooo-monero** [comment]
That's normal if you don't have a daemon connected.

**Comment by muff1nman** [comment]
Regardless of expected or not, is that desired? I would argue that should be a warning instead of an error and it should at least show transfers that were imported.

**Comment by moneromooo-monero** [comment]
It shows in/out transfers either way, so... if it doesn't for you, then you'll have to supply more info as to how you're doing it, there might be a particular set of circumstances which cause those txes not to be displayed, but since it works for, I can't fix it.
