### ISSUE TITLE
The "failed to find tx meta" bug or feature

### ISSUE THREAD

**Issue by trurebel** [monero-project/monero#6879]
Googling for this error message made me believe I might have corrupted my (newly synced) DB, so I did a couple of resyncs from scratch on Ubuntu and Windows, no improvements. Then I realized the meta message was connected to me starting solo mining. Then Google took me to this other issue where a comment suggested the "meta" is connected to pruned databases. I did not prune mine but maybe my peers are pruned? Anyway, the rate of this notification alone could crash the computer, that's what it feels like, and would jam up the log if it ends up in any log. I don't think the defaults here are sane, and that would be my second most requested feature, to somehow clean this up, after my first requested feature, a "monerod --pruned" that syncs from scratch in a pruned state.

**Comment by moneromooo-monero** [comment]
It's unrelated to pruning, it's a minor bug that is harmless in practice, you can ignore it. Your blockchain is most likely just fine.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/6880 silences it for now.
