### ISSUE TITLE
Monero GUI Wallet, Sending Problem (Oxygen Orion)

### ISSUE THREAD

**Issue by Furiouz84** [monero-project/monero#6885]
Hi guys, 

hopefully some can brighten up my dark world...

I've downloaded a second wallet.
I could send Monero to it. And I did.

But sending Monero from this Wallet says "awaiting confirmation".
And my Monero balance is untouched.
Under transactions it says sended, and To (awaiting transaction).

I've made a simple wallet.
Versions:
Gui version: 0.17.0.1-afc2e84 (Qt 5.9.9)
Monero vers: 0.17.0.1-afc2e846f

On options there is no "Node" since I tried to solve on my own. 

I've verified the hashes before downloading.

Why can I receive, but not send?

Thx in advance

**Comment by selsta** [comment]
Which wallet mode did you select? Simple mode or advanced mode? You can check inside Settings -> Info.

**Comment by Furiouz84** [comment]
I made a "Simple" wallet

**Comment by selsta** [comment]
Please follow the instructions here: https://github.com/monero-project/monero-gui/issues/3140#issuecomment-706440354

It is a bug in simple mode, we are working on a fix.

**Comment by selsta** [comment]
Resolved: https://www.getmonero.org/2020/10/14/monero-GUI-0.17.1.0-released.html
