### ISSUE TITLE
XMR wallet GUI not working anymore... Please HELP!!!

### ISSUE THREAD

**Issue by dariensc** [monero-project/monero#6899]
I've just downloaded the most recent version of the wallet GUI and now it doesn't allow me to sign in with my previous password. It says: 

"Couldn't open wallet: Wrong Device Status:0x6a30 (UNKNOWN), EXPECTED 0x9000 (SW_OK), MASK 0xffff"

I've also tried to restore wallet from device, with restore height but haven't succeded either. Shows "Error writing wallet from hardware device. Check applications logs".

I'm really new to all this tech and has no background coding, so I'm really desperate and afraid I can't recover my money. So please, any help would be greatly appreciated

**Comment by selsta** [comment]
Update Monero Ledger all to v1.7.4 using Ledger Live

**Comment by dariensc** [comment]
Oh, thanks... I'll do it right now. Hope it helps

**Comment by dariensc** [comment]
@selsta Awesome!! IT WORKED THANKS!!

Now I have some issues with the DOUBLE SPENDING... Yesterday I was having troubles with sending XMR and I followed your workaround entering the address (node.xmr.to) and Port (18081) as you suggested in another posts.

I'm guessing it has to do with the stucked TXNs (Waiting confirmation). Is there any way to solve this issue?

**Comment by dariensc** [comment]
@iDunk5400 Oh, thanks, I'll move there then.

**Comment by selsta** [comment]
Go to Settings -> Info, click on "(Change)" next to restore height and then simply click on okay, don’t change the number.

Afterwards it will refresh and your issue should be resolved.
