### ISSUE TITLE
--detach option for simplewallet [enhancement]

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#690]
Useful for rpc mode.

**Comment by dEBRUYNE-1** [comment]
+enhancement

**Comment by Leeeei** [comment]
As the program monero-wallet-rpc has replaced the rpc interface that was in simplewallet and then monero-wallet-cl, so I believe this enhancement is no longer valid.

**Comment by moneromooo-monero** [comment]
It's just been added to monero-wallet-rpc now.

+resolved
