### ISSUE TITLE
Unsigned transactions generated on macOS cannot be signed on Linux

### ISSUE THREAD

**Issue by leevlad** [monero-project/monero#6901]
- `macOS` version: `10.15.7`
- `Linux` version: `Ubuntu 18.04`
- `monerod` version: `0.17.1.0` obtained from the official downloads page
- `monero-wallet-rpc` version: `0.17.1.0` obtained from the official downloads page
- `network`: `mainnet`

### Steps to reproduce:

1. Generate a transaction on macOS using `monero-wallet-rpc` by calling the `transfer` JSON-RPC method.
2. Pass the `unsigned_txset` string to a `monero-wallet-rpc` instance running on Linux using the `sign_transfer` JSON-RPC method.

### Error:
```
{
  "error": {
    "code": -39,
    "message": "cannot load unsigned_txset"
  },
  "id": "0",
  "jsonrpc": "2.0"
}
```

### Additional notes:
I did verify that the `unsigned_txset` in my test case is indeed of the `version == '\005'` format.

Passing the `unsigned_txset` string to a `monero-wallet-rpc` instance running on macOS does not produce an error and creates a signed transaction correctly.

Looking through the source code it appears to be a problem with the new serialization format introduced in the following PR: 
https://github.com/monero-project/monero/pull/6690

Specifically, the following `serialize` call fails: 
https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L6710

**Comment by moneromooo-monero** [comment]
Can you repro this on testnet for a wallet you could give me both the seed for and the file generated on mac ?

**Comment by leevlad** [comment]
I'm not currently running any nodes or wallets on the testnet, but can look into it when I have time. Alternatively I can share my mainnet wallet's `view_secret_key` and the `unsigned_txset` hex string that's failing, so you might be able to write a test harness with those values that would just replicate the code here:

https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L6710

**Comment by moneromooo-monero** [comment]
I think that'd be sufficient, yes.

**Comment by moneromooo-monero** [comment]
My GPG key's in the monero tree if you don't want that secret view key public.

**Comment by leevlad** [comment]
No worries, this is a transient wallet that I created for testing this issue, of no monetary/privacy consequence whatsoever. Plus it will allow other people to work on it. You can find both in the gist below:
https://gist.github.com/leevlad/2f569e971646cdfc1108c0ffd919221e

**Comment by moneromooo-monero** [comment]
If it has no privacy consequence... is the change supposed to be  0.048983820000 to 42wqzvHUsEv9aX9PTXy2UM6vbaABdra7sHcGvpaL3nxPBDitduMxYgLWxiXv3ph3SN2hBCx8DuK4T4Rs3JdcpjZHUbzJN6H ? I'm trying to find out where it starts going wonky.

**Comment by leevlad** [comment]
That address is where I'd expect the change to go. The wallet balance before the transfer should be 0.05 XMR, sent amount was for 0.001 XMR + network fees. So that looks about right to me.

Another thing that might help narrow it down is that I found that when I exported outputs from a macOS machine using the `export_outputs` call, and then imported them on a Linux machine using the `import_outputs` call of `monero-wallet-rpc` - I did not run into any issues.

**Comment by moneromooo-monero** [comment]
Does this fix it (apply on the mac version) ?

```
diff --git a/src/cryptonote_core/cryptonote_tx_utils.h b/src/cryptonote_core/cryptonote_tx_utils.h
index dbdf409b5..a6c71d3b1 100644
--- a/src/cryptonote_core/cryptonote_tx_utils.h
+++ b/src/cryptonote_core/cryptonote_tx_utils.h
@@ -102,8 +102,8 @@ namespace cryptonote
       FIELD(original)
       VARINT_FIELD(amount)
       FIELD(addr)
-      FIELD(is_subaddress)
-      FIELD(is_integrated)
+      VARINT_FIELD(is_subaddress)
+      VARINT_FIELD(is_integrated)
     END_SERIALIZE()
   };
 
```

**Comment by moneromooo-monero** [comment]
(if not, please send me the new unsigned tx data)

**Comment by leevlad** [comment]
Thanks for looking into it so soon.

I'm not going to be able to get this tested on my Mac as I can't compile monero on the latest version Catalina on `clang v12.0.0`, but I do see that this issue has recently been solved (per https://github.com/monero-project/monero/issues/6799).

I'll give this a go later this week and report back.

**Comment by selsta** [comment]
@leevlad normal `make release` should work fine on Mac. (I’m on Catalina too)

**Comment by leevlad** [comment]
> Does this fix it (apply on the mac version) ?
> 
> ```
> diff --git a/src/cryptonote_core/cryptonote_tx_utils.h b/src/cryptonote_core/cryptonote_tx_utils.h
> index dbdf409b5..a6c71d3b1 100644
> --- a/src/cryptonote_core/cryptonote_tx_utils.h
> +++ b/src/cryptonote_core/cryptonote_tx_utils.h
> @@ -102,8 +102,8 @@ namespace cryptonote
>        FIELD(original)
>        VARINT_FIELD(amount)
>        FIELD(addr)
> -      FIELD(is_subaddress)
> -      FIELD(is_integrated)
> +      VARINT_FIELD(is_subaddress)
> +      VARINT_FIELD(is_integrated)
>      END_SERIALIZE()
>    };
>  
> ```

This doesn't seem to compile on Mac. Here's a relevant snippet:
```
[ 50%] Building CXX object src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
In file included from /Users/vladimirli/Developer/paradiso/xmr-golang-bindings/monero/src/wallet/wallet2.cpp:35:
In file included from /usr/local/include/boost/algorithm/string/classification.hpp:17:
In file included from /usr/local/include/boost/range/as_literal.hpp:22:
In file included from /usr/local/include/boost/range/iterator_range.hpp:13:
In file included from /usr/local/include/boost/range/iterator_range_core.hpp:38:
In file included from /usr/local/include/boost/range/functions.hpp:20:
In file included from /usr/local/include/boost/range/size.hpp:21:
In file included from /usr/local/include/boost/range/size_type.hpp:24:
/usr/local/include/boost/type_traits/make_unsigned.hpp:32:4: error: static_assert failed due to requirement '!::boost::is_same<bool, bool>::value' "The template argument to make_unsigned must not be the type bool"
   BOOST_STATIC_ASSERT_MSG((! ::boost::is_same<typename remove_cv<T>::type, bool>::value), "The template argument to make_unsigned must not be the type bool");
   ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/static_assert.hpp:31:45: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
#     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)
                                            ^             ~~~~~~~~~~~
monero/src/serialization/binary_archive.h:142:41: note: in instantiation of template class 'boost::make_unsigned<bool>' requested here
    serialize_uvarint(*(typename boost::make_unsigned<T>::type *)(&v));
                                        ^
monero/src/cryptonote_core/cryptonote_tx_utils.h:105:7: note: in instantiation of function template specialization 'binary_archive<false>::serialize_varint<bool>' requested here
      VARINT_FIELD(is_subaddress)
      ^
monero/src/serialization/serialization.h:267:8: note: expanded from macro 'VARINT_FIELD'
    ar.serialize_varint(f);                     \
       ^
monero/src/cryptonote_core/cryptonote_tx_utils.h:101:5: note: in instantiation of function template specialization 'cryptonote::tx_destination_entry::do_serialize_object<false, binary_archive>' requested here
    BEGIN_SERIALIZE_OBJECT()
/usr/local/include/boost/type_traits/make_unsigned.hpp:32:4: error: static_assert failed due to requirement '!::boost::is_same<bool, bool>::value' "The template argument to make_unsigned must not be the type bool"
   BOOST_STATIC_ASSERT_MSG((! ::boost::is_same<typename remove_cv<T>::type, bool>::value), "The template argument to make_unsigned must not be the type bool");
   ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/static_assert.hpp:31:45: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
#     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)
                                            ^             ~~~~~~~~~~~
monero/src/serialization/binary_archive.h:142:41: note: in instantiation of template class 'boost::make_unsigned<bool>' requested here
    serialize_uvarint(*(typename boost::make_unsigned<T>::type *)(&v));
                                        ^
monero/src/cryptonote_core/cryptonote_tx_utils.h:105:7: note: in instantiation of function template specialization 'binary_archive<false>::serialize_varint<bool>' requested here
      VARINT_FIELD(is_subaddress)
      ^
monero/src/serialization/serialization.h:267:8: note: expanded from macro 'VARINT_FIELD'
    ar.serialize_varint(f);                     \
       ^
monero/src/cryptonote_core/cryptonote_tx_utils.h:101:5: note: in instantiation of function template specialization 'cryptonote::tx_destination_entry::do_serialize_object<false, binary_archive>' requested here
    BEGIN_SERIALIZE_OBJECT()
```

**Comment by moneromooo-monero** [comment]
Then this one:

```
diff --git a/src/cryptonote_core/cryptonote_tx_utils.h b/src/cryptonote_core/cryptonote_tx_utils.h
index dbdf409b5..d4cfb8262 100644
--- a/src/cryptonote_core/cryptonote_tx_utils.h
+++ b/src/cryptonote_core/cryptonote_tx_utils.h
@@ -76,8 +76,8 @@ namespace cryptonote
     std::string original;
     uint64_t amount;                    //money
     account_public_address addr;        //destination address
-    bool is_subaddress;
-    bool is_integrated;
+    uint8_t is_subaddress;
+    uint8_t is_integrated;
 
     tx_destination_entry() : amount(0), addr(AUTO_VAL_INIT(addr)), is_subaddress(false), is_integrated(false) { }
     tx_destination_entry(uint64_t a, const account_public_address &ad, bool is_subaddress) : amount(a), addr(ad), is_subaddress(is_subaddress), is_integrated(false) { }
```

**Comment by leevlad** [comment]
Just tried this out. Unfortunately it's still producing the same error. Tried just the diff you posted above, which compiled fine, but failed to sign on Linux with the same error.

Then tried both your suggestions from above, which also compiled fine but produced the same error:
```
 #pragma once
@@ -76,8 +76,8 @@ namespace cryptonote
     std::string original;
     uint64_t amount;                    //money
     account_public_address addr;        //destination address
-    bool is_subaddress;
-    bool is_integrated;
+    uint8_t is_subaddress;
+    uint8_t is_integrated;
 
     tx_destination_entry() : amount(0), addr(AUTO_VAL_INIT(addr)), is_subaddress(false), is_integrated(false) { }
     tx_destination_entry(uint64_t a, const account_public_address &ad, bool is_subaddress) : amount(a), addr(ad), is_subaddress(is_subaddress), is_integrated(false) { }
@@ -102,8 +102,8 @@ namespace cryptonote
       FIELD(original)
       VARINT_FIELD(amount)
       FIELD(addr)
-      FIELD(is_subaddress)
-      FIELD(is_integrated)
+      VARINT_FIELD(is_subaddress)
+      VARINT_FIELD(is_integrated)
     END_SERIALIZE()
   };
```

Here's the resulting `unsigned_tx_set` string from the latest test I ran (with both you suggestions applied): https://gist.github.com/leevlad/efafb91c388430dd272996a1e6d8d2e1

**Comment by moneromooo-monero** [comment]
Could you run with the patch at https://paste.debian.net/1167877/ on mac please ? It will log what it loads, and then I can compare with what I get here to see where it's going out of sync. You'll have to run the wallet with log level 0 or higher (the CLI wallet logs nothing by default).
I suspect it might be a list of size_t, and sizeof(size_t) might be different, we'll see.

**Comment by leevlad** [comment]
Ok, I applied the patch from above to a clean state (at tag v0.17.1.0). Here's the log output:
https://gist.github.com/leevlad/b959b9c8b05b6dddaa6c6d616ffe3754

**Comment by moneromooo-monero** [comment]
This is very odd, I can't see parts of the extra string in the decoded data you posted earlier. Are you sure you're loading the same data ?

**Comment by moneromooo-monero** [comment]
What is the output of this exact command ?
```
echo -e '#include <stddef.h>\nint main(){return sizeof(size_t);}' | clang -x c - ; ./a.out ; echo $?
```

**Comment by leevlad** [comment]
> This is very odd, I can't see parts of the extra string in the decoded data you posted earlier. Are you sure you're loading the same data ?

I'm not entirely sure what you're referring to. I just ran `monero-wallet-rpc` and tried to generate an unsigned transaction in the same way as before and gave you the trace output from `stdout`.



> What is the output of this exact command ?
> 
> ```
> echo -e '#include <stddef.h>\nint main(){return sizeof(size_t);}' | clang -x c - ; ./a.out ; echo $?
> ```

The output was:
```
8
```

**Comment by moneromooo-monero** [comment]
If you generated another, it doesn't match anymore the one I have, so can't compare. Can you send me the new rx dump then, which matches the log data ?

**Comment by leevlad** [comment]
This should be it: https://gist.github.com/leevlad/9c023225f807c0b762b8d1f53c59719f

**Comment by selsta** [comment]
Someone on IRC reported the same issue.

**Comment by jonathancross** [comment]
I've seen this issue as well going back several releases, but have not looked into it carfully to isolate the problem.

I also saw that outputs exported from macOS (watch-only wallet) via `export_outputs` would corrupt a (Linux) offline wallet when imported.  This seems to contradict what @leevlad says above in https://github.com/monero-project/monero/issues/6901#issuecomment-711084354 though, so I figured it might be something specific to my setup.  

Outputs exported from Linux watch-only version of the same wallet worked fine.

**Comment by moneromooo-monero** [comment]
https://github.com/moneromooo-monero/bitmonero/commit/2910c84f4ba7c80f70e20c2746be6bf4189d1df0 should fix it. It should also convert your existing mac wallet cache to the new format, and be able to reload it. If it fails, it means the patch is not complete.

**Comment by moneromooo-monero** [comment]
https://github.com/moneromooo-monero/bitmonero/commit/b744466e906b6c6233e996de07fa648624918a4c (slightly modified, thanks xmrdog for mac testing) fixes it.

**Comment by dethos** [comment]
I'm experiencing the same behavior using 2 `monero-wallet-rpc` instances on Linux. The view only wallet creates the `unsigned_txset` hex but full wallet does not recognize it.

----------------------
**RPC response**:
```
"code": -39,
"message": "cannot load unsigned_txset"
```
**RPC logs**:
```
2021-02-11 13:53:46.889 W Failed to decrypt unsigned tx: Failed to authenticate ciphertext
2021-02-11 14:14:40.492 E !crypto::check_signature(hash, pkey, signature). THROW EXCEPTION: error::wallet_internal_error
2021-02-11 14:14:40.492 W Failed to decrypt unsigned tx: Failed to authenticate ciphertext
```
**Network**: Stagenet
**Monero version:** Monero 'Oxygen Orion' (v0.17.1.9-release)

-------------------

**Steps to reproduce:**
1. call `transfer` from the view-only wallet
2. Store the  generated `unsigned_txset` hex
3. call `sign_transfer` (or even `describe_transfer`) using the stored `unsigned_txset` on the full wallet
4. RPC return the above error message.

**Comment by woodser** [comment]
> What is the output of this exact command ?
> 
> ```
> echo -e '#include <stddef.h>\nint main(){return sizeof(size_t);}' | clang -x c - ; ./a.out ; echo $?
> ```

`sizeof(size_t);` returns 4 in WebAssembly (built on mac) which also has serialization compatibility issues:

- https://github.com/monero-ecosystem/monero-javascript/issues/50.
- The wallet cache fails to deserialize in WebAssembly.  moneromooo-monero@b744466 appears to have no effect unfortunately

**Comment by jonathancross** [comment]
FYI: This should be fixed now that #7321 is merged.

**Comment by selsta** [comment]
It is not merged yet?

**Comment by jonathancross** [comment]
Sorry, my mistake.  Updated my comment.

**Comment by jonathancross** [comment]
#7321 is now merged  :-)
