### ISSUE TITLE
 Unknown CMake command "monero_crypto_autodetect".

### ISSUE THREAD

**Issue by ghdqh1515** [monero-project/monero#6904]
$make
Error after execution
Can't build due to error
 Unknown CMake command "monero_crypto_autodetect".

**Comment by moneromooo-monero** [comment]
What platform ? What cmake version ? In what directory are you running make ? Any other error before that ?

**Comment by mikegeoffrey** [comment]
All the external subdirs are empty in the v0.17.1.1 tar.gz release, so the monero_crypto_autodetect can't be found as it's in function.cmake file in the supercop subdir. Same for a lot of the other dirs, just empty.

**Comment by selsta** [comment]
Github auto generates the source tarball without submodules. This is out of our control. Please use git to clone recursively.
