### ISSUE TITLE
There were 0 blocks in the last 90 minutes

### ISSUE THREAD

**Issue by 90hacker** [monero-project/monero#6908]
There were 0 blocks in the last 90 minutes, there might be large hash rate changes, or we might be partitioned, cut off from the Monero network or under attack, or your computer's time is off. Or it could be just sheer bad luck.

What is the problem

![image](https://user-images.githubusercontent.com/15024497/96366778-79ae1200-117c-11eb-9df6-9bdee4fe6e3f.png)

**Comment by selsta** [comment]
See #6907 

New version will be out soon

**Comment by PauleBertt** [comment]
https://github.com/monero-project/monero/pull/6906

it is related to this

**Comment by 90hacker** [comment]
I upgraded to v0.17.1.1。
solved this problem。
