### ISSUE TITLE
Malwarebytes reports RiskWare.BitcoinMiner malware

### ISSUE THREAD

**Issue by PostNZT** [monero-project/monero#6919]
![image](https://user-images.githubusercontent.com/34854542/96475040-21ebd580-1266-11eb-9013-6e43e110db63.png)

**Comment by moneromooo-monero** [comment]
Assuming you did not get infected, you should report it to them so they can fix their detection.

**Comment by PostNZT** [comment]
Done, I already filed a report on the support. Will be waiting for confirmation.

**Comment by erciccione** [comment]
See https://www.getmonero.org/get-started/faq/#antivirus
