### ISSUE TITLE
"Edit" and "Copy" buttons in Account and Receive tabs are not visible in GUI low graphics mode

### ISSUE THREAD

**Issue by MoneroArbo** [monero-project/monero#6945]
Version: 0.17.1.1

Platform: Windows 10 installer

Steps to reproduce: Launch Monero GUI in low graphics mode with monero-wallet-gui-low-graphics-mode.bat

Expected behavior: edit and copy buttons are visible in interface

Actual behavior: buttons work and can be used, but are invisible

Picture of the issue: https://i.imgur.com/4D2wkYp.png

This issue has been going on since at least version 0.16, when I started using low graphics mode.

**Comment by hyc** [comment]
Sounds like you should have submitted this in the monero-gui repo.
