### ISSUE TITLE
Transactions remain in pool for up to several minutes while blocks are mined

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#6951]
Transactions can remain in the pool for up to several minutes while mining blocks on a local stagenet network whereas they should confirm in the next available block?

**Comment by vtnerd** [comment]
Transactions in the "stem" phase are excluded from mining, to prevent potential leaking of the stem path. The Dandelion++ paper doesn't mention what to do in this case, this was a decision made during development.

There is a [related issue](https://github.com/monero-project/monero/issues/6929) about transactions being "stuck" in the local mempool and not distributed widely. Based on your description its not clear whether the transaction was sent correctly yet still waiting for the Dandelion++ "embargo timer", or whether it triggered this other issue. `set_log +net.p2p.tx:DEBUG` will print messages specific to transaction relaying.

**Comment by moneromooo-monero** [comment]
Should be better now. It can still happen if you relay to a peer that drops the tx on the floor though.
