### ISSUE TITLE
Unable to do transactions Cannot deserialize mg[i] (Trezor T)

### ISSUE THREAD

**Issue by ossii79** [monero-project/monero#6955]
Using latest code, tried both on windows 10 and linux, wallet-cli and gui wallet with a Trezor T.
Wallet syncs fine with remote daemon, however when trying to do transactions I get
`Can't create transaction: unexpected error: Cannot deserialize mg[i]`

Tried to do this with log_lvl 2. It creates the transaction, everything looks normal (recieving address, change amount etc) all the way to the end (transaction created) until it throws the error message.
Nothing it shown in transactions and no amount has been sent.

**Comment by selsta** [comment]
Did you try updating your Trezor firmware?

**Comment by ossii79** [comment]
Well that was embarrasing... Your absolutly right, upgrading the trezor firmware from 2.3.3 to 2.3.4 resolved it.
