### ISSUE TITLE
Monero issue

### ISSUE THREAD

**Issue by MNSTG** [monero-project/monero#6980]
[![image](https://user-images.githubusercontent.com/73965908/98164386-3af6b680-1ef5-11eb-921a-f8229c22177f.png)
](https://t.me/joinchat/KjFam0tUwsNDIxhr__BJ3w)

**Comment by kindyfree** [comment]
гони монера сукааа

**Comment by moneromooo-monero** [comment]
Looks like spam. File a new one if you manage to recover.
