### ISSUE TITLE
 coinbase maturity 

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#699]
With blocktime change for 2 minutes .

--  CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW 60 
++ CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW 45

Reduce 1/4  for increase blocktime per factor 2 .

**Comment by luigi1111** [comment]
This is a hardforking change. Personally, I think the coinbase maturation was possibly dangerously low before. The blocktime bump makes it somewhat better.
