### ISSUE TITLE
Does Monero-GUI attempt to retry failed transactions?

### ISSUE THREAD

**Issue by pushshift** [monero-project/monero#6998]
I have several failed transactions in my history which was eventually successful for one of them. I'm worried that if I receive enough Monero, the failed transactions will auto-attempt and retry to send to the same address.

1) How to I delete failed transactions in the GUI? I tried right-clicking but there doesn't seem to be any option to remove failed transactions.

2) Do failed transactions retry automatically? If so, how can this be disabled?

Thanks!

**Comment by iDunk5400** [comment]
Please open an issue in [Monero-GUI repo](https://github.com/monero-project/monero-gui/issues). Thank you.

**Comment by moneromooo-monero** [comment]
Monero is not balanced based. Receiving new monero will not affect previous transactions, which spend the same outputs whether or not you receive other monero later.

**Comment by selsta** [comment]
@pushshift Please update to v0.17.1.4, it should fail less often in simple mode.

**Comment by dEBRUYNE-1** [comment]
Please try the recently released v0.17.1.4:

https://www.reddit.com/r/Monero/comments/jrgtca/gui_v01714_oxygen_orion_released/

Additionally, see:

https://www.reddit.com/r/Monero/comments/jrh7mv/psa_informational_thread_on_the_recently_observed/

**Comment by selsta** [comment]
Wrong repo also Issue no longer relevant.
