### ISSUE TITLE
Inbound and outbound i2p connections have the same peer ID

### ISSUE THREAD

**Issue by MoneroArbo** [monero-project/monero#7004]
With the most recent version of monerod (0.17.1.3) I have been occasionally connected to INC and OUT i2p peers that have the same peer ID. As discussed in #6380, this is going to result in the ability to correlate transactions relayed over i2p with a particular i2p address.

[Output of print_cn](https://i.imgur.com/IMsoDr9.png)

[Output of sync_info](https://i.imgur.com/iTJRIDA.png)

@vtnerd I was suggested to ping you on this one

**Comment by vtnerd** [comment]
I closed the prior issue, and I will work on a fix for this shortly.

**Comment by moneromooo-monero** [comment]
Patch merged.
