### ISSUE TITLE
[P2P6]	ERROR	net	contrib/epee/include/net/abstract_tcp_server2.inl:765	Setting timer on a shut down object

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#7031]
[P2P6]	ERROR	net	contrib/epee/include/net/abstract_tcp_server2.inl:765	Setting timer on a shut down object

i mean, the daemon says its an error, so i guess its an issue?

**Comment by Gingeropolous** [comment]
Monero 'Oxygen Orion' (v0.17.1.3-release)

**Comment by sumogr** [comment]
this message was always there and its unimportant afaik

**Comment by moneromooo-monero** [comment]
It's fine in general.
