### ISSUE TITLE
[CI] Windows build failing - deprecated actions

### ISSUE THREAD

**Issue by mj-xmr** [monero-project/monero#7034]
For the below PRs (and others) the Windows build fails since about Saturday, 14.11.

[Xiphon's](https://github.com/monero-project/monero/pull/7030) 
[Mine1](https://github.com/monero-project/monero/pull/6956) 
[Mine2](https://github.com/monero-project/monero/pull/6977) 
[Vtnerd's](https://github.com/monero-project/monero/pull/7028) 

The error message is:

Error: Unable to process command '::add-path::D:\a\_temp\msys' successfully. 

105Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ 

106Error: Unable to process command '::set-env name=MSYSTEM::MINGW64' successfully. 

107Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by sumogr** [comment]
skipping eine's and using msys2/setup-msys2@v2 will fix that i guess. its not the commits

**Comment by selsta** [comment]
Thanks, there should be a PR for it already from a couple weeks ago, we just didn’t merge it yet.

**Comment by selsta** [comment]
#6982

**Comment by mj-xmr** [comment]
Thanks for the input. I confirm, that the version switch helped in my PRs.

**Comment by selsta** [comment]
Issue is resolved now.

**Comment by mj-xmr** [comment]
Since this is resolved for a time long enough, I think I can close the issue.
