### ISSUE TITLE
Can't export key images - always 164 bytes file

### ISSUE THREAD

**Issue by KarboDuck** [monero-project/monero#7042]
I'm trying to export key images. But I always get a file with size just of 164 bytes.

Importing this file on view wallet does nothing - balance is not updated.

Tried that using three different wallets with some balance on them on:

1. Laptop #1: Ubuntu 20.10, gui wallet 0.17.1.4

2. Laptop #2: 
* Windows 10, gui wallet 0.17.1.4, cli 0.17.1.3, cli 0.17.11
* Ubuntu 20.10 from live usb, gui wallet 0.17.1.4

**Comment by moneromooo-monero** [comment]
The wallet exports what it's not exported before. Add "all" to export all, like this:

export_key_images all somefilename

**Comment by KarboDuck** [comment]
Thanks. Seems it worked.

Is there way to use this in gui wallet?

**Comment by dEBRUYNE-1** [comment]
@KarboDuck - Perhaps you can close this issue (as there isn't really an issue with `monero-wallet-cli`) and open a new one on the GUI repository?

https://github.com/monero-project/monero-gui/issues/new

**Comment by KarboDuck** [comment]
https://github.com/monero-project/monero-gui/issues/3246
