### ISSUE TITLE
ERROR	cn.block_queue	src/cryptonote_protocol/cryptonote_protocol_handler.h:95	Error in handle_invoke_map: Attempt to get cumulative difficulty from height 2241261 failed -- difficulty not in db

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#7047]
I have 24 instances of this over 3 days. 

this is on a node with its RPC ports publicly listed and its also mining (via other machines pointing xmrig to this daemon)

**Comment by moneromooo-monero** [comment]
That usually means your db is toast.
