### ISSUE TITLE
Stagenet wallet from scratch only syncs up to block 570429.

### ISSUE THREAD

**Issue by normoes** [monero-project/monero#7048]
I am talking about `monero-wallet-rpc`, version `v0.17.1.5`.

I had troubles with the wallet and deleted the entire file, since this used to help.

It started to work, taking its time, but then it stopped and died with:
```
2020-11-30 16:01:44.048 E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon
2020-11-30 16:01:44.053 E pull_blocks failed, try_count=3
2020-11-30 16:01:44.053 E Wallet initialization failed: no connection to daemon
```

I tried a few more times and noticed, that it only synchronized the wallet up to (and including) block number `570429`. This block contains one of my transactions.

---

The wallet file, once completely synchronized (using a backup file), is `213 MB` in total.

**Comment by moneromooo-monero** [comment]
Can you share the seed ? You can encrypt it with my key (in utils).

**Comment by normoes** [comment]
I will.

By the way @moneromooo-monero , not sure if you are aware of this, your key will expire in a few days:
```
pub   rsa4096 2014-10-06 [SC] [expires: 2020-12-10]
      48B08161FBDADFE393ADFC3E686F07454D6CEFC3
uid           [ unknown] moneromooo-monero <moneromooo-monero@users.noreply.github.com>
sub   rsa4096 2014-10-06 [E] [expires: 2020-12-10]
```

**Comment by normoes** [comment]
Here you can find the seed: https://paste.debian.net/1175750/

**Comment by moneromooo-monero** [comment]
Oh, thanks. I always forget :)

**Comment by moneromooo-monero** [comment]
It gets past that for me. Try master :)

**Comment by normoes** [comment]
I can try that. Although, for `stagenet` and `mainnet` I usually don't. Let's see.

**Comment by moneromooo-monero** [comment]
Did you try ?

**Comment by normoes** [comment]
Oh yes, sorry.

It works with `master`.

**Comment by moneromooo-monero** [comment]
Thanks, closing then.
