### ISSUE TITLE
Adopting more inclusive terminology

### ISSUE THREAD

**Issue by amarube** [monero-project/monero#7060]
I was scanning through the codebase and observed use of "grandfathering" in  https://github.com/monero-project/monero/blob/master/src/cryptonote_core/blockchain.cpp. 

I propose we replace its use with more inclusive terms like "legacied" or "exempted".

For context on the complicated nature of the term and its racist origin please refer to: https://en.wikipedia.org/wiki/Grandfather_clause

**Comment by moneromooo-monero** [comment]
If you happen to change that code, rewording would be fine, but I fear doing this once will open the floodgates to more diff spam.

**Comment by jonahpq** [comment]
Codes of conduct, so-called "inclusive" terminology, and similar intrusions, are the death of software projects. There are enough real issues open for this project that you do not need to create any imaginary ones. 

If you want Monero to survive then do not do this.
