### ISSUE TITLE
GUI does not sync with my remote node

### ISSUE THREAD

**Issue by moneroentusi** [monero-project/monero#7064]
I open GUI, I connect to my private remote node on my VPS. It connects but is stuck at "Waiting for daemon to syns" , Daemon blocks remaining: 2. Whatever I do is not getting past this.....

Please help.

If I use a public node is working just fine.

**Comment by selsta** [comment]
Download: https://gui.xmr.pm/files/block.txt

Start daemon with --ban-list /path/to/block.txt

**Comment by moneroentusi** [comment]
Now is everything is working properly. Thank you!
