### ISSUE TITLE
Weird DNS requests from monerod to moneroPulse

### ISSUE THREAD

**Issue by hundehausen** [monero-project/monero#7077]
#### Issue description

As I saw in my pihole logs, monerod is making dns requests to [moneroPulse](https://monerodocs.org/infrastructure/monero-pulse/) which is normal, but some DNS queries look weird, because the only contain a dot or the tld. My upstream DNS server has no answer obviously. 
I am not sure if this is intended to act like this or if this has something to do with DNSSEC which I do not have enabled.

#### Steps to reproduce the issue

1.  Log all types of DNS queries (A, AAAA, TXT, DS, DNSKEY)
2.  Start monerod

#### What's the expected result?

- normal A and AAAA queries

#### What's the actual result?

- TXT, DS, DNSKEY queries with just a dot or the tld

#### Additional details / screenshot

<img width="878" alt="monerod_dns" src="https://user-images.githubusercontent.com/25672277/101226449-d31ec180-3694-11eb-956f-df4994926961.png">

**Comment by moneromooo-monero** [comment]
I don't know about DNSSEC, but this is probably the root.

**Comment by moneromooo-monero** [comment]
From the, er, horse's mouth:

```
<@fluffypony> yes it's the root
<@fluffypony> https://dnssec-analyzer.verisignlabs.com/checkpoints.moneropulse.net
```

**Comment by hundehausen** [comment]
All right thanks. The issue can be closed.
