### ISSUE TITLE
sync failure on rpi2 running ubuntu 14.04.4

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/monero#708]
Using --db-type lmdb 

commit a7310031f4b232af1e059088afc017bfaa1835b7 (pulled from master several days ago)

2016-Mar-07 06:02:14.210060 [P2P1][X.X.X.X:18080 OUT]Synced 543551/986276
2016-Mar-07 06:02:28.936539 [P2P1][X.X.X.X:18080 OUT]Synced 543751/986276
2016-Mar-07 06:02:43.988333 [P2P1][X.X.X.X:18080 OUT]Synced 543951/986276
2016-Mar-07 06:03:47.638078 [P2P1][X.X.X.X:18080 OUT]Synced 544151/986276
2016-Mar-07 06:03:49.317887 [P2P8]Failed to add output pubkey to db transaction
2016-Mar-07 06:03:49.467195 [P2P8]ERROR /home/ubuntu/bitmonero-0.9/src/cryptonote_core/blockchain.cpp:2716 Error adding block with hash: <b6a855618084e4dda2b8bb208d4c09f8203ca6aa62dd26ee40575bcd936416c4> to blockchain, what = Failed to add output pubkey to db transaction
2016-Mar-07 06:03:49.475352 [P2P8]DB error attempting to fetch block index from hash
2016-Mar-07 06:03:49.477070 [P2P8]ERROR /home/ubuntu/bitmonero-0.9/contrib/epee/include/net/abstract_tcp_server2.inl:342 Exception at [connection<t_protocol_handler>::handle_read], what=DB error attempting to fetch block index from hash
2016-Mar-07 06:03:51.120850 [P2P8]Error attempting to retrieve a block hash from the db: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid

**Comment by iamsmooth** [comment]
After restart it continued syncing. Not sure if this is good or bad.

**Comment by moneromooo-monero** [comment]
The original "Failed to add output pubkey to db transaction" error case now print out the lmdb API return code, so if you get this again, paste the message again.

**Comment by iamsmooth** [comment]
OK. hyc mentioned changing the 32 bit format, so I was planning to redo the whole sync and see what happens.

**Comment by NanoAkron** [comment]
Hi @iamsmooth, is this issue still present or can it be closed?

**Comment by iamsmooth** [comment]
I haven't tried this in a long time, so it may well be obsolete. Closing, can reopen if the problem reappears.
