### ISSUE TITLE
Add support for integrated subaddress to monero CLI wallet.

### ISSUE THREAD

**Issue by crocket** [monero-project/monero#7091]
https://monerodocs.org/public-address/integrated-address/ mentions an integrated address consists of public view key, public spend key, and payment ID.

For now, it seems that integrated addresses are generated only for standard address.

A subaddresses also has public view key and public spend key. An integrated subaddress helps a person assign a subaddress to each business.

Business 1 generates integrated addresses off subaddress 1.
Business 2 generates integrated addresses off subaddress 2.

If each business that I own generates multiple integrated addresses on top of its unique subaddress, tracking companies can't easily link my separate businesses together by just comparing payment addresses. Integrated subaddresses also help avoid computational cost of using subaddresses.

**Comment by moneromooo-monero** [comment]
It was decided to not do so. Use an account per business, and subaddresses off those accounts.

**Comment by crocket** [comment]
Why was it decided not to do so? https://monerodocs.org/public-address/integrated-address/ still mentions computational cost of using subaddresses.

Integrated addresses are not useful for people who have more than one business or do mining apart from business.

**Comment by moneromooo-monero** [comment]
I don't remember all maybe, but at least because it would keep the confusion between the full integrated address and the the split address + payment id. Subaddresses don't have much computational cost, assuming you don't use massive amounts of them.

**Comment by crocket** [comment]
> split address

What is this? I never heard.

**Comment by moneromooo-monero** [comment]
An integrated address is your standard address and the payment id stuck together along with some glue, so it looks different when displayed as integrated or displayed separately. This is a continuous source of confusion.

**Comment by crocket** [comment]
It is only confusing because the documentation doesn't say this. And, I understood split address intuitively, but I just didn't know the name for it.

**Comment by knaccc** [comment]
> computational cost of using subaddresses

The computational cost is that a modern CPU can "only" generate thousands of subaddresses per second. What kind of business is exceeding thousands of transactions per second, yet can't afford to run their business on more than one CPU?

I'm yet to hear a compelling argument that using a library to generate multiple subaddresses (grouping them by account) is significantly more effort than using a library to generate multiple integrated addresses (grouping them by subaddress).

**Comment by crocket** [comment]
There's also administrative and coding costs of using subaddresses.
It's also cheaper to scan a subaddress than thousands of subaddresses when you need to sync a wallet again.

**Comment by selsta** [comment]
> It's also cheaper to scan a subaddress than thousands of subaddresses when you need to sync a wallet again.

That’s not the case. Subaddresses use a lookup table, there is no speed difference in scanning.

**Comment by knaccc** [comment]
@crocket In case you aren't aware - you don't have to do RPC with a wallet in order to generate subaddresses. You can generate them locally with a library, just like you probably already use a library to generate integrated addresses.

Here are Java and Javascript libraries for generating subaddresses, and more are available for other languages:

https://github.com/knaccc/subaddress-java
https://github.com/knaccc/subaddress-js

**Comment by crocket** [comment]
The fact that subaddress generation requires a private view key isn't ideal.
Bitcoin can derive subaddresses with an extended public key.

**Comment by knaccc** [comment]
> There could be wide gaps between subaddresses. Is it okay for there to be huge gaps between subaddresses?

If the gap is more than 200, you need to set a flag on your wallet to "look ahead" more than 200 addresses at a time. You'd want to try and be sequential with your use though, by using a counter to remember the highest subaddress index you've issued so far.

**Comment by crocket** [comment]
> If the gap is more than 200, you need to set a flag on your wallet to "look ahead" more than 200 addresses at a time. You'd want to try and be sequential with your use though, by using a counter to remember the highest subaddress index you've issued so far.

Administrative and coding and conceptual costs.

> I agree it's not ideal. However, if they've compromised the server enough to steal the private view key, they have probably stolen your database credentials too and breached access to much more private information than that.

Programmers could lose private view keys through mistakes, or they could leak it intentionally against the will of contractors or employers. If you don't want to lose private view key, you better generate 1 million subaddresses and transfer them.
You still have to make sure that there will not be huge gaps between subaddresses.

**Comment by knaccc** [comment]
> Programmers could lose private view keys through mistakes, or they could leak it intentionally 

That is a good point.

> Administrative and coding and conceptual costs

Note that if you were to issue different bitcoin addresses in the same way as you'd issue different subaddresses, the implementation approach and effort would be similar. This does not diminish the fact that integrated addresses would be simpler.

It's certainly not the case that integrated addresses offer no advantages vs generating subaddresses. But we need subaddresses to avoid unlinkability, and so the question is whether we are making things too complicated by having integrated addresses in addition to subaddresses. I'm a big fan of simplicity.

**Comment by knaccc** [comment]
> Integrated subaddresses make things simpler

I strongly disagree that when a developer starts looking at the documentation, it is simpler that they will be be offered the choice of subaddresses vs integrated address vs integrated subaddress. It's obviously much simpler for them to understand what to do next if they are just told to issue subaddresses.

**Comment by selsta** [comment]
Integrated addresses have resulted in a lot of support requests by users, subaddresses are easier for the end user.

**Comment by crocket** [comment]
Why do end users need to understand address types in the first place?

**Comment by crocket** [comment]
> I strongly disagree that when a developer starts looking at the documentation, it is simpler that they will be be offered the choice of subaddresses vs integrated addresses vs integrated subaddresses. It's obviously much simpler for them to understand what to do next if they are just told to issue subaddresses.

I'm not even a good developer, but I understood the concept quickly. I understood it so quickly that I realized there could be integrated subaddresses even before having any amount of XMR.

You don't have to use integrated addresses. But, if you learn it, a little bit of time you spent on learning it will pay dividends over time because integrated subaddresses make things easier for development and administration.

**Comment by knaccc** [comment]
@crocket I can see that if there were a strong argument for integrated (sub)addresses, that we could get the best of both worlds. We'd prevent regular users from being able to create integrated (sub)addresses (by not implementing the ability to create them in the GUI), and only allow integrated (sub)addresses to be created by developers using the CLI or RPC API. People might be confused when they are given integrated addresses that are many characters longer than regular addresses, but a strong argument for integrated addresses could outweigh that confusion.

Unfortunately, I still don't understand what that strong argument is, and why it's a significant burden to add a row to a database for every subaddress issued. There would simply be a table with an auto-increment column for a subaddress index that would correlate to a user/transaction/shopping basket. You're going to need to use a database anyway, so it's not like subaddresses would be the only reason people would need to use a database at all.

Another privacy advantage of dropping integrated addresses that I should have mentioned before:

With integrated addresses, hosted wallets (MyMonero etc) and exchanges that log users' outgoing transactions will be able to observe whether users are paying the same business multiple times. If, instead, a non-integrated subaddress is issued for each transaction, hosted wallets will not have this visibility on repeat transactions to a vendor.

**Comment by crocket** [comment]
> With integrated addresses, hosted wallets (MyMonero etc) and exchanges that log users' outgoing transactions will be able to observe whether users are paying the same business multiple times. If, instead, a non-integrated subaddress is issued for each transaction, hosted wallets will not have this visibility on repeat transactions to a vendor.

If you use a hosted wallet or exchange as your payment wallet, you forfeit a lot of privacy benefits of monero. Subaddresses can help a bit if they are not reused. But, nothing prevents merchants from reusing subaddresses. Even if subaddresses are not reused for a long time, we don't know other ways that online wallets can compromise your privacy. I would not leave my money on online wallets for any longer than it is necessary.

In any case, using online wallets as the main wallet is a form of privacy leak for everyone.

> Should users be asked to forgive this privacy leak, so that you don't have to implement an auto-increment counter?

An auto-increment counter can easily create huge gaps for large websites. Ways to prevent huge gaps can be complex.

* Do you know any way to easily prevent address gaps without adding more cognitive burden or make them irrelevant?
* Any way to create subaddresses on the fly without unnecessarily exposing view key to networked services? The less interfaces a view key has to deal with, the better. The view key should ideally be only used for viewing the wallet.
* What about allowing only secret view key to extract base address and payment ID from integrated address? This would prevent privacy leak. Asymmetrical encryption is the key here. You can use only public keys to generate integrated address, but you need secret view key to extract components of integrated addresses.

**Comment by knaccc** [comment]
> Do you know any way to easily prevent address gaps

It takes a second of compute time for a wallet to add thousands of subaddresses to the look-ahead lookup table. So if you just set the wallet to look ahead by 50,000 subaddresses, there will be a pause for a few seconds when you first start the wallet. What kind of gaps were you expecting to see?

> Any way to create subaddresses on the fly without unnecessarily exposing view key to networked services?

Only with the private view key

> What about allowing only secret view key to extract base address and payment ID from integrated address?

That's what a subaddress is :)

**Comment by crocket** [comment]
> That's what a subaddress achieves :) Subaddresses were quite challenging to devise. If there were a way of issuing them without needing to create a lookup table, we'd have done it that way.

Subaddresses have two drawbacks.

1. Secret view key is required to generate them
2. Address gaps have to be accounted for. If you migrate between wallets, it can be frustrating.

Use one-time public key to encrypt base addresses in integrated addresses, and use secret view key to decrypt them?

**Comment by knaccc** [comment]
> Address gaps have to be accounted for. If you migrate, it can be frustrating.

I'm struggling to understand what kind of migration you might be imagining. You mean if you threw away your database that correlated the subaddress indices you'd issued to customers/shopping baskets/transactions etc? Why would you do that? If you did that and wanted to keep using the same wallet, you could just use a different account in that wallet and start from scratch.

I'm not sure what you mean by "account for address gaps". All you need is a counter that you increment by one every time you issue a subaddress. That's it.

Re: your suggestions: the cornerstone of the subaddress scheme is that it is vital that the same private view key is used for ECDH on the transaction public key, regardless of the subaddress issued. This is what keeps scanning time constant and prevents scanning time from increasing linearly with the number of subaddresses issued. After examining the subaddress scheme math, if you think you have an idea that preserves the constant scanning time property of subaddresses, it would be interesting to hear. I don't see how any of your suggestions would be compatible with that scanning time constraint.

**Comment by crocket** [comment]
> I don't see how any of your suggestions would be compatible with that scanning time constraint.

It's not a suggestion about blockchain. It could be a wallet-level feature or a node-level feature.

> I'm not sure what you mean by "account for address gaps".

There can be algorithms that guarantee there is little or no gap between subaddresses.
Auto-increment counter is not such an algorithm.
My aesthetic sense doesn't like gaps that can make a wallet lose track of money.

**Comment by crocket** [comment]
Possible solutions

* Make address gaps totally irrelevant whatsoever
* Apply address compression before creating a stealth address for monero blockchain.
  * Billions of subaddresses may be represented by an account address on the blockchain?

**Comment by knaccc** [comment]
> you can reduce scanning time in the long term
> a wallet may slow down or require a lot of RAM

The lookup table requires 32 bytes of storage for every subaddress issued. So an implementation storing a billion subaddresses in a lookup table would require 32GB RAM. So that's $200 of RAM for someone that is processing millions of transactions.

The harder part is that the lookup table with a billion subaddresses would take approx. 100 hours to generate, or 2hrs if it were GPU accelerated. This would be a one-time cost, and would be built up in small increments over long periods of time. It would not need to be re-computed if the wallet were restarted. A wallet scanning for a billion addresses would require about the same scanning time as if it were scanning for only a single subaddress. 

If you restored your wallet from scratch, you'd need to build the entire table up all at once. So if you really did issue a billion subaddresses, you'd have to A) Wait 100 hours or B) GPU accelerate it or C) Use a temporary AWS cluster.

> There can be algorithms that guarantee there is little or no gap between subaddresses

How would you do this? If you issue a subaddress to someone for payment, and they don't use it, then you could re-use it after a period of waiting. I don't know why you would consider it worth bothering to do that.

> Apply address encryption over integrated subaddresses as a wallet-level or a node-level feature
Unless you explain exactly how your ideas can work without increasing the scanning time linearly with the number of issued subaddresses, your ideas do not meet the basic criterion necessary to provide a workable solution.

**Comment by crocket** [comment]
> Unless you explain exactly how your ideas can work without increasing the scanning time linearly with the number of issued integrated subaddresses, your ideas do not meet the basic criterion necessary to provide a workable solution.

You don't pre-generate a list of integrate subaddresses. You generate integrated subaddresses on the fly. You don't scan integrated subaddresses on blockchain, either.

> Payment ID in a transaction will be encrypted with a shared secret (one-time random key known only to sender and recipient).

Why can't you use one-time random key to also encrypt base address in an integrated address?
Perhaps, can a personal node decrypt encrypted integrated addresses? If the node has one-time random key, the node can decrypt the address. Think of it as a node-level feature. It doesn't exist on blockchain.

> How would you do this? Perhaps you mean that if you issue a subaddress to someone for payment, and they don't use it, then you could re-use it after a period of waiting. I'd advise against that though.

If a payment is canceled, the subaddress used is reserved in a database for later reuse.
A subaddress is marked used only after it receives one payment.
You don't have to be a genius programmer to make this work, but it can be complex if you are not an experienced programmer.

**Comment by knaccc** [comment]
I recommend you learn more about the math behind how transactions to subaddresses are constructed so that you can make some more specific and fully explained suggestions. I can't make sense of anything you've suggested.

**Comment by crocket** [comment]
> I recommend you learn more about the math behind how transactions to subaddresses are constructed so that you can make some more specific and fully explained suggestions. I can't make sense of anything you've suggested.

Are you too tired? The concepts I suggested are not difficult to grasp.

**Comment by knaccc** [comment]
> If someone tries to send monero to your one-time address

Once you take the time to understand how transactions are created, you'll realize that one-time addresses need to be created by the sender and not the recipient.

> You encrypt integrated address and let a customer advertise a transaction with the encrypted integrated (sub)address

Encrypt how? If you literally mean just encrypt it, then how do you create sensical transactions? Again, you've not understood how transactions are created.

You fundamentally don't understood how transactions are created, which is why your suggestions are non-sensical.

**Comment by crocket** [comment]
> If you throw away the normal transaction creation process and just directly write into the transaction a one-time address specified by the recipient, then multiple transactions to the same one-time address will be linkable on the blockchain.

As I wrote, I'm just a monero beginner. I don't yet know how monero crafts transactions. Where do I start?

**Comment by jonathancross** [comment]
> As I wrote, I'm just a monero beginner. I don't yet know how monero crafts transactions. Where do I start if I want to learn some technical details of transaction?

https://web.getmonero.org/library/Zero-to-Monero-2-0-0.pdf

**Comment by selsta** [comment]
Closing as this won't get implemented.
