### ISSUE TITLE
Beacon chain P2P error faild to find peers

### ISSUE THREAD

**Issue by Robelsan** [monero-project/monero#7095]
Hello everyone,
i've an issue with the beaconchain mainnet related to the p2p error attached, can anyone help with this?

Thank you so much in advance
![p2p error beaconchian](https://user-images.githubusercontent.com/75683847/101500047-38f99a80-396e-11eb-9a75-a93dd72a7f81.PNG)

**Comment by moneromooo-monero** [comment]
I assume beaconchain is an altcoin ? If so, it's a different project than Monero. Find their issue tracker.
