### ISSUE TITLE
Add wallet name/path to the inactivity lock message.

### ISSUE THREAD

**Issue by normoes** [monero-project/monero#7126]
I very much like and appreciate the locking of the wallet.

Since I tend to work with several wallets in all the Monero networks it is quite confusing to see the same lock message everywhere.

It would be nice to have the wallet name (file name) or complete file path in the lock message (maybe even along with the network mode):
It could look like this:
```
 ____________________________________________   
/ I locked the '<my_wallet_file_name_here>' Monero 'mainnet' wallet to protect you \
| while you were away                        |
\ see "help set" to configure/disable        /
 --------------------------------------------
```
instead of just:
```
 ____________________________________________   
/ I locked your Monero wallet to protect you \
| while you were away                        |
\ see "help set" to configure/disable        /
 --------------------------------------------
```

**Comment by normoes** [comment]
Is `m_wallet_file` in https://github.com/monero-project/monero/blob/master/src/simplewallet/simplewallet.cpp the right variable to use?

How can I easily  getthe network mode? I bet there is a variable as well.

**Comment by moneromooo-monero** [comment]
Yes. See wallet_info, do the same. Put the (user selected) name in the text below, not the cow speech.

**Comment by normoes** [comment]
Understood. Thanks.

**Comment by normoes** [comment]
So, the result looks like this.
* Nothing changed in the cow speech.
* See the lnked PR https://github.com/monero-project/monero/pull/7153.
```
 ____________________________________________   
/ I locked your Monero wallet to protect you \
| while you were away                        |
\ see "help set" to configure/disable        /
 --------------------------------------------
        \   (__)
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


Locked due to inactivity. The wallet password is required to unlock the console.
Filename: <my_wallet_file_name_here>
Network type: Stagenet
Wallet password: 
```

**Comment by bill-mcgonigle** [comment]
Can we make this 'set'-able and a non-default behavior?  I have use cases where I would 'set' it, but if we assume that locking exists for the scenario where somebody walks away from their screen and we're protecting that user from would-be troublemakers, having the wallet name on the lock screen may be too big of an information disclosure in some situations.

**Comment by moneromooo-monero** [comment]
That's a fair point.

**Comment by normoes** [comment]
@moneromooo-monero 
The suggestion above is implemented:
```
set show-wallet-name-when-locked 1|0
```

Could you please check?

**Comment by selsta** [comment]
This seems resolved.
