### ISSUE TITLE
Sending a tx with Mac GUI Ledger not showing address on Ledger

### ISSUE THREAD

**Issue by songproducer** [monero-project/monero#7148]
No way to confirm address using Ledger screen

**Comment by jonathancross** [comment]
If this is specific to the GUI, it should be submitted to the [monero-gui](https://github.com/monero-project/monero-gui/issues) repo.

**Comment by selsta** [comment]
@songproducer are you using the latest firmware, Ledger live version and ledger monero version?

**Comment by songproducer** [comment]
Yes

**Comment by songproducer** [comment]
I believe so
Ledger Live 1.2.4-5
Leder Monero App 1.7.5
Monero GUI 0.17.1.6-cc352e4 (Qt 5.12.8)
Embedded Monero version: 0.17.1.6-cc352e491

**Comment by selsta** [comment]
So the only problem is that you can't verify the receiving address? Or can't you send at all?

**Comment by songproducer** [comment]
The only issue is I can't verify the address. I don't want to send without verifying the address first.

**Comment by selsta** [comment]
Works as expected here.

You first accept the fee, then change and then the amount and destination address.
