### ISSUE TITLE
The address created during synchronization is missing

### ISSUE THREAD

**Issue by caozi522** [monero-project/monero#7171]
Someone transferred xmr to the address during synchronization

**Comment by Agorist-Action** [comment]
Transferring XMR during synchronization does not lead to your funds disappearing.

**Comment by caozi522** [comment]
> Transferring XMR during synchronization does not lead to your funds disappearing.

But the address disappeared when I opened the wallet again

**Comment by moneromooo-monero** [comment]
If you want to report a bug, give details if you intend something to be done about it.

**Comment by moneromooo-monero** [comment]
Reopen if any details or explanation can be given.
