### ISSUE TITLE
After the remote node synchronization is completed, there is no transaction displayed

### ISSUE THREAD

**Issue by mifankk** [monero-project/monero#7177]
After the synchronization of the remote node is completed, there is no transaction record, but when I check the provc / check, it is verified to be successful. What should I do if I query that there is such a transaction?

**Comment by dEBRUYNE-1** [comment]
Can you open a new thread on r/monerosupport (reddit) and close this issue? Github is not particularly suitable for support, as it is a bug / issue tracker.
