### ISSUE TITLE
lots and lots of  SYNCHRONIZED OK messages

### ISSUE THREAD

**Issue by unamefailed** [monero-project/monero#7187]
600+  lines
https://paste.debian.net/1178269/

**Comment by foodv** [comment]
is printing  all the time after reboot

**Comment by selsta** [comment]
You can ignore these messages. Please apply the latest block list while this attack is ongoing: https://gui.xmr.pm/files/block_tor.txt

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/7189 should fix that, some nodes were claiming data but then only supplying existing but no new actual data.

**Comment by BKdilse** [comment]
I'm also seeing this, along with the 2 blocks ahead on Daemon.
@selsta I've already applied a block last week, I'll try the latest file now.

**Comment by BKdilse** [comment]
@selsta actually I applied https://gui.xmr.pm/files/block.txt
Do I also need https://gui.xmr.pm/files/block_tor.txt ?

**Comment by rblaine95** [comment]
> 
> 
> @selsta actually I applied https://gui.xmr.pm/files/block.txt
> Do I also need https://gui.xmr.pm/files/block_tor.txt ?

As far as I know, `block_tor.txt` includes all the IPs in `block.txt` but also adds some tor exit nodes

**Comment by selsta** [comment]
v0.17.1.8 is out: https://www.getmonero.org/downloads/

**Comment by BKdilse** [comment]
Thanks, I already compiled the tagged release earlier today, after seeing the 2 block ahead issue coming back due to more dodgy nodes.  Can confirm, it appears to be resolved.
