### ISSUE TITLE
Wallet (auto)save not working / Wrong filename

### ISSUE THREAD

**Issue by TheNec** [monero-project/monero#7214]
The wallet's name is "wallet" but according to the log it can't write to "wallet".new

As the last write date to the file is 2019-11-25 the problem started most probably with v0.15.0.

Thank you in advance and best regards!

**Comment by moneromooo-monero** [comment]
Are you *sure* you have enough space, permissions on that directory, etc ?

**Comment by TheNec** [comment]
Thanks for your quick response!

_Sure_ is such a big word... ;)

Last year I installed/changed from CLI to GUI including moving the wallet files from former installation path at %programdata% to %programfiles%. So on the one hand if I start the software as admin it indeed works now but on the other hand the log message is misleading and/or a hint would be very nice. Also the CLI still searches for wallet files in the installation directory.

So this may be a low priority feature request or bug report.

**Comment by moneromooo-monero** [comment]
What is the actual message that's misleading ?

**Comment by TheNec** [comment]
The Error saving wallet.new and failed to generate wallet keys.new look like that the software has problems with the filename and not that it is a permission problem.

**Comment by selsta** [comment]
Permission issue was resolved by issue creator.
