### ISSUE TITLE
monero-wallet-rpc stuck at "Starting wallet RPC server"

### ISSUE THREAD

**Issue by vceylan** [monero-project/monero#7215]
I upgraded monero node successfully and can get latest block etc. info. When i try start wallet rpc it is showing info below and not continue:

![image](https://user-images.githubusercontent.com/4114128/103220028-47fdb800-4930-11eb-8fe3-676f90a8e7d7.png)

This is my config file:

![image](https://user-images.githubusercontent.com/4114128/103220087-724f7580-4930-11eb-8d84-6250f4adfeef.png)

Please help!

**Comment by moneromooo-monero** [comment]
Post the JSON you're sending as well as the response you get (or whether it times out without a response).

**Comment by vceylan** [comment]
Thanks for your reply. My problem was on connection to wallet. i didn't open wallet from my integration and couldn't connect.
My installation was correct.
