### ISSUE TITLE
Delayed transaction broadcast with --tx-proxy

### ISSUE THREAD

**Issue by Ashaman-** [monero-project/monero#7223]
A transaction sent with a daemon that was just launched with i2pzero --tx-proxy flags will fail to broadcast if the node has not yet made connections to any other nodes over i2p. While I've had this happen a few times, it was never a problem until today wnen it did eventually broadcast - hours later, well after the merchant invoice it was for had expired. I'm not sure what eventually dislodged it and got it broadcast, the only event I can attribute it to was my triggering of 'systemctl restart monerod'

It seems like better handling of tx-proxy transactions is needed rather urgently. Perhaps some kind of detection to identify failed broadcasts and rebroadcast them, along with the option to automatically drop any tx that has failed to broadcast for a user defined quantity of minutes.

**Comment by aquilacooper** [comment]
See #6938. A workaround for this issue is adding the `disable_noise` parameter to the `--tx-proxy` option.

**Comment by xanoni** [comment]
Would this also happen if the node had two `--tx-proxy` flags, one for Tor and one for I2P?

**Comment by selsta** [comment]
Should be solved by #8326
