### ISSUE TITLE
Segmentation error when syncing Armv8 Rock64

### ISSUE THREAD

**Issue by SomaticFanatic** [monero-project/monero#7259]
Constant segmentation faults when syncing new node from scratch on RockPro64 Armv8 using binaries downloaded from GetMonero.org. Error happens perhaps every 10% synced, and not with any regularity. Sometimes can go 25% before erroring, sometimes just 3%. Happens both on pruned and non-pruned syncs.

`sudo ./monerod --restricted-rpc --ban-list block_tor.txt --prune-blockchain --log-level 2`

Note: I have to run monerod as sudo or else it says Permission denied.

Daemon log: https://pastebin.com/u1b0yHxf

Gdb: https://pastebin.com/TA7Hfe13

**Comment by moneromooo-monero** [comment]
Are you always using the same storage device ?

**Comment by SomaticFanatic** [comment]
Yes

**Comment by moneromooo-monero** [comment]
Use another.

**Comment by SomaticFanatic** [comment]
I don’t understand. Right now I’m syncing via a SSD on the USB3 port. Are you saying I should try another drive or not use USB to SSD at all?

**Comment by SomaticFanatic** [comment]
New GDB: https://pastebin.com/vn8hBbU7

**Comment by moneromooo-monero** [comment]
Yes. A crash in cryptonote::BlockchainLMDB::compare_uint64 hints at a broken database, and a broken database several times in a row hints at hardware failiure.

**Comment by moneromooo-monero** [comment]
The new stack looks more like memory corruption though.

**Comment by SomaticFanatic** [comment]
> Yes. A crash in cryptonote::BlockchainLMDB::compare_uint64 hints at a broken database, and a broken database several times in a row hints at hardware failiure.

Should I try a different SSD or switching away from USD>SSD altogether and use the MicroSD card slot?

**Comment by moneromooo-monero** [comment]
The microsd sounds like it's totally different hw so is best to try that.

**Comment by selsta** [comment]
#7271 might be related

**Comment by komatom** [comment]
Monerod recently closes itself without reasons on my node on Ubuntu 20.04, I though .8 point version would fix it, but apparently ti is not, it continues to do that.. just kills itself after an hour or so.

**Comment by SomaticFanatic** [comment]
I moved to a different SSD and it still errored. I moved to a MicroSD and it errored. Perhaps memory corruption? I ordered a new Rock board so hopefully that fixes it.

**Comment by selsta** [comment]
@komatom See here: https://reddit.com/r/Monero/comments/ko3d1n/third_update_on_the_ongoing_network_attacks/

**Comment by SomaticFanatic** [comment]
@selsta Is the bug confirmed and is it fixed?

**Comment by selsta** [comment]
@SomaticFanatic do you know how to compile a specific PR? #7309 might resolve your issue.

**Comment by SomaticFanatic** [comment]
@selsta I do. Will compile and get back to this

**Comment by SomaticFanatic** [comment]
@selsta Built from scratch. Sync from scratch. Seg fault.

**Comment by selsta** [comment]
Ok, that means 7309 is not related to your issue.

**Comment by selsta** [comment]
@SomaticFanatic can you try compiling a debug build and then doing `thread apply all bt` in gdb?

**Comment by SomaticFanatic** [comment]
@selsta I tried `make debug` and it freezes at 81%. I tried increasing swap file to 6GB and it doesn't matter. Still freezes at 81%: https://pastebin.com/mD9S5keW

**Comment by SomaticFanatic** [comment]
If you want I can remove the -d flag for a less noisy output

**Comment by selsta** [comment]
You can do

make -C path/to/build/directory daemon

to build only daemon.

Build will take a while so be patient. Build directory is where e.g. the bin folder is inside.

**Comment by selsta** [comment]
Also which distro are you using from here? https://wiki.pine64.org/wiki/ROCKPro64_Software_Release#Armbian

**Comment by SomaticFanatic** [comment]
If I do make -C build/directory daemon it says 

make *** No rule to make target ‘daemon’. Stop. 

and quits. The distro I’m using is https://github.com/ayufan-rock64/linux-build/releases/tag/0.9.14 Ubuntu 18

**Comment by SomaticFanatic** [comment]
@selsta 7309 was merged. Built from current master, began sync from scratch, and it is still segfaulting. Should I do the gdb?

**Comment by selsta** [comment]
@SomaticFanatic Can you use https://paste.debian.net/hidden/c939360a/ to make a debug build and then try to reproduce the segfault under gdb?

**Comment by selsta** [comment]
https://forum.pine64.org/showthread.php?tid=11209&pid=76615#pid76615

Could it be that the Rock64 is simply unstable during high load? Can you try reducing memory clock?

**Comment by selsta** [comment]
ping @SomaticFanatic, did you check regarding memory clock? Otherwise I will close this issue.
