### ISSUE TITLE
New Monero Wallet GUI update is too big for my screen and I can't resize it.

### ISSUE THREAD

**Issue by ImNotASheep** [monero-project/monero#7305]
Just downloaded the latest version of GUI wallet and when I opened it for the first time, the whole interface (including text) is enlarged compared to older versions. I cannot access the top bar to close/minimise/maximise, nor can I access the resize tool in the bottom right corner. Any way to manually resize the wallet before starting the .exe? Link to screenshot of problem: https://imgur.com/a/POOtFov

**Comment by selsta** [comment]
We now have high dpi support, previously everything was too small on high dpi screens. Did you set scaling inside Windows? How large is your screen?

**Comment by selsta** [comment]
Did you start using the "start-high-dpi.bat" file?

**Comment by ImNotASheep** [comment]
> Did you start using the "start-high-dpi.bat" file?

No, I started using the usual monero-wallet-GUI.exe

**Comment by jonathancross** [comment]
Hi @ImNotASheep 
Did `start-high-dpi.bat` work?
This should be moved to the [monero-gui](https://github.com/monero-project/monero-gui) repo if still an issue.

**Comment by selsta** [comment]
We don't ship start-high-dpi.bat anymore, Windows now supports high dpi scaling.

**Comment by jonathancross** [comment]
This should be moved to the monero-gui repo if there is still problems.
