### ISSUE TITLE
--restore-height CLI option not honored by monero-wallet-cli

### ISSUE THREAD

**Issue by robby-dermody** [monero-project/monero#7307]
had issues getting `--restore-height` to be honored with monero-wallet-cli. I tried a command like `./monero-wallet-cli --generate-from-device myledger --restore-height 0` and the wallet still prompts with "No restore height is specified." -- this is newest release, on OS X Big Sur.

@moneromooo-monero responded on IRC that it looked like a bug and posted this (potential) fix: https://paste.debian.net/hidden/938e4dd5/

I will attempt to test this later once I can get the time to recompile the source. Posting this here for documentation of the issue.

**Comment by selsta** [comment]
I noticed this bug too.

@robby-dermody please open a PR if your patch passes testing.

**Comment by hyc** [comment]
I'd say restore-height=0 is meaningless since nobody owns any txns in block 0. Just use restore-height=1 instead.

**Comment by selsta** [comment]
If the patch is small I don’t see why we shouldn’t change this. Specifying --restore-height 0 and then getting the "no restore height specified" is not good user experience.

**Comment by robby-dermody** [comment]
Agreed with @selsta as it removes the requirement of additional domain specific knowledge from the user. Also, the monero-wallet-cli command line help states: `--restore-height arg (=0)             Restore from specific blockchain height`, which made me think that specifying 0 was both the default and perfectly acceptable.

**Comment by robby-dermody** [comment]
@selsta I would open a PR, but it seems the Debian paste snippet expired, and I have no familiarity with the Monero codebase. Perhaps you or @moneromooo-monero could PR a fix that takes the feedback above on better user feedback if 0 is specified in mind? Sorry about that.
