### ISSUE TITLE
error when opening monero gui  

### ISSUE THREAD

**Issue by sexboyrichcult** [monero-project/monero#7314]
i just downloaded monero gui yesterday 1/11/2021. i also downloaded the monero app onto my ledger nano x (version 1.7.5) now when trying to login this comes up 
_wrong device status :  0x6e00 (SW_CLA_NOT_SUPPORTED),EXPECTED 0x9000 (SW_OK),MASK 0xffff_

**Comment by selsta** [comment]
Please try to restart your computer and make sure that monero ledger app is open and Ledger Live is closed.

**Comment by sexboyrichcult** [comment]
wow that was easy thank you !
