### ISSUE TITLE
monero-wallet-cli

### ISSUE THREAD

**Issue by spitrip82** [monero-project/monero#7316]
hello 
after accessing monero-wallet-cli  ./monero I started mining with the command: start_mining (my wallet adress) 1
after starting to mine I ran the command: mining_status 
and the result was this :

mining_status
Mining at 101 H/s with 1 threads
PoW algorithm: RandomX
Mining address: 44AQ4WuLq9UYVaSyQBDMgT5y7ETxZ1enBLbjaXu4B8jgGXTZVKFV4GBVuKEqQyD1baGAzUX8dcs3PhkEV4eHXkSESGKsFrn
Expected: 0.000045739943 monero daily, 0.001395068269 monero monthly, 0.016283419795 yearly
 
my question is, how will I be able to see how many moneros I've already made and when will I receive it in my wallet?

**Comment by moneromooo-monero** [comment]
You'll get an incoming tx in your wallet whenever you mine a block.
As this rate though, it'll be with an expected time to a block of about... 1.2/0.016283419795 == 73 years. It's a lottery, and you don't have many tickets. Good luck!
