### ISSUE TITLE
Don't corrupt database on unsafe shutdown

### ISSUE THREAD

**Issue by sonatagreen** [monero-project/monero#7320]
It should be possible to structure writes in such a way that the data on disk is never in a state corresponding to a corrupted database.

Temporary workaround: periodically do the following:
1. (at daemon console) `save`
2. (at daemon console) `exit`
3. (at OS shell) `$ cp /path/to/lmdb/data.mdb /path/to/lmdb/data.mdb.bak`
4. re-start daemon

**Comment by trasherdk** [comment]
How about 
```bash
monerod --rpc-bind-port 18083 save     
2021-01-17 07:14:49.511 I Monero 'Oxygen Orion' (v0.17.1.9-release)
Blockchain saved
```

**Comment by selsta** [comment]
```
--db-sync-mode safe
```

**Comment by sonatagreen** [comment]
> ```
> --db-sync-mode safe
> ```
\>_< Thanks.
