### ISSUE TITLE
sweep_all command does not store recipient's address and payment id

### ISSUE THREAD

**Issue by AJIekceu4** [monero-project/monero#7360]
Hello. I am using CLI version Monero 'Oxygen Orion' (v0.17.1.7-release) wallet. And found out that after using sweep_all command and transfer balance to integrated address (Kraken), command show_transfers did not show recepient's address or payment id. It is just show "0000000000000000" and "-" instead of payment id and address. Before this i was use "transfer" command to the same integrated address multiple times and everything is ok.
If i use show_transfer txid, then i see same problem:

> Payment ID: 0000000000000000
> Change: 0.000000000000
> Fee: 0.000011410000
> Destinations:

**Comment by moneromooo-monero** [comment]
Addresses do get stored here. It might due to particular non default conditions on your side ?
Encrypted payment IDs are only decodable by the recipient, so they won't show for the sender.

**Comment by AJIekceu4** [comment]
> Addresses do get stored here. It might due to particular non default conditions on your side ?
> Encrypted payment IDs are only decodable by the recipient, so they won't show for the sender.

Hello. I was do as always (as i remember it): opened a wallet, entered a passphrase, typed "refresh", wait until refresh is finish, after this typed "sweep_all address_from_kraken", entered password and transaction confirmation (i use my remote node in all cases). After i get transaction ID, closed wallet (did not wait until transaction get 10 confirmation or wallet became blocked) by closing terminal in which wallet was started (did not use exit command, just closed terminal window with mouse click). All previous transactions from this wallet i was doing the same way (maybe close wallet after it blocked with passphrase, can't remember now) and all recipients information was stored.

**Comment by moneromooo-monero** [comment]
"closed terminal window with mouse click" means killing the window with the usual x button ? If so, you're killing monero-wallet-cli before it has a chance to save the wallet cache.

**Comment by AJIekceu4** [comment]
> "closed terminal window with mouse click" means killing the window with the usual x button ? If so, you're killing monero-wallet-cli before it has a chance to save the wallet cache.

Ok, thanks. I will close this issue then.
