### ISSUE TITLE
View only wallet shows incorrect balance

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero#7365]
In the Windows GUI I created a view only wallet, and it shows an incorrect balance... like I only received, but never spent anything. So the balance is higher than it's supposed to be.

I have also tried to create the wallet in the monerujo android wallet using my address and viewkey secret, and the same incorrect balance is shown. Using the most recent version of Monero. The full wallet has two accounts, maybe that has something to do with it? I don't know.

**Comment by moneromooo-monero** [comment]
Are you sure you correctly imported key images ?

**Comment by voidzero** [comment]
Yeah, well in the gui there's only a button so that's why I used that one to verify. In monerujo I added my public address and my private view key. I added the correct block number - one below my first transaction (incoming). All incoming transactions show properly but the outgoing just do not show up. I'll try it again from the Linux cli later today, but this does already appear to be a bug at least from the GUI and monerujo.

**Comment by voidzero** [comment]
Ok, used the monero-wallet-cli utility to create a view only wallet as described in <https://www.getmonero.org/resources/user-guides/view_only.html>. Same issue: only inputs, no outputs. However, I get this text here:

`Some owned outputs have missing key images - import_key_images needed`

**Comment by selsta** [comment]
You have to import your key images.

Please see https://monero.stackexchange.com/questions/7217/view-only-wallets-only-shows-incoming-transactions-only-how-to-see-outgoing-asw

**Comment by voidzero** [comment]
Oh! There you go. Thank you, @selsta. Maybe who manages the getmonero.org website could make a note of this on that page I posted.

**Comment by voidzero** [comment]
I also need to learn how to read. Because it does say:

_If your wallet has outgoing transactions, the balance displayed will not be correct. To get a correct balance in a view-only wallet, you have to import the accompanying key images of each output of the wallet._

Sorry about that. Still, the *how* could be posted to the page.

**Comment by voidzero** [comment]
Again my apologies for not reading the page thoroughly and the invalid bug. I will go ahead and close this and I apologize for taking up your time.
