### ISSUE TITLE
Prevent randomx from polluting monerod log.

### ISSUE THREAD

**Issue by crocket** [monero-project/monero#7372]
Unless huge pages are enabled by a command like `sysctl vm.nr_hugepages=1280`, randomx large page allocator keeps printing exceptions in monerod log.

It occupies almost 100% of monerod log. I can't analyze monerod log at all because of the large page allocator exceptions.

This problem should be documented or fixed properly.

**Comment by selsta** [comment]
Fixed in https://github.com/tevador/RandomX/pull/241
