### ISSUE TITLE
seed generates a different wallet

### ISSUE THREAD

**Issue by bissiol** [monero-project/monero#7386]
I was restoring my wallet from seed and my 25 word seed is generating a different primary address from the original wallet I created (and funded).
Seed's words are in Italian.
25th word is the same of 24th.
I tried with 24-word (without the last) and the result is the same primary address. 
I tried to restore from CLI and from GUI with same result.
I'm sure that I didn't use an offset passphrase when I generated the wallet.
I tried to change language of GUI app to Italian and to English with same output (always the same primary address that doesn't match my original one).
Please help.... maybe I lost funds?

**Comment by bissiol** [comment]
Ok I understand that is normal that last word repeats one of the 24 seed words...

**Comment by selsta** [comment]
Which wallet did you use to generate the initial address? CLI?

**Comment by bissiol** [comment]
> Which wallet did you use to generate the initial address? CLI?

The same I used to (try to) restore: monero-wallet-cli

Thanks for your reply

**Comment by selsta** [comment]
Do you still have the original wallet file? I assume no?

**Comment by bissiol** [comment]
> Do you still have the original wallet file? I assume no?

No. Only two paper backups

**Comment by selsta** [comment]
Do you know which version was used to originally create the wallet?

Try to download the old version and restore the wallet using it.

**Comment by bissiol** [comment]
> Do you still have the original wallet file? I assume no?

No. Only two paper backups

> Do you know which version was used to originally create the wallet?
> 
> Try to download the old version and restore the wallet from seed with it.

I will try old versions. Do you know other issues about this version's difference in seed-to-address?

**Comment by selsta** [comment]
> Do you know other issues about this version's difference in seed-to-address?

No, that's why I suspected accidental seed offset used, but you said that's not the case.

**Comment by elibroftw** [comment]
@bissiol did you set the seed language in the CLI before you tried restoring from seed?

**Comment by selsta** [comment]
No reply from issue author and no steps to reproduce.
