### ISSUE TITLE
Code styling and indentation

### ISSUE THREAD

**Issue by stnby** [monero-project/monero#7395]
I honestly do not know why and how someone allowed this to happen but the code base is literally so uneven that I have seen enough random indentation (*2 spaces seriously, functions in the same source file having multiple different styles?*).

I think enforcing [Linux kernel coding stye](https://www.kernel.org/doc/html/latest/process/coding-style.html) or some alternative as the code is C++ after all. I think this would greatly increase codes readability.

**Comment by moneromooo-monero** [comment]
No reindent spam please.

**Comment by xanoni** [comment]
Some projects care, others don't. Seems this project doesn't ;-)

Off topic, but I think tickets should be closed faster. I see a lot of very outdated or irrelevant tickets.

**Comment by selsta** [comment]
Monero forked from a project that already had messy indentation and we didn't want to auto format the whole project as it spams the git history.
