### ISSUE TITLE
Daemon RPC Connection Failure

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#7411]
I'm still getting connection timeouts when mining to the daemon. Today I started up two machines that had been shut down and started xmrig and they would not get any new jobs even when there was no connection error in the proxy. Restarting the Monero Daemon temporarily solved the problem. The connection errors I get when connected to the Monero Daemon are happening very often throughout the day. At this point I am wondering, am I even mining anything because there are so many connect errors to the daemon. There is something seriously wrong here that needs to be addressed and I haven't heard hide nor hair of the Monero team about this. Ten days after submitting my first report about this problem it would be nice to hear at least "we're looking into it", "we're working on it" or "it's a bug" instead of radio silence. Show some respect for the people that are trying to help the Monero project instead of completely ignoring them.

**Comment by vdero133** [comment]
Could you run monerod with `--log-level 4` and post the logs?  (or point me to where you posted them, did not see them elsewhere), I only saw the ones from xmrig.

**Comment by downystreet** [comment]
I ran log level 4 however when I go to find the log file that corresponds to the time when the connection timeout occurred it seems it doesn't exist. I have several log files in the .bitmonero directory but they only span a 3 hour period while log level 4 has been running for more than 10 hours. I am assuming that the Monero daemon uses Universal Time and calculated the times accordingly. I am also assuming that the numbers of the bitmonero.log file correspond to bitmonero.log-year-month-day-hour-minute-second. Do you want to see the logs from when there is no connection timeout? Is there something I'm skipping over?

**Comment by moneromooo-monero** [comment]
monerod only keeps 50 log files by default, it'll delete the oldest ones when it reaches that many.
There's a monerod command line option to change this.

**Comment by downystreet** [comment]
Daemon RPC connect error occurred in xmrig proxy from 17:28-17:30 UTC. The Monero daemon log is available from the zip file.
[monerodlog.zip](https://github.com/monero-project/monero/files/6063591/monerodlog.zip)

**Comment by mrx23dot** [comment]
For me RPC is unresponsive when it's syncing:
https://github.com/monero-project/monero/issues/7431

**Comment by selsta** [comment]
There have been larger monerod code changes in the last 2 years, if this issue persists in the latest version please open a new issue.
