### ISSUE TITLE
wallet_rpc: generate_from_keys not setting seed language

### ISSUE THREAD

**Issue by camthegeek** [monero-project/monero#7414]
When restoring with keys via wallet-rpc method `generate_from_keys`, the **wallet seed language is not set**.

The wallet is created on the wallet-rpc server and does operate normally, however, when trying to request the mnemonic via query_keys, result is 'Failed to get seed'.

Upon entering wallet using CLI and typing `seed`, the wallet returns with `seed_language not set`.

Could we default to English on this function but have the ability to define which language to restore in?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/7430

**Comment by camthegeek** [comment]
7430 does fix this issue. 

Thanks
