### ISSUE TITLE
blocks sync : last 2%  is slow

### ISSUE THREAD

**Issue by unamefailed** [monero-project/monero#7421]
it's a VPS , SSD hard disk  

From 0 to 98% took 9 hours,  The last 40000+  blocks(2%) has been working several hours  and it says "I Synced 2280357/2309052 (98%, 28695 left, 24% of total synced, estimated 5.9 hours left)" , I have tried restarting  monerod  and rise out_peers to 60 But still slow . 
 is it normal?

**Comment by selsta** [comment]
There has been no new release in ~2 months, meaning the last fast sync checkpoint is also 2 months old. This is normal.

**Comment by hardrun744** [comment]
See #7521

**Comment by velvetbailiff** [comment]
View #7523
