### ISSUE TITLE
Error: transaction was not constructed, when sending to integrated address in batch transfer

### ISSUE THREAD

**Issue by xmrvsbeast** [monero-project/monero#7423]
Hi,

When I try to send funds to 1 integrated address in a batch transfer along with standard addresses I am getting " transaction was not constructed" error.  I have tried v0.17.1.9-release and v0.17.0.0-b8f3e44a3

thank you

**Comment by hardrun744** [comment]
Check out #7521

**Comment by velvetbailiff** [comment]
#7523

**Comment by SneakyPlant43** [comment]
Have a look at #7527

**Comment by wideFaint903** [comment]
See #7532

**Comment by finelyscuff** [comment]
See #7534

**Comment by YetCord** [comment]
Check out #7536

**Comment by moneromooo-monero** [comment]
Works for me, with a transfer to a standard address and an integrated address from another address:

> curl -k -X POST http://127.0.0.1:8888/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"transfer_split","params":{"destinations":[{"address":"9zuzDZX1nyZNBKrGSkY6FJ3vw4S9dGT5VPaaaMmdc8AQba6g8akpJrKKfHDgH4fF4LFKeWDZ4r9AoV9h9irQ9SCGR1uHcku","amount":1000000000000},{"address":"A9cx1nh6Dr2PHNjzkdKTMy5E7uvf85eNtZmuDQ3FLJrq3TeMy9cEaEi5CK7FqXNboWKHBvLGAxHFB5gq8KpSxmgJabnvhrbEKPNHWCowqH","amount":1000000000000}],"fee":50000000000,"mixin":10,"unlock_time":0, "trusted_daemon":true,"do_not_relay":false,"get_tx_hex":true,"get_tx_metadata":true}}' -H 'Content-Type: application/json'

You might have particular preconditions, or it might be unrelated to integrated addresses. Can you give more info ?
