### ISSUE TITLE
Incorrect Balance Total

### ISSUE THREAD

**Issue by LotannaEzenwa** [monero-project/monero#7426]
Good Morning,

I am trying to verify the total monero balance on my primary and created addresss.

I created 2 addresses, and made transactions to each.

I am able to verify that these created addresses received the correct amount of monero via the monero-gui and two third party blockchain analyses. 

My wallet is also completely synced 100+ blocks past either transaction.

However, when using `balance` in the cli, and using the gui, my total balance is shown as 0.00000000. Also, using `show_transfers in` gives no transactions.

I have a Trezor wallet, and I am connected to a remote node.

Please advise.

**Comment by moneromooo-monero** [comment]
Are the GUI and CLI running on the same wallet file ? What are third party blockchain analyses ?

**Comment by LotannaEzenwa** [comment]
Yes, GUI and CLI are running on the same wallet file. 

Third party blockchain analyses are 
https://blockchair.com
and
https://xmrchain.net

**Comment by moneromooo-monero** [comment]
Does show_transfers show anything ?

**Comment by LotannaEzenwa** [comment]
`show_transfers` shows nothing

**Comment by moneromooo-monero** [comment]
Does incoming_transfers show anything ?

**Comment by LotannaEzenwa** [comment]
"No incoming transfers"

**Comment by moneromooo-monero** [comment]
What is the value of refresh-from-block-height in the output of "set" ?

**Comment by LotannaEzenwa** [comment]
Value is 2289630

**Comment by moneromooo-monero** [comment]
At what block heights did the incoming txes get mined ?

**Comment by LotannaEzenwa** [comment]
The first was slightly after 2310000, both within 100 blocks of each other.

**Comment by moneromooo-monero** [comment]
What does "status" show in the wallet ?

**Comment by LotannaEzenwa** [comment]
"Refreshed 2310331/2310331, synced, daemon RPC v3.2, SSL"

**Comment by moneromooo-monero** [comment]
Did the incoming txes go to accunts or addresses with large minor or major indices ?

**Comment by LotannaEzenwa** [comment]
Please clarify 'large minor or major indices'.

Txns went to addresses 1 and 2.

**Comment by moneromooo-monero** [comment]
Small enough. What is the value of subaddress-lookahead in the output of "set" ?

**Comment by LotannaEzenwa** [comment]
Ah, subaddress lookahead is "5:20"

**Comment by moneromooo-monero** [comment]
So, to make sure I understand, the CLI shows no transactions and the GUI shows transactions on the same wallet file ?

**Comment by LotannaEzenwa** [comment]
Yes, both show no transactions on the same wallet file.

**Comment by moneromooo-monero** [comment]
If the GUI also shows no transactions, what did you mean by: I am able to verify that these created addresses received the correct amount of monero via the monero-gui

**Comment by LotannaEzenwa** [comment]
I received two txn ids from a sender, then used those txn id in the gui (and on third party analyses) along with my generated addresses to generate txn proofs within the GUI.

Then I used those txn proofs generated in the GUI to verify the amount sent to each address. i.e. the GUI created an alert which read something along the lines of "Address XXXXX received YY.Y Monero"

**Comment by selsta** [comment]
Did you use different accounts? Can you restore your wallet with a different remote node? E.g. node.xmr.to 18081

**Comment by moneromooo-monero** [comment]
And you're really sure you are looking in the right wallet (sorry) ?

**Comment by LotannaEzenwa** [comment]
@moneromooo-monero no worries, I am sure I am looking in the right wallet. I have just reverified using only copy/paste.

@selsta How would I go about doing that?

**Comment by moneromooo-monero** [comment]
"rescan_bc" (after setting your daemon to another, there are many asshole nodes offering public RPC, might be lying about txes, always run your own node if you want to be secure - might not be the cause here though, but it certainly looks odd)

**Comment by LotannaEzenwa** [comment]
`rescan_bc` worked and the txns have appeared in total balance. Thank you both for your assistance.

I was using moneroworld.com's nodes, for all who may see this in the future. `node.xmr.to:18081` worked.

**Comment by selsta** [comment]
moneroworld aggregates "trusted" nodes so I doubt that asshole nodes were the culprit here.

**Comment by moneromooo-monero** [comment]
I thought it was anything that was listening on 18089 ?

**Comment by selsta** [comment]
It was changed some time ago.

**Comment by LotannaEzenwa** [comment]
I would like to edit this to say that I had tried to refresh and rescan many times, but the Trezor only just now asked if I would like to refresh after changing nodes and stopping the daemon. Not sure if that's an issue for anyone else.
