### ISSUE TITLE
Weird errors creating wallet via RPC

### ISSUE THREAD

**Issue by mrx23dot** [monero-project/monero#7431]
1,
monero-wallet-rpc --wallet-dir . --rpc-bind-port 28089 --rpc-bind-ip 127.0.0.1 --disable-rpc-login

Monero 'Oxygen Orion' (v0.17.1.9-release)
Win10 x64

2,
Issue RPC call
```
cmd1 = {
 "method": "create_wallet",
 "params": {
    "filename":"wallet",
    "password":"54b6565r7hhDSTH!",
    "language":"English"
  }
}
```

3,
warnings in console:
```
2021-03-05 14:49:49.970 W Espa+¦ol word 'asa' is shorter than its prefix length, 4
2021-03-05 14:49:49.971 W Espa+¦ol word 'ave' is shorter than its prefix length, 4
2021-03-05 14:49:49.972 W Espa+¦ol word 'boa' is shorter than its prefix length, 4
2021-03-05 14:49:49.972 W Espa+¦ol word 'cal' is shorter than its prefix length, 4
2021-03-05 14:49:49.973 W Espa+¦ol word 'dar' is shorter than its prefix length, 4
2021-03-05 14:49:49.974 W Espa+¦ol word 'don' is shorter than its prefix length, 4
2021-03-05 14:49:49.974 W Espa+¦ol word 'dos' is shorter than its prefix length, 4
```

Wallet file created **20secs** (!) after POST. Files:
  wallet.keys
  wallet

4,
```
cmd2 = {
 "method": "open_wallet",
 "params": {
    "filename":"wallet",
    "password":"54b6565r7hhDSTH!",
  }
}
```

5,
```
2021-03-05 14:50:07.766 E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon   <-- **I never wanted to connect!**
2021-03-05 14:50:07.767 E Exception at while refreshing, what=no connection to daemon
2021-03-05 14:50:29.778 E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon
2021-03-05 14:50:29.779 E Exception at while refreshing, what=no connection to daemon
2021-03-05 14:50:58.823 E Failed to open ./wallet.keys: system:32
2021-03-05 14:50:58.825 E !is_keys_file_locked(). THROW EXCEPTION: error::wallet_internal_error    <-- **why??**
```

full log:
[monero-wallet-rpc.log](https://github.com/monero-project/monero/files/6091329/monero-wallet-rpc.log)

**Comment by moneromooo-monero** [comment]
Did you close the wallet between creating and opening it ?

**Comment by mrx23dot** [comment]
Nope, all I did is listed.
RPC seems super unreliable, despite running everything locally.
Why would executing a wallet creation take 20seconds? 1-2s maybe.
I'm not even connected to remote node, not running mining.
That's a lot of burden to put on an higher level application.

I wanted auto generate wallets via RPC, but it has to be done manually as I see.

**Comment by moneromooo-monero** [comment]
You can run "sudo perf top -a" to see what your system is doing during that time. I just tried here, about 1.6 seconds.

**Comment by moneromooo-monero** [comment]
Maybe it's just timing out on the daemon. When creating a wallet, it asks the daemon for the current height for example.

**Comment by mrx23dot** [comment]
--offline solved it.

But after connected to remote node the RPC is unresponsive until it fully synced.
My RPC POST call times out after 2minutes. Is that expected? 

> 2021-03-08 16:49:05.339 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:05.359 T READ ENDS: Success. bytes_tr: 10087
> 2021-03-08 16:49:05.766 D Pulled blocks: blocks_start_height 2292820, count 580, height 2293400, node height 2312630
> 2021-03-08 16:49:05.916 D Pulling blocks: start_height 0
> 2021-03-08 16:49:05.916 D Block is already in blockchain: 069e601117f8d13671e785663aabf7d9bd77f1921ead4adaa07e8c1e742b4b72
> 2021-03-08 16:49:33.091 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.123 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.174 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.189 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.189 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.362 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.405 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.483 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.504 T READ ENDS: Success. bytes_tr: 16384
> 2021-03-08 16:49:33.611 T READ ENDS: Success. bytes_tr: 16384
> ...

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by mrx23dot** [comment]
That makes development any application that uses monero kinda awkward.
I saw RPC already uses 8 threads, can't we add one more that only handles RPC connection?

How does the Monero GUI connect to the backend, because it's able to query the progress of syncing.

**Comment by hardrun744** [comment]
Have a look at #7521

**Comment by velvetbailiff** [comment]
Check out #7523

**Comment by SneakyPlant43** [comment]
See #7527

**Comment by LenientVedism280** [comment]
Have a look at #7529

**Comment by wideFaint903** [comment]
Take a look #7532

**Comment by vtnerd** [comment]
This is likely due to a lock in `core` being held for a while. [Poorman's profiler](https://poormansprofiler.org/) will help determine where its being stuck.

As per the GUI, its probably making a different API call that doesn't block.

**Comment by finelyscuff** [comment]
#7534

**Comment by mrx23dot** [comment]
That GDB inspection wouldn't work on my windows.
It won't even allow to connect to RPC server. So GUI must be using something else.

Can you connect to your RPC while it's syncing? Maybe it's only windows.

**Comment by YetCord** [comment]
Have a look at #7536

**Comment by Morbidlystrum671** [comment]
Check out #7540

**Comment by flushRelay34** [comment]
Take a look #7543

**Comment by Smartlycount707** [comment]
#7547

**Comment by Lastsew987** [comment]
See #7558

**Comment by Wiselyconserve14** [comment]
View #7564

**Comment by LuridlyPearl** [comment]
Have a look at #7567

**Comment by PlopDelegate54** [comment]
Check out #7569

**Comment by selsta** [comment]
#7760 should help with RPC becoming unresponsive but it's not clear if that's the issue you are seeing.

> Can you connect to your RPC while it's syncing?

Yes that should work fine.

**Comment by selsta** [comment]
New versions of monero have a `--no-initial-sync` flag which should solve your issue.

https://github.com/monero-project/monero/pull/8355
