### ISSUE TITLE
Can't start RPC without daemon

### ISSUE THREAD

**Issue by mrx23dot** [monero-project/monero#7432]
monero-wallet-rpc --wallet-file wallet --password xxx --rpc-bind-port 28089 --rpc-bind-ip 127.0.0.1 --disable-rpc-login
Monero 'Oxygen Orion' (v0.17.1.9-release) 
Win10 64x

2021-03-05 15:01:58.267 E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon
2021-03-05 15:01:58.268 E Wallet initialization failed: no connection to daemon
then exits

I want to assign daemon-address from RPC later, since servers can change.

**Comment by ndorf** [comment]
Pass the `--offline` flag to `monero-wallet-rpc`.

**Comment by mrx23dot** [comment]
That solves it, without offline param it gives these extra lines:

> 2021-03-08 15:54:50.925 D Reconnecting...
> 2021-03-08 15:54:52.930 D Some problems at connect, message: No connection could be made because the target machine actively refused it
> 2021-03-08 15:54:52.932 D Failed to connect to localhost:18081
> 2021-03-08 15:54:52.932 I Failed to invoke http request to  /getheight
> 2021-03-08 15:54:53.051 D Reconnecting...
> 2021-03-08 15:54:55.058 D Some problems at connect, message: No connection could be made because the target machine actively refused it
> 2021-03-08 15:54:55.059 D Failed to connect to localhost:18081
> 2021-03-08 15:54:55.059 I Failed to invoke http request to  /json_rpc
> 2021-03-08 15:54:55.059 E Failed to connect to daemon
> 2021-03-08 15:54:55.060 D Reconnecting...
> 2021-03-08 15:57:17.614 D Reconnecting...
> 2021-03-08 15:57:19.616 D Some problems at connect, message: No connection could be made because the target machine actively refused it
> 2021-03-08 15:57:19.616 D Failed to connect to localhost:18081
> 2021-03-08 15:57:19.617 I Failed to invoke http request to  /gethashes.bin
> 2021-03-08 15:57:19.618 E !r. THROW EXCEPTION: tools::error::no_connection_to_daemon
> 2021-03-08 15:57:19.618 W /home/ubuntu/build/monero/src/wallet/wallet2.cpp:13997:N5tools5error23no_connection_to_daemonE: no connection to daemon, request = gethashes.bin
> 2021-03-08 15:57:19.618 E Exception at while refreshing, what=no connection to daemon

Shouldn't --offline  be the default when there is no --daemon-address specified?

**Comment by ndorf** [comment]
> Shouldn't --offline be the default when there is no --daemon-address specified?

I think not. The current default is probably expected behavior in the vast majority of cases, plus it's consistent with `monero-wallet-cli`.
