### ISSUE TITLE
Unnamed constant in construct_miner_tx invocation in blockchain.cpp

### ISSUE THREAD

**Issue by tewinget** [monero-project/monero#747]
https://github.com/monero-project/bitmonero/blob/master/src/cryptonote_core/blockchain.cpp#L1111
https://github.com/monero-project/bitmonero/blob/master/src/cryptonote_core/blockchain.cpp#L1120

construct_miner_tx is passed a parameter it calls "max_outs" which appears to be a limit to the number of digits an output amount should have.  The lines referenced above use a hard-coded amount (11) which should instead be a named constant.

**Comment by luigi1111** [comment]
https://github.com/monero-project/monero/commit/c3b3260ae5b5acde445fa88a6f0909f582903754
