### ISSUE TITLE
RPC connections stuck in CLOSE_WAIT on high load public RPC server

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#7482]
One of my public nodes sees a lot of connections.

I monitor the connection using nload. During normal operation, i see upwards of 100 - 200 Mbits / second upload, and an rpc connection count of 70+

sometimes, nload reports an upload of only 60 kbits/ second upload. During these times, if I use 

netstat -anp |grep 18089 | grep -v ESTABLISHED

I see loads of connections in the CLOSE_WAIT state. Once I restart monerod, the uploads go back to the 100s of mbits/sec range, and the loads of connections in CLOSE_WAIT go away. 

I notice that some of the connections in the CLOSE_WAIT state are from the same IP (9 connections). my most recent instance of this had 4 IPs that had 9 connections each, all in the CLOSE_WAIT state. Then 1 IP had 8, and 1 IP had 7. 

this happens so frequently I have to schedule monerod to restart every hour in the hopes that the service remains useful, but just recently I noticed the "bug" or whatever it is occurring after the node had 9 minutes of uptime. 

this is on ubuntu 18 on recent master (v0.17.0.0-b8f3e44a3)

**Comment by analyticname857** [comment]
View #7518

**Comment by hardrun744** [comment]
Check out #7521

**Comment by velvetbailiff** [comment]
#7523

**Comment by SneakyPlant43** [comment]
View #7527

**Comment by LenientVedism280** [comment]
Have a look at #7529

**Comment by wideFaint903** [comment]
Check out #7532

**Comment by vtnerd** [comment]
Can you attach GDB the next time this happens to get a stacktrace. It sounds like something deadlocked. The [poorman's profiler](https://poormansprofiler.org/) will help with a command to execute.

**Comment by finelyscuff** [comment]
Check out #7534

**Comment by YetCord** [comment]
See #7536

**Comment by Morbidlystrum671** [comment]
Check out #7540

**Comment by flushRelay34** [comment]
Have a look at #7543

**Comment by Smartlycount707** [comment]
View #7547

**Comment by Lastsew987** [comment]
#7558

**Comment by Wiselyconserve14** [comment]
Check out #7564

**Comment by Gingeropolous** [comment]
thread apply all bt

https://termbin.com/rnnu

**Comment by LuridlyPearl** [comment]
Have a look at #7567

**Comment by PlopDelegate54** [comment]
Have a look at #7569

**Comment by shiftilyConnect55** [comment]
See #7574

**Comment by lustilySurfeit685** [comment]
#7578

**Comment by publiclySpring87** [comment]
See #7581

**Comment by potentlywhistle** [comment]
View #7583

**Comment by AnglicanLordship** [comment]
Check out #7587

**Comment by Truehappen73** [comment]
See #7595

**Comment by czechforth** [comment]
Have a look at #7597

**Comment by SicilianAsian** [comment]
View #7599

**Comment by civilsalsify58** [comment]
View #7601

**Comment by SavagelyExtract49** [comment]
#7603

**Comment by turgidlyforedoom** [comment]
Have a look at #7607

**Comment by Gingeropolous** [comment]
@vtnerd , this seems to be a problem with rpc-ssl. When rpc-ssl is disabled, this behavior no longer occurs. multiple other public node operators replicate.

**Comment by visiblyDock78** [comment]
#7613

**Comment by outersnorer64** [comment]
Have a look at #7625

**Comment by Quaintlypitch** [comment]
See #7628

**Comment by vtnerd** [comment]
I've been looking at this issue, and is indeed a pain to track down (duplicate). I may need some more information shortly.

**Comment by vtnerd** [comment]
Nevermind, I can duplicate. I had the correct test, but the server shutdown was timing out and exiting, hiding the issue.

**Comment by selsta** [comment]
Should be fixed in #8426 / v0.18.0.0, if not please comment and I will reopen.
