### ISSUE TITLE
Exception in main. (Opening monero file)

### ISSUE THREAD

**Issue by LucasCalamar** [monero-project/monero#7494]
Hello, this is my problem when i try start monero:
![image](https://user-images.githubusercontent.com/63023472/110550282-21b77e00-8112-11eb-9dd1-8d7c3d4be23a.png)

**Comment by moneromooo-monero** [comment]
Your blockchain is most likely corrupted. Delete and resync.

**Comment by analyticname857** [comment]
Have a look at #7518

**Comment by LucasCalamar** [comment]
Okay, im reinstalling.
the download is slow asf, the start was fast, but now..
