### ISSUE TITLE
monero-wallet-rpc lost transaction

### ISSUE THREAD

**Issue by xinyijun** [monero-project/monero#7531]
it's the same issue as #6297, but this time we lost more than 90 deposit transaction("type": "in"), while last time we only lost 1 transaction.

recently we upgrade our monero-wallet-rpc to v0.17.1.9, and more than 90 of our users reported that their deposits were NOT recorded. we asked some of them for transaction keys and verified that they did deposit to us.

we did following steps to find all the lost transactions:

1. we delete files in ~/.shared-ringdb and the wallet file.
2. we run RPC rescan_blockchain, after rescan, we still lost 57 transactions.
3. we run RPC rescan_blockchain the 2nd time, after rescan, we still lost 20 transactions.
4. we run RPC rescan_blockchain the 3rd time, after rescan, we still lost 6 transactions.
5. we run RPC rescan_blockchain the 4th time, after rescan, we find all lost transactions.

we tried other versions and also found some transactions were lost, we guess this may be related to network between monero-wallet-rpc and node, please help to investigate it, thanks.

**Comment by wideFaint903** [comment]
#7532

**Comment by finelyscuff** [comment]
#7534

**Comment by YetCord** [comment]
View #7536

**Comment by Morbidlystrum671** [comment]
Have a look at #7540

**Comment by flushRelay34** [comment]
Have a look at #7543

**Comment by Smartlycount707** [comment]
Take a look #7547

**Comment by Lastsew987** [comment]
Have a look at #7558

**Comment by Wiselyconserve14** [comment]
View #7564

**Comment by LuridlyPearl** [comment]
Take a look #7567

**Comment by PlopDelegate54** [comment]
Have a look at #7569

**Comment by shiftilyConnect55** [comment]
View #7574

**Comment by lustilySurfeit685** [comment]
#7578

**Comment by publiclySpring87** [comment]
Check out #7581

**Comment by potentlywhistle** [comment]
Have a look at #7583

**Comment by AnglicanLordship** [comment]
See #7587

**Comment by Truehappen73** [comment]
Have a look at #7595

**Comment by selsta** [comment]
Are you running your own node?

**Comment by czechforth** [comment]
#7597

**Comment by SicilianAsian** [comment]
View #7599

**Comment by civilsalsify58** [comment]
View #7601

**Comment by SavagelyExtract49** [comment]
View #7603

**Comment by turgidlyforedoom** [comment]
Have a look at #7607

**Comment by xinyijun** [comment]
> Are you running your own node?

yes, we run our own node.

**Comment by visiblyDock78** [comment]
View #7613

**Comment by moneromooo-monero** [comment]
How many in transactions do you have on that wallet, roughly ? It's to get an idea of how often it happens.

**Comment by moneromooo-monero** [comment]
Testing here, I ran rescan_blockchain five times on monero-wallet-rpc, nohting  seems missed. grep "Received money:" in the logs shows 31245 lines, and:

cat build/Linux/crash/release/bin/monero-wallet-rpc.log-* build/Linux/crash/release/bin/monero-wallet-rpc.log | awk '/Calling RPC method rescan_blockchain/{if (C) print C; C=0}/Received money:/{++C}END{print C}'
6249
6249
6249
6249
6249

Also, are there any errors in the wallet or daemon logs corresponding to roughly where the missing transactions are ?

**Comment by outersnorer64** [comment]
#7625

**Comment by Quaintlypitch** [comment]
Take a look #7628

**Comment by moneromooo-monero** [comment]
Resolved offline.
