### ISSUE TITLE
Tails OS workaround for using remote nodes (CLI)

### ISSUE THREAD

**Issue by thoughtmaker5** [monero-project/monero#7566]
I've used the CLI without many issues connecting to remote nodes, but recently my transactions aren't being sent.  I get an error "outgoing tcp: connect: connection refused for [IP address]".
Through research I learned that Tails has "very restrictive firewall settings." I found tutorials about how to customize settings using monerod and running a full node. I didn't find much like that for using remote nodes. 
I tried "--no-dns" which removes the error.  My transactions appear to work and show as pending. But the funds don't leave my wallet.  

Help me plz

**Comment by LuridlyPearl** [comment]
Check out #7567

**Comment by PlopDelegate54** [comment]
View #7569

**Comment by shiftilyConnect55** [comment]
Take a look #7574

**Comment by lustilySurfeit685** [comment]
Check out #7578

**Comment by tobtoht** [comment]
Follow the guide here to set up the CLI with a remote node on Tails: http://xmrguide42y34onq.onion/tails/cli/install/manual

> My transactions appear to work and show as pending

Which remote node are you using? Some may consistently fail to relay transactions.

**Comment by publiclySpring87** [comment]
See #7581

**Comment by thoughtmaker5** [comment]
> 
> 
> Follow the guide here to set up the CLI with a remote node on Tails: http://xmrguide42y34onq.onion/tails/cli/install/manual
> 
> > My transactions appear to work and show as pending
> 
> Which remote node are you using? Some may consistently fail to relay transactions.

Thanks for replying. The steps in the guide match up with what I'm doing, I don't see anything I can correct. I'm alternating 3 or 4 nodes. Tried using the one hosted by xmr.to (https://community.xmr.to/nodes.html), same issue.

**Comment by potentlywhistle** [comment]
See #7583

**Comment by AnglicanLordship** [comment]
View #7587

**Comment by QuaintCrime** [comment]
Have a look at #7589

**Comment by Truehappen73** [comment]
See #7595

**Comment by czechforth** [comment]
View #7597

**Comment by SicilianAsian** [comment]
View #7599

**Comment by civilsalsify58** [comment]
View #7601

**Comment by SavagelyExtract49** [comment]
View #7603

**Comment by turgidlyforedoom** [comment]
#7607

**Comment by visiblyDock78** [comment]
Have a look at #7613

**Comment by outersnorer64** [comment]
#7625

**Comment by Quaintlypitch** [comment]
Have a look at #7628

**Comment by selsta** [comment]
Closing this, if this issue is still relevant please comment.
