### ISSUE TITLE
PR #756: improve watch-only import handling

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero#757]
Per https://github.com/monero-project/bitmonero/pull/756#issuecomment-201100119

> This needs public spend key (or address) I believe.
> 
> I'd suggest allowing an optional address which will be checked if provided and used for view key if needed.

**Comment by moneromooo-monero** [comment]
It works fine without an address. The generated address is different for the first part, but the second part is the same, and should still see the incoming txes I think, though I don't think I've tested that.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/785

**Comment by luigi1111** [comment]
https://github.com/monero-project/bitmonero/blob/0fbe9cfcdb9df2b141024eec04c3c7412791b741/src/simplewallet/simplewallet.cpp#L1118-L1126

This won't work correctly. If address AND spendkey are not present, this should error instead of creating a wallet with on the view key pair.

**Comment by Maxithi** [comment]
Is this issue still relevant?

**Comment by moneromooo-monero** [comment]
Apparetnly not, the code errors out if !field_address_found (now in wallet2.cpp).

**Comment by jonathancross** [comment]
Can this issue be closed then?

**Comment by lazaridiscom** [comment]
Please be aware that "ancient" `help wanted` issues make a super-strange impression to newcomers.

**Comment by moneromooo-monero** [comment]
Looks like it's moot now.

+wontfix
