### ISSUE TITLE
Reduce the number of requests to poll a daemon

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#7571]
Currently, wallets make up to 4 requests each time a wallet polls a daemon: get_info, get_transaction_pool_hashes, get_transactions, and get_blocks.bin.

As a result, daemons must service up to 4 requests for each client poll, and the user may experience a noticeable delay before their wallet even starts to sync blocks if their connection is slow.

This issue requests reducing the number of requests to poll from 4 to 1 wherein the daemon responds with everything needed:

- Txs in the pool not previously seen by the client
- Txs dropped from the pool
- Current chain height
- New blocks and confirmed txs

The wallet may send a client id to the daemon to track what has been previously served.

@moneromooo suggests this RPC call could piggyback on the existing get_blocks.bin RPC call.

**Comment by shiftilyConnect55** [comment]
Have a look at #7574

**Comment by lustilySurfeit685** [comment]
Take a look #7578

**Comment by publiclySpring87** [comment]
View #7581

**Comment by potentlywhistle** [comment]
Check out #7583

**Comment by AnglicanLordship** [comment]
See #7587

**Comment by QuaintCrime** [comment]
Check out #7589

**Comment by Truehappen73** [comment]
See #7595

**Comment by czechforth** [comment]
#7597

**Comment by SicilianAsian** [comment]
Check out #7599

**Comment by civilsalsify58** [comment]
See #7601

**Comment by SavagelyExtract49** [comment]
Check out #7603

**Comment by turgidlyforedoom** [comment]
Take a look #7607

**Comment by visiblyDock78** [comment]
View #7613

**Comment by Quaintlypitch** [comment]
See #7628

**Comment by hyc** [comment]
Requiring the monerod to remember clientIDs and their last state is a bad idea. Instead, the client just needs to send the last height & hash of the last block it knows about, plus the timestamp of the last time it saw the txn pool. The timestamp should be one that obtained from monerod itself. (f the block height & hash don't match on monerod side, that means there was a reorg.)

So, extending the get_blocks.bin RPC, should also add monerod's current timestamp.

**Comment by j-berman** [comment]
I'm in to work on this!

Thinking out loud on the reorg case: if it's determined there was a reorg, it seems the monerod side could find the block on an alternate chain, then find the divergent height of that alternate chain from the main chain, then return blocks/transactions (and perhaps just return all tx's in the pool for simplicity) since that height. Wondering if that's how the alternate chain can/should be used.

Note: I included this issue as a bullet in my CCS proposal - it wouldn't make sense for me to take a bounty for it.

**Comment by rbrunner7** [comment]
If @j-berman changes his mind, or priorities won't allow him to work on it after all, this would also be within reach for me. Don't intend to snatch it from him by submitting faster, however :)

**Comment by j-berman** [comment]
All yours @rbrunner7 :) I've got a fair amount of things to work on

**Comment by rbrunner7** [comment]
Thanks, @j-berman, kind of you.

Alright, then I will try my luck. I estimate that it might take me 3 calendar weeks or so until PR because working in my spare time.

**Comment by erciccione** [comment]
@rbrunner7 glad to hear that, please comment on https://github.com/haveno-dex/haveno/issues/110 so i can assign the issue to you.

**Comment by selsta** [comment]
Implemented in #8076
