### ISSUE TITLE
PR #756: improve version handling

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero#758]
Per: https://github.com/monero-project/bitmonero/pull/756#discussion-diff-57412861

> This feels like something that shouldn't be hard-coded.

**Comment by moneromooo-monero** [comment]
It's the version of what the current code knows about. You can't pass that on a command line, it doesn't make sense. So I think it makes sense to put a const int with it.How would you make it less hard coded ?

**Comment by tewinget** [comment]
Looking at it now, I guess all I'd question is the scoping of that constant, but I'm not sure where all it would be used, so it may be fine.  Woops.

**Comment by Maxithi** [comment]
Is this issue still relevant?

**Comment by lazaridiscom** [comment]
Please be aware that "ancient" help wanted issues make a super-strange impression to newcomers.

**Comment by moneromooo-monero** [comment]
I guess it can be closed. It was opened from a comment by tewinget, who's long gone, and the code's OK IMHO.

+wontfix
