### ISSUE TITLE
PR #756: sanity check scan-from height

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero#759]
Per https://github.com/monero-project/bitmonero/pull/756#discussion-diff-57412912

> May want a sanity check on scan_from_height.

**Comment by moneromooo-monero** [comment]
Beyond type checking as other JSON fields, what you would have ? It's unsigned to can't be negative, and the whole range is valid (if maybe very, very late in the future).

**Comment by tewinget** [comment]
Well, while I suppose you *could* create a wallet for which you only care
about transactions a year from now or later, it doesn't seem very
practical.  My thought was that one could at the very least inform the user
that the height doesn't make sense (if it's too far above the current chain
height).

On Fri, Mar 25, 2016 at 5:20 AM, moneromooo-monero <notifications@github.com
> wrote:

> Beyond type checking as other JSON fields, what you would have ? It's
> unsigned to can't be negative, and the whole range is valid (if maybe very,
> very late in the future).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/monero-project/bitmonero/issues/759#issuecomment-201214969>
>



-- 
Thomas Winget
Computer Engineering
Purdue University '12

**Comment by moneromooo-monero** [comment]
I suppose it could, but the wallet doesn't know the blockchain height (unless there's a daemon running), and it's meant to be an unattended process. Still, it could consider something from 2100 to be too far away, though it seems rather arbitrary.

**Comment by Cifrita** [comment]
@fluffypony Is this still needed?
