### ISSUE TITLE
wallet2::balance -> m_light_wallet_unlocked_balance, wallet2::unlocked_balance -> m_light_wallet_balance O_o

### ISSUE THREAD

**Issue by mahnunchik** [monero-project/monero#7627]
`wallet2::balance` method returns `m_light_wallet_unlocked_balance` and `wallet2::unlocked_balance` returns `m_light_wallet_balance` when `m_light_wallet` is true.

It seems values should be swapped.

https://github.com/monero-project/monero/blob/v0.17.1.9/src/wallet/wallet2.cpp#L5967-L5995

**Comment by Quaintlypitch** [comment]
Check out #7628

**Comment by moneromooo-monero** [comment]
Indeed, thanks. Fixed in https://github.com/monero-project/monero/pull/7635
