### ISSUE TITLE
Tests: node_server.bind_same_p2p_port failing with 10% probability

### ISSUE THREAD

**Issue by mj-xmr** [monero-project/monero#7645]
In my recent scheduled runs, the Unit Test `node_server.bind_same_p2p_port` was failing with 10% probability. Below are the logs:

```
[----------] 1 test from node_server
[ RUN      ] node_server.bind_same_p2p_port
/home/runner/work/monero/monero/tests/unit_tests/node_server.cpp:307: Failure
Value of: init(node, port)
  Actual: false
Expected: true
[  FAILED  ] node_server.bind_same_p2p_port (25 ms)
```

The test can be considered unstable for now. I will soon run more in-depth tests to learn what the real cause is.

**Comment by moneromooo-monero** [comment]
Anything interesting with log level 2 (or even 3) ?

**Comment by mj-xmr** [comment]
> Anything interesting with log level 2 (or even 3) ?

We checked with `wfaressuissia` but found nothing interesting.
