### ISSUE TITLE
'Wagner attack' in Monero multisig

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero#7830]
Monero's multisignature implementation is vulnerable to a Wagner attack: if multiple signatures are constructed for a given address, and the wagner attack is executed, then the attacker can learn the private key shares of other participants.

We (Haveno) had talks with @luigi1111, @SarangNoether, @moneromooo-monero and @UkoeHB about it. Looks like the change needed to fix the vulnerability would be quite invasive so a deeper look into the problem is needed.

@SarangNoether suggests to implement [MRL-0009](https://www.getmonero.org/resources/research-lab/pubs/MRL-0009.pdf). @moneromooo-monero gave his availability for the coding part if somebody provide him with python code to refactor into C++. We need a cryptographer willing to look into the issue and provide mooo with the info he needs.

Haveno is happy to provide resources to fix the vulnerability and we already opened an issue to keep track of progresses: https://github.com/haveno-dex/haveno/issues/103. As you can see, the issue has a bounty, but we could provide more resources if necessary.

**Comment by selsta** [comment]
https://github.com/monero-project/monero/pull/8113

**Comment by johnnyluo** [comment]
given https://github.com/monero-project/monero/pull/8149 has been merged , believe this one has been fixed, correct?
