### ISSUE TITLE
Where do wallets created via the monero wallet RPC get stored? (Aside from main)

### ISSUE THREAD

**Issue by eddiejibson** [monero-project/monero#7841]
Hello,

So obviously beside the --wallet-file that is defined upon startup of the RPC, where do all the other addresses get stored that are created via the wallet RPC? Whenever I create them I look inside the directory of the wallet file etc, but no files are present? And the .address.txt file still only has one address. So where exactly can I find the files for the keys, address etc? At first I thought this was defined within the --wallet-dir but obviously you cannot set the --wallet-file and --wallet-dir at the same time.

Thanks

**Comment by trasherdk** [comment]
Did you look in ` ~/.bitmonero/` ? That would be my guess.

**Comment by selsta** [comment]
Do you mean subaddresses? I don't think they get stored in any file.

**Comment by elibroftw** [comment]
I think you should've asked this question on the monero stack exchange. It's just so poorly worded. There's only one key per wallet.

**Comment by selsta** [comment]
Closing this as it's a question and the original issue creator never replied.
