### ISSUE TITLE
Restoring GUI Wallet From Recent Height Yields No Outbound Tx's In Tx History.

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#7857]
GUI Version: 0.17.2.2-937cb98 (Qt 5.15.2)

When restoring GUI wallet in Simple Mode from a recent height of approximately 2 months ago there are no outbound tx's listed in the tx history. Comparing the CLI show_transfers command to the GUI tx history, the GUI has omitted all outbound tx's.

**Comment by selsta** [comment]
Can you go to Settings -> Info and post the restore height you have set?

**Comment by downystreet** [comment]
The height was set at 2021-07-01. I have already started refreshing from another height that I usually refresh from which is before there were any tx's.

**Comment by selsta** [comment]
What is the date of your first transactions?

**Comment by downystreet** [comment]
Actually what I said is not correct the first transactions are from around 2019 but I usually restore from January of 2020.

**Comment by selsta** [comment]
You have to set a restore height that is earlier than the first received transactions.

**Comment by downystreet** [comment]
Ok that's what it is then.

**Comment by downystreet** [comment]
All is good now. Thank you!
