### ISSUE TITLE
Incorrect warning when blockchain on LUKS encrypted SSD volume => "W The blockchain is on a rotating drive: this will be very slow, use an SSD if possible"

### ISSUE THREAD

**Issue by xanoni** [monero-project/monero#7865]
`monerod` shows the message `W The blockchain is on a rotating drive: this will be very slow, use an SSD if possible` when the blockchain is indeed stored on a LUKS-encrypted SSD volume, which uses more CPU but still has great random read/write performance.

**Comment by selsta** [comment]
It's what the OS returns. Not much we can do here.

https://github.com/monero-project/monero/blob/89664fcee58688b7e439fb8fcdce0c3792195dd3/src/common/util.cpp#L813

**Comment by xanoni** [comment]
K. Well. Guess I can live with it.
