### ISSUE TITLE
Build fails on Pinebook Pro - aarch64 running Manjaro

### ISSUE THREAD

**Issue by Dendrocalamus64** [monero-project/monero#7900]
It built successfully last year.  Now it fails building tests/unit_tests/wipeable_string.cpp with,
`/usr/include/boost/optional/optional.hpp:1596:3: error: static assertion failed: If you want to output boost::optional, include header <boost/optional/optional_io.hpp>                           
 1596 |   BOOST_STATIC_ASSERT_MSG(sizeof(CharType) == 0, "If you want to output boost::optional, include header <boost/optional/optional_io.hpp>"); `

Changing the include from <boost/optional/optional.hpp> to <boost/optional/optional_io.hpp> doesn't fix it, then it starts saying,
`/usr/include/boost/optional/optional_io.hpp:47:21: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const epee::wipeable_string’)`

It's similar to this bug on another project:
[REQUIRE/CHECK not compatible with boost::optional](https://github.com/catchorg/Catch2/issues/1135)

**Comment by Dendrocalamus64** [comment]
I tried the build instructions on this project's top page, and building that way does work for me.

The Arch wiki says,
[Makepkg fails, but make succeeds](https://wiki.archlinux.org/title/makepkg#Makepkg_fails,_but_make_succeeds)
>If something manually compiles using make, but fails through makepkg, it is almost certainly because /etc/makepkg.conf sets a compilation variable to something reasonable that usually works, but that what you are compiling is incompatible with.

So, next I'll figure out what build options are necessary to reproduce the error.

**Comment by selsta** [comment]
release-v0.17 branch contains a fix for your reported issue, it's not included in v0.17.2.0 tag

**Comment by Dendrocalamus64** [comment]
Oh, I see it.
67ba733de173008a94e6fcb1b4bf8549acbe81ec, merged into release-v0.17 in pull request #7825 on Aug 27.

If I apply that patch to wipeable_string.cpp, it builds successfully.  Thank you!
