### ISSUE TITLE
Monero core team

### ISSUE THREAD

**Issue by AAH20** [monero-project/monero#7909]
After greetings , this issue is intended to request the improvement of the project documentation in the following aspects : 

 1-getmonero.org admin privileges contributors identification 

2-Creating a blog section related to all legal cases , regulations,KYCs in the most stable crypto exchange platforms 

3-Raising the public situational awareness when it comes to monero's security policies , bug bounty programs 

4-you have to find a way to get monero out of the blackbox which is always matching monero with the dark markets

Finally you have to keep an eye on ciphertrace and binance and what is happening to them recently , and provide monero's community with these updates , 

regards.

**Comment by AAH20** [comment]
Also if you are looking for a deep technical security suggestion take a look at #7896

**Comment by hyc** [comment]
Wrong repo for an issue like this, should be in monero-meta.
