### ISSUE TITLE
monerod failing to run

### ISSUE THREAD

**Issue by Samuel20354** [monero-project/monero#7914]
It's me again. When I run monerod with the command `./monerod` i get the error:
`Illegal instruction (core dumped)`

Thanks!

**Comment by Samuel20354** [comment]
anyone

plz help

**Comment by selsta** [comment]
Where did you get the monerod binay?

**Comment by Samuel20354** [comment]
I ran the command make and after that the file in the bin dir

**Comment by selsta** [comment]
Did you do it on the same computer?

**Comment by Samuel20354** [comment]
yes

**Comment by selsta** [comment]
This message usually shows up if you compile on one system and copy the binary to a different one.

**Comment by Samuel20354** [comment]
Ah alr. Thanks for the reply ill try recompiling

**Comment by Samuel20354** [comment]
Ok so i reinstalled the entire repo and remaked it and I'm still getting the same error

**Comment by selsta** [comment]
Does the binary from getmonero.org work?

**Comment by Samuel20354** [comment]
how would I get that binary onto my VPS? and test if it works because I have only used the one from here
