### ISSUE TITLE
Selective Transactions View Key

### ISSUE THREAD

**Issue by AAH20** [monero-project/monero#7932]
After greetings , This is an urgent required feature to allow monero's adoption in white markets , 

The view key feature of the cryptonote whitepaper was intended to add a regulatory compliance feature , but it wasn't implemented well , as you can't select certain transactions from history to show , either all of the transactions history or none , and this isn't suitable for multi national businesses , as each country local regulations differ , hence the selective transactions view key is the solution , also this feature will open a new business domain based on view keys smart contracts "a hint from the ETH community" , also these smart contracts can be tied to the digital signatures certificate authorities " a hint from me" , 
Finally I believe that this feature will ease the lack of monero's mass adoption  in regulated businesses , while opening new business domains based on selective centralized transactions , 

## you don't need to use multiple wallets , you can just reveal the required transactions from your unified monero official wallet.

**Comment by selsta** [comment]
There are other proofs that you can use to prove individual transactions.

**Comment by AAH20** [comment]
> There are other proofs that you can use to prove individual transactions.

Hi selsta , can you highlight these proofs ? , also if this is already an existing feature it doesn't seem to be popular which for sure lead to lack of automation , and my evidence is simple , that if this feature exists , monero wouldn't have been removed from nearly all kyc exchange platforms such as binance , kraken , etc.

**Comment by selsta** [comment]
There are different transaction proofs to prove different things. See e.g. https://www.getmonero.org/library/Zero-to-Monero-2-0-0.pdf#page=83

Monero is listed on both Binance and Kraken.
