### ISSUE TITLE
Mining jobs all running on a single core

### ISSUE THREAD

**Issue by BigassJohnny** [monero-project/monero#7941]
I'm trying to get a mining benchmark on a Dell R900 with 4 Xeon X7460.  Build/installation went ok, blockchain sync at 100%.  When I start mining, every thread gets scheduled on a single core.  The output from 'top' shows one CPU at 2500% load and the other 23 idle.  Running one miner thread per core would probably work better but I can't find the right config options.  I'd rather not deal with installing a GUI and the requisite X overhead; looking for a command line/config file solution.  Monerod version is 0.17.2.0-release; OS is FreeBSD 13.0-RELEASE.

Any suggestions would be appreciated.

**Comment by hyc** [comment]
You're misinterpreting the "top" output. One CPU core can only yield 100% usage, max. If you're seeing 2500% CPU usage that means it's using at least 25 cores.

**Comment by BigassJohnny** [comment]
Then how is it that running one thread produces the same 1.3kH/s as running 24?

**Comment by selsta** [comment]
Try XMRig and check if you have the same issue there.
