### ISSUE TITLE
Issues when starting monero-wallet-rcp

### ISSUE THREAD

**Issue by Samuel20354** [monero-project/monero#7988]
im in the bin dir and i have set the path but when I run It with this command `./monero-wallet-rpc --wallet-file monero_pool --password BHFy=passwrrd --rpc-bind-port 18083 --rpc-bind-ip 127.0.0.1 --disable-rpc-login` i get the error:
```
This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly.

Monero 'Oxygen Orion' (v0.17.0.0-6b824c9ed)
Logging to ./monero-wallet-rpc.log
2021-10-03 21:55:40.280 W Loading wallet...
2021-10-03 21:55:41.437 E e || !exists. THROW EXCEPTION: error::file_not_found
2021-10-03 21:55:41.437 E Wallet initialization failed: file not found "moneropool.keys"
```

Thanks!

**Comment by selsta** [comment]
Something doesn't add up.

Your command says `--wallet-file monero_pool` and your log says `failed: file not found "moneropool.keys"`.

**Comment by Samuel20354** [comment]
ikr that's what i was thinking

**Comment by Samuel20354** [comment]
shoudl i make a .keys file if so what should i put in the file

**Comment by selsta** [comment]
Can you type "ls -l" inside the `bin` dir and post the output here.

**Comment by selsta** [comment]
I don't see any wallet file in your folder.

According to your command it should be in the same folder aa `monero-wallet-rpc`.

You have to specify the correct path to your wallet file.

**Comment by Samuel20354** [comment]
that is the same folder as monero-wallet-rpc

**Comment by selsta** [comment]
Yes, but there is no wallet file. You have to generate one first.

**Comment by Samuel20354** [comment]
how do i generate one

**Comment by selsta** [comment]
Just create a wallet file with monero-wallet-cli for example. Closing as there doesn't seem to be a bug here.
