### ISSUE TITLE
Sweep_all command in CLI wallet only sweeps half of balance.

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#7990]
Wallet Version: CLI Monero 'Oxygen Orion' (v0.17.2.3-release)

The sweep_all command only sent half of my full balance to the address. A second sweep_all command sent the rest of it. My wallet balance was empty previously and I received monero from two different addreses in different amounts. The sweep_all command sent the exact amount of the individual amounts received previously. I wasn't paying attention to the first transaction when the y/n authorization came up and I went ahead with it only sending the amount of a previously received amount. I thought sweep_all was supposed to send the entire balance? 
![sweep_all1](https://user-images.githubusercontent.com/63488055/135783700-49bcbfc9-52b8-45fb-ad31-2ae14ae5f217.png)

**Comment by selsta** [comment]
```
[wallet]: help sweep_all
Command usage: 
  sweep_all [index=<N1>[,<N2>,...] | index=all] [<priority>] [<ring_size>] [outputs=<N>] <address> [<payment_id (obsolete)>]

Command description: 
  Send all unlocked balance to an address. If the parameter "index=<N1>[,<N2>,...]" or "index=all" is specified, the wallet sweeps outputs received by those or all address indices, respectively. If omitted, the wallet randomly chooses an address index to be used. If the parameter "outputs=<N>" is specified and  N > 0, wallet splits the transaction into N even outputs.
```

You have to use `sweep_all index=all` if you want to sweep from all subaddress indices.

**Comment by downystreet** [comment]
Good to know.

**Comment by trasherdk** [comment]
It says `[<payment_id (obsolete)>]` Okay.
What about `[<ring_size>]` Is that still an option?

**Comment by selsta** [comment]
> What about [<ring_size>] Is that still an option?

No, it should fail with different ring sizes. I guess the help text should update.
