### ISSUE TITLE
Unusable when multiple wallets are attached

### ISSUE THREAD

**Issue by kelvinwop** [monero-project/monero#7991]
Hello,

Monero GUI is unusable when you have multiple trezor wallets attached to the computer. Any authentication attempt fails and if you are authenticated then any transaction attempt fails.

**Comment by selsta** [comment]
This likely won't get fixed, it's a niche use case that would require larger changes.

@ph4r05 what's your opinion?

**Comment by ph4r05** [comment]
@kelvinwop @selsta, correct, this is a won't fix issue. We do not plan to support this as it is very rarely used.

**Comment by selsta** [comment]
Okay, will close this for now.
