### ISSUE TITLE
Rename legacy bits to Monero

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero#80]
Per https://help.github.com/articles/renaming-a-repository - renaming a project will forward everything from the old name to the new with no major consequences. Forks would do well to change their upstream URL, or just re-clone their fork to a working copy, but it'll forward a 'git fetch upstream' to the new URL.

The binary should also be renamed 'monerod' from 'bitmonerod'.

**Comment by fluffypony** [comment]
This slipped away due to all the other bits, but I'd like to revisit it.

The recommendations above all still stand, except I'm leaning more towards a dash instead of an underscore, to follow ```git``` convention. Thus the following changes would occur:

- ```bitmonerod``` -> ```monero-daemon``` (or ```monero-node``` ?)
- ```simplewallet``` -> ```monero-wallet-cli```
- ```blockchain_dump``` -> ```monero-blockchain-dump```
- ```blockchain_import``` -> ```monero-blockchain-import```
- ```blockchain_export``` -> ```monero-blockchain-export```
- utility bits (eg. pop-blocks) from blockchain_import -> ```monero-utils-blockchain```
- ```cn_deserialize``` -> dropped, or renamed to ```monero-utils-deserialize```
- ```blockchain_converter``` -> dropped, no longer necessary
- ```simpleminer``` -> dropped due to disuse

And later on:

- ```monero-wallet-rpc``` once we've pulled through the old rpcwallet work
- ```monero-deprecated-rpc``` for the RPC stub for daemon RPC calls, once the 0MQ work is done

Suggestions welcome.

**Comment by moneromooo-monero** [comment]
How about s/monero-blockchain/monero-utils/ ?
Or s/monero-blockchain/monero-utils-blockchain/ too.

**Comment by hyc** [comment]
Naming of resulting binaries with '-' is ok. Naming of individual source files should use underscores. Debuggers don't like filenames/symbols with dashes in them.

**Comment by radfish** [comment]
Please accept vote for: `monerod` -- it is short and follows the convention.

I would combine all those separate blockchain manipulation binaries into either one binary with subcommands (`monero-blockchain import|export|dump|convert`) or even roll it into monerod (after all, the daemon "owns" the blockchain). Not sure what cm_serialize does, but hopefully it can also be rolled into. With all respect to unix principle, I think grouping these is better for the end user than having them as separate binaries.

One vote for `monero-wallet` instead of `monero-wallet-cli` for sake of shortness, although I don't know what the *-rpc binaries are intended to be and how they relate to *-cli?

**Comment by hyc** [comment]
Yes, I had proposed rolling import/export into the daemon earlier as well. It would have made the migration code much easier to write.

**Comment by fluffypony** [comment]
@radfish it's silly to have monero-wallet offer both CLI and RPC modes, since they're super distinct and will need to be able to be developed independently of each other without affecting each other's moving parts. so having one that is CLI, and pulling out the RPC stuff into its own binary (as we did with rpcwallet on the now-defunct development branch) is the way to allow that to happen.

**Comment by fluffypony** [comment]
Mostly closed by #1039, will have to consider the CRYPTONOTE_NAME stuff later on.

**Comment by jetwhiz** [comment]
It looks like Travis-CI is broken -- possibly related to the rename? 

https://travis-ci.org/monero-project/bitmonero

**Comment by fluffypony** [comment]
@jetwhiz the Travis stuff moved as well, check https://travis-ci.org/monero-project/monero

**Comment by jetwhiz** [comment]
@fluffypony  -- I think the [README.md](https://github.com/monero-project/monero/blob/master/README.md) is still pointing to https://travis-ci.org/monero-project/bitmonero

**Comment by fluffypony** [comment]
@jetwhiz tks - busy fixing that now :)

**Comment by sysfu** [comment]
Blockchain is still being written to legacy folder name C:\ProgramData\bitmonero\lmdb as of version 0.12.2.0
