### ISSUE TITLE
Monerod Using 59% System Memory When Synced?

### ISSUE THREAD

**Issue by downystreet** [monero-project/monero#8009]
Version: v0.17.2.3

Monerod is sycned and is using 59% of system memory. What is going on here? Daemon is running with --prune-blockchain command. When I stop the daemon there is 12GB available instead of 11. Am I reading this correctly?
![monerod](https://user-images.githubusercontent.com/63488055/137566933-a7491f46-d709-47d0-a4f0-0516de1376bc.png)

**Comment by hyc** [comment]
It's normal. Any free RAM is used by the filesystem cache, and mapped in as shared memory. Has no impact on the system, the OS will reclaim it if it needs it for other uses.

**Comment by trasherdk** [comment]
Not exactly a memory or resource hog :smiley: 
![image](https://user-images.githubusercontent.com/5003891/137627466-0f38dca0-3e51-4433-a5a4-6c9414c4f4fe.png)
