### ISSUE TITLE
Monero GUI crashes when over-filling description of payment request

### ISSUE THREAD

**Issue by the-lightstack** [monero-project/monero#8012]
Version of pre-build binary GUI:
0.17.2.3-113efbf (Qt 5.15.2)

OS:
Linux, 64bit

Crash message in terminal:
`
terminate called after throwing an instance of 'qrcodegen::data_too_long'
  what():  Data length = 20604 bits, Max capacity = 18672 bits
fish: “./monero-wallet-gui” terminated by signal SIGABRT (Abort)
`
Solution:
Cap the UI input field after MAX_CAPACITY bytes entered

**Comment by selsta** [comment]
Thank you, I created a PR for it on the GUI repo. Closing this as this issue tracker is for monero itself, not the GUI.
