### ISSUE TITLE
RPC setup

### ISSUE THREAD

**Issue by S1700** [monero-project/monero#8042]
So I'm setting up monerod for a pool that I am making but when I am running monerod it says that RPC has already been initialized but when I use the IP and port that it lists it says that there is no RPC server on that IP/port. So I try running `monero-wallet-rpc` and it cant bind to the IP/port because it is already in use?

**Comment by selsta** [comment]
Please post the exact commands you are using.

**Comment by S1700** [comment]
./monero-wallet-rpc --rpc-bind-port 18080 --wallet-file moneropool --log-level 1 --prompt-for-password

**Comment by selsta** [comment]
18080 is the default p2p port, you can't bind `monero-wallet-rpc` to it. Use for example 18083 instead.

**Comment by S1700** [comment]
ah alr sorry for making a issue for something so simple

**Comment by selsta** [comment]
There are the default daemon ports:

```
18080: P2P port
18081: RPC port
18082: ZMQ port
```

Closing as the question seems resolved.
