### ISSUE TITLE
Monero wallet RPC callback on incoming transaction

### ISSUE THREAD

**Issue by ob45** [monero-project/monero#8045]
Hello

Is there a way to get notified about an incoming transaction?
I'm currently working on a node.js application and I'd like to validate transactions in an automated way. (mainly checking if the incoming transaction has the right amount of XMR etc.)

**Comment by selsta** [comment]
```
  --tx-notify arg                       Run a program for each new incoming 
                                        transaction, '%s' will be replaced by 
                                        the transaction hash
```

There is also ZMQ but that's more advanced: https://github.com/monero-project/monero/blob/master/docs/ZMQ.md
