### ISSUE TITLE
Encounter a know virus running OS X version of Monero GUI

### ISSUE THREAD

**Issue by jpitz31** [monero-project/monero#8059]
Just installed Monero GUI, on a Mac running MacOS Big Sur version 11.6.

Avast virus protection indicates that the Monero GUI is infected with MacOS:Miner-DL

Refer to the below link for details on this threat:

https://www.bleepingcomputer.com/news/security/cs-go-cheat-delivers-cryptocurrency-miner-on-macos/

"SentinelOne security researcher Arnaud Abbati says the Monero miner uses the user's resources to mine funds for two email addresses registered with the MinerGate service."

Thanks

**Comment by selsta** [comment]
The GUI contains a miner, as it gets warned by your anti virus.

Add an exception, there isn't anything we can do on our side.

**Comment by jpitz31** [comment]
Read the virus report, someone modified the source to to include a threat to mine in the background to several email addresses, one owned by a past developer.  The account is held by someone on minergate.  They are stealing resources to mine Monero into their account.

**Comment by selsta** [comment]
That's an unrelated report from 2017.

**Comment by selsta** [comment]
You can use these steps to confirm the binary has the correct hash: https://www.getmonero.org/resources/user-guides/verification-allos-advanced.html
