### ISSUE TITLE
E: duplicate key: support_flags

### ISSUE THREAD

**Issue by S1700** [monero-project/monero#8062]
![image](https://user-images.githubusercontent.com/68336568/141820479-e248d86c-106e-4c0c-8be1-3e5b9cb1cf7d.png)
don't know why and how but I'm getting it every time i run monerod

**Comment by selsta** [comment]
It's someone running a broken node, you can try to ban that IP.

**Comment by S1700** [comment]
how would i find and ban the IP?

**Comment by selsta** [comment]
I guess you can delete ~/.bitmonero/p2pstate.bin file, then you will connect to new nodes, hopefully the broken node isn't part of it.
