### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by rexbutz** [monero-project/monero#8074]
I'm trying to setup a Monero node on ubuntu 20.  I am getting the following error:

> candidate: 2403424 -> 2497555 [Your node is 94131 blocks (4.3 months) behind] 
2021-11-20 18:10:17.054 I SYNCHRONIZATION started
monerod: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted

Does anyone have any idea what is wrong and how to fix?

**Comment by antonegorov** [comment]
Hi.

First it makes sense to try running monerod with `--log-level 4`

If, alas, there is no answers in the logs, then try re-sync blocks. Read about `--db-sync-mode` and maybe this option is a solution to your problem.

**Comment by selsta** [comment]
Which version are you using?
