### ISSUE TITLE
Please, add the Exolix Exchange to the list of Swappers on your website!

### ISSUE THREAD

**Issue by Exolix-com** [monero-project/monero#8093]
Hello,
My name is Julie and I am a marketing manager at Exolix.
Exolix is an instant anonymous crypto exchange service with fixed rate.
Recently we have added XMR to the list of coins available on our website for exchange. So, we wanted to establish contact with you, as well as maintaining communication within the crypto community.
Also, we noticed that you have a list of Swappers on your site, but Exolix is not on the list.
Please add the Exolix Exchange to this list on your website.
Thanks!

**Comment by erciccione** [comment]
Wrong repository: https://github.com/monero-project/monero-site.

Anyway. If you added XMR recently i doubt the community trusts your service enough to be listed on Getmonero. If you wish to stay in contact with the community, you have many ways to do so. Take a look at our Hangouts page: https://www.getmonero.org/community/hangouts/.

**Comment by selsta** [comment]
Closing as this is the wrong repo.
