### ISSUE TITLE
Spinning drive warning with no spinning drive

### ISSUE THREAD

**Issue by LukeeeeBennett** [monero-project/monero#8104]
Hello,

I'm getting a warning about monerod syncing to a spinning drive. I don't have any spinning drives, I have a regular SSD and an M.2 SSD. monerod is currently running in an wsl2 debian instance which is on the M.2.

Any ideas?

**Comment by Gingeropolous** [comment]
i mean, i think it can be ignored. It just means that whatever mechanism monero uses to detect the type of drive isn't working properly on your system. I don't think that the detection of a spinny drive changes any parameters.

Oh, so you essentially have a debian virtual machine on top of windows? yeah, I doubt the monero software can detect the hardware abstraction going on in the vm if I had to guess.

**Comment by LukeeeeBennett** [comment]
Sure, makes sense. Just checking, thanks

**Comment by moneromooo-monero** [comment]
You can look for a "rotational" pseudo file somewhere in the /sys/dev/block tree and cat it. That's what monero looks for. There may be several if you have more than one disk. The VMM might be filling these settings with default values for a "fake" disk layer.
