### ISSUE TITLE
minig button not working

### ISSUE THREAD

**Issue by bullocksedwardo** [monero-project/monero#8111]
I'm having several issues all the same issue you're having with fatal error messages and wallet not closing mining button not working and yet it doesn't show I'm mining but when i call out for status mining GUIt says I am.  So I guess I will uninstall reinstall and resync.  This sort of trhing never happend on my laptop now I have new desk top with new 3975 threadripper pro and it showing a hash of 500 just like my laptop lol something fishy going on here

**Comment by selsta** [comment]
If you are serious about mining I would recommend to use something like xmrig

**Comment by selsta** [comment]
If you continue to have issues please open it here: https://github.com/monero-project/monero-gui/issues
