### ISSUE TITLE
reference binding to null pointer discovered via LibFuzzer

### ISSUE THREAD

**Issue by swirsz** [monero-project/monero#8119]
Bug detected via Libfuzzer & UndefinedBehaviorSanitizer.

./cold-outputs_fuzz_tests crash-c1c.txt

/src/monero/boost_1_70_0/boost/serialization/singleton.hpp:181:13: runtime error: reference binding to null pointer of type 'const boost::archive::detail::extra_detail::map<boost::archive::portable_binary_iarchive>'
SUMMARY: UndefinedBehaviorSanitizer

[crash-c1c.txt](https://github.com/monero-project/monero/files/7766724/crash-c1c.txt)

**Comment by moneromooo-monero** [comment]
That should be reported to boost.
