### ISSUE TITLE
Copyright updating

### ISSUE THREAD

**Issue by glazedtorus** [monero-project/monero#8122]
It's almost 2022, so the copyright dates need to be changed once again. I saw a lot of PR's related to updating copyright to 2021, but most of them changed a different number of files. I was wondering if it would be easier if we simply moved to a yearless copyright, 
for example: `Copyright (c)  The Monero Project` .
 Or something like, `Copyright (c) 2014-present, The Monero Project`.
I think these options would require less maintenance. Thoughts?

**Comment by moneromooo-monero** [comment]
"present" is useless since its value depends on when you are reading it.

**Comment by moneromooo-monero** [comment]
(or dishonest, if you're trying to claim copyright after you last modified it)

**Comment by glazedtorus** [comment]
So is a yearless copyright preferable or should things stay the way they are now with annual updates?

**Comment by selsta** [comment]
I think either updating yearly or only updating when someone touches the file is fine.

**Comment by hyc** [comment]
There is no such thing as a yearless copyright.
