### ISSUE TITLE
How can I get the file for the blockchain to run for a pool [NOT A ISSUSE]

### ISSUE THREAD

**Issue by TimyIsCool** [monero-project/monero#8124]
![image](https://user-images.githubusercontent.com/74112751/147703318-367c40e6-be37-4be0-9c8b-268e541f8b15.png)
Would like to know the file and how to set it up?

**Comment by selsta** [comment]
This repo isn't about pool software, please ask at the correct place.

You can get the blockchain by running `monerod` and waiting for it to sync.

**Comment by TimyIsCool** [comment]
> This repo isn't about pool software, please ask at the correct place.
> 
> You can get the blockchain by running `monerod` and waiting for it to sync.

Where can I find the pool software?

**Comment by selsta** [comment]
here is an example https://github.com/jtgrassie/monero-pool

**Comment by TimyIsCool** [comment]
> here is an example https://github.com/jtgrassie/monero-pool

how would i setup a rpc with monerod?
