### ISSUE TITLE
Vulnerable as 51% attack

### ISSUE THREAD

**Issue by mr459** [monero-project/monero#8127]
pools can attack xmr directly
minexmr pool have more than 50% of net hash and can make xmr price 0$ in one night
and also some pools like : nanopool+support xmr can do it 
and if minexmr+suppport xmr do that , no chance of unsucceful attack

xmr should remove pool mining to prevent this like things
or just have many cpu's in backend to turn on when 51% attack happens

we cant even understand if they printed 298374298472934xmr and waiting to xmr pump and sell small amount of that and gain milions of $

**Comment by selsta** [comment]
Please read up on the definition of a 51%.

**Comment by getgle** [comment]
so true bestie
