### ISSUE TITLE
3.93 xmr transaction fee for .34 xmr transaction 

### ISSUE THREAD

**Issue by PacificNWVet** [monero-project/monero#8134]
![D9019A9F-0CFB-46DD-A093-4B65E356D339](https://user-images.githubusercontent.com/97309317/148589375-08af1233-cdc8-4d0f-b9c3-52324789add9.jpeg)

I have posted image proof I did not check transaction fee before sending however I have sent countless transactions with very low transaction fees instead of this one…

Can you lmk how this happened and or why? I’ve accepted I have lost the xmr but yeah… I’m willing to share the logs with the devs to see why this would happen prevent it from happening etc

**Comment by selsta** [comment]
I need to know the IP of the remote node (I asked on Reddit about it)

**Comment by PacificNWVet** [comment]
[1/7/22 6:33 PM] 2022-01-07 18:33:48.935 I Monero 'Oxygen Orion' (v0.17.2.0-release)
Height: 2532154/2532154 (100.0%) on mainnet, bootstrapping from 23.88.121.112:18089, local height: 620051 (24.5%), not mining, net hash 3.11 GH/s, v14, 0(out)+0(in) connections




that is what you requested I did not know your a dev t hanks for the help

**Comment by selsta** [comment]
that's a completely different IP now :/ do you have the previous one?

**Comment by PacificNWVet** [comment]
unfortunately just what i had posted on reddit, I am using monero on whonix so theirs that

**Comment by selsta** [comment]
Ok, next time you see extremely high fee, please go directly to Settings -> Log and post the output of `status` so that we can find out which node is responsible for this.

Currently you are the only transaction on the blockchain with a high fee so it isn't widespread yet.

**Comment by PacificNWVet** [comment]
Hey thanks for the help I appreciate it. I don’t lie this is very disheartening for me and has pushed me away from monero and crypto altogether…

i appreciate the help nonetheless and support and that the devs are willing to help with this… that makes me happy and softens the blow a bit I certainly will…

i can show you transactions from like yesterday and days ago where transaction fees are low so I know this isn’t user error..

but thanks for the help :)

**Comment by selsta** [comment]
The fee / block was mined by MineXMR, I will contact them, maybe they can refund it :)

**Comment by PacificNWVet** [comment]
Sure I would appreciate that greatly most definitely.. if they do I will be incredibly happy I will be like whoa like crazy the support up till now is amazing…

idk you you don’t know me, your a developer doijg this for free it’s clear what has happened isn’t user error but something else..

to want to go above and beyond and want to help me and even go as far as request a refund for me is amazing your a nice person..

Im just a random disabled combat veteran posting on the internet you bring a little
Faith to me thanks I’ll be check this email and thread for results..

your a great Dev selsta

**Comment by selsta** [comment]
It will probably take a bit until I can contact @xnbya (MineXMR admin). Can you post your XMR address here in the meantime?

**Comment by PacificNWVet** [comment]
That is my xmr address I receive xmr for as well as the one I made with the transaction no worries, ill be keeping an eye on my email its cool i appreciate it regardless selsta. I'll keep the thread open until you come to a resolution refund or no refund :) 


87PUa5d7TCZ11Dtiw5Y6Q7NNRrwReM4k9XEcdjP7YA7sCrkQA6xFtoaEThhd32qVUN4UAF1STue3xUoPhbKU4DrXG8X1aCR

**Comment by selsta** [comment]
Though I don't know how quickly the pool distributes the block rewards. If they do it quickly then maybe they can't refund it anymore. Sorry, I didn't want to get your hopes up. Let's wait for @xnbya reply.

**Comment by xnbya** [comment]
The block reward has already been distributed to miners, the pool won't be able to refund it I'm afraid.

**Comment by PacificNWVet** [comment]
hey guys thats ok thanks for your help its much appreciated :) Again I have no idea why this happened.. I have a couple of transaction fees...

But I have never had this issue with bitcoin sneding transactions and certainly this one transaction with a 3.93xmr transaction fee has seriously made me weary of doing any cyrpto transactions..

Again I guess the name of the game is if your not present in the moment or paying attention then do not mess with cyrpto..

I dont ever mess with the settings.. but yes this has been a disheartening situation my friends.. I plan to not deal with cyrpto for a decent time atm..

3.93 xmr transaction fee for .34 transaction seems way to high and hopefully this is something that does not happen ever to anyone else.. it was 800 dollars approximately transaction fee for a 70 dollar transaction..

hopefully this doesnt happen to anyone else ever but I have just learned to always look at the transaction fee before sending..

thanks again for your help regardless its greatly appreciated.. ;)

**Comment by selsta** [comment]
I'm still trying to figure out why this happened and how we can avoid it in the future.

Couple ideas:

- Warn the user if the fee seems too high.
- Let GUI simple mode only connect to "trusted" remote node.

**Comment by PacificNWVet** [comment]
Hey im very curious to the resolution of what will happen from here..

Like when you find out why how can you fix it etc?

Will you have a warning with monero about connecting to certain nodes?

Warning the user about transaction ids etc is great as well as connected to trusted nodes..

I wish I was paying attention more but I have so many transactions that have a low transaction fee..

What possibility how much control does an operator of a nefarious node have? Is it possible the transaction fee would have shown up as low and not the actual number? Like and got that way?

**Comment by selsta** [comment]
> Is it possible the transaction fee would have shown up as low and not the actual number

No, this is not possible. It would be visible on the confirmation screen. The fee gets calculated client side with data from the server.

**Comment by Hueristic** [comment]
No one using wallet in simple mode will have a use case to have a higher fee than transaction so a simple check should be installed (maybe just keep area greyed if out of bounds with popup stating why) for any wallet not in advanced mode.

**Comment by PacificNWVet** [comment]
Hey someone from this dev team or someone from the xmrmine rig sent me the exact amount I lost in transaction fees.. I am truly blessed you guys are amazing.... Im not an emotional person.. but basically it had to be someone from here.. I already have a hard time from the holidays because of my mental health issues/pain issues from the military, but you guys have made my day and very happy..

What was going to be a bad day, and bad week for me, took a very nice turn.. you guys are awesome.. and my faith in the crypto community, particularly the xmr/monero community is amazing.. you guys went above and beyond to help me out i love you guys dearly for doing this for me.. I couldn't be happier that you guys helped me out.

I am incredibly blessed to have had you guys help me..

I will 100 percent be looking at transaction fees before sending and if it happens again I will certainly cancel the transaction and click on status for the log..

Thanks guys you guys are awesome :)

**Comment by shopglobal** [comment]
Happy new year!

**Comment by PacificNWVet** [comment]
thanks for the help guys and hope this gets fixed ;) thanks
