### ISSUE TITLE
sir, help, my monero is become .00000000000

### ISSUE THREAD

**Issue by batara666** [monero-project/monero#8137]
Sir, my friend told me to install moneri gui because he already has 0.2937551 on it, but after I install the monero gui, my balance is 0.0000000000000

![image](https://user-images.githubusercontent.com/67689090/148670282-5904c28a-ebde-46b1-a3f2-d5b25e9761ed.png)

the status is syncing....

**Comment by thomasvaughan** [comment]
GitHub is the place to report bugs, but what you are seeing is _not_ a bug. [**Click here**](https://monero.stackexchange.com/questions/6640/i-am-missing-not-seeing-a-transaction-to-in-the-gui-zero-balance) to see a question similar to yours (and a detailed answer!) posted on StackExchange.

The answer on StackExchange has two parts: one for people using local nodes and the other for people using remote nodes. To understand the difference, you may wish to read [**this section**](https://www.getmonero.org/get-started/faq/#anchor-long-sync) in the FAQ on the Monero website. If you then decide to use a remote node, you will find [further information in **Moneropedia**](https://www.getmonero.org/resources/moneropedia/remote-node.html) and the links therein. Also, you should check the [**monero-gui release page**](https://github.com/monero-project/monero-gui/releases) to make sure you're running the latest release.

**Comment by selsta** [comment]
You need to connect to a remote node or wait until your local node is synced.

Also see the reply above.
