### ISSUE TITLE
Transactions sent to high `AddressIndex` addresses are not visible in wallet.

### ISSUE THREAD

**Issue by 3h5t4tvz8etx1op2** [monero-project/monero#8138]
I run a site, which generate every address for each visitor. So many addresses are left unused. And after checking my view only wallet on the server I've seen many transactions coming to addresses with AddressIndex around 200, 400, 500 but none of that can be seen in my monero-gui wallet (nor in monerujo and cake)

**Comment by ndorf** [comment]
Not sure how one would accomplish this in the GUI, but if you can open the wallet in the CLI, the following commands should fix it:

`set subaddress-lookahead 50:1000`
`rescan_bc`

**Comment by 3h5t4tvz8etx1op2** [comment]
thanks @ndorf! Could you please tell me what does 50 and 1000 mean in that command?

**Comment by 3h5t4tvz8etx1op2** [comment]
Sadly - after even changing the numebrs to 50 and 2000 transactions send to address with account id ~1300 are have not been seen.

**Comment by JustFranz** [comment]
50 is account and 2000 is subaddress. With that command you will not see transactions in accounts 51 and up and it will not see transactions in accounts 1-50 if they do not have transactions in the first 2000 subaddresses or if there is a gap of 2000 subadrersses with no transactions on any of the 50 accounts.

I would generate the subaddresses and assign them to your visitors when they need them. Each time a visitor sends XMR it should be to a new subaddress. You save on scanning time, database size and will not have this issue.

**Comment by selsta** [comment]
@3h5t4tvz8etx1op2 do you generate a new account or a new address for each user?

if it's account then try `set subaddress-lookahead 1000:10` and then `rescan_bc`.

**Comment by 3h5t4tvz8etx1op2** [comment]
@JustFranz sadly I can't do that, the UX tradeoff is too big in my case, and I do use old addresses when they expire, but gaps of ~2k are frequent.

@selsta that was addresses. I've just re-coded the program to move the funds directly to my main address so there will be no problem with huge indexes.

**Comment by SamsungGalaxyPlayer** [comment]
You can fiddle with the lookahead values to raise/reduce the number of accounts/addresses as needed. If this is an outrageously huge number, take some steps to reduce the display of subaddresses unless a user is more likely than 1 in 500 or whatever to send funds to it. If you only need 1 account and you need a bunch of subaddresses, set the lookahead to `1:10000` on desktop CLI for roughly similar performance as the default, and then you can set up the auto-forward to the main address so it will appear in Cake Wallet.

**Comment by selsta** [comment]
Performance generally should say the same, only RAM usage increases with more subaddresses.

**Comment by 3h5t4tvz8etx1op2** [comment]
@SamsungGalaxyPlayer that's what I ended up with, just swaping the funds whenever certain amount is there, this is not the ideal solution for me - but it for sure works.

**Comment by 3h5t4tvz8etx1op2** [comment]
However, I think that there should be option to specify the subaddress-lookahead in all wallets, or at least in the `gui` wallet

**Comment by SamsungGalaxyPlayer** [comment]
I've added a note on the Cake Wallet side to support different lookahead values 👍

**Comment by 3h5t4tvz8etx1op2** [comment]
according to @selsta - how big is the memory footprint? I remember that in `core` bitcoin wallet the `wallet.dat` file was growing bigger and bigger with more addresses.

**Comment by selsta** [comment]
@3h5t4tvz8etx1op2 I don't have any numbers, you'll have to try it out
