### ISSUE TITLE
E Exception at while refreshing, what=reorg exceeds maximum allowed depth, use 'set max-reorg-depth N' to allow it, reorg depth: 356

### ISSUE THREAD

**Issue by 7jw92nVd1kLaq1** [monero-project/monero#8147]
> wallet-rpc_1         |  2022-01-18 13:10:21.478    E reorg_depth > m_max_reorg_depth. THROW EXCEPTION: error::reorg_depth_error
> 
> wallet-rpc_1         | 2022-01-18 13:10:21.485  E Exception at while refreshing, what=reorg exceeds maximum allowed depth, use 'set max-reorg-depth N' to allow it, reorg depth: 356  

Here is the issue I am currently facing with launching the RPC server in a Docker container of Monero image using Dockerfile.

So, I was able to create a Docker image using Dockerfile successfully, and subsequently tried the RPC server out in a Docker container. And the errors I posted above keep popping up no matter which wallet I use to launch the server. I wonder if some of you guys deal with the same issue I am dealing with.

**Comment by selsta** [comment]
Is your node fully synced?

**Comment by selsta** [comment]
No reply by the issue creator, closing.
