### ISSUE TITLE
Where is the blockchain file stored at? (NAB)

### ISSUE THREAD

**Issue by TimyIsCool** [monero-project/monero#8148]
I was wondering where the blockchain file is, I need to delete it because i have no space left on my ssd

**Comment by selsta** [comment]
~/.bitmonero/lmdb/data.mdb

**Comment by TimyIsCool** [comment]
> ~/.bitmonero/lmdb/data.mdb

Thank you, anyway to move it to a different folder to a different disk?

**Comment by selsta** [comment]
Use the `--data-dir` flag when starting monerod.

**Comment by TimyIsCool** [comment]
> 

ty

**Comment by TimyIsCool** [comment]
> Use the `--data-dir` flag when starting monerod.

What is the size of the blockchain file?

**Comment by selsta** [comment]
~ 110GB, 40GB pruned
