### ISSUE TITLE
Getting this error, rpc-client-secret-key: RPC client secret key should be 32 byte in hex format

### ISSUE THREAD

**Issue by TimyIsCool** [monero-project/monero#8150]
Hey there, Im trying to setup rpc but im getting this error: rpc-client-secret-key: RPC client secret key should be 32 byte in hex format
How would i fix this?

Also what is the blockchain size?

**Comment by reemuru** [comment]
@TimyIsCool I think this error message is about rpc payments key. If you want to pass `--rpc-client-secret-key` for RPC payments it must be hex format and 32 bytes. So if you did something like `--rpc-client-secret-key 123` that would yield an error. The key can be acquired from `monero-wallet-cli` by running `rpc_payment_info`

```bash
RPC client ID: <abc...>
RPC client secret key: <abc...>
```

There are more details in the commit message 2899379791b7542e4eb920b5d9d58cf232806937

**Comment by reemuru** [comment]
> Also what is the blockchain size?

mainnet - 123G
stagenet - 9G

**Comment by TimyIsCool** [comment]
> @TimyIsCool I think this error message is about rpc payments key. If you want to pass `--rpc-client-secret-key` for RPC payments it must be hex format and 32 bytes. So if you did something like `--rpc-client-secret-key 123` that would yield an error. The key can be acquired from `monero-wallet-cli` by running `rpc_payment_info`
> 
> ```shell
> RPC client ID: <abc...>
> RPC client secret key: <abc...>
> ```
> 
> There are more details in the commit message [2899379](https://github.com/monero-project/monero/commit/2899379791b7542e4eb920b5d9d58cf232806937)

Thank you, what would the config file look like for monero-wallet-rpc?

**Comment by reemuru** [comment]
> Thank you, what would the config file look like for monero-wallet-rpc?
@TimyIsCool  StackExchange would be a better resource for user setup stuff.

https://monero.stackexchange.com/questions/9857/is-there-a-monerod-config-file-to-change-certain-settings-when-you-run-monerod-i
