### ISSUE TITLE
Accounts and seeds

### ISSUE THREAD

**Issue by titoli11** [monero-project/monero#8160]
Sorry for the beginner question but if I generate a new account for the monero-wallet-cli does that mean i have to make a new backup everytime of the seed? I noticed that recovering from my seed only recovers the first account in the wallet. 
Would apriciate any input

**Comment by ndorf** [comment]
No, all of the accounts and subaddresses in the same wallet are derived from the same seed. You only need the one.

Have you ever received any transactions to the second (or subsequent) accounts? If not, they won't show up when you restore, but your wallet still controls them. If you then make a "new" account it will be the same one as you had before.

Note, however, that any labels you set on the account won't be preserved if you restore from the seed. If you need those, you would have to back up the actual wallet files. This also applies to certain other metadata, for example the destination address of any transactions you've sent.
