### ISSUE TITLE
Don't require --rpc-login with --rpc-access-control-origins

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#8168]
This issue requests removing the requirement to use RPC authentication when starting monerod with `--rpc-access-control-origins`.

That way, public nodes may serve browser clients.

**Comment by jeffro256** [comment]
This would be great! I've run into this issue myself

**Comment by jeffro256** [comment]
Tangentially related issue: #7951

**Comment by jeffro256** [comment]
@woodser check out the above PR. There may be some security implications with allowing --rpc-access-control-origins with public nodes, but I think that would mostly be a concern for the browser applications, not the daemon operators. In that case, the incumbent security concerns of using an untrusted node overshadow what issues --rpc-access-control-origins bring into the equation,

**Comment by woodser** [comment]
Great. The PR should be opened on release-0.17 to be incorporated into the next release, too.

**Comment by jeffro256** [comment]
@woodser done: #8227
