### ISSUE TITLE
[Bug] --daemon is not an invalid argument

### ISSUE THREAD

**Issue by elibroftw** [monero-project/monero#8182]
I used `--daemon` instead of `--detach` accidentally and got some weird command line argument parsing errors. The error message changes if I use `--daemon` as the first argument or the last argument.

**Comment by selsta** [comment]
`--daemon` is not a valid option / setting for monerod. See `./monerod --help`.

**Comment by elibroftw** [comment]
Well then I should be given that error message. The error message I get is that --config-file is not an option

**Comment by elibroftw** [comment]
Try it yourself `monerod --daemon --config-file=monerod.conf`

**Comment by selsta** [comment]
`daemon` is a special keyword for the command line argument parser so it doesn't print the usual help screen but instead It tries to send `--config-file=monerod.conf` as a command which obviously doesn't exist.

Now why daemon is a special keyword, I don't know.

**Comment by elibroftw** [comment]
Can you document somewhere then at least?

**Comment by selsta** [comment]
I don't know why you entered --daemon in the first place. It's not a documented keyword.

**Comment by elibroftw** [comment]
Well like I said, I got caught up in the moment and read --detach as --daemon because I was trying to create a systemd service. So much daemon my brain thought detact was daemon.

**Comment by selsta** [comment]
I don't see the point in documenting things to **not** enter. Documentation works the other way around, only valid keywords get documented in the `--help` screen. Everything else will be broken in some way, ideally with the correct error message.

If someone wants to fix this that the correct error message shows up then this can get merged, but this has such a low priority that I won't bother with it.

**Comment by selsta** [comment]
I can reopen this want but I doubt anyone will fix this as it's a harmless edge case.

Please also update the issue title and first post to make it more clear what you are reporting.

**Comment by jeffro256** [comment]
To add, running only `monerod --daemon` gives the following error message:

    Failed to parse arguments: the required argument for option '--daemon_command' is missing

I assume then that maybe `--daemon` is aliased or something to `--daemon_command`.

**Comment by selsta** [comment]
@jeffro256 thanks, that solves the question

seems to be an alias that was maybe kept for backwards compatibility
