### ISSUE TITLE
I forked Monero, it wont stop trying to sync?

### ISSUE THREAD

**Issue by kvthweatt** [monero-project/monero#8185]
I mined --offline to block height 140 or so.

Why isn't the daemon picking up the existing chain?

When I start my daemon online, it says "Syncing with the network, this may take a long time"
Also when started online, using print_block 100 gives the appropriate block, so my daemon
knows the blocks are there.

**Comment by moneromooo-monero** [comment]
Just give it time to find other peers.

**Comment by kvthweatt** [comment]
Oh so the only problem is there's no one else mining? Or is it because there's no other wallet trying to sync?

**Comment by kvthweatt** [comment]
The problem I'm having because of it is I can't mine locally, because the miner daemon says "BUSY"

**Comment by selsta** [comment]
This isn't the correct place to get fork help, I would recommend to search on Google or ask other projects that have forked monero.
