### ISSUE TITLE
show_transfer <txid> command doesn't work in CLI

### ISSUE THREAD

**Issue by Cactii1** [monero-project/monero#8188]
I tested this on two wallets. On a windows system with pre-built binaries.

First I did a show_transfers in and grabbed a txid from the list and then I tried show_transfer with a txid and it always gives the message "failed to parse txid".

I don't have the skills to follow the code to debug/fix it - sorry.

**Comment by ndorf** [comment]
I couldn't reproduce this with 0.17.3.0 on Linux. Are you sure you're copy/pasting the txid, and not some other field? The txid would be exactly 64 hexadecimal characters.

**Comment by Cactii1** [comment]
Oh man! I feel so dumb. Massive error on my part. I was using the encrypted payment ID.
