### ISSUE TITLE
add check to make sure arguments of --log-file and --wallet-file are not pointing to the same file

### ISSUE THREAD

**Issue by mbg033** [monero-project/monero#820]
e.g. following command will silently overwrite the wallet:
`simplewallet --wallet-file wallet_m --password "" --log-file wallet_m --command balance`

**Comment by moneromooo-monero** [comment]
I guess one could check against other files in the command line, but then why not the lmdb files, well known system files, etc. The program is doing what was asked. But a patch would be fine I guess.

**Comment by luigi1111** [comment]
It seems like the log file shouldn't overwrite any existing non-text files (and should append to such a file). That might be easy or hard to implement. :)

**Comment by moneromooo-monero** [comment]
Logs do append. Analyzing existing files to see if they're logs or not... Meh.

**Comment by moneromooo-monero** [comment]
I'm not going to do that. Just don't point your log file at your wallet ^_^

+invalid
