### ISSUE TITLE
How to simulate a TXID for multiple UTXO transaction

### ISSUE THREAD

**Issue by EWIT521** [monero-project/monero#8204]
How to simulate a TXID for multiple UTXO transaction，Thank you very much

**Comment by selsta** [comment]
Can you explain in more detail what you want to do?

**Comment by EWIT521** [comment]
Account A  has   2 xmr
Account B  has   3 xmr
two UTXOs under different accounts 
want to spent In a transfer transaction

**Comment by selsta** [comment]
You will have to do two separate transactions.

**Comment by EWIT521** [comment]
The wallet is under account 0 by default, I can't see another UTXO, do I have to change the account?

**Comment by selsta** [comment]
Yes, see `help account`.

Also you can use subaddressses instead of accounts so that you can spend them in a single transaction. See `help address`.

**Comment by EWIT521** [comment]
Thank you very much
