### ISSUE TITLE
unit_tests node_server.bind_same_p2p_port FAILED

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [monero-project/monero#8206]
OS: OpenBSD 7.0
commit d562deaaa950979b7a31a441a8f02a00013e26d6 (HEAD -> master, origin/master, origin/HEAD)

To reporduce `make release-test`

[LastTest.log](https://github.com/monero-project/monero/files/8188609/LastTest.log)

**Comment by AK041120** [comment]
> OS: OpenBSD 7.0 commit [d562dea](https://github.com/monero-project/monero/commit/d562deaaa950979b7a31a441a8f02a00013e26d6) (HEAD -> master, origin/master, origin/HEAD)
> 
> To reporduce `make release-test`
> 
> [LastTest.log](https://github.com/monero-project/monero/files/8188609/LastTest.log)

**Comment by selsta** [comment]
This test currently only works on Linux by default. The following comment is for macOS but should also apply to OpenBSD.

```
For Mac OSX, set the following alias, before running the test, or else it will fail:
sudo ifconfig lo0 alias 127.0.0.2
```
