### ISSUE TITLE
adding entry to address book edits description of anther entry

### ISSUE THREAD

**Issue by Arimfexendrapus** [monero-project/monero#8218]
Adding an entry to the address book in Monero GUI version 0.17.3.1 will result in not only an entry being added, but it will also cause the description of the bottom entry in the address book to change to the description of the newly added entry.

**Comment by reemuru** [comment]
@Arimfexendrapus I was able to duplicate this in monero-wallet-gui but not the cli so this issue should probably be [here](https://github.com/monero-project/monero-gui/issues). Looks like address book index 0 is getting overwritten on new add. Will take a look later.

![duplicate-8218](https://user-images.githubusercontent.com/13033037/158316492-176f13be-dbc2-47cb-88c5-19bed783015e.png)

**Comment by selsta** [comment]
Wrong repo
