### ISSUE TITLE
archiving log files

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [monero-project/monero#8219]
I have noticed that some daemons are sent a signal when their log files are being swapped out and archived.

Does monerod require a signal or something else when log archiver is running to keep it from crashing?

**Comment by trasherdk** [comment]
I have in `/etc/logrotate.d/monero`
```
/var/lib/monero/data/mainnet/logs/*.log {
        notifempty
        weekly
        rotate 4
        missingok
        copytruncate
}
```
