### ISSUE TITLE
Monero GUI Wallet download issue

### ISSUE THREAD

**Issue by Vacman** [monero-project/monero#8221]
Attempting to download the wallet GUI (Windows 64 bit) from their site. Neither the installer version or the zip version are downloadable at this point.

**Comment by selsta** [comment]
What happens when you try downloading? It works for me, could be an issue with the CDN at your location.

Does this link work? First is the installer, second the .zip

- https://dlsrc.getmonero.org/gui/win64install
- https://dlsrc.getmonero.org/gui/win64

**Comment by selsta** [comment]
Firewall or anti virus blocking the download.
