### ISSUE TITLE
Monero Multisig for HF

### ISSUE THREAD

**Issue by UkoeHB** [monero-project/monero#8237]
There are currently several multisig PRs in the air. Ideally all of them would be merged before the upcoming [hard fork](https://github.com/monero-project/meta/issues/680).

### Mandatory PRs

| PR |  Author | (Review) / Approved / Merged | Status |
|----|---------|------------------------------|--------|

### Good-to-have PRs

| PR |  Author | (Review) / Approved / Merged | Status |
|----|---------|------------------------------|--------|
[Kex round boosting #8203](https://github.com/monero-project/monero/pull/8203) | @UkoeHB | none | Needs to rebase onto the force-update flag PR and get reviewed. |
| [Code quality #7852](https://github.com/monero-project/monero/pull/7852) | @UkoeHB | @rbrunner7  | Either review+merge or reject it.

**Comment by arnuschky** [comment]
Thanks for the summary @UkoeHB - I was a bit lost after the dev meeting. 

One question: You said above that the status of #8220 is "Needs a review of multisig kex changes." To what changes are you referring exactly? Are there additional, un-approved changes in the PR that you are referring to, or do you mean #8203?

**Comment by UkoeHB** [comment]
@arnuschky #8220 adds a key exchange round, this is a change to the key exchange protocol that's in master. The reviews on that PR did not validate the kex changes.
