### ISSUE TITLE
monerod Segmentation fault in libzmq.so

### ISSUE THREAD

**Issue by othello777** [monero-project/monero#8238]
I've been experiencing segfaults every 1-5 days after starting the monero daemon. 

arguments:
`--zmq-pub tcp://<local ip>:18083 --disable-dns-checkpoints --enable-dns-blocklist --rpc-bind-ip <local ip> --restricted-rpc --confirm-external-bind`
gdb output:
```
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 11 "monerod" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fdc9f7fe700 (LWP 49359)]
0x00007ffff7dc8483 in ?? () from /lib/x86_64-linux-gnu/libzmq.so.5
```
I got this far but I'm a bit stumped. thanks

**Comment by selsta** [comment]
Which monero version are you using? Where did you get it? Is it custom compiled?

**Comment by othello777** [comment]
oh right, yes it is compiled from source. originally it was compile from source the latest release (0.17) but after it was crashing a bunch I pulled the rest of the changes and recompiled. but it still crashes every 1-5 days. I think I've been on 319b831e65437f1c8e5ff4b4cb9be03f091f6fc6
my libzmq info:
`libzmq3-dev/focal,now 4.3.2-2ubuntu1 amd64 [installed]`
`libzmq5/focal,now 4.3.2-2ubuntu1 amd64 [installed,automatic]`

**Comment by selsta** [comment]
Can you try to compile with

```
make depends target=x86_64-linux-gnu
```

It will build static binaries and the dependencies get also compiled from scratch. That will make sure you have to latest version of libzmq.

**Comment by othello777** [comment]
It gave errors about libtool and gperf not being installed. I recompiled successfully and will be testing now. if it doesn't crash within a week it will be solved. thanks

**Comment by othello777** [comment]
ok it still crashed. its notable that I am running p2pool and monerod on a PC with only 4GB of RAM (and 4GB swap)

**Comment by othello777** [comment]
OS: Ubuntu Server 20.04
CPU: Intel Core2 Duo E6750
RAM: 4x1GB DDR2
Storage: 2 HDDs in a software RAID1

**Comment by selsta** [comment]
As far as I know if RAM is an issue it would usually get killed by OOM, not a segfault in libzmq.

**Comment by SChernykh** [comment]
You can try to run p2pool with `--no-randomx --no-cache` parameteres to use minimum RAM.

**Comment by othello777** [comment]
@selsta good to know that. I notice the CPU on the machine isn't used much so that wouldnt be an issue either.
@SChernykh thanks I'll try that.

**Comment by othello777** [comment]
I tried running p2pool with the arguments and monerod still crashed

**Comment by selsta** [comment]
Do you still have this issue? Can you reproduce with release binaries from getmonero.org?
