### ISSUE TITLE
GUI wallet is inaccessible with voiceover on Mac

### ISSUE THREAD

**Issue by demhademha** [monero-project/monero#8252]
System: macOS Montaray (M1 MacBook Pro)

Using the gui wallet with voiceover just speaks "horizontal scroll bar"

**Comment by selsta** [comment]
@rating89us did some work to making it more accessible but the changes didn't all get merged yet

**Comment by selsta** [comment]
Closing this here as it's a duplicate and also wrong repo: https://github.com/monero-project/monero-gui/issues/3343
