### ISSUE TITLE
Locate wallet file

### ISSUE THREAD

**Issue by arkadiy-telegin** [monero-project/monero#8265]
Due to a terrible accident, I deleted my whole filesystem.

Luckily, I could restore a lot of files. Unluckily, there is no way to know the name of the restored files, only the type.

It seems that Monero GUI doesn't store any metadata in the wallet file, which makes it very difficult to find which of the hundreds of binary files of approx. 2kB is the monero wallet file.

So my question is, could I somehow make a script that would make monero-cli try to decrypt hundreds of files in hopes that one of them would be the sought wallet file?

I run Arch Linux.

Thanks!

**Comment by selsta** [comment]
the wallet files usually end with .keys, do the restored files have any extension?

**Comment by arkadiy-telegin** [comment]
The restored file would be categorized as application/octet-stream. There's unfortunately no separate file type for keys.

**Comment by selsta** [comment]
Ok, you have to rename the file you are testing to something with .keys in the name and then try

```
./monero-wallet-cli --wallet-file test.keys --password "your_password"
```

If it's not a proper keys file then monero-wallet-cli will close with exit code 1.

**Comment by hinto-janaiyo** [comment]
```
#!/bin/bash

folder="/your/path/here/"
log="/your/log/here/"
binary="/your/binary/here/"

printf "Password: "
read -s -p "Password: " password 
echo "Working..."

for wallet in $(find $folder -size -5k) ;do
    "$binary" --wallet-file "$wallet" --password "$password" > "$log" &
done
```
this tests every file in `$folder` that is under 5kb and outputs it to a log file

replace `/your/path/here/` with whatever folder/path you want to search  
replace `/your/log/here/` with where you want to save the log  
replace  `/your/binary/here/` to the path of a monero-wallet-cli binary

after it finishes, run `grep "Filename" /your/log/here/` and that'll show you every file that was a valid wallet

**Comment by selsta** [comment]
@hinto-janaiyo thank you for a proper solution. Closing this here as the question seems answered.

**Comment by arkadiy-telegin** [comment]
Thank you very much @selsta and @hinto-janaiyo. I am now going to try to recover it.

**Comment by hinto-janaiyo** [comment]
@arkadiy-telegin

actually you might want to manually run `grep "Filename" "/your/log/here/"` afterwards 

`sleep 1` sometimes isn't enough time for monero-wallet-cli to finish writing to the log so the grep in the script doesn't work
