### ISSUE TITLE
busy wait

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [monero-project/monero#8268]
I have managed to sync the entire blockchain but now am having the problem of monerod busy waiting. While observing monerod with `top` the 2 core cpu is completely consumed with 100% Kernel and 100% Spin when it is waiting for more blocks. This effectively freezes the entire computer.

OS: OpenBSD 7.0

**Comment by jeffro256** [comment]
Are you using an SSD or a hard drive? What kind of computer?

**Comment by BebeSparkelSparkel** [comment]
The monero files are on an SSD.

Currently, not allowing incoming network transactions.

Hardware: Dell Inspiron 541, dual core, 4Gb ram

OS: OpenBSD 7.0

**Comment by jeffro256** [comment]
Might be related: https://github.com/monero-project/monero/issues/8210
Can you see if your message queues are overloaded?

**Comment by BebeSparkelSparkel** [comment]
Ran for 90mins with no overflows listed with `dmesg`.

**Comment by jeffro256** [comment]
I would post this to https://reddit.com/r/monerosupport because it's not documenting a specific issue, and you're more likely to get help there.

**Comment by selsta** [comment]
Seems to be a duplicate of https://github.com/monero-project/monero/issues/7027

Seems to be related to OpenBSD.

**Comment by BebeSparkelSparkel** [comment]
Duplicate
