### ISSUE TITLE
Monerod blocked by MSE

### ISSUE THREAD

**Issue by MaxQiu0108** [monero-project/monero#8283]
I am here to report an issue that monerod.exe, the deamon, is blocked by microsoft security essentials (or MSE) as a trash dropper.

**Comment by selsta** [comment]
You have to add an exception to your anti virus. There isn't anything we can do on our side here.

https://monero.stackexchange.com/questions/10798/my-antivirus-av-software-blocks-quarantines-the-monero-gui-wallet-is-there
