### ISSUE TITLE
Apple Silicon official binaries.

### ISSUE THREAD

**Issue by web-sharp** [monero-project/monero#8286]
Official Apple Silicon binaries available [here](https://github.com/web-sharp/monero/releases/tag/v0.17.3.0).  Website only has Intel.

monero-blockchain-ancestry
monero-blockchain-depth
monero-blockchain-export
monero-blockchain-import
monero-blockchain-mark-spent-outputs
monero-blockchain-prune
monero-blockchain-prune-known-spent-data
monero-blockchain-stats
monero-blockchain-usage
monero-gen-ssl-cert
monero-gen-trusted-multisig
monero-wallet-cli
monero-wallet-rpc
monerod

**Comment by hyc** [comment]
In what way are these "official" ?

If you had to pass any particular flags to the build process, it would be better to submit a PR to get those changes integrated into the Gitian build scripts, which are the actual mechanism for producing "official" binaries.

**Comment by web-sharp** [comment]
No tinkering!  No tinkering.Except for nginx and tor.  I tinkered with those don’t distribute them   On Mon, Apr 25, 2022 at 9:22 AM, Jeffrey Ryan ***@***.***> wrote:  
@web-sharp Can you explain how you built these, and if there was an tinkering necessary besides the default build scripts?

**Comment by selsta** [comment]
It sounds like these are just static binaries for ARM Mac, not built with gitian / depends.

**Comment by web-sharp** [comment]
@selsta is right   On Mon, Apr 25, 2022 at 9:26 AM, selsta ***@***.***> wrote:  
It sounds like these are just static binaries for ARM Mac, not built with gitian / depends.

**Comment by selsta** [comment]
I'll close this here as these are 3rd party binaries without reproducible builds.

@web-sharp it's fine for you to offer 3rd party builds but we can't advertise them as official.
