### ISSUE TITLE
M1 binaries

### ISSUE THREAD

**Issue by web-sharp** [monero-project/monero#8291]
I will provide you with the Xcode flags for cross compiling.   When you compile with Homebrew I used the Hardening flags for tor and nginx.   --without-mail and --without-realip

**Comment by selsta** [comment]
I didn't accuse you of tempering with the binaries. It's fine if you want to provide 3rd party binaries for M1, but the bug tracker is not the place for this, especially when they are incorrectly tagged as "official".

We have a specific process for building release binaries and if that process isn't followed they aren't "official" binaries.

**Comment by web-sharp** [comment]
Well your release is no more official than mine if it doesn't work so let's test it you pass some amount to me I'll pass everything along to Jeff. 

Or whoever you working with I don't know you I'm not running your binary on my machine. 

I do know monero that's why I want to contribute.  I can't compile bitcoin I can't compile Ethereum I don't trust those.

So if you want to test it just tell me what parameters you want to me to run on my machine through an email I will pass everything along to Jeff then we can all know that version 17_3 is working on main_net.

If it's not working on Main_net then don't tell people to download it on the Debian 17.2 release.

**Comment by web-sharp** [comment]
> I didn't accuse you of tempering with the binaries. It's fine if you want to provide 3rd party binaries for M1, but the bug tracker is not the place for this, especially when they are incorrectly tagged as "official".
> 
> 
> 
> We have a specific process for building release binaries and if that process isn't followed they aren't "official" binaries.

If you're going to provide binaries then warn people about the hardcoded DNS servers.

I'm providing these binaries unaltered.  I don't recommend anybody run them because they have those hardcoded DNS servers in there and it will work just fine if you go and change those DNS servers.  

Put your money where your mouth is and put my binaries with yours.  I'm on my node anonymously and if you don't like it tough titties

**Comment by jeffro256** [comment]
@web-sharp : @selsta is legit and part of the core dev team, funded through the [CCS](https://ccs.getmonero.org/proposals/selsta-4.html). He's not trying to trick you, but there is a process which binaries must go through (gitian). It's good that you're contributing, but advertising your binaries as "official" is misleading and dangerous since we can't guaranteed that your binaries are not malicious. 

If you want "official" Apple Silicon binaries, then create a PR for the gitian build process. I'm not an expert, but @hyc or @mj-xmr are much more familiar with that process.

**Comment by mj-xmr** [comment]
We do confirm each other's binaries through Gitian, see (`contrib/gitian` directory). Contributions there are always welcome and will allow reviewers to have a peek.

**Comment by web-sharp** [comment]
I didn't compile it with Xcode I used gnu C.   I can probably get that to you though

**Comment by web-sharp** [comment]
Does anyone have a coupon code I can use with Mac stadium?  lol.  It's pretty pricy and all my X86_64 Macs run linux

**Comment by web-sharp** [comment]
If @selsta is paid in euros then I suppose I trust them.  I will purchase bare metal x86_64 with Mac stadium and test that I can send 32 Monero to it using from main_net

**Comment by selsta** [comment]
https://github.com/monero-project/monero/tree/master/contrib/gitian

As it was already said before, this is the process we are using for release binaries. Support for M1 Mac has to be added there. We cross compile everything from x86_64 linux.
