### ISSUE TITLE
17.3.0 Rollback

### ISSUE THREAD

**Issue by web-sharp** [monero-project/monero#8303]
Has anyone even ran the test library since v17.2 ? 

I see a lot of commits to the 17.3 branch which ban transaction types and it looks like none of this has even been verified on Main_net yet.

-  missing binaries for major platforms
-  Unit tests don't run
-  multitude of messaging and onion features were added

**Comment by selsta** [comment]
We constantly run the tests, on every single commit to be exact.

**Comment by selsta** [comment]
Here is an example of tests run on the latest PR: https://github.com/monero-project/monero/runs/6235008179

If you meant something else please reword it. Closing this in the meantime as your question was answered.

**Comment by web-sharp** [comment]
Please stop closing my issues when you have only proven that nothing works except on Ubuntu

**Comment by web-sharp** [comment]
Make build-test 

… Nothing works

**Comment by web-sharp** [comment]
> We constantly run the tests, on every single commit to be exact.

Show me one that isn't Ubuntu

**Comment by web-sharp** [comment]
Please reopen my Issue or stop commenting them on at all. 

Your comments and feedback are completely useless

**Comment by selsta** [comment]
Please check the README: https://github.com/monero-project/monero#on-linux-and-macos

The command is called:

```
make release-test
```

**Comment by web-sharp** [comment]
That's what I just said.

It doesn't work .

you're clearly trying to do 50% ruin takeover of monero.  Where enough idiots, at least 50% adopt an a New version that doesn't work when the  current version already worked ... and it wasn't needed

**Comment by web-sharp** [comment]
17.2 works Just fine I've traded plenty of monero and products online  for several.   

 there's no reason to upgrade to 17.3 As far as I can tell nothing works

**Comment by selsta** [comment]
No, you said `make build-test`, that's two different commands. Try to read properly.

**Comment by web-sharp** [comment]
make Is a command 

try putting a command line in a command line once in your life

**Comment by selsta** [comment]
`build-test` and `release-test` are two different targets. I would suggest reading this if you don't know what make targets are: https://stackoverflow.com/questions/2270643/what-is-a-make-target

**Comment by web-sharp** [comment]
Return the first principle

TEST

**Comment by web-sharp** [comment]
OK I think it's clear you are paid by the government organization at this point to ruin monero

**Comment by sanderfoobar** [comment]
- this issue has the nonsensical title "17.3.0 Rollback" - when posting issues you ought to keep them relevant to the actual issue
- the actual issue does not specify a *specific problem* that needs to be discussed or solved, instead you listed 3 random statements
- you are being rude to a valuable community member

So, if you want *something* fixed, learn how to articulate your problem into something that is comprehensible and post a new github issue.

**Comment by plowsof** [comment]
> OK I think it's clear you are paid by the government organization at this point to ruin monero

If by 'government organization' you mean 'Community Crowdfunding System' then yes, you are correct. see (note the number 5): https://ccs.getmonero.org/proposals/selsta-5.html

**Comment by jeffro256** [comment]
@web-sharp To run the tests, do `cd build/<OS>/<branch>/release/tests/ && make test`

**Comment by web-sharp** [comment]
![image](https://user-images.githubusercontent.com/63826817/166125619-6c2c87d9-8ac5-4602-b369-245c48dab92b.jpeg)![image](https://user-images.githubusercontent.com/63826817/166125620-bddb3878-dfb8-4138-a8c4-6290f0849161.jpeg)

Here is the promised bounty.

**Comment by web-sharp** [comment]
> @web-sharp To run the tests, do `cd build/<OS>/<branch>/release/tests/ && make test`

Still doesn't work

**Comment by web-sharp** [comment]
> > OK I think it's clear you are paid by the government organization at this point to ruin monero
> 
> 
> 
> If by 'government organization' you mean 'Community Crowdfunding System' then yes, you are correct. see (note the number 5): https://ccs.getmonero.org/proposals/selsta-5.html
> 
> 
> 
> 

Rolls eyes.  So no accountability that's aparent!!  Here's two euros for you they matter to me nothing

**Comment by trasherdk** [comment]
@web-sharp update your github profile :grimacing: 
![image](https://user-images.githubusercontent.com/5003891/166136071-488a2e48-391f-44ce-9f3b-c63002bb8134.png)
