### ISSUE TITLE
17.2 Debian patch

### ISSUE THREAD

**Issue by web-sharp** [monero-project/monero#8305]
I'm removing the recommendation to update to 17.3 in the Debian 17.2 release.  It's clearly unstable the make files can't even run tests on Microsoft or OSX.   17.3 is an ANDROID only device branch so far.

**Comment by web-sharp** [comment]
@selsta

**Comment by web-sharp** [comment]
Mac OSX Results: After 4 hours it can't run on CORE BECAUSE YOU VIRTUALIZED IT

[ 98%] Built target net_load_tests_clt
[100%] Building CXX object tests/net_load_tests/CMakeFiles/net_load_tests_srv.dir/srv.cpp.o
[100%] Linking CXX executable net_load_tests_srv
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
[100%] Built target net_load_tests_srv
Running tests...
Test project /Volumes/Ext4/.bitmonero/github/build/Darwin/_HEAD_detached_at_v0.17.3.2_/debug
      Start  1: hash-target
 1/21 Test  #1: hash-target ......................   Passed    3.58 sec
      Start  2: wallet-crypto-bench
 2/21 Test  #2: wallet-crypto-bench ..............   Passed    1.64 sec
      Start  3: core_tests
^Cmake[1]: *** [test] Interrupt: 2
make: *** [debug-test] Interrupt: 2

**Comment by hyc** [comment]
I see no bug here. Core tests routinely takes over 6 hours on my old Intel laptop.
