### ISSUE TITLE
Bug v0.17.3.2 Generate payment proof button - non responsive

### ISSUE THREAD

**Issue by westz36** [monero-project/monero#8313]
Hello found a bug,

Environment
- Windows 11 x64 Virtual Machine in VMware workstation
- Remote node: xmr.support
- Ran monero-gui as admin
- No password key file

How i found the bug:
1. Created a temp wallet in monero-gui v0.17.3.1
2. temp wallet sent a transaction, generated payment proof, works no problem
3. Same temp wallet loaded in v0.17.3.2, tried to generate payment proof, no response.

Not sure why this is happening, already whitelisted v0.17.3.2 in windows defender.

thanks

**Comment by selsta** [comment]
please open an issue here: https://github.com/monero-project/monero-gui

**Comment by westz36** [comment]
> please open an issue here: https://github.com/monero-project/monero-gui

ok
