### ISSUE TITLE
Adding Swapzone to the "Swappers" section

### ISSUE THREAD

**Issue by MariaSwapzone** [monero-project/monero#8345]
Hello team!

I'm Maria, a marketing manager at Swapzone - an instant crypto exchange aggregator. We help users to compare exchange rates, analyze and swap cryptocurrency in just one interface. 

XMR is one the most popular assets on our platform and we also have a separate page of your coin so new users can learn about your project: https://swapzone.io/currencies/monero

I'd love to know whether it's possible for you to add our project in your "Swappers" section (https://www.getmonero.org/community/merchants/). It would be a huge deal for us. 

Let me know your opinion about it!
Best regards, Maria

**Comment by selsta** [comment]
Please open an issue here: https://github.com/monero-project/monero-site

Note that in the past we had issues with scammers and scam reports so we are more careful with listing on the official website now.
