### ISSUE TITLE
"Error: Daemon response did not include the requested real outputs"

### ISSUE THREAD

**Issue by garth-xmr** [monero-project/monero#8347]
Tried to send 50 tXMR. CLI wallet failed with error text below.

Result: `Error: internal error: Daemon response did not include the requested real outputs`

Monero-wallet-cli.log: https://paste.debian.net/1241707/

Note: I am copying and pasting from a VPS via nano editor, so apologies for the broken log lines. If anybody needs further info just let me know.

**Comment by selsta** [comment]
For completeness, what is your wallet version and what your daemon version?

**Comment by garth-xmr** [comment]
Freshly pulled from master branch. 

2022-05-22 23:40:20.319 I Monero 'Oxygen Orion' (v0.17.0.0-6e60919e6)

**Comment by moneromooo-monero** [comment]
Are you sure your wallet is synced to the same chain as your daemon ?
If your wallet still refreshes new txes, it means it is.

**Comment by garth-xmr** [comment]
Absolutely. For some reason, sending a 100 tXMR worked fine, but sending a 50 tXMR gave this error. Very strange.

**Comment by garth-xmr** [comment]
You can see that it’s telling me I have a balance of 100 tXMR at the beginning of the log

**Comment by selsta** [comment]
If you try to do the same tx do you get the same error?

**Comment by selsta** [comment]
@garth-xmr can you share the seed with moneromooo on irc?

**Comment by garth-xmr** [comment]
Sure but the outputs have been spent. And the account was created with a spend/view key pair

**Comment by garth-xmr** [comment]
Mooo showed me how to pop blocks and do this test myself so I’ll work on this in the next week

**Comment by garth-xmr** [comment]
Mooo and I are both unable to reproduce this issue so I'm closing it
