### ISSUE TITLE
Feature request: bind multiple RPC ports and selectively control access of each

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#835]
Would be cool to bind multiple RPC ports to bitmonerod, and be able to lock down one of them using the --restricted-rpc flag.

So when launching, flag would be

`--rpc-restricted-port 18085 --rpc-bind-port 18081`

**Comment by jonathancross** [comment]
This would be very useful for those who want to monitor from localhost (`monerod status`, `monerod stop_daemon`, etc), but restrict remote connections.

**Comment by Timo614** [comment]
I have this somewhat working here: https://github.com/Timo614/monero/tree/bind-multiple-rpc-ports

I'm going to spend a bit more time with it before putting up a pull request as I'm not sure if my approach is ideal but in the branch the logic adds the argument `--rpc-restricted-bind-port` for create a restricted RPC port
https://github.com/Timo614/monero/commit/4a0aa7fb474e86063cd178b3d5f8fc42a404eadf was able to confirm that both reply to unrestricted calls (such as `/getinfo`) while the restricted port cannot handle the restricted calls (`/get_connections`).

**Comment by moneromooo-monero** [comment]
+resolved
