### ISSUE TITLE
'#monero-markets:monero.social' channel in Monero's official matrix space is ran by a troll

### ISSUE THREAD

**Issue by Kreyren** [monero-project/monero#8350]
* https://matrix.to/#/!TlVgUtVNZychNpMzKW:matrix.org/$rBEikedNKTDrmNXLBm9gpihg3-lv8L5GnA_tCDdcB-M?via=matrix.org&via=monero.social&via=halogen.city
* https://matrix.to/#/!TlVgUtVNZychNpMzKW:matrix.org/$lS4DznyN9xTLP1HtHvjBfiAF6W56FWtGgHxAnxG3zDs?via=matrix.org&via=monero.social&via=halogen.city
* https://matrix.to/#/!TlVgUtVNZychNpMzKW:matrix.org/$MPcp76U8VxNyipB-yZbJCkxYZSg5djiO3H_sk_RFIVo?via=matrix.org&via=monero.social&via=halogen.city
* https://matrix.to/#/!TlVgUtVNZychNpMzKW:matrix.org/$TEQ7ljAkFRcEBroywoBdC61c9OwXpJRfzOZiparpjRk?via=matrix.org&via=monero.social&via=halogen.city
* https://matrix.to/#/!TlVgUtVNZychNpMzKW:matrix.org/$yPohNc9lwQDADtFFQFgeDsUYrBL9SEsNcxgg4HPUT0w?via=matrix.org&via=monero.social&via=halogen.city

**Comment by selsta** [comment]
please open a meta issue https://github.com/monero-project/meta
