### ISSUE TITLE
Monero testnet doesn't sync to latest height

### ISSUE THREAD

**Issue by sharifzadesina** [monero-project/monero#8363]
Hello,

So this is what is happening:

```
2022-05-27 18:35:08.481 I Synced 1067618/1989519 (53%, 921901 left)
2022-05-27 18:35:08.744 I Synced 1067638/1989519 (53%, 921881 left)
```

But the current testnet height [at the time of writing this] is [1990185](https://community.rino.io/explorer/testnet/block/1990185).

I first thought my node database is corrupted so I removed blockchain files and it is syncing again.

The peers are also at height 1989519, I think this is the reason my node is syncing up to an old height.

Also I am using latest version 0.17.3.2.

**Comment by sharifzadesina** [comment]
I just removed whole blockchain again, still no luck, I don't know why all the peers it connects to are old.
I even tried different servers from different data centers.

**Comment by selsta** [comment]
You have to use master branch, we forked already to v0.18
