### ISSUE TITLE
Cache grows even for wallets without transactions

### ISSUE THREAD

**Issue by onionltd** [monero-project/monero#8366]
I made a new wallet in monero-wallet-gui. The size of a the cache file was initially around 400kB. Once the wallet was synced with the daemon, the cache has grown to around 5MB and continues to grow as time passes, though much slower. I've made no transaction to or from the wallet. Why is the cache growing so much?

**Comment by moneromooo-monero** [comment]
The wallet cache keeps a list of block hashes, to know when it needs to reorg. When you update to next version, it'll be able to cut off old block hashes and reduce the cache size a lot, which will then continue slowly growing again.

**Comment by Cactii1** [comment]
This issue should be closed.
