### ISSUE TITLE
ERROR: failed to find tx meta

### ISSUE THREAD

**Issue by garth-xmr** [monero-project/monero#8368]
Started to mine on testnet and received this error:

`2022-05-31 19:44:10.286     7f89727fc700        ERROR   txpool  src/cryptonote_core/tx_pool.cpp:1456      failed to find tx meta: <16b8c28802a93c67bdd3e31368b0b15426f2a577e0abd1c60b328e5bcb25fcf5> (will only print once)`

**Comment by garth-xmr** [comment]
pulled from current master

**Comment by selsta** [comment]
Duplicate #6687
