### ISSUE TITLE
Incorrect password

### ISSUE THREAD

**Issue by MadelineProtoFan** [monero-project/monero#8370]
I entered the wallet with password, recieved the money tried to send it - but password incorrect

**Comment by selsta** [comment]
Maybe you simply mistyped the wallet?

Can you still open the wallet? Do you have the seed?

**Comment by MadelineProtoFan** [comment]
i can enter the same _viewonly wallet with my password. But the normal one - invalid password
I dont have the seed
I am sure in this password 100%
Are there any variants how to open my wallet?

**Comment by selsta** [comment]
What is the file size of wallet_name.keys?
When was it last changed?

Do you have a backup? Which OS are you using?

**Comment by MadelineProtoFan** [comment]
Size: 2 kb
Last change : 21:06
Time now : 1:04

Windows 10. No backups :(

It is not the same problem?
https://www.reddit.com/r/monerosupport/comments/hxqv2m/monero_gui_and_ledger_invalid_password/

**Comment by selsta** [comment]
Do you use a Ledger?

**Comment by selsta** [comment]
Can you try to open the wallet with monero-wallet-cli?

The problem is files can get corrupted, so it's super important to write down the seed. That's the only way to guarantee access in all cases. Which isn't helpful right now.

**Comment by selsta** [comment]
Did you maybe use the change wallet password feature and forgot? Did you try an empty password?

**Comment by MadelineProtoFan** [comment]
Is it possible that i was hacked by some malware and somebody changed the key wallet password. And there is no record about it in the log file?

Can you say how to open the key file in monero-wallet-cli?

**Comment by selsta** [comment]
What did you do at 21:06?

**Comment by MadelineProtoFan** [comment]
Password incorrect :(

**Comment by selsta** [comment]
I did not see anything interesting in the logs. Did you force shutdown your computer?

**Comment by MadelineProtoFan** [comment]
No did not do this

**Comment by MadelineProtoFan** [comment]
Now i cannot enter _viewonly wallet! I can do it before

**Comment by selsta** [comment]
From the file size it does not seem corrupted. And there is no known issue of what you are describing. Do you have a second PC? Can you copy wallet on USB stick and try on a different PC?

Also are you typing the password manually or do you use a password manager?

This here was unrelated and fixed: https://www.reddit.com/r/monerosupport/comments/hxqv2m/monero_gui_and_ledger_invalid_password/

**Comment by MadelineProtoFan** [comment]
What a great support selsta! 5 stars!
So i installed GUI on the second laptop and put all passwords i know. And there was no password at all
The problem that on my first PC empty password - was incorrect password, I deleted GUI and restared my PC. And it works
Thanks you very much!!! Big pleasure that monero have such dev!

**Comment by selsta** [comment]
Make sure to write down the seed now. Otherwise if your hard drive has issues you lose your funds.

> The problem that on my first PC empty password - was incorrect password, I deleted GUI and restared my PC. And it works
Thanks you very much!!! Big pleasure that monero have such dev!

Still not really sure what happened here but glad it's resolved.
