### ISSUE TITLE
Redefinition of WALLET_RPC_VERSION_MINOR

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#8376]
The release-v0.17 branch defines `WALLET_RPC_VERSION_MINOR` twice, causing a warning.

https://github.com/monero-project/monero/blob/424e4de16b98506170db7b0d7d87a79ccf541744/src/wallet/wallet_rpc_server_commands_defs.h#L51

**Comment by selsta** [comment]
Sorry, my mistake: https://github.com/monero-project/monero/pull/8166
