### ISSUE TITLE
Missing payment ID for outgoing transfer after cache deleted

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#8378]
monero-wallet-rpc does not return payment ids for outgoing transfers after the cache is deleted.

Steps to reproduce:

1. transfer to integrated address
2. delete wallet cache
3. get transfer by hash id
4. observe that transfer does not have payment id

**Comment by Cactii1** [comment]
By design, this transfer information is only stored in the wallet cache, once deleted it is irrecoverable.

**Comment by Cactii1** [comment]
An encrypted version if it.

**Comment by woodser** [comment]
Ah, so it's intentional that the payment ID not be decryptable without the wallet cache and not the private key?

**Comment by Cactii1** [comment]
It's not stored as plain text on the blockchain. If the private key is known you can, however I don't think any wallet currently has the capability of restoring this information from the blockchain.

You might want to have a look at https://xmr.llcoins.net/addresstests.html

**Comment by woodser** [comment]
> If the private key is known you can, however I don't think any wallet currently has the capability of restoring this information from the blockchain.

Right, this issue requests restoring the payment id from private key when the cache is deleted.

**Comment by Cactii1** [comment]
So it's a feature request. Can we get this tagged as a feature request then?

**Comment by selsta** [comment]
```
13:23 <moneromooo> It can't, as it doesn't have the secret key for it.
```
