### ISSUE TITLE
Memory leak in monerod v0.17.3.2-release

### ISSUE THREAD

**Issue by daemonserj** [monero-project/monero#8389]
Hi.
I ran node a couple of days and monerod allocated all awailable RAM on server and swap kept growing.
On the first day it increased from zero to 512M, on the second day to 812M.

Top output:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
14100 monero    20   0  149.3g   9.6g   8.9g S  15.6  82.3 374:36.40 monerod
```

free -m output:
```
              всего        занято        свободно      общая  буф./врем.   доступно
Память:       11893        1713         136          40       10043        9816
Подкачка:        3856         812        3044

```

monerod status

```
2022-06-17 12:12:15.633 I Monero 'Oxygen Orion' (v0.17.3.2-release)
Height: 2647697/2647697 (100.0%) on mainnet, not mining, net hash 2.56 GH/s, v14, 16(out)+90(in) connections, uptime 2d 1h 31m 30s

```

[monerod.conf.zip](https://github.com/monero-project/monero/files/8927451/monerod.conf.zip)

**Comment by selsta** [comment]
How much RAM does your VPS have overall?

**Comment by daemonserj** [comment]
11gb with zswap enabled

**Comment by selsta** [comment]
And how much free RAM do you have available without monerod running?

**Comment by daemonserj** [comment]
Almost all of RAM is free because there is no other worlkloads on server.

**Comment by selsta** [comment]
Did you try mining?

**Comment by daemonserj** [comment]
No. Actually it's small nettop with low perf CPU, so mining is not suitable for me.

**Comment by hyc** [comment]
Doesn't look like any leak to me. 9.6G resident, 8.9G shared. Majority of usage is shared memory, not a leak.

**Comment by daemonserj** [comment]
What is your uptime and swap usage ?

**Comment by hyc** [comment]
If there's no other busy processes on the machine, it doesn't mean much. You can set /proc/sys/vm/swappiness = 0 if it bothers you but it won't have any impact.

**Comment by selsta** [comment]
Your config was in a zip so I didn't want to download it. 128 in peers is a lot, my nodes don't even reach 128 in peers with months of uptime.

**Comment by daemonserj** [comment]
I see incoming peers count floating around ~90 right now.
I don't want to restart service, I'll watch for overall RAM usage.
If it continues growing then I'll limit in-peers to 32 and try to find some leaks with memleax.

**Comment by hyc** [comment]
> I'll keep an eye on it but if trend continues it will cause the system to run out of memory.

No, it won't. The OS will reclaim cache memory as needed. There is no leak here, there is no problem here.

**Comment by daemonserj** [comment]
I've checked monerod by memlex with 1 minute memblock expiration.
There is no leaks right now, so you guys was right.
I'll return to it after some weeks, if some wrong happens I'll reopen this issue.
