### ISSUE TITLE
Monero transferred funds haven't arrived

### ISSUE THREAD

**Issue by davidbroomhead** [monero-project/monero#8399]
Hi there - I transferred funds from one GUI wallet to another, but the funds haven't arrived. The outgoing transaction from the first wallet is showing as there & present, but the incoming wallet is still showing as 'no transactions yet'. When I checked both the outgoing & incoming wallet IDs at wallet.mymonero.com, they are both showing as empty & 'no transactions yet'.

I rebuilt both wallets following the instructions in this post:

https://monero.stackexchange.com/questions/6649/transaction-stuck-as-pending-in-the-gui

But this did not fix the situation. 

The outgoing transaction is definitely showing the correct address, but that receiving address is showing as 'no transactions yet'.

Is there anything else I can try, or are the funds lost?

**Comment by davidbroomhead** [comment]
It was Monero GUI wallet

**Comment by selsta** [comment]
Please open an issue here: https://github.com/monero-project/monero-gui/issues

Also add the version you are using, add the transaction id from the missing transaction, and the wallet restore height (you can find it on Settings -> Info page).

**Comment by davidbroomhead** [comment]
Thanks - will do
