### ISSUE TITLE
Monerod shuts down at random times

### ISSUE THREAD

**Issue by ksdhans** [monero-project/monero#8402]
Monerod will periodically just quit. It happens every few hours or so, although it's rather unpredictable. 

Here's the final entries when I run it in a console window:
2022-06-23 06:44:18.667 W No incoming connections - check firewalls/routers allow port 18080
Assertion failed: Connection reset by peer [10054] (src/signaler.cpp:372)
Assertion failed: Connection reset by peer [10054] (src/signaler.cpp:372)

This is with Monero 'Oxygen Orion' (v0.17.3.2-release), on Windows 10.  The blockchain is fully synchronized.

NOTE: I've only managed to capture one failure so far, so I can't say if it's always the connection reset that triggers it.

**Comment by selsta** [comment]
Can you please post your config / which options you start monerod with?

**Comment by selsta** [comment]
ping

**Comment by moneromooo-monero** [comment]
From a web search, it looks like libzmq asserting on us.

**Comment by John4266** [comment]
I just had this problem as well

![](https://i.imgur.com/YTzISD3.png)
![](https://i.imgur.com/AMfwyJ1.png)

My arguments were: `.\monerod.exe --out-peers=50 --prep-blocks-threads=8 --block-sync-size=60 --data-dir G:\bitmonero --check-updates disabled --non-interactive --max-concurrency 12`

**Comment by selsta** [comment]
Closing as the issue does not appear to be on monero's side.
