### ISSUE TITLE
Unspendable dust outputs (> 0.00000582 XMR~)

### ISSUE THREAD

**Issue by hinto-janaiyo** [monero-project/monero#8405]
I've naturally accumulated a few dust outputs/change that are worth less than current fees (currently around 0.00000582 XMR), and due to the mandatory fees, they've essentially become unspendable.

I assumed if I had a single output that could cover fees like:
```
10 outputs worth 0.000005 XMR
1 output worth 1 XMR
```
`sweep_all` would pay for fees using the 1 XMR output, however it just skips over the dust outputs and sweeps the single 1 XMR output. I'm under the impression network consensus rejects transactions without any fees, so modifying wallet software is a no-go.

I'm aware that sweeping these outputs would actually lose me money (probably why sweeps don't include dust), but having a bunch of unspendable outputs does feel weird. For now, is this the only solution https://github.com/monero-project/monero/issues/1525#issuecomment-270388425?

**Comment by plowsof** [comment]
I'm a bit confused myself because:
```
sweep_unmixable - only relevant for very old wallets (<= 2016); send all unmixable outputs to yourself with ring_size 10
```
but `sweep_dust` appears in the monero rpc wallet hm

**Comment by moneromooo-monero** [comment]
Outputs that do not pay for themselves increased fee are ignored. You can turn this off with "set ignore-fractional-outputs 0".
Consensus allows 0 fee txes, though nobody will mine them for you, you'd have to mine it yourself.

**Comment by hinto-janaiyo** [comment]
> set ignore-fractional-outputs 0

I didn't think to look at the set commands. It works perfect, thanks.
