### ISSUE TITLE
funds lost!!!

### ISSUE THREAD

**Issue by dance88** [monero-project/monero#8440]
I transferred funds from one web wallet[xmrwallet.Com] to another,

but the funds haven't arrived,

But the XMR in my wallet has been deducted,

<img width="693" alt="1" src="https://user-images.githubusercontent.com/109477764/179416719-d77b0e6c-3e71-45d4-a65b-2ca03c640fc0.PNG">

When I checked the transaction id[00a888c91b0f6cceb8e2a7d2fc1a93dd00253d53d6226c74604399b0d51cf0a1] at xmrchain, 

<img width="1714" alt="2" src="https://user-images.githubusercontent.com/109477764/179416731-d0b0b94d-fcc2-48ee-bd55-8ebf6531a8a8.PNG">

After entering the wallet address and private viewkey in the Decode outputs option, the returned result is as follows,

<img width="1533" alt="3" src="https://user-images.githubusercontent.com/109477764/179416737-1a5da0ad-c130-4205-8d02-b7a4e2a68b1b.PNG">

I tried using Multiple remote node to restore the height before the transaction, but it didn't work,

address: 88.198.199.23
port: 18081

address: node.supportxmr.com
port: 18081

address: 78.47.80.55
port: 18081

address: node.community.rino.io
port: 18081

#### Please Help Me.

**Comment by selsta** [comment]
Your screenshot shows a different transaction id, starting with 00a88, or what is that?

Are you the one who made the transaction on that exact date?

**Comment by dance88** [comment]
> Your screenshot and your text shows a different transaction id, starting with 00a88, or what is that?
> 
> Are you the one who made the transaction on that exact date?

Sorry, the transaction id in the text is wrong, I have changed it, the correct transaction id is: 00a888c91b0f6cceb8e2a7d2fc1a93dd00253d53d6226c74604399b0d51cf0a1

**Comment by SChernykh** [comment]
xmrwallet[dot]com is a known scam: https://www.reddit.com/r/Monero/comments/jh15e3/psa_xmrwalletcom_is_a_scam_who_steals_your_funds/
You've got scammed.

**Comment by dance88** [comment]
> xmrwallet[dot]com is a known scam: https://www.reddit.com/r/Monero/comments/jh15e3/psa_xmrwalletcom_is_a_scam_who_steals_your_funds/ You've got scammed.

I've used this web wallet many times, and it worked until now,

and I checked other successful transactions,

After entering the wallet address and private viewkey in the Decode outputs option, The results of Decode outputs look different


<img width="1586" alt="5" src="https://user-images.githubusercontent.com/109477764/179470845-08a01db3-0cc0-4448-8549-a75538c4a782.PNG">

**Comment by SChernykh** [comment]
Which means you actually sent your XMR to a different address. Maybe you have clipboard hijack malware on your PC.

**Comment by dance88** [comment]
> Which means you actually sent your XMR to a different address. Maybe you have clipboard hijack malware on your PC.

I can be sure that my pc is not infected with a hijack malware

**Comment by SChernykh** [comment]
But your screenshot in the first post shows that XMR were sent to some other address. If viewkey doesn't decode any output, it went somewhere else.

**Comment by dance88** [comment]
> You didn't answer my question. Did you send those funds at the timestamp yourself? Or did you log into your wallet and there was an outgoing transaction?
> 
> Also on IRC you said you didn't send these funds to yourself so how do you have the view key?

I recharge funds to my own Binance account via xmrwallet,

view key from xmrwallet[.]com----account----View Key (Private).
<img width="744" alt="6" src="https://user-images.githubusercontent.com/109477764/179513778-276f349b-9be4-4841-8a9f-69d1dbcf0573.PNG">

**Comment by nmateo** [comment]
As stated above, multiple people have already reported lost funds using xmrwallet[dot]com, you should another wallet, like official GUI or cake.

**Comment by SChernykh** [comment]
> I recharge funds to my own Binance account via xmrwallet,

So you sent fund from xmrwallet to Binance? Then you can't use the viewkey from xmrwallet to check Binance's wallet, it doesn't work this way.

**Comment by selsta** [comment]
Yes, the receiver view key is required.

**Comment by SChernykh** [comment]
Hmm, there's also "Your Seed" on that screenshot - you can use it to restore your wallet in the official CLI or GUI wallet.

**Comment by dance88** [comment]
> Yes, the receiver view key is required, not the sender.

I don't quite understand,Shouldn't I enter my address and key in the Decode option?

**Comment by dance88** [comment]
> Hmm, there's also "Your Seed" on that screenshot - you can use it to restore your wallet in the official CLI or GUI wallet.

I restored the mnemonic in the gui wallet,
got the same result.

**Comment by dance88** [comment]
> No. The receiver has to enter their address and their view key.

How can I check if my transfer was successful? I have no way to get the Binance view key, there is only one xmr recharge 
 address.

**Comment by SamsungGalaxyPlayer** [comment]
This is an issue tracker, not a help desk for third party wallets. Please try asking for help in https://reddit.com/r/MoneroSupport
