### ISSUE TITLE
Unable to build from source - /usr/bin/ld: (.text+0xc1): undefined reference to `event_base_set'

### ISSUE THREAD

**Issue by rblaine95** [monero-project/monero#8449]
I'm unable to build `v0.18.0.0` in my [Docker Build](https://github.com/rblaine95/docker_monero) and I'm unsure how to troubleshoot.

Build logs are available [here](https://github.com/rblaine95/docker_monero/runs/7445673300?check_suite_focus=true#step:5:4629).

Any help would be greatly appreciated.

**Comment by selsta** [comment]
See https://github.com/monero-project/monero/issues/8439

You can install `apt install libevent-dev`, and maybe some of the other libs listed in this issue and then check if it builds correctly.

Also ping @sethforprivacy since you also had similar issues with docker.

**Comment by sethforprivacy** [comment]
> I'm unable to build `v0.18.0.0` in my [Docker Build](https://github.com/rblaine95/docker_monero) and I'm unsure how to troubleshoot.
> 
> Build logs are available [here](https://github.com/rblaine95/docker_monero/runs/7445673300?check_suite_focus=true#step:5:4629).
> 
> Any help would be greatly appreciated.

There was a change that now requires `libunbound-dev` to be installed at compile time. You may also need to install it in your final image, as I wasn't able to get it to properly statically link anymore.

**Comment by selsta** [comment]
@sethforprivacy this is how you would have to compile unbound to get proper static binaries: https://github.com/monero-project/monero-gui/pull/3696/files

**Comment by sethforprivacy** [comment]
> @sethforprivacy this is how you would have to compile unbound to get proper static binaries: https://github.com/monero-project/monero-gui/pull/3696/files

Ah, that's not bad at all! Will explore that shortly. Thanks!

**Comment by sethforprivacy** [comment]
Working on it now: https://github.com/sethforprivacy/simple-monerod-docker/pull/61

**Comment by rblaine95** [comment]
Build seems to be working now, thank you @selsta and @sethforprivacy 🎉
