### ISSUE TITLE
Monero GUI v0.18.0.0 Problem Lendger Nano X

### ISSUE THREAD

**Issue by smurfman13** [monero-project/monero#8461]
Monero GUI v0.18.0.0 Problem Ledger Nano X, Ledger  Monero App updated to latest version 1.7.8,  an error appears:” Unable to open wallet Try to update the Monero Ledger App, at least 1.6.0. required.”
Mac OS 12.5 , Windows 10 Monero gui v0.18.0.0

**Comment by selsta** [comment]
Please continue to use v0.17.3.2 until Ledger puts out an update, this is out of our control.

Ledger Monero app `v1.8.0` will work together with Monero app `v0.18.1.0`, both will be released in time before the HF.

**Comment by smurfman13** [comment]
v0.17.3.2 after August 13 will work?

**Comment by selsta** [comment]
No, but there will be an update for both Monero and Ledger in time before August 13th.

**Comment by smurfman13** [comment]
Thank you

**Comment by bloodspork** [comment]
running ledger monero 1.7.8, monero-gui-v0.18.0.0 on debian 

Can I (safely) run monero-gui-v0.17.3.2 as a workaround for now?

**Comment by selsta** [comment]
> Can I (safely) run monero-gui-v0.17.3.2 as a workaround for now?

Yes.

**Comment by bloodspork** [comment]
thank you
