### ISSUE TITLE
RockPr64 - Armbian build error

### ISSUE THREAD

**Issue by dawiepoolman** [monero-project/monero#8468]
![image](https://user-images.githubusercontent.com/2351212/181220162-dbe993be-3c4f-4c02-894b-89b07959bd37.png)

specs:
![image](https://user-images.githubusercontent.com/2351212/181220304-5a0443bf-2d82-4147-ae45-d1162ee9a8bc.png)

where could I have missed something?

**Comment by dawiepoolman** [comment]
![image](https://user-images.githubusercontent.com/2351212/181221075-8e8cda82-1f51-4115-a59d-bb530b410833.png)

**Comment by dawiepoolman** [comment]
seems like a rebuild went though.
I will test stability and revert..

**Comment by dawiepoolman** [comment]
nope, 
folder build/release/bin is missing:
![image](https://user-images.githubusercontent.com/2351212/181235299-bd34b97f-a677-4cb8-a645-fae86d51a73f.png)

**Comment by hyc** [comment]
Go into the Linux directory. The default build paths have the OS added to them now.

Most likely you ran out of memory during the first build; if you had used a larger swap it probably would have succeeded. No bug here.

**Comment by dawiepoolman** [comment]
confirmed:
![image](https://user-images.githubusercontent.com/2351212/181245094-ee4275bb-4129-408c-bcd9-d4fd5ceb3da6.png)

Thanks @hyc !
