### ISSUE TITLE
Weird behaviour after updating to version 0.18

### ISSUE THREAD

**Issue by erib3** [monero-project/monero#8472]
So I installed the new release. I copied over my testnet wallets, when I ran monerod on testnet, it did this thing where it 'popped off blocks' then supposedly synced. Ok. Running the monero-wallet-rpc on testnet is fine but the money is pretty much all gone. Is that normal? Will the money come back?

Also when I try to revert to version 0.17, I get a DB error. --db-salvage does not help this, so I can only use the new release now.

**Comment by selsta** [comment]
Testnet forked on May 16th. If you continued to use v0.17 after that date then you were on the wrong chain and all money you received on that wrong chain is gone.

> Also when I try to revert to version 0.17, I get a DB error. --db-salvage does not help this, so I can only use the new release now.

You can't use the old version anymore after a network upgrade.

If you are trying to test your monero integration in your app / website / ... then I would recommend to use stagenet instead.

**Comment by erib3** [comment]
thank you for the response
