### ISSUE TITLE
Monero 18.0.0 vs. Ledger Nano X

### ISSUE THREAD

**Issue by fabiobfava** [monero-project/monero#8481]
Hey there, if I update to MoneroCLI and/or MoneroGUI v18.0.0 they cannot connect to my Ledger Nano X device. The error message says I should have the Monero App on Ledger v1.6.x and I have v1.7.8 (latest) but they still cannot connect to my Ledger. Will I be safe after Aug 13 network upgrade? Is there something I can do to make it work? I've tried uninstalling XMR from my Ledger and reinstalling it, without success. Thanks for any help or support here, cheers1

**Comment by selsta** [comment]
Please continue to use v0.17.3.2 for now. Ledger support will be added in v0.18.1.0 + Ledger app v1.8.0. The release will be in time before the hardfork.
