### ISSUE TITLE
set-daemon command not referenced in initialization message

### ISSUE THREAD

**Issue by dscotese** [monero-project/monero#8514]
"This is the command line monero wallet. It needs to connect to a monero daemon to work correctly."
This is a frustrating error because it doesn't provide any advice.  It should be revised to:
"This is the command line monero wallet. Use set-daemon to connect to a monero
daemon to work correctly."

**Comment by moneromooo-monero** [comment]
It is not an error. It always prints that. For most people, they will not have to use set_daemon, the wallet will use the local daemon.

There is a reference to set_daemon on the actual error message.
