### ISSUE TITLE
bitmonerod.exe crashes on fat32 file system after about block 250,000

### ISSUE THREAD

**Issue by pointbiz** [monero-project/monero#852]
Using --data-dir option to store the blockchain on an external hard drive with FAT32 formatting.

I'm not suggesting it should work on FAT32 but it crashes without any indication in the logs for why the crash occurred. Therefore, user does not know how to rectify the problem. I solved this by formatting the external hard drive in NTFS format.

Is there a way to detect the disk format and shut down bitmonerod.exe with appropriate log message?

Crash happens after around block 250,000. Using Windows.
v 0.9.4

**Comment by livinginformation** [comment]
I looked for a cross-platform way to detect the file system type, and can't find one in boost, or other places. We can write a separate section of code for Linux and Windows.

For Windows, we can use [GetVolumeInformation()](https://msdn.microsoft.com/en-us/library/aa364993(VS.85).aspx) from the Win32 API

For Linux, according to [StackOverflow](http://stackoverflow.com/questions/25639180/in-linux-in-c-c-how-to-determine-filesystem-type-of-a-mounted-or-unmounted-par), we can use the blkid libraries in libblkid-dev. 

This should be a quick fix, but it requires adding a dependency to the project for Linux systems. I can write the Linux part of this, but unfortunately, don't have access to a Windows dev machine, so someone else will have to add the Windows part and make sure it compiles.

**Comment by luigi1111** [comment]
Probably a file size limitation. I'm not sure this will be common enough to justify spending much time on.

**Comment by moneromooo-monero** [comment]
monerod should not error out instead of crashing. It certainly worked when I ran on a filled up partition (failure to commit, but no crash).

**Comment by hyc** [comment]
FAT32 has a max filesize of 4GB so you can't use that for storing the blockchain.

**Comment by moneromooo-monero** [comment]
I saw a report of someone else trying to use FAT32, and it doesn't crash anymore, it errors out with I/O errors.

+resolved
