### ISSUE TITLE
timestamp strangeness in archive on Linux auto update

### ISSUE THREAD

**Issue by BeholdersEye** [monero-project/monero#8522]
tar xvf monero-gui-linux-x64-v0.18.1.0.tar.bz2
monero-gui-v0.18.1.0/
monero-gui-v0.18.1.0/LICENSE
tar: monero-gui-v0.18.1.0/LICENSE: implausibly old time stamp -9223372036854775808
monero-gui-v0.18.1.0/extras/
monero-gui-v0.18.1.0/extras/monero-blockchain-ancestry
tar: monero-gui-v0.18.1.0/extras/monero-blockchain-ancestry: implausibly old time stamp -9223372036854775808
monero-gui-v0.18.1.0/extras/monero-blockchain-depth
tar: monero-gui-v0.18.1.0/extras/monero-blockchain-depth: implausibly old time stamp -9223372036854775808

Crashes the archive manager under Ubuntu.

**Comment by selsta** [comment]
Try to use `tar --warning=no-timestamp`

**Comment by BeholdersEye** [comment]
Overriding the warning is addressing the symptom and not the cause.

I will wait until an archive with no screwy timestamps is released, I think. Hopefully this is not the standard for Monero going forward.

**Comment by selsta** [comment]
All the binaries are reproducible. You can build your own GUI binaries with docker or wait for the next release where this issue is resolved. Or you can manually fix the timestamp.

We are not going to fix this for the existing release as this would mean the archive gets a new hash which might confuse people.

Closing this as the timestamp issue is fixed internally in the packaging script and this is the wrong repo.

**Comment by BeholdersEye** [comment]
This was just to notify you of the problem. Take as much time to address it as you need.

"Just build it yourself" seems like a less than ideal response to a problem with the auto updater, and the same goes for "just do a manual install". I already intended on waiting for the next version. I expect many Monero users are not going to be comfortable suppressing error messages no matter how benign.

**Comment by selsta** [comment]
Which auto updater are you talking about? The one inside the GUI doesn't extract any files and I have not seen any warnings with Ubuntu when extracting this archive.

Are you extracting the file from the command line or from your desktop environment? What is your exact Ubuntu version?

**Comment by BeholdersEye** [comment]
The problem is not with the auto-updater itself, the problem is that the archive:

"monero-gui-linux-x64-v0.18.1.0.tar.bz2"

Causes Ubuntu's Archive Manager to crash when attempting to open the file. The tar command was just to show the problem.

I expect most auto-update users will attempt to open the archive with the GUI manager, fail, and get no further than that.

I am using version 3.28.0, Archive Manager, the default archive manager for Gnome. It has no difficulty opening the tar.bz2 files associated with previous Monero releases, so I believe the fault to lie in the timestamps. However, If you believe the problem is with Archive Manager and not the archive's formatting, you might report the error here:

https://gitlab.gnome.org/GNOME/file-roller/-/issues

I don't consider further details of my operating environment to be relevant, since other users, who are using a different version of Ubuntu, also experience the problem:

https://old.reddit.com/r/Monero/comments/wmtrs8/cli_gui_v01810_fluorine_fermi_ledger_monero_app/ik6y1kv/

**Comment by selsta** [comment]
I see the issue now. Right click -> `Extract here` works without issues. That's what I do usually and also have done while testing this release. Only double clicking causes the crash in Archive Manager.

**Comment by BeholdersEye** [comment]
It is a bad look to delay the auto-updater while Trezor gets its act together but tell Linux users they have to wait until next release if they want the auto-updater to deliver an archive they can double-click. I will wait, don't get me wrong- but it's a bad look.

**Comment by stefan-reich** [comment]
I am using tar xvfj and also got the timestamp warning. Extracted fine anyway though.

**Comment by BeholdersEye** [comment]
> We are not going to fix this for the existing release as this would mean the archive gets a new hash which might confuse people.

In my opinion fixing the archive is less confusing than expecting Ubuntu users to know not to double click it.

I hope everyone reading this appreciates how the tone changed from "What's your Ubuntu version?" (implying I'm not able to discern whether my config is at fault) to "fixing this might confuse people" once I provided a link with other people experiencing the same problem.

**Comment by selsta** [comment]
As I already explained we can't fix it without putting out a new release. We never change the archive hash of an existing release.

We are already preparing v0.18.1.1 which will have correct timestamps: https://github.com/monero-project/monero/pull/8534

**Comment by BeholdersEye** [comment]
In that case all I can say is that I am champing at the bits. :)

**Comment by selsta** [comment]
https://www.getmonero.org/2022/09/19/monero-GUI-0.18.1.1-released.html is now released. Auto updater will be activated in 1-2 days assuming no major issues get reported.

**Comment by selsta** [comment]
v0.18.1.2 has been released and the auto updater should work now.
