### ISSUE TITLE
Could blockchain sync use more than 2 cores?

### ISSUE THREAD

**Issue by stefan-reich** [monero-project/monero#8533]
I'm using monero-wallet-gui and a local node to sync the blockchain.

When doing so, it appears monerod is using between one and two cores.

Could this be increased? Or is there a  fundamental problem?

Thanks in advance for any answers

**Comment by selsta** [comment]
Which OS are you using? Did you set a custom blockchain location?

**Comment by stefan-reich** [comment]
> Which OS are you using? Did you set a custom blockchain location?

Sorry for editing the question while you already answered. I took out the reference of the GUI core use because it went to 0% just after I typed this.

Regarding your question, I am using Linux and yes it is a custom blockchain location.

**Comment by selsta** [comment]
Is the blockchain stored on a HDD or SSD?

**Comment by stefan-reich** [comment]
> Is the blockchain stored on a HDD or SSD?

SSD in a VeryCrypt volume

**Comment by selsta** [comment]
VeraCrypt volume will likely significantly slow down sync.

**Comment by stefan-reich** [comment]
> VeraCrypt volume will likely significantly slow down sync.

OK I see. So monerod is generally able to use all available cores?

**Comment by selsta** [comment]
Yes, it can use more than 2 cores.

**Comment by stefan-reich** [comment]
> Yes, it can use more than 2 cores.

Ah, that answers my question. Thanks a lot. I'll try to move the blockchain out of the encrypted volume.

**Comment by selsta** [comment]
Initially sync also uses checkpoints to skip known PoW hashes during block verification, the last couple percentage won't use checkpoints so system CPU usage should significantly increase.

**Comment by stefan-reich** [comment]
Just quick feedback: I moved the blockchain to a non-encrypted drive and CPU use went up a tiny bit, I saw 2.5 cores used max (out of 8).

**Comment by selsta** [comment]
Which height are you? After the latest checkpoint (~2661600) CPU usage should go up.
