### ISSUE TITLE
Wallet cli does not connect to daemon, although curl works 

### ISSUE THREAD

**Issue by aghamir** [monero-project/monero#8536]
## Version info
Monero cli/Monerod version: v0.18.1.0
## Issue description
I've run monerod under a domain(behind nginx) with https schema.
When I run this curl:
```
curl https://monero.example.com/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: application/json'
```
However, when I run `wallet-monero-cli` like this:
```
monero-wallet-cli --generate-new-wallet wallet_1 --mnemonic-language english --use-english-language-names --daemon-address  https://monero.example.com/ --subaddress-lookahead 5:1000 --max-concurrency 8
```
It cannot connect to the daemon and returns:
```
Error: wallet failed to connect to daemon: https://monero.example.com. Daemon either is not started or wrong port was passed. Please make sure daemon is running or change the daemon address using the 'set_daemon' command.
```

**Comment by selsta** [comment]
Try `--daemon-address monero.example.com` instead, or `--daemon-address monero.example.com:18081` if that's the RPC port.

**Comment by aghamir** [comment]
@selsta 
Thanks a lot. It fixed with `--daemon-address monero.example.com:443`.
