### ISSUE TITLE
V0.17.2.0 fails to synch daemon

### ISSUE THREAD

**Issue by synthcube** [monero-project/monero#8542]
Been running this for over a year with no trouble, but this last time opened and not synching. GIU screen says 'Daemon is synchronized(2701062) but the 'Waiting for daemon to synch' progress bar shows zero and not moving. Log says: "2022-08-30 17:35:12.607	17144	ERROR	cn	src/cryptonote_basic/cryptonote_format_utils.cpp:231	Failed to parse transaction from blob" and I do not know what step(s) to take next. Thank you in advance.

**Comment by selsta** [comment]
Monero had a network upgrade, you have to use v0.18.1.0
