### ISSUE TITLE
Problems at shutdown: Transport endpoint is not connected 

### ISSUE THREAD

**Issue by DeeDeeRanged** [monero-project/monero#8549]
Running Debian testing (bookworm)
When I call monerod --lpg-level 2 status I get the following as the last line:

Problems at shutdown: Transport endpoint is not connected

Don't know what it actually is referring to and I would like to find out.

**Comment by selsta** [comment]
Do you have any issues or do you just want to know what it means?

**Comment by selsta** [comment]
From what I can tell the message means that it tries to shutdown a network socket that is already disconnected.

**Comment by DeeDeeRanged** [comment]
Was just curious and the log lines before, there no lines after, that don't say anything either. Have tries all the log-levels if I could see anything specific that would trigger a bell with me.
In my time I have been digging through scripts and logfiles besides scripting when I was still working, just a retired IT soecialist now and still learning things lol.

**Comment by selsta** [comment]
Do you have any issues or do you just want to know what it means? Also can you post a larger log with a couple lines before (and after)?

**Comment by DeeDeeRanged** [comment]
Have nothing to add anymore than what I stated before and it is not important enough and it doesn't stop monerod running as intended. So I close this issue as of now.
