### ISSUE TITLE
bitmonerod crashes on ARM (pine64)

### ISSUE THREAD

**Issue by antanst** [monero-project/monero#858]
uname -a

> `Linux pine 3.10.101-4-pine64-longsleep #51 SMP PREEMPT Thu May 26 18:20:37 CEST 2016 aarch64 aarch64 aarch64 GNU/Linux
> `

At commit `a837c9cb0feeb7c8c4e616df64cbf650e38355f7`

Bitmonerod crashes with message:

> `bitmonerod: /usr/include/boost/thread/pthread/recursive_mutex.hpp:104: boost::recursive_mutex::~recursive_mutex(): Assertion '!pthread_mutex_destroy(&m)' failed.`

**Comment by radfish** [comment]
Does `--max-concurrency 1` make a difference?

**Comment by antanst** [comment]
Can't try it anymore...unfortunately my Pine64 gave up the ghost (talk about reliability). I'm waiting for a new one at the moment.

**Comment by NanoAkron** [comment]
Hi @antanst is this issue still present or can it be closed?

**Comment by luigi1111** [comment]
@antanst Did you ever a get a new one?

**Comment by moneromooo-monero** [comment]
Was it on exit only by any chance ?
