### ISSUE TITLE
monerod syncs 100% at incorrect block height

### ISSUE THREAD

**Issue by duckology** [monero-project/monero#8589]
OS: Void Linux
Monerod Version: Monero 'Oxygen Orion' (v0.17.2.3-unknown) directly from the Void Repository

Attempted:
- moving lmdb folder and trying to resync from scratch
- moving lmdb folder + deleting p2pstate.bin
- rebooting
- turning off VPN
- popping off the last 100000 blocks

It says 100% synced at block height 2688964 whereas localmonero.co says it's around 2717582

**Comment by selsta** [comment]
You are using a majorly outdated version, monero had a network upgrade. You need to use client v.18.0.0 or newer.
