### ISSUE TITLE
Error with shared libraries

### ISSUE THREAD

**Issue by ChervonaKomanda** [monero-project/monero#8608]
Fresh install of Debian 11

> Downloaded the linux tar.bz2 from Monero website
` tar xf monero-gui-linux-x64-v0.18.1.2.tar.bz2`
` ./monero-wallet-gui`
` ./monero-wallet-gui: error while loading shared libraries: libxcb-icccm.so.4: cannot open shared object file: No such file or directory`

**Comment by selsta** [comment]
Try to install

```
libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xkb1 libxcb-shape0 libxkbcommon-x11-0
```

These should come preinstalled unless you installed an OS without any graphical user interface.

**Comment by yacinecheikh** [comment]
I was able to reproduce the error with a Ubuntu 22 LTS minimal install, after extracting the .tar.bz2:
./monero-wallet-gui./monero-wallet-gui: error while loading shared libraries: libxcb-icccm.so.4: cannot open shared object file: No such file or directory

Installing the libraries fixed it. The missing libraries were:
libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxkbcommon-x11-0
