### ISSUE TITLE
monero-wallet-rpc does not handle json_rpc parameters properly

### ISSUE THREAD

**Issue by llacqie** [monero-project/monero#8612]
Passing an object in the array as a parameter when calling the "set_daemon" json_rpc method leads to the error "Invalid ssl support mode", which obviously should not happen. Maybe this happens with other methods, I haven't checked.

![image](https://user-images.githubusercontent.com/46074473/195573097-4ce713a5-b3ae-4f25-b4f8-0c121d90d8f3.png)
![image](https://user-images.githubusercontent.com/46074473/195573141-56ac1149-6f03-4dd6-b665-197121c8afaf.png)

**Comment by plowsof** [comment]
why are we passing empty lists/arrays?

**Comment by llacqie** [comment]
> when passing an array inside a list you get an error: but not when passing a empty params list . im wondering what your issue is about?

My issue is primarily about the fact that the error message is not true, but it would be ideal if [{}] were handled as {}, which is possible and should not entail any problems.

**Comment by plowsof** [comment]
Don't pass it a [list] with an [{empty array}] for absolutely no reason at all. Give me a use case where you need this? 

Perhaps if you created a function that 1/10 times will handle your rpc call incorrectly and pass a [{}] on purpose (because reasons) and you need to detect when that happens?

**Comment by llacqie** [comment]
> 

In my case, due to the specific implementation of the json_rpc client that I used (I can't call it incorrect, it's just not obvious how to use it correctly), while testing this method, I came across this error and spent a lot of time to understand what the reason is. If the error message was correct, it would greatly speed up the work. Also, since monero-wallet-cli does not handle this error, in this case it stopped at another check, but this check might not have happened and then it might have led to more serious consequences.

**Comment by llacqie** [comment]
> Don't pass it a [list] with an [{empty array}] for absolutely no reason at all. Give me a use case where you need this?
> 
> Perhaps if you created a function that 1/10 times will handle your rpc call incorrectly and pass a [{}] on purpose (because reasons) and you need to detect when that happens?

In my case, due to the specific implementation of the json_rpc client that I used (I can't call it incorrect, it's just not obvious how to use it correctly), while testing this method, I came across this error and spent a lot of time to understand what the reason is. If the error message was correct, it would greatly speed up the work. Also, since monero-wallet-cli does not handle this error, in this case it stopped at another check, but this check might not have happened and then it might have led to more serious consequences.

**Comment by plowsof** [comment]
RTFM , it even has examples. If an example is broken/missing please report it on monero-site 
- https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#set_daemon
- https://github.com/monero-project/monero/blob/v0.18.1.0/src/wallet/wallet_rpc_server_commands_defs.h#L2660

**Comment by selsta** [comment]
> Also, since monero-wallet-cli does not check the correctness of the parameters format

Do you mean monero-wallet-rpc?

**Comment by llacqie** [comment]
> RTFM , it even has examples. If an example is broken/missing please report it on monero-site
> 
>     * https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#set_daemon
> 
>     * https://github.com/monero-project/monero/blob/v0.18.1.0/src/wallet/wallet_rpc_server_commands_defs.h#L2660

The problem is not that something doesn't work for me.
The problem is that when passing parameters in the wrong form, monero-wallet-rpc does not write about it in the error message, but writes about something else unrelated to the real error.

**Comment by llacqie** [comment]
> > Also, since monero-wallet-cli does not check the correctness of the parameters format
> 
> Do you mean monero-wallet-rpc?

Yes, sorry.

**Comment by llacqie** [comment]
> > RTFM , it even has examples. If an example is broken/missing please report it on monero-site
> > ```
> > * https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#set_daemon
> > 
> > * https://github.com/monero-project/monero/blob/v0.18.1.0/src/wallet/wallet_rpc_server_commands_defs.h#L2660
> > ```
> 
> The problem is not that something doesn't work for me. The problem is that when passing parameters in the wrong form, monero-wallet-rpc does not write about it in the error message, but writes about something else unrelated to the real error.

I said that I used the json_rpc client implementation. I gave this as an example, when you cannot immediately see that the request is incorrect, and the error message does not indicate that something might be wrong with the way you send the parameters.

**Comment by moneromooo-monero** [comment]
I just looked and technically, it's correct :D The first thing it looks for in the parameters is the ssl mode, and it cannot find a valid one.
A check for an object in the json code would be a nice improvement.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/8692
