### ISSUE TITLE
creating a view only wallet on 18.1.2 always returns an error

### ISSUE THREAD

**Issue by anycolo** [monero-project/monero#8614]
E offset >= num_outputs. THROW EXCEPTION: error::wallet_internal_error
	E Error creating view only wallet: Offset is larger than total outputs

**Comment by j-berman** [comment]
I see one way to trigger this error -- does the wallet that you're trying to create a view only wallet have 0 txs (is it a totally new wallet)?

**Comment by j-berman** [comment]
Here are the errors I'm seeing in the GUI. When creating a view-only wallet from:

- A wallet with 0 transfers triggers: `Offset is larger than total outputs`
- A wallet with >1 transfer(s) triggers: `Imported outputs omit more outputs that we know of. Try using export_outputs all.`

I see the causes of the above two errors. Will PR fixes shortly but want to confirm this is what you're seeing as well.

**Comment by anycolo** [comment]
Yes!!!

**Comment by anycolo** [comment]
I've been having other issues as well:
https://github.com/monero-project/monero/issues/8613
Even if it returns an error, the gui still creates a wallet, which seems usable. I have used that wallet. Was it safe to use, or will i lose funds?

**Comment by j-berman** [comment]
I don't see how you could lose funds. The issue of the view-only wallet displaying too high of a balance in #8613 seems entirely to do with not importing key images into the view-only wallet as mentioned in the comments there.
