### ISSUE TITLE
monero-wallet-cli: do not use UTC time, or at least be clear thats what's being used

### ISSUE THREAD

**Issue by imfiesh** [monero-project/monero#8669]
Both ```show_transfer``` and ```show_transfers``` displays the transaction timestamp using UTC time. This is different from the norm for UNIX based (or at least Linux based) software which normally use the localtime call which respects the TZ environment variable. If there is a good reason for using UTC, it should at least be clearly labeled as such, for example by adding the string "UTC" at the end. As it is now it can be confusing and potentially misleading in some situations, especially if you are in a timezone that is very close to UTC. If you are waiting for a incoming transaction and aren't careful you could potentially mistake a new transaction for an old one or vice versa. It gets extra confusing when combined with #8667

**Comment by moneromooo-monero** [comment]
For privacy reasons, time functions use GMT. It'd make sense to explicitely use local time on wallet info though.

**Comment by moneromooo-monero** [comment]
It's unclear whether things like block timestamp in monerod should also use local time. It would be consistent, but the daemon logs by default, and GMT was used so that log sharing does not leak timezones. For now, I'll just add a "Z" suffix.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/8694
