### ISSUE TITLE
Compilation takes a very long time on raspberry pi zero w

### ISSUE THREAD

**Issue by MuzuWeb** [monero-project/monero#8674]
Hello, i am compiling the monero CLI wallet for my raspberry pi zero w because there is no releases for armv6 and it takes a
very long time (it's been like 13 hours).
In the README file, it says to wait 4 to 6 hours, it is normal ?
Thanks in advance for answers.

**Comment by afungible** [comment]
try only `-j `option to compile fastest (you won't be able to do anything else on PI)

OR
use make `-j`N

The -j flag specifies how many threads you want to allot for compiling. where `N` is the max number of threads you wish to allocate. The rule of thumb is to make `N = the number of cores your CPU has`. So if you are on a dual core machine, you may use -j2, whereas on an quad-core machine, use -j4 

I use make -j4, for example.

EDIT: RaspberryZero I see may be single core. If its a single core, -j4 may be optimized to -j1 but you can try.

**Comment by selsta** [comment]
You need about 2.5GB RAM per make job. The Raspberry is single core and has 512MB RAM. -j2 wouldn't even work on it.

Closing as it's simply weak hardware.
