### ISSUE TITLE
monerod: High CPU usage after 2-3 days

### ISSUE THREAD

**Issue by BotoX** [monero-project/monero#8685]
I've been running a monero node "Monero 'Fluorine Fermi' (v0.18.1.2-release)" on Archlinux for a few months now.
Every few days I have to restart monerod, as it will constantly use around 160-180% CPU.
Regular CPU usage is around 2-10%

I think that this hasn't been an issue from the start, but is now constantly plaguing me.
I can still connect and use the daemon as a remote wallet when this happens.

Here's my config:
```
# Configuration for monerod
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-igd' are specified as 'no-igd=1'.
# See 'monerod --help' for all available options.

# Data directory (blockchain db and indices)
data-dir=/var/lib/monero

# Log file
log-file=/var/log/monero/monerod.log
log-level=0
max-log-file-size=0            # Prevent monerod from managing the log files; we want logrotate to take care of that

# P2P full node
p2p-bind-ip=0.0.0.0            # Bind to all interfaces (the default)
p2p-bind-port=18080            # Bind to default port

# RPC open node
rpc-bind-ip=0.0.0.0            # Bind to all interfaces
rpc-bind-port=18081            # Bind on default port
confirm-external-bind=1        # Open node (confirm)
restricted-rpc=1               # Prevent unsafe RPC calls
rpc-ssl=enabled
rpc-ssl-certificate=/etc/ssl/private/monerod.pem
rpc-ssl-private-key=/etc/ssl/private/monerod.key
rpc-login=****
no-igd=1                       # Disable UPnP port mapping
no-zmq=1                       # Disable ZMQ RPC server to decrease attack surface (it's not used)


# Emergency checkpoints set by MoneroPulse operators will be enforced to workaround potential consensus bugs
# Check https://monerodocs.org/infrastructure/monero-pulse/ for explanation and trade-offs
enforce-dns-checkpointing=1
enable-dns-blocklist=1

out-peers=16              # This will enable much faster sync and tx awareness; the default 8 is suboptimal nowadays
in-peers=64               # The default is unlimited; we prefer to put a cap on this

limit-rate-up=30000     # 1048576 kB/s == 1GB/s; a raise from default 2048 kB/s; contribute more to p2p network
limit-rate-down=100000   # 1048576 kB/s == 1GB/s; a raise from default 8192 kB/s; allow for faster initial sync
```

I've attached the monerod log file here, from start to finish:
[monerod.log.txt](https://github.com/monero-project/monero/files/10280925/monerod.log.txt)
Though I suppose I should've raised the log-level to 1 before reporting this, in any case I have now so just need to wait another two to three days.

CPU usage started rising around 2022-12-21 11:32:00
![image](https://user-images.githubusercontent.com/395711/208996920-5d1d66a4-4016-4755-98c8-f92f1ed368d0.png)

I've also made a core dump before restarting the monero daemon:
https://cloud.botox.bz/s/HrgRyR8d9Nk3gxb

Edit: I should've run perf to find out where exactly monerod was wasting cpu cycles, ooops. will do soon.

**Comment by selsta** [comment]
`perf` output and `--log-level 2` would be interesting.

**Comment by vtnerd** [comment]
You can also look up poorman's profiler which can be run at anytime after launch using special `gdb` commands. This is probably TCP server related, but its easier with at least some stack trace to begin the investigation.

**Comment by jkhsjdhjs** [comment]
Downstream bug report: https://bugs.archlinux.org/task/76735 (It also contains links to perf top outputs)

I've been trying to debug this issue for a while already. Also asked on the IRC channel, no luck.
Since it doesn't occur with the binary from the monero website, I'm currently trying various build configurations with older dependencies since I thought that maybe a recent version of a library is buggy (Arch's packages are usually far more up to date than most distributions).
Last thing I tried was building with boost 1.74 (Arch currently has 1.80), but the same issue appeared.

But maybe you have an idea of what's wrong by looking at the perf output.

**Comment by BotoX** [comment]
The issue happened again within a few days, however I was sick so I've just attached gdb and let it sleep until I was feeling good enough to come back to it.

A `perf record -F 99 -p <pid> -g -- sleep 120` fed into FlameGraph identifies the epoll loop as a cluprit.
![monerod](https://user-images.githubusercontent.com/395711/209672898-802cb3ea-d5b9-4394-a8ef-4e912d059703.svg)

Sadly I have not recompiled monero with symbols, so information is missing on monerod function names...

Here's a screenshots from perf report:
![image](https://user-images.githubusercontent.com/395711/209673135-e0487f98-c01f-46f4-8954-bcd58860d4e6.png)

I have now built the monero arch pkg with '!strip' and CMAKE_BUILD_TYPE=debug and started it with `valgrind --tool=callgrind --instr-atstart=no` (and then use callgrind_control -i on when the CPU usage rises again).
~~So in 2-3 days I should hopefully have a nice callgrind file that can be loaded into KCachegrind, etc. and analyzed.~~
(Btw. I had to recompile valgrind and raise the virtual memory limit to 512GB, lmdb wasn't able to open the blockchain)
Nevermind, monerod won't sync a single block while running under valgrind...
But at least I have symbols now for perf

**Comment by BotoX** [comment]
New perf report:
![image](https://user-images.githubusercontent.com/395711/210012021-c7405766-3176-415b-9133-c2e920afc02c.png)

and FlameGraph:
![monerod](https://user-images.githubusercontent.com/395711/210012050-466d94bd-071a-407a-8e50-0030dc95492d.svg)

any other wishes? froze the process with gdb.

**Comment by moneromooo-monero** [comment]
At a guess, start_shutdown and on_interrupt might be called ping pong fast. You can check by adding something like:

> MGINFO(__FUNC__);

at the start of both, and see whether you can a spam of those when the CPU spike happens.

If it does, then something in the logic of that code is likely buggy. If not, the issue is probably elsewhere.

**Comment by BotoX** [comment]
recompiled with:
```diff
diff --git a/contrib/epee/include/net/abstract_tcp_server2.inl b/contrib/epee/include/net/abstract_tcp_server2.inl
index 81aa725d1..90d2e59f7 100644
--- a/contrib/epee/include/net/abstract_tcp_server2.inl
+++ b/contrib/epee/include/net/abstract_tcp_server2.inl
@@ -559,6 +559,7 @@ namespace net_utils
   template<typename T>
   void connection<T>::start_shutdown()
   {
+    MGINFO(__func__);
     if (m_state.socket.wait_shutdown)
       return;
     auto self = connection<T>::shared_from_this();
@@ -661,6 +662,7 @@ namespace net_utils
   template<typename T>
   void connection<T>::on_interrupted()
   {
+    MGINFO(__func__);
     assert(m_state.status == status_t::INTERRUPTED);
     if (m_state.timers.general.wait_expire)
       return;
```

**Comment by BotoX** [comment]
Update: @moneromooo-monero was right.

My log file is 66 GB big and getting spammed with this crap:

```
2023-01-12 19:01:35.442 [RPC1]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:562 start_shutdown
2023-01-12 19:01:35.442 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.442 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.442 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.442 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.442 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:562 start_shutdown
2023-01-12 19:01:35.442 [RPC1]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.442 [RPC1]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:562 start_shutdown
2023-01-12 19:01:35.443 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.443 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:562 start_shutdown
2023-01-12 19:01:35.443 [RPC1]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.443 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.443 [RPC1]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.443 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:665 on_interrupted
2023-01-12 19:01:35.443 [RPC0]  INFO    global  contrib/epee/include/net/abstract_tcp_server2.inl:562 start_shutdown
```

https://asciinema.org/a/Rtso2l9aZceB8lBFDzn81qJF3

I've froze the monero process again if you want me to poke around with gdb or post a core dump.

**Comment by moneromooo-monero** [comment]
An all thread stack trace would be nice in this state:

thread apply all bt full

**Comment by moneromooo-monero** [comment]
Actually, better even:

break epee::Connection TAB , etc, etc, till you complete to on_interrupted
Same with start_shutdown

Now cont till it breaks in either. Then "thread apply all bt full".
Then cont till it breaks in the other one. Then "thread apply all bt full".

That way we see where the calls from those some from. Possibly from a boost async scheduled call, but you never know.

**Comment by BotoX** [comment]
> An all thread stack trace would be nice in this state:
> 
> thread apply all bt full

[thread apply all bt full.txt](https://github.com/monero-project/monero/files/10406051/thread.apply.all.bt.full.txt)



> Actually, better even:
> 
> "break epee::net_utils::connection" TAB TAB , etc, etc, till you complete to on_interrupted Same with start_shutdown

There is:

epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::on_interrupted()
epee::net_utils::connection<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::on_interrupted()

and

epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::start_shutdown()
epee::net_utils::connection<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::start_shutdown()

Starting with the HTTP ones:
```
(gdb) break epee::net_utils::connection<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::on_interrupted()
Breakpoint 3 at 0x55df84b67650: epee::net_utils::connection<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::on_interrupted(). (2 locations)
(gdb) break epee::net_utils::connection<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::start_shutdown()
Breakpoint 4 at 0x55df84b672e0: epee::net_utils::connection<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::start_shutdown(). (2 locations)```

doing continue and holding down enter blocks on every log line:
[1.txt](https://github.com/monero-project/monero/files/10406111/1.txt)


Next one:
```
(gdb) break epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::on_interrupted()
Breakpoint 11 at 0x55df84b729e0: epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::on_interrupted(). (2 locations)
(gdb) break epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::start_shutdown()
Breakpoint 12 at 0x55df84b72580: epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::start_shutdown(). (2 locations)
```

[2.txt](https://github.com/monero-project/monero/files/10406119/2.txt)
barely anything and then just keeps on running for a minute (and spamming the log) until I ^C it.
so it's the HTTP one it seems


And now a few "continue" + "bt full" with the http breakpoints:
[3.txt](https://github.com/monero-project/monero/files/10406137/3.txt)


Here's a on_shutdown "thread apply all bt full":
[4.txt](https://github.com/monero-project/monero/files/10406153/4.txt)

Finally a on_interrupted "thread apply all bt full":
[5.txt](https://github.com/monero-project/monero/files/10406172/5.txt)

Also uploading the monerod binary + build directory (for libraries, is this because I did a debug build?) + core dump:
Will edit and insert link when done, it's 2GB gzipped.

**Comment by moneromooo-monero** [comment]
This might work, though I do not know the semantics of this code, so even if it works it's not certain to be a good fix.
It basically prevents calling shutdown while a shutdown is in progress. I don't think the author of this code is around anymore to give an opinion on the patch (or make a better fix) though.

```
diff --git a/contrib/epee/include/net/abstract_tcp_server2.inl b/contrib/epee/include/net/abstract_tcp_server2.inl
index 81aa725d1..333a1144e 100644
--- a/contrib/epee/include/net/abstract_tcp_server2.inl
+++ b/contrib/epee/include/net/abstract_tcp_server2.inl
@@ -565,7 +565,7 @@ namespace net_utils
     m_state.socket.wait_shutdown = true;
     auto on_shutdown = [this, self](const ec_t &ec){
       std::lock_guard<std::mutex> guard(m_state.lock);
-      m_state.socket.wait_shutdown = false;
+      epee::misc_utils::auto_scope_leave_caller scope_exit_handler = epee::misc_utils::create_scope_leave_handler([&](){ m_state.socket.wait_shutdown = false; });
       if (m_state.socket.cancel_shutdown) {
         m_state.socket.cancel_shutdown = false;
         switch (m_state.status)
```

**Comment by j-berman** [comment]
Taking a stab at this... from what I recall in discussions with the author, their intent behind the connection's interrupted status was to allow the server to reuse a connection that hasn't been terminated yet. But the author didn't actually implement the code to reuse an interrupted connection (I don't see a way for a connection's status to go from `INTERRUPTED` to anything but `TERMINATING` or `WASTED`). I believe they intended to implement the ability to reuse a connection *in a future PR* building off this interrupted status.

In this `on_interrupted` -> `start_shutdown` infinite ping pong (good spot @moneromooo-monero), it looks like the server just keeps attempting to re-shut the SSL stream down, while leaving the connection in an interrupted state. I'm thinking until someone actually writes the code to reuse an "interrupted" connection, it makes sense to simply complete the connection termination sequence *after* the server shuts the SSL stream down. This way the server isn't leaving a connection around in this interrupted state that can't be "un-interrupted."

This would be my proposed patch:

```
diff --git a/contrib/epee/include/net/abstract_tcp_server2.inl b/contrib/epee/include/net/abstract_tcp_server2.inl
index 81aa725d1..fb935a9cb 100644
--- a/contrib/epee/include/net/abstract_tcp_server2.inl
+++ b/contrib/epee/include/net/abstract_tcp_server2.inl
@@ -586,8 +586,7 @@ namespace net_utils
       else if (ec.value())
         terminate();
       else {
-        cancel_timer();
-        on_interrupted();
+        terminate();
       }
     };
     m_strand.post(
```

This is a blunt stab of a solution on my end. After some attempts, I still haven't figured out how to repro this bug on my machine, but I think this makes a bit more sense as a patch since it doesn't leave the connection in an interrupted state forever (with the timer canceled forever too).

**Comment by BotoX** [comment]
Seems like the proposed fix from @moneromooo-monero didn't work, cpu load at 200% now after a few days :D
![image](https://user-images.githubusercontent.com/395711/213784712-cfd09fd2-c5bb-4cc2-aa32-4660daa8cd7c.png)

I've just compiled and deployed the patch proposed by @j-berman

**Comment by BotoX** [comment]
It's been a week and my CPU is not on fire. 👍
![image](https://user-images.githubusercontent.com/395711/215154780-51d8f146-dd8a-4bcf-86ce-2b88513e3c86.png)

**Comment by jkhsjdhjs** [comment]
Works for me as well!
![cpu usage graph](https://screens.totally.rip/2023/02/63db9f1bbddca.png)

But since this was an issue with the handling of interrupted connections, I do wonder why it was only present in the binaries compiled by distributions or by myself, but not in the official binaries published on https://www.getmonero.org.

**Comment by hajes** [comment]
been there, disable public RPC node. it uses extra 10Wh and hogs CPU

**Comment by g00g1** [comment]
I don't observe high cpu usage anymore after applying the suggested patch, can confirm that after monitoring for almost a week.

![image](https://user-images.githubusercontent.com/91201021/233834614-5b1ecfe8-caae-4269-8f35-20129fba3d9a.png)
