### ISSUE TITLE
Adopt NO_COLOR environment variable

### ISSUE THREAD

**Issue by oscar-heitmann** [monero-project/monero#8688]
If the NO_COLOR environment variable is set, disable color output.

https://no-color.org/

I believe this informal standard holds value and I would enjoy seeing an implementation in the monero utilities, such as monerod and monero-wallet-cli. Appreciate all your work.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/8693

**Comment by jeffro256** [comment]
@selsta Can we mark this as completed?
