### ISSUE TITLE
monerod: unrecognised option 'non-interactive'

### ISSUE THREAD

**Issue by v-byte-cpu** [monero-project/monero#8753]
Hi there! When I try to add `non-interactive=1` option to the monerod.conf file and start with `--config-file monerod.conf`, monerod crashes with the following error:
```
Exception in main! unrecognised option 'non-interactive'
```

However, when I run monerod with the `--non-interactive` command line flag directly, it starts successfully.

**Comment by almalh** [comment]
Will look into it, can you paste your .conf file here?

**Comment by almalh** [comment]
Just had a look at the code and it is by design; only a subset of all possible options are allowed in the .conf file. In particular all daemon config options (incl. non-interactive) should be kept in the command line. Someone else may chime in, but I don't think this should be changed.

**Comment by almalh** [comment]
That being said, I could add something to better handle the error and make it clear that option belongs to the command line

**Comment by v-byte-cpu** [comment]
Ok, the only question is why it was designed that way. I mean, what are the benefits of this restriction? 
Probably it was designed to override values at startup without changing config, but in this case then it is better to make the cli flags have a higher priority than the flags in the configuration file

**Comment by v-byte-cpu** [comment]
This is great news, thanks!
