### ISSUE TITLE
Monero wallet RPC error

### ISSUE THREAD

**Issue by spyder0000** [monero-project/monero#8761]
2023-03-04 12:33:56.856 E Blocks start before blockchain offset: 0 2720000
2023-03-04 12:34:05.043 E !m_blockchain.is_in_bounds(current_index). THROW EXCEPTION: error::out_of_hashchain_bounds_error
2023-03-04 12:35:54.256 E (m_blockchain.size() == stop_height || (m_blockchain.size() == 1 && stop_height == 0) ? false : true). THROW EXCEPTION: error::wallet_internal_error

**Comment by selsta** [comment]
Are you using testnet, stagenet or mainnet? Was your node fully synced before you created / opened this wallet? Did you try a full wallet rescan?

**Comment by spyder0000** [comment]
I am using mainnet. Node was not fully synchronised. I created the wallet and started monero-wallet-rpc when it was 45% synced. 

> Are you using testnet, stagenet or mainnet? Was your node fully synced before you created / opened this wallet? Did you try a full wallet rescan?

**Comment by selsta** [comment]
How did you create this wallet? If your node isn't synced then you can ignore this message.

**Comment by spyder0000** [comment]
Wallets can be created through monero-wallet-cli repositories.

**Comment by spyder0000** [comment]
> How did you create this wallet? If your node isn't synced then you can ignore this message.

I created it using monero-wallet-cli repositories, it did not ask for full synchronisation. After wallet creation, I started monero-wallet-rpc but getting the error, which I previously mentioned.

**Comment by selsta** [comment]
The error means that your wallet height is significantly higher than your daemon height. Sync your daemon and then it will go away.
