### ISSUE TITLE
Issue with connecting to multiple local nodes after v18.2.0

### ISSUE THREAD

**Issue by suggalla** [monero-project/monero#8768]
Seeing the following error when configuring multiple local nodes to connect: `CONNECTION FROM 127.0.0.1 REFUSED, too many connections from the same address`. I also have the following flag configured: `--allow-local-ip`. This worked prior to this version.

**Comment by selsta** [comment]
Which version did you use previously?
Did you set `--max-connections-per-ip` ?

**Comment by suggalla** [comment]
Let me try setting that. Previously I used `v0.18.1.2`

**Comment by selsta** [comment]
I can't think of any change between v0.18.1.2 and v0.18.2.0 that would cause this.

I'd need detailed steps to reproduce this myself if the max-connections flag doesn't help.

**Comment by suggalla** [comment]
That seems to have resolved it. Thanks!
