### ISSUE TITLE
other items

### ISSUE THREAD

**Issue by rookie-kjq** [monero-project/monero#8773]
Is it true that a token has the same code base as Monroe?
![Uploading Screenshot_2023-03-11-10-27-32-79_df198e732186825c8df26e3c5a10d7cd.jpg…]()

**Comment by selsta** [comment]
Tokens on other blockchains don't have the same code base as monero.

**Comment by rookie-kjq** [comment]
https://github.com/Judecoin/judecoin-core

**Comment by selsta** [comment]
It appears that they have forked the monero codebase at some point. Please ask them for specific information about their coin.

**Comment by rookie-kjq** [comment]
> 他们似乎在某个时候分叉了门罗币代码库。请向他们询问有关其硬币的具体信息。

Thank you for your reply
