### ISSUE TITLE
Resync Required If Processed Killed Due to OOM?

### ISSUE THREAD

**Issue by devatgo** [monero-project/monero#8782]
Was syncing a node on a VPS the other day (we're running a few tests on one of our wimpy VPS's before migrating to one of our beefy dedi servers) and when I checked the sync progress I noticed that the monero daemon shutdown and output the message "Killed" (no other error messages indicating a corrupt db was ever displayed in output upon resuming syncing), I'm guessing this probably occurred due to OOM and the fact that I forgot to setup a swap file on the server. I've since created a swap file on the server and have resumed syncing. Is it safe to continue syncing (safe in regards to assuming no data corruption)? Or should I resync? I'm hoping I won't have to resync because this is on a VPS with a spinning disk and it took a few days to get to 94% lol.

**Comment by selsta** [comment]
Yes, it means OOM. You can safely continue syncing.
