### ISSUE TITLE
Feature request: Transaction that require the signature of both the sender and recipient.

### ISSUE THREAD

**Issue by destenson** [monero-project/monero#881]
EDIT: Please see [this comment](https://github.com/monero-project/monero/issues/881#issuecomment-351917989) for a clearer explanation of the requested feature I've called "multi-sig transactions", for lack of a better term.

I would like to propose that Monero add the concept of multi-signature transactions (in addition to multisig wallets). A multi-signature transaction would be a transaction that requires the valid signature of all parties involved before it is actually committed to the blockchain as a valid transaction. A requester or recipient could be any valid address, not just multi-signature wallets. The transaction can be initiated by either the payer or the payee.

Requests for payment can be initiated by party A with a valid signature (or all required signatures if initiated by a multisig wallet) & when party B also signs the request, the actual transfer of funds from B to A will occur like a normal transaction. This will add invoicing as an intrinsic feature to Monero.

Outgoing payments to a third-party can also be multisig. In that case, the request is for acceptance of payment, and the transfer is completed when the recipient signs the transaction. Since the transfer is not valid until all parties sign, this allows the funds for the transaction not to be committed until the recipient accepts the payment. If funds are not available when the transaction is adequately signed, it will be rejected by the blockchain due to insufficient funds. A signatory can also rescind their signature before the transaction is accepted by all parties. This allows a fund transfer to be cancelled before payment is accepted. This is a feature that is missing from all major cryptocurrencies.

**Comment by fluffypony** [comment]
MRL work currently being done here: https://shnoe.wordpress.com/2016/03/22/ring-multisignature/

**Comment by ChristopherKing42** [comment]
Its already possible: http://monero.stackexchange.com/q/782/255

**Comment by luigi1111** [comment]
This is known. No one has wanted to take up implementation with RingCT coming "soon" and making it incompatible.

Getting the communication to be non-clunky will be a work of art in itself I think.

**Comment by Riiume** [comment]
Dear developers, I have posted a $480 bounty for completion of this issue: https://www.bountysource.com/issues/35498752-feature-request-multi-sig-transactions

Best of luck!

**Comment by lessless** [comment]
This is an **OUTSTANDING** feature! It will allow to create recurring payments: business can initiate transfers at the beginning of the each billing cycle and customer just sign them off in the wallet. 

What a brilliant idea!

**Comment by Tails** [comment]
The communications across the web are a bit ambiguous. Is multi-sig already possible now or not? Is it being worked on? When is it expected?

**Comment by destenson** [comment]
@Tails, I'm sure the devs will have more to say, but it certainly appears to have been worked on recently. From the links you posted, it looks like many features are already implemented, but it's probably not considered complete yet.

However, @lessless's comment shows he understands that this particular issue that I posted originally is not about standard "multi-sig" as you normally think of when you think of multi-sig wallets, etc. This particular issue is about possibly generating a temporary ring between sender and receiver that would allow individual transactions to be completed when the recipient signs the transaction.

@luigi1111 or @fluffypony, or anyone who knows, does a recipient's address contain enough information to generate a 2-party ring-signed transaction that would allow/require both sender and receiver to sign before the transaction is complete? If private keys for both parties are necessary to create the ring-signature, that would prohibit the use-case(s) I was thinking of when creating this issue. But if the address contains a public key, and if only public keys are necessary to create the ring signature(s), then it definitely seems like it would be a viable way to implement this feature.

**Comment by moneromooo-monero** [comment]
That stack exchange link essentially says "yes, it's possible, if you write the code". It does not say "yes, and the code is written". #2134 is the code for doing so, and is close to being fixed up to work with subaddresses.

**Comment by moneromooo-monero** [comment]
I'm not sure I understand your question destenson, but:

- a recipient's address contains both the public spend key and public view key.
- to create a ring signature, you need a private spend key for one of the ring members (and multisig does that in reconstructing the results of using that private key).

So I think you will have to rephrase your question with specific details.

**Comment by destenson** [comment]
@moneromooo-monero, thank you. That does answer my question. Thank you. It would mean that this implementation of "multisig" as you refer to it, does not provide the features required to fullfill this issue, #881.

**Comment by moneromooo-monero** [comment]
Then I suggest you explain it clearly, as the first post is very vague, due to being explained in flowing English. For instance, "Requests for payment can be initiated by party A with a valid signature" needs the following information: what is a request (from the point of view of the network), what is the initiation step, what information does the signature sign (if it is just "the request" then the request needs to be well defined), and it would be helpful to have an basic overview of whether monero is meant to flow from A to B, or B to A, or both.

**Comment by destenson** [comment]
@moneromooo-monero, thank you. You are absolutely right. I agree and apologize. It was difficult to explain initially and I did not explain it very effectively. Let me try this again...

The idea is to have a sender (_Sam_) send payment to a recipient (_Rita_) in such a way that either _Sam_ or _Rita_ can cancel the payment (for little-to-no cost) and both must approve the payment before the transaction is considered valid for inclusion in the blockchain (i.e. mineable).

I jumped ahead to a possible (_non- Monero-specific_) implementation with the [current suggestion of "multi-sig transactions"](#881). By this I mean, a type of transaction created by either _Sam_ or _Rita_ that describes a payment made from _Sam's address_ to _Rita's_, but can only be considered complete and valid only after _both_ Sam _and_ Rita agree to it by signing the transaction with their respective credentials.

This type of transaction would be similar to a traditional multi-sig account, but rather than requiring signatures of a certain number of pre-authorized accounts for the transaction to be complete and valid, it would instead require the signatures of the both the sender and the recipient.

In the following examples, _Sam_ may represent a single individual address or a regular multi-sig wallet account/address. In the case of a multi-sig wallet, all necessary signing requirements for making transactions would remain intact. If _2-of-3 signatures_ is required to make payments from that address, then all _2-of-3 signatures_ would be required to be a valid signature as _Sam_ to initiate or approve an outgoing payment. When _Rita_ is a multi-sig address, it might make sense to allow a single one of the authorized signers to acknowledge receipt instead of requiring all (e.g. _2-of-3 signatures_) to sign.

This type of transaction,  a "_multi-sig transaction_" as I called it, could be created by either party:
1. _Sam_ makes a payment to _Rita_ by:
    * creating a transaction with payment details for _Rita_ and signing it.
    * then the incomplete, _half-signed_ transaction is provided to _Rita's client_ (specifically or broadcast to the network if clients are unreachable).
    * by offering a half-signed transaction for her to sign, this effectively requests _Rita's_ acknowledgment and approval of the payment's details.
    * therefore, a _fully-signed_ transaction (signed by both _Sam_ and _Rita_) effectively provides both:
      * authorization (by _Sam_) to make the intended payment from his address, and
      * acknowledgement (by _Rita_) that approval was granted to receive the payment by her address.
    * When _Rita_, or her automated client, notices the _half-signed_ transaction waiting for her to approve, acknowledge, sign and complete, she can:
      * sign the transaction and broadcast it to the network to be mined, completing the transaction and effectively providing _Sam_ the additional acknowledgement of payment acceptance as requested.
      * or cancel it, by:
        * requesting that the network remove the incomplete transaction from its list of incomplete, _half-signed_ transactions
        * this effectively provides _Sam_ with the acknowledgement requested of _Rita_ as well as acknowledgement that _Rita_ disapproved of the payment details from _Sam's_ transaction.
2. or, _Rita_ creates an invoice requesting payment from _Sam_ by:
    * creating a transaction with payment details for _Sam_ and signing it.
    * then the incomplete, _half-signed_ transaction is provided to _Sam's client_ individually or broadcast to the network if clients are unreachable.
    * by offering him a half-signed transaction for him to sign, this effectively requests _Sam's_ acknowledgment and approval of the payment's details to send funds from _Sam's address_ to _Rita's_.
    * When _Sam_, or his automated bill-payment software ;-), notices the _half-signed_ transaction awaiting his signature, he can:
      * sign the transaction and broadcast it to the network for mining, completing the transaction and providing _Rita_ with the acknowledgement, approval and transmission of payment she effectively requested.
      * or cancel it, by:
        * requesting that the network remove the incomplete transaction from its list of incomplete, _half-signed_ transactions,
        * this effectively provides acknowledgement of receipt of the payment's details and disapproval of the payment's details.

Some benefits of having a type of "multi-sig transaction" like this available:
- Mistakes and accidents can be corrected before they cause the loss of funds.
- Sam can change his mind and cancel the transaction to prevent it from being mined, at any time before _Rita_ signs it.
- _Rita_ can send a partially signed transaction effectively as an invoice. Sam would only need to sign the transaction (and have it be mined) to complete the requested payment.

Some problems with having a transaction type like this:
- The network could become saturated with incomplete, _half-signed_, non-mineable transactions. Possible solutions include:
  - directly send _half-signed_ transactions to the other party instead of broadcasting them, using, e.g.:
    - a specially formatted link including all the information needed to recreate the partially-signed transaction,
    - a direct messaging system that sends the _half-signed_ transaction as a message,
    - or by a _half-signed_ transaction _file_ that could be attached to an email and opened by compliant clients.
- Network fees may change between the first and last signatures. Probably trivial to solve.
- Transactions specifying UTXO as inputs may be difficult to reliably initiate by Rita, unless those inputs could be specified in a way that the transaction need not be re-signed when inputs change.
  - This could prevent this type of transaction from working well on blockchains that depend upon UTXO like Bitcoin and Monero.
  - It might be more of an edge case that is really only a problem for addresses that send payments frequently, but I still think it's an issue to be solved before this idea is viable.
- To cancel a transaction, a party may need to sign a proof of cancellation. I could see this getting problematic unless the cancellation proof can replace the existing half-signed transaction instead of leaving the transaction multiple times on the network in variously signed states.
- There are probably many other things I haven't thought of as well.

Hopefully you and others will find this explanation more digestible. Thanks for your suggestion.

**Comment by moneromooo-monero** [comment]
That was a lot more understandable, thanks.
First thing that comes to mind is that you'll be either spamming the chain with "cancel" notes, or allowing the cancelling pary to later replay a previously cancelled tx. Using the txpool like this is an attempt to bypass mining, and thus is not decided by consensus.

That said, the idea behind it is possible, by having both parties spend one of their inputs in that tx. Then cancellation becomes merely "not signing the tx". It seems similar to vespco's idea about dominant assurance contracts.

**Comment by destenson** [comment]
I did consider the additional load on the txpool might be excessive. With ethereum or bitcoin, I know a transaction can be created and signed with an offline wallet, then submitted to the network by a different client. Does Monero also provide that capability?  If so, a half-signed transaction could be given to the other party "by hand" with a file, network message, or by any other method that preventing the transaction from entering the txpool until after it's been fully signed. And then, as you suggested, a cancelled transaction would simply be one that is never signed. 

Also, is it true that Monero doesn't offer any method of communication between individual clients or addresses (besides submitting transactions to the txpool)? If so, and if this feature is added to Monero, you should consider adding a messaging feature as well. It might even be good to add messaging regardless, since it would permit additional use-cases that may have never been considered before.

**Comment by lessless** [comment]
@moneromooo-monero as far as I understood from reading https://www.reddit.com/r/Monero/comments/6htvg3/monero_is_perfect_for_dominant_assurance/
DAC  will require a seller to attach extra funds to initiate a payment.
The first application of proposed feature, in my mind, is empowering  SaaS business model. So far it's not possible to use any other crypto in the SaaS model unless there is a 3rd party like Coinbase that will sign off periodical payments on the customer behalf. 

Using DAC in such condition doesn't seem reasonable (and it will be almost impossible to justify to any management) - business potentially can lose money with any of its customers when it wants to bill them. Quite opposite outcome.
One way around that is to increase a fee when accepting Monero and hedge the risk by including those funds in the monthly payments. That will make the same service cost in fiat less, then it will cost in Monero. 

Off-chain sharing sounds like a nice option here. Maybe LN will help somehow?

**Comment by dEBRUYNE-1** [comment]
+proposal

**Comment by destenson** [comment]
I don't know how easily it can be implemented in Monero, but the Simple Schnorr Multisignatures recently described by [Blockstream](https://blockstream.com/2018/01/23/musig-key-aggregation-schnorr-signatures.html) in [this paper](https://eprint.iacr.org/2018/068.pdf), sound like exactly the kind of algorithm that would enable this proposal.

**Comment by moneromooo-monero** [comment]
Above, cancelling a transaction is just not signing it. No active step. Not like a revocation you check, just the absence of an action. Therefore, the party can sign/relay it later, if wanted. The case I had in mind is:

Alice and Bob have a 2/2 multiisig wallet.
Alice creates a new tx, and passes it to Bob for signing
Bob does not sign it (Bob could claim he never received it too)
Stuff happens
Bob actually signs/relays it days later, surprising Alice

Here, "Stuff happens" could be "Alice makes another tx, and Bob signs it normally". If that tx doesn't invalidate the earlier one (through double spending), then Alice/Bob spent twice.

**Comment by destenson** [comment]
I understand that is how it works now.

The suggestion would require allowing cancelling or revoking a transaction as an action.

As this topic is going nowhere. I'm ok if it's closed.
