### ISSUE TITLE
looking for setup openmonero.

### ISSUE THREAD

**Issue by b4sh1t1** [monero-project/monero#8816]
Hello,

I'm looking for setup https://github.com/moneroexamples/openmonero who can setup please write me in mail:

08.fascia-strides@icloud.com

or if someone can offer a web wallet using monero we can work with on private server ?

**Comment by selsta** [comment]
Please open an issue on the openmonero issue tracker, or I'd recommend asking on Reddit or IRC / Matrix. This here isn't the right place.
