### ISSUE TITLE
I can't download monero's mdb_recover tool

### ISSUE THREAD

**Issue by hugohugo130** [monero-project/monero#8820]
I can't download monero's mdb_recover tool from the official website, both github and monero official website show 404 errors

I'm use windows system
my blockchain file(data.mdb) is broken
I don't want to fix this by resyncing the blockchain
then I asked the artificial intelligence, and the 3 download links he provided were all invalid. Finally, the artificial intelligence told me that I could ask questions on Github.
Hope I provided enough information.
(Translated by Google, I am from Hong Kong)

**Comment by selsta** [comment]
There's no monero tool named mdb_recover.

You can try to start monerod.exe with `--db-salvage` and if that doesn't solve the corruption issues you have to resync from scratch.
