### ISSUE TITLE
I can't mine with the Monero client

### ISSUE THREAD

**Issue by hugohugo130** [monero-project/monero#8822]
I can't mine with the Monero client
Neither "p2pool" nor another option ("alone") option works
p2pool is stuck
Another option ("Solo") cannot start mining
(Translated by Google. there may be deviations, another option of p2pool should be Solo)

**Comment by selsta** [comment]
Please go to Settings -> Info and post what is says under

- Version
- Wallet mode

Also what computer hardware and operating system do you have?

**Comment by hugohugo130** [comment]
Oh, I forgot to mention, I use Windows system, the version is 0.18.2.2, it was release before, but now it becomes "unknown".
CPU: 12th Gen Inter(R) Core(TM) i7-1255U
RAM: 8GBx2 DDR4 SODIMM speed 3200MHz
DISK: 490GB SSD(system) + 2TB HDD
GPU: Intel(R) Iris(R) Xe Graphics
Internet: Ethernet

**Comment by selsta** [comment]
You can't mine before you are synced up to 100%.

**Comment by selsta** [comment]
I'll close this for now, if you continue to have issues after your node is fully synced up please comment and I can reopen it.

**Comment by hugohugo130** [comment]
I know, but the bootstrap node shows me 100% synced when in fact it's only 50% synced

**Comment by hugohugo130** [comment]
I know, so I removed

**Comment by hugohugo130** [comment]
I'm now trying to wait for him to sync to 100%. Hope the problem doesn't recur.

**Comment by hugohugo130** [comment]
Because I want to be faster and have more space, I put it on SSD before sync progress 45%, and put it on HDD after sync progress 45%

**Comment by selsta** [comment]
It is slow after 45% because you put it on HDD.

**Comment by selsta** [comment]
If you want fast sync then put it in your SSD. HDD is slow for sync.

**Comment by hugohugo130** [comment]
Sync was slow after 45%, so I put it on HDD
I put it on the SSD, and there will be no space after about 45% of the progress
Now I have 4 options
1: Free up SSD space to put down the entire monero blockchain
2: Buy an SSD
3: Maybe it is possible to resize the blockchain to be synced?
4: Continue to put the entire monero blockchain on HDD

**Comment by selsta** [comment]
Did you make sure to prune the blockchain? It will reduce the size to about 60GB.

**Comment by hugohugo130** [comment]
Yes, because I want to sync only to mine on the monero client, not on other mining software (Xmrig). I have not traded XMR

**Comment by hugohugo130** [comment]
But how to prune the blockchain?

**Comment by nahuhh** [comment]
1. 'settings > node 
2. startup flag `--prune-blockchain`
3. stop node
4. start node 

you only need to do step 2 once

**Comment by hugohugo130** [comment]
thx

**Comment by plowsof** [comment]
@hugohugo130 about 500 people receive an email every time we comment here. If you want real time feedback better join IRC

**Comment by hugohugo130** [comment]
I'm using Hexchat, which channel can I ask on?
