### ISSUE TITLE
Issue with monero-cli-wallet and daemon

### ISSUE THREAD

**Issue by Dinamitrii** [monero-project/monero#8823]
Wanna inform for this bug.
When in monero-cli-wallet option 'persistent-rpc-client-id' is set to 1 (on),then payments from the daemon getting to 'Stale' status and never received.
All of this is when payments for rpc are set to on.
Is there any solution?

**Comment by selsta** [comment]
We will drop the rpc payment system: https://github.com/monero-project/monero/pull/8724

See here for reasons to remove: https://github.com/monero-project/monero/issues/8722

**Comment by Dinamitrii** [comment]
Thanks i'll remove it right now
