### ISSUE TITLE
Persistent high CPU usage for a 24 hours

### ISSUE THREAD

**Issue by g00g1** [monero-project/monero#8824]
How can I figure out why monero daemon is utilizing almost 2 CPU cores fully for more than 24 hours is straight? Is it normal behavior for a public node? I am not observing high bandwidth utilization although. As of daemon start the blockchain was already synchronized.

```
$ date -u; echo; monerod status
Sun Apr 16 08:18:55 UTC 2023

2023-04-16 08:18:56.829	I Monero 'Fluorine Fermi' (v0.18.2.2-unknown)
Height: 2865386/2865386 (100.0%) on mainnet, not mining, net hash 2.49 GH/s, v16, 258(out)+73(in) connections, uptime 2d 20h 48m 29s
```

![image](https://user-images.githubusercontent.com/91201021/232284935-bbfdf14b-b65e-4eb6-958b-b59c3a817c3c.png)

![image](https://user-images.githubusercontent.com/91201021/232284599-21d8998a-d184-4d2e-ab87-a190b1ac5c68.png)

**Comment by selsta** [comment]
How did you install monerod? Did you compile it yourself?

**Comment by g00g1** [comment]
> How did you install monerod? Did you compile it yourself?

Yes, I have compiled it from source with `CXXFLAGS="-march=native -O2 -pipe"` using [Gentoo ebuild](https://gitweb.gentoo.org/repo/proj/guru.git/tree/net-p2p/monero/monero-0.18.2.2.ebuild) and `USE="daemon -readline -tools -wallet-cli -wallet-rpc"`

**Comment by selsta** [comment]
Apply this patch: https://github.com/monero-project/monero/pull/8731
