### ISSUE TITLE
How to run multiple nodes on one ip?

### ISSUE THREAD

**Issue by Dinamitrii** [monero-project/monero#8825]
How to run multiple nodes on one ip?
Sorry if this question is stupid but i want to run multiple nodes on different machines but i have only one real ip and i'm behind router.Port forwarding works only with one local machine.Which setting have to be changed or what could be the settings of the router?
Thank you in advance.

**Comment by moneromooo-monero** [comment]
Listen on different ports for p2p, rpc, and zmq (or just disable the latter). You probably also want a different --data-dir (though it's supposed to be able to use two nodes a single chain).

**Comment by Dinamitrii** [comment]
So until now i used the router capabilities for 
pc1 used the original ports 18080~18083 outer to the same inner forwarding
pc2 18084~18087 outer to the 18080~18083 inner and
pc3 18088~18091 outer to the 18080~18083 inner.

Until now pc2 and pc3 importing the blockchain(exported by me) and after that i'll see if getting this msg for no incoming connections.

How it seems to you this setup?
Thank you in advance :)
