### ISSUE TITLE
monerod segfault with homebrew

### ISSUE THREAD

**Issue by casrass** [monero-project/monero#8829]
My monerod segfaults at this exact point in its sync every time. I have resynced from scratch more times than I can count and it has not fixed the issue. I have tried every fix that I could find and none have worked, so I am making an issue report. Could anyone help me? Im on an M1 Macbook Pro, running monero from homebrew. The backtrace from lldb is as follows.

```023-04-23 03:22:17.071	I [142.254.87.115:18080 OUT] Sync data returned a new top block candidate: 2850807 -> 2870306 [Your node is 19499 blocks (27.1 days) behind]
2023-04-23 03:22:17.072	I SYNCHRONIZATION started
Process 98791 stopped
* thread #4, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001011d04b4 dyld
->  0x1011d04b4: ldpsw  x18, x19, [x18]
    0x1011d04b8: mov.d  v28[0], x18
    0x1011d04bc: mov.d  v28[1], x19
    0x1011d04c0: scvtf.2d v28, v28```

**Comment by selsta** [comment]
See https://github.com/monero-project/monero/issues/8657

It's unclear if this is an issue with macOS or on our side. Workaround

- Start monerod with the `MONERO_RANDOMX_UMASK=8` env var.
- Use the binaries from getmonero.org – they are built with an older SDK that doesn't have this issue.

**Comment by selsta** [comment]
Closing as a duplicate.
