### ISSUE TITLE
cant open wallet with monero-wallet-cli.

### ISSUE THREAD

**Issue by hubgitbb** [monero-project/monero#8833]
Hi
i have build the p2pool with Docker Compose and a new wallet was generated. i have the wallet name and password but cannot login to it.  there is no error message. it looks like the wallet does not exist.

monero-wallet-cli.log
**INFO    logging contrib/epee/src/mlog.cpp:273   New log categories: *:WARNING,net:FATAL,net.http:FATAL,net.ssl:FATAL,net.p2p:FATAL,net.cn:FATAL,daemon.rpc:FATAL,global:INFO,verify:FATAL,serialization:FATAL,daemon.rpc.payment:ERROR,stacktrace:INFO,logging:INFO,msgwriter:INFO**

**Comment by hubgitbb** [comment]
**monero@dffd5696461f:~$ monero-wallet-cli
This is the command line monero wallet. It needs to connect to a monero
daemon to work correctly.
WARNING: Do not reuse your Monero keys on another fork, UNLESS this fork has key reuse mitigations built in. Doing so will harm your privacy.

Monero 'Fluorine Fermi' (v0.18.2.2-release)
Logging to monero-wallet-cli.log
WARNING: You may not have a high enough lockable memory limit, see ulimit -l
Specify wallet file name (e.g., MyWallet). If the wallet doesn't exist, it will be created.
Wallet file name (or Ctrl-C to quit):**

**Comment by selsta** [comment]
You have to enter the wallet name that you want to open.

**Comment by hubgitbb** [comment]
if i enter my wallet name i get
"No wallet found with that name. Confirm creation of new wallet named"

**Comment by selsta** [comment]
It searches for the wallet in the same directory as the monero-wallet-cli binary. Is the wallet in the same directory? If not, try to manually set the path to the wallet using the --wallet flag.

**Comment by hubgitbb** [comment]
i cant find any wallet file that eq my walletname

**Comment by selsta** [comment]
You have to create a wallet first before opening it. If you have one created you also have a wallet and wallet.keys file.

**Comment by hubgitbb** [comment]
ok i have the wallet name, wallet password, the 25 words for recreating the wallet but i cant find the wallet file and wallet keys file
is it possible that docker did not create the files?

**Comment by selsta** [comment]
I am not familiar with your docker setup. The wallet file gets created in the same folder as the monero-wallet-cli binary by default.

Why even use docker to run monero-wallet-cli? Just run it locally and avoid all this extra complexity.

**Comment by plowsof** [comment]
"where does docker store files" / "where are my docker volumes located" is out of scope. once you find them point the monero wallet cli to it with `--wallet-file` as instructed above.

**Comment by hubgitbb** [comment]
My volumes are the defaults from the dicker compose file
monero:/home/monero/.bitmonero:rw
/dev/null:/home/monero/.bitmonero/bitmonero.log:rw
/dev/hugepages:/dev/hugepages:rw

But the wallet files are not in there

**Comment by selsta** [comment]
This is not the right place to get support on how to use docker.

I can only say again that I would suggest you to run monero-wallet-cli natively.

**Comment by hubgitbb** [comment]
OK thanks for the help

**Comment by selsta** [comment]
The docker compose is for running **monerod + p2pool**. It's not for running monero-wallet-cli. See https://github.com/SChernykh/p2pool/tree/master/docker-compose

> Run your own Monero Node + P2Pool + XMRig in Docker

It does not expose any wallet files. Run monero-wallet-cli locally on your computer and you won't have any issues.
