### ISSUE TITLE
I can't access my monero wallet

### ISSUE THREAD

**Issue by hugohugo130** [monero-project/monero#8847]
I'm using Windows 11
The version is v0.18.2.2
My hard drive failed, I formatted my hard drive and it worked. Now the problem is that my key file and seed file is missing. I lost both my seed and private key. I only know my wallet address. Can I still access my Monero wallet?

**Comment by selsta** [comment]
Unfortunately there's nothing we can do here, you need either your seed or your keys file :/

**Comment by hugohugo130** [comment]
Maybe I can use some software to restore data?

**Comment by hugohugo130** [comment]
I will try to use Recuva
I tried using Disk Drill yesterday to recover the files, but Disk Drill didn't work.

**Comment by hugohugo130** [comment]
Recuva didn't work :(
