### ISSUE TITLE
[Suggestion] Daemon RPC: submit_block improvements

### ISSUE THREAD

**Issue by duggavo** [monero-project/monero#8874]
I think submit_block should return the submitted block's fast hash, if successful.
This would allow to keep track of mined blocks more easily, as knowing the height might be not enough if there are reorgs.

**Comment by jeffro256** [comment]
I opened a PR (#8890) to add this feature. Now the `submit_block` RPC call will respond with a `block_id` field containing the block fast hash. Is this what you were imagining? Try compiling with that commit and test it out for yourself
