### ISSUE TITLE
Can I save the wallet after clearing the subaddress?

### ISSUE THREAD

**Issue by EWIT521** [monero-project/monero#8886]
static serializable_unordered_map<crypto::public_key, cryptonote::subaddress_index> m_subaddresses;
 
m_subaddresses, object containing 50 million subaddresses, each time save is called.A new wallet file is generated locally.
When the wallet is loaded  It takes a long time。 Can I save the wallet after clearing the subaddress?

**Comment by moneromooo-monero** [comment]
You can erase subaddresses from the map. If you do that though, the wallet will not see any output sent to any of those erased addresses, so you gotta make sure you only erase ones you're sure will be unused in the future.
There's no code for this atm but it's a straightforward change.

**Comment by EWIT521** [comment]
What kind of addresses is unused in the future?if I have deleted it ,What is the impact？
