### ISSUE TITLE
monero make error

### ISSUE THREAD

**Issue by shaoxianduiyuan007** [monero-project/monero#890]
`
/usr/include/boost/filesystem/path.hpp:300:5: note:   template argument deduction/substitution failed:
/usr/include/boost/filesystem/path.hpp: In substitution of ‘template<class Source> typename boost::enable_if<boost::filesystem::path_traits::is_pathable<typename boost::decay<F>::type>, boost::filesystem::path&>::type boost::filesystem::path::operator/=(const Source&) [with Source = boost::sub_match<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> > >]’:
/root/bitmonero/src/wallet/api/wallet_manager.cpp:104:66:   required from here
/usr/include/boost/filesystem/path.hpp:300:5: error: no type named ‘type’ in ‘struct boost::enable_if<boost::filesystem::path_traits::is_pathable<boost::sub_match<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> > > >, boost::filesystem::path&>’
make[3]: *** [src/wallet/CMakeFiles/wallet.dir/api/wallet_manager.cpp.o] Error 1
make[3]: Leaving directory '/root/bitmonero/build/release'
make[2]: *** [src/wallet/CMakeFiles/wallet.dir/all] Error 2
make[2]: Leaving directory '/root/bitmonero/build/release'
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/bitmonero/build/release'
make: *** [release-all] Error 2
`

> Use libboost 1.55
> Use libboost 1.55
> Use libboost 1.55

**Comment by moneromooo-monero** [comment]
More information would be helpful. In particular the call site from the monero tree (there may be like a dozen layers in the output). Also GCC version, and 32/64 bit of your arch.

**Comment by iDunk5400** [comment]
IIRC, that output comes after the /= operator error. Should be fixed in #889 and is already merged in master.

**Comment by shaoxianduiyuan007** [comment]
ubuntu 14 x64

**Comment by NanoAkron** [comment]
@shaoxianduiyuan007 is this issue still present or can it be closed?

**Comment by luigi1111** [comment]
Assume fixed in #889. If not please reopen with more information.
