### ISSUE TITLE
It is possible to open >1 connections to the same I2P node

### ISSUE THREAD

**Issue by nahuhh** [monero-project/monero#8918]
Monero has the same problem that bitcoin once did. You can even connect to yourself multiple times.

Bitcoin issue: https://github.com/bitcoin/bitcoin/issues/21389
comment with proposed fixes: https://github.com/bitcoin/bitcoin/issues/21389#issuecomment-866925116
the merged fix: https://github.com/bitcoin/bitcoin/pull/22112

In monero, `anonymous-inbound` broadcasts the i2p domains to peers. 
`anonymous-inbound` written as `anonymous-inbound=your.b32.i2p:18085,...` will broadcast `your.b32.i2p:18085`. It should only allow `anonymous-inbound=your.b32.i2p:0,...` or perhaps `anonymous-inbound=your.b32.i2p,...`

Im not sure what conditions must be met, but in certain circumstances it will broadcast 18080 as the port. Either way, the fix is to force port i2p peers to only be stored using port 0, and to remove duplicate i2p domains from peerlists.
the merged fix: https://github.com/bitcoin/bitcoin/pull/22112

this is i2p only. Onion works fine and uses ports

**Comment by nahuhh** [comment]
Worth noting that btc uses i2p sam and we use socks.

Either way, the ability to spam peerlists with "valid" peers on "different" ports (just a change to anonymous inbound i2p port), and being able to connect to yourself are the issues here

**Comment by MoneroArbo** [comment]
Having a possibly related issue where I did not specify a port in moderod config for my i2p inbound address, but my node makes an outgoing i2p connection to my own address, except it has :18080 appended at the end.

Some i2p peers in my list don't have a port number, others have 18080 or a non-default port, but as mentioned i2p doesn't really use ports so monerod should at a minimum recognize that xxxx.i2p and xxxx.i2p:18080 and xxxx.i2p:18088 and etc are all the same.

**Comment by MoneroArbo** [comment]
Confirming that I also form multiple i2p connections to the same (non-self) node but with different port numbers. Poking around the peer list, there are multiple entries for many if not most addresses. For example:

- s3l6ke4ed3df466khuebb4poienoingwof7oxtbo6j4n56sghe3a.b32.i2p:0
- s3l6ke4ed3df466khuebb4poienoingwof7oxtbo6j4n56sghe3a.b32.i2p:18080:0
- s3l6ke4ed3df466khuebb4poienoingwof7oxtbo6j4n56sghe3a.b32.i2p:28081:0

The extra :0 at the end of the latter two entries stands out as odd to me, especially as IPv4/6 addresses don't have it.

Regardless, it seems to me @nahuhh is entirely correct in their assessment of the issue.

**Comment by vtnerd** [comment]
I urge everyone having problems with this to try #9138 if they know how to compile from source. This should collapse overloads on port into one value.
