### ISSUE TITLE
wallet2 fails to save to disk if first created in-memory

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#8932]
If wallet2 is first created in-memory (i.e. with empty path `""`), then it will fail to save to disk, due to incorrect assumptions that the other files have already been created, based on this comment and the following logic: https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L6238

This issue requests fixing wallet2 to correctly save to disk after being created in-memory with empty path.

**Comment by jeffro256** [comment]
Which interface are you invoking to attempt to get it to save to the disk? Are you calling `store_to()` directly? Not ncessarily uper important, but just curious. Also, I can fix this v soon, thanks for finding that

**Comment by woodser** [comment]
Yeah I'm calling `store_to` directly, to support moving the wallet files [here](https://github.com/monero-ecosystem/monero-cpp/blob/a60c2752bb7f405a1d2e4c405ebfa57dc8efcd96/src/wallet/monero_wallet_full.cpp#L3449).

**Comment by jeffro256** [comment]
lmao just found another issue with `store_to` which was driving me utterly insane while unit testing a fix: if the new file path contains the old file path, it thinks its the same file and just deletes the cache.

**Comment by jeffro256** [comment]
Because I was trying to move a wallet file from `name` to `name_new` and the keys file showed up in the right place but my cache file kept disappearing

**Comment by jeffro256** [comment]
AND it doesn't save cache on when the file is different anyways??
