### ISSUE TITLE
Monero blockchain problem

### ISSUE THREAD

**Issue by hugohugo130** [monero-project/monero#8935]
I get an error when I try to sync the Monero blockchain

D:\Apps\Monero GUI Wallet>monerod.exe --prune-blockchain --data-dir "G:\monero-blockchain" --db-salvage
2023-07-07 11:26:46.112 My Monero "Fluoro Fermi" (v0.18.2.2-release)
2023-07-07 11:26:46.113 I am initializing the cryptocurrency protocol...
2023-07-07 11:26:46.114 I Cryptonote protocol initialization is normal
2023-07-07 11:26:46.115 I am initializing core...
2023-07-07 11:26:46.116 I am loading blockchain from folder G:\monero-blockchain\lmdb...
2023-07-07 11:26:46.137 W Attempt to get block from height 2879495 failed - block not in database

I used --db-salvage, doesn't work, and I accidentally backed up the wrong data.mdb, do I need to resync the blockchain? or other methods?

(Translated by google)

**Comment by selsta** [comment]
Yes, you will likely have to resync if you don't have a backup.

Did you plug out the harddrive during sync, have a power outtage or did you force shutdown your computer? All of this can cause corruption.

**Comment by hugohugo130** [comment]
I didn't unplug the hard drive (because it was a built-in SSD hard drive), didn't open monerod.exe when the power was off, and didn't force shut down the computer

**Comment by hugohugo130** [comment]
I am downloading the blockchain file (moneroblockchain.raw) and my command to import the blockchain is
monero-blockchain-import --imput-file "W:\rawfile\moneroblockchain.raw" --batch 2 --batch-size 35000 --log-level 4 --dangerous-unverified-import 1 --prune-blockchain - -data-dir "W:\monero-blockchain"

**Comment by selsta** [comment]
I would sync with monerod, download blockchain.raw is usually not faster and is also not recommended.

**Comment by hugohugo130** [comment]
oh ok thx. I'll use monerod.exe to sync my monero blockchain

**Comment by selsta** [comment]
20 days on an SSD?
