### ISSUE TITLE
New motherboard, now no start of bitmonerod

### ISSUE THREAD

**Issue by Elmit2015** [monero-project/monero#894]
Since I could not start anymore bitmonerod I rebuild the updated source.

I did not see any error during compiling.

The start however looks like:

~/bitmonero/build/release/bin$ ./bitmonerod 

```
Creating the logger system
2016-Jul-09 18:33:31.942942 Initializing cryptonote protocol... 
2016-Jul-09 18:33:31.943086 Cryptonote protocol initialized OK  
2016-Jul-09 18:33:31.943435 Initializing p2p server...         
2016-Jul-09 18:33:32.647114 Set limit-up to 2048 kB/s
2016-Jul-09 18:33:32.647355 Set limit-down to 8192 kB/s
2016-Jul-09 18:33:32.647469 Set limit-up to 2048 kB/s
2016-Jul-09 18:33:32.647602 Set limit-down to 8192 kB/s 
2016-Jul-09 18:33:32.657789 Binding on 0.0.0.0:18080 
2016-Jul-09 18:33:32.658064 Net service bound to 0.0.0.0:18080
2016-Jul-09 18:33:32.658135 Attempting to add IGD port mapping.

2016-Jul-09 18:36:13.756596 Deinitializing rpc server...                                           
2016-Jul-09 18:36:13.756789 Deinitializing p2p...                                                   
2016-Jul-09 18:36:13.768390 Deinitializing core...
2016-Jul-09 18:36:13.768981 Closing IO Service. 
2016-Jul-09 18:36:13.769242 Failed to deinitialize core... 
2016-Jul-09 18:36:13.769347 Deinitializing cryptonote_protocol...
```

How to track down the problem?

**Comment by antanst** [comment]
I noticed this behaviour when I accidentally tried to run an older bitmonerod using a data dir with an updated database format from a newer version of the daemon. Are you sure you've compiled bitmonerod from latest master?

**Comment by radfish** [comment]
Run with verbose logging and attach the log:

    ./bitmonerod --log-level 6

**Comment by Elmit2015** [comment]
Thanks, reading the log helped to get the new database synced.

Got now new problem:
`sudo cpuminer/cpuminer-multi/minerd -a cryptonight -o stratum+tcp://monerohash.com:3333 -u ******* -p x -t 4
`
results in two lines:
`[2016-07-10 06:31:16] Using JSON-RPC 2.0                                                            │
[2016-07-10 06:31:16] 4 miner threads started, using 'cryptonight' algorithm. `

**Comment by NanoAkron** [comment]
@Elmit2015 is this issue still current or can it be closed?

**Comment by luigi1111** [comment]
@Elmit2015 Please reopen with more information if this is still relevant.
