### ISSUE TITLE
Didn't receive monero my balance is 0.

### ISSUE THREAD

**Issue by GpStop** [monero-project/monero#8982]
Hello is there someone who can help me. i'm new in monero world and i'm not a developer and now i have a problem that i cannot resolve by myself. So my problem is:

Someone send me a monero, but i wasn't sync already. I download and instal monero GUI and connected it to my ledger, but the sync took much time. So they send me monero on my address before i sync. They send me a tx key that i check and the transaction was on.
I check online and i saw that i have to change wallet restore height. I did it i change it to 100001.
I'm in local node all sync but ballance is 0.00000
I use GUI interface and do rescan wallet balance, then scan transaction with the tx key. nothing happened.
I have windows firewall off. But i have also kaspersky antivirus on. Is this the problem? Should i have to uninstal kaspersky and windows firewall? How can i trace my missing transaction? How to fix my 0 balance?
I really don't know what to do. I need help. Is there someone who can help me fix it ?

**Comment by selsta** [comment]
As a first step go to Settings -> Info and share

- Wallet mode
- Version
- Wallet restore height

**Comment by GpStop** [comment]
> As a first step go to Settings -> Info and share
> 
> * Wallet mode
> * Version
> * Wallet restore height

I've done this already
i set my wallet height to 100003, to be sure, but still 0 balance.

**Comment by selsta** [comment]
Please answer my full question so that I can help you

**Comment by GpStop** [comment]
> Please answer my full question so that I can help you

Advanced mode
0.18.2.2
100001

**Comment by selsta** [comment]
Ok, go to Settings -> Log, type "status" and share the output here.

**Comment by GpStop** [comment]
[9/7/2023 2:33 PM] 2023-09-07 11:33:12.387 I Monero 'Fluorine Fermi' (v0.18.2.2-release) 
Height: 1382070/2968904 (46.6%) on mainnet, not mining, net hash 137.16 MH/s, v5, 12(out)+0(in) connections, uptime 0d 0h 40m 48s

**Comment by selsta** [comment]
If you use a local node you have to wait until it is synced to 100%. If you don't want to wait you have to manually set a remote node.

**Comment by GpStop** [comment]
i know i just start, that's why it's not 100%

**Comment by selsta** [comment]
Restarting the GUI does not delete your blockchain progress.

Did you manually delete the blockchain file?

To give you support you either need a local daemon that is 100% synced or you manually connect to a synced remote node.

**Comment by GpStop** [comment]
it's not 100% sync. It takes more than 10 hours and i don't know why?
I've done this already. Usually when i got log in it takes few minutes, but now i don't know why it sync from 0.
My disc space was full with monero network about 217GB, now when i sync it was erased and start from 110Gb.
I don't understand why this happened.
Everyday it takes few minutes now ... hours.

**Comment by selsta** [comment]
You are syncing your node from scratch, that takes 12h to a couple days depending on your hardware and over 160GB.

If you don't have enough space then I would recommend you to either use a pruned node (you can select that during the initial wizard), or a remote node.

Do you know how to connect to a remote node or should I post the steps?

**Comment by GpStop** [comment]
i know how to do it but not gonna do. 
i'm still waiting for now . it's almoust done.
2 more hours may be

**Comment by GpStop** [comment]
is it going to do load from scratch every time? because new time will have no disc space.
How to stop this .
I did this download this and now again it doesn't seem right.
Do i have to change wallet hight again with something more.
now its 100001 do i have to do it at may be 2100000.

**Comment by selsta** [comment]
> is it going to do load from scratch every time?

No, but you said in your previous comment that your disk space was full so it seems you manually deleted the blockchain at some point?

> Do i have to change wallet hight again with something more.

Depends on if your funds show up.

**Comment by selsta** [comment]
I don't know what happened but there is no integrated function to delete the blockchain. Either you deleted it yourself or you set a different blockchain location in Settings -> Node.

**Comment by GpStop** [comment]
i'm still waiting. i gues 1 more hour, after that what do u want me to do?

**Comment by selsta** [comment]
The last percentage of the daemon sync takes the longest so it will likely take more than 1 hour.

To me it seems it seems that you have limited disk space so it might make sense to connect to a remote node for now, at least until your funds show up. Running a node with a close to full disk won't be a good experience.

**Comment by GpStop** [comment]
[9/9/2023 1:29 AM] 2023-09-08 22:29:46.914 I Monero 'Fluorine Fermi' (v0.18.2.2-release) 
Height: 2969956/2969956 (100.0%) on mainnet, not mining, net hash 2.16 GH/s, v16, 12(out)+0(in) connections, uptime 0d 18h 37m 14s

**Comment by GpStop** [comment]
that's my second download of the monero system. Now i have only a 80GB free. 
I don't have space for 3 times. my balance is still 0.
what if i download monero network on another pc. do the hashes can i use my wallet. i mean my exact wallet with my exact address. can i use them on another pc like recover or something?
im asking because if there is no space i have to do something or erase my network on this pc and start over again or new pc with same wallet address.

**Comment by selsta** [comment]
Let's first try to find your balance and then check regarding remaining storage.

If you go to Settings -> Info, click on "Change restore height", set it to 1 and then click on ok twice, now it should only sync the wallet from scratch. This will likely take 30 minutes or so but it will not use more storage.

**Comment by GpStop** [comment]
> Let's first try to find your balance and then check regarding remaining storage.
> 
> If you go to Settings -> Info, click on "Change restore height", set it to 1 and then click on ok twice, now it should only sync the wallet from scratch. This will likely take 30 minutes or so but it will not use more storage.

**Comment by GpStop** [comment]
Hello friend i'm back.
Now i'm 100% online 24/7 
I'm waiting for you advice. i'm all yours.
I set my wallet height to 1 as u told me.

**Comment by selsta** [comment]
Did you let it sync after changing it to 1?

**Comment by GpStop** [comment]
all sync

**Comment by selsta** [comment]
And still no funds? ... Do you have the transaction id of a transaction that should be inside your wallet?

**Comment by GpStop** [comment]
no funds. i have tx key

**Comment by selsta** [comment]
Do you have multiple wallets / seed and made sure that you didn't open the wrong one?

**Comment by GpStop** [comment]
Just one hardware wallet. no multiple wallets.

**Comment by selsta** [comment]
Ledger / Trezor? Did you confirm that your wallet address is correct compared to your old wallet?

Also can you make a screenshot of the bottom left part of the GUI where it shows the status?

**Comment by GpStop** [comment]
ledger yes everything.

[9/12/2023 3:30 PM] 2023-09-12 12:30:51.356 I Monero 'Fluorine Fermi' (v0.18.2.2-release) 
Height: 2972561/2972561 (100.0%) on mainnet, not mining, net hash 2.18 GH/s, v16, 12(out)+0(in) connections, uptime 0d 1h 43m 39s

**Comment by GpStop** [comment]
wallet daemon sync network status connected 
account #0 xmr balance 0 thats all

**Comment by GpStop** [comment]
no transactions yet

**Comment by GpStop** [comment]
how about these commands in the log
where can i type for tx key to my wallet

**Comment by GpStop** [comment]
Tx hash: 
Tx public key: 
Payment id (encrypted): 
Transaction  was carried out on the Monero network on 2023-07-05 16:02:37. The transaction has 14312 confirmations

is that helpful i don't want to share the exact id and stuff

**Comment by selsta** [comment]
Is this supposed to be an incoming or an outgoing transaction?

**Comment by selsta** [comment]
Try to go to Settings -> Wallet, click on "Scan transaction", and then enter the transaction hash and press ok. What happens?

**Comment by GpStop** [comment]
transfer succesfully searched . and that's it .
still 0

**Comment by selsta** [comment]
Did you change the account number on your physical Ledger? In the settings you can switch between account 0, 1, etc. Make sure you have 0 selected.

**Comment by GpStop** [comment]
on ledger  settings - select wallet - it will reset the application! 0+ 1 2 3 4 5 6 7 8 9  these are the options
the other select network - test network stage network main network+
these are options i don't do anything wrong because it says reset

main adress - major:0 minor:0

**Comment by GpStop** [comment]
what should i do i mean i don't want to crash something

**Comment by selsta** [comment]
There's something non-obvious going on. Usually a resync from 0 is enough to solve everything.

Did you setup your Ledger from scratch at some point with a new seed?

**Comment by GpStop** [comment]
monero is new for me . i made a new address and wallet especially for this transaction. so i did it for the first time.
download it from getmonero.org install hashes new hardware wallet averything is brand new and for the first time.
so i did't have any transactions and actions on the monero network.
i've had only bitcoin account but this is different. i had also a kaspersky antivirus. can it block the monero network or search for transactions?

**Comment by GpStop** [comment]
let end for today. see ya tomorrow

**Comment by selsta** [comment]
> i made a new address and wallet especially for this transaction

How did you do this?

**Comment by GpStop** [comment]
> > i made a new address and wallet especially for this transaction
> 
> How did you do this?

I didn't have monero at all. so i have to get the monero network. i go to getmonero and follow steps.
download instal hash and make a new wallet advance option and that kind of stuff. i didn't have monero adress before that.

**Comment by GpStop** [comment]
hey friend i want to ask u something. 
in the cli version of monero there is a commands that u can control everything. 
what about if i use these commands into my gui. there is a window with commands that u told me to write status. is it going to work?

**Comment by plowsof** [comment]
Those commands are sent to your local node aka daemon/monerod. You have a txid , please scan it (if not already).[heres a guide](https://deploy-preview-1996--barolo-time-757cf9.netlify.app/resources/user-guides/scan-txid.html). If you see any kind of error that might indicate a problem with your node, use a remote one OR sync from scratch.  If you say "i know how to do it but not gonna do" then my frown, will not be turned upside down! :(

Please consider IRC/Matrix for tech support e.g. #monero-support on libera.chat (ignore dms) as thousands of people receive emails for each comment.

**Comment by selsta** [comment]
Can you go to the Accounts page in the GUI and check if you have multiple accounts? Do you still know if the address you sent to the other party started with a 4 or 8?

> what about if i use these commands into my gui. there is a window with commands that u told me to write status. is it going to work?

The "status" message is a command to your daemon. That is unrelated to the CLI wallet.

**Comment by GpStop** [comment]
my address start with 4

**Comment by GpStop** [comment]
if i use a another pc and there i install cli wallet is it going to work? i mean if i succeed to put my wallet there and if i use commands to tranck and to catch the missiong transaction to my wallet?

**Comment by selsta** [comment]
One thing we can try is that you give me your address (can be a subaddress if you are concerned about privacy) and I send you a small amount of XMR. If that shows up and the other transaction doesn't show up it means it was sent to a different wallet.

**Comment by GpStop** [comment]
we can try this.

**Comment by GpStop** [comment]
subaddress but same wallet right?

**Comment by selsta** [comment]
Yes, subaddress from the same wallet.

**Comment by GpStop** [comment]
87JFnK3764MbaADmExNHc22PZTo7akobR8P143Kex8rwdEj7jRxEFoj4FpJxkWVaDR3UyKWAedgFics6Pt4PKRo83vTC4DE

my subaddress starts with 8
my 0 address start with 4

**Comment by selsta** [comment]
Sent <137b4190f10618c81394a2e39467a40f3741c86f835abf37f64887597d7ef7f8>

**Comment by selsta** [comment]
It should show up by itself, did your balance increase?

**Comment by selsta** [comment]
Did you export your private view key on your Ledger when opening your wallet?

**Comment by GpStop** [comment]
yes

**Comment by selsta** [comment]
Did you take the subaddress from the "Receive" or the "Account" page?

**Comment by GpStop** [comment]
u told me receive and i did it .

**Comment by selsta** [comment]
Yes, Receive is correct. I just try to double check everything.

**Comment by GpStop** [comment]
i'm telling u that's very strange. i feel like i download the network and complete everything. i verify evrything and everything looks nice and done. but the transactions didn't come to me it's like something is blocking me.

**Comment by GpStop** [comment]
and keep doing that. sync is complete wallet is sync. and then start over again. wallet sync then sync .

**Comment by selsta** [comment]
Is this how it looks like in the bottom left corner?

<img width="289" alt="" src="https://github.com/monero-project/monero/assets/7697454/7b34bf5b-cd92-4d98-8d1a-72e6065fff3f">

**Comment by GpStop** [comment]
yes

**Comment by GpStop** [comment]
0.001000

**Comment by selsta** [comment]
Yes, so that did show up?

**Comment by GpStop** [comment]
just now

**Comment by selsta** [comment]
Next thing to try:

You go to Settings -> Info, click on "Change", enter 2920000 and then on okay twice.

Now you wait for it to resync and once it is finished tell me how many transactions you see.

If it is still just 1 then the transaction got sent into a different wallet.

**Comment by selsta** [comment]
https://xmrchain.net/search?value=2920000 is 2023-07-01 07:35:10

You said your transaction is from 2023-07-05 16:02:37 so it should work.

**Comment by GpStop** [comment]
only 1 transaction

**Comment by GpStop** [comment]
So we check the monero network is working.
Now we do something else. the missing transaction is in the monero network. it's hidden encrypted locked or whatever.
I have a key for that transaction, i'm not sure id key or tx key but i have it. so i have to catch this from the monero network.
i saw in the cli that there is a commands to do that, so should be in the gui interface.
in the log that  u tell me to type status, there is also help command. when u type it there is some commands that are tx and id .
so i want u to test these commands type and see what will happen.

**Comment by plowsof** [comment]
@GpStop 

Now then. You have a ledger. So extract the private viewkey (i think featherwallet shows it now, not certain, otherwise follow [this guide](https://shawnhogan.com/2021/07/how-to-get-monero-private-view-key-from-ledger.html)

Great, we have the private viewkey , the txid and the address it was sent to, perfect. Now, go to a blockchain explorer like the p2pool one which even has a tor link (open source so you can host it yourself if you want) https://p2pool.io/explorer/tx/5dbd3a47b1174d0442aed9f4ad87e5704b2b905e35a2e4e288649b422c1aea8b

There is a decode outputs box. So i want you to type your private viewkey + address it was sent  to and see what happens.

**Comment by GpStop** [comment]
transactions appear to be findable with print_tx

**Comment by selsta** [comment]
Yes, the transaction exists. But it wasn't sent to your wallet, otherwise it would have shown up. You have to think if you ever created a separate wallet? Do you have malware on your computer that changes the address when copying? Did you double check on the "Account" page that you didn't send it to a different account?

**Comment by GpStop** [comment]
check check and check

**Comment by GpStop** [comment]
The print_tx monerod command finds a transaction by its txid:


  print_tx TXIDHERE

The output will tell you whether that transaction was found, and if it was, whether it is mined or still in the txpool. If it was mined, you'll see when it was mined

how about that?

**Comment by GpStop** [comment]
should i do this?

**Comment by selsta** [comment]
`print_tx` is a monerod command, it will just say yes this transaction exists in the blockchain. It will not say anything about if this transaction is in your wallet.

Who sent you this transaction? Are they an reputable exchange?

**Comment by GpStop** [comment]
was not an exchange, a person send me for the first time to see and check the monero network what is it.

**Comment by GpStop** [comment]
there are other commands that contains tx

**Comment by selsta** [comment]
All commands on monerod are solely network related, they are not related to your wallet. wallet and monerod are separate programs.

Can you double check and ask this person what address they sent the funds to? Maybe you still have the chatlog?

**Comment by GpStop** [comment]
what will happen if i type  print_tx (and tx address) 
i don't want to type anything without u say because i don't want to crash something.
i check and recheck the address and wallet and evrything is 100% but it's still not in my wallet.
they send it to me before i sync and that's it.
I know where is it what block what date they send it the tx key my address everything, so i have to catch it somehow.

**Comment by GpStop** [comment]
what JSON HEX is ?

**Comment by selsta** [comment]
The print_tx command can only help you to see if the transaction is on the blockchain, it does not help you to see if it is in your wallet.

I sent some XMR to you and it showed up correctly. The fact that the other don't show up means they didn't send it to your address.

**Comment by GpStop** [comment]
i gues i have to try cli interface.

**Comment by GpStop** [comment]
i can see the number of the exact block, should i have to mine it?

**Comment by selsta** [comment]
The CLI interface won't help here and you don't have to mine the block, the block is already mined. The person who sent you the funds sent it to the wrong address. You don't have to do anything if it's sent to the correct address, like the 0.001 XMR I sent you a couple days ago. It would show up correctly.

**Comment by GpStop** [comment]
Hello selsta. Sorry for not answearing u  i was sick.
I want to ask u something.
I saw a person who has the same problem. He said that he go to remote note and refresh wallet and that helped.
He said he had transaction of monero before his wallet sync. Just like me. should i try this because this is the only thing i didnt do.

**Comment by selsta** [comment]
We already did a full rescan in this comment: https://github.com/monero-project/monero/issues/8982#issuecomment-1717906469

As far as I can see only my transaction showed up. I still assume the person who sent you the money didn't send it to the correct address.

**Comment by GpStop** [comment]
I want to try remote note. Can u help me with that. 
I haven't done it before. Do u know a good remote note that i can join. I don't know how to find any?

**Comment by Unkn8wn69** [comment]
Xmrguide.org had a couple

**Comment by selsta** [comment]
address: selsta1.featherwallet.net port: 18081
address: selsta2.featherwallet.net port: 18081

**Comment by GpStop** [comment]
Couldn't connect to Daemon: 127.0.0.1:18081
i can't join your stuff selsta

**Comment by selsta** [comment]
My nodes are online and the message you posted is irrelevant for remote nodes. What does it say in the bottom left corner?

**Comment by GpStop** [comment]
remote node

**Comment by selsta** [comment]
<img width="305" alt="remote node" src="https://github.com/monero-project/monero/assets/7697454/2641ae14-c4ff-4a69-9cc0-39d45b2ea2d1">

If it looks like this it means it's connected correctly.

**Comment by GpStop** [comment]
yes

**Comment by selsta** [comment]
I can only repeat again, whoever sent you the transaction didn't send it to the correct address. That's why my test transaction shows up and the other one doesn't. It's not a node related issue.

**Comment by GpStop** [comment]
selsta u told me to do this: 
https://p2pool.io/explorer/tx/5dbd3a47b1174d0442aed9f4ad87e5704b2b905e35a2e4e288649b422c1aea8b

There is a decode outputs box. So i want you to type your private viewkey + address it was sent to and see what happens.

**Comment by GpStop** [comment]
it says that transaction is send to my wallet address. i check it several times.
i have to try cli.
Would u like to guide me step by step, i mean, i don't what to do with it.
I can only download and then...
would u like to help me more?

**Comment by selsta** [comment]
What transaction is this? https://p2pool.io/explorer/tx/5dbd3a47b1174d0442aed9f4ad87e5704b2b905e35a2e4e288649b422c1aea8b

The transaction is from Sep 11, but you opened this issue on Sep 6 so it can't be the missing transaction.

**Comment by GpStop** [comment]
the transaction was send before i sync my gui

**Comment by GpStop** [comment]
this is wrong that i send u i'm sorry.
u send me https://xmrchain.net to check my transaction
and i did many times

**Comment by selsta** [comment]
Sending before syncing the GUI is not an issue. I juat don't know what this transaction id (5dbd..) is. It can't be your missing transaction since it's from days after you even opened this issue.

**Comment by GpStop** [comment]
don't look at this id(5dbd...) i was posting something wrong

**Comment by selsta** [comment]
I feel like this is going in circles. Since the transaction I sent you is showing up after a rescan, but the transaction this other person sent you doesn't show up it's almost certain they didn't send it to the correct address. Using a different wallet, node etc. isn't going to help here. It appears they simply didn't send it to the correct place.

I'll close this issue since the bug tracker isn't the right place for this but if you continue to need support I'd suggest the #monero-support matrix channel: https://www.getmonero.org/community/hangouts/
