### ISSUE TITLE
Create monero-project repo for organization issues unrelated to software development

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero#903]
I've repeatedly found myself with instances of questions/issues/proposals that don't fit into the categories of bitmonero, kovri, monero-site, and monero-forum. A few of these issues have been posted to both the forum and IRC but I've had little-to-no response and it is a bit discouraging - though I think the lack of response is understandable considering the nature of forum software and IRC in general (so, no hard feelings).

I propose a centralized repository that will cover all organizational issues unrelated to software development. Something that will give us a chance to easily review and contribute to project ideas in a memorable setting. The issues covered would also include all public DevOps-related concerns and *possibly* all future [ideas](https://forum.getmonero.org/6/ideas) of which are currently only accessible through the forum.

Note: if anyone hasn't visited the [ideas](https://forum.getmonero.org/6/ideas) section in a while, I think that there are some good all-across-the-spectrum ideas that deserve some more attention.

**Comment by luigi1111** [comment]
What should we call it? :)

**Comment by anonimal** [comment]
I had imagined ```monero-project/monero-project``` and a nice caption to clarify its purpose but maybe there's a better name?

**Comment by radfish** [comment]
monero-project/meta

**Comment by livinginformation** [comment]
Repo-y McRepoface

(in all seriousness, I like @radfish's "Meta" Suggestion)

**Comment by anonimal** [comment]
```
i2p-relay | {-ArticMine} monero-organization for #903
```

I like ```monero-organization``` or ```monero-org``` or ```organization```

**Comment by luigi1111** [comment]
I like `organization`.

**Comment by fluffypony** [comment]
+1 for ```meta```, or failing that ```org```

**Comment by anonimal** [comment]
I've never understood the recent trend to use meta as a singular noun. To me, [it just doesn't make sense](https://en.wikipedia.org/wiki/Meta).

:+1: for ```organization``` or for new ideas that we could be unanimous about.

How about ```meta-monero```?

**Comment by luigi1111** [comment]
That same wiki page says:

> For information on the wiki-based web site for the coordination of all the Wikimedia Foundation projects, see Wikipedia:Meta.

LOL

**Comment by anonimal** [comment]
@luigi1111 apparently they don't always read what people write :laughing: 

I take it we're waiting for some Esperanto naming alternatives?

**Comment by luigi1111** [comment]
I say we go with `meta` to see if you get upset. :laughing:

**Comment by anonimal** [comment]
Hi everyone. I'm hoping to revisit this soon. There are many things related to I2P and Kovri that the community could help with that are *not* code related. For example, scraping and saving years of core I2P development from `zzz.i2p`.

We've had a long discussion on IRC about this and are finding long-term solutions, but if a meta repo was opened, it would be easier to keep track of this issue and others.

So, a name? Do we need to pick straws or throw a :game_die:?

**Comment by luigi1111** [comment]
`meta` `meta` `meta`

**Comment by anonimal** [comment]
@luigi1111 I'm not sure about those first two choices. The 1st `meta` is mmm, ok? The 2nd `meta`, well I don't really like that all. The third one though.... I think I like the third one the most: `meta`.

**Comment by luigi1111** [comment]
That's so meta.

**Comment by luigi1111** [comment]
See https://github.com/monero-project/meta
