### ISSUE TITLE
start of monerod gives "Segmentation fault (core dumped)" on Archlinux

### ISSUE THREAD

**Issue by ZombB** [monero-project/monero#9055]
When the monerod daemon is started on Archlinux it segfaults every time. I have attached the shelloutput when trying to start the daemon manually and the logfile that is produced.

[monero.log](https://github.com/monero-project/monero/files/13257610/monero.log)
[shelloutput.log](https://github.com/monero-project/monero/files/13257611/shelloutput.log)

This bug first appeared on Monero 'Fluorine Fermi' (v0.18.2.2-release)

This is my Linux kernel version: 6.5.8-arch1-1

monerod was installed using the package manager which is pacman on Archlinux. So this affects the official monero Archlinux package: https://archlinux.org/packages/extra/x86_64/monero/

/mnt/ is a local harddrive on the PC. Precisely it is an ext4 filesystem on a raid 5 array.

I ran monero as a full node since 2017 on this machine and the node was fully synced up. Then suddenly the daemon did not get started during boot.

When I  updated to Monero 'Fluorine Fermi' (v0.18.2.2-release) using the regular Archlinux updates with the distros standard package manager pacman. And it synced up again.
Then from one day to another it stopped working. The daemon did not start. This problem persists also with the succeeding updates of the package.

@ketiv17 has recently filed a similar bug https://github.com/monero-project/monero/issues/9054

_*** by mistake this issue was initially filed under monero-gui, see https://github.com/monero-project/monero-gui/issues/4233 but actually it is not monero-gui instead it is the monero package and I am using monero-cli ***_

**Comment by selsta** [comment]
Did you lose access to the storage at some point during sync? E.g. power outtage or other reason it would unmount?

Do you have a backup of the blockchain or file are you able to sync up from scratch again? To me it looks like a corrupted blockchain but it's difficult to say why it happened.

**Comment by ZombB** [comment]
Thank you for the hint. I synced up from scratch again and now everything works again. Closing this issue.

**Comment by rslay** [comment]
`monerod --db-salvage` saved me from having to redo my whole blockchain, saves it if it is corrupted from a hard reboot or whatever else
