### ISSUE TITLE
Monerod crashing on Macbook Pro M1

### ISSUE THREAD

**Issue by ChesterHCopperpot** [monero-project/monero#9062]
Monerod --log-level 2 output: https://paste.debian.net/hidden/cb58677a/

Mdb_stat output: https://paste.debian.net/hidden/39140c0b/

I've had this problem for a while. Seems it is related to RandomX. I recently tried rebuilding as I thought that it might be fixed with RandomX v1.2.1, which merged [issue 259](https://github.com/tevador/RandomX/pull/259) related to Apple silicon, but this doesn't seem to have helped.

Any ideas?

Edit: Forgot to add that my M1 Pro has 32GB of RAM and is on MacOS Sonoma 14.1

Edit 2: Whoops I see that RandomX 1.2.1 is not in the most recent tag. I'll rebuild off master and see if that helps...

**Comment by ChesterHCopperpot** [comment]
Well what do you know. Solved my own problem. 

For future readers, this fix for Apple CPUs will be included in a future Monero release, so this issue is unlikely to rise up again.

**Comment by hyc** [comment]
The actual change that fixed this was in https://github.com/tevador/RandomX/pull/281

**Comment by ChesterHCopperpot** [comment]
Ah good to know. Thanks Hyc. Either way, building from Master solved this issue, and it will be included in the next Monero release.

Have ALWAYS appreciated the hard work you've done for Monero. Thanks again.
