### ISSUE TITLE
openalias starting with any digit is invalid

### ISSUE THREAD

**Issue by Minecon724** [monero-project/monero#9066]
![image](https://github.com/monero-project/monero/assets/39800107/e0dcb21b-3101-4b58-9135-dfe19ff72bd4)
![image](https://github.com/monero-project/monero/assets/39800107/80870885-85f7-461a-8c15-41576d718326)
![image](https://github.com/monero-project/monero/assets/39800107/57184aae-6c53-4ce8-a67a-07923a4bd5de)

**Comment by selsta** [comment]
Thank you, I'm closing this here as this is not the GUI repository but this should be fixed in the next release.
