### ISSUE TITLE
print_height displays higher by 1 number on stagenet

### ISSUE THREAD

**Issue by quakemmo** [monero-project/monero#9071]
Using Monero 'Fluorine Fermi' (v0.18.3.1-release) on Linux.

monerod's print_height command displays a number higher (by 1) than the actual blockchain height.
Displaying the latest block (as reported by print_height) results in an error. The issue doesn't seem to be there on mainnet.

```
print_height
1484213

print_block 1484213
Error: Unsuccessful -- 

print_block 1484212
<prints block json OK>

```

**Comment by selsta** [comment]
1484213 is currently being mined, 1484212 is the last mined block.

From what I can tell this behaviour is consistent on mainnet, testnet and stagenet.

**Comment by quakemmo** [comment]
Correct, behavior is consistent between mainnet, and testnet. I guess I just ran into a race condition when between the moment I typed print_height and print_block on mainnet, a block has been mined.

Is there a particular reason that the "currently being mined" block is included in the print_height result? This isn't consistent with other blockchains such as ethereum or bitcoin, where "blockchain height"  relates to blocks that already have been mined. Or am I completely wrong somewhere?

**Comment by selsta** [comment]
From what I know behaviour has always been this way in monero, I don't know why exactly but changing this now would break a lot of existing systems.

**Comment by quakemmo** [comment]
Thanks for your replies!

**Comment by quakemmo** [comment]
Thanks for your replies!
