### ISSUE TITLE
Can't create cold transaction!

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9078]
1. I exported exits to file from only-view wallet.
2. I opened the same cold wallet on computer without network and tap on "import exits". But it prints error "Failed to import outputs: Failed to import outputs: Hot wallets cannot import outputs"!

How can I fix it?

**Comment by developergames2d** [comment]
> Can you follow all the steps in this tutorial? It seems you did something wrong.
> 
> https://monerodocs.org/cold-storage/offline-transaction-signing/

Is it necessarily use CLI? I used gui-v0.18.3.1...

**Comment by selsta** [comment]
You can also use the GUI. "Hot wallets cannot import outputs" means that your wallet was at some point connected to a node, meaning it's not a cold wallet anymore but a hot wallet. This can happen if you copy the wallet file.

**Comment by developergames2d** [comment]
> You can also use the GUI. "Hot wallets cannot import outputs" means that your wallet was at some point connected to a node, meaning it's not a cold wallet anymore but a hot wallet. This can happen if you copy the wallet file.

What do I need to do? Delete this wallet and restore it from the SEED without connecting to the network?

**Comment by selsta** [comment]
Generally a cold wallet should have been created on a computer without internet connection in the first place.

If you still want to use this wallet then yes you have to restore from seed without connecting to the internet, but it would be preferable to create a new wallet that was never connected to the internet.

**Comment by developergames2d** [comment]
> Generally a cold wallet should have been created on a computer without internet connection in the first place.
> 
> If you still want to use this wallet then yes you have to restore from seed without connecting to the internet, but it would be preferable to create a new wallet that was never connected to the internet.

I have a new problem: I could to import exits and export keys, but when I launch view-only wallet and connect to remote daemon, the button "import" for keys is non-clickable.
![image](https://github.com/monero-project/monero/assets/106807841/561f7376-3cdd-46ff-b59e-dde23d669f77)

After I try to transfer coins without keys, and it worked...

**Comment by developergames2d** [comment]
Напишу по-русски:
Я вообще не понимаю, зачем нужны ключи. Отправить можно так:
1. Для сгенерированного кошелька взять адрес, private view key и высоту блока.
2. Создать кошелёк только для просмотра с этими параметрами в Monero gui.
3. Во вкладке "Отправить" ввести адрес, сумму и комиссию.
4. Нажать "Оффлайн подпись транзакций"->Создать и сохранить файл "SIGN".
5. На компьютере без сети восстановить сгенерированный кошелёк из SEED или открыть восстановленный.
6. Нажать "Оффлайн подпись транзакций"->Подписать(оффлайн) и выбрать файл "SIGN". В папке должны добавиться файлы "SIGN_signed_keyImages" и "SIGN_signed".
7. Открыть онлайн кошелёк только для просмотра.
8. Во вкладке Отправить нажать "Оффлайн подпись транзакций"->Отправить и выбрать файл "SIGN_signed". Монеты должны отправиться.

Причём после последнего действия мне выскакивает сообщение об ошибке, но монеты все равно отправляются. Я так и не понял, зачем нужен экспорт/импорт выходов и ключей, и зачем эти пункты в инструкции.

**Comment by developergames2d** [comment]
> You have to set your remote node as a trusted daemon to import key images.

This was done: see left-down data on the screenshot, I used remote node.

**Comment by selsta** [comment]
Yes, you are connected to a remote node but the screenshot doesn't show if you marked the remote mode as a trusted node. You can do that in the remote node settings.

**Comment by developergames2d** [comment]
> Yes, you are connected to a remote node but the screenshot doesn't show if you marked the remote mode as a trusted node. You can do that in the remote node settings.

Okay, I'll try later, but I don't understand now why do this if the coins are sent without import/export keys and exits. As I wrote in 9078#issuecomment-1831613572 all works with using only creating sign-file online, signing this file offline and broadcasting signed file to mempool online.

**Comment by selsta** [comment]
Your comment is in Russian, I didn't fully understand it. I think importing key images is only necessary after you sent a transaction, if you only had received transactions then you don't have any key images to import.
