### ISSUE TITLE
Error with blockchain after abnormal shutdown

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9081]
After abnormal shutdown I can't to continue download local blockchain ".../lmdb/data.mdb": in logs print:
[29.11.2023 15:04] 2023-11-29 08:04:14.546 I Monero 'Fluorine Fermi' (v0.18.3.1-release) 
Error: Couldn't connect to daemon: 127.0.0.1:18081
[29.11.2023 15:05] 2023-11-29 08:05:47.031 I Monero 'Fluorine Fermi' (v0.18.3.1-release) 
Error: Couldn't connect to daemon: 127.0.0.1:18081
[29.11.2023 17:29] 2023-11-29 10:29:55.191 I Monero 'Fluorine Fermi' (v0.18.3.1-release) 
Error: Couldn't connect to daemon: 127.0.0.1:18081
[29.11.2023 17:30] 2023-11-29 10:29:59.568 I Monero 'Fluorine Fermi' (v0.18.3.1-release) 
Error: Couldn't connect to daemon: 127.0.0.1:18081

When I run monerod.exe, it creates new mdb-file on disk C:\ (although all exe-files placed on other disk) and tries to load blockchain at height 0!

**Comment by selsta** [comment]
Did you force shutdown during sync? If yes it likely means your blockchain is corrupted. You have to delete it any resync from scratch.

**Comment by selsta** [comment]
> My HDD can to write 160MB/s, my 5G-Wi-Fi can to download 20MB/s, but the blockchain was downloaded average on ~100KB/s.

Your download speed is mostly irrelevant because it's not the bottleneck, you don't just download but also simultanouly verify the blockchain. This is the resource intensive part that requires a disk with fast random IO speeds. SSDs are ideal for this, a HDD will be slow.

**Comment by selsta** [comment]
> I thought that blockchain has structure as BLOCK_1-NONSE_1-BLOCK_2-NONSE_2..., where SHA256 after each nonse lower some value. This file could be trimmed to the last NONSE...

What you are describing is a simplified conceptual data structure for a blockchain, in real-world applications this is more complex.

We use LMDB (B-tree internally) to store the blockchain data. It's simply not possible to cut the database file like you are suggesting.

**Comment by MoneroArbo** [comment]
A useful flag here might be might be:

`--block-sync-size=x`

where x is the number of blocks to write to disk at once. Default is only 100, but even with full blocks setting it to 500 would only be 150 MB sync'd at a time.

I think you can do something similar but measured in bytes with something like:

`--db-sync-mode=safe:sync:250000000bytes`

250000000 bytes (~250 MB) is the default here so I'm not 100% how it relates to the block-sync-size, if it just uses whichever number is smaller, or if these are in fact slightly different settings.

Anyway, playing around with these settings *may* help with HDD syncing speed
