### ISSUE TITLE
Add a cap to the supply

### ISSUE THREAD

**Issue by FU3X** [monero-project/monero#9083]
All it is, is beneficial, maybe next hardfork, limit the supply to prevent the coin from losing its value? like, the blockchain size for a monero node will get super big anyway and may come to an end one day, why not just have halves to half until that day comes. 
if you disagree with me, bring it on im open to debates

**Comment by nahuhh** [comment]
wontfix

You're welcome to cont convo here:
[ofrnxmr on matrix](https://matrix.to/#/@ofrnxmr:monero.social)

or here:
[monero-offtopic](https://matrix.to/#/!qqRhJzAUfTJRpMHqIP:matrix.org?via=monero.social&via=matrix.org&via=tchncs.de)

thanks

**Comment by selsta** [comment]
Changing the supply for the sake of manipulating the price is one of those things that is not up for debate.

**Comment by FU3X** [comment]
> Changing the supply for the sake of manipulating the price is one of those things that is not up for debate.

infinite supply is even worse

**Comment by nahuhh** [comment]
I directed you to the appropriate channels for discussion. 

this issue is closed.
