### ISSUE TITLE
Slow synchronization for 'today'-created wallet.

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9085]
I created today new wallet and sent to it some moneros. After I created onlyview-wallet on monero-gui for today date and now try to synchronize via remote daemon (node in Switzerland; I am in Siberia, Russia). But it needs 2 hours! I repeat, the first transaction of wallet was today. Other wallets on Android worked much faster.
The synchronization was fast, but the passage through the blocks is very slow.
![image](https://github.com/monero-project/monero/assets/106807841/686eaffb-3251-4732-af08-691d572d41ae)

**Comment by selsta** [comment]
can you go to Settings -> Info and share what value your wallet restore height has?

**Comment by developergames2d** [comment]
> can you go to Settings -> Info and share what value your wallet restore height has?

1514158

**Comment by selsta** [comment]
Is this a mainnet wallet? The block height should be around 3000000 if you entered the current date correctly.

**Comment by developergames2d** [comment]
> Is this a mainnet wallet? The block height should be around 3000000 if you entered the current date correctly.

I entered 2023-12-15 (ГГГГ-ММ-ДД).
I changed to 3040000, but passage through the blocks is still slow (1-2 thousands per minute for 41000).

**Comment by selsta** [comment]
Can you share which remote node you use? Then I can check the speed I have with it.

**Comment by developergames2d** [comment]
> Can you share which remote node you use? Then I can check the speed I have with it.

178.22.107.109:18081

**Comment by selsta** [comment]
I don't think there is a bug here, maybe a node closer to you will result in faster sync.
