### ISSUE TITLE
Can't to submit transaction from only-view wallet!

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9086]
I use remote node from Iran. But I can't to submit new transaction from only-view wallet!
When I click on button "Дополнительные настройки" (Additional settings) nothing happens!
![image](https://github.com/monero-project/monero/assets/106807841/c48bdb5c-4ba4-4827-98de-2a446b702c60)

**Comment by selsta** [comment]
You can't send a transaction from view only wallets directly, you need offline transaction signing setup: https://monerodocs.org/cold-storage/offline-transaction-signing/

**Comment by developergames2d** [comment]
> You can't send a transaction from view only wallets directly, you need offline transaction signing setup: https://monerodocs.org/cold-storage/offline-transaction-signing/

I want to see this:
![image](https://github.com/monero-project/monero/assets/106807841/c6d6dcd4-ee59-4ecd-95c5-f40e282765c1)

**Comment by selsta** [comment]
On my system this shows up when clicking where the red arrow is. Does it not work for you? Can you try switching to English temporarily and see if it works?
