### ISSUE TITLE
Problem with broadcasting SECOND out transaction

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9087]
I use monero-gui. When I sent first out transaction after offline signing, all was ok with the exception of error-message (but moneros was send). But when I try to create, offline-sign second output transaction from the same wallet, creating and offline signing was ok, but after trying broadcast I have error message like "double spending" and moneros didn't go to output wallet. I am sure I have selected a new transaction file (they were marked as 1 and 2).

**Comment by selsta** [comment]
> exception of error-message

What did the error message say?

Did you export / import outputs and key images first before creating the second transaction?

**Comment by developergames2d** [comment]
> > exception of error-message
> 
> What did the error message say?
> 
> Did you export / import outputs and key images first before creating the second transaction?

No, don't import because it didn't need for the first transaction...

**Comment by selsta** [comment]
It needs it for the second transaction, otherwise it will try to double spend the same outputs.

**Comment by selsta** [comment]
Also reminder that you have to set your remote node as trusted in Settings -> Node to import outputs.
