### ISSUE TITLE
Can I to see balance after out transaction after creating only-view wallet? 

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9088]
Can I to see balance after out transaction after creating only-view wallet on monero-gui? I notice that Monerujo on Android can to see my "change" value after the outgoing transaction.
I didn't set seed on Monerujo.

**Comment by selsta** [comment]
You have to import key images to get the correct balance in your view only wallet.

**Comment by developergames2d** [comment]
> You have to import key images to get the correct balance in your view only wallet.

Is it safe? I don't want to move private send key or seed on online computer with only-view wallet.

**Comment by selsta** [comment]
Your seed should not be entered on an online computer, that's why you have to exchange key images and outputs between the offline wallet and the view only wallet.

Did you read this? It explains the concept: https://monerodocs.org/cold-storage/offline-transaction-signing/
