### ISSUE TITLE
Is there a simple algorithm to convert Height <-> Date?

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9094]
Is there a simple algorithm to convert BlockHeight <-> BlockDate?

**Comment by hyc** [comment]
Converting height to date is trivial, just read the timestamp in the block.

Converting date to height takes more work, you can use wallet/wallet2.cpp:get_blockchain_height_by_date().

**Comment by selsta** [comment]
https://github.com/monero-project/monero-gui/blob/master/js/Wizard.js#L134

Here is an algorithm for date to height.
