### ISSUE TITLE
Incorrect getting block height from date

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9098]
I restored my wallet from date 2023-12-01, but monero-gui sets height ~1'500'000, while real height is ~3'032'307.
I used formula:
1'009'827 + get_difference_days(2016.03.23, 2023.12.01) * 720.

**Comment by selsta** [comment]
Do you have the GUI set to stagenet?

**Comment by developergames2d** [comment]
> Do you have the GUI set to stagenet?

I use usual monero-wallet-gui.exe

**Comment by developergames2d** [comment]
> Do you have the GUI set to stagenet?

I restored from SEED and date.

**Comment by selsta** [comment]
Yes, but do you have monero-wallet-gui set to Stagenet mode?

**Comment by developergames2d** [comment]
> Yes, but do you have monero-wallet-gui set to Stagenet mode?

How can I check it? I just run monero-wallet-gui.exe

**Comment by selsta** [comment]
When you open the GUI click on Advanced settings in the main menu and then there's a selection for Mainnet, Stagenet and Testnet.

**Comment by developergames2d** [comment]
> When you open the GUI click on Advanced settings in the main menu and then there's a selection for Mainnet, Stagenet and Testnet.

When I use Stagenet, I show not my wallet, with other addresses.

**Comment by developergames2d** [comment]
When I try to restore from height 3030000, all is OK.
