### ISSUE TITLE
Trezor hardware wallet balance issue

### ISSUE THREAD

**Issue by FU3X** [monero-project/monero#9099]
Trezor balance issue
- Creates Trezor wallet
- Creates view only wallet for computer and phone
- Receives $300
- Sends $15
- ($285 is the change between the two)

Now on all my view only wallets, even if I recreate them, rescan and refresh them, the balance is always wrong, however when I connect to the wallet on Trezor directly balances show fine.

Heres the point of view on the view only wallet(s):
- Shows 2 transactions (Received and received, instead of received then sent)
- Received $300, received $285
- Total balance $585

Now this is the POV of Directly connecting using the Trezor:
- Received $300, sent $15
- Total balance $285

**Comment by vtnerd** [comment]
A view-only wallet cannot detect the "real" spends because it lacks the spend key needed to compute the key-image. So this is a known-issue, and really cannot be fixed until the Seraphis update.

**Comment by selsta** [comment]
Please read up on how view-only wallets work: https://www.getmonero.org/resources/user-guides/view_only.html
