### ISSUE TITLE
Bug with input-transaction

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9102]
I got moneros to #2-address, but monero-gui writes #0.
![image](https://github.com/monero-project/monero/assets/106807841/ad1853d9-93d8-452c-a692-c4893bdd69e9)

**Comment by developergames2d** [comment]
Maybe it #0-subaddress...

**Comment by selsta** [comment]
Please open GUI related issues here: https://github.com/monero-project/monero-gui/issues

Regarding your question, you have account 2 selected and you receives funds in subaddress 0.

Each account has its own list of subaddresses.
