### ISSUE TITLE
Mining on cutted blockchain

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9107]
Can I to mine moneros on cutted blockchain in monero-gui? How weights this cutted blockchain now?

**Comment by selsta** [comment]
I don't know what a cutted blockchain is. If you mean pruned, yes you can mine with a pruned blockchain, it works exactly the same as with an unpruned blockchain.

**Comment by developergames2d** [comment]
> I don't know what a cutted blockchain is. If you mean pruned, yes you can mine with a pruned blockchain, it works exactly the same as with an unpruned blockchain.

Thanks
