### ISSUE TITLE
Synchronization on my SSD-blockchain

### ISSUE THREAD

**Issue by developergames2d** [monero-project/monero#9108]
If I download full blockchain on my SSD, will be the synchronization **FROM BLOCK WITH HEIGHT 0** very fast (on local demon)? Now I wait many hours (with remote demon node).

**Comment by selsta** [comment]
Please don't use GitHub to ask basic questions, this is a issue tracker. There are other places for this, like Matrix / IRC monero chat.

To answer your question, syncing with an SSD will take approximately 12-24h.

**Comment by selsta** [comment]
If you mean wallet syncrhonization, yes it will also be faster than using a remote node. But it won't be instantly, it will likely take a bit less than an hour.
