### ISSUE TITLE
any fixes, (monorod won't start or is missing)

### ISSUE THREAD

**Issue by kcid123** [monero-project/monero#9112]
Please anything helps
![2024-01-04](https://github.com/monero-project/monero/assets/155665988/0c5d4bf0-dda8-44bf-8298-d33d87c453c0)

**Comment by selsta** [comment]
Did your anti virus delete monerod.exe?

**Comment by JacksonZ03** [comment]
what does the log say?

**Comment by 0xFFFC0000** [comment]
The picture you posted just says the monerod.exe executable file is missing/removed. As @selsta mentioned please check anti-virus.

**Comment by plowsof** [comment]
Please read this comment (how/why you need to add an exclusion folder) https://monero.stackexchange.com/a/10799

Antoviruses  would rather you downloaded the ZIP instead of the installer exe and extracted it inside of an'excluded folder'.

**Comment by kcid123** [comment]
> Please read this comment (how/why you need to add an exclusion folder) https://monero.stackexchange.com/a/10799
> 
> Antoviruses would rather you downloaded the ZIP instead of the installer exe and extracted it inside of an'excluded folder'.

Thank you I'm gonna try that.

**Comment by kcid123** [comment]
> The picture you posted just says the monerod.exe executable file is missing/removed. As @selsta mentioned please check anti-virus.

do you know how I can do that?

**Comment by kcid123** [comment]
> what does the log say?

Where do I check for the log?

**Comment by kcid123** [comment]
> Please read this comment (how/why you need to add an exclusion folder) https://monero.stackexchange.com/a/10799
> 
> Antoviruses would rather you downloaded the ZIP instead of the installer exe and extracted it inside of an'excluded folder'.

Its useless stupid admin access is needed i'm prob gonna use the online version or something no clue if that's worse or what i can do but yeah.

**Comment by selsta** [comment]
Your anti-virus is deleting monerod.exe – this is out of our control. If you don't have admin access to add an exception then for example try Feather Wallet which uses a remote node automatically.
