### ISSUE TITLE
Is https://unstoppableswap.net/ reliable ? 

### ISSUE THREAD

**Issue by flopi123** [monero-project/monero#9118]
Hello, 
I was wondering whether the software from https://unstoppableswap.net/ was reliable or not to swap Bitcoin for Monero, and if so, if you know how much they charge for swaps ? I am looking for the cheapest non KYC exchange option. 
Thank you in advance !

**Comment by selsta** [comment]
Please ask on Reddit or Matrix: https://www.getmonero.org/community/hangouts/

This here is an issue tracker for the monero codebase itself, not for third party software or services.
