### ISSUE TITLE
Feature request: option to turn off simplewallet logging

### ISSUE THREAD

**Issue by mmortal03** [monero-project/monero#913]
With Monero being considered a privacy-centric cryptocurrency, there should be an option to disable simplewallet's logging completely.  Maybe --log-level -1 or something, such that no transaction data or even public addresses are logged? The less information that is left around in plain text the better when wanting to avoid any privacy concerns.

**Comment by moneromooo-monero** [comment]
There's a vague plan to replace the whole logging infrastructure in the near/medium future, which this will likely be part of.

**Comment by grummerd** [comment]
--log-level=false

or

--log-level=0

**Comment by mmortal03** [comment]
grummerd, I tested --log-level=0, and it did not turn off logging. I did not test --log-level=false.

**Comment by iamsmooth** [comment]
--log-file nul (windows) or --log-file /dev/null (linux)

Have not tested

**Comment by mmortal03** [comment]
I just tested --log-level=false, and that doesn't work.

I next tested --log-file nul, and that works, both for simplewallet and bitmonerod.

I noticed that bitmonerod still creates an empty folder structure, though, called "log\dr-monero\net"

Anyway, I'll close this, as this is a sufficient workaround.

**Comment by grummerd** [comment]
it's not sufficient until it's well documented. Has the documentation been updated?
