### ISSUE TITLE
wallet2.cpp-3e34503d.o.tmp infected with malware

### ISSUE THREAD

**Issue by sandytrevor** [monero-project/monero#9153]
Tried to compile release-v0.18 on macOS Sonoma, but Avast found MacOS:Miner-GP[PUP] in wallet2.cpp-3e34503d.o.tmp.  Should I be using a different release, or is this a false threat by Avast?

**Comment by selsta** [comment]
The wallet contains miner code and that's why Avast is complaining, you can ignore it. Not malware.

**Comment by sandytrevor** [comment]
Thanks!

 

From: selsta ***@***.***>
Reply-To: monero-project/monero ***@***.***>
Date: Monday, February 5, 2024 at 10:24 PM
To: monero-project/monero ***@***.***>
Cc: sandytrevor ***@***.***>, Author ***@***.***>
Subject: Re: [monero-project/monero] wallet2.cpp-3e34503d.o.tmp infected with malware (Issue #9153)

 

The wallet contains miner code and that's why Avast is complaining, you can ignore it. Not malware.
