### ISSUE TITLE
monero-wallet-rpc can't work via socks5

### ISSUE THREAD

**Issue by longnetwork** [monero-project/monero#9177]
I use the --proxy option to specify a local proxy. My proxy responds with an error that version 4 for socks is not correct.
full run command monero-wallet-rpc:
`monero-wallet-rpc --log-level 0 --trusted-daemon --daemon-ssl autodetect --daemon-ssl-allow-any-cert --max-concurrency 6 --non-interactive --disable-rpc-login --rpc-bind-port {{RPC_WALLET_PORT}} --rpc-bind-ip 127.0.0.1 --disable-rpc-ban --wallet-dir {{WALLET_DIR}} --proxy 127.0.0.1:{{SOCKS5_PORT}}`

**monero-wallet-rpc** does not support socks5

**Comment by vtnerd** [comment]
This is a duplicate of #8562

**Comment by vtnerd** [comment]
@selsta I don't think this is completed, but we definitely don't need two bug reports for this.

**Comment by vtnerd** [comment]
Nevermind, I see you added the `duplicate` label also.
