### ISSUE TITLE
Add more zmq features

### ISSUE THREAD

**Issue by Codi33** [monero-project/monero#9192]
Need more features in ZMQ to accept real-time payments.
Could be implemented using RPC but long polling is needed.
The information provided by txpool_add and chain_main events
is insufficient for verification.

**Comment by vtnerd** [comment]
Perhaps [LWS](https://github.com/vtnerd/monero-lws) will meet your needs? It has _receive_ notifications via Webhooks/ZMQ per monero address, and optionally per integrated address. There is also ZMQ notification on new address creation.

There is some [rough documentation](https://github.com/vtnerd/monero-lws/blob/master/docs/zmq.md) on LWS ZMQ usage.

**Comment by vtnerd** [comment]
If you have further questions about LWS, I recommend opening an issue on LWS project page to track the discussion. Otherwise, it is unlikely that `monerod` will use ZMQ for real-time payments (because it is not designed to track user funds, which is different than `bitcoind` for instance).

**Comment by Codi33** [comment]
Thank you for answering my question! Your project is good solution for what I need.
