### ISSUE TITLE
Add ability to create wallets through rpcwallet

### ISSUE THREAD

**Issue by Jojatekok** [monero-project/monero#92]

**Comment by hyc** [comment]
I may work on this. I suggest:
monero-wallet-rpc takes a commandline arg "--wallet-dir" to specify where newly created wallets will live.

createwallet RPC takes 3 params - simple filename, seed language, and password.

This probably also means we should have an RPC to return the list of supported seed languages.

This also would seem to require TLS if talking to a remote wallet.
