### ISSUE TITLE
`prune_blockchain` cause entire node to hang on

### ISSUE THREAD

**Issue by SyntheticBird45** [monero-project/monero#9209]
**Monero v0.18.3.1 syncing 99%, Linux 6.7 x86_64**

`prune_blockchain` rpc methods cause node to hang on and don't react to SIGTERM. Killing process is the only solution.
The bug is consistent

**Comment by SyntheticBird45** [comment]
command used for rpc:
```
curl http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"prune_blockchain","params":{"check":true}}' -H 'Content-Type: application/json'
```

**Comment by SyntheticBird45** [comment]
I waited 30 minute. node is already pruned and since i set `check: true` It shouldn't even trigger the pruning process

**Comment by SyntheticBird45** [comment]
Issue is still happening when node is fully synced

**Comment by selsta** [comment]
does entering `check_blockchain_pruning` in monerod also not work?

**Comment by SyntheticBird45** [comment]
Yes

**Comment by SyntheticBird45** [comment]
Just tested if it wasn't alacritty or terminal emulator causing issue but it is consistent across 3 other terminals.

**Comment by SyntheticBird45** [comment]
Disk read I/O is increasing while hanging so it might be stuck at interacting with the database. I maybe stupid but is the `prune_blockchain` rpc command check the pruning state over all the database ?

**Comment by selsta** [comment]
Do you have an SSD or HDD? Running `check_blockchain_pruning` took about 5 minutes on my system with SSD.

moneromooo said it reads all tx data so it can be lengthy

**Comment by SyntheticBird45** [comment]
I've an SSD, however the filesystem is almost at capacity.

**Comment by SyntheticBird45** [comment]
Looking at my I/O Read rate monerod will have finish to check in 1 hour. I believed that monerod didn't checked the all database for pruning state. If the hanging of monerod is something known during the check of the prune worker, I believe we can close this issue.
