### ISSUE TITLE
[Enhancement] Stealth Wallets

### ISSUE THREAD

**Issue by livinginformation** [monero-project/monero#921]
I've considered (starting) implementing a Trezor-style wallet scheme for simplewallet, where your actual privkey is derived from both the privkey in your wallet and the password you enter when loading it. This would allow for plausible deniability with regards to how much funds are actually contained within your wallet, as multiple different passwords can potentially lead to multiple different accounts. 

The caveat here is that you would need to rescan the blockchain whenever you load a stealth account, because any remnants on-disk of your stealth accounts would inform an adversary of their existence (and quite possibly their quantity). I don't think this is much of a problem though, as someone using stealth accounts could very easily use the base wallet for a hot wallet, and occasionally top it off from one of their stealth (cold) accounts.

**Comment by livinginformation** [comment]
As far as storing the wallet's historical transactions on-disk such that the blockchain wouldn't need to be rescanned, and the user _also_ has plausible deniability:  I have a few ideas on how we could do it, but it would be complicated. In effect, there would be a single fixed-size file on disk, where the size is chosen by the user, and a larger size means more plausible deniability. 

For each password, the file would store the block heights containing your historical transactions, as well as the last height that your wallet synced.  Then, an encryption scheme is performed such that when each password is used individually, the history file is decrypted to display only the history related to that password, where the rest is junk data. Truecrypt uses this style of encryption with their 'Hidden Volumes', so I know that it's not impossible to do. If someone with a better grasp on the cryptography involved could tell me whether this is possible for an arbitrary number of stealth wallets, I would appreciate your insight here.

**Comment by expez** [comment]
If they know someone has sent you money using `$address` will this pass the test of sending a token amount to `$address` and seeing if it really shows up in the (fake) wallet you're claming is the real one?

**Comment by livinginformation** [comment]
It will not. If someone can associate a public address with you (say a withdrawal from an exchange on which your identity is verified), and then later, you're asked to prove that the address you withdrew to is derived from your (fake) wallet, you would be unable to provide that proof without revealing your stealth wallet. If you want plausible deniability, you would need to use your (fake) wallet as the intermediary, and transfer the funds from there to their final destination in the stealth wallet. So long as there isn't proof that the address you sent to is one under your control, plausible deniability is retained. Withdrawing slowly over time as opposed to a lump sum could also add more plausible deniability.

**Comment by ChristopherKing42** [comment]
This technically can be done at the file system level, I believe. Run True crypt, give each wallet a different hidden volume. The only question is if monero integration could make it more efficient (store the block chain once, and each hidden volume stores where in the block chain it's funds are).

**Comment by moneromooo-monero** [comment]
A similar thing: https://github.com/monero-project/monero/pull/2257

**Comment by JollyMort** [comment]
>The caveat here is that you would need to rescan the blockchain whenever you load a stealth account

You can address that: if you do sweep_all to yourself and remember the height, you don't need to scan from scratch, but just from that height. You will not see the history, but what do you care - you got all your money in the last TX =)

**Comment by moneromooo-monero** [comment]
+resolved
