### ISSUE TITLE
Update check: no update available 

### ISSUE THREAD

**Issue by C20-H25-N3O** [monero-project/monero#9249]
I tried to download the new version Via Monero Cli command. In monerod.exe
I have 0.18.3.1 

I want update to 0.18.3.2

When trying command: update check/download
I get: No update available

**Comment by C20-H25-N3O** [comment]
@0xFFFC0000 what information do you need?

**Comment by selsta** [comment]
We haven't updated the DNS records for v0.18.3.2 yet. Once this is done it should notify you about a new version being available, though I'm not sure if you can download it with monerod.

I'd recommend to download from the website.
