### ISSUE TITLE
monerod broken after latest update

### ISSUE THREAD

**Issue by Jayd603** [monero-project/monero#9250]
It has trouble getting caught up and was stuck syncing.  I Deleted the entire monero_data directory and had it re-sync the entire blockchain, it is still getting stuck on more recent blocks and not finishing sync.

Height: 3098510/3104955 (99.8%)

**Comment by selsta** [comment]
What kind of hardware are you using? Where is your blockchain stored? How long did you wait?

**Comment by Jayd603** [comment]
Ubuntu server, it's in a docker image , I used the same build commands as the previous build.  It uses an SSD array on the backend.  I waited many hours after it stopped at 99.8%

**Comment by selsta** [comment]
How much resources did you give the docker container?

**Comment by Jayd603** [comment]
It has no restrictions.  The version it downloaded was 18.3.3 , site says 18.3.2 is latest but i'm assuming someone snuck out 18.3.3 after.

**Comment by Jayd603** [comment]
I'll try building the older version again for now

**Comment by Jayd603** [comment]
> If you let it run for 10 minutes, does it stay at `3098510` exactly?
> 
> Also can you share the output of `sync_info` and `status`?

It stays at the exact block, even after restart, I'm trying 18.3.1 now just to see if ti works, i can switch back and trouble shoot later just don't have enough time at the moment.

**Comment by selsta** [comment]
I don't think this will help but try adding `--block-sync-size 10`.

**Comment by R-Caser** [comment]
try the option 
--db-sync-mode safe

**Comment by Jayd603** [comment]
It's pausing when getting to the later blocks, this time it paused at Height: 3098624/3105618 (99.8%).  This happens with every version now.   This was a very busy public node now it's dead.

**Comment by selsta** [comment]
Do you have public RPC access enabled? If yes, disable it first until you are fully synced up.

**Comment by Jayd603** [comment]
> Do you have public RPC access enabled? If yes, disable it first until you are fully synced up.

Ok, I'm trying that,

**Comment by glv2** [comment]
@Jayd603 I have a node that had difficulties syncing because it had a slow network connection (around 400 kB/s download speed). It got stuck into a loop:
 1- connect to new peer
 2- start downloading block range from peer
 3- download fails because of timeout
 4- peer blocked
 5- back to step 1

If this is what is happening to your daemon, there should be many "Peer a.b.c.d blocked' messages in the logs.

**Comment by Jayd603** [comment]
Same thing -2024-03-16 13:40:16.026	I [77.183.126.48:18080 OUT] Sync data returned a new top block candidate: 3098624 -> 3106351 [Your node is 7727 blocks (10.7 days) behind]

Stuck there, once it gets to the newer blocks it hangs.  I can't seem to prevent this.

@glv2 this is my speed test result, the connectivity is very fast:
Idle Latency:     2.25 ms   (jitter: 0.09ms, low: 2.23ms, high: 2.41ms)
    Download:  4658.19 Mbps (data used: 5.0 GB)                                                   
                  2.38 ms   (jitter: 0.40ms, low: 2.00ms, high: 7.29ms)
      Upload:  4283.99 Mbps (data used: 3.0 GB)                                                   
                  2.39 ms   (jitter: 0.27ms, low: 2.04ms, high: 4.10ms)
 Packet Loss:     0.0%

**Comment by selsta** [comment]
Please try starting `monerod` without any configuration options.

**Comment by Jayd603** [comment]
Starting with the minimun of: monerod --non-interactive --data-dir=/mnt/monero_data --restricted-rpc --rpc-bind-ip=0.0.0.0 --confirm-external-bind --public-node

..seems to have allowed syncing to resume.  The defaults are an issue though since this node normally has thousands of connections.  I did tuning options to get it to perform better.  I'll try slowly adding some back that impact performance of users

**Comment by selsta** [comment]
I think you set a too high `--block-sync-size` value. Keep it at default. It has no impact on performance once you are fully synced up, so you don't have to re-add it.

**Comment by selsta** [comment]
Also I would recommend to not enable public node access until you are fully synced up.

**Comment by Jayd603** [comment]
> Also I would recommend to not enable public node access until you are fully synced up.

Right, public access wasn't enabled, it wasnt forwarded by Docker.

**Comment by Jayd603** [comment]
So far it seems it may have been the block sync size of 100, even though it works up until the latest blocks and has always worked in the past.   This is probably a bug.

**Comment by selsta** [comment]
If you set such a high block-sync-size it can happen that you request too much data from other nodes, which causes them to drop or not reply to you.

**Comment by Jayd603** [comment]
> If you set such a high block-sync-size it can happen that you request too much data from other nodes in a single request, which causes them to drop or not reply to you.

Ok, I'll look out for this when doing a full sync next time, maybe i'll try 50.

**Comment by Jayd603** [comment]
New bug?
2024-03-18 03:05:00.689	I [165.22.2.201:53552 INC] Sync data returned a new top block candidate: 3107490 -> 4613133 [Your node is 1505643 blocks (5.7 years) behind]

Except when I connect with my client, it's the latest block?

**Comment by Jayd603** [comment]
> It's not a bug, it's someone sending invalid data. You can apply my block list which has most of these peers included: https://gui.xmr.pm/files/block.txt
> 
> You don't have the apply the block list, it's just a harmless log message.

Oh ok, that makes sense.  Everything seems to be running fine then.  Thanks for the help.

**Comment by selsta** [comment]
Closing this as there doesn't seem to be a bug here introduced in the latest version.
