### ISSUE TITLE
How to open ledger wallet in Monero Cli 

### ISSUE THREAD

**Issue by GpStop** [monero-project/monero#9256]
I would like some help please.
I download cli and i download the monerod, so i'm all sync.
when i started the cli wallet wanted from me to create wallet and i did.
Now i want to put my ledger wallet in the system, not the one who created with monero cli wallet by default.
what commands to use to do that? i want to use my ledger wallet not the default one.
How to do it?

**Comment by plowsof** [comment]
https://www.getmonero.org/resources/user-guides/ledger-wallet-cli.html

**Comment by GpStop** [comment]
> https://www.getmonero.org/resources/user-guides/ledger-wallet-cli.html

thanks man for the information.
