### ISSUE TITLE
Currently unable to restore wallet even with seedphrase

### ISSUE THREAD

**Issue by randomaccountlookingforsolutions** [monero-project/monero#9264]
Here is the error i am getting even when using the correct (triple-checked) 25-word seed phrase to restore monero wallet, if someone could please help look into this:

'WalletRestoreFromSeedException'
#0      restoreWalletFromSeedSync (package:cw_monero/api/wallet_manager.dart:101)
#1      _restoreFromSeed (package:cw_monero/api/wallet_manager.dart:176)
#2      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#3      _RemoteRunner._run (dart:isolate:1090)
#4      _RemoteRunner._remoteExecute (dart:isolate:1084)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by selsta** [comment]
Can you restore that seed with monero-wallet-cli? If not, what error message does it show.

**Comment by randomaccountlookingforsolutions** [comment]
Hi selsta and thank you so much for such a prompt response. I have already posted the error at the post you have responded to. It is the entire error log. 'WalletRestoreFromSeedException'
I am using Stack Wallet by CypherStack for iOS 
I do not have monero-wallet-cli at the moment. I am relatively new to monero, but I can try and learn. I will look into it and try to get back to you.

**Comment by randomaccountlookingforsolutions** [comment]
Hi selsta:
I learned (as much as I reasonably could in a short amount of time) on how to use a monero-wallet-cli for macbook, and I tried to restore xmr wallet there using 25 word seedphrase.
And it gave this error:
"Electrum-style word-list failed verification."

**Comment by selsta** [comment]
It means the seed is invalid. Is it possible you wrote it down incorrectly?

**Comment by randomaccountlookingforsolutions** [comment]
Hi selsta:
As I have stated in my previous post, i have triple-checked the 25 word seedphrase, and also made sure each word was valid in the blobmaster github for monero here: https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h 

But yes, even after triple-checking I admit it is still possible, that maybe the order that I have them in may be incorrect. It is also a possibility that even though all 25 words are valid, that the order they are in may be inaccurate. I might just attempt to change the combinations and try restoring the wallet successfully that way. Regardless, thank you for your attempt at helping me, selsta. I will close the issue.

**Comment by selsta** [comment]
The order of words is important.

Here is a list of English words, make sure that all words are in this list: https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h

**Comment by randomaccountlookingforsolutions** [comment]
Hi selsta,
 
I have great news! I finally figured out the issue. I confused one of the words with another word, even though both were valid in the master mnemonic list! So it turns out i copied a different similar correctly spelled word with another. I have now restored my monero xmr wallet. THANK YOU!

**Comment by selsta** [comment]
Glad you were able to resolve it!
