### ISSUE TITLE
cant find coins on trezor after monero gui update

### ISSUE THREAD

**Issue by ofiryy** [monero-project/monero#9276]
i had monero gui from 2 years ago, so i uninstalled it,
and installed the lated version  0.18.3.3,
i accessed the gui and restored from trezor device,
now i see all the coins are gone, the balance is 0.
could i have created by aacident a new monero wallet from trezor?
what can i do to access the old coins?

**Comment by selsta** [comment]
Do you still have the old wallet file?

What does it say inside Settings -> Info -> Wallet restore height?

**Comment by ofiryy** [comment]
i dont think i have any old file, i uninstalled the old gui, and also manually deleted its directory,
i wanted to start fresh with the latest monero gui.
the wallet restore hight is 1.  i use remote node

**Comment by selsta** [comment]
What does it say in Settings -> Info -> Wallet mode?

What does it say in the bottom left corner? Wallet is synchronized or is it still syncing?

**Comment by ofiryy** [comment]
wallet mode is advanced mode (remote node)
wallet still syncing

**Comment by selsta** [comment]
You have to let the wallet finish syncing first before the funds show up.

**Comment by ofiryy** [comment]
i use node.moneroworld.com:18089 
is it ok?
how much time should it take ?

**Comment by selsta** [comment]
If it syncs blocks then the node is ok. I don't know how long it will take, it depends on your internet speed, your CPU, the speed of the node, etc.

In the future it would be better to set a restore height that is higher than 1 but still lower than your first received transactions to speed up the process.

**Comment by ofiryy** [comment]
can i change the restore height while it is suncronizing ?

**Comment by selsta** [comment]
In theory yes, but it would be best to just let it sync now before you enter a wrong restore height.

**Comment by ofiryy** [comment]
the remote node has finished syncronizing and still i see 0 in balance,
so i switched to local node, network status is connected, ans still 0 balance.
i had changed the resore hight to a date 2021-04-04, could it be the problem ?

**Comment by selsta** [comment]
Please stay on remote node, you don't have a synced local node so use remote node instead.

>i had changed the resore hight to a date 2021-04-04, could it be the problem ?

What does it say under Settings -> Info -> Restore height? Share the exact value.

**Comment by ofiryy** [comment]
Wallet restore height: 2311108

**Comment by ofiryy** [comment]
i did not setup any passphrase. not before and not now.
with the remote node - it finished syncronizing, i mean, the "Syncronizing" was replaced with "Remote node",
so i understood from this that it finished syncronizing (btw at that point the Wallet restore height was: 2311108) 
and i still had only 0 funds.
but after  the "Syncronizing" was replaced with "Remote node", i dont know to say how many blocks were remaining.

**Comment by ofiryy** [comment]
now, with local node, after hours of syncronizing, i have the "Connected" status,
and still 0 funds.
what can i do to access my funds ?

**Comment by selsta** [comment]
@ofiryy  go to Settings -> Log, type "status" into the textbox and post the output here.

**Comment by ofiryy** [comment]
i found the funds! 
i just needed to "open wallet from file" and then go the first wallet. i had like 3 wallets there, the 3rd one i created yesterday, because i didnt know it actually kept some files from the old wallet, i didnt know it works like that.
so i send some funds to another address- and complete the approvel process on trezor - it went well,
but it seems stuck on "Sending transaction..."
what do you think is the issue ?
thanks

**Comment by selsta** [comment]
Please do what I suggested in my last comment.

**Comment by selsta** [comment]
> Height: 3120194, target: 3120202 (99.9997%)

It has to be at 100% for everything to work correctly.

**Comment by ofiryy** [comment]
now i confirmd that it was 100%, and the transaction still get stuck....

**Comment by selsta** [comment]
I'm confused how you were even able to create that transaction because as long as your node isn't at 100% you can't create one. Did you switch to a remote node for it?

> now i confirmd that it was 100%

Get the transaction ID, go to Settings -> Log and enter

relay_tx txid

with txid being your transaction id.

**Comment by ofiryy** [comment]
its so weird,  i let the trasaction be stuck for like 15 min, and now i see that it succeeded, i see the funds in the target adress, but the gui is still stuck.

i would send you the log you asked, but i dont have the transaction id.
this wallet need some work to be more stable - but your support is fantastic,
thank you very much
