### ISSUE TITLE
Funds are blocked every time I send them with RPC Wallet

### ISSUE THREAD

**Issue by maksemen2** [monero-project/monero#9283]
```
>> wallet.balance(unlocked=True) # 0.49
>> wallet.transfer(<address>, 0.03)
>> wallet.balance(unlocked=True) # 0
>> wallet.balance(unlocked=False) # 0.46
```

Why does it happen and how to deal with it?

**Comment by selsta** [comment]
Please see https://monero.stackexchange.com/a/12781 and https://monero.stackexchange.com/questions/2783/what-is-the-purpose-of-locked-balance
