### ISSUE TITLE
tx_memory_pool is now private in master.

### ISSUE THREAD

**Issue by minerjed** [monero-project/monero#9284]
This is more of a question.  It looks like in the master branch the tx_memory_pool in cryptonote_core has been moved to the private section in master but in v0.18 it is public. I tried to find a pull request referencing this change but can't seem to find one.  Could you tell me what pull request this is related to?  This change breaks the compile for the Monero onion explorer. Thanks.

**Comment by selsta** [comment]
https://github.com/monero-project/monero/pull/8924

**Comment by minerjed** [comment]
Thanks
