### ISSUE TITLE
Hide the sending address and prompt that destinations do not exist

### ISSUE THREAD

**Issue by imaiops** [monero-project/monero#9301]
I use the get_transfer_by_txid method to query the transaction details, and the response I get does not have the destinations field.

**Comment by selsta** [comment]
Can you add more information to what you are asking/suggesting?

**Comment by imaiops** [comment]
> Can you add more information to what you are asking/suggesting?

I use the get_transfer_by_txid method to query the transaction details, and the response I get does not have the destinations field.
![1](https://github.com/monero-project/monero/assets/21233395/45da2491-2b02-49cb-abcc-34d198f98b34)

**Comment by imaiops** [comment]
> Did you rescan your wallet? Is this a multisig wallet?
Yes, Not multisig.

**Comment by selsta** [comment]
Does the receipient show up when you submit a transaction and not rescan the wallet?

**Comment by selsta** [comment]
Closing due to lack of reply.
