### ISSUE TITLE
Remove refresh from call from import_multisig

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#9312]
This issue requests removing the `refresh` call from wallet2's `import_multisig` if possible:

https://github.com/monero-project/monero/blob/c8214782fb2a769c57382a999eaf099691c836e7/src/wallet/wallet2.cpp#L13892

Refreshing is a relatively expensive operation which can take considerable time, especially over tor, and the wallet should be refreshing periodically anyway, so it could make most sense to remove this call.

Otherwise I observe this call hanging on the tor network and even timing out when it may not be necessary at all.

For comparison, refresh isn't called when key images are imported, etc.

**Comment by jeffro256** [comment]
To keep behavior consistent, we could make an argument `do_refresh_after` and default it to `true`.

**Comment by woodser** [comment]
That sounds ok, though I think we'd want to change the default behavior in monero-wallet-rpc's `import_multisig` call so clients do not have to refresh in order to use this function.

That would lead to the question if the internal default should be false too, considering very few services are hooking into this call directly. But that's an internal implementation detail, as long as clients do not need to refresh.

**Comment by woodser** [comment]
Based on testing, the refresh is necessary or the wallet cannot create txs.
