### ISSUE TITLE
Daemon crashed last night with only a warning

### ISSUE THREAD

**Issue by Column01** [monero-project/monero#9315]
Last night, my daemon crasged with only a warning saying the following:

```
2024-05-02 06:34:11.786	[P2P3]	INFO	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1697	Synced 3139930/3139930
2024-05-02 06:53:10.124	[P2P4]	WARNING	ringct	src/ringct/rctOps.cpp:457	ge_frombytes_vartime failed at 457
```

Now when I try to launch the daemon, it just sits at the stage where it would be loading the blockchain for a long time.

`Monero 'Fluorine Fermi' (v0.18.3.3-release)` is the version I'm using

**Comment by selsta** [comment]
How long did you wait after launch?

**Comment by Column01** [comment]
It's been almost 20 mins and the console has done nothing else, resource usage shows that it hasn't even tried to read the disk as far as I can really tell

**Comment by Column01** [comment]
The disk still works, I have media on there I can still stream just fine, its not an IO issue either as this machine has nothing else running at the moment

**Comment by Column01** [comment]
Can confirm, IOTop doesn't show the daemon doing any disk access

**Comment by Column01** [comment]
OK it is verifying transactions. spamming the console with a lot of:

```
2024-05-02 16:36:42.734 I Transaction added to pool: txid <dd3fb300aa6ad4095319e1ce59b90b08c38a63ef4cd10cdefe9a2bc324e7fc3e> weight: 101187 fee/byte: 80000, count: 338
2024-05-02 16:36:42.773 D Removing tx <0f19390354b694ee7774356757f2b0f85f5af1ab838b07b141812290172a323f> from tx pool, but it was not found in the map of added txs
2024-05-02 16:36:42.773 D Transaction removed from pool: txid <0f19390354b694ee7774356757f2b0f85f5af1ab838b07b141812290172a323f>, total entries in removed list now 339
2024-05-02 16:36:42.773 D Using 0.000000019000/byte fee
2024-05-02 16:36:42.773 D Mixin: 15-15
```

**Comment by Column01** [comment]
Its using 250% CPU according to htop so it is actually doing stuff

**Comment by Column01** [comment]
So I also mistitled it, I checked the log and it did close the daemon, not freeze. I also have ZMQ enabled like this issue: https://github.com/monero-project/monero/issues/8897, could it be related?

**Comment by selsta** [comment]
How much RAM does your machine have? Did it get killed for OOM or crash?

**Comment by Column01** [comment]
16GB of RAM, wasn't anywhere close to full. My virtual memory was at 91% though since its only a gig

**Comment by Column01** [comment]
OK it was able to resync properly. I guess ill wait to see if it crashes again and try to get you more info if I can

**Comment by selsta** [comment]
It's still not clear to me if it ran out of memory, or if it crashed. I have seen RAM usage spikes on my node in some specific situations that caused my node to OOM.

**Comment by selsta** [comment]
Just checked one of my nodes, around the same time one of my nodes also ran out of memory. What you are reporting is not a crash, though it would be nice if someone could investigate what casues this RAM spike.

**Comment by Column01** [comment]
> Just checked one of my nodes, around the same time one of my nodes also ran out of memory. What you are reporting is not a crash, though it would be nice if someone could investigate what casues this RAM spike.

That is very odd indeed. No other processes were affected

**Comment by selsta** [comment]
Let's continue here #9315

**Comment by Column01** [comment]
The issue you linked is this one

**Comment by selsta** [comment]
https://github.com/monero-project/monero/issues/9317
