### ISSUE TITLE
aggregating multisig partial signatures

### ISSUE THREAD

**Issue by SepehrDamavandi** [monero-project/monero#9318]
I ran a M/N multi signature account locally. From what I noticed, there is no aggregation command in cli-wallet or RPC to aggregate partial signatures and the process of finalizing transactions has a sequential order.  Alice who generates the transaction needs to send it to Bob, Bob needs to sign and pass to Carol and so on, until the transaction is signed by the threshold size and ready to be submitted. Are there any commands or RPC API for Alice to be able to gather all the signatures from collaborators and aggregate them to make and submit the final transaction? In other words, I want the process to be done not in sequential order but in parallel. 
Also, I noticed that there is a maximum limit(16) on signer numbers participating in the multisig account. You have mentioned that in order to be able to support more signers efficiently, the key exchange phase should be done FROST style. Is there an implementation of this? how can I remove the limit of signers?

**Comment by SepehrDamavandi** [comment]
Is it even possible to aggregate partial signatures from one wallet? or should it have this sequential order?

**Comment by SepehrDamavandi** [comment]
ANYONE?

**Comment by selsta** [comment]
@UkoeHB can you answer this?

**Comment by SepehrDamavandi** [comment]
@UkoeHB Do you have an implementation of this aggregation-style for CLSAG?

**Comment by SepehrDamavandi** [comment]
Thank you, @UkoeHB I appreciate it.

Is it true that changing the key aggregation style from MuSig2 to FROST would require changings in the wallet functions that handle multisig operations?  or are they both endup with each participant having `N - M + 1` private keys? 

And about the Seraphis library, does it provide the siggnature aggregation command through RPC API?
