### ISSUE TITLE
Cannot connect wallet client to daemon

### ISSUE THREAD

**Issue by dev-warrior777** [monero-project/monero#9320]
> Similar issue: #8156

Started 2 connected `regtest` nodes on localhost and trying to start the wallet client and receiving the same exception as above `Exception at while refreshing, what=no connection to daemon
` 

```
+ monerod --detach --pidfile=/home/dev/dextest/xmr/alpha/monerod.pid --regtest --data-dir=/home/dev/dextest/xmr/alpha --config-file=/home/dev/dextest/xmr/alpha/alpha.conf --no-igd --no-zmq --hide-my-port --p2p-bind-ip 127.0.0.1 --p2p-bind-port 48080 --rpc-bind-ip 127.0.0.1 --rpc-bind-port 48081 --add-exclusive-node 127.0.0.1:58080 --fixed-difficulty 1 --disable-rpc-ban --log-level 1
2024-05-06 19:05:59.454	I Monero 'Fluorine Fermi' (v0.18.3.3-release)
2024-05-06 19:05:59.454	I Moving from main() into the daemonize now.
Forking to background...
+ sleep 5
+ monerod --detach --pidfile=/home/dev/dextest/xmr/beta/monerod.pid --regtest --data-dir=/home/dev/dextest/xmr/beta --config-file=/home/dev/dextest/xmr/beta/beta.conf --no-igd --no-zmq --hide-my-port --p2p-bind-ip 127.0.0.1 --p2p-bind-port 58080 --rpc-bind-ip 127.0.0.1 --rpc-bind-port 58081 --add-exclusive-node 127.0.0.1:48080 --fixed-difficulty 1 --disable-rpc-ban --log-level 1
2024-05-06 19:06:04.568	I Monero 'Fluorine Fermi' (v0.18.3.3-release)
2024-05-06 19:06:04.568	I Moving from main() into the daemonize now.
Forking to background...
+ monero-wallet-rpc --daemon-address 127.0.0.1:58081 --rpc-bind-ip 127.0.0.1 --rpc-bind-port 28884 --log-file=/home/dev/dextest/xmr/wallets/fred-wallet-rpc.log --disable-rpc-login --allow-mismatched-daemon-version --wallet-dir /home/dev/dextest/xmr/wallets
This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly.

Monero 'Fluorine Fermi' (v0.18.3.3-release)
Logging to /home/dev/dextest/xmr/wallets/fred-wallet-rpc.log


```

_Originally posted by @dev-warrior777 in https://github.com/monero-project/monero/issues/8156#issuecomment-2096723462_

**Comment by dev-warrior777** [comment]
Note the wallet client RPC does not accept `--regtest` parameter

I am building a dev tool to further develop Monero <-> Decred atomic swaps

The requirements are:
1. 2 connected local net nodes
2. Manual mining
3. 2 or more wallets

Thanks

**Comment by selsta** [comment]
Did you try getting it working with a single node and single wallet first? If not, can you try to get this working first with minimal flags (no `--regtest`), and then add back your requirements until it fails.

**Comment by dev-warrior777** [comment]
Thanks for reply. I will definitely go that route today. 

Actually 1 & 2 above are already working - 2 connected nodes with manual mining on regtest. Just no wallets connecting. I specifically use `--no-zmq` on the nodes .. _could that be a reason_? The wallet does not seem to be able to find a node even when given one explicitly `--daemon-address 127.0.0.1:58081`

Thanks again

**Comment by selsta** [comment]
`--no-zmq` should be unrelated for just regular wallets connecting

**Comment by dev-warrior777** [comment]
Ok, thank you.
I made good progress today with your suggestions, appreciated

Please close this issue.

**Comment by dev-warrior777** [comment]
If I can ride another question before closing: arestakenet coins different than testnet coins?

**Comment by selsta** [comment]
Stagenet and testnet are different, yes.

Stagenet is for testing your mainnet application, while on testnet we often test new protocol featurea early.

**Comment by dev-warrior777** [comment]
Ok, thanks .. let's close this issue.

**Comment by dev-warrior777** [comment]
Closed, thanks
