### ISSUE TITLE
Unified Code Issue with German seed letters on Windows

### ISSUE THREAD

**Issue by Mordoch** [monero-project/monero#938]
Hi,
I found an issue that occurs only on Windows. If a seed is created with German word that contain ä/ü/ö then, the letters are appear as ä=├ñ, ö= ├Â, ü= ├╝. There is no problem with that on Linux. 
So if you try to import a wallet created on Linux with a seed word "Müll" then "Müll" won't work on Windows and you must use "M├╝ll"
Good Luck!

**Comment by moneromooo-monero** [comment]
Looks like 6 extra bytes, assuming copy/pasting did not lose any information. Do you know if your terminal supports UTF-8 ? IIRC, Windows uses UTF-16 by default (and lower endian to boot).

**Comment by Mordoch** [comment]
I am sorry, not an expert. I just used the standard Windows "cmd" terminal. Don't know wether it supports UTF-8 or 16... What I know is that I did copy and past my seed. I typed every single letter ;-).

**Comment by dEBRUYNE-1** [comment]
+bug
