### ISSUE TITLE
Prouver un transfert 

### ISSUE THREAD

**Issue by Jojosig** [monero-project/monero#9401]
J'ai transféré des monero mais je pense que le montant était insuffisant ! Comme je peux les récupérer ?

**Comment by Jojosig** [comment]
I transferred some monero but I think the amount was not enough! How can I get them back? 
![Screenshot_20240716_054040_Kraken](https://github.com/user-attachments/assets/9a65757a-4f90-43cf-b6c1-ac51ec1d6ba8)

**Comment by Jojosig** [comment]
But how can I send him proof that I made the transfer?

**Comment by selsta** [comment]
Copy the value that is under "Identifiant de transaction on-Chain"

**Comment by 0xFFFC0000** [comment]
@Jojosig hope this answers your question. If you have any other problem feel free to reopen this issue, otherwise I am closing this issue.
