### ISSUE TITLE
[GUI][Restore wallet] 'Create wallet' stays disabled until monero-wallet-gui is closed

### ISSUE THREAD

**Issue by b4n6-b4n6** [monero-project/monero#9449]
Kindly observe video @ 00:37 where 'Create wallet' button stays disabled even though mnemonic seed has been corrected
[restore-bug-2.webm](https://github.com/user-attachments/assets/f611803b-65d8-4a3a-87e8-c0b78dbed754)

**Comment by selsta** [comment]
It says "Electrum style seed verification failed", which means the seed is invalid. That's why it is grayed out.

**Comment by b4n6-b4n6** [comment]
It stays grayed out after I have corrected the seed, please observe 00:34

**Comment by selsta** [comment]
Sorry, not sure how I missed that! Seems like a valid report. Can you re-open it here?

https://github.com/monero-project/monero-gui/issues

**Comment by selsta** [comment]
Continuing in GUI repo.
