### ISSUE TITLE
Hardfork V3 not defined in testnet 

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#946]
Can you add information when switch version 3 on testnet .

Thanks,

**Comment by perl5577** [comment]
HardFork V3: 25 days from now

**Comment by moneromooo-monero** [comment]
Probably a week after ringct is merged.
On mainnet, the fork is in ~47 days. You're probably counting with 1 minute blocks still.

**Comment by perl5577** [comment]
shits  is true :) 

I hope information is present before 3 week for make complete test before fork.

**Comment by NanoAkron** [comment]
Is this issue still live or can it be closed?

**Comment by luigi1111** [comment]
It is donezo.
