### ISSUE TITLE
transfert de xmr de la plateforme Binance à la plateforme monero gui

### ISSUE THREAD

**Issue by Diad28** [monero-project/monero#9468]
Bonjour j'ai effectué un transfert de la plateforme Binance a la plateforme monero mais il y 'a rien qui s'affiche pouvez vous m'aider svp.

**Comment by Diad28** [comment]
assez urgeng merci

**Comment by plowsof** [comment]
https://www.binance.com/en/support/announcement/binance-will-delist-ant-multi-vai-xmr-on-2024-02-20-f73b083ba6834771b07dbe5319917ae5

- Deposits of these token(s) after 2024-02-21 03:00 (UTC) will not be credited to your account. 

- Withdrawals of these token(s) from Binance will not be supported after 2024-05-20 03:00 (UTC).

- Delisted tokens may be converted into stablecoins on behalf of users after 2024-05-21 03:00 (UTC). Please note that the conversion of delisted tokens into stablecoins is not guaranteed

Please close, wrong place for this issue

**Comment by Diad28** [comment]
Bonjour, 
j'ai parler avec le support binance il m'on dit que la transaction a bien eu lieu sur la plateorme monero gui voici la preuve[
](https://xmrchain.net/tx/4898c78a7a77b41bccd0997a4f7e416f2e1a91ffb3b46cd33555d54c4b743e54)

**Comment by Diad28** [comment]
https://xmrchain.net/tx/4898c78a7a77b41bccd0997a4f7e416f2e1a91ffb3b46cd33555d54c4b743e54

**Comment by Diad28** [comment]
je suis au courant de ce probleme mais je possédais toujours des monero et je pouvais toujours faires des envoie .

**Comment by Diad28** [comment]
je vous envoie en copie ce que le support de binance m'as envoye

**Comment by Diad28** [comment]
Vous me dites que c'est pas le bon endroit pour ce genre de problème  vers qui je dois m'adresser svp

**Comment by Diad28** [comment]
est ce que il ya une personne plus compétente a qui je peux m'adresser
