### ISSUE TITLE
Help Recover wallet

### ISSUE THREAD

**Issue by error0x1337** [monero-project/monero#9472]
Hey there, can i restore the wallet if i have only these files (username username.keys username.old_cache) i lost the password. thanks

**Comment by 0xFFFC0000** [comment]
I don't think that is possible. I will wait for further comments to help you from other community member. Otherwise this issue can be closed.

**Comment by selsta** [comment]
As far as I know, Feather Wallet has a tool integrated to crack wallet passwords. Try looking into that. Otherwise this isn't something we can help with.
