### ISSUE TITLE
comment contacter le service client de la plateforme monero Gui svp?

### ISSUE THREAD

**Issue by Diad28** [monero-project/monero#9474]
J'aimerais rentrer en contacte avec le service client de la plateforme monero car j'ai un probleme .

**Comment by SyntheticBird45** [comment]
Bonjour @Diad28,

Je suis au regret de vous annoncez qu'il n'y a pas de service client Monero. C'est un project communautaire, entretenue par des bénévoles. La platforme Github est une plateforme pour développeurs. La fonctionnalité que vous avez utilisé ici est normalement reservé au rapport de bug dans le logiciel Monero.

Cependant ce n'est pas la première fois que quelqu'un se trompe et je pense qu'il est possible de continuer la discussion ici. Décrivez votre problème en details, je me chargerai de le traduire en anglais pour quiconque souhaite apportez son aide dans la discussion.

**Comment by selsta** [comment]
Please open issues in English, if you don't speak English well please use Google Translate.

**Comment by Diad28** [comment]
I sent monero from the binance platform to monero gui but I'm not getting anything. I contacted binance support and they sent me a link to the blockchain to confirm that the monero transfer had gone through. I don't understand anything anymore, maybe I'm using the monero gui application wrong.

**Comment by selsta** [comment]
When was this? Binance has removed Monero support many months ago.
