### ISSUE TITLE
first use dialog: recommend tor for anonymous transactions

### ISSUE THREAD

**Issue by milahu** [monero-project/monero#9476]
XMR noobs can have the false expectation that "XMR is anonymous"
but **anonymous XMR transactions require tor** to connect to other XMR nodes

`monero-wallet-gui` should make this more transparent

first impression of `monero-wallet-gui` ...

1. add desktop entry: no
1. set language: english
1. mode selection: simple mode
1. about the simple mode: [skip the fine print](https://en.wikipedia.org/wiki/HumancentiPad), ok, next
1. create a new wallet
1. ...

currently, the `about the simple mode` dialog says

[monero-gui/wizard/WizardModeRemoteNodeWarning.qml](https://github.com/monero-project/monero-gui/raw/master/wizard/WizardModeRemoteNodeWarning.qml)

<blockquote>

About the simple mode

This mode is ideal for managing small amounts of Monero. You have access to basic features for making and managing transactions. It will automatically connect to the Monero network so you can start using Monero immediately.

Remote nodes are useful if you are not able/don't want to download the whole blockchain, but be advised that malicious remote nodes could compromise some privacy. They could track your IP address, track your "restore height" and associated block request data, and send you inaccurate information to learn more about transactions you make.

Remain aware of these limitations. <b>Users who prioritize privacy and decentralization must use a full node instead</b>.

`[ ]` I understand the privacy implications of using a third-party server.

</blockquote>

### what is wrong

> This mode is ideal for managing small amounts of Monero.

this first sentence is misleading.
focus should be: disk space.
disk space is the biggest difference to "advanced mode" (full node).

"simple mode is better for small amounts" implies
that the remote node could steal coins (is that true?)

> be advised that malicious remote nodes could compromise some privacy.

this part should be in bold font.
the whole dialog has too much text, so new users may [skip reading](https://en.wikipedia.org/wiki/HumancentiPad)...

> the whole dialog has too much text

i would prefer less text with expandable details sections
example:

<blockquote>

About the simple mode

Pros:

<details>
<summary>
Less disk space. Faster first use.
</summary>

Simple mode is useful if you are not able (or do not want) to download the full blockchain.

Simple mode works by using the full blockchain on someone else's computer.

The full blockchain was about xxx GiB on 2024-09-12,
and grows by about xxx MiB every day.
Running a full node means that you must download the full blockchain
before you can start using Monero.

Simple mode will automatically connect to the Monero network
so you can start using Monero immediately.

</details>

Cons:

<details>
<summary>
Less privacy.
</summary>

Malicious remote nodes can compromise your privacy.

Malicious remote nodes can

- track your IP address (to de-anonymize your transactions)
- track your "restore height" and associated block request data
- send you inaccurate information to learn more about transactions you make

Fix 1: Connect via Tor.
All these risks can be reduced by using Tor as proxy.
Tor is not perfect, but better than nothing.
TODO explain how to connect via tor

Fix 2: Run a full node and connect via Tor.
Users who prioritize privacy and decentralization should run a full node.

</details>

<details>
<summary>
No advanced features.
</summary>

In the simple mode, you have access to basic features for making and managing transactions.
TODO what advanced features are missing in simple mode?

</details>

`[ ]` I understand the privacy implications of using a third-party server.

</blockquote>

> Users who prioritize privacy and decentralization must use a full node instead

this is one of two possible solutions.
using "simple mode" over tor should be "good enough" for most users.
running a full node behind tor requires more system resources, mostly disk space.

> if you are not able/don't want to download the whole blockchain

offtopic:
this sentence should have an estimated size of the full blockchain
example:
the full blockchain (about xxx GiB on 2024-09-12)

**Comment by selsta** [comment]
please reopen the issue here https://github.com/monero-project/monero-gui

**Comment by milahu** [comment]
moved to https://github.com/monero-project/monero-gui/issues/4352
