### ISSUE TITLE
This wallet is multisig, and multisig is disabled on exchange_multisig_keys

### ISSUE THREAD

**Issue by zbder** [monero-project/monero#9488]
I am trying to create a new wallet and make it run a few multisig  commands using rpc but i cant get beyond this point.

`Code`
> $createResult = make_multisig_request('create_wallet', [
    'filename' => $walletName,
    'password' => $walletPass,
    'language' => 'English'
]);
$createResult = make_multisig_request('open_wallet', [ 'filename' => $walletName, 'password' => $walletPass ]);
$prepareMultisig = make_multisig_request('prepare_multisig');
$prepareMultisig = json_decode($prepareMultisig, true);
$myMultisigKey = $prepareMultisig['result']['multisig_info'];
$makeMultisig = make_multisig_request('make_multisig', [
    'threshold' => 2,
    'password' => $walletPass,
    'multisig_info' => [
        'Example from second party',
        'Example from third party'
    ]
]);
// Until here it works super fine but on exchange_multisig_keys i get the error message listed below
$makeMultisig = make_multisig_request('exchange_multisig_keys', [
     'multisig_info' => [
        'Example from second party',
        'Example from third party'
    ]
]);

"This wallet is multisig, and multisig is disabled. Multisig is an experimental feature and may have bugs. Things that could go wrong include: funds sent to a multisig wallet can't be spent at all, can only be spent with the participation of a malicious group member, or can be stolen by a malicious group member. You can enable it by running this once in monero-wallet-cli: set enable-multisig-experimental 1"

When i manually run "monero-wallet-cli: set enable-multisig-experimental 1", it also allows me to use the command without issues but i seemingly cannot make it working without manually running it, when i use shell_exec or a bash script it says the .keys file would be used by another programm - when i run it manually it works fine. I also cannot set that from rpc, also tried to run close_wallet from rpc before but it doesnt work either. Also tried to add enable-multisig-experimental=1 in the monerod.conf which seems to have no effect and also tried this "Wallet: disable multisig by default, enable with --enable-multisig-experimental (#[8328](https://github.com/monero-project/monero/pull/8328))" but seemingly it does not exist in 0.18.3.4 anymore and i have no idea how to bypass this issue anymore - did anyone make the same experience and may have a helpful hint for me ?

**Comment by zbder** [comment]
Solved it.

**Comment by 0xFFFC0000** [comment]
> Solved it.

I would appreciate it if in your spare time write how you solved it, in case later someone founds this page.
