### ISSUE TITLE
simplewallet --restore-deterministic-wallet isn't detecting past transactions

### ISSUE THREAD

**Issue by mmortal03** [monero-project/monero#950]
Restoring from deterministic seed isn't detecting any past transactions. MoneroMooo's theory from the bitcointalk thread is that this may be happening because "simplewallet now skips refresh till the block the wallet was created, so there must be a bug that makes it think it doesn't need to refresh those early blocks."

Steps to reproduce:
 
Run simplewallet --restore-deterministic-wallet
pick a wallet file name 
pick a password
Enter an Electrum seed that represents an address with past transactions (you can use the one below)
Let simplewallet scan for past transactions.

Bug: After scanning, no transaction history will be found, and the balance will display as zero, even if the wallet actually has a current balance. Running refresh, rescan_bc, etc. don't help. 

You can use the following seed to reproduce the issue:

toilet zeal lion cafe circle ruthless inkling were dauntless jogger custom lagoon suddenly bays torch pager uttered react nurse cause aphid vulture bounced civilian lagoon

This had past transactions that began at block 1088432.

**Comment by hyc** [comment]
What git rev did you build from?

**Comment by mmortal03** [comment]
Originally (From July 8th): https://github.com/monero-project/bitmonero/commit/18dd50702407ece54a98563921fa744c6b7c15b2

As well as the current revision: https://github.com/monero-project/bitmonero/commit/0fbe9cfcdb9df2b141024eec04c3c7412791b741

**Comment by mmortal03** [comment]
Meaning, it must have become broken before July 8th.

**Comment by luigi1111** [comment]
mmortal03, this patch fixes these issues for me (I was able to reproduce the behavior you experienced).

**Comment by mmortal03** [comment]
Thanks @luigi1111 , I've just finished testing @hyc 's "better fix", and it does seem to fix the problem: https://github.com/monero-project/bitmonero/pull/952/commits/709c7247cd525952e89c4b8975171152a3969d92

**Comment by mmortal03** [comment]
The fix was merged soon after the above was tested, so I'm closing this.
