### ISSUE TITLE
[Bug Report] Windows, database_size field from get_info is 0

### ISSUE THREAD

**Issue by Cyrix126** [monero-project/monero#9513]
On Windows at least 10 & 11, the method "get_info" of the endpoint /json_rpc will always have a value of 0 on field "database_size".

To reproduce:

1. Start monerod without any args on a Windows system.
2. execute in cmd:
 `curl -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_info\"}" http://127.0.0.1:18081/json_rpc`
3.  See the field "database_size"
`"database_size": 0,`

**Comment by jeffro256** [comment]
I don't have a windows machine on me, but could you try compiling PR #9514 please and see if it fixes the issue?

**Comment by Cyrix126** [comment]
@jeffro256 Now it shows this value without changing: 18446744072227688448, so 18.446EB

**Comment by iamamyth** [comment]
@Cyrix126 Can you compile https://github.com/iamamyth/monero/commit/57e651219a1faaf3ce20478015592df23db49800 and see if it fixes your issue?

**Comment by Cyrix126** [comment]
It's now returning the correct size.
Thanks !

**Comment by jeffro256** [comment]
@iamamyth Can you open PRs for that please?
