### ISSUE TITLE
create cmake and make should fallback to system packages for projects in /external

### ISSUE THREAD

**Issue by solomoncyj** [monero-project/monero#9561]
In packaging, this will stop conflicts with system packages. moreover, some distrols, eg fedora, do not allow us to use static libs and or vendor 3rd party libs

**Comment by hyc** [comment]
None of the code in external/ is packaged or installed on its own, so that all seems irrelevant. liblmdb and randomx in external/ certainly cannot rely on a system package anyway.

**Comment by solomoncyj** [comment]
ye s, but for packages like trezor-common, rapid json,  and other submodule execpt for supercop are already in package managers

**Comment by solomoncyj** [comment]
> None of the code in external/ is packaged or installed on its own, so that all seems irrelevant. liblmdb and randomx in external/ certainly cannot rely on a system package anyway.

why cant they?
[randomx](https://packages.fedoraproject.org/pkgs/randomx/randomx/index.html)
[lmdb](https://packages.fedoraproject.org/pkgs/lmdb/lmdb/index.html)

**Comment by solomoncyj** [comment]
please prefer `find_packag` (if it's a normally CMake installed package) and only conditionally `add_subdirectory(external)`.

**Comment by hyc** [comment]
No. The issue you're reporting doesn't exist. There are no components of external/ that are installed, therefore there cannot be any conflicts with distro package managers. This ticket is invalid.

**Comment by hyc** [comment]
No. The issue you're reporting doesn't exist. There are no components of external/ that are installed, therefore there cannot be any conflicts with distro package managers. This ticket is invalid.

> > None of the code in external/ is packaged or installed on its own, so that all seems irrelevant. liblmdb and randomx in external/ certainly cannot rely on a system package anyway.
> 
> why cant they? [randomx](https://packages.fedoraproject.org/pkgs/randomx/randomx/index.html) [lmdb](https://packages.fedoraproject.org/pkgs/lmdb/lmdb/index.html)

Monero builds LMDB with non-default compile options. Distro packages are not compatible.
RandomX is consensus-critical, you would have to be stupid or insane to trust someone else's build of it.

All of the components in external/ are at known specific versions. This is a requirement for both reliability and reproducibility.
