### ISSUE TITLE
Where is monero-source-v0.18.3.4.tar.bz2?

### ISSUE THREAD

**Issue by halcyonseeker** [monero-project/monero#9597]
I downloaded the gzipped v0.18.3.4 source tarball linked on [the release page](https://github.com/monero-project/monero/releases/tag/v0.18.3.4).  Per the instructions for security verification, I also downloaded the [list of hashes](https://www.getmonero.org/downloads/hashes.txt).  This file contains sha256sums for number of v0.18.3.4 files, but the only source release (I assume corresponding to the code in this repo) is monero-source-v0.18.3.4.tar.bz2 — it's not in the same compression format as the v0.18.3.4 source tarball in the release.  I tried converting the source tarball from gzip to bzip2 with `gunzip < v0.18.3.4.tar.gz | bzip2 > v0.18.3.4.tar.bz2` but the sha256 checksum still didn't match the one in the file for monero-source-v0.18.3.4.tar.bz2.

Where is the source release of the latest version of Monero and how do I verify its integrity?

**Comment by selsta** [comment]
You can download it here: https://www.getmonero.org/downloads/

The source tarball that is generated by GitHub is incomplete, it's not something we can turn off as far as I am aware.
