### ISSUE TITLE
Instead of Ring multisignatures, why not use multiparty computation for increased privacy?

### ISSUE THREAD

**Issue by ChristopherKing42** [monero-project/monero#971]
The plan is currently that multisig will be implemented via ring multisignatures.

Multisig transactions and accounts will be able to be distinguished from non-multisig by looking at the blockchain. Also, the nature of the multisig wallet (the number of participants and the threshold) would be apparent. (Is this paragraph correct?)

Therefore, I propose that multiparty computation is used instead, as described [here](http://monero.stackexchange.com/questions/782/can-you-have-a-multsig-wallet-with-the-current-monero-protocol).

It would make multisig addresses indistinguishable from regular addresses. They would also be the same size as regular addresses as a corollary (in terms of what needs stored on the blockchain).

Moreover, this does not require any changes to consensus code, and is compatible with RingCT.

**Comment by moneromooo-monero** [comment]
>  (Is this paragraph correct?)

As far as I know, it is not.

If you are the person who devised another way to do multisig, you may want to discuss this with Shen Noether, so that any pros and cons of various methods may be compared. Ask fluffypony if so.

**Comment by ChristopherKing42** [comment]
Where can I contact Shen Noether?

**Comment by luigi1111** [comment]
This "ring multisignature" that has been proposed (I think by tacotime originally) *is* a multiparty computation. Basically what you describe (AFA being indistinguishable, etc). I believe the RingCT version will be similar.

**Comment by ChristopherKing42** [comment]
Oh, okay. Sorry. (I should have studied it closer.)
