### ISSUE TITLE
Readline support in the command-line tool simplewallet

### ISSUE THREAD

**Issue by aalex** [monero-project/monero#987]
The users would find it easier to use the command-line tool if the code was using readline.
- control-A to move to the beginning of the line
- up/down arrow to navigate through history
- control-C to cancel a line (instead of cancelling a foreground refresh and/or exit without saving)
- control-D to quit
- etc.

**Comment by radfish** [comment]
Agreed. As a temporary crutch: https://github.com/monero-project/bitmonero#using-readline

**Comment by moneromooo-monero** [comment]
+resolved
